---
sidebar: sidebar
permalink: ontap-security-hardening/autonomous-ransomware-protection.html
keywords: tr-4569, ontap hardening guide, security, ARP, fpolicy, UBA, ransomware, machine learning, volume workloads, entropy
summary: "ONTAP's on-box machine learning capability detects ransomware based on volume workloads and entropy."
---
= ONTAP autonomous ransomware protection
:hardbreaks:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
To supplement user behavior analytics for Storage Workload Security, the ONTAP autonomous ransomware protection analyzes volume workloads and entropy to detect ransomware and takes a snapshot and notifies the administrator when an attack is suspected.

In addition to ransomware detection and prevention using external FPolicy user behavioral analytics (UBA) with NetApp Cloud Insights / Cloud Secure and the NetApp FPolicy partner ecosystem, ONTAP 9.10.1 introduces autonomous ransomware protection. ONTAP autonomous ransomware protection uses a built-in on-box machine learning (ML) capability that looks at volume workload activity plus data entropy to automatically detect ransomware. It monitors for activity that is different from UBA so that it can detect attacks that UBA does not.

For more detailed information about this capability, see link:../ransomware-solutions/ransomware-overview.html[NetApp solutions for ransomware^] or link:../anti-ransomware/use-cases-restrictions-concept.html[ONTAP autonomous ransomware protection documentation^].

//6-24-24 ontapdoc-1938
