---
sidebar: sidebar
permalink: ontap-security-hardening/snapshot-copy-locking.html
keywords: tr-4569, ontap hardening guide,security, snapshot copy locking, tamper-proof snapshot, tamperproof, tamper proof
summary: "Snapshot copy locking prevents Snapshot deletion using SnapLock technology."
---
= Snapshot copy locking
:hardbreaks:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
Snapshot copy locking is a SnapLock capability where Snapshot copies are rendered indelible manually or automatically with a retention period on the volume Snapshot policy. The purpose of Snapshot copy locking is to prevent rogue or untrusted administrators from deleting Snapshots on primary or secondary ONTAP system.

Snapshot copy locking was introduced in ONTAP 9.12.1.  Snapshot copy locking is also referred to as tamper-proof Snapshot locking. Although it does require the SnapLock license and initialization of the compliance clock, Snapshot copy locking is unrelated to SnapLock Compliance or SnapLock Enterprise. There is no trusted storage administrator, as with SnapLock Enterprise and it does not protect the underlying physical storage infrastructure, as with SnapLock Compliance.  This is an improvement over SnapVaulting Snapshot copies to a secondary system. Rapid recovery of locked Snapshots on primary systems can be achieved to restore volumes corrupted by ransomware.

For more details on Snapshot copy locking, see the link:../snaplock/snapshot-lock-concept.html[ONTAP documentation].

//6-24-24 ontapdoc-1938