---
sidebar: sidebar
permalink: ontap-security-hardening/snapshot-copy-locking.html
keywords: tr-4569, ontap hardening guide,security, snapshot copy locking, tamper-proof snapshot, tamperproof, tamper proof
summary: "Snapshot locking prevents Snapshot deletion using SnapLock technology."
---
= Snapshot locking
:hardbreaks:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Snapshot locking is a SnapLock capability where Snapshot copies are rendered indelible manually or automatically with a retention period on the volume Snapshot policy. The purpose of snapshot locking is to prevent rogue or untrusted administrators from deleting Snapshots on primary or secondary ONTAP system.

Snapshot locking was introduced in ONTAP 9.12.1. Snapshot locking is also referred to as tamper-proof snapshot locking. Although it does require the SnapLock license and initialization of the compliance clock, snapshot locking is unrelated to SnapLock Compliance or SnapLock Enterprise. There is no trusted storage administrator, as with SnapLock Enterprise and it does not protect the underlying physical storage infrastructure, as with SnapLock Compliance. This is an improvement over SnapVaulting Snapshot copies to a secondary system. Rapid recovery of locked Snapshots on primary systems can be achieved to restore volumes corrupted by ransomware.

For more details on snapshot locking, see the link:../snaplock/snapshot-lock-concept.html[ONTAP documentation].

//6-24-24 ontapdoc-1938