---
sidebar: sidebar
permalink: authentication-access-control/webauthn-mfa-overview.html
keywords: mfa, multi-factor, authentication, authorization, webauthn, FIDO2, hardware key
summary: Beginning with ONTAP 9.16.1, you can enable WebAuthn MFA for ONTAP users.
---

= WebAuthn MFA overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP 9.16.1, administrators can enable WebAuthn multi-factor authentication (MFA) for users that log in to System Manager. This enables System Manager logins using a FIDO2 key (such as a YubiKey) as a second form of authentication. By default, WebAuthn MFA is disabled for new and existing ONTAP users. 

// Audience for this feature is admins.  People logging in to System Manager will also be admins.

WebAuthn MFA is supported for users and groups that use the following types of authentication for the first authentication method:

* Users: password, domain, or nsswitch
* Groups: domain or nsswitch

After you enable WebAuthn MFA as the second authentication method for a user, the user is asked to register their hardware FIDO2 device upon logging in to System Manager. This registration is handled by their local operating system. After registration, the passkey is stored in ONTAP.

NOTE: Users that have WebAuthn MFA enabled as a second authentication method need to use the FQDN (for example https://myontap.example.com) instead of the IP address (for example https://192.168.100.200) to access System Manager. For users with WebAuthn MFA enabled, attempts to log in to the System Manager using the IP address are rejected.

//If you are using dynamic authorization, further authentication challenges can also use WebAuthn MFA for those users. (not supported for 9.16.1)