---
permalink: s3-config/configure-access-ldap.html
sidebar: sidebar
keywords: tr-4814, generate, ldap, s3, access keys, secret keys using API
summary: "Keys for accessing S3 clients can be regenerated by S3 users by using API."
---

= Configure external directory services for ONTAP S3 access
:icons: font
:imagesdir: ../media/
:hardbreaks-option:

[.lead]
Beginning with ONTAP 9.14.1, services for external directories have been integrated with ONTAP S3 object storage. This integration simplifies user and access management through external directory services.

You can provide user groups belonging to an external directory service with access to your ONTAP object storage environment. Lightweight Directory Access Protocol (LDAP) is an interface for communicating with directory services, such as Active Directory, that provide a database and services for identity and access management (IAM). To provide access, you need to configure LDAP groups in your ONTAP S3 environment. After you have configured access, the group members have permissions to ONTAP S3 buckets. For information about LDAP, see link:../nfs-config/using-ldap-concept.html[Learn about using LDAP name services on ONTAP NFS SVMs].

You can also configure Active Directory user groups for fast bind mode, so that user credentials can be validated and third-party and open-source S3 applications can be authenticated over LDAP connections.

.Before you begin
Ensure the following before configuring LDAP groups and enabling the fast bind mode for group access:

. An S3-enabled storage VM containing an S3 server has been created. See link:../s3-config/create-svm-s3-task.html[Create an SVM for S3].
. A bucket has been created in that storage VM. See link:../s3-config/create-bucket-task.html[Create a bucket].
. DNS is configured on the storage VM. See link:../networking/configure_dns_services_auto.html[Configure DNS services].
. A self-signed root certification authority (CA) certificate of the LDAP server is installed on the storage VM. See link:../nfs-config/install-self-signed-root-ca-certificate-svm-task.html[Install the self-signed root CA certificate on the SVM].
. An LDAP client is configured with TLS enabled on the SVM. See link:../nfs-config/create-ldap-client-config-task.html[Create LDAP client configurations for ONTAP NFS access] and link:../nfs-config/enable-ldap-svms-task.html[Associate LDAP client configurations with ONTAP NFS SVMs for information].

== Configure S3 access for LDAP

. Specify LDAP as the _name service database_ of the SVM for the group and password to LDAP:
+
----
ns-switch modify -vserver <vserver-name> -database group -sources files,ldap
ns-switch modify -vserver <vserver-name> -database passwd -sources files,ldap
----
+
Learn more about the link:https://docs.netapp.com/us-en/ontap-cli/vserver-services-name-service-ns-switch-modify.html[`vserver services name-service ns-switch modify`^] command in the ONTAP command reference.

. Create an object store bucket policy statement with the `principal` set to the LDAP group to which you want to grant access:
+
----
object-store-server bucket policy statement create -bucket <bucket-name> -effect allow -principal nasgroup/<ldap-group-name> -resource <bucket-name>, <bucket-name>/*
----
+
Example: The following example creates a bucket policy statement for `buck1`. The policy allows access for the LDAP group `group1` to the resource (bucket and its objects) `buck1`.
+  
----
vserver object-store-server bucket policy add-statement -bucket buck1 -effect allow -action
GetObject,PutObject,DeleteObject,ListBucket,GetBucketAcl,GetObjectAcl,ListBucketMultipartUploads,ListMultipartUploadParts, ListBucketVersions,GetObjectTagging,PutObjectTagging,DeleteObjectTagging,GetBucketVersioning,PutBucketVersioning -principal nasgroup/group1 -resource buck1, buck1/*
----
+
.	Verify that a user from the LDAP group `group1` is able to the perform S3 operations from the S3 client.

== Use LDAP fast bind mode for authentication

. Specify LDAP as the _name service database_ of the SVM for the group and password to LDAP:
+
----
ns-switch modify -vserver <vserver-name> -database group -sources files,ldap
ns-switch modify -vserver <vserver-name> -database passwd -sources files,ldap
----
+
Learn more about the link:https://docs.netapp.com/us-en/ontap-cli/vserver-services-name-service-ns-switch-modify.html[`vserver services name-service ns-switch modify`^] command in the ONTAP command reference.

. Ensure that an LDAP user accessing the S3 bucket has permissions defined in the bucket-policies. For more information, see link:../s3-config/create-modify-bucket-policy-task.html[Modify a bucket policy].
. Verify that a user from the LDAP group can perform the following operations:
.. Configure the access key on the S3 client in this format:
`"NTAPFASTBIND" + base64-encode(user-name:password)`
Example: `"NTAPFASTBIND"` + base64-encode(ldapuser:password), which results in 
`NTAPFASTBINDbGRhcHVzZXI6cGFzc3dvcmQ=`
[NOTE]
The S3 client might prompt for a secret key. In the absence of a secret key, any password of at least 16 characters can be entered.
+
.. Perform basic S3 operations from the S3 client for which the user has permissions.

==== Base64 credentials
ONTAP S3's default configuration excludes HTTP and exclusively uses HTTPS and a Transport Layer Security (TLS) connection. ONTAP can generate self-signed certificates, but the recommended best practice is to use certificates from a third-party certificate authority (CA). When you use CA certificates, you create a trusted relationship between client applications and the ONTAP object store server.
 
Be aware that credentials encoded using Base64 are easily decoded. Using HTTPS will prevent encoded credentials from being captured by man-in-the-middle packet sniffers. 

Do not use LDAP fast-bind mode for authentication when creating pre-signed URLs. Authentication is based exclusively on the Base64 access key that is included in the pre-signed URL. The user name and password will be revealed to anyone decoding the Base64 access key.

=== Authentication method is nsswitch and LDAP is enabled example

----
$curl -siku <user>:<user_password> -X POST https://<LIF_IP_Address>/api/protocols/s3/services/<SVM_UUID>/users -d {"comment":"<S3_user_name>", "name":<user>,"<key_time_to_live>":"PT6H3M"}'
----

[NOTE]
Direct the API to the cluster management LIF, not to the SVM's data LIF. If you want to allow users to generate their own keys, you must add HTTP permissions to their role to use curl. This permission is in addition to S3 API permissions.

== Configure S3 access for Active Directory or CIFs servers 
If the nasgroup specified in the bucket policy statement or the users who are part of the nasgroup do not have UID and GID set, lookups fail when these attributes are not found. Active Directory uses SID, not UID. If SID entries cannot be mapped to UID, the necessary data needs to be brought to ONTAP. 

To do so, use link:../authentication/enable-ad-users-groups-access-cluster-svm-task.html[vserver active-directory create] so that the SVM can authenticate with Active Directory and get the necessary user and group information.

Alternatively, use link:../authentication/enable-ad-users-groups-access-cluster-svm-task.html[vserver cifs create] to create a SMB server in an Active Directory domain.

To avoid lookup failures, NetApp recommends using trusted domains for resource authorization in UPN format: `nasgroup/group@trusted_domain.com`

=== Generate keys when the authentication method is domain and trusted domains are configured in Active Directory
Use the `s3/services/<svm_uuid>/users` endpoint with users specified in UPN format. Example:
----
$curl -siku FQDN\\user:<user_password> -X POST https://<LIF_IP_Address>/api/protocols/s3/services/<SVM_UUID>/users -d {"comment":"<S3_user_name>", "name":<user@fqdn>,"<key_time_to_live>":"PT6H3M"}'
----
[NOTE]
Direct the API to the cluster management LIF, not to the SVM's data LIF. If you want to allow users to generate their own keys, you must add HTTP permissions to their role to use curl. This permission is in addition to S3 API permissions.

=== Generate keys when the authentication method is domain and there are no trusted domains

This action is possible when LDAP is disabled or when non-POSIX users have not configured UID and GID. Example:

----
$curl -siku FQDN\\user:<user_password> -X POST https://<LIF_IP_Address>/api/protocols/s3/services/<SVM_UUID>/users -d {"comment":"<S3_user_name>", "name":<user[@fqdn]>,"<key_time_to_live>":"PT6H3M"}'
----
[NOTE]
Direct the API to the cluster management LIF, not to the SVM's data LIF. If you want to allow users to generate their own keys, you must add HTTP permissions to their role to use curl. This permission is in addition to S3 API permissions. You only need to add the optional domain value (@fqdn) to a user name if there are no trusted domains.

// 2025 May 29, ONTAPDOC-2982
// 2025-May-01 Attention to Base64 vulnerabilities
// 27-MAR-2025 ONTAPDOC-2909
// 2025-March 14, Split LDAP and AD into separate sections
// 2025-Jan-15, Additional AD information
// 2024-12-19, ontapdoc-2606
// 2024 Dec-09, ONTAPDOC 2569
// 2024-Nov-26, ONTAPDOC-2569
// 2024-Aug-23, ONTAPDOC-1808
// 2024-7-18 PR-1935
// 2024 may 16, ontapdoc-1986
// 2024 Feb 07, Public PR 1329