---
permalink: s3-config/ontap-s3-validated-third-party-solutions-reference.html
sidebar: sidebar
keywords: configuration, support, third, party, solutions
summary: "Third-party solutions for use with ONTAP S3."
---
= Validated third-party solutions using S3 in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
S3 is a universal standard and this is not a comprehensive list of supported applications--only a list of solutions that have been validated in collaboration with the respective partners. If the solution you are looking for is not listed, please contact your NetApp account representative.

== Third-party solutions validated using native S3 buckets

* Amazon SageMaker
* Apache Hadoop S3A client
* Apache Kafka
* Commvault (V11)
* Confluent Kafka
* NetBackup
* Red Hat Quay
* Rubrik
* Snowflake
* Trino
* Veeam (V12)

[NOTE]
These solutions are validated specifically when using native S3 buckets in ONTAP. Some of these solutions, such as those associated with versioning, object locks, and other capabilities, are not supported when using link:../s3-multiprotocol/index.html[S3 NAS buckets (S3 in multiprotocol NAS volumes)].

// 2025-06-10, removed "NetApp has validated ..." and added note
// 2025-05-29, Clarified that validated does not mean comprehensive list
// 2025-01-17, Added NetBackup
// 2024-12-19, ontapdoc-2606
// 2023 Sept 6, ONTAPDOC 1315
// 2023 Aug 28, ONTAPDOC 1315
// 2023 June 26, ONTAPDOC-1048