---
permalink: snaplock/commit-files-worm-state-manual-task.html
sidebar: sidebar
keywords: commit, file, worm, manually, nfs, cifs, read, only
summary: "You commit a file to WORM manually by making the file read-only. You can use any suitable command or program over NFS or CIFS to change the read-write attribute of a file to read-only."
---
= Commit files to WORM manually
:icons: font
:imagesdir: ../media/

[.lead]
You commit a file to WORM manually by making the file read-only. You can use any suitable command or program over NFS or CIFS to change the read-write attribute of a file to read-only.

.What you'll need
* The file you want to commit must reside on a SnapLock volume.
* The file must be writable.

.About this task

The volume ComplianceClock time is written to the `ctime` field of the file when the command or program is executed. The ComplianceClock time determines when the retention time for the file has been reached.

.Steps

. Use a suitable command or program to change the read-write attribute of a file to read-only.
+
In a UNIX shell, use the following command to make a file named `document.txt` read-only:
+
----
chmod -w document.txt
----
+
In a Windows shell, use the following command to make a file named `document.txt` read-only:
+
----
attrib +r document.txt
----
