---
permalink: snaplock/create-locked-snapshot-task.html
sidebar: sidebar
keywords: snaplock, snapshot copy, lock, tamperproof, enable, retention, policy
summary: "Beginning with ONTAP 9.12.1, you can create Snapshot copy policies to apply a Snapshot copy retention period and apply the policy to a volume to lock Snapshot copies for the specified period. You can also lock a Snapshot copy by manually setting a retention period."
---
= Create a locked Snapshot copy
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.12.1, you can create Snapshot copy policies to apply a Snapshot copy retention period and apply the policy to a volume to lock Snapshot copies for the specified period. You can also lock a Snapshot copy by manually setting a retention period.

== Create a Snapshot copy locking policy

. To create a Snapshot copy policy, enter the following command: 
+
`volume snapshot policy create -policy policy_name -enabled true -schedule1 _schedule1_name_ -count1 _maximum_Snapshot_copies -retention-period1 _retention_period_`
+
The following command creates a Snapshot copy locking policy:
+
----
cluster1> volume snapshot policy create -policy policy_name -enabled true -schedule1 5min -count1 5 -retention-period1 "1 months"
----

== Apply a locking policy to a volume

. To apply a Snapshot copy locking policy to an existing volume, enter the following command:
+
`volume modify -volume volume_name -vserver vserver_name -snapshot-policy policy_name`

== Apply retention period during manual Snapshot copy creation

. To create a Snapshot copy manually and apply a locking retention period, enter the following command:
+
`volume snapshot create -volume _volume_name_ -snapshot _snapshot_copy_name_ -expiry-time _expiration_date_time_`
+
The following command creates a new Snapshot copy and sets the retention period:
+
----
cluster1> volume snapshot create -vserver vs1 -volume vol1 -snapshot snap1 -snaplock-expiry-time "11/10/2022 09:00:00"
----

== Apply retention period to an existing Snapshot copy

. To manually apply a retention period to an existing Snapshot copy, enter the following command:
+
`volume snapshot modify-snaplock-expiry-time -volume _volume_name_ -snapshot _snapshot_copy_name_ -expiry-time _expiration_date_time_`
+
The following example applies a retention period to an existing Snapshot copy:
+
----
cluster1> volume snapshot modify-snaplock-expiry-time -volume vol1 -snapshot snap2 -expiry-time "11/10/2022 09:00:00"
----

// 2022-Oct-26, ONTAPDOC-600