---
permalink: snaplock/create-snaplock-volume-task.html
sidebar: sidebar
keywords: snaplock, volume, shanpshot, copy, create, complianceclock, file, worm, compliance, enterprise
summary: "You must create a SnapLock volume for the files or Snapshot copies that you want to commit to the WORM state. The volume inherits the SnapLock mode—Compliance or Enterprise—from the SnapLock aggregate, and the ComplianceClock time from the node."
---
= Create a SnapLock volume
:icons: font
:imagesdir: ../media/

[.lead]
You must create a SnapLock volume for the files or Snapshot copies that you want to commit to the WORM state. The volume inherits the SnapLock mode--Compliance or Enterprise--from the SnapLock aggregate, and the ComplianceClock time from the node.

.What you'll need

The SnapLock aggregate must be online.

.About this task

You can destroy or rename an Enterprise volume at any time. You cannot destroy a Compliance volume until the retention period has elapsed. You can never rename a Compliance volume.

You can clone SnapLock volumes, but you cannot clone files on a SnapLock volume.

[NOTE]
====
LUNs are not supported on SnapLock volumes. Although it is possible to move LUNs onto a SnapLock volume using legacy technology, this is not a supported operation, nor is any other operation involving LUNs on a SnapLock volume.
====

.Steps

. Create a SnapLock volume:
+
`*volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_*`
+
For a complete list of options, see the man page for the command. The following options are not available for SnapLock volumes: `-nvfail`, `-atime-update`, `-is-autobalance-eligible`, `-space-mgmt-try-first`, and `vmalign`.
+
The following command creates a SnapLock `Compliance` volume named `vol1` on `aggr1` on `vs1`:
+
----
cluster1::> volume create -vserver vs1 -volume vol1 -aggregate aggr1
----
