---
permalink: snaplock/enable-snapshot-lock-task.html
sidebar: sidebar
keywords: snaplock, snapshot copy, lock, tamperproof, enable
summary: "Beginning with ONTAP 9.12.1, you can enable Snapshot copy locking when you create a new volume or when you modify an existing volume by using the `-snapshot-locking-enabled` option with the `volume create` and `volume modify` commands."
---
= Enable Snapshot copy locking
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.12.1, you can enable Snapshot copy locking when you create a new volume or when you modify an existing volume by using the `-snapshot-locking-enabled` option with the `volume create` and `volume modify` commands.

== Enable Snapshot copy locking when creating a volume

. To create a new volume and enable Snapshot copy locking, enter the following command: 
+
`volume create -vserver _vserver_name_ -volume _volume_name_ -snapshot-locking-enabled true`
+
The following command enables Snapshot copy locking on a new volume named vol1:
+
----
> volume create -volume vol1 -aggregate aggr1 -size 100m -snapshot-locking-enabled true
Warning: Snapshot copy locking is being enabled on volume “vol1” in Vserver “vs1”. It cannot be disabled until all locked Snapshot copies are past their expiry time. A volume with unexpired locked Snapshot copies cannot be deleted. 
Do you want to continue: {yes|no}: y
[Job 32] Job succeeded: Successful
----

== Enable Snapshot copy locking on an existing volume

. To modify an existing volume to enable Snapshot copy locking, enter the following command: 
+
`volume modify -vserver _vserver_name_ -volume _volume_name_ -snapshot-locking-enabled true`



// 2022-Oct-26, ONTAPDOC-600