---
permalink: snaplock/install-license-task.html
sidebar: sidebar
keywords: snaplock, license, install, compliance, mode, enterprise, aggregate
summary: "A SnapLock license entitles you to use both SnapLock Compliance mode and SnapLock Enterprise mode. SnapLock licenses are issued on a per-node basis. You must install a license for each node that hosts a SnapLock aggregate."
---
= Install the license
:icons: font
:imagesdir: ../media/

[.lead]
A SnapLock license entitles you to use both SnapLock Compliance mode and SnapLock Enterprise mode. SnapLock licenses are issued on a per-node basis. You must install a license for each node that hosts a SnapLock aggregate.

For details about Compliance mode and Enterprise mode, see link:https://docs.netapp.com/us-en/ontap/snaplock/index.html[What SnapLock is].

.What you'll need

You must be a cluster administrator to perform this task.

.About this task

You should have received the SnapLock license keys from your sales representative.

Perform this task using ONTAP System Manager or the ONTAP CLI.

[role="tabbed-block"]
====
.System Manager
--
. Navigate to *Cluster > Settings > Licenses > Add License*.
. Click *+Add*.
. Click *Browse* and locate the NetApp License File.
. Click *Add*.
--

.CLI
--

. Install the SnapLock license for a node:
+
`*system license add -license-code _license_key_*`
+
The following command installs the license with the key `AAAAAAAAAAAAAAAAAAAAAAAAAAAA`.
+
----
cluster1::> system license add -license-code AAAAAAAAAAAAAAAAAAAAAAAAAAAA
----

. Repeat the previous step for each node license.
--
====

// 2022-9-12, ONTAPDOC-580