---
permalink: nfs-trunking/adapt-exports-overview.html
sidebar: sidebar
keywords: NFS, servers, network, NFSv4.1, trunking, adapt, single-path, export, VMware, SMB, SVM 
summary: 'You can adapt an existing single-path (non-trunked) NFSv4.1 export to use trunking.'
---
= Adapting single-path exports overview 
:icons: font
:imagesdir: ../media/

[lead]
You can adapt an existing single-path (non-trunked) NFSv4.1 export to use trunking. Trunking-capable clients can take advantage of improved performance as soon as trunking is enabled on the server, provided the server and client prerequisites have been satisfied.

Adapting a single-path export for trunking allows you to maintain exported data sets in their existing volumes and SVMs. To do so, you must enable trunking on the NFS server, update networking and export configuration, and remount the exported share on the clients. If you have existing exports from NFSv3 or NFSv4.0 servers, you must also configure an NFSv4.1 server and remove other NAS servers ensure that the existing SVM is dedicated to NFSv4.1 trunking.

If you are serving NFS exports and SMB shares from the same SVM, you will have to rehost the volumes containing SMB shares to another SVM in order for the existing NFS exports to be accessible from an SVM dedicated to trunking. Learn about link:../volumes/rehost-volume-another-svm-task.html[volume rehosting]. 

Enabling trunking has the effect of restarting the server. VMware clients must then remount the exported datastores; Linux clients must remount exported volumes with the `max_connect` option.

// 2022 Nov 28, ONTAPDOC-552

