---
permalink: nfs-trunking/client-mount-task.html
sidebar: sidebar
keywords: NFS, servers, network, NFS trunking, data shares, Linux, VMware, mounts
summary: 'Linux and VMware clients that support trunking can mount volumes or data shares from an ONTAP NFS server that is enabled for trunking.'
---
= Mount ONTAP volumes or data shares for NFS trunking 
:icons: font
:imagesdir: ../media/

[.lead]
Linux and VMware clients that support trunking can mount volumes or data shares from an ONTAP NFSv4.1 server that is enabled for trunking.

Learn about link:index.html#supported-clients[supported clients].

[role="tabbed-block"]
====
.Linux client requirements
--

If you are using ONTAP 9.16.1 or later and Red Hat Enterprise Linux version 8.7 or later (for RHEL 8) or 9.2 or later (for RHEL 9) as your Linux client, only one mount point is required for the trunking group. Mount the exported volumes with this command, using the `trunkdiscovery` option:

+
[source,cli]
----
mount <lif_ip>:<volume_name> </mount_path> -o trunkdiscovery,vers=4.1
----

Otherwise, a separate mount point is required for each connection in the trunking group. Mount the exported volumes with commands similar to the following, using the `max_connect` option:

+
[source,cli]
----
mount <lif1_ip>:<volume_name> </mount_path1> -o vers=4.1,max_connect=16
----

+
[source,cli]
----
mount <lif2_ip>:<volume_name> </mount_path2> -o vers=4.1,max_connect=16
----
The version (`vers`) value should be `4.1` or later.

The `max_connect` value corresponds to the number of connections in the trunking group.

-- 

.VMware client requirements
-- 
A mount statement is required that includes an IP address for each connection in the trunking group.

Mount the exported datastore with a command similar to the following:

`#esxcli storage nfs41 -H lif1_ip, lif2_ip -s /mnt/sh are1 -v nfs41share`

The `-H` values correspond to the connections in the trunking group.
-- 
====

// 2025-1-22 GH-1581
// 2024-12-18 ONTAPDOC-2606
// 2023 Jan 09, ONTAPDOC-552
