---
permalink: nfs-trunking/create-exports-task.html
sidebar: sidebar
keywords: servers, network, NFS trunking, NIC, export policies, rule, Linux, VMware, datastores, client 
summary: 'To provide client access to data shares, you must create one or more volumes, and the volume must have export policies with at least one rule.'
---
= Export data for client access 
:icons: font
:imagesdir: ../media/

[lead]
To provide client access to data shares, you must create one or more volumes, and the volume must have export policies with at least one rule.  

Client export requirements:

* Linux clients must have a separate mount and a separate mount point for each trunking connection (that is, for each LIF).
+
* VMware clients require only a single mount point for an exported volume, with multiple LIFs specified. 
+
VMware clients require root access in the export policy.

.Steps

. Create an export policy:
+
[source,cli]
----
vserver export-policy create -vserver <svm_name> -policyname <policy_name>
----
+
The policy name can be up to 256 characters long.

. Verify that the export policy was created:
+
[source,cli]
----
vserver export-policy show -policyname <policy_name>
----
+
.Example
+
The following commands create and verify the creation of an export policy named exp1 on the SVM named vs1:
+
----
vs1::> vserver export-policy create -vserver vs1 -policyname exp1
----

. Create an export rule and add it to an existing export policy:
+
[source,cli]
----
vserver export-policy rule create -vserver <svm_name> -policyname <policy_name> -ruleindex <integer> -protocol nfs4 -clientmatch { _text | "text,text,…"_ } -rorule <security_type> -rwrule <security_type> -superuser <security_type> -anon <user_ID>
----
+
The `-clientmatch` parameter should identify the trunking-capable Linux or VMware clients that will mount the export.
+
Learn more about link:../nfs-config/add-rule-export-policy-task.html[creating export rules.]

. Create the volume with a junction point:
+
[source,cli]
----
volume create -vserver <svm_name> -volume <volume_name> -aggregate <aggregate_name> -size {integer[KB|MB|GB|TB|PB]} -security-style unix -user <user_name_or_number> -group <group_name_or_number> -junction-path <junction_path> -policy <export_policy_name>
----
+
Learn about link:../nfs-config/create-volume-task.html[creating volumes.]

. Verify that the volume was created with the desired junction point:
+
[source,cli]
----
volume show -vserver <svm_name> -volume <volume_name> -junction
----

// 2023 Jan 09, ONTAPDOC-552
