---
permalink: nfs-trunking/index.html
sidebar: sidebar
keywords: NFS, NFSv4.1, trunking, Linux, VMware, FlexGroup, volumes, multipathing
summary: 'Beginning with ONTAP 9.12.1, NFSv4.1 clients can take advantage of session trunking functionality to open multiple connections to the NFS server, thereby increasing the speed of data transfer and providing resiliency through multipathing'
---
= NFSv4.1 trunking overview 
:icons: font
:imagesdir: ../media/

[lead]
Beginning with ONTAP 9.12.1, NFSv4.1 clients can take advantage of session trunking functionality to open multiple connections to the NFS server, thereby increasing the speed of data transfer and providing resiliency through multipathing.

Trunking is advantageous for exporting FlexVol volumes to trunking-capable clients; in particular, VMware and Linux clients. 

FlexGroup volumes are supported for trunking. However, in this release, multipath access to a FlexGroup volume can only be configured on a single node, thereby limiting the benefit of FlexGroup volumes if they cannot be configured on multiple nodes.

*Only session trunking is supported for multipathing in this release.*

== How to use trunking 

To take advantage of multipathing benefits offered by trunking, you need to create a set of LIFs – referred to as a _trunking group_ – that are associated with the SVM containing a trunking-enabled NFS server. Each LIF in a trunking group must have a home port on the same node of the cluster and be a member of the same failover group. Most trunking-capable clients can support up to 16 trunked connections.

When clients mount shares exported from the SVM with the trunking-enabled server, they specify the IP addresses of the LIFs in the trunk group. The clients then distribute NFS operations over the multiple connections based on their own algorithm (such as round-robin).

For best performance, you should configure trunking in an SVM that is dedicated to providing multipath exports, not single-path exports. That is, you should only enable trunking on a NFS server in an SVM whose exports are provided to trunking-enabled clients only.

== Supported clients 

The ONTAP NFSv4.1 server supports trunking on any client capable of single-node trunking.

*The following clients have been tested with ONTAP 9.12.1:*

* VMware – *??*
* Linux  – RHEL 8.7, 9.1

NOTE: When trunking is enabled on an NFS server, users accessing exported shares on NFS clients that don't support trunking might see a performance drop. This is because only a single TCP connection is used for multiple mounts to the SVM data LIFs.

== Difference between NFSv4.1 trunking and nconnect 

Beginning with ONTAP 9.8, nconnect _multiplexing_ functionality is available by default when NFSv4.1 is enabled. On nconnect-capable clients, a single NFS mount can have multiple TCP connections (up to 16) over a single physical connection (NIC). 

In contrast, trunking is _multipathing_ functionality, which provides multiple TCP connections over multiple NICs. If you have the ability to employ additional NICs in your environment, trunking provides increased parallelism and performance beyond the capability of nconnect.

Learn more about link:https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv41-concept.html[nconnect.]

== Reverting to ONTAP 9.12.1 or earlier when trunking is enabled

After reverting to an earlier ONTAP release, the clients using trunked connections will fall back to using *a single connection* and their data throughput will be affected, but there will be no disruption. The revert behavior is the same as modifying the NFSv4.1 trunking option for the SVM from enabled to disabled.

// 2022 Nov 28, ONTAPDOC-552




