---
permalink: cloud/file-sharing-nfs-smb-concept.html
sidebar: sidebar
keywords: file sharing, nfs, smb/cifs
summary: "The NFS and SMB/CIFS protocols are used to make shares and files available to client applications over a network. Cloud Volumes ONTAP enables you to provide files from a public cloud using either or both of these protocols."
---
= File sharing with NFS and SMB/CIFS
:icons: font
:imagesdir: ../media/

[.lead]
The NFS and SMB/CIFS protocols are used to make shares and files available to client applications over a network. Cloud Volumes ONTAP enables you to provide files from a public cloud using either or both of these protocols.

If you choose to move an entire workload to the cloud, Cloud Volumes ONTAP enables your application to work with storage in the cloud exactly as it does on premises. There is no need to change your application, and if you decide to move to a different cloud provider, there is no worry about provider lock in. The same commands and scripts you use to manage file services on premises work in the cloud.

In the cloud, you can scale file shares rapidly, by adding or removing storage and compute instances or by adjusting your service level as needed to respond to changes in client demand without incurring capital expenses. The more resources you use, the more you pay, but only when you are using the resources.

NetApp SnapMirror technology moves and synchronizes your file data between your on-premises ONTAP system and Cloud Volumes ONTAP. You can easily move the data to and from the cloud, and between cloud providers.

*Related information*

https://docs.netapp.com/us-en/occm/task_provisioning_storage.html#creating-flexvol-volumes[Cloud Manager: Provisioning Storage]

https://docs.netapp.com/us-en/occm/task_manage_anf.html[Managing volumes for Azure NetApp Files]

https://docs.netapp.com/us-en/occm/task_manage_cvs_aws.html[Managing Cloud Volumes Service for AWS]
