---
permalink: cloud/high-availability-concept.html
sidebar: sidebar
keywords: high availability
summary: "In an on-premises data center, physical nodes are configured in high-availability (HA) pairs for fault tolerance and nondisruptive operations. If a node fails or if you need to bring a node down for routine maintenance, its partner takes over its storage and continues to serve data from it."
---
= High availability
:icons: font
:imagesdir: ../media/

[.lead]
In an on-premises data center, physical nodes are configured in high-availability (HA) pairs for fault tolerance and nondisruptive operations. If a node fails or if you need to bring a node down for routine maintenance, its partner takes over its storage and continues to serve data from it.

In a cloud environment, you can create an HA pair of Cloud Volumes ONTAP instances for the same fault tolerance and non-disruptive operations as an on-premises HA pair. These recovery objectives are available with cloud HA pairs:

* The recovery point objective (RPO) is 0 seconds. Your data is transactionally consistent with no data loss.
* The recovery time objective (RTO) is 60 seconds. In the event of an outage, data should be available in 60 seconds or less.

Each cloud provider offers its own HA architecture and configuration options. For Cloud Volumes Service, high availability is guaranteed in the service level agreement.

*Related information*

https://docs.netapp.com/us-en/occm/concept_ha.html[High-availability pairs in AWS]

https://docs.netapp.com/us-en/occm/concept_ha_azure.html[High-availability pairs in Azure]
