---
permalink: cloud/index.html
sidebar: sidebar
keywords: azure netapp volumes, overview, decide, ontap, cloud, administration, on-premises
summary: "Administrators of on-premises ONTAP systems can start using “the cloud.” ONTAP features are compared to the equivalent products and features in the cloud."
---
= ONTAP and the cloud overview
:icons: font
:imagesdir: ../media/

[.lead]
Administrators of on-premises ONTAP systems can start using "`the cloud.`" ONTAP features are compared to the equivalent products and features in the cloud.

If you are already familiar with ONTAP but are not as familiar with cloud-based products, the following information helps you understand what you can do in the cloud and points you to other resources to learn how:

* Cloud Volumes ONTAP
+
A software-only storage appliance that runs ONTAP data management software in the cloud.

* Cloud Volume Services
+
Cloud native file services that provide metered file storage for NAS volumes. Three options are offered:

 ** Azure NetApp Files
 ** Amazon FSx for ONTAP
 ** Cloud Volumes Service for Google Cloud

.Related information

Whether you are new to these cloud products or already familiar with them, you can find more information at https://www.netapp.com/support-and-training/documentation/[NetApp Product Documentation^].

// 2022 Nov 21, Issue 711
// BURT 1448684, 20 JAN 2022
