---
permalink: cloud/snaplock-worm-storage-concept.html
sidebar: sidebar
keywords: snaplock worm storage
summary: "An important aspect of compliance is being able to guarantee that certain data is maintained unchanged for a required period of time. SnapLock is a high-performance compliance solution that uses write once, read many (WORM) storage to retain files in unmodified form for regulatory and governance purposes. With cloud WORM storage, the SnapLock feature extends to Cloud Volumes ONTAP."
---
= SnapLock WORM storage
:icons: font
:imagesdir: ../media/

[.lead]
An important aspect of compliance is being able to guarantee that certain data is maintained unchanged for a required period of time. SnapLock is a high-performance compliance solution that uses write once, read many (WORM) storage to retain files in unmodified form for regulatory and governance purposes. With cloud WORM storage, the SnapLock feature extends to Cloud Volumes ONTAP.

SnapLock offers two data retention models:

* *SnapLock Compliance* provides strict data retention and is compliant with multiple industry and government regulations. SnapLock Compliance is not currently available in Cloud Volumes ONTAP.
* *SnapLock Enterprise* is deployed for more flexible regulatory requirements and organization-defined policies. Unlike SnapLock Compliance, a privileged administrator can delete SnapLock Enterprise files at any time. SnapLock Enterprise is available in Cloud Volumes ONTAP.

*Related information*

https://docs.netapp.com/us-en/ontap/snaplock/index.html[Archive and compliance using SnapLock technology]

https://cloud.netapp.com/blog/enhance-cloud-data-protection-with-worm-storage[NetApp Cloud WORM: Enhancing Data Protection with Locking Features]
