---
permalink: cloud/snaplock-worm-storage-concept.html
sidebar: sidebar
keywords: cloud worm storage
summary: "An important aspect of compliance is being able to guarantee that certain data is maintained unchanged for a required period of time. You can activate write once, read many (WORM) storage on a Cloud Volumes ONTAP system to retain files in unmodified form for a specified retention period. Cloud WORM storage is powered by SnapLock technology, which means WORM files are protected at the file level."
---
= Cloud WORM storage
:icons: font
:imagesdir: ../media/

[.lead]
An important aspect of compliance is being able to guarantee that certain data is maintained unchanged for a required period of time. You can activate write once, read many (WORM) storage on a Cloud Volumes ONTAP system to retain files in unmodified form for a specified retention period. Cloud WORM storage is powered by SnapLock technology, which means WORM files are protected at the file level.

Once a file has been committed to WORM storage, it can’t be modified, even after the retention period has expired. A tamper-proof clock determines when the retention period for a WORM file has elapsed.

You can activate WORM storage on a Cloud Volumes ONTAP system when you create a new working environment. This includes setting the default retention period for files. You can’t activate WORM storage on individual volumes—​WORM must be activated at the system level.


.Related information

https://docs.netapp.com/us-en/occm/concept_worm.html#activating-worm-storage[WORM storage]

link:../snaplock/index.html[Archive and compliance using SnapLock technology]

https://cloud.netapp.com/blog/enhance-cloud-data-protection-with-worm-storage[NetApp Cloud WORM: Enhancing Data Protection with Locking Features]

// 2023-May-17, issue# 917
// 09 DEC 2021, BURT 1430515
// 2022-1-6, issue 310
