---
permalink: flexcache/accelerate-data-access-concept.html
sidebar: sidebar
keywords: using, flexcache, volumes, accelerate, data, access
summary: "A FlexCache volume is a sparsely populated volume that is backed by an origin volume. The FlexCache volume can be on the same cluster as or on a different cluster than that of the origin volume. The FlexCache volume provides access to data in the origin volume without requiring that all of the data be in the FlexCache volume."
---
= Use FlexCache volumes to accelerate data access overview 
:icons: font
:imagesdir: ../media/

[.lead]
A FlexCache volume is a sparsely populated volume that is backed by an origin volume. The FlexCache volume can be on the same cluster as or on a different cluster than that of the origin volume. The FlexCache volume provides access to data in the origin volume without requiring that all of the data be in the FlexCache volume.

In ONTAP 9.5, the origin volume is a FlexVol volume and the FlexCache volume is a FlexGroup volume. An origin volume supports NFSv3, NFSv4, and SMB protocols. A FlexCache volume supports only NFSv3 protocol in ONTAP 9.5. Beginning with ONTAP 9.8, a FlexCache volume also supports SMB protocol. Beginning with ONTAP 9.10.1, a FlexCache volume supports the NFSv4 protocol. For a table summary of supported features in FlexCache volumes, refer to xref:supported-unsupported-features-concept.adoc[Supported and unsupported features for FlexCache volumes].

Beginning with ONTAP 9.7, FlexGroup volumes are also supported as source volumes.

[NOTE]
====
In ONTAP 9 releases earlier than 9.5, origin FlexVol volumes can only serve data to FlexCache volumes created on systems running Data ONTAP 8.2.x operating in 7-Mode. Beginning in ONTAP 9.5, origin FlexVol volumes can also serve data to FlexCache volumes on ONTAP 9 systems. For information about migrating from 7-mode FlexCache to ONTAP 9 FlexCache, link:http://www.netapp.com/us/media/tr-4743.pdf[NetApp Technical Report 4743: FlexCache Volumes in NetApp ONTAP].

====

A FlexCache volume directly serves read requests if the volume contains the data requested by the client. Otherwise, the FlexCache volume requests the data from the origin volume and stores the data before serving the client request. Subsequent read requests for the data are then served directly from the FlexCache volume. This improves performance when the same data is accessed repeatedly, because after the first request, the data no longer has to travel across the network, or be served from an overloaded system.

Beginning with ONTAP 9.9.1, FlexCache volumes cache a directory listing for "file not found" errors that occur when a file no longer exists on the origin volume. This helps reduce network traffic by removing the need to send multiple calls to the origin when clients search for non-existent files.

You can use FlexCache volumes to speed up access to data or to offload traffic from heavily accessed volumes. FlexCache volumes help improve performance, especially when clients need to access the same data repeatedly, because the data can be served directly without having to access the origin volume. Therefore, you can use FlexCache volumes to handle system workloads that are read-intensive.

Any write operation is applied at the origin volume.

// 2021-11-01, IE-426