---
permalink: flexcache/prepopulate-volume-task.html
sidebar: sidebar
keywords: prepopulating, flexcache, volume
summary: "You can prepopulate a FlexCache volume to reduce the time it takes to access cached data."
---
= Prepopulate a FlexCache volume
:icons: font
:imagesdir: ../media/

[.lead]
You can prepopulate a FlexCache volume to reduce the time it takes to access cached data.

.What you'll need

* You must be a cluster administrator at the advanced privilege level
* The paths you pass for prepopulation must be valid or the prepopulate operation fails.

.About this task

* Prepopulate reads files only and crawls through directories
* The is-recursion flag applies to the entire list of directories passed to prepopulate

.Steps

. Prepopulate a FlexCache volume:
+
`volume flexcache prepopulate -cache-vserver vserver_name -cache-volume -path-list path_list -is-recursion true|false`
+
This example includes a single directory path for prepopulation:
+
----
cluster1::*> flexcache prepopulate start -cache-vserver vs2 -cache-volume fg_cachevol_1 -path-list /dir1
  (volume flexcache prepopulate start)
[JobId 207]: FlexCache prepopulate job queued.
----
+
This example includes a list of several paths for prepopulation:
+
----
cluster1::*> flexcache prepopulate start -cache-vserver vs2 -cache-volume fg_cachevol_1 -path-list /dir1,/dir2,/dir3,/dir4
  (volume flexcache prepopulate start)
[JobId 208]: FlexCache prepopulate job queued.
----

. Display the number of files read:
+
`job show -id job_ID -ins`
