---
permalink: flexcache/refresh-config-relationship-task.html
sidebar: sidebar
keywords:  updating, configurations, flexcache, relationship
summary: "After events such as volume move, aggregate relocation, or storage failover, the volume configuration information on the origin volume and FlexCache volume is updated automatically. In case the automatic updates fail, an EMS message is generated and then you must manually update the configuration for the FlexCache relationship."
---
= Update the configuration of ONTAP FlexCache relationships
:icons: font
:imagesdir: ../media/

[.lead]
After events such as volume move, aggregate relocation, or storage failover, the volume configuration information on the origin volume and FlexCache volume is updated automatically. In case the automatic updates fail, an EMS message is generated and then you must manually update the configuration for the FlexCache relationship.

If the origin volume and the FlexCache volume are in the disconnected mode, you might need to perform some additional operations to update a FlexCache relationship manually.

.About this task

If you want to update the configurations of a FlexCache volume, you must run the command from the origin volume. If you want to update the configurations of an origin volume, you must run the command from the FlexCache volume.

.Step

. Update the configuration of the FlexCache relationship:
+
`volume flexcache config-refresh -peer-vserver peer_svm -peer-volume peer_volume_to_update -peer-endpoint-type [origin | cache]`

// 2-APR-2025 ONTAPDOC-2919