---
permalink: flexcache/sizing-concept.html
sidebar: sidebar
keywords: guidelines, sizing, flexcache, volume
summary: "You must be aware of the limits for FlexCache volumes before you start provisioning the volumes."
---
= Guidelines for sizing a FlexCache volume
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of the limits for FlexCache volumes before you start provisioning the volumes.

The size limit of a FlexVol volume is applicable to an origin volume. The size of a FlexCache volume can be less than or equal to the origin volume. The best practice for the size of a FlexCache volume is to be at least 10 percent of the size of the origin volume.

You must also be aware of the following additional limits on FlexCache volumes:
[options="header"]
|===
|Limit |ONTAP 9.9.1 |ONTAP 9.8  |ONTAP 9.7 and 9.6 |ONTAP 9.5
|Maximum number of FlexCache volumes that you can create from an origin volume
|100
|100
|100
|10
|Maximum number of origin volumes per node
|100
|100
|100
|10
|Maximum number of FlexCache volumes per node
|100
|100
|100
|10
|Maximum number of FlexGroup constituents in a FlexCache volume per node
|800
|800
|800
|40
|===
*Related information*

https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability]

