---
permalink: flexcache/sizing-concept.html
sidebar: sidebar
keywords: guidelines, sizing, flexcache, volume
summary: "You must be aware of the limits for FlexCache volumes before you start provisioning the volumes."
---
= Guidelines for sizing a FlexCache volume
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of the limits for FlexCache volumes before you start provisioning the volumes.

The size limit of a FlexVol volume is applicable to an origin volume. The size of a FlexCache volume can be less than or equal to the origin volume. The best practice for the size of a FlexCache volume is to be at least 10 percent of the size of the origin volume.

You must also be aware of the following additional limits on FlexCache volumes:

[cols="55,15,15,15"]
|===

h|Limit  h|ONTAP 9.5-9.6 h|ONTAP 9.7 h|ONTAP 9.8 and later

|Maximum number of FlexCache volumes that you can create from an origin volume
|10
|10
|100
|Recommended maximum number of origin volumes per node
|10
|100
|100
|Recommended maximum number of FlexCache volumes per node
|10
|100
|100
|Recommended maximum number of FlexGroup constituents in a FlexCache volume per node
|40
|800
|800
|Maximum number of constituents per FlexCache volume per node
|32
|32
|32
|===

.Related information

https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability^]


// 27 October 2021, BURTs 1430251, 1299586
