---
permalink: volumes/assign-quota-policies-concept.html
sidebar: sidebar
keywords: considerations for, assigning, quota, policies
summary: "A quota policy is a grouping of the quota rules for all the FlexVol volumes of an SVM. You must be aware of certain considerations when assigning the quota policies."
---
= Considerations for assigning quota policies
:icons: font
:imagesdir: ../media/

[.lead]
A quota policy is a grouping of the quota rules for all the FlexVol volumes of an SVM. You must be aware of certain considerations when assigning the quota policies.

* An SVM has one assigned quota policy at any given time. When an SVM is created, a blank quota policy is created and assigned to the SVM. This default quota policy has the name "default" unless a different name is specified when the SVM is created.
* An SVM can have up to five quota policies. If an SVM has five quota policies, you cannot create a new quota policy for the SVM until you delete an existing quota policy.
* When you need to create a quota rule or change quota rules for a quota policy, you can choose either of the following approaches:
 ** If you are working in a quota policy that is assigned to an SVM, you need not assign the quota policy to the SVM.
 ** If you are working in an unassigned quota policy and then assigning the quota policy to the SVM, you must have a backup of the quota policy that you can revert to if required.
+
For example, you can make a copy of the assigned quota policy, change the copy, assign the copy to the SVM, and rename the original quota policy.
* You can rename a quota policy even when it is assigned to the SVM.
