---
permalink: volumes/change-maximum-number-files-allowed-concept.html
sidebar: sidebar
keywords: considerations, changing, maximum number of files, allowed, flexvol volume
summary: "FlexVol volumes have a maximum number of files that they can contain. You can change the maximum number of files for a volume, but before doing so you should understand how this change affects the volume."
---
= Considerations for changing the maximum number of files allowed on a FlexVol volume
:icons: font
:imagesdir: ../media/

[.lead]
FlexVol volumes have a maximum number of files that they can contain. You can change the maximum number of files for a volume, but before doing so you should understand how this change affects the volume.

//Barb 8-OCT-2021, added the following sentence as per Satyajit/Ed comment in a PDF as part of the ONTAP catalyst QA review.

If your data requires a large number of files or very large directories, you can expand ONTAP file or directory capacity. However, you should understand the limitations and caveats for doing so before proceeding.

The number of files a volume can contain is determined by how many inodes it has. An _inode_ is a data structure that contains information about files. Volumes have both private and public inodes. Public inodes are used for files that are visible to the user; private inodes are used for files that are used internally by ONTAP. You can change only the maximum number of public inodes for a volume. You cannot affect the number of private inodes.

ONTAP automatically sets the maximum number of public inodes for a newly created volume based on the size of the volume: 1 inode per 32 KB of volume size. When the size of a volume is increased, either directly by an administrator or automatically by ONTAP through the autosize feature, ONTAP also increases (if necessary) the maximum number of public inodes so there is at least 1 inode per 32 KB of volume size, until the volume reaches approximately 680 GB in size.

In versions of ONTAP before 9.13.1, growing the volume greater than 680 GB in size does not automatically result in more inodes, because ONTAP does not automatically create more than 22,369,621 inodes. If you need more files than the default number for any size volume, you can use the volume modify command to increase the maximum number of inodes for the volume.

Beginning in ONTAP 9.13.1, maximum number of inodes continues to grow so there is 1 inode per 32 KB of volume even if the volume is larger than 680 GB. This growth continues until volume reaches the inode maximum 2,147,483,632

You can also decrease the maximum number of public inodes. This does not change the amount of space currently allocated to inodes, but it does lower the maximum amount of space the public inode file can consume. However, after space has been allocated for inodes, it is never returned to the volume. Therefore, lowering the maximum number of inodes below the number of inodes currently allocated does not return the space used by the allocated but unused inodes to the volume.

.More information 
* xref:display-file-inode-usage-task.html[Display file or inode usage]

// 3 august 2023, BURT 1575111 + ONTAPDOC-1217
