---
permalink: volumes/change-maximum-number-files-allowed-concept.html
sidebar: sidebar
keywords: considerations, changing, maximum number of files, allowed, flexvol volume, maximum, files, file
summary: "FlexVol volumes have a maximum number of files that they can contain. You can change this maximum, but be aware of how this affects the volume."
---
= The maximum number of files allowed for FlexVol volumes in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
FlexVol volumes have a maximum number of files that they can contain. You can change this maximum, but before doing so you should understand how this change affects the volume.

//Barb 8-OCT-2021, added the following sentence as per Satyajit/Ed comment in a PDF as part of the ONTAP catalyst QA review.

If your data requires a large number of files or very large directories, you can expand ONTAP file or directory capacity. However, you should understand the limitations and caveats for doing so before proceeding.

The number of files a volume can contain is determined by how many inodes it has. An _inode_ is a data structure that contains information about files. Volumes have both private and public inodes. Public inodes are used for files that are visible to the user; private inodes are used for files that are used internally by ONTAP. You can change only the maximum number of public inodes for a volume. You cannot affect the number of private inodes.

ONTAP automatically sets the maximum number of public inodes for a newly created volume based on the size of the volume: 1 inode per 32 KB of volume size. When the size of a volume is increased, either directly by an administrator or automatically by ONTAP through the autosize feature, ONTAP also increases (if necessary) the maximum number of public inodes so there is at least 1 inode per 32 KB of volume size, until the volume reaches approximately 680 GB in size.

In versions of ONTAP before 9.13.1, growing the volume greater than 680 GB in size does not automatically result in more inodes, because ONTAP does not automatically create more than 21,251,126 inodes. If you need more files than the default number for any size volume, you can use the volume modify command to increase the maximum number of inodes for the volume.

Beginning with ONTAP 9.13.1, the maximum number of inodes continues to grow so there is one inode per 32 KB of volume space even if the volume is larger than 680 GB. This growth continues until the volume reaches the inode maximum of 2,040,109,451.

You can also decrease the maximum number of public inodes. Decreasing the number of public inodes does _not_ change the amount of space allocated to inodes, but it does lower the maximum amount of space the public inode file can consume. After space has been allocated for inodes, it is never returned to the volume. Therefore, lowering the maximum number of inodes below the number of inodes currently allocated does not return the space used by the allocated inodes.

.More information 
* xref:display-file-inode-usage-task.html[Determine file and inode usage for a volume]


// 2025 Jan 22, ONTAPDOC-1070
// 2025-Jan-21, issue# 1589
// 3 august 2023, BURT 1575111 + ONTAPDOC-1217
// ONTAPDOC-2119/GH-1818 2024-6-24
