---
permalink: volumes/commands-manage-flexvol-volumes-reference.html
sidebar: sidebar
keywords: commands for, managing, flexvol, volumes, manage, command
summary: "There are specific commands for managing FlexVol volumes using the ONTAP CLI."
---
= Commands for managing FlexVol volumes
:icons: font
:imagesdir: ../media/

[.lead]
The ONTAP CLI provides specific commands for managing FlexVol volumes. Depending on what you need to do, you can use the following commands to manage FlexVol volumes:

[cols="2*",options="header"]
|===
| If you want to...| Use this command...
a|
Bring a volume online
a|
`volume online`
a|
Change the size of a volume
a|
`volume size`
a|
Determine the associated aggregate of a volume
a|
`volume show`
a|
Determine the associated aggregate for all volumes on a storage virtual machine (SVM)
a|
`volume show -vserver -fields aggregate`
a|
Determine the format of a volume
a|
`volume show -fields block-type`
a|
Mount a volume onto another volume using a junction
a|
`volume mount`
a|
Put a volume into the restricted state
a|
`volume restrict`
a|
Rename a volume
a|
`volume rename`
a|
Take a volume offline
a|
`volume offline`
|===
See the man page for each command for more information.

// ONTAPDOC-1818 2024-6-25
