---
permalink: volumes/commands-configure-deletion-flexclone-reference.html
sidebar: sidebar
keywords: commands for, configuring, deletion of, flexclone files, configure, command, delete, deletion, files, file
summary: "When clients delete FlexClone files without using the NetApp Manageability SDK, you can use the volume file clone deletion commands to enable faster deletion of FlexClone files from a FlexVol volume."
---
= Commands for configuring deletion of FlexClone files
:icons: font
:imagesdir: ../media/

[.lead]
When clients delete FlexClone files without using the NetApp Manageability SDK, you can use the `volume file clone deletion` commands to enable faster deletion of FlexClone files from a FlexVol volume. Extensions for and minimum size of FlexClone files are used to enable faster deletion.

You can use the `volume file clone deletion` commands to specify a list of supported extensions and a minimum size requirement for FlexClone files in a volume. The faster deletion method is used only for FlexClone files that meet the requirements. For FlexClone files that do not meet the requirements, the slower deletion method is used.

When clients delete FlexClone files and FlexClone LUNs from a volume by using the NetApp Manageability SDK, the extension and size requirements do not apply because the faster deletion method is always used.
[cols="2*",options="header"]
|===
| To...| Use this command...
a|
Add an extension to the supported list of extensions for the volume
a|
`volume file clone deletion add-extension`
a|
Change the minimum size of FlexClone files that can be deleted from the volume by using the faster deletion method
a|
`volume file clone deletion modify`
a|
Remove an extension from the supported list of extensions for the volume
a|
`volume file clone deletion remove-extension`
a|
View the supported list of extensions and the minimum size of FlexClone files that clients can delete from the volume by using the faster deletion method
a|
`volume file clone deletion show`
|===
For detailed information about these commands, see the appropriate man page.

// ONTAPDOC-2119/GH-1818 2024-6-25