---
permalink: volumes/commands-manage-quota-rules-policies-reference.html
sidebar: sidebar
keywords: commands to, manage, quota rules, quota policies, command, commands, quota, quotas, policy, policies
summary: "The `volume quota policy rule` commands enable you to configure quota rules, and the `volume quota policy` commands and some `vserver` commands enable you to configure quota policies."
---
= Commands to manage quota rules and quota policies
:icons: font
:imagesdir: ../media/

[.lead]
The `volume quota policy rule` commands enable you to configure quota rules, and the `volume quota policy` commands and some `vserver` commands enable you to configure quota policies. Depending on what you need to do, use the following commands to manage quota rules and quota policies:

[NOTE]
You can run the following commands only on FlexVol volumes.

== Commands for managing quota rules
[cols="2*",options="header"]
|===
| If you want to...| Use this command...
a|
Create a new quota rule
a|
`volume quota policy rule create`
a|
Delete an existing quota rule
a|
`volume quota policy rule delete`
a|
Modify an existing quota rule
a|
`volume quota policy rule modify`
a|
Display information about configured quota rules
a|
`volume quota policy rule show`
|===

== Commands for managing quota policies
[cols="2*",options="header"]
|===
| If you want to...| Use this command...
a|
Duplicate a quota policy and the quota rules it contains
a|
`volume quota policy copy`
a|
Create a new, blank quota policy
a|
`volume quota policy create`
a|
Delete an existing quota policy that is not currently assigned to a storage virtual machine (SVM)
a|
`volume quota policy delete`
a|
Rename a quota policy
a|
`volume quota policy rename`
a|
Display information about quota policies
a|
`volume quota policy show`
a|
Assign a quota policy to an SVM
a|
`vserver modify -quota-policy _policy_name_`
a|
Display the name of the quota policy assigned to an SVM
a|
`vserver show`
|===

Learn more about the commands described in this procedure in the link:https://docs.netapp.com/us-en/ontap-cli/[ONTAP command reference^].

.Related information
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota+policy[volume quota policy^]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-modify.html[vserver modify -quota-policy policy_name^]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-show.html[vserver show^]


// 2025 Mar 24, ONTAPDOC-2758
// 27 march 2023, ontapdoc-780
// ONTAPDOC-2119/GH-1818 2024-6-25
