---
permalink: volumes/configure-automatic-grow-shrink-size-task.html
sidebar: sidebar
keywords: configure, volumes, automatically, grow, shrink, size, automatic, space
summary: "You can configure FlexVol volumes to automatically grow and shrink according to how much space they currently require."
---
= Configure volumes to automatically grow and shrink their size
:icons: font
:imagesdir: ../media/

[.lead]
You can configure FlexVol volumes to automatically grow and shrink according to how much space they currently require. Automatic growing helps prevent a volume from running out of space, if the aggregate can supply more space. Automatic shrinking prevents a volume from being larger than needed, freeing space in the aggregate for use by other volumes.

.About this task

Autoshrink can only be used in combination with autogrow to meet changing space demands and is not available alone. When autoshrink is enabled, ONTAP automatically manages the shrinking behavior of a volume to prevent an endless loop of autogrow and autoshrink actions.

As a volume grows, the maximum number of files it can contain might be automatically increased. When a volume is shrunk, the maximum number of files it can contain is left unchanged, and a volume cannot be automatically shrunk below the size that corresponds to its current maximum number of files. For this reason, it might not be possible to automatically shrink a volume all the way to its original size.

By default, the maximum size a volume can grow to is 120% of the size at which autogrow is enabled. If you need to ensure that the volume can grow to be larger than that, you must set the maximum size for the volume accordingly.

.Before you begin

The FlexVol volume must be online.

.Step

. Configure the volume to grow and shrink its size automatically:
+
`volume autosize -vserver _SVM_name_ -volume _volume_name_ -mode grow_shrink`
+
The following command enables automatic size changes for a volume called test2. The volume is configured to begin shrinking when it is 60% full. The default values are used for when it will begin to grow and its maximum size.
+
----
cluster1::> volume autosize -vserver vs2 test2 -shrink-threshold-percent 60
vol autosize: Flexible volume "vs2:test2" autosize settings UPDATED.

Volume modify successful on volume: test2
----

// ONTAPDOC-2119/GH-1818 2024-6-25