---
permalink: volumes/control-io-performance-qos-task.html
sidebar: sidebar
keywords: control, monitor, i/o performance, flexvol volumes, using storage qos, qos, performance, throttle, flexvol, policy, policy group
summary: "You can control I/O performance for FlexVol volumes using storage QoS policy groups to manage workloads."
---
= Control and monitor FlexVol volume I/O performance with Storage QoS
:icons: font
:imagesdir: ../media/

[.lead]
You can control input/output (I/O) performance to FlexVol volumes by assigning volumes to Storage QoS policy groups. You might control I/O performance to ensure that workloads achieve specific performance objectives or to throttle a workload that negatively impacts other workloads.

.About this task

Policy groups enforce a maximum throughput limit (for example, 100 MB/s). You can create a policy group without specifying a maximum throughput, which enables you to monitor performance before you control the workload.

You can also assign SVMs, LUNs, and files to policy groups.

Note the following requirements about assigning a volume to a policy group:

* The volume must be contained by the SVM to which the policy group belongs.
+
You specify the SVM when you create the policy group.

* Beginning with ONTAP 9.18.1, you can assign QoS policies to inside volumes contained in SVMs that have QoS policies. When you use nested QoS policies, the most restrictive policy is applied. 

For more information about how to use Storage QoS, see the link:../system-admin/index.html[System Administration Reference].

.Steps

. Use the `qos policy-group create` command to create a policy group.
. Use the `volume create` command or the `volume modify` command with the `-qos-policy-group` parameter to assign a volume to a policy group.
. Use the `qos statistics` commands to view performance data.
. If necessary, use the `qos policy-group modify` command to adjust the policy group's maximum throughput limit.

.Related information
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=qos+policy-group[qos policy-group^]
* link: https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html[qos policy-group create]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html[volume create^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html[volume modify^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=qos+statistics[qos statistics^]

// 2025-Jan-22, ONTAPDOC-3629
// 2025-Oct-7, ONTAPDOC-3271
// 2025 May 27, ONTAPDOC-2960
// 2025 Mar 19, ONTAPDOC-2758
// ONTAPDOC-2119/GH-1818 2024-6-25