---
permalink: volumes/create-flexclone-snapmirror-concept.html
sidebar: sidebar
keywords: considerations, creating, flexclone volume, from snapmirror, source, destination, volume, flexclone, snapmirror, future
summary: "You can create a FlexClone volume from the source or destination volume in an existing SnapMirror relationship, but doing so can affect future SnapMirror replication operations."
---
= Considerations for creating a FlexClone volume from a SnapMirror source or destination volume
:icons: font
:imagesdir: ../media/

[.lead]
You can create a FlexClone volume from the source or destination volume in an existing volume SnapMirror relationship. However, doing so could prevent future SnapMirror replication operations from completing successfully.

Replication might not work because when you create the FlexClone volume, you might lock a snapshot that is used by SnapMirror. If this happens, SnapMirror stops replicating to the destination volume until the FlexClone volume is destroyed or is split from its parent. You have two options for addressing this issue:

* If you require the FlexClone volume on a temporary basis and can accommodate a temporary stoppage of the SnapMirror replication, you can create the FlexClone volume and either delete it or split it from its parent when possible.
+
The SnapMirror replication continues normally when the FlexClone volume is deleted or is split from its parent.

* If a temporary stoppage of the SnapMirror replication is not acceptable, you can create a snapshot in the SnapMirror source volume, and then use that snapshot to create the FlexClone volume. (If you are creating the FlexClone volume from the destination volume, you must wait until that snapshot replicates to the SnapMirror destination volume.)
+
This method of creating a snapshot in the SnapMirror source volume allows you to create the clone without locking a snapshot that is in use by SnapMirror.

// ONTAPDOC-2119/GH-1818 2024-6-25