---
permalink: volumes/create-efficiency-policy-task.html
sidebar: sidebar
keywords: create, volume efficiency policy, run, efficiency, operation, volume, policy
summary: "You can create a volume efficiency policy to run efficiency operations on a volume."
---
= Create a volume efficiency policy
:icons: font
:imagesdir: ../media/

[.lead]
You can create a volume efficiency policy to run deduplication or data compression followed by deduplication on a volume for a specific duration, and specify the job schedule using the `volume efficiency policy create` command.

.Before you begin

You must have created a cron schedule using the `job schedule cron create` command. For more information about managing the cron schedules, see the link:../system-admin/index.html[System administration reference].

.About this task

An SVM administrator with default predefined roles cannot manage the deduplication policies. However, the cluster administrator can modify the privileges assigned to an SVM administrator by using any customized roles. For more information about the SVM administrator capabilities, see link:../authentication/index.html[Administrator authentication and RBAC].

[NOTE]
====
You can run deduplication or data compression operations at a scheduled time, or by creating a schedule with a specific duration, or by specifying a threshold percentage, which waits for the new data to exceed the threshold and then triggers the deduplication or data compression operation. This threshold value is the percentage of the total number of blocks used in the volume. For example, if you set the threshold value on a volume to 20% when the total number of blocks used on the volume is 50%, data deduplication or data compression triggers automatically when new data written on the volume reaches 10% (20% of 50% blocks used). If required, you can obtain the total number of blocks used from the `df` command output.
====

.Steps

. Use the `volume efficiency policy create` command to create a volume efficiency policy.

.Examples

The following command creates a volume efficiency policy named pol1 that triggers an efficiency operation daily:

`volume efficiency policy create -vserver vs1 -policy pol1 -schedule daily`

The following command creates a volume efficiency policy named pol2 that triggers an efficiency operation when the threshold percentage reaches 20%:

`volume efficiency policy create -vserver vs1 -policy pol2 -type threshold -start-threshold-percent 20%`

// 2022 OCT 10, BURT 1376065
// 2021 NOV 15, BURT 1376065 
// ONTAPDOC-2119/GH-1818 2024-6-25
