---
permalink: volumes/create-flexclone-file-flexclone-lun-task.html
sidebar: sidebar
keywords: create, flexclone file, flexclone lun
summary: "You can create space-efficient and time-efficient clones of files and LUNs present in FlexVol volumes or FlexClone volumes by using the volume file clone create command."
---
= Create a FlexClone file or FlexClone LUN
:icons: font
:imagesdir: ../media/

[.lead]
You can create space-efficient and time-efficient clones of files and LUNs present in FlexVol volumes or FlexClone volumes by using the `volume file clone create` command.

.What you'll need

* The FlexClone license must be installed on the cluster. This license is included with link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one[ONTAP One].
* If multiple block ranges are used for sub-LUN cloning or sub-file cloning, the block numbers must not overlap.
* If you are creating a sub-LUN or sub-file on volumes with adaptive compression enabled, the block ranges must not be misaligned.
+
This means that the source start block number and destination start block number must either be even aligned or odd aligned.

.About this task

Depending on the privileges assigned by the cluster administrator, an SVM administrator can create FlexClone files and FlexClone LUNs.

You can specify the autodelete setting for FlexClone files and FlexClone LUNs when you create and modify clones. By default, the autodelete setting is disabled.

You can overwrite an existing FlexClone file or FlexClone LUN when you create a clone by using the `volume file clone create` command with the `-overwrite-destination` parameter.

When the node reaches its maximum split load, the node temporarily stops accepting requests to create FlexClone files and FlexClone LUNs and issues an `EBUSY` error message. When the split load for the node falls below the maximum, the node accepts requests to create FlexClone files and FlexClone LUNs again. You should wait until the node has capacity to create the clones before trying the create request again.

.Steps

. Create a FlexClone file or FlexClone LUN by using the `volume file clone create` command.
+
The following example shows how you can create a FlexClone file file1_clone of the parent file file1_source in the volume vol1:
+
----
cluster1::> volume file clone create -vserver vs0 -volume vol1 -source-path /file1_source -destination-path /file1_clone
----
+
For more information about using this command, see the man pages.

.Related information

link:../concepts/manual-pages.html[ONTAP command reference]

// 2024-Mar-28, ONTAPDOC-1366