---
permalink: volumes/default-quotas-concept.html
sidebar: sidebar
keywords: default quotas, quotas, quota, default
summary: "You can use default quotas to apply a quota to all instances of a given quota type. Default quotas also enable you to modify quotas easily."
---
= How default quotas work
:icons: font
:imagesdir: ../media/
:hardbreaks-option:

[.lead]
You can use default quotas to apply a quota to all instances of a given quota type. For example, a default user quota affects all users on the system for the specified FlexVol volume or qtree. In addition, default quotas enable you to modify your quotas easily.

You can use default quotas to automatically apply a limit to a large set of quota targets without having to create separate quotas for each target. For example, if you want to limit most users to 10 GB of disk space, you can specify a default user quota of 10 GB of disk space instead of creating a quota for each user. If you have specific users for whom you want to apply a different limit, you can create explicit quotas for those users. (Explicit quotas--quotas with a specific target or list of targets--override default quotas.)

In addition, default quotas enable you to use resizing rather than reinitialization when you want quota changes to take effect. For example, if you add an explicit user quota to a volume that already has a default user quota, you can activate the new quota by resizing.

Default quotas can be applied to all three types of quota target (users, groups, and qtrees).

Default quotas do not necessarily have specified limits; a default quota can be a tracking quota.

A quota is indicated by a target that is either an empty string ("") or an asterisk (*), depending on the context:

* When you create a quota using the `volume quota policy rule create` command, setting the `-target` parameter to an empty string ("") creates a default quota.
* In the `volume quota policy rule create` command, the `-qtree` parameter specifies the name of the qtree to which the quota rule applies. This parameter is not applicable for tree type rules. For user or group type rules at the volume level, this parameter should contain "".
* In the output of the `volume quota policy rule show` command, a default quota appears with an empty string ("") as the target.
* In the output of the `volume quota report` command, a default quota appears with an asterisk (*) as the ID and Quota Specifier.

== Default user quota example

The following quota rule uses a default user quota to apply a 50-MB limit on each user for vol1:

----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "" -qtree "" -disk-limit 50m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -          -
----

If any user on the system enters a command that would cause that user's data to take up more than 50 MB in vol1 (for example, writing to a file from an editor), the command fails.

//19 april 2022, issue #459
// ONTAPDOC-1818 2024-6-26