---
permalink: volumes/determine-space-usage-volume-aggregate-concept.html
sidebar: sidebar
keywords: determine, space usage, volume, aggregate
summary: "Enabling a feature in ONTAP might consume space that you are not aware of or more space than you expected. ONTAP helps you determine how space is being consumed by providing three perspectives from which to view space: the volume, a volume’s footprint within the aggregate, and the aggregate."
---
= Determine space usage in a volume or aggregate
:icons: font
:imagesdir: ../media/

[.lead]
Enabling a feature in ONTAP might consume space that you are not aware of or more space than you expected. ONTAP helps you determine how space is being consumed by providing three perspectives from which to view space: the volume, a volume's footprint within the aggregate, and the aggregate.

A volume can run out of space due to space consumption or insufficient space within the volume, aggregate, or a combination of both. By seeing a feature-oriented breakdown of space usage from different perspectives, you can assess which features you might want to adjust or turn off, or take other action (such as increase the size of the aggregate or volume).

You can view space usage details from any of these perspectives:

* The volume's space usage
+
This perspective provides details about space usage within the volume, including usage by Snapshot copies.
+
You see a volume's space usage by using the `volume show-space` command.

* The volume's footprint within the aggregate
+
This perspective provides details about the amount of space each volume is using in the containing aggregate, including the volume's metadata.
+
You see a volume's footprint with the aggregate by using the `volume show-footprint` command.

* The aggregate's space usage
+
This perspective includes totals of the volume footprints of all of the volumes contained in the aggregate, space reserved for aggregate Snapshot copies, and other aggregate metadata.
+
You can see the aggregate's space usage by using the `storage aggregate show-space` command.

Certain features, such as tape backup and deduplication, use space for metadata both from the volume and directly from the aggregate. These features show different space usage between the volume and volume footprint perspectives.
