---
permalink: volumes/disable-deduplication-volume-task.html
sidebar: sidebar
keywords: disabling, deduplication, volume
summary: "You can disable postprocess deduplication and inline deduplication independently on a volume."
---
= Disable deduplication on a volume
:icons: font
:imagesdir: ../media/

[.lead]
You can disable postprocess deduplication and inline deduplication independently on a volume.

.What you'll need

Stop any volume efficiency operation that is currently active on the volume: `volume efficiency stop`

Learn more about `volume efficiency stop` in the link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-stop.html[ONTAP command reference^].

.About this task

If you have enabled data compression on the volume, running the `volume efficiency off` command disables data compression. Learn more about `volume efficiency off` in the link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-off.html[ONTAP command reference^].

.Choices

* Use the `volume efficiency off` command to disable both postprocess deduplication and inline deduplication.
+
The following command disable both postprocess deduplication and inline deduplication on volume VolA:
+
`volume efficiency off -vserver vs1 -volume VolA`

* Use the `volume efficiency modify` command with the `-policy` option set to `inline only` to disable postprocess deduplication, but inline deduplication remains enabled.
+
The following command disables postprocess deduplication, but inline deduplication remains enabled on volume VolA:
+
`volume efficiency modify -vserver vs1 -volume VolA -policy inline-only`

* Use the `volume efficiency modify` command with the `-inline-deduplication` option set to `false` to disable inline deduplication only.
+
The following command disables only inline deduplication on volume VolA:
+
`volume efficiency modify -vserver vs1 -volume VolA -inline-deduplication false`
+
Learn more about `volume efficiency modify` in the link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html[ONTAP command reference^].


// 2025 Mar 19, ONTAPDOC-2758