---
permalink: volumes/display-file-inode-usage-task.html
sidebar: sidebar
keywords: flexvol, file limit, inode, maximum
summary: "Determine whether you need to increase the number of (public) inodes for your FlexVol volumes to prevent them from hitting their file limit."
---
= Determine file and inode usage for a volume
:icons: font
:imagesdir: ../media/

[.lead]
FlexVol volumes have a maximum number of files that they can contain. You can use a CLI command to determine whether you need to increase the number of (public) inodes for your FlexVol volumes to prevent them from hitting their file limit.

.About this task

Public inodes can be either free (they are not associated with a file) or used (they point to a file). The number of free inodes for a volume is the total number of inodes for the volume minus the number of used inodes (the number of files).

If qtree-level and volume-level shares exist on the same FlexVol or SCVMM pool, the qtrees appear as directories on the FlexVol share. Therefore, you need to be careful not to delete them accidentally.

.Steps

. To display inode usage for a volume, enter the following command:
+
[source, cli]
----
volume show -vserver <SVM_name> -volume <volume_name> -fields files
----

.Example

----
cluster1::*> volume show -vserver vs1 -volume vol1 -fields files
Vserver Name: vs1
Files Used (for user-visible data): 98
----

//2024-7-24 cfq ontapdoc-2120
//2023 Sept 6, Git Issue 1079