---
permalink: volumes/enable-inline-data-compaction-fas-systems-task.html
sidebar: sidebar
keywords: enable, inline, data compaction, fas systems, hdd aggregate, volume efficiency
summary: "Enable inline data compaction on FAS systems with Flash Pool (hybrid) aggregates or HDD aggregates at the volume or aggregate level."
---
= Enable inline data compaction for FAS systems
:icons: font
:imagesdir: ../media/

[.lead]
YYou can enable inline data compaction on FAS systems with Flash Pool (hybrid) aggregates or HDD aggregates at the volume level by using the `volume efficiency` cluster shell command. Data compaction is disabled by default for volumes created on FAS systems. Learn more about `volume efficiency` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+efficiency[ONTAP command reference^].

.About this task

To enable inline data compaction on a volume, its `-space-guarantee` option must be set to `none`. Enabling data compaction on a volume on an HDD aggregate uses additional CPU resources.

.Steps

. Change to the advanced privilege level:
+
[source, cli]
----
set -privilege advanced
----
+
Learn more about `set` in the link:https://docs.netapp.com/us-en/ontap-cli/set.html[ONTAP command reference^].

. Check the data compaction state of the volumes and aggregates for the desired node:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----
+
Learn more about `volume efficiency show` in the link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html[ONTAP command reference^].

. Enable data compaction on volume:
+
[source, cli]
----
volume efficiency modify -volume <volume_name> -data-compaction true
----
+
Learn more about `volume efficiency modify` in the link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html[ONTAP command reference^].
+
[NOTE] 
====
If data compaction is set to `false` for either an aggregate or a volume, then compaction fails. Enabling compaction does not compact existing data; only new writes to the system are compacted. The `volume efficiency start` command contains more information about how to compact existing data. Learn more about `volume efficiency start` in the link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-start.html[ONTAP command reference^].
====
+
. View the compaction statistics:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----

// 2025 Mar 18, ONTAPDOC-2758
// 2025 Mar 17, GH-1662
// 2025 Mar 10, ONTAPDOC-2617
// 16 may 2024, ontapdoc-1986
// BURT 1392595, update 21 October 2021