---
permalink: volumes/enable-temperature-sensitive-efficiency-concept.html
sidebar: sidebar
keywords: enable, temperature, sensitive, storage, efficiency, sequential packing
summary: "Temperature sensitive storage efficiency was introduced in ONTAP 9.8 and is enabled automatically on newly created thin-provisioned AFF volumes. Beginning with ONTAP 9.10.1, new AFF volumes are created by default with 8k adaptive compression on the volume (default mode). If temperature sensitive storage efficiency is desired, it must be explicitly set to enable auto adaptive compression and inline deduplication, cross volume inline deduplication, and cross volume background deduplication on the volume (efficient mode)."
---
= Temperature-sensitive storage efficiency overview
:icons: font
:imagesdir: ../media/

[.lead]
Temperature-sensitive storage efficiency was introduced in ONTAP 9.8 and was enabled automatically on newly created thin-provisioned AFF volumes. Beginning with ONTAP 9.10.1, new AFF volumes are created by default with 8k adaptive compression on the volume (default mode). If temperature sensitive storage efficiency is desired, it must be explicitly set to enable auto adaptive compression and inline deduplication, cross volume inline deduplication, and cross volume background deduplication on the volume (efficient mode).

Beginning with ONTAP 9.13.1, temperature-sensitive storage efficiency adds sequential packing of contiguous physical blocks to improve storage efficiency. Volumes that have temperature-sensitive storage efficiency enabled automatically have sequential packing enabled when you upgrade systems to ONTAP 9.13.1. After sequential packing is enabled, you must manually repack existing data.

Accomplishing storage efficiency depends on a correct assessment of your data’s “temperature;” meaning, how frequently the data is accessed. Temperature-sensitive storage efficiency is determined by the temperature of a volume’s data. For cold data, larger data blocks are compressed, and for hot data, which is overwritten more often, smaller data blocks are compressed, making the process more efficient.

Both storage efficiency modes are supported on FabricPool-enabled aggregates and with all tiering policy types.

== Upgrade considerations

When upgrading to ONTAP 9.10.1, existing volumes are assigned a storage efficiency mode based on the type of compression currently enabled on the volumes. During an upgrade, volumes with compression enabled are assigned the default mode, and volumes with temperature-sensitive storage efficiency enabled are assigned the efficient mode. If compression is not enabled, storage efficiency mode remains blank.

// 2023-Apr-10, ONTAPDOC-877
// 2021-12-21, add missing 9.10.1 info in lead
