---
permalink: volumes/enable-disable-background-deduplication-aff-task.html
sidebar: sidebar
keywords: manage, aggregate-level, background, deduplication, aff systems
summary: "Enable or disable aggregate-level deduplication for volumes or determine whether the feature is turned on."
---
= Manage aggregate-level background deduplication on AFF systems
:icons: font
:imagesdir: ../media/

[.lead]
Aggregate-level deduplication eliminates duplicate blocks across volumes belonging to the same aggregate. Beginning with ONTAP 9.3, you can perform aggregate-level deduplication in the background on AFF systems. The feature is enabled by default for all newly created volumes and all upgraded volumes with volume background deduplication turned on.

.About this task

The operation is triggered automatically when a large enough percentage of the change log has been populated. No schedule or policy is associated with the operation.

Beginning with ONTAP 9.4, AFF users can also run the aggregate-level deduplication scanner to eliminate duplicates of existing data across volumes in the aggregate. You can use the `storage aggregate efficiency cross-volume-dedupe start` command with the `-scan-old-data=true` option to start the scanner:

----
cluster-1::> storage aggregate efficiency cross-volume-dedupe start -aggregate aggr1 -scan-old-data true
----

Deduplication scanning can be time consuming. You might want to run the operation in off-peak hours.

[NOTE]
====
Aggregate-level background deduplication is sometimes referred to as cross-volume background deduplication.
====

.Steps

. Manage aggregate-level background deduplication on AFF systems:
+
[cols="2*",options="header"]
|===
| If you want to...| Use this command
a|
Enable aggregate-level background deduplication
a|
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe true`
a|
Disable aggregate-level background deduplication
a|
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe false`
a|
Display aggregate-level background deduplication status
a|
`aggregate efficiency cross-volume-dedupe show`
|===
