---
permalink: volumes/enable-logical-space-reporting-enforcement-task.html
sidebar: sidebar
keywords: enable, logical, space, reporting, enforcement
summary: "Beginning with ONTAP 9.4, you can enable logical space reporting. Beginning with 9.5, you can enable logical space enforcement, or both reporting and enforcement together."
---
= Enable logical space reporting and enforcement
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.4, you can enable logical space reporting. Beginning with 9.5, you can enable logical space enforcement, or both reporting and enforcement together.

.About this task

In addition to enabling logical space reporting and enforcement at the individual volume level, you can enable them at the SVM level for every volume that supports the functionality. If you enable logical space features for the entire SVM, you can also disable them for individual volumes.

Beginning with ONTAP 9.8, if you enable logical space reporting on a SnapMirror source volume, it is automatically enabled on the destination volume after the transfer.

[NOTE]
If the enforcement option is enabled on a SnapMirror source volume, the enforcement setting is transferred to the destination volume. However, because the destination volume does not support enforcement, the destination will report logical space consumption but not honor its enforcement.

.Choices

* Enable logical space reporting for a volume:
+
`volume modify -vserver __svm_name__ -volume _volume_name_ -size _volume_size_ -is-space-reporting-logical true`
* Enable logical space enforcement for a volume:
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-enforcement-logical true`
* Enable logical space reporting and enforcement together for a volume:
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-reporting-logical true -is-space-enforcement-logical true`
* Enable logical space reporting or enforcement for a new SVM:
+
`+vserver create -vserver _svm_name_ -rootvolume root-_volume_name_ -rootvolume-security-style unix -data-services {desired-data-services} [-is-space-reporting-logical true] [-is-space-enforcement-logical true]+`
* Enable logical space reporting or enforcement for an existing SVM:
+
`+vserver modify -vserver _svm_name_ -data-services {desired-data-services} [-is-space-reporting-logical true][-is-space-enforcement-logical true]+`
