---
permalink: volumes/enable-large-vol-file-support-task.html
sidebar: sidebar
keywords: create, modify, volume, large file, large volume
summary: "You can enable support for large volumes and files when you create a new volume or you can modify an existing volume."
---
= Enable large volume and large file support in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.12.1 P2, you can create a new volume or modify an existing volume to enable support for a maximum volume size of 300TB and a maximum file (LUN) size of 128TB. 

.Before you begin

* ONTAP 9.12.1 P2 or later is installed on the cluster.
* If you are enabling large volume support on the source cluster in a SnapMirror relationship, you must have ONTAP 9.12.1 P2 or later installed on the cluster hosting the source volume as well as the cluster hosting the destination volume. 
* You are a cluster or SVM administrator.
* Learn more about the commands described in this procedure in the link:https://docs.netapp.com/us-en/ontap-cli/[ONTAP command reference^].

== Create a new volume

.Step

. Create a volume with large volume and file support enabled:
+
[source,cli] 
----
volume create -vserver <svm_name> -volume <volume_name> -aggregate <aggregate_name> -is-large-size-enabled true
----

.Example
The following example creates a new volume with large volume and file size support enabled.

----
volume create -vserver vs1 -volume big_vol1 -aggregate aggr1 -is-large-size-enabled true
----

== Modify an existing volume

.Step

. Modify a volume to enable large volume and file support:
+
[source,cli]
----
volume modify -vserver <svm_name> -volume <volume_name> -is-large-size-enabled true
----
+
.Example
The following example modifies an existing volume to support large volume and file size.
+
----
volume modify -vserver vs2 -volume data_vol -is-large-size-enabled true
----

. Activate the new configuration settings by remounting the volume:
+
[source,cli]
----
volume unmount -vserver <svm_name> -volume <volume_name>
----
+
[source,cli]
----
volume mount -vserver <svm_name> -volume <volume_name>
----


.Related information
* link:../volumes/create-volume-task.html[Create a volume]
* link:https://docs.netapp.com/us-en/ontap-cli/[Command Reference]

// 2024 Dec 05, ONTAPDOC-2569
// 2024 Sep 09 ontapdoc-2331
// 2024-7-9 ontapdoc-2192
// 2024 Mar 07 Jira 1677
// 2023-Aug-21, ONTAPDOC-1791