---
permalink: volumes/enable-temperature-sensitive-efficiency-concept.html
sidebar: sidebar
keywords: enable, temperature, sensitive, storage, efficiency
summary: "Temperature sensitive storage efficiency was introduced in ONTAP 9.8 and is enabled automatically on newly created thin-provisioned AFF volumes. Beginning with ONTAP 9.10.1, you can enable temperature-sensitive storage efficiency on newly created AFF volumes and on existing AFF volumes. Additionally, two storage efficiency modes are introduced: default, which is the performance-based mode, which is enabled by default, and efficient mode, which you must enable."
---
= Temperature-sensitive storage efficiency overview
:icons: font
:imagesdir: ../media/

[.lead]
Temperature sensitive storage efficiency was introduced in ONTAP 9.8 and is enabled automatically on newly created thin-provisioned AFF volumes. Accomplishing storage efficiency depends on a correct assessment of your data’s “temperature;” meaning, how frequently the data is accessed.

Accomplishing storage efficiency depends on a correct assessment of your data’s “temperature;” meaning, how frequently the data is accessed. Temperature-sensitive storage efficiency is determined by the temperature of a volume’s data. For cold data, larger data blocks are compressed, and for hot data, which is overwritten more often, smaller data blocks are compressed, making the process more efficient.

Both storage efficiency modes are supported on FabricPool-enabled aggregates and with all tiering policy types.

== Upgrade considerations

When upgrading to Data ONTAP 9.10.1, existing volumes are assigned a storage efficiency mode based on the type of compression currently enabled on the volumes. During an upgrade, volumes with compression enabled are assigned the default mode, and volumes with temperature-sensitive storage efficiency enabled are assigned the efficient mode. If compression is not enabled, storage efficiency mode remains blank.
