---
permalink: volumes/enable-inline-data-compaction-fas-systems-task.html
sidebar: sidebar
keywords: enable, inline, data compaction, fas systems, hdd aggregate, volume efficiency
summary: "Enable inline data compaction on FAS systems with Flash Pool (hybrid) aggregates or HDD aggregates at the volume or aggregate level."
---
= Enable inline data compaction for FAS systems
:icons: font
:imagesdir: ../media/

[.lead]
You can enable inline data compaction on FAS systems with Flash Pool (hybrid) aggregates or HDD aggregates at the volume or aggregate level by using the `volume efficiency` cluster shell command. Data compaction is disabled by default for FAS systems.

.About this task

If you enable data compaction at the aggregate level, data compaction is enabled on any new volume that is created with a volume space guarantee of `none` in the aggregate. Enabling data compaction on a volume on an HDD aggregate uses additional CPU resources.

.Steps

. Change to the advanced privilege level:
+
[source, cli]
----
set -privilege advanced
----

. Check the data compaction state of the volumes and aggregates for the desired node:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----

. Enable data compaction on volume:
+
[source, cli]
----
volume efficiency modify -volume <volume_name> -data-compaction true
----
+
[NOTE] 
====
If data compaction is set to `false` for either an aggregate or a volume, then compaction fails. Enabling compaction does not compact existing data; only new writes to the system are compacted. The `volume efficiency start` command contains more information about how to compact existing data (in ONTAP 9.1 and later). 
For more information, see the link:http://docs.netapp.com/us-en/ontap-cli[ONTAP 9 command reference^].
====
+
. View the compaction statistics:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----

// 16 may 2024, ontapdoc-1986
// BURT 1392595, update 21 October 2021