---
permalink: volumes/enable-large-vol-file-support-task.html
sidebar: sidebar
keywords: create, modify, volume, large file, large volume
summary: "You can enable support for large volumes and files when you create a new volume or you can modify an existing volume."
---
= Enable large volume and large file support
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.12.1 P2, you can create a new volume or modify an existing volume to enable support for a maximum volume size of 300TB and a maximum file (LUN) size of 128TB. 

.About this task
Large volume and file support is disabled by default.

.Before you begin

* ONTAP 9.12.1 P2 or later is installed on the cluster.
* You are a cluster or SVM administrator.

== Create a new volume

.Step
. Create a volume with large volume and file support enabled:
+
`volume create -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_ -is-large-size-enabled true`

.Example
The following example creates a new volume with large volume and file size support enabled.

----
`volume create -vserver vs1 -volume big_vol1 -aggregate aggr1 -is-large-size-enabled true`
----

== Modify an existing volume
. Modify a volume to enable large volume and file support:
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_ -is-large-size-enabled true`

.Example
The following example modifies an existing volume to support large volume and file size.

----
`volume modify -vserver vs2 -volume data_vol -aggregate aggr1 -is-large-size-enabled true`
----