---
permalink: volumes/enable-storage-efficiency-visualization-concept.html
sidebar: sidebar
keywords: storage, efficiency, visualization, storage aggregate
summary: "Show different views of the storage efficiency of all the aggregates in your system."
---
= Storage efficiency visualization
:icons: font
:imagesdir: ../media/

[.lead]
Use the `storage aggregate show-efficiency` command to display information about the storage efficiency of all the aggregates in your system.

The `storage aggregate show-efficiency` command has three different views that can be invoked by passing command options.

== Default view

The default view displays the overall ratio for each of the aggregates.

`cluster1::> storage aggregate show-efficiency`

== Detailed view

Invoke the detailed view with the `-details` command option. This view displays the following:

* Overall efficiency ratio for each of the aggregates.
* Overall ratio without snapshots.
* Ratio split for the following efficiency technologies: volume deduplication, volume compression, snapshots, clones, data compaction, and aggregate inline deduplication.

`cluster1::> storage aggregate show-efficiency -details`

== Advanced view

The advanced view is similar to the detailed view and displays both logical and physical used details.

You must run this command at the advanced privilege level. Switch to advanced privilege by using the `set -privilege advanced` command.

The command prompt changes to `cluster::*>`.

`cluster1::> set -privilege advanced`

Invoke the advanced view with the `-advanced` command option.

`cluster1::*> storage aggregate show-efficiency -advanced`

To view ratios for a single aggregate individually invoke the `-aggregate _aggregate_name_` command. This command can be run at the admin level, as well as the advanced privilege level.

`cluster1::> storage aggregate show-efficiency -aggregate aggr1`

//2024-7-24 cfq ontapdoc-2120
// 2023 DEC 15, ontap-issues-1184