---
permalink: volumes/enforced-quotas-differ-configured-concept.html
sidebar: sidebar
keywords: why, enforced, quotas, differ, configured, quotas
summary: "Understand how enforced quotas differ from configured quotes so that you can compare enforced quotas shown in quota reports to the quotas that you configured"
---
= Why enforced quotas differ from configured quotas
:icons: font
:imagesdir: ../media/

[.lead]
Enforced quotas differ from configured quotas because derived quotas are enforced without being configured but configured quotas are enforced only after they are successfully initialized. Understanding these differences can help you compare the enforced quotas that are shown in quota reports to the quotas that you configured.

Enforced quotas, which appear in quota reports, might differ from the configured quota rules for the following reasons:

* Derived quotas are enforced without being configured as quota rules. ONTAP creates derived quotas automatically in response to default quotas.
* Quotas might not have been reinitialized on a volume after quota rules were configured.
* Errors might have occurred when quotas were initialized on a volume.

// ONTAPDOC-2119/GH-1818