---
permalink: volumes/explicit-quotas-concept.html
sidebar: sidebar
keywords: how to, use, explicit, quotas
summary: "You can use explicit quotas to specify a quota for a specific quota target, or to override a default quota for a specific target."
---
= How you use explicit quotas
:icons: font
:imagesdir: ../media/

[.lead]
You can use explicit quotas to specify a quota for a specific quota target, or to override a default quota for a specific target.

An explicit quota specifies a limit for a particular user, group, or qtree. An explicit quota replaces any default quota that is in place for the same target.

When you add an explicit user quota for a user that has a derived user quota, you must use the same user mapping setting as the default user quota. Otherwise, when you resize quotas, the explicit user quota is rejected because it is considered a new quota.

Explicit quotas only affect default quotas at the same level (volume or qtree). For example, an explicit user quota for a qtree does not affect the default user quota for the volume that contains that qtree. However, the explicit user quota for the qtree overrides (replaces the limits defined by) the default user quota for that qtree.

.Examples of explicit quotas

The following quota rules define a default user quota that limits all users in vol1 to 50 MB of space. However, one user, jsmith, is allowed 80 MB of space, because of the explicit quota (shown in bold):

----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "" -qtree "" -disk-limit 50m

cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "jsmith" -qtree "" -disk-limit 80m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1
Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -          -
user   jsmith    ""      off          80MB        -       -        -          -
----

The following quota rule restricts the specified user, represented by four IDs, to 500MB of disk space and 10,000 files in the vol1 volume:

----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target " jsmith,corp\jsmith,engineering\john smith,S-1-5-32-544" -qtree "" -disk-limit 550m -file-limit 10000
cluster1::> volume quota policy rule show -vserver vs0 -volume vol1                                                                                                         
Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   "jsmith,corp\jsmith,engineering\john smith,S-1-5-32-544"  "" off  550MB  -  10000  -      -

----

The following quota rule restricts the eng1 group to 150 MB of disk space and an unlimited number of files in the proj1 qtree:

----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol2 -policy-name default -type group -target "eng1" -qtree "proj1" -disk-limit 150m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol2
Vserver: vs0               Policy: default           Volume: vol2
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
group  eng1      proj1   off         150MB        -       -        -          -
----

The following quotas entry restricts the proj1 qtree in the vol2 volume to 750 MB of disk space and 75,000 files:

----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol2 -policy-name default -type tree -target "proj1" -disk-limit 750m -file-limit 75000

cluster1::> volume quota policy rule show -vserver vs0 -volume vol2
Vserver: vs0               Policy: default           Volume: vol2
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
tree   proj1     ""      -           750MB        -   75000        -          -
----
