---
permalink: volumes/flexclone-efficient-copies-concept.html
sidebar: sidebar
keywords: use, flexclone, volumes, create, efficient, copies, flexvol volumes
summary: "FlexClone volumes are writable, space-efficient, point-in-time copies of a parent FlexVol volume that can be managed for data protection or other purposes."
---
= FlexClone volume use overview
:icons: font
:imagesdir: ../media/

[.lead]
FlexClone volumes are writable, point-in-time copies of a parent FlexVol volume. FlexClone volumes are space-efficient because they share the same data blocks with their parent FlexVol volumes for common data. The Snapshot copy used to create a FlexClone volume is also shared with the parent volume.

You can clone an existing FlexClone volume to create another FlexClone volume. You can also create a clone of a FlexVol volume containing LUNs and LUN clones.

You can also split a FlexClone volume from its parent volume. Beginning with ONTAP 9.4, for non-guaranteed volumes on AFF systems, the split operation for FlexClone volumes shares the physical blocks and does not copy the data. Therefore, splitting of FlexClone volumes on AFF systems is faster than the FlexClone splitting operation in other FAS systems in ONTAP 9.4 and later releases.

You can create two types of FlexClone volumes: read-write FlexClone volumes and data protection FlexClone volumes. While you can create a read-write FlexClone volume of a regular FlexVol volume, you must use only a SnapVault secondary volume to create a data protection FlexClone volume.

// 2022-6-6, issue #524 
