---
permalink: volumes/index.html
sidebar: sidebar
keywords: decide, locgical, storage, management, overview, flexvol, volumes, manage, create, flexclone, deduplication compression
summary: "This content describes how to work with ONTAP FlexVol volumes. It shows you how to create and manage FlexVol volumes, how to use FlexClone technology to create efficient copies of volumes, files, and LUNs, how to create qtrees and quotas, and how to manage efficiency features like deduplication and compression."
---
= Logical storage management overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to work with ONTAP FlexVol volumes. It shows you how to create and manage FlexVol volumes, how to use FlexClone technology to create efficient copies of volumes, files, and LUNs, how to create qtrees and quotas, and how to manage efficiency features like deduplication and compression.

*You should use this content* under the following circumstances:

* You want to understand the range of ONTAP FlexVol volume capabilities and storage efficiency features.
* You want to use the command-line interface (CLI), not ONTAP System Manager or an automated scripting tool.

*If you do not want to use FlexVol volumes* and want to use FlexGroup volumes instead, you should choose the following documentation:

* link:../flexgroup/index.html[FlexGroup volumes management]

*If you require additional configuration or conceptual information*, you should choose among the following documentation:

* Conceptual background for volumes
+
link:../concepts/index.html[ONTAP concepts]

* Best practices for moving volumes
+
https://docs.netapp.com/us-en/ontap-sm-classic/volume-admin/index.html[Volume move management]

* Disk and aggregate management
+
link:../disks-aggregates/index.html[Disk and aggregate management]

* Command reference
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands]

* Technical Reports (TRs), which include additional information about ONTAP technology and interaction with external services
 ** http://www.netapp.com/us/media/tr-3483.pdf[NetApp Technical Report 3483: Thin Provisioning in a NetApp SAN or IP SAN Enterprise Environment]
 ** http://www.netapp.com/us/media/tr-3563.pdf[NetApp Technical Report 3563: NetApp Thin Provisioning Increases Storage Utilization With On Demand Allocation]
