---
permalink: volumes/logical-space-reporting-concept.html
sidebar: sidebar
keywords: what, logical, space, reporting, shows
summary: "When you enable logical space reporting on a volume, your system displays the logical used and available space in addition to the total space in a volume."
---
= Logical space reporting
:icons: font
:imagesdir: ../media/

[.lead]
When you enable logical space reporting on a volume, your system can display the amount of logical used and available space in addition to the total space in a volume. In addition, users on Linux and Windows client systems can see logical used and available space instead of physical used and physical available space.

Definitions:

* Physical space refers to the physical blocks of storage available or used in the volume.
* Logical space refers to the usable space in a volume.
* Logical space used is physical space used plus savings from storage efficiency features (such as deduplication and compression) that have been configured.

Beginning with ONTAP 9.5, you can enable logical space enforcement together with space reporting.

When enabled, logical space reporting displays the following parameters with the `volume show` command:
[cols="25%,75%",options="header"]
|===
| Parameter| Meaning
a|
`-logical-used`
a|
Displays information only about the volume or volumes that have the specified logical used size. This value includes all the space saved by the storage efficiency features along with the physically used space. This does not include snapshot reserve but does consider snapshot spill.

a|
`-logical-used-by-afs`
a|
Displays information only about the volume or volumes that have the specified logical size used by the active file system. This value differs from the``-logical-used`` value by the amount of snapshot spill that exceeds the snapshot reserve.

a|
`-logical-available`
a|
When only logical space reporting is enabled, only physical-available space is displayed. When both space reporting and enforcement are enabled, it displays the amount of free space currently available considering space saved by the storage efficiency features as being used. This does not include the snapshot reserve.

a|
`-logical-used-percent`
a|
Displays the percentage of the current `-logical-used` value with the provisioned size excluding snapshot reserve of the volume.

This value can be greater than 100%, because the `-logical-used-by-afs` value includes efficiency savings in the volume. The `-logical-used-by-afs` value of a volume does not include snapshot spill as used space. The `-physical-used` value of a volume includes Snapshot spill as used space.

a|
`-used`
a|
Displays the amount of space occupied by user data and file system metadata.  It differs from `physical-used` space by the sum of the space that is reserved for future writes and the space that is saved by aggregate storage efficiency.  It includes snapshot spill (the amount of space by which snapshots exceed snapshot reserve). It does not include the snapshot reserve.

|===
Enabling logical space reporting in the CLI also allows the Logical Used Space (%) and Logical Space values to display in System Manager

Client systems see logical space displayed as "`used`" space on the following system displays:

* *df* output on Linux systems
* Space details under Properties using Windows Explorer on Windows systems.

[NOTE]
====
If logical space reporting is enabled without logical space enforcement, the total displayed on client systems can be higher than the provisioned space.
====


//2024 April 12, ONTAPDOC 1871