---
permalink: volumes/logical-space-reporting-enforcement-concept.html
sidebar: sidebar
keywords: logical, space, reporting, enforcement, volumes
summary: "Beginning with ONTAP 9.4, you can allow the logical space used in a volume and the amount of remaining storage space to be displayed to users. Beginning with 9.5, you can limit the amount of logical space consumed by users."
---
= Logical space reporting and enforcement for volumes overview 
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.4, you can allow the logical space used in a volume and the amount of remaining storage space to be displayed to users. Beginning with ONTAP 9.5, you can limit the amount of logical space consumed by users.

Logical space reporting and enforcement are disabled by default.

The following volume types support logical space reporting and enforcement.
[cols="3*",options="header"]
|===
| Volume type| Is space reporting supported?| Is space enforcement supported?
a|
FlexVol volumes
a|
Yes, beginning with ONTAP 9.4
a|
Yes, beginning with ONTAP 9.5
a|
SnapMirror destination volumes
a|
Yes, beginning with ONTAP 9.8
a|
Yes, beginning with ONTAP 9.13.1
a|
FlexGroup volumes
a|
Yes, beginning with ONTAP 9.9.1
a|
Yes, beginning with ONTAP 9.9.1
a|
FlexCache volumes
a|
Origin setting is used at the cache
a|
Not applicable
|===


// 2023-Apr-10, ONTAPDOC-853
// 2023 April 10, Public PR 871

