---
permalink: volumes/migration-compression-type-coexistence.html
sidebar: sidebar
keywords: access control lists, flexclone files, flexclone luns, inheritance, ACL, ACLs, acl, acls, flexclone
summary: "FlexClone files and FlexClone LUNs inherit the access control lists of their parent files and LUNs."
---
= Support for compression type coexistence during ONTAP volume migration
:icons: font
:imagesdir: ../media/

[.lead]
When a volume is migrated between ONTAP systems, the source volume might use a different data compression type than the destination volume.

Supported compression types include secondary, adaptive 8K, and temperature-sensitive storage (TSSE). During migration, these compression types can temporarily coexist on the destination volume as follows:

[options="header", cols="4"]
|===
|Source compression type|Destination compression type|Coexistence supported for migration|Application I/O read/write size

|Secondary|TSSE|Yes|Auto
|Adaptive 8K|TSSE|Yes|Auto
|Secondary|Adaptive 8K|No|Not supported
|===

.Migration from secondary and adaptive 8k compression to TSSE compression

Secondary and 8k adaptive volumes are progressively converted to TSSE through background processes after the migration or as data is rewritten to the destination volume during the migration.  

After a volume is migrated from secondary or adaptive 8K compression to TSSE compression, the *compression type* displayed in the `volume efficiency show` command output does not change even after all existing blocks have been converted. The compression type remains *secondary* for a converted secondary volume and *adaptive* for a converted adaptive 8K volume.

New data written to volumes converted from secondary or adaptive 8K compression is compressed with TSSE.

.Migration from secondary compression to adaptive 8k compression 

Direct coexistence of Secondary and Adaptive 8K compression on the same volume is not supported. 

Learn to link:move-between-secondary-adaptive-compression-task.html[move between secondary and adaptive compression].