---
permalink: volumes/modify-volume-efficiency-policy-task.html
sidebar: sidebar
keywords: modify, volume efficiency policy, volume, efficiency, policy 
summary: "You can modify a volume efficiency policy to run deduplication and data compression for a different duration or change the job schedule."
---
= Modify a volume efficiency policy
:icons: font
:imagesdir: ../media/

[.lead]
You can modify a volume efficiency policy to run deduplication and data compression for a different duration or change the job schedule using the `volume efficiency policy modify` command. Learn more about `volume efficiency policy modify` in the link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-policy-modify.html[ONTAP command reference^].

.Steps

. Use the `volume efficiency policy modify` command to modify a volume efficiency policy.

.Examples

The following command modifies the volume efficiency policy named policy1 to run every hour:

`volume efficiency policy modify -vserver vs1 -policy policy1 -schedule hourly`

The following command modifies a volume efficiency policy named pol2 to threshold 30%:

`volume efficiency policy modify -vserver vs1 -policy pol1 -type threshold -start-threshold-percent 30%`

// 2025 Mar 13, ONTAPDOC-2758