---
permalink: volumes/move-between-secondary-adaptive-compression-task.html
sidebar: sidebar
keywords: move, secondary compression, adaptive compression
summary: "You can switch between secondary compression and adaptive compression depending on the amount of data reads. Adaptive compression is preferred when there are a high volume of random reads on the system and higher performance is required. Secondary compression is preferred when data is written sequentially and higher compression savings are required."
---
= Move between secondary compression and adaptive compression
:icons: font
:imagesdir: ../media/

[.lead]
You can switch between secondary compression and adaptive compression depending on the amount of data reads. Adaptive compression is preferred when there are a high volume of random reads on the system and higher performance is required. Secondary compression is preferred when data is written sequentially and higher compression savings are required.

.About this task

The default compression type is selected based on your aggregates and platform.

.Steps

. Disable data compression on the volume:
+
`volume efficiency modify`
+
The following command disables data compression on volume vol1:
+
`volume efficiency modify -compression false -inline-compression false -volume vol1`

. Change to the advanced privilege level:
+
`set -privilege advanced`
. Decompress the compressed data:
+
`volume efficiency undo`
+
The following command decompresses the compressed data on volume vol1:
+
`volume efficiency undo -vserver vs1 -volume vol1 -compression true`
+
[NOTE]
====
You must verify that you have sufficient space in the volume to accommodate the decompressed data.
====

. Verify that the status of the operation is idle:
+
`volume efficiency show`
+
The following command displays the status of an efficiency operation on volume vol1:
+
`volume efficiency show -vserver vs1 -volume vol1`

. Enable data compression, and then set the type of compression:
+
`volume efficiency modify`
+
The following command enables data compression and sets the compression type as secondary compression on volume vol1:
+
`volume efficiency modify -vserver vs1 -volume vol1 -compression true -compression-type secondary`
+
[NOTE]
====
This step only enables secondary compression on the volume; the data on the volume is not compressed.

  ** To compress existing data on AFF systems, you must run the background compression scanner.

  ** To compress existing data on Flash Pool aggregates or HDD aggregates, you must run the background compression.
====

. Change to the admin privilege level:
+
`set -privilege admin`
. Optional: Enable inline compression:
+
`volume efficiency modify`
+
The following command enables inline compression on volume vol1:
+
`volume efficiency modify -vserver vs1 -volume vol1 -inline-compression true`
