---
permalink: volumes/non-space-reserved-luns-thin-provisioned-concept.html
sidebar: sidebar
keywords: configuration, settings, non-space-reserved, files, luns, thin-provisioned, volumes
summary: "FlexVol volume and file or LUN configuration combination requires storage to be allocated up front and active free space management to prevent lack of space."
---
= Settings for non-space-reserved files or LUNs with thin-provisioned volumes
:icons: font
:imagesdir: ../media/

[.lead]
This FlexVol volume and file or LUN configuration combination requires the smallest amount of storage to be allocated up front, but requires active free space management to prevent errors due to lack of space.

The following settings are required to configure a non-space-reserved files or LUN in a thin-provisioned volume:
[cols="2*",options="header"]
|===
| Volume setting| Value
a|
Guarantee
a|
None
a|
Fractional reserve
a|
0
a|
Snapshot reserve
a|
Any
a|
Snapshot autodelete
a|
Optional
a|
Autogrow
a|
Optional
|===
[cols="2*",options="header"]
|===
| File or LUN setting| Value
a|
Space reservation
a|
Disabled
|===

== Additional considerations

When the volume or aggregate runs out of space, write operations to the file or LUN can fail.

If you do not want to actively monitor free space for both the volume and the aggregate, you should enable Autogrow for the volume and set the maximum size for the volume to the size of the aggregate. In this configuration, you must monitor aggregate free space actively, but you do not need to monitor the free space in the volume.
