---
permalink: volumes/quota-targets-types-concept.html
sidebar: sidebar
keywords: quotas, quota targets, quota types
summary: "Each quota has a specific type. The quota target is derived from the type and specifies the user, group, or qtree to which the quota limits are applied."
---
= Quota targets and types
:icons: font
:imagesdir: ../media/

[.lead]
Each quota has a specific type. The quota target is derived from the type and specifies the user, group, or qtree to which the quota limits are applied.

The following table lists the quota targets, what types of quotas each quota target is associated with, and how each quota target is represented.

[cols="15,15,35,35"]
|===

h| Quota target h| Quota type h| How target is represented h| Notes

a|
user
a|
user quota
a|
UNIX user name UNIX UID

A file or directory whose UID matches the user

Windows user name in pre-Windows 2000 format

Windows SID

A file or directory with an ACL owned by the user's SID

a|
User quotas can be applied for a specific volume or qtree.
a|
group
a|
group quota
a|
UNIX group name UNIX GID

A file or directory whose GID matches the group

a|
Group quotas can be applied for a specific volume or qtree.

NOTE: ONTAP does not apply group quotas based on Windows IDs.

a|
qtree
a|
tree quota
a|
qtree name
a|
Tree quotas are applied to a particular volume and do not affect qtrees in other volumes.
a|
`""`
a|
user quotagroup quota

tree quota

a|
Double quotation marks ("")
a|
A quota target of "" denotes a _default quota_. For default quotas, the quota type is determined by the value of the type field.

|===

// DP - August 5 2024 - ONTAP-2121