---
permalink: volumes/quotas-concept.html
sidebar: sidebar
keywords: why use quotas
summary: "You can use quotas to limit resource usage in FlexVol volumes, to provide notification when resource usage reaches specific levels, or to track resource usage."
---
= Why you use quotas
:icons: font
:imagesdir: ../media/

[.lead]
You can use quotas to limit resource usage in FlexVol volumes, to provide notification when resource usage reaches specific levels, or to track resource usage.

You specify a quota for the following reasons:

* To limit the amount of disk space or the number of files that can be used by a user or group, or that can be contained by a qtree
* To track the amount of disk space or the number of files used by a user, group, or qtree, without imposing a limit
* To warn users when their disk usage or file usage is high

Use default, explicit, derived and tracking quotas to manage disk usage in the most efficient manner.

// Barb 8-OCT-2021 added "Use default, explicit, derived and tracking quotas to manage disk usage in the most efficient manner." as per Satyajit's note during the ONTAP catalyst migration QA (pdf comment)
