---
permalink: volumes/quotas-activated-concept.html
sidebar: sidebar
keywords: quotas, how quotas are activated, quota activation
summary: "New quotas and changes to existing quotas must be activated to take effective. The activation is performed at the volume level. Knowing how quota activation works can help you manage your quotas with less disruption."
---
= Overview of how quotas are activated
:icons: font
:imagesdir: ../media/

[.lead]
New quotas and changes to existing quotas must be activated to take effective. The activation is performed at the volume level. Knowing how quota activation works can help you manage your quotas with less disruption.

Quotas are activated either by _initializing_ (turning them on) or by _resizing_. Turning off quotas and turning them on again is called reinitializing.

The length of the activation process and its impact on quota enforcement depends on the type of activation:

* The initialization process involves two parts: a `quota on` job and a quota scan of the volume's entire file system. The scan begins after the `quota on` job completes successfully. The quota scan can take some time; the more files that the volume has, the longer it takes. Until the scan is finished, quota activation is not complete and quotas are not enforced.
* The resize process involves only a `quota resize` job. Resizing takes less time than a quota initialization because it does not involve a quota scan. During a resize process, quotas continue to be enforced.

By default, the `quota on` and `quota resize` jobs run in the background, which permits you to use other commands at the same time.

Errors and warnings from the activation process are sent to the event management system. If you use the `-foreground` parameter with the `volume quota on` or `volume quota resize` commands, the command does not return until the job is complete; this is useful if you are reinitializing from a script. To display errors and warnings later, you can use the `volume quota show` command with the `-instance` parameter.

Quota activation persists across halts and reboots. The process of quota activation does not affect the availability of the storage system data.

// DP - August 5 2024 - ONTAP-2121