---
permalink: volumes/quotas-applied-concept.html
sidebar: sidebar
keywords: how quotas are applied, configure, quotas
summary: "Understanding how quotas are applied enables you to configure quotas and set the expected limits."
---
= How quotas are applied
:icons: font
:imagesdir: ../media/

[.lead]
Understanding how quotas are applied enables you to configure quotas and set the expected limits.

Whenever an attempt is made to create a file or write data to a file in a FlexVol volume that has quotas enabled, the quota limits are checked before the operation proceeds. If the operation exceeds either the disk limit or the files limit, the operation is prevented.

Quota limits are checked in the following order:

. The tree quota for that qtree (This check is not relevant if the file is being created or written to qtree0.)
. The user quota for the user that owns the file on the volume
. The group quota for the group that owns the file on the volume
. The user quota for the user that owns the file on the qtree (This check is not relevant if the file is being created or written to qtree0.)
. The group quota for the group that owns the file on the qtree (This check is not relevant if the file is being created or written to qtree0.)

The quota with the smallest limit might not be the one that is exceeded first. For example, if a user quota for volume vol1 is 100 GB, and the user quota for qtree q2 contained in volume vol1 is 20 GB, the volume limit could be reached first if that user has already written more than 80 GB of data in volume vol1 (but outside of qtree q2).
