---
permalink: volumes/quota-rules-policies-enforced-quotas-concept.html
sidebar: sidebar
keywords: understand quotas, quota rules, quota policies
summary: "Quotas are defined in quota rules specific to FlexVol volumes. These quota rules are collected together in a quota policy for a storage virtual machine (SVM) and activated on each volume on the SVM."
---
= Understand quotas, quota rules, and quota policies
:icons: font
:imagesdir: ../media/

[.lead]
Quotas are defined in quota rules specific to FlexVol volumes. These quota rules are collected together in a quota policy for a storage virtual machine (SVM) and activated on each volume on the SVM.

A quota rule is always specific to a volume. Quota rules have no effect until quotas are activated on the volume defined in the quota rule.

A quota policy is a collection of quota rules for all the volumes of an SVM. Quota policies are not shared among SVMs. An SVM can have up to five quota policies, which enable you to have backup copies of quota policies. One quota policy is assigned to an SVM at any given time. When you initialize or resize quotas on a volume, you are activating the quota rules in the quota policy that is currently assigned to the SVM.

A quota is the actual restriction that ONTAP enforces or the actual tracking that ONTAP performs. A quota rule always results in at least one quota, and might result in many additional derived quotas. The complete list of enforced quotas is visible only in quota reports.

Activation is the process of triggering ONTAP to create enforced quotas from the current set of quota rules in the assigned quota policy. Activation occurs on a volume-by-volume basis. The first activation of quotas on a volume is called initialization. Subsequent activations are called either reinitialization or resizing, depending on the scope of the changes.

// DP - August 5 2024 - ONTAP-2121