---
permalink: volumes/rehost-nfs-volumes-task.html
sidebar: sidebar
keywords: rehost, nfs, volumes
summary: "You can rehost a volume that serves data using the NFS protocol."
---
= Rehost an NFS volume
:icons: font
:imagesdir: ../media/

[.lead]
You can rehost a volume that serves data using the NFS protocol. To allow clients to continue accessing the data after the rehosting operation, you must associate the volume with the export policy of the SVM as well as manually configure the policies and associated rules.

.About this task

* Rehosting is a disruptive operation.
* If the rehosting operation fails, you might need to reconfigure the volume policies and the associated rules on the source volume.
include::../_include/encypted-volume-rehost.adoc[]
* After the rehost operation, the following volume policies, policy rules, and configurations are lost from the source volume, and must be manually reconfigured on the rehosted volume:
 ** Volume and qtree export policies
 ** Antivirus policies
 ** Volume efficiency policy
 ** Quality of service (QoS) policies
 ** Snapshot policies
 ** Quota rules
 ** ns-switch and name services configuration export policy and rules
 ** User and group IDs

.Before you begin

* The volume must be online.
* Volume management operations, such as volume moves or LUN moves, must not be running.
* Data access to the volume that is being rehosted must be stopped.
* The ns-switch and name services configuration of the target SVM must be configured to support data access of the rehosting volume.
* The user ID and group ID of the volume must be either available in the target SVM or changed on the hosting volume.


.Steps

. Record information about the NFS export policies to avoid losing information on NFS policies in case volume rehost operation fails.
. Unmount the volume from the parent volume:
+
`volume unmount`
. Switch to the advanced privilege level:
+
`set -privilege advanced`
. Rehost the volume on the destination SVM:
+
`volume rehost -vserver _source_svm_ -volume _volume_name_ -destination-vserver _destination_svm_`
+
The default export policy of the destination SVM is applied to the rehosted volume.

. Create the export policy:
+
`vserver export-policy create`
. Update the export policy of the rehosted volume to a user-defined export policy:
+
`volume modify`
. Mount the volume under the appropriate junction path in the destination SVM:
+
`volume mount`
. Verify that the NFS service is running on the destination SVM.
. Resume NFS access to the rehosted volume.
. Update the NFS client credentials and LIF configurations to reflect the destination SVM LIFs.
+
This is because the volume access path (LIFs and junction path) has undergone changes.

.After you finish

You must manually reconfigure the policies and the associated rules on the rehosted volume. See https://docs.netapp.com/us-en/ontap-system-manager-classic/nfs-config/index.html[NFS configuration] for more information.

// DP - August 5 2024 - ONTAP-2121