---
permalink: volumes/resume-efficiency-operation-checkpoint-task.html
sidebar: sidebar
keywords: resume, halted, efficiency, operation
summary: "If an efficiency operation is halted due to a system halt, system disruption, or reboot, you can resume the efficiency operation from the same point it was halted. This helps to save time and resources by not needing to restart the operation from the beginning."
---
= Resume a halted efficiency operation
:icons: font
:imagesdir: ../media/

[.lead]
If an efficiency operation is halted due to a system halt, system disruption, or reboot, you can resume the efficiency operation from the same point it was halted. This helps to save time and resources by not needing to restart the operation from the beginning.

.About this task

If you enabled only deduplication on the volume, deduplication runs on the data. If you enabled both deduplication and data compression on a volume, then data compression runs first, followed by deduplication.

You can view the details of the checkpoint for a volume by using the `volume efficiency show` command.

By default, the efficiency operations resume from checkpoints. However, if a checkpoint corresponding to a previous efficiency operation (the phase when the `volume efficiency start``-scan-old-data` command is run) is older than 24 hours, then the efficiency operation does not resume from the previous checkpoint automatically. In this case, the efficiency operation starts from the beginning. However, if you know that significant changes have not occurred in the volume since the last scan, you can force continuation from the previous checkpoint by using the `-use-checkpoint` option.

.Steps

. Use the `volume efficiency start` command with the `-use-checkpoint` option to resume an efficiency operation.
+
The following command enables you to resume an efficiency operation on new data on volume VolA:
+
`volume efficiency start -vserver vs1 -volume VolA -use-checkpoint true`
+
The following command enables you to resume an efficiency operation on existing data on volume VolA:
+
`volume efficiency start -vserver vs1 -volume VolA -scan-old-data true -use-checkpoint true`

// DP - August 5 2024 - ONTAP-2121