---
permalink: volumes/run-efficiency-operations-manual-task.html
sidebar: sidebar
keywords: starting deduplication manually, starting data compression manually, efficiency, run, sequential packing
summary: "You can run efficiency operations on a volume manually. You might do this when scheduling efficiency operations is not appropriate."
---
= Run an efficiency operation manually
:icons: font
:imagesdir: ../media/

[.lead]
You can run efficiency operations on a volume manually. You might do this when scheduling efficiency operations is not appropriate.

.Before you begin

Depending on the efficiency operation you want to run manually, you must have enabled deduplication or both data compression and deduplication on a volume.

.About this task

This operation is performed using the `volume efficiency start` command. When temperature-sensitive storage efficiency is enabled on a volume, deduplication is run initially followed by data compression.

Deduplication is a background process that consumes system resources while it is running. If the data does not change often in a volume, it is best to run deduplication less frequently. Multiple concurrent deduplication operations running on a storage system lead to a higher consumption of system resources.

You can run a maximum of eight concurrent deduplication or data compression operations per node. If any more efficiency operations are scheduled, the operations are queued.

Beginning with ONTAP 9.13.1, if temperature-sensitive storage efficiency is enabled on a volume, you can run volume efficiency on existing data to take advantage of sequential packing to further improve storage efficiency. 

== Run efficiency manually

.Steps

. Start the efficiency operation on a volume: `volume efficiency start` 

.Example
+
The following command allows you to manually start only deduplication or deduplication followed by logical compression and container compression on the volume VolA
+
----
volume efficiency start -vserver vs1 -volume VolA
----

== Repack existing data

To take advantage of sequential data packing introduced in ONTAP 9.13.1 on volumes with temperature-sensitive storage efficiency enabled, you can repack existing data. You must be in advanced privilege mode to use this command.

.Steps

. Set the privilege level: `set -privilege advanced`
. Repack existing data: `volume efficiency inactive-data-compression start -vserver _vserver_name_ -volume _volume_name_ -scan-mode extended_recompression`

.Example
----
volume efficiency inactive-data-compression start -vserver vs1 -volume vol1 -scan-mode extended_recompression
----

.Related information

* link:run-efficiency-operations-manual-existing-data-task.html[Run efficiency operations manually on existing data]

// DP - August 5 2024 - ONTAP-2121
// 20223-Apr-21, IDR-225
// 2023-Apr-10, ONTAPDOC-877