---
permalink: volumes/set-efficiency-mode-task.html
sidebar: sidebar
keywords: enable, temperature, sensitive, storage, efficiency, mode, performance mode, efficient mode, set, System Manager, higher efficiency
summary: "Beginning with ONTAP 9.10.1, you can set the storage efficiency mode when creating a new AFF volume."
---
= Set storage efficiency mode during volume creation
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.10.1, you can set the storage efficiency mode when creating a new AFF volume. 

.About this task

You can control the storage efficiency mode on a new AFF volume using the parameter `-storage-efficiency-mode`. You can choose between two options to set the storage efficiency mode: `default` or `efficient`.  The storage efficiency mode you choose depends on whether you want greater performance or higher storage efficiency on the volume. The parameter `-storage-efficiency-mode` is not supported on non-AFF volumes or on data protection volumes. 

Performance mode is set by default when you create new AFF volumes with storage efficiency. 

link:enable-temperature-sensitive-efficiency-concept.html[Learn more about temperature-sensitive storage efficiency and storage efficiency modes].

.Steps

. Create a new volume and set the efficiency mode:
+
`volume create -vserver <vserver name> -volume <volume name> -aggregate <aggregate name> -size <volume size> -storage-efficiency-mode <efficient|default>
+
Set `-storage-efficiency-mode` to `efficient` for efficiency mode or to `default` for performance mode.
+
In the following example, aff_vol1 is created with efficiency mode.
----
volume create -vserver vs1 -volume aff_vol1 -aggregate aff_aggr1 -storage-efficiency-mode efficient -size 10g
----

// 2025 Dec 3, Git Issue 1878
// 2025-Apr-17, issue# 1709
// DP - August 12 2024 - ONTAP-2121
// 2023 Oct 6, Git Issue 1129
// 2023-July-7, issue #990
// 2021-11-2, Jira IE-350