---
permalink: volumes/setup-quotas-svm-task.html
sidebar: sidebar
keywords: set up, quotas on svm
summary: "You can set up quotas on a new SVM to management and monitor resource utilization."
---
= Set up quotas on an SVM
:icons: font
:imagesdir: ../media/

[.lead]
You can set up quotas on a new SVM to management and monitor resource utilization.

.About this task
At a high level, there several steps involved when configuring quotas including:

* Create a quota policy
* Add the quota rules to the policy
* Assign the policy to the SVM
* Initialize the quotas on each FlexVol volume on the SVM

.Steps
. Enter the command `vserver show -instance` to display the name of the default quota policy that was automatically created when the SVM was created.
+
If a name was not specified when the SVM was created, the name is "default". You can use the `vserver quota policy rename` command to give the default policy a name.
+
[NOTE]
====
You can also create a new policy by using the `volume quota policy create` command.
====
. Use the `volume quota policy rule create` command to create _any_ of the following quota rules for each volume on the SVM:
 ** Default quota rules for all users
 ** Explicit quota rules for specific users
 ** Default quota rules for all groups
 ** Explicit quota rules for specific groups
 ** Default quota rules for all qtrees
 ** Explicit quota rules for specific qtrees
. Use the `volume quota policy rule show` command to check that the quota rules are configured correctly.
. If you are working on a new policy, use the `vserver modify` command to assign the new policy to the SVM.
. Use the `volume quota on` command to initialize the quotas on each volume on the SVM.
+
You can monitor the initialization process in the following ways:

 ** When you use the `volume quota on` command, you can add the `-foreground` parameter to run the quota on job in the foreground. (By default, the job runs in the background.)
+
When the job runs in the background, you can monitor its progress by using the `job show` command.

 ** You can use the `volume quota show` command to monitor the status of the quota initialization.

. Use the `volume quota show -instance` command to check for initialization errors, such as quota rules that failed to initialize.
. Use the `volume quota report` command to display a quota report so that you can ensure the enforced quotas match your expectations.

// DP - August 5 2024 - ONTAP-2121