---
permalink: volumes/space-reserved-luns-thick-provisioned-concept.html
sidebar: sidebar
keywords: configuration, settings, space-reserved, files, luns with thick-provisioned volumes
summary: "There are several configuration combinations of FlexVol volume and file or LUN configurations you can use.
This combination based on thick-provisioned volumes provides the ability to use storage efficiency technologies and does not require you to actively monitor your free space because sufficient space is allocated up front."
---
= Configuration settings for space-reserved files or LUNs with thick-provisioned volumes
:icons: font
:imagesdir: ../media/

[.lead]
There are several configuration combinations of FlexVol volume and file or LUN configurations you can use.
This combination based on thick-provisioned volumes provides the ability to use storage efficiency technologies and does not require you to actively monitor your free space because sufficient space is allocated up front.

The following settings are required to configure a space-reserved file or LUN in a volume using thick provisioning:
[cols="2*",options="header"]
|===
| Volume setting| Value
a|
Guarantee
a|
Volume
a|
Fractional reserve
a|
100
a|
Snapshot reserve
a|
Any
a|
Snapshot autodelete
a|
Optional
a|
Autogrow
a|
Optional; if enabled, aggregate free space must be actively monitored.
|===
[cols="2*",options="header"]
|===
| File or LUN setting| Value
a|
Space reservation
a|
Enabled
|===

.Related information

* link:recommended-volume-lun-config-combinations-concept.html[Recommended volume and file or LUN configuration combinations overview]

// DP - August 5 2024 - ONTAP-2121