---
permalink: volumes/specify-windows-users-quotas-concept.html
sidebar: sidebar
keywords: specify, windows users, for quotas
summary: "You can specify a Windows user for a quota in one of several different formats."
---
= Specify Windows users for quotas
:icons: font
:imagesdir: ../media/

[.lead]
You can specify a Windows user for a quota in one of several different formats.

The three formats available when specifying a Windows user for a quota include the following:

* The Windows name in pre-Windows 2000 format.
* The security ID (SID) as displayed by Windows in text form, such as `S-1-5-32-544`.
* The name of a file or directory that has an ACL owned by that user's SID.
+
[NOTE]
====
If you specify a file or directory name, you must select a file or directory that will last as long as the user account remains on the system.

For ONTAP to obtain the SID from the ACL, the ACL must be valid.

If the file or directory exists in a UNIX-style qtree, or if the storage system uses UNIX mode for user authentication, ONTAP applies the user quota to the user whose *UID*, not SID, matches that of the file or directory.

Specifying a file or directory name to identify a user for a quota does not cause ONTAP to apply a quota to that file or directory.
====

// DP - August 5 2024 - ONTAP-2121