---
permalink: volumes/split-flexclone-from-parent-task.html
sidebar: sidebar
keywords: split, flexclone, volume, parent, volume, clone
summary: "You can split a FlexClone volume from its parent to make the clone a normal FlexVol volume."
---

= Split a FlexClone volume from its parent volume
:icons: font
:imagesdir: ../media/

[.lead]
You can split a FlexClone volume from its parent to make the clone a normal FlexVol volume.

The clone splitting operation takes place in the background. Data is accessible on the clone and the parent during the split. Beginning with ONTAP 9.4, space efficiency is preserved. The split process only updates metadata and requires minimal IO. No data blocks are copied.

.About this task

* New Snapshot copies of the FlexClone volume cannot be created during the split operation.
* A FlexClone volume cannot be split from the parent volume if it belongs to a data protection relationship or is part of a load-sharing mirror. 
* If you take the FlexClone volume offline while splitting is in progress, the split operation is suspended; when you bring the FlexClone volume back online, the splitting operation resumes.
* After the split, both the parent FlexVol volume and the clone require the full space allocation determined by their volume guarantees.
* After a FlexClone volume is split from its parent the two cannot be rejoined.
* Beginning with ONTAP 9.4, for non-guaranteed volumes on AFF systems, the split operation for FlexClone volumes shares the physical blocks and does not copy the data. Therefore, splitting of FlexClone volumes on AFF systems is faster than the FlexClone splitting operation in other FAS systems in ONTAP 9.4 and later. The improved FlexClone splitting operation on AFF systems has the following benefits:
** Storage efficiency is preserved after splitting the clone from the parent.
** Existing Snapshot copies are not deleted.
** The operation is faster.
** The FlexClone volume can be split from any point in the clone hierarchy.

.Before you begin
* You must be a cluster administrator.
* The FlexClone volume must be online when the split operation begins.
* The parent volume must be online for the split to succeed.

.Steps

. Determine the amount of free space required to complete the split operation:
+
`volume clone show -estimate -vserver _vserver_name_ -flexclone _clone_volume_name_ -parent-volume _parent_vol_name_`
+
The following example provides information about the free space required to split FlexClone volume "`clone1`" from its parent volume "`vol1`":
+
----
cluster1::> volume clone show -estimate -vserver vs1 -flexclone clone1 -parent-volume volume1
                             Split
Vserver   FlexClone       Estimate
--------- ------------- ----------
vs1       clone1           40.73MB
----

. Verify that the aggregate containing the FlexClone volume and its parent has sufficient space:
.. Determine the amount of free space in the aggregate that contains the FlexClone volume and its parent:
+
`storage aggregate show`
 .. If the containing aggregate does not have enough free space available, add storage to the aggregate:
+
`storage aggregate add-disks`
. Start the split operation:
+
`volume clone split start -vserver _vserver_name_ -flexclone _clone_volume_name_`
+
The following example shows how you can initiate the process to split FlexClone volume "`clone1`" from its parent volume "`vol1`":
+
----
cluster1::> volume clone split start -vserver vs1 -flexclone clone1

Warning: Are you sure you want to split clone volume clone1 in Vserver vs1 ?
{y|n}: y
[Job 1617] Job is queued: Split clone1.
----

. Monitor the status of the FlexClone split operation:
+
`volume clone split show -vserver _vserver_name_ -flexclone _clone_volume_name_`
+
The following example shows the status of the FlexClone split operation on an AFF system:
+
----
cluster1::> volume clone split show -vserver vs1 -flexclone clone1
                                              Inodes                   Blocks
                                     ---------------------    ---------------------
Vserver   FlexClone    Processed Total    Scanned  Updated      % Inode   % Block
                                                                 Complete  Complete
vs1       clone1        0         0       411247   153600         0        37
----

. Verify that the split volume is no longer a FlexClone volume:
+
`volume show -volume _volume_name_ -fields clone-volume`
+
The value of the `clone-volume` option is "`false`" for a volume that is not a FlexClone volume.
+
The following example shows how you can verify whether volume "`clone1`" that is split from its parent is not a FlexClone volume.
+
----
cluster1::> volume show -volume clone1 -fields clone-volume
vserver volume **clone-volume**
------- ------ **------------**
vs1     clone1 **false**
----

// DP - August 5 2024 - ONTAP-2121
// 2023-Aug-30, issue# 1066
// 2023 Jul 20, ONTAPDOC-1126
// 2023 Jun 28, partial fix for issue# 956
// 2021 Dec 09, BURT 1430515