---
permalink: volumes/storage-limits-reference.html
sidebar: sidebar
keywords: storage limits
summary: "There are limits for storage objects that you should consider when planning and managing your storage architecture."
---
= Storage limits
:icons: font
:imagesdir: ../media/

[.lead]
There are limits for storage objects that you should consider when planning and managing your storage architecture.

Limits are often platform dependent. Refer to the link:https://hwu.netapp.com/[Hardware Universe^] to learn the limits for your specific configuration. 

Limits are listed in the following sections:

* <<vollimits>>
* <<flexclone>>

Storage limits for Cloud Volumes ONTAP are documented in the link:https://docs.netapp.com/us-en/cloud-volumes-ontap/[Cloud Volumes ONTAP Release Notes^].

== Volume limits [[vollimits]]
[cols="4*",options="header"]
|===
| Storage object| Limit| Native storage| Storage arrays
a|
*Array LUNs*
a|
Minimum size for root volume^1^
a|
N/A
a|
Model-dependent
.2+a|
*Files*
a|
Maximum size
a|
16 TB
a|
16 TB
a|
Maximum per volume^3^
a|
Volume size dependent, up to 2 billion
a|
Volume size dependent, up to 2 billion
a|
*FlexClone volumes*
a|
Hierarchical clone depth^4^
a|
499
a|
499
.4+a|
*FlexVol volumes*
a|
Maximum per node^1^
a|
Model-dependent
a|
Model-dependent
a|
Maximum per node per SVM^5^
a|
Model-dependent
a|
Model-dependent
a|
Minimum size
a|
20 MB
a|
20 MB
a|
Maximum size^1^
a|
Model-dependent
a|
Model-dependent
a|
*FlexVol volumes for primary workloads*
a|
Maximum per node^2^
a|
Model-dependent
a|
Model-dependent
a|
*FlexVol root volumes*
a|
Minimum size^1^
a|
Model-dependent
a|
Model-dependent
.4+a|
*LUNs*
a|
Maximum per node^5^
a|
Model-dependent
a|
Model-dependent
a|
Maximum per cluster^5^
a|
Model-dependent
a|
Model-dependent
a|
Maximum per volume^5^
a|
Model-dependent
a|
Model-dependent
a|
Maximum size
a|
* In releases of ONTAP before 9.12.1: 16 TB
* Beginning with ONTAP 9.12.1: 128 TB
a|
* In releases of ONTAP before 9.12.1: 16 TB
* Beginning with ONTAP 9.12.1: 128 TB
a|
*Qtrees*
a|
Maximum per FlexVol volume
a|
4,995
a|
4,995
a|
*Snapshot copies*
a|
Maximum per volume^6^
a|
255/1023
a|
255/1023
.2+a|
*Volumes*
a|
Maximum per cluster for NAS
a|
12,000
a|
12,000
a|
Maximum per cluster with SAN protocols configured
a|
Model-dependent
a|
Model-dependent
|===
*Notes:*

. In ONTAP 9.3 and earlier, a volume can contain up to 255 Snapshot copies. In ONTAP 9.4 and later, a volume can contain up to 1023 Snapshot copies.
. Beginning with ONTAP 9.7, the maximum supported number of FlexVol volumes on AFF platforms with at least 128 GB of memory has increased to 2,500 FlexVol volumes per node.
+
For platform-specific information and for the latest support details, see https://hwu.netapp.com/[Hardware Universe^].

. 2 billion = 2 × 10^9^.
. The maximum depth of a nested hierarchy of FlexClone volumes that can be created from a single FlexVol volume.
. This limit applies only in SAN environments.
+
link:../san-config/index.html[SAN Configuration]

. You can use a SnapMirror cascade deployment to increase this limit.

== FlexClone file and FlexClone LUN limits [[flexclone]]
[cols="3*",options="header"]
|===
| Limit| Native storage| Storage arrays
a|
**Maximum per file or LUN**^1^
a|
32,767
a|
32,767
a|
*Maximum total shared data per FlexVol volume*
a|
640 TB
a|
640 TB
|===
*Note:*

. If you try to create more than 32,767 clones, ONTAP automatically creates a new physical copy of the parent file or LUN.
+
This limit might be lower for FlexVol volumes that use deduplication.

.Related information

https://www.netapp.com/cloud-services/cloud-manager/documentation/[Find the Release Notes for your version of Cloud Volumes ONTAP]

// 2023 6 december, ontap-issues #1192
// 22 march 2023, ONTAPDOC-1497
// 29 march 2022 issue #405
