---
permalink: volumes/user-ids-mixed-environment-concept.html
sidebar: sidebar
keywords: ontap determines, determine user ids, mixed environment
summary: "Several factors determine whether ONTAP uses a UNIX or Windows ID when applying user quotas."
---
= How ONTAP determines user IDs in a mixed environment
:icons: font
:imagesdir: ../media/

[.lead]
If you have users accessing your ONTAP storage from both Windows and UNIX clients, both Windows and UNIX security are used to determine file ownership. Several factors determine whether ONTAP uses a UNIX or Windows ID when applying user quotas.

If the security style of the qtree or FlexVol volume that contains the file is only NTFS or only UNIX, then the security style determines the type of ID used when applying user quotas. For qtrees with the mixed security style, the type of ID used is determined by whether the file has an ACL.

The following table summarizes what type of ID is used.
[cols="3*",options="header"]
|===
| Security Style| ACL| No ACL
a|
UNIX
a|
UNIX ID
a|
UNIX ID
a|
Mixed
a|
Windows ID
a|
UNIX ID
a|
NTFS
a|
Windows ID
a|
Windows ID
|===

// DP - August 6 2024 - ONTAP-2121