---
permalink: volumes/view-status-efficiency-operations-task.html
sidebar: sidebar
keywords: efficiency, operation, status, view, sequential packing
summary: "You can view whether deduplication or data compression is enabled on a volume. You can also view the status, state, type of compression, and progress of the efficiency operations on a volume."
---
= View efficiency operations and status
:icons: font
:imagesdir: ../media/

[.lead]
You can view whether deduplication or data compression is enabled on a volume. You can also view the status, state, type of compression, and progress of the efficiency operations on a volume.

There are two tasks available. Both use the command `volume efficiency show`.

== View efficiency status

.Steps

. View the status of an efficiency operation on a volume: `volume efficiency show` 
+
The following command displays the status of an efficiency operation on volume VolA that is assigned the adaptive compression type:
+
`volume efficiency show -instance -vserver vs1 -volume VolA`
+
If the efficiency operation is enabled on volume VolA and the operation is idle, then you can see the following in the system output:
+
----
cluster1::> volume efficiency show -vserver vs1 -volume VolA

  Vserver Name: vs1
   Volume Name: VolA
   Volume Path: /vol/VolA
         State: Enabled
        Status: Idle
      Progress: Idle for 00:03:20
----

== Determine if volumes contain sequentially packed data

You can display a list of volumes that have sequential packing enabled, for instance, when you need to revert to an ONTAP release earlier than 9.13.1. You must be in advanced privilege mode to use this command.

.Steps

. Set the privilege level: `set -privilege advanced`

. List volumes that have sequential packing enabled:
+
`volume efficiency show -extended-auto-adaptive-compression true`

// DP - August 5 2024 - ONTAP-2121
// 2023-Apr-21, IDR-225
// 2023-Apr-10, ONTAPDOC-877