---
permalink: encryption-at-rest/assign-authentication-keys-seds-onboard-task.html
sidebar: sidebar
keywords: assign, data, authentication, key, fips, drive, sed, onboard, key, management
summary: "You can use the storage encryption disk modify command to assign a data authentication key to a FIPS drive or SED. Cluster nodes use this key to access data on the drive."
---
= Assign a data authentication key to a FIPS drive or SED (onboard key management) with ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `storage encryption disk modify` command to assign a data authentication key to a FIPS drive or SED. Cluster nodes use this key to access data on the drive.

.About this task

A self-encrypting drive is protected from unauthorized access only if its authentication key ID is set to a non-default value. The manufacturer secure ID (MSID), which has key ID 0x0, is the standard default value for SAS drives. For NVMe drives, the standard default value is a null key, represented as a blank key ID. When you assign the key ID to a self-encrypting drive, the system changes its authentication key ID to a non-default value.

.Before you begin

You must be a cluster administrator to perform this task.

.Steps

. Assign a data authentication key to a FIPS drive or SED:
+
`storage encryption disk modify -disk _disk_ID_ -data-key-id _key_ID_`
+
Learn more about `storage encryption disk modify` in the link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html[ONTAP command reference^].
+
[NOTE]
====
You can use the `security key-manager key query -key-type NSE-AK` command to view key IDs.
====
+
----
cluster1::> storage encryption disk modify -disk 0.10.* -data-key-id <id_value>

Info: Starting modify on 14 disks.
      View the status of the operation by using the
      storage encryption disk show-status command.
----

. Verify that the authentication keys have been assigned:
+
`storage encryption disk show`
+
Learn more about `storage encryption disk show` in the link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html[ONTAP command reference^].
+
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data <id_value>
0.0.1   data <id_value>
[...]
----

// 2025-Feb-3, gh-1263 and ontap-2681
// 2025 Jan 14, ONTAPDOC-2569
// BURT 1374208, 09 NOV 2021
// 2022 september 6, ontap-issues-#588
