---
permalink: encryption-at-rest/before-configuring-concept.html
sidebar: sidebar
keywords: collect, network, information, ontap 9.2, earlier
summary: "If you are using ONTAP 9.2 or earlier, you should fill out the network configuration worksheet before enabling external key management."
---
= Collect network information in ONTAP 9.2 and earlier
:icons: font
:imagesdir: ../media/

[.lead]
If you are using ONTAP 9.2 or earlier, you should fill out the network configuration worksheet before enabling external key management.

[NOTE]
====
Beginning with ONTAP 9.3, the system discovers all needed network information automatically.
====


[cols="35,35,30"]

|===

h| Item h| Notes h| Value

a|
Key management network interface name
a|

a|

a|
Key management network interface IP address
a|
IP address of node management LIF, in IPv4 or IPv6 format
a|

a|
Key management network interface IPv6 network prefix length
a|
If you are using IPv6, the IPv6 network prefix length
a|

a|
Key management network interface subnet mask
a|

a|

a|
Key management network interface gateway IP address
a|

a|

a|
IPv6 address for the cluster network interface
a|
Required only if you are using IPv6 for the key management network interface
a|

a|
Port number for each KMIP server
a|
Optional. The port number must be the same for all KMIP servers. If you do not provide a port number, it defaults to port 5696, which is the Internet Assigned Numbers Authority (IANA) assigned port for KMIP.
a|

a|
Key tag name
a|
Optional. The key tag name is used to identify all keys belonging to a node. The default key tag name is the node name.
a|

|===

.Related information

https://www.netapp.com/pdf.html?item=/media/19676-tr-3954.pdf[NetApp Technical Report 3954: NetApp Storage Encryption Preinstallation Requirements and Procedures for IBM Tivoli Lifetime Key Manager^]

https://www.netapp.com/pdf.html?item=/media/19682-tr-4074.pdf[NetApp Technical Report 4074: NetApp Storage Encryption Preinstallation Requirements and Procedures for SafeNet KeySecure^]

// 2025 July 3, ONTAPDOC-2616, removed from sidebar but kept in repo
