---
permalink: encryption-at-rest/change-encryption-key-volume-92-earlier-task.html
sidebar: sidebar
keywords: changing, encryption key, volume, volume move start, command
summary: "It is a security best practice to change the encryption key for a volume periodically. You can use the volume move start command to change the encryption key. You must use volume move start in ONTAP 9.2 and earlier. The moved volume can reside on the same aggregate or a different aggregate."
---
= Change the encryption key for a volume with the volume move start command with ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
It is a security best practice to change the encryption key for a volume periodically. You can use the `volume move start` command to change the encryption key. You must use `volume move start` in ONTAP 9.2 and earlier. The moved volume can reside on the same aggregate or a different aggregate.

.About this task

You cannot use `volume move start` to rekey a SnapLock or FlexGroup volume.

.Before you begin

You must be a cluster administrator to perform this task. Alternately, you can be an SVM administrator to whom the cluster administrator has delegated authority. For more information, see link:delegate-volume-encryption-svm-administrator-task.html[delegate authority to run the volume move command].

.Steps

. Move an existing volume and change the encryption key:
+
`volume move start -vserver _SVM_name_ -volume _volume_name_ -destination-aggregate _aggregate_name_ -generate-destination-key true`
+
Learn more about `volume move start` in the link:https://docs.netapp.com/us-en/ontap-cli/volume-move-start.html[ONTAP command reference^].
+
The following command moves an existing volume named `*vol1*` to the destination aggregate `*aggr2*` and changes the encryption key:
+
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr2 -generate-destination-key true
----
+
A new encryption key is created for the volume. The data on the volume remains encrypted.

. Verify that the volume is enabled for encryption:
+
`volume show -is-encrypted true`
+
Learn more about `volume show` in the link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html[ONTAP command reference^].
+
The following command displays the encrypted volumes on `cluster1`:
+
----
cluster1::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr2     online    RW  200GB    160.0GB  20%
----

// 2025 Jan 14, ONTAPDOC-2569