---
permalink: encryption-at-rest/configure-external-key-management-concept.html
sidebar: sidebar
keywords: external key management, kmip, configure
summary: "You can use one or more external key management servers to secure the keys that the cluster uses to access encrypted data. An external key management server is a third-party system in your storage environment that serves keys to nodes using the Key Management Interoperability Protocol (KMIP)."
---
= Learn about configuring external key management with ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
You can use one or more external key management servers to secure the keys that the cluster uses to access encrypted data. An external key management server is a third-party system in your storage environment that serves keys to nodes using the Key Management Interoperability Protocol (KMIP).

For ONTAP 9.1 and earlier versions, node management LIFs must be assigned to ports that are configured with the node management role before you can use the external key manager.

NetApp Volume Encryption (NVE) can be implemented with Onboard Key Manager in ONTAP 9.1 and later. In ONTAP 9.3 and later, NVE can be implemented with external key management (KMIP) and Onboard Key Manager. Beginning with ONTAP 9.11.1, you can configure multiple external key managers in a cluster. See xref:configure-cluster-key-server-task.html[Configure clustered key servers.]


// 2025 Jan 22, ONTAPDOC-1070
// BURT 1374208, 10 NOV 2021
//22 march 2022 IE-497