---
sidebar: sidebar
permalink: encryption-at-rest/configure-cluster-key-server-task.html
keywords: KMIP, clustered key server, external key server, secondary key server
summary: Beginning with ONTAP 9.11.1, you can set up clustered key server, supporting up to four key servers per vserver. 
---
= Configure clustered external key servers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Beginning in 9.11.1, ONTAP offers clustered key servers, a simplified solution to support multiple external key managers in your vserver. 
// What is the main selling point?

External key servers can be used for NSE, NVE, and NAE keys. A vserver can support up to four primary external KMIP servers. Each primary server can support up to three secondary key servers. 

== Before you begin
* link:install-ssl-certificates-hardware-task.html[KMIP key management is already enabled for the vserver]. Use the command `security certificate show -vserver _vserver_name_` to check. 
* This process only supports key servers that use KMIP. For a list of support key servers, check the link:http://mysupport.netapp.com/matrix/[NetApp Interoperability Matrix Tool^]. 
//what is the search term here?
* All nodes in the cluster must be running ONTAP 9.11.1 or later
* The order of servers list arguments in the `-secondary-key-servers` parameter reflects the access order of the CLI servers

== Create a clustered key server

The configuration procedure depends on whether or not you have configured a key server

[options="header"]
|===
| If no key server has been enabled on the vserver | If a key server already exists on the vserver:
|
1. Confirm that no key management has been enabled for the cluster:
`security key-manager external show -vserver _vserver_name_`
2. Enable the primary key manager: 
`security key-manager external enable -vserver _vserver_name_ -key-servers _server_ip_`
3. Modify the primary key server to add secondary key servers. The `-secondary-key-servers` parameter accepts a comma-separated list of up to three key servers. 
`security key-manager external modify-server -vserver _vserver_name_ -key-servers _primary_key_server_ -secondary-key-servers _list_of_key_servers_`
| 1. Add a new primary key server:
`security key-manager external add-servers -vserver _vserver_name_ -key-servers _server_ip_`
2. Modify the primary key server to add secondary key servers. The `-secondary-key-servers` parameter accepts a comma-separated list of up to three key servers. 
`security key-manager external modify-server -vserver _vserver_name_ -key-servers _primary_key_server_ -secondary-key-servers _list_of_key_servers_`
|===

=== Modifying primary key servers

To convert a primary key server into a secondary key server, you must first remove it from the vserver with the `security key-manager external remove-servers` command. 

To convert a secondary key server into a primary key server, you must first remove the secondary key server from its existing primary key server. See <<mod-secondary>>. If you convert a secondary key server to a primary server while removing an existing key, attempting to add a new server before completing the removal and conversion can result in the the duplication of keys. 

=== Modifying secondary key servers [[mod-secondary]]

Secondary key servers are managed with the `-secondary-key-servers` parameter of the `security key-manager external modify-server` command. The `-secondary-key-servers` parameter accepts a comma-separated list, whose order determines the access sequence for the secondary key servers. The access order can be running the command `security key-manager external modify-server` with the existing secondary key servers entered in a different order. 

To remove a secondary key server, the `-secondary-key-servers` arguments should include the key servers you want to keep while omitting the one to be removed. To remove all secondary key servers, use the argument `-`, signifying none. 

For additional information, refer to the `security key-manager external` manual pages. 

// if someone has used the manual solution, are the conversion workflows covered here?
// if there are multiple primary key servers, how are they configured?