---
permalink: encryption-at-rest/create-authentication-keys-96-later-task.html
sidebar: sidebar
keywords: creating, authentication keys, ontap 9.6, later
summary: "You can use the security key-manager key create command to create the authentication keys for a node and store them on the configured KMIP servers."
---
= Create authentication keys in ONTAP 9.6 and later
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `security key-manager key create` command to create the authentication keys for a node and store them on the configured KMIP servers.

.About this task

If your security setup requires you to use different keys for data authentication and FIPS 140-2 authentication, you should create a separate key for each. If that's not the case, you can use the same authentication key for FIPS compliance that you use for data access.

ONTAP creates authentication keys for all nodes in the cluster.

* This command is not supported when Onboard Key Manager is enabled. However, two authentication keys are created automatically when Onboard Key Manager is enabled. The keys can be viewed with the following command:
+
----
security key-manager key query -key-type NSE-AK
----

* You receive a warning if the configured key management servers are already storing more than 128 authentication keys.

* You can use the `security key-manager key delete` command to delete any unused keys. The `security key-manager key delete` command fails if the given key is currently in use by ONTAP. (You must have privileges greater than `admin` to use this command.)
+
[NOTE]
====
In a MetroCluster environment, before you delete a key, you must make sure that the key is not in use on the partner cluster. You can use the following commands on the partner cluster to check that the key is not in use:

* `storage encryption disk show -data-key-id <key-id>`

* `storage encryption disk show -fips-key-id <key-id>`
====


.Before you begin

You must be a cluster administrator to perform this task.

.Steps

. Create the authentication keys for cluster nodes:
+
[source,cli]
----
security key-manager key create -key-tag <passphrase_label> -prompt-for-key true|false
----
+
[NOTE]
====
Setting `prompt-for-key=true` causes the system to prompt the cluster administrator for the passphrase to use when authenticating encrypted drives. Otherwise, the system automatically generates a 32-byte passphrase.  The `security key-manager key create` command replaces the `security key-manager create-key` command. 
Learn more about `security key-manager key create` in the link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-create.html?q=security+key-manager+key+create[ONTAP command reference^].
====
+
The following example creates the authentication keys for `cluster1`, automatically generating a 32-byte passphrase:
+
----
cluster1::> security key-manager key create
Key ID: <id_value>
----

. Verify that the authentication keys have been created:
+
----
security key-manager key query -node node
----
+
[NOTE]
====
The `security key-manager key query` command replaces the `security key-manager query key` command. 
Learn more about `security key-manager key query` in the link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html[ONTAP command reference^].
The key ID displayed in the output is an identifier used to refer to the authentication key. It is not the actual authentication key or the data encryption key.
====
+
The following example verifies that authentication keys have been created for `cluster1`:
+
----
cluster1::> security key-manager key query
       Vserver: cluster1
   Key Manager: external
          Node: node1

Key Tag                               Key Type  Restored
------------------------------------  --------  --------
node1                                 NSE-AK    yes
    Key ID: <id_value>
node1                                 NSE-AK    yes
    Key ID: <id_value>

       Vserver: cluster1
   Key Manager: external
          Node: node2

Key Tag                               Key Type  Restored
------------------------------------  --------  --------
node2                                 NSE-AK    yes
    Key ID: <id_value>
node2                                 NSE-AK    yes
    Key ID: <id_value>
----

// 2025-Feb-3, gh-1263 and ontap-2681
// 2025 Jan 14, ONTAPDOC-2569
// BURT 1374208, 10 NOV 2021
// 2022 Dec 14, ONTAPDOC-710
