---
permalink: encryption-at-rest/delete-key-management-database-task.html
sidebar: sidebar
keywords: transitioning, onboard key management, external key management
summary: "If you want to switch to onboard key management from external key management, you must delete the external key management configuration before you can enable onboard key management."
---
= Transition to onboard key management from external key management
:icons: font
:imagesdir: ../media/

[.lead]
If you want to switch to onboard key management from external key management, you must delete the external key management configuration before you can enable onboard key management.

.What you'll need

* For hardware-based encryption, you must reset the data keys of all FIPS drives or SEDs to the default value.
+
link:return-seds-unprotected-mode-task.html[Returning a FIPS drive or SED to unprotected mode]

* You must have deleted all external key manager connections.
+
link:remove-external-key-server-93-later-task.html[Deleting an external key manager connection]

* You must be a cluster administrator to perform this task.

.Steps

. Delete the external key management configuration for a cluster:
+
`security key-manager delete-kmip-config`
+

[cols="25,75"]
|===

h| For this ONTAP version... h| Use this command...

a|
ONTAP 9.6 and later
a|
`security key-manager external disable -vserver admin_SVM`
a|
ONTAP 9.5 and earlier
a|
`security key-manager delete-kmip-config`
|===

+
[NOTE]
====
For complete command syntax, see the man pages. The ONTAP 9.6 version of the command requires advanced privilege level.
====
+
The following ONTAP 9.6 commands delete the external key management configurations for `cluster1`:
+
----
cluster1::> set -privilege advanced
cluster1::> security key-manager external disable
----
