---
permalink: encryption-at-rest/delete-encrypted-volume-task.html
sidebar: sidebar
keywords: deleting, encrypted, volume
summary: "You can use the volume delete command to delete an encrypted volume."
---
= Delete an encrypted volume
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `volume delete` command to delete an encrypted volume.

.What you'll need

* You must be a cluster administrator to perform this task, or an SVM administrator to whom the cluster administrator has delegated authority.
+
link:delegate-volume-encryption-svm-administrator-task.html[Delegating authority to run the volume move command]

* The volume must be offline.

.Step

. Delete an encrypted volume:
+
`volume delete -vserver SVM_name -volume volume_name`
+
For complete command syntax, see the man page for the command.
+
The following command deletes an encrypted volume named `vol1`:
+
----
cluster1::> volume delete -vserver vs1 -volume vol1
----
+
Enter `yes` when you are prompted to confirm deletion.
+
The system deletes the encryption key for the volume after 24 hours.
+
Use `volume delete` with the `-force true` option to delete a volume and destroy the corresponding encryption key immediately. This command requires advanced privileges. For more information, see the man page.

.After you finish

You can use the `volume recovery-queue` command to recover a deleted volume during the retention period after issuing the `volume delete` command:

`volume recovery-queue SVM_name -volume volume_name`

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue[How to use the Volume Recovery feature]
