---
permalink: encryption-at-rest/enable-onboard-key-management-96-later-nve-task.html
sidebar: sidebar
keywords: enabling, onboard key management, ontap 9.6, later, nve
summary: "You can use the Onboard Key Manager to secure the keys that the cluster uses to access encrypted data. You must enable Onboard Key Manager on each cluster that accesses an encrypted volume or a self-encrypting disk."
---
= Enable onboard key management for NVE in ONTAP 9.6 and later

:icons: font
:imagesdir: ../media/

[.lead]
You can use the Onboard Key Manager to secure the keys that the cluster uses to access encrypted data. You must enable the Onboard Key Manager on each cluster that accesses an encrypted volume or a self-encrypting disk.
 
.About this task

You must run the `security key-manager onboard sync` command each time you add a node to the cluster.

If you have a MetroCluster configuration, you must run the `security key-manager onboard enable` command on the local cluster first, then run the `security key-manager onboard sync` command on the remote cluster, using the same passphrase on each. When you run the `security key-manager onboard enable` command from the local cluster and then synchronize on the remote cluster, you do not need to run the `enable` command again from the remote cluster.

Learn more about `security key-manager onboard enable` and `security key-manager onboard sync` in the link:https://docs.netapp.com/us-en/ontap-cli//security-key-manager-onboard-enable.html[ONTAP command reference^].

By default, you are not required to enter the key manager passphrase when a node is rebooted. You can use the `cc-mode-enabled=yes` option to require that users enter the passphrase after a reboot.

For NVE, if you set `cc-mode-enabled=yes`, volumes you create with the `volume create` and `volume move start` commands are automatically encrypted. For `volume create`, you need not specify `-encrypt true`. For `volume move start`, you need not specify `-encrypt-destination true`.

When configuring ONTAP data at rest encryption, to meet the requirements for Commercial Solutions for Classified (CSfC) you must use NSE with NVE and ensure the Onboard Key Manager is enabled in Common Criteria mode. See link:https://assets.netapp.com/m/128a1e9f4b5d663/original/Commercial-Solutions-for-Classified.pdf[CSfC Solution Brief^] for more information on CSfC.

[NOTE]
====
When the Onboard Key Manager is enabled in Common Criteria mode (`cc-mode-enabled=yes`), system behavior is changed in the following ways:

* The system monitors for consecutive failed cluster passphrase attempts when operating in Common Criteria mode.
+
If you fail to enter the cluster passphrase 5 times, wait 24 hours or reboot the node to reset the limit.

* System image updates use the NetApp RSA-3072 code signing certificate together with SHA-384 code signed digests to check the image integrity instead of the usual NetApp RSA-2048 code signing certificate and SHA-256 code signed digests.
+
The upgrade command verifies that the image contents have not been altered or corrupted by checking various digital signatures. The system proceeds to the next step in the image update process if validation succeeds; otherwise, it fails the image update. Learn more about `cluster image` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+image[ONTAP command reference^].
====

[NOTE]
The Onboard Key Manager stores keys in volatile memory. Volatile memory contents are cleared when the system is rebooted or halted. The system clears volatile memory within 30 seconds when it is halted.

.Before you begin

* You must be a cluster administrator to perform this task.
* You must configure the MetroCluster environment before you configure the Onboard Key Manager. 


.Steps

. Start the key manager setup:
+
`security key-manager onboard enable -cc-mode-enabled yes|no`
+
[NOTE]
====
Set `cc-mode-enabled=yes` to require that users enter the key manager passphrase after a reboot. For NVE, if you set `cc-mode-enabled=yes`, volumes you create with the `volume create` and `volume move start` commands are automatically encrypted. The `- cc-mode-enabled` option is not supported in MetroCluster configurations.    The `security key-manager onboard enable` command replaces the `security key-manager setup` command.
====
+
The following example starts the key manager setup command on cluster1 without requiring that the passphrase be entered after every reboot:
+
----
cluster1::> security key-manager onboard enable

Enter the cluster-wide passphrase for onboard key management in Vserver "cluster1"::    <32..256 ASCII characters long text>
Reenter the cluster-wide passphrase:    <32..256 ASCII characters long text>
----

. At the passphrase prompt, enter a passphrase between 32 and 256 characters, or for "`cc-mode`", a passphrase between 64 and 256 characters.
+
[NOTE]
====
If the specified "`cc-mode`" passphrase is less than 64 characters, there is a five-second delay before the key manager setup operation displays the passphrase prompt again.
====

. At the passphrase confirmation prompt, reenter the passphrase.
. Verify that the authentication keys have been created:
+
`security key-manager key query -key-type NSE-AK`
+
[NOTE]
====
The `security key-manager key query` command replaces the `security key-manager query key` command.
====
+
The following example verifies that authentication keys have been created for `cluster1`:
+
----
cluster1::> security key-manager key query -key-type NSE-AK
               Node: node1
            Vserver: cluster1
        Key Manager: onboard
   Key Manager Type: OKM
 Key Manager Policy: -

 Key Tag                               Key Type Encryption   Restored

------------------------------------  -------- ------------ --------

node1                                 NSE-AK   AES-256      true

    Key ID: <id_value>

node1                                 NSE-AK   AES-256      true

    Key ID: <id_value>

2 entries were displayed.
----
+
Learn more about `security key-manager key query` in the link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html[ONTAP command reference^].

. You can convert plain text volumes to encrypted volumes.
+
`volume encryption conversion start`
+
The Onboard Key Manager must be fully configured before you convert the volumes. In a MetroCluster environment, the Onboard Key Manager must be configured on both sites.

.After you finish

Copy the passphrase to a secure location outside the storage system for future use.

After configuring the Onboard Key Manager passphrase, manually back up the information to a secure location outside the storage system. See link:backup-key-management-information-manual-task.html[Back up onboard key management information manually].

.Related information
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+image[cluster image commands^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-enable.html[security key-manager external enable^]
* link:https://docs.netapp.com/us-en/ontap-cli//security-key-manager-key-query.html[security key-manager key query^]
* link:https://docs.netapp.com/us-en/ontap-cli//security-key-manager-onboard-enable.html[security key-manager onboard enable^]


// 2025 October 10, ONTAPDOC-3363 and GH-2716 and NADIAA
// 2025 June 10, ONTAPDOC-2960
// 2025 Feb 14, ONTAPDOC-2758
// 2025 feb 3, gh-1283 and ontap-2681
// 2025 Jan 15, ONTAPDOC-2569 
// 2023 Sept 21, Git Issue 1096
// ONTAPDOC-1076, 2023 Jun 30
// 2021 dec 3, issue #273
