---
permalink: encryption-at-rest/enable-encryption-new-volume-task.html
sidebar: sidebar
keywords: encryption, new volume, NAE, NVE, volume create
summary: "You can use the volume create command to enable encryption on a new volume."
---
= Enable encryption on a new volume
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `volume create` command to enable encryption on a new volume.

.About this task [[about_this_task]]

A volume encrypted with a unique key is called an _NVE volume_ (NetApp volume encryption). Beginning with ONTAP 9.6, you can also use NetApp Aggregate Encryption (NAE). Plaintext volumes are not supported in NAE aggregates. See xref:../concepts/encryption-concept.html[Encryption] to learn more about NAE and NVE. 

Beginning with ONTAP 9.4, if you enable `cc-mode` when you set up the Onboard Key Manager, volumes you create with the `volume create` command are automatically encrypted, whether or not you specify `-encrypt true`.

You can use aggregate-level encryption to assign keys to the containing aggregate for the volumes to be encrypted. Volumes you create in the aggregate are encrypted by default. When NAE is enabled, individual volumes must be encrypted. If you have NAE enabled on the aggregate, creating a new volume with the `-encrypt` parameter to `true` overrides the default, creating an NVE encryption instead of NAE. 

Beginning with ONTAP 9.7, newly created volumes are encrypted by default when you have the VE license and onboard or external key management.

Encryption can be enabled on a SnapLock volume.

.Steps

. Create a new volume and specify whether encryption is enabled on the volume:
+
[cols="25,75"]
|===
h| To create... h| Use this command...
a| An NAE volume 
a| `volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_` +
[NOTE] 
In ONTAP 9.6, you must enable NAE at the aggregate-level to create an NAE volume. See <<about_this_task>> for details about NAE encryption in ONTAP 9.7 and later.
a|
An NVE volume
a|
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_` +
[NOTE]
If you are using ONTAP 9.6 or earlier, add `-encrypt true` to the command. Using this parameter in ONTAP 9.7 or later with NAE enabled will create a new volume with NVE encryption. 
a| A plain text volume
a| `volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_ -encrypt false`
|===
+
For complete command syntax, refer to the command reference page for link:https://docs.netapp.com/us-en/ontap-cli-9121/volume-create.html[`volume show`^].

. Verify that volumes are enabled for encryption:
+
`volume show -is-encrypted true`
+
For complete command syntax, see the link:https://docs.netapp.com/us-en/ontap-cli-9121/volume-show.html[command reference^].

.Result

If you are using a KMIP server to store the encryption keys for a node, ONTAP automatically "pushes" an encryption key to the server when you encrypt a volume.

// 14 NOV 2022, BURT 1510942
//  09 NOV 2021, BURT 1374208
