---
permalink: encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html
sidebar: sidebar
keywords: enabling, onboard key management, ontap 9.6, later
summary: "You can use the Onboard Key Manager to secure the keys that the cluster uses to access encrypted data. You must enable Onboard Key Manager on each cluster that accesses an encrypted volume or a self-encrypting disk."
---
= Enable onboard key management in ONTAP 9.6 and later
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Onboard Key Manager to authenticate cluster nodes to a FIPS drive or SED. The Onboard Key Manager is a built-in tool that serves authentication keys to nodes from the same storage system as your data. The Onboard Key Manager is FIPS-140-2 level 1 compliant.

You can use the Onboard Key Manager to secure the keys that the cluster uses to access encrypted data. You must enable Onboard Key Manager on each cluster that accesses an encrypted volume or a self-encrypting disk.

.About this task

You must run the `security key-manager onboard enable` command each time you add a node to the cluster. In MetroCluster configurations, you must run `security key-manager onboard enable` on the local cluster first, then run `security key-manager onboard sync` on the remote cluster, using the same passphrase on each.

Learn more about `security key-manager onboard enable` and `security key-manager onboard sync` in the link:https://docs.netapp.com/us-en/ontap-cli//security-key-manager-onboard-enable.html[ONTAP command reference^].

By default, you are not required to enter the key manager passphrase when a node is rebooted. Except in MetroCluster, you can use the `cc-mode-enabled=yes` option to require that users enter the passphrase after a reboot.

[NOTE]
====
When the Onboard Key Manager is enabled in Common Criteria mode (`cc-mode-enabled=yes`), system behavior is changed in the following ways:

* The system monitors for consecutive failed cluster passphrase attempts when operating in Common Criteria mode.
+
If NetApp Storage Encryption (NSE) is enabled and you fail to enter the correct cluster passphrase at boot, the system cannot authenticate to its drives and automatically reboots. To correct this, you must enter the correct cluster passphrase at the boot prompt. Once booted, the system allows up to 5 consecutive attempts to correctly enter the cluster passphrase in a 24-hour period for any command that requires the cluster passphrase as a parameter. If the limit is reached (for example, you have failed to correctly enter the cluster passphrase 5 times in a row) then you must either wait for the 24-hour timeout period to elapse, or you must reboot the node, in order to reset the limit.

* System image updates use the NetApp RSA-3072 code signing certificate together with SHA-384 code signed digests to check the image integrity instead of the usual NetApp RSA-2048 code signing certificate and SHA-256 code signed digests.
+
The upgrade command verifies that the image contents have not been altered or corrupted by checking various digital signatures. If validation works, the image update goes to the next step. If validation does not work, the image update fails. Learn more about `cluster image` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+image[ONTAP command reference^].
====

[NOTE]
The Onboard Key Manager stores keys in volatile memory. Volatile memory contents are cleared when the system is rebooted or halted. Under normal operating conditions, volatile memory contents will be cleared within 30s when a system is halted. 

.Before you begin 

* If you are using NSE with an external key management (KMIP) server, you must have deleted the external key manager database.
+
link:delete-key-management-database-task.html[Transitioning to onboard key management from external key management]

* You must be a cluster administrator to perform this task.
* You must configure the MetroCluster environment before you configure the Onboard Key Manager.


.Steps

. Start the key manager setup command:
+
`security key-manager onboard enable -cc-mode-enabled yes|no`
+
[NOTE]
Set `cc-mode-enabled=yes` to require that users enter the key manager passphrase after a reboot. The `- cc-mode-enabled` option is not supported in MetroCluster configurations. The `security key-manager onboard enable` command replaces the `security key-manager setup` command.
+
The following example starts the key manager setup command on cluster1 without requiring that the passphrase be entered after every reboot:

. Enter a passphrase between 32 and 256 characters, or for "`cc-mode`", a passphrase between 64 and 256 characters.
+
[NOTE]
If the specified "`cc-mode`" passphrase is less than 64 characters, there is a five-second delay before the key manager setup operation displays the passphrase prompt again.

. At the passphrase confirmation prompt, reenter the passphrase.
. Verify that the system creates the authentication keys:
+
`security key-manager key query -node node`
+
[NOTE]
The `security key-manager key query` command replaces the `security key-manager query key` command. 
+
Learn more about `security key-manager key query` in the link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html[ONTAP command reference^].

.After you finish

Copy the passphrase to a secure location outside the storage system for future use.

The system automatically backs up key management information to the replicated database (RDB) for the cluster. You should also back up this information manually for disaster recovery.

.Related information
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+image[cluster image commands^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-enable.html[security key-manager external enable^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html[security key-manager key query^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-enable.html[security key-manager onboard enable^]
* link:delete-key-management-database-task.html[Transitioning to onboard key management from external key management]


// 2025 October 10-17, ONTAPDOC-3363, GH-2716, NADIAA, updates from Ed
// 2025 June 10, ONTAPDOC-2960
// 2025 Feb 14, ONTAPDOC-2758
// 2025 feb 3, gh-1263 and ontap-2681
// 2025 Jan 15, ONTAPDOC-2569