---
permalink: encryption-at-rest/install-license-task.html
sidebar: sidebar
keywords: install, license, VE license, NVE, encryption, encrypt data
summary: "A VE license entitles you to use the feature on all nodes in the cluster. You must verify that the license is installed before you can encrypt data with NVE."
---
= Install the license
:icons: font
:imagesdir: ../media/

[.lead]
A VE license entitles you to use the feature on all nodes in the cluster. This license is required before you can encrypt data with NVE. It is included with link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one[ONTAP One]. 

Prior to ONTAP One, the VE license was included with the Encryption bundle. The Encryption bundle is no longer offered, but is still valid. Although not currently required, existing customers can choose to link:https://docs.netapp.com/us-en/ontap/system-admin/download-nlf-task.html[upgrade to ONTAP One].

.Before you begin

* You must be a cluster administrator to perform this task.
* You must have received the VE license key from your sales representative or have ONTAP One installed.


.Steps

*  link:https://docs.netapp.com/us-en/ontap/system-admin/manage-license-task.html[Verify that the VE license is installed]. 
+
The VE license package name is `VE`.

* If the license is not installed, link:https://docs.netapp.com/us-en/ontap/system-admin/install-license-task.html[use System Manager or the ONTAP CLI to install it].



// 2024-Mar-26, ONTAPDOC-1366
// BURT 1374208, 09 NOV 2021
