---
permalink: encryption-at-rest/install-license-task.html
sidebar: sidebar
keywords: install, license
summary: "An NVE license entitles you to use the feature on all nodes in the cluster. You must install the license before you can encrypt data with NVE."
---
= Install the license
:icons: font
:imagesdir: ../media/

[.lead]
An NVE license entitles you to use the feature on all nodes in the cluster. You must install the license before you can encrypt data with NVE.

.What you'll need

You must be a cluster administrator to perform this task.

.About this task

You should have received the NVE license key from your sales representative.

.Steps

. Install the NVE license for a node:
+
`system license add -license-code license_key`
+
The following command installs the license with the key `AAAAAAAAAAAAAAAAAAAAAAAAAAAA`.
+
----
cluster1::> system license add -license-code AAAAAAAAAAAAAAAAAAAAAAAAAAAA
----

. Verify that the license is installed by displaying all the licenses on the cluster:
+
`system license show`
+
For complete command syntax, see the man page for the command.
+
The following command displays all the licenses on `cluster1`:
+
----
cluster1::> system license show
----
+
The NVE license package name is "`VE`".
