---
permalink: encryption-at-rest/migrate-keys-between-key-managers.html
sidebar: sidebar
keywords: onboard key manager, external key manager, configure, migrate keys, store keys, authentication keys, encryption keys
summary: "You can use the ONTAP onboard key manager or an external key manager or both (in one case) to manage data encryption keys."
---
= Migrate ONTAP data encryption keys between key managers
:icons: font
:imagesdir: ../media/

[.lead]
You can use the ONTAP onboard key manager or an external key manager or both (in one case) to manage data encryption keys. External key managers can only be enabled at the storage VM level. At the ONTAP cluster level, you can enable either the onboard key manager or an external key manager.  

[cols="2,2" options="header"]
|===
// header row
| If you enable your key manager at the...
| You can use the following key manager...


// first body row
| Cluster level only
| Onboard or external

| SVM level only
| External

a| Cluster and SVM level

[NOTE]
When you use a key manager at both the ONTAP cluster level and SVM level, you have two options for how you combine the key manager types.

| _Option 1_
Cluster level: onboard
SVM level: external

_Option 2_
Cluster level: external
SVM level: external

// table end
|===

.When would I need to migrate my encryption keys?

If a key manager is enabled at the cluster level before you configure an external key manager at the storage VM level, the keys for any encrypted volumes must be migrated from the key manager at the cluster level to the external key manager at the storage VM level.  If no volumes are encrypted at the cluster level when you configure an external key manager at the SVM level, there is no need to migrate keys.  

Keys must also be migrated between key managers at the cluster level if you switch from using the onboard key manager to an external key manager or vice versa.



== Migrate keys between key managers at the ONTAP cluster level
Beginning in ONTAP 9.16.1 you can use the ONTAP CLI to migrate keys between key managers at the cluster level. 

// start tabbed area

[role="tabbed-block"]
====

.First tab
--
From onboard key manager to external key manager
--

.Steps

. Set the privilege level to advanced:
+
[source, cli]
----
set -privilege advance
----

. Create an inactive external key manager configuration:  
+
[source, cli]
----
security key-manager external create-config 
----

. Switch to the external key manager:
+
[source, cli]
----
security key-manager keystore enable -vserver SVM -type KMIP
----

. Delete the onboard key manager configuration:
+
[source, cli]
----
security key-manager keystore delete-config -vserver SVM -type OKM
----

. Set the privilege level to admin:
+
[source, cli]
----
set -privilege admin
----


.Second tab
--
From external key manager to onboard key manager
--

.Steps

. Set the privilege level to advanced:
+
[source, cli]
----
set -privilege advance
----

. Create an inactive onboard key manager configuration: 
+
[source, cli]
----
security key-manager onboard create-config
----

. Enable the onboard key manager configuration: 
+
[source, cli]
----
security key-manager keystore enable -vserver SVM -type OKM
----

. Delete the external key manger configuration
+
[source, cli]
----
security key-manager keystore delete-config -vserver SVM -type KMIP
----

. Set the privilege level to admin:
+
[source, cli]
----
set -privilege admin
----

====

// end tabbed area


== Migrate keys between key managers across ONTAP cluster and storage VM levels

You can use the ONTAP command line interface (CLI) to migrate keys between the key manager at the cluster level and a key manager at the storage VM level.  


.Steps

. Set the privilege level to advanced:
+
[source, cli]
----
set -privilege advance
----

. Migrate the keys:
+
[source, cli]
----
security key-manager key migrate -from-vserver SVM -to-vserver SVM
----

. Set the privilege level to admin:
+
[source, cli]
----
set -privilege admin
----

// 2024 Nov 07, ONTAPDOC 2491