---
permalink: encryption-at-rest/move-encrypted-volume-task.html
sidebar: sidebar
keywords: moving, encrypted, volume
summary: "You can use the volume move start command to move an encrypted volume. The moved volume can reside on the same aggregate or a different aggregate."
---
= Move an encrypted volume
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `volume move start` command to move an encrypted volume. The moved volume can reside on the same aggregate or a different aggregate.

.About this task

The move will fail if the destination node or destination volume does not support volume encryption.

The `-encrypt-destination` option for `volume move start` defaults to true for encrypted volumes. The requirement to specify you do not want the destination volume encrypted ensures that you do not inadvertently unencrypt the data on the volume. 

.Before you begin

You must be a cluster administrator to perform this task. Alternately, you can be an SVM administrator to whom the cluster administrator has delegated authority. For more information, see link:delegate-volume-encryption-svm-administrator-task.html[delegate authority to run the volume move command].

.Steps

. Move an existing encrypted volume and leave the data on the volume encrypted:
+
`volume move start -vserver _SVM_name_ -volume _volume_name_ -destination-aggregate _aggregate_name_`
+
For complete command syntax, see the man page for the command.
+
The following command moves an existing volume named `vol1` to the destination aggregate `aggr3` and leaves the data on the volume encrypted:
+
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr3
----

. Verify that the volume is enabled for encryption:
+
`volume show -is-encrypted true`
+
For complete command syntax, see the man page for the command.
+
The following command displays the encrypted volumes on `cluster1`:
+
----
cluster1::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr3     online    RW  200GB    160.0GB  20%
----
