---
permalink: encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html
sidebar: sidebar
keywords: restoring, onboard, key management encryption
summary: "Occasionally, you may need to restore an onboard key management encryption key. Once you have verified that a key needs to be restored, you can run the Onboard Key Manager setup wizard to restore the key."
---
= Restore onboard key management encryption keys
:icons: font
:imagesdir: ../media/

[.lead]
Occasionally, you may need to restore an onboard key management encryption key. Once you have verified that a key needs to be restored, you can run the Onboard Key Manager setup wizard to restore the key.

.What you'll need

* If you are using NSE with an external key management (KMIP) server, you must have deleted the external key manager database.
+
xref:delete-key-management-database-task.adoc[Transitioning to onboard key management from external key management]

* You must be a cluster administrator to perform this task.

.About this task

In ONTAP 9.6 and later, you can use the `security key-manager key query -node node` command to verify if your key needs to be restore.

In ONTAP 9.5 and earlier, you can use the `security key-manager key show` command to verify if your key needs to be restored.

.Steps

. If you are running ONTAP 9.8 and later, and your root volume is encrypted, do the following:
+
If you are running ONTAP 9.7 or earlier, or if you are running ONTAP 9.8 or later and your root volume is not encrypted, skip this step.

 .. Boot the node to the boot menu and select option `(10) Set onboard key management recovery secrets`.
 .. Enter `y` to use this option.
 .. At the prompt, enter the onboard key management passphrase for the cluster.
 .. At the prompt, enter the backup key data.
+
The node returns to the boot menu..

 .. From the boot menu, select option `(1) Normal Boot`.

. Restore the key:
+
[options="header"]
|===
| For this ONTAP version...| Use this command...

a|
ONTAP 9.6 and later
a|
`security key-manager onboard sync`
a|
ONTAP 9.5 and earlier
a|
`security key-manager setup -node node`
|===
For complete command syntax, see the man pages.
+
The following ONTAP 9.6 command synchronize the keys in the onboard key hierarchy:
+
----
cluster1::> security key-manager onboard sync

Enter the cluster-wide passphrase for onboard key management in Vserver "cluster1"::    <32..256 ASCII characters long text>
----

. At the passphrase prompt, enter the onboard key management passphrase for the cluster.
