---
permalink: encryption-at-rest/unencrypt-volume-data-task.html
sidebar: sidebar
keywords: unencrypting, volume, data
summary: "You can use the volume move start command to move and unencrypt volume data."
---
= Unencrypt volume data
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `volume move start` command to move and unencrypt volume data.

.Before you begin

You must be a cluster administrator to perform this task. Alternately, you can be an SVM administrator to whom the cluster administrator has delegated authority. For more information, see link:delegate-volume-encryption-svm-administrator-task.html[Delegate authority to run the volume move command].

.Steps

. Move an existing encrypted volume and unencrypt the data on the volume:
+
`volume move start -vserver _SVM_name_ -volume volume_name -destination-aggregate _aggregate_name_ -encrypt-destination false`
+
For complete command syntax, see the man page for the command.
+
The following command moves an existing volume named `vol1` to the destination aggregate `aggr3` and unencrypts the data on the volume:
+
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr3 -encrypt-destination false
----
+
The system deletes the encryption key for the volume. The data on the volume is unencrypted.

. Verify that the volume is disabled for encryption:
+
`volume show -encryption`
+
For complete command syntax, see the man page for the command.
+
The following command displays whether volumes on `cluster1` are encrypted:
+
----
cluster1::> volume show -encryption

Vserver  Volume   Aggregate   State    Encryption State
-------  ------   ---------   -----    ----------------
vs1      vol1     aggr1       online   none
----
