---
sidebar: sidebar
permalink: s3-snapshots/list-restore-s3-snapshot.html
keywords: s3 snapshots, list, restore, browse S3 snapshots
summary: The ONTAP S3 snapshot feature enables you to view, browse, and restore the S3 snapshot content for your buckets from S3 clients.
---

= View and restore S3 snapshots 
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The ONTAP S3 snapshot feature enables you to view and browse the S3 snapshot content for your buckets from S3 clients. You can perform client-side restore of a single object, a set of objects, or a whole bucket from a snapshot copy. 

.Before you begin
For viewing, browsing, and restoring ONTAP S3 snapshots on your buckets, the snapshots should have been created and the S3 base bucket should be accessible to you through the S3 protocol client. 

== List and view S3 snapshots
You can view the S3 snapshot details, compare them, and identify and rectify errors. Using the ONTAP CLI, you can list all snapshots created on your S3 buckets. 

.Steps
. List S3 snapshots:

----
vserver object-store-server bucket snapshot show
----
You can view the snapshot names, storage VMs, buckets, creation time, and `instance-uuid` for all the S3 snapshots created for your buckets on the cluster.

Specifying the bucket name retrieves the name, creation time, and `instance-uuid` of all the S3 snapshots created for that bucket.

----
vserver object-store-server bucket snapshot show -vserver <vserver_name> -bucket <bucket_name>
----

== Browse S3 snapshots content
If you notice any failures or issues in your environment, you can browse the content of the S3 snapshots for a bucket to identify and fix the error, or restore a previous, error-free version.

S3 snapshots are presented as snapshot buckets in the S3 clients. The snapshot bucket name is formatted as `<base-bucket-name>-s3snap-<snapshot-name>`. You can see the all the snapshot buckets in a storage VM using the S3 `ListBuckets` API.

Additionally, if you have permissions to access the base bucket, you can also perform read-only S3 operations on the S3 snapshot bucket, such as HeadObject, GetObject, GetObjectTagging, ListObjects, ListObjectVersions, GetObjectAcl, and CopyObject. For more information about these functions, refer to link:../s3-config/ontap-s3-supported-actions-reference.html[ONTAP S3 supported actions].

== Restore S3 snapshots

You can perform a restore operation on the S3 client to recover a single object, a set of objects, or a whole bucket by copying content from a snapshot bucket to the original bucket or a different bucket. You can browse snapshots and determine the snapshot content to copy. 

You restore the entire bucket, objects with a prefix, or a single object,by using the `aws s3 cp` command.

.Steps

. Take a snapshot of the S3 bucket.
+
----
vserver object-store-server bucket snapshot create -vserver <vserver_name> -bucket <base_bucket_name> -snapshot <snapshot_name>
----
+
. Restore the base bucket using the snapshot:
** Restore an entire bucket:
+
----
aws --endpoint http://<IP> s3 cp s3://<snapshot-bucket-name> s3://<base-bucket>  --recursive
----
+
In this case, use the snapshot bucket name in the format `<base-bucket-name>-s3snap-<snapshot-name>`.
+
** Restore objects in a directory with the prefix `dir1`:
+
----
aws --endpoint http://<IP> s3 cp s3://<snapshot-bucket-name>/dir1 s3://<base-bucket-name>/dir1 --recursive
----
+
** Restore a single object named `web.py`:
+
----
aws --endpoint http://<IP> s3 cp s3:// <snapshot-bucket-name>/web.py s3://<base-bucket-name> /web.py
----

