---
permalink: s3-multiprotocol/create-nas-bucket-task.html
sidebar: sidebar
keywords: s3, svm, bucket, object, server, versioning, protocol, filesystems, nas, directories
summary: "An S3 NAS buckets is a mapping between an S3 bucket name and a NAS path. "
---
= Create an ONTAP S3 NAS bucket  
:icons: font
:imagesdir: ../media/

[.lead]
An S3 NAS bucket is a mapping between an S3 bucket name and a NAS path. S3 NAS buckets allow you to provide S3 access to any part of an SVM namespace having existing volumes and directory structure.

.Before you begin 

* An S3 object server is configured in an SVM containing NAS data. 
* The NAS data conforms to the link:nas-data-requirements-client-access-reference.html[requirements for S3 client access]. 

.About this task
You can configure S3 NAS buckets to specify any set of files and directories within the root directory of the SVM.

You can also set bucket policies that allow or disallow access to NAS data based on any combination of these parameters: 

* Files and directories
* User and group permissions
* S3 operations

For example, you might want to set up a bucket policy that grants read-only data access to a large group of users and another bucket policy that allows a limited group to perform operations on a subset of that data.

Beginning with ONTAP 9.18.1, you can create NAS buckets that enable applications to access data on FlexCache volumes using the S3 protocol. All nodes in the cluster must be running ONTAP 9.18.1 or later. Before you can access a FlexCache volume using the S3 protocol, you must set the `-is-s3-enabled` option to `true` link:../flexcache/create-volume-task.html[on the FlexCache volume]. The parameter is set to `false` by default.

Beginning with ONTAP 9.17.1, you can directly link a S3 NAS bucket to a volume rather than the junction path. By default, an S3 bucket on a NAS volume is associated with a junction path, which can be changed by an ONTAP administrator at any time. These changes can potentially disrupt S3 bucket operations. Beginning with ONTAP 9.17.1, you can use the `-is-nas-path-mutable false` option with the `vserver object-store-server bucket create` command in the ONTAP CLI to enable linking the S3 NAS bucket to a volume. By default, `-is-nas-path-mutable` is set to `true`.

Because S3 NAS "buckets" are mappings and not S3 buckets, the following properties of standard S3 buckets don't apply to S3 NAS buckets.

* *aggr-list \ aggr-list-multiplier \ storage-service-level \ volume \ size \ exclude-aggr-list \ qos-policy-group* +
No volumes or qtree are created when configuring S3 NAS buckets.
* *role \ is -protected \ is -protected-on-ontap \ is -protected-on-cloud* +
S3 NAS buckets are not protected or mirrored using SnapMirror S3, but instead use regular SnapMirror protection available at volume granularity.
* *versioning-state* +
NAS volumes usually have snapshot technology available to save different versions. However, versioning is not currently available in S3 NAS buckets.
* *logical-used \ object-count* +
Equivalent statistics are available for NAS volumes through the volume commands.
* *multipart objects* +
Beginning with ONTAP 9.16.1, multipart objects are supported in S3 NAS buckets when link:../flexgroup/enable-adv-capacity-flexgroup-task.html[advanced capacity balancing] is enabled on the underlying FlexGroup volume.
Advanced capacity balancing can only be enabled on FlexGroup volumes. It cannot be enabled on FlexVol volumes. 

.Steps

You can use System Manager or the ONTAP CLI to create a NAS bucket.

// start tabbed area

[role="tabbed-block"]
====

.System Manager
--
Add a new S3 NAS bucket on a NAS-enabled storage VM.

. Click *Storage > Buckets*, then click *Add*.
. Enter a name for the S3 NAS bucket and select the storage VM, do not enter a size, then click *More Options*.
. Enter a valid path name or click Browse to select from a list of valid path names. +
When you enter a valid pathname, options that are not relevant to S3 NAS configuration are hidden.
. If you have already mapped S3 users to NAS users and created groups, you can configure their permissions, then click *Save*. +
You must have already mapped S3 users to NAS users before configuring permissions in this step.

Otherwise, click *Save* to complete S3 NAS bucket configuration.
--

.CLI
--
. Create an S3 NAS bucket in an SVM containing NAS filesystems. +
`vserver object-store-server bucket create -vserver <svm_name> -bucket <bucket_name> -type nas -nas-path <junction_path> -is-nas-path-mutable true|false [-comment <text>]`
+
Example 1: Create a S3 NAS bucket 
+
`cluster1::> vserver object-store-server bucket create -bucket testbucket -type nas -path /vol1`
+
Example 2: Create an S3 NAS bucket and linking the bucket to a volume 
+
`vserver object-store-server bucket create -vserver vs1 -bucket nasbucket1 -type nas -nas-path /pathA/dir1 -is-nas-path-mutable false`
--

====

// end tabbed area

// 2025-Dec-8, ONTAPDOC-3406
// 2025-June-17, ONTAPDOC-2928
// 2025 May 07, linked to advanced capacity balancing
// 2024-Aug-30, ONTAPDOC-2346
// 2022 Nov 5, ONTAPDOC-564