---
permalink: consistency-groups/configure-task.html
sidebar: sidebar
keywords: consistency groups, consistency group, application protection, parent, child, configure
summary: "Create a single consistency group for application workload management and data protection."
---
= Configure a single consistency group
:icons: font
:imagesdir: ../media/

[.lead]
Consistency groups can be created with existing volumes or new LUNs. Once a volume is associated with a consistency group, it cannot be added with another consistency group.

Beginning in ONTAP 9.12.1, you can modify the member volumes of a consistency group. For more information on this process, refer to xref:modify-task.html[Modify a consistency group]. In ONTAP 9.10.1 through 9.11.1, modifying the member volumes of a consistency group is not supported.

== Create a consistency group with new LUNs

Creating a consistency group with new LUNs allows you to create and configure new LUNs in a new consistency group and set protection policies.

.Steps
. Select *Storage > Consistency groups*.
. Select *+Add* then *Using New LUNs*.
. Name the consistency group. Designate the number of LUNs and capacity per LUN.
.. **Application Type**: If you are using ONTAP 9.12.1 or later, select an application type. If no value is selected, the consistency group will be assigned the type of **Other** by default. Learn more about tagging consistency in xref:index.html#application-and-component-tags[Application and component tags]. If you plan to create an SM-BC relationship, you must use *Other*.
. Select the host operating system and LUN format. Enter the host initiator information.
. To configure protection policies, add a child consistency group, or show more options about host initiators, select *More options*.
. Select *Save*.
. Confirm your consistency group has been created by returning to the main consistency group menu where it will appear once the job completes. If you set a protection policy, you will know it has been applied when you see a green shield under look under the appropriate policy, remote or local.

== Create a consistency group with existing volumes

You can use existing volumes to create a consistency group.

.Steps
. Select *Storage > Consistency groups*.
. Select *+Add* then *Using existing volumes*.
. Name the consistency group and select the storage VM.
.. **Application Type**: If you are using ONTAP 9.12.1 or later, select an application type. If no value is selected, the consistency group will be assigned the type of **Other** by default. Learn more about tagging consistency in xref:index.html#application-and-component-tags[Application and component tags]. If the consistency group has an SM-BC relationship, you must use *Other*.
. Select the existing volumes to include. Only volumes that are not already part of a consistency group will be available for selection.
+
[NOTE]
If creating a consistency group with existing volumes, the consistency group supports FlexVol volumes. Volumes with Asynchronous or Synchronous SnapMirror relationships can be added to consistency groups, but they are not consistency group-aware. Consistency groups do not support S3 buckets, MetroCluster, or storage VMs with SVMDR relationships.
+
. Select *Save*.
. Confirm your consistency group has been created by returning to the main consistency group menu where it will appear once the ONTAP job completes. If you have chosen a protection policy, confirm it was properly set by selecting your consistency group from the menu. If you set a protection policy, look under the appropriate policy, remote or local, which should display a green shield with a checkmark.

.Next steps
* xref:protect-task.html[Protect a consistency group]
* xref:modify-task.html[Modify a consistency group]
* xref:clone-task.html[Clone a consistency group]

// 17 OCT 2022, ONTAPDOC-612
//29 october 2021, BURT 1401394, IE-364
