---
permalink: consistency-groups/limits.html
sidebar: sidebar
keywords: consistency groups, object limits
summary: "When planning your consistency groups, there are object limits you should be aware of."
---
= Consistency group limits
:icons: font
:imagesdir: ../media/

[.lead]
When planning and managing your consistency groups, account for object limits at the scope of both the cluster and the parent or child consistency group. 

== Limits

[NOTE]
If you are using SnapMirror Business Continuity, refer to link:../smbc/considerations-limits.html[SM-BC restrictions and limitations for limits].

|===
h| Limit h| Scope h| Minimum h| Maximum
| Number of consistency groups | Cluster | 0 | Same as maximum volume count in cluster
| Number of parent consistency groups | Cluster | 0 | Same as maximum volume count in cluster
| Number of individual and parent consistency groups | Cluster | 0 | Same as maximum volume count in cluster
| Number of volumes in a consistency group | Single consistency group | 1 volume | 80 volumes
| Number of volumes in the child of a parent consistency group | Parent consistency group | 1 volume  | 80 volumes 
| Number of volumes in a child consistency group | Child consistency group | 1 volume | 80 volumes 
| Number of child consistency groups in a parent consistency group | Parent consistency group | 1 consistency group | 5 consistency groups
|===

== Recommendations 

include:../_include/consistency-group-snapshot-minimum.adoc[]
+
This recommendation is based on link:https://www.netapp.com/media/12385-tr4571.pdf[testing for FlexGroups^], which share the same Snapshot infrastructure as consistency groups

// 2023 sept 22, ontapdoc-1375
// 9 Feb 2023, ONTAPDOC-880