---
sidebar: sidebar
permalink: concept_object_provision_overview.html
keywords: netapp, ontap, System Manager, StorageGRID, Amazon Simple Storage Service, S3, storage, object, object storage, object storage server, object provision, overview, on-premises, FabricPool, AFF, tier, tiering, bucket, remote, local, cluster, clusters, cloud tier, self-tiering, deployments, performance, throughput, capacity, latency, QoS
summary: Beginning with ONTAP 9.8, you can enable an Amazon Simple Storage Service (S3) object storage server in an ONTAP cluster.
---

= ONTAP S3 overview
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP 9.8, you can enable an ONTAP Simple Storage Service (S3) object storage server in an ONTAP cluster.

System Manager supports two on-premises use case scenarios for serving S3 object storage:

*	FabricPool tier to a bucket on local cluster (tier to a local bucket) or remote cluster (cloud tier).
*	S3 client app access to a bucket on the local cluster or a remote cluster.

For more information about tiering, see link:concept_cloud_overview.html[Cloud overview].

NOTE: ONTAP S3 is appropriate if you want S3 capabilities on existing clusters without additional hardware and management. For deployments larger than 300TB, NetApp StorageGRID software continues to be the NetApp flagship solution for object storage. For more information, see the link:https://docs.netapp.com/sgws-114/index.jsp[StorageGRID documentation].

When you create an S3 bucket using System Manager, ONTAP configures a default performance service level that is the highest available on your system. For example, on an AFF system, the default setting would be *Extreme*. Performance service levels are predefined adaptive Quality of Service (QoS) policy groups; instead of one of the default service levels, you can specify a custom QoS policy group or no policy group.

*	*Extreme*: Used for applications that expect the lowest latency and highest performance.
*	*Performance*: Used for applications with modest performance needs and latency.
*	*Value*: Used for applications for which throughput and capacity are more important than latency.
*	*Custom*: Specify a custom QoS policy or no QoS policy. See also link:
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-perf-mon/GUID-B144F39A-2E14-4048-91CA-D8080C50F70D.html[Using adaptive QoS policy groups].

If you check the box *Use for tiering*, no performance service levels are selected, and the system tries to select low-cost media with optimal performance for the tiered data.

ONTAP tries to provision this bucket on local tiers that have the most appropriate disks, satisfying the chosen service level. However, if you need to specify which disks to include in the bucket, consider configuring S3 object storage from the CLI by specifying the local tiers (aggregate). If you configure the S3 server from the CLI, you can still manage it with System Manager if desired. For more information, see link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html[S3 Configuration Power Guide].
