---
sidebar: sidebar
permalink: concept_dp_overview.html
keywords: netapp, ontap, protection, overview, data, protect, loss, backup, back up, types, mirror, vault, snapmirror, snapvault, SVM, storage VM, LIF, network interface, intercluster, single file snap restore, metrocluster, sfsr, disaster recovery, SnapMirror, protection policy, vault relationship, mirror relationship, relationship, snapshot, Snapshot copy, policy, schedule, replica, standards compliance, vault, default protection policy, asynchronous policy, synchronous policy, custom policy
summary: Protect your data by creating and managing Snapshot copies, mirrors, vaults, and mirror-and-vault relationships.
---

= Protect data
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The topics in this section show you how to configure and manage data protection with ONTAP System Manager in ONTAP 9.7 and later releases.

If you are using the ONTAP CLI to configure and manage data protection, see this content:

* link:https://docs.netapp.com/us-en/ontap/snaplock/index.html[Archive and Compliance Using SnapLock Technology Power Guide]
* link:https://docs.netapp.com/us-en/ontap/peering/index.html[Cluster and SVM Peering Power Guide]
* link:https://docs.netapp.com/us-en/ontap/data-protection/index.html[Data Protection Power Guide]
* link:https://docs.netapp.com/us-en/ontap/tape-backup/index.html[Data Protection Tape Backup and Recovery Guide]
* link:https://docs.netapp.com/us-en/ontap/ndmp/index.html[NDMP Configuration Express Guide]
* link:https://docs.netapp.com/us-en/ontap/element-replication/index.html[Replication between NetApp Element Software and ONTAP]

If you are using legacy OnCommand System Manager for ONTAP 9.7 and earlier releases to configure and manage data protection, see the content for your ONTAP release:

* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/home.html[Cluster and SVM Peering Express Guide]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-fr/home.html[Volume Disaster Recovery Express Guide]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-cg/home.html[Volume Disaster Recovery Preparation Express Guide]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-buvault/home.html[Volume Backup Using SnapVault Express Guide]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-buvault-restore/home.html[Volume Restore Using SnapVault Express Guide]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/home.html[Cluster management using System Manager 9.6 and 9.7]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-950/home.html[Cluster management using System Manager 9.5]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-930/home.html[Cluster management using System Manager 9.3 and 9.4]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-900/home.html[Cluster management using System Manager 9.2 and earlier]

== Data protection overview
Protect your data by creating and managing Snapshot copies, mirrors, vaults, and mirror-and-vault relationships.

//updated for GitHub Issue 89, June 17, aherbin
_SnapMirror_ is disaster recovery technology, designed for failover from primary storage to secondary storage at a geographically remote site. As its name implies, SnapMirror creates a replica, or mirror, of your working data in secondary storage from which you can continue to serve data in the event of a catastrophe at the primary site.

A _vault_ is designed for disk-to-disk Snapshot copy replication for standards compliance and other governance-related purposes. In contrast to a SnapMirror relationship, in which the destination usually contains only the Snapshot copies currently in the source volume, a vault destination typically retains point-in-time Snapshot copies created over a much longer period.
