---
sidebar: sidebar
permalink: concept_metrocluster_manage_nodes.html
keywords: system manager, manage, metrocluster, clusters, nodes, mcc, HA, config, peering, peers, pairing, pairs
summary: Beginning with ONTAP 9.8, you can manage MetroCluster operations with System Manager.
---

= MetroCluster site management overview with System Manager
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP 9.8, you can use System Manager as a simplified interface for managing a configuration of a MetroCluster setup.

A MetroCluster configuration allows two clusters to mirror data to each other so if one cluster goes down, the data isn't lost.

Typically, an organization sets up the clusters in two separate geographical locations. An administrator at each location sets up a cluster and configures it. Then one of the administrators can set up the peering between the clusters so that they can share data.

The organization can also install an ONTAP Mediator in a third location.  The ONTAP Mediator service monitors the status of each cluster. When one of the clusters detects that it cannot communicate with the partner cluster, it queries the monitor to determine if the error is a problem with the cluster system or with the network connection.

If the problem is with the network connection, the system administrator performs troubleshooting methods to correct the error and reconnect. If the partner cluster is down, the other cluster initiates a switchover process to control the data I/O for both clusters.

You can also perform a switchover to bring down one of the cluster systems for planned maintenance.  The partner cluster handles all data I/O operations for both clusters until you bring up the cluster on which you performed maintenance and perform a switchback operation.

You can manage the following operations:

* link:task_metrocluster_setup.html[Set up an IP MetroCluster site]

* link:task_metrocluster_peering.html[Set up IP MetroCluster peering]

* link:task_metrocluster_configure.html[Configure an IP MetroCluster site]

* link:task_metrocluster_switchover_switchback.html[Perform IP MetroCluster switchover and switchback]

* link:task_metrocluster_troubleshooting.html[Troubleshoot problems with IP MetroCluster configurations]

* link:task_metrocluster_ANDU_upgrade.html[Upgrade ONTAP on MetroCluster clusters]

// 28 SEP 2020, BURT 1323833, new topic for 9.8, thomi
// 23 OCT 2020, thomi....review comments...all topics except ANDU apply only to IP
// 07 DEC 2021, BURT 1430515
