---
sidebar: sidebar
permalink: concept_dp_overview.html
keywords: netapp, ontap, protection, overview, data, protect, loss, backup, back up, types, mirror, vault, snapmirror, snapvault, SVM, storage VM, LIF, network interface, intercluster, single file snap restore, metrocluster, sfsr, disaster recovery, SnapMirror, protection policy, vault relationship, mirror relationship, relationship, snapshot, Snapshot copy, policy, schedule, replica, standards compliance, vault, default protection policy, asynchronous policy, synchronous policy, custom policy
summary: Protect your data by creating and managing Snapshot copies, mirrors, vaults, and mirror-and-vault relationships.
---

= Data protection overview with System Manager
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The topics in this section show you how to configure and manage data protection with ONTAP System Manager in ONTAP 9.7 and later releases.

Protect your data by creating and managing Snapshot copies, mirrors, vaults, and mirror-and-vault relationships.

_SnapMirror_ is disaster recovery technology, designed for failover from primary storage to secondary storage at a geographically remote site. As its name implies, SnapMirror creates a replica, or mirror, of your working data in secondary storage from which you can continue to serve data in the event of a catastrophe at the primary site.

A _vault_ is designed for disk-to-disk Snapshot copy replication for standards compliance and other governance-related purposes. In contrast to a SnapMirror relationship, in which the destination usually contains only the Snapshot copies currently in the source volume, a vault destination typically retains point-in-time Snapshot copies created over a much longer period.

//updated for GitHub Issue 89, June 17, aherbin
