---
sidebar: sidebar
permalink: concept_rest_overview.html
keywords: netapp, ontap, rest, rest api, rest api log, api log, rest overview
summary: The REST API log captures the API calls that System Manager issues to ONTAP. You can use the log to understand the nature and sequence of the API calls needed to perform various ONTAP administrative tasks.
---

= Rest API management with System Manager
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The REST API log captures the API calls that System Manager issues to ONTAP. You can use the log to understand the nature and sequence of the calls needed to perform the various ONTAP administrative tasks.

== How System Manager uses the REST API and API log

There are several ways that REST API calls are issued by System Manager to ONTAP.

=== When does System Manager issue API calls

Here are the most important examples of when System Manager issues ONTAP REST API calls.

==== Automatic page refresh
System Manager automatically issues API calls in the background to refresh the displayed information, such as on the dashboard page.

==== Display action by user
One or more API calls are issued when you display a specific storage resource or a collection of resources from the System Manager UI.

==== Update action by user
An API call is issued when you add, modify, or delete an ONTAP resource from the System Manager UI.

=== Reissuing an API call

You can also manually reissue an API call by clicking a log entry. This displays the raw JSON output from the call.

== More information

* link:https://docs.netapp.com/us-en/ontap-automation/[ONTAP 9 Automation docs^]
