---
sidebar: sidebar
permalink: concept_nas_file_system_analytics_overview.html
keywords: netapp, ontap, file, system, analytics, overview, volume, volumes, FlexGroup, FlexVol, ONTAP System Manager, monitor file, evaluate file activity, assess capacity usage, corrective action, 7-mode
summary: File System Analytics is a framework for collecting and displaying data about the contents of a FlexGroup or FlexVol volume.
---

= File System Analytics overview
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
File System Analytics is a framework for collecting and displaying data about the contents of a FlexGroup or FlexVol volume.

File System Analytics presents detailed information at each level of the volume’s file system hierarchy, allowing you to:

*	Assess capacity usage and trends
*	Monitor file and directory counts
*	Evaluate file activity and history
* Take corrective action based on displays (beginning with ONTAP 9.9.1)

In ONTAP 9.8 and later, File System Analytics data can be displayed using ONTAP System Manager. You can also use ONTAP REST APIs to access the data programmatically.

*NOTES:*

* Enabling File System Analytics is expected to have a performance impact. Do not enable analytics if maximal performance is required in your environment. You can also disable analytics if your testing shows that the performance impact is unacceptable. When you disable analytics, previously collected data is no longer displayed for that volume.
* If you have enabled File System Analytics on volumes whose containing storage VM is in a protection relationship, the analytics data is not replicated to the destination storage VM. If the source storage VM must be resynchronized in a recovery operation, you must manually re-enable File System Analytics on desired volumes after recovery.
* Beginning with ONTAP 9.9.1, File System Analytics is available for volumes transitioned from 7-mode systems. Nonetheless, because File System Analytics data can consume storage space, it should not be run on transitioned volumes that are close to maximum capacity.

File System Analytics is not available for the following volume types:

*	SnapMirror destination volumes
*	SnapLock volumes
*	Volumes containing LUNs
*	Volumes used only to hold SMB/CIFS audit logs
*	Node root volumes (/mroot)

// 2020-09-28, BURT 1289113
// 2021-04-12, BURT 1382699
// 2021-04-14, BURT 1376903
// 2021-05-21, BURT 1374049
// 2021-05-21, BURT 1385863
// 2021-06-10, TN-0058 and TN-0059
