---
sidebar: sidebar
permalink: concept_administration_overview.html
keywords: netapp, ontap, administration, overview, cluster, node, local tier, aggregate, svm, storage vm, service level, volume, qtree, LUN, automatic aggregate selection, vserver, protocol, quota, disk, HA pair, dashboard, subnet, domain, interface, mirroring, vaulting, storage
summary: ONTAP System Manager lets you to manage storage systems and storage objects and perform common management tasks related to storage systems from a web browser.
---

= Administration overview
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
ONTAP System Manager is a graphical management interface that enables you to use a web browser to manage storage systems and storage objects (such as disks, volumes, and storage tiers) and perform common management tasks related to storage systems.

Using the System Manager Dashboard, you can view at-a-glance information about important alerts and notifications, the efficiency and capacity of storage tiers and volumes, the nodes that are available in a cluster, the status of the nodes in an HA pair, the most active applications and objects, and the performance metrics of a cluster or a node.



With System Manager you can perform many common tasks, such as the following:

* Create a cluster, configure a network, and set up support details for the cluster.

* Configure and manage storage objects, such as disks, aggregates, volumes, qtrees, and quotas.

* Configure protocols, such as CIFS and NFS, and provision file sharing.

* Configure protocols such as FC, FCoE, NVMe, and iSCSI for block access.

* Create and configure network components, such as subnets, broadcast domains, data and management interfaces, and interface groups.

* Set up and manage mirroring and vaulting relationships.

* Perform cluster management, storage node management, and storage virtual machine (storage VM) management operations.

* Create and configure storage VMs, manage storage objects associated with storage VMs, and manage storage VM services.

* Monitor and manage high-availability (HA) configurations in a cluster.

* Configure service processors to remotely log in, manage, monitor, and administer the node, regardless of the state of the node.
