---
sidebar: sidebar
permalink: concept_nas_provision_overview.html
keywords: netapp, ontap, provisioning, nas, overview, provision NAS storage, manage NAS services, NAS file service, Linux client, Windows client, NAS multiprotocol, name service, name service switch, NFS, SMB, DNS, LDAP, NIS, Kerberos security, export, share, qtree, name mapping, NAS data service
summary: ONTAP enables you to serve data to Linux and Windows clients simply, securely, and efficiently.
---

= NAS management overview with System Manager
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The topics in this section show you how to configure and manage NAS environments with System Manager in ONTAP 9.7 and later releases.

If you are using the classic System Manager (available only in ONTAP 9.7 and earlier), see these topics:

* https://docs.netapp.com/us-en/ontap-sm-classic/nfs-config/index.html[NFS configuration overview^]

* https://docs.netapp.com/us-en/ontap-sm-classic/smb-config/index.html[SMB configuration overview^]

System Manager supports workflows for:

* Initial configuration of clusters that you intend to use for NAS file services.

* Additional volume provisioning for changing storage needs.

* Configuration and maintenance for industry-standard authentication and security facilities.

Using System Manager, you can manage NAS services at the component level:

* Protocols - NFS, SMB, or both (NAS multiprotocol)

* Name services - DNS, LDAP, and NIS

* Name service switch

* Kerberos and TLS security

* Exports and shares

* Qtrees

* Name mapping of users and groups
