---
sidebar: sidebar
permalink: concept_metrocluster_manage_nodes.html
keywords: system manager, manage, metrocluster, clusters, nodes, mcc, HA, config, peering, peers, pairing, pairs
summary: Beginning with ONTAP 9.8, you can manage MetroCluster operations with System Manager.
---

= Manage MetroCluster IP sites with System Manager
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP 9.8, you can use System Manager as a simplified interface for managing a MetroCluster IP configuration.

A MetroCluster configuration allows two clusters to mirror data to each other so if one cluster goes down, you can recover the data. 

NOTE: You can only perform MetroCluster operations using System Manager in a MetroCluster IP configuration. In a MetroCluster FC configuration, you can still use System Manager, but you can't perform any MetroCluster-specific operations.  

Typically, an administrator at each site sets up and configures the clusters in two separate geographical locations. In eight-node or four-node MetroCluster IP configurations, each site consists of storage controllers configured as one or two HA pairs. You can set up peering between the clusters so that they synchronize and share data.

You can also install an ONTAP Mediator in a third location to monitor the state of the nodes and their disaster recovery (DR) partners. If one of the clusters detects that it cannot communicate with the partner cluster, it queries to determine if the error is a problem with the cluster system or with the network connection.

If the problem is with the network connection, the system performs troubleshooting methods to correct the error and reconnect. If the partner cluster is down, the other cluster initiates a switchover to control the data I/O for both clusters. The ONTAP Mediator service can implement a Mediator-assisted unplanned switchover (MAUSO) in the case of a disaster.

You can also perform a switchover to bring down one of the cluster systems for planned maintenance. The partner cluster handles all data I/O operations for both clusters until you bring up the cluster that you performed maintenance on and perform a switchback operation.

You can find procedures for setting up and managing a MetroCluster IP configuration using System Manager in the link:https://docs.netapp.com/us-en/ontap-metrocluster/index.html[MetroCluster documentation]. 

// 28 SEP 2020, BURT 1323833, new topic for 9.8, thomi
// 23 OCT 2020, thomi....review comments...all topics except ANDU apply only to IP
// 07 DEC 2021, BURT 1430515
