---
sidebar: sidebar
permalink: concept_dp_overview.html
keywords: netapp, ontap, protection, overview, data, protect, loss, backup, back up, types, mirror, vault, snapmirror, snapvault, SVM, storage VM, LIF, network interface, intercluster, single file snap restore, metrocluster, sfsr, disaster recovery, SnapMirror, protection policy, vault relationship, mirror relationship, relationship, snapshot, Snapshot copy, policy, schedule, replica, standards compliance, vault, default protection policy, asynchronous policy, synchronous policy, custom policy
summary: Protect your data by creating and managing Snapshot copies, mirrors, vaults, and mirror-and-vault relationships.
---

= Data protection overview with System Manager
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The topics in this section show you how to configure and manage data protection with System Manager in ONTAP 9.7 and later releases.

If you are using System Manager in ONTAP 9.7 or earlier, see link:https://docs.netapp.com/us-en/ontap-system-manager-classic/index.html[ONTAP System Manager Classic documentation^]

Protect your data by creating and managing Snapshot copies, mirrors, vaults, and mirror-and-vault relationships.

_SnapMirror_ is disaster recovery technology, designed for failover from primary storage to secondary storage at a geographically remote site. As its name implies, SnapMirror creates a replica, or mirror, of your working data in secondary storage from which you can continue to serve data in the event of a catastrophe at the primary site.

A _vault_ is designed for disk-to-disk Snapshot copy replication for standards compliance and other governance-related purposes. In contrast to a SnapMirror relationship, in which the destination usually contains only the Snapshot copies currently in the source volume, a vault destination typically retains point-in-time Snapshot copies created over a much longer period.

Beginning with ONTAP 9.10.1, you can create data protection relationships between S3 buckets using S3 SnapMirror. Destination buckets can be on local or remote ONTAP systems, or on non-ONTAP systems such as StorageGRID and AWS. For more information, see link:s3-snapmirror/index.html[S3 SnapMirror overview].

// 2022-8-2, issue #606
// 2021-12-16, Jira IE-412
//updated for GitHub Issue 89, June 17, aherbin
