---
sidebar: sidebar
permalink: concept-svm-admin-dashboard-sm.html
keywords: netapp, system manager, ontap, administration, overview, svm, storage vm, volume, vserver, dashboard, administrator, tenant, multi-tenancy, protocol, network interface, performance, learn
summary: SVM administrators can monitor and manage their own SVMs using a dedicated System Manager dashboard. This is particularly useful in a tenanted ONTAP environment, where the cluster administrator can provide an SVM dashboard for each tenant.
---
= Learn about the ONTAP System Manager SVM administrator dashboard
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP 9.19.1, SVM administrators can monitor and manage their SVMs using a dedicated System Manager dashboard and the Storage > Volumes page. This is particularly useful in a tenanted ONTAP environment, where the cluster administrator can provide an SVM dashboard for each tenant.

The cluster administrator provides login credentials to SVM administrators. SVM administrators can view details and performance on the SVM dashboard and the *Storage > Volumes* page. The dashboard shows SVM protocols, network interfaces, details, and performance metrics. The Volume page provides information about the SVM volumes and, if allowed by the cluster administrator, the ability for the SVM administrator to add new volumes. 

.What's Next
link:task-assign-svm-admin-access-sm.html[Assign SVM administrator access with ONTAP System Manager]

// 2026 February 4-18, ONTAPDOC-3605 and NADIAA

