---
sidebar: sidebar
permalink: concept_quotas_overview.html
keywords: netapp, ontap, quotas, quota, managing, resources, qtree, qtrees, disk space, hard quota, soft quota
summary: Quotas provide a way to restrict or track the disk space and number of files used by a user, group, or qtree. Quotas are applied to a specific volume or qtree.
---

= Manage resources using quotas
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Beginning with ONTAP 9.7, you can configure and manage usage quotas with System Manager.

If you are using the ONTAP CLI to configure and manage usage quotas, refer to link:./volumes/index.html[Logical Storage Management].

If you are using legacy OnCommand System Manager for ONTAP 9.7 and earlier releases to configure and manage usage quotas, see the following for your release:

* link:http://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/index.html[ONTAP 9.6 and 9.7 Documentation^]
* link:https://mysupport.netapp.com/documentation/docweb/index.html?productID=62686&language=en-US[ONTAP 9.5 Documentation^]
* link:https://mysupport.netapp.com/documentation/docweb/index.html?productID=62594&language=en-US[ONTAP 9.4 Documentation^]
* link:https://mysupport.netapp.com/documentation/docweb/index.html?productID=62579&language=en-US[ONTAP 9.3 Documentation^]
* link:https://mysupport.netapp.com/documentation/docweb/index.html?productID=62499&language=en-US&archive=true[ONTAP 9.2 Archived Documentation^]
* link:https://mysupport.netapp.com/documentation/docweb/index.html?productID=62320&language=en-US&archive=true[ONTAP 9.0 Archived Documentation^]


== Quota overview
Quotas provide a way to restrict or track the disk space and number of files used by a user, group, or qtree. Quotas are applied to a specific volume or qtree.

You can use quotas to track and limit resource usage in volumes and provide notification when resource usage reaches specific levels.

Quotas can be soft or hard. Soft quotas cause ONTAP to send a notification when specified limits are exceeded, and hard quotas prevent a write operation from succeeding when specified limits are exceeded.

// BURT 1448684, 10 JAN 2022
