---
sidebar: sidebar
permalink: concept_file_system_analytics_overview.html
keywords: netapp, ontap, file, system, analytics, overview, volume, volumes, FlexGroup, FlexVol, ONTAP System Manager, monitor file, evaluate file activity, assess capacity usage
summary: File System Analytics is a framework for collecting and displaying data about the contents of a FlexGroup or FlexVol volume.
---

= File system analytics overview
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
File System Analytics is a framework for collecting and displaying data about the contents of a FlexGroup or FlexVol volume.

File System Analytics presents detailed information at each level of the volume’s file system hierarchy, allowing you to:

*	assess capacity usage and trends
*	monitor file and directory counts
*	evaluate file activity and history

When enabled in ONTAP 9.8 and later releases, File System Analytics can be displayed using ONTAP System Manager. You can also use ONTAP REST APIs to access the data programmatically.

Enabling File System Analytics is expected to have a performance impact. You might choose not to enable analytics if maximal performance is required in your environment. You can also disable analytics if your testing shows that the performance impact is unacceptable. When you disable analytics, previously collected data is no longer displayed for that volume.

File System Analytics is not currently available for the following volume types:

*	FlexCache destination volumes
*	SnapMirror destination volumes
*	SnapLock volumes
*	volumes containing LUNs
*	volumes used for SMB/CIFS audit
*	volumes transitioned from 7-mode systems
*	node root volumes (/mroot)

//28Sep2020, BURT 1289113, forry
