---
sidebar: sidebar
permalink: concept_nas_provision_overview.html
keywords: netapp, ontap, provisioning, nas, overview
summary: ONTAP enables you to serve data to Linux and Windows clients simply, securely, and efficiently.
---

= NAS overview
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
ONTAP enables you to serve data to Linux and Windows clients simply, securely, and efficiently.

ONTAP System Manager supports workflows for:

* initial configuration of clusters that you intend to use for NAS file services.

* additional volume provisioning for changing storage needs.

* configuration and maintenance for industry-standard authentication and security facilities.

Using ONTAP System Manager, you can manage NAS services at the component level:

* Protocols – NFS, SMB, or both (NAS multiprotocol)

* Name services – DNS, LDAP, and NIS

* Name service switch

* Kerberos security

* Exports and shares

* Qtrees

* Name mapping of users and groups

If you need to learn more about ONTAP NAS features, you can review the _Concepts_ guide and _Provisioning for NAS protocols_ section in the link:https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.dot-cm-concepts%2FGUID-3E2E1403-9C89-4BD4-AB66-463465A08BED.html[ONTAP 9 Documentation Center].
