---
sidebar: sidebar
permalink: concept_cloud_overview.html
keywords: netapp, ontap, cloud, FabricPool, Fabric Pool, NDAS, cloud volumes, data availability services, install, installing, cluster, set up, setup, configure, disk, data port, guided setup, local tier, aggregate, Alibaba, Amazon, Google Cloud, IBM Cloud, Microsoft Azure Blob, All Flash, StorageGRID, all SSD, tiering, cloud tier
summary: You can use FabricPool to automatically tier data depending on how frequently the data is accessed.
---

= Extend to the cloud
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The topics in this section show you how to configure and manage a cloud tier with ONTAP System Manager in ONTAP 9.7 and later releases.

 If you are using the ONTAP CLI to configure and manage a cloud tier, see this content:

* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mgng-stor-tier-fp/home.html[Managing Storage Tiers By Using FabricPool]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html[S3 Configuration Power Guide]

If you are using legacy OnCommand System Manager for ONTAP 9.5-9.7 releases to configure and manage a cloud tier, see the content for your ONTAP release:

* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/home.html[Cluster management using System Manager 9.6 and 9.7]
* link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-950/home.html[Cluster management using System Manager 9.5 ]
 
== Cloud overview

You can use FabricPool to automatically tier data depending on how frequently the data is accessed.

FabricPool is a hybrid storage solution that uses an all flash (all SSD) aggregate as the performance tier and an object store as the cloud tier. Using a FabricPool helps you reduce storage cost without compromising performance, efficiency, or protection.

The cloud tier can be located on NetApp StorageGRID or ONTAP S3 (beginning with ONTAP 9.8), or one of the following service providers:

* Alibaba cloud

* Amazon S3

* Google Cloud

* IBM cloud

* Microsoft Azure Blob Storage

video::Vs1-WMvj9fI[youtube, width=848, height=480]
