---
sidebar: sidebar
permalink: concept_key_ontap.html
keywords: netapp, ontap, cluster, node, local tier, cloud tier, aggregate, SVM, storage VM, service level, volume, qtree, LUN, automatic aggregate selection, tier selection, vserver, ONTAP concepts, terms, Snapshot copy, data protection, mirroring, HA pair, storage efficiency, compression, deduplication, compaction, multifactor authentication, client, LUN, NVMe namespace, flash storage
summary: A quick introduction to ONTAP, and some terminology changes for current customers
---

= Key concepts
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

NetApp ONTAP is NetApp’s proven data management software. You can run ONTAP in your data center on NetApp-engineered hardware, on your commodity hardware, or in any of the major public clouds.

//BURT 1353463. Oct 5,2020 thomi,  Change to be inclusive for 9.7, 9.8

Starting with ONTAP 9.7, you can manage your system with the all-new ONTAP System Manager interface. This web-based interface gets you up and running with just a few clicks.

ONTAP System Manager gives you a clear visual of the status of your cluster and guides you on the best ways to achieve your storage goals.

If you are familiar with a previous version of ONTAP, you will feel right at home.  There are a few terminology changes with ONTAP System Manager that you should be aware of.

* *Local tier* – a set of physical solid-state drives or hard-disk drives you store your data on. You might know these as aggregates. In fact, if you use the ONTAP CLI, you will still see the term _aggregate_ used to represent a local tier.

*	*Cloud tier* – storage in the cloud used by ONTAP when you want to have some of your data off premises for one of several reasons. If you are thinking of the cloud part of a FabricPool, you’ve already figured it out. And if you are using a StorageGRID system, your cloud might not be off premises at all. (A cloud like experience on premises is called a _private cloud_.)

*	*Storage VM* – a virtual machine running within ONTAP that provides storage and data services to your clients. You might know this as an _SVM_ or a _vserver_.

* *Network interface* -  an address and properties assigned to a physical network port.  You might know this as a _logical interface (LIF)_.

If you are new to ONTAP, here are a few other concepts that will get you up to speed.

*	*Cluster* – that’s the big picture. A cluster is made up of one or more nodes. Think of nodes as computers that specialize in data management and storage. You can add nodes to your cluster as your needs grow, or you can replace smaller nodes with bigger ones. All without interrupting access to your data, of course.

*	*Snapshot copies* – these are instant copies of your data that you can use to undo a mistake, move or back up to cloud, mirror to another cluster, or even copy to tape. Without interruption to your clients. And who can afford downtime?

*	*Data protection* - the protection features you use depend on what you need to protect against and how long you can wait to recover if something goes wrong. ONTAP offers synchronous and asynchronous mirroring and more.

* *HA pair* – speaking of avoiding downtime, the high-availability pair is the basic unit of an ONTAP cluster. It’s made up of two partner nodes that can take over for each other. Say you want to upgrade to the latest version of ONTAP to get a great new data management feature. Just have the partner take over a node’s client load, upgrade that client, and then give the load back. Repeat for the partner node and you have just upgraded without any disruption.

* *Storage efficiency* – disks cost money (real money!), but storage efficiency lets you store more data in less space. And that saves real money and makes you a data hero. You can use any or all of ONTAP's compression, deduplication, and compaction features. We're sure you already know what compression is. Deduplication identifies multiple copies of the same data and replaces the duplicates with pointers to a single copy. Compaction puts multiple small files into a single block of storage, filling in what would otherwise be wasted space.

*	*Security* – security is integral to ONTAP data management software. ONTAP helps you out in many ways, such as using multifactor authentication for administrators, encrypting data on disk and in flight, and using antivirus tools to protect Windows files.

* *Volumes* – are exactly what you think volumes are. They're containers to store files. You can export volumes to Linux clients, share volumes with Windows clients, or even do both at the same time with the same files.

*	*LUNs* – the basic unit of SAN. That’s Fibre Channel and iSCSI. In a SAN environment, ONTAP provides virtual disks to clients instead of files. Database administrators often want virtual disks that they can manage at a low level or apply a specialized file system to. Many ONTAP systems, but not all, can serve data to SAN clients.

* *NVMe namespaces* – the future of flash storage. The NVMe protocol is optimized for SSD-based storage, and it is really fast. NVMe is a flavor of SAN, but the basic unit of storage is called a _namespace_ instead of a LUN.

So now you know the basics of ONTAP and you’re ready to get to work. Read the sections that follow to learn how to set up and manage your cluster with System Manager.

If you want to learn even more, check out the ONTAP link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html[Concepts Guide]. Join a NetApp community. And just click around to see what else is there.

//BURT 1353463, Oct 5,2020 
