---
layout: astra
sidebar: sidebar
permalink: index.html
keywords: ontap, netapp, documentation, system, manager
summary: ONTAP System Manager is a simple and versatile product that enables you to easily configure and manage ONTAP clusters. System Manager simplifies common storage tasks such as creating volumes, LUNs, qtrees, shares, and exports, which saves time and helps prevent errors.
---

= ONTAP System Manager docs
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
ONTAP System Manager (formerly OnCommand System Manager) is a simple and versatile product that enables you to easily configure and manage ONTAP clusters. System Manager simplifies common storage tasks such as creating volumes, LUNs, qtrees, shares, and exports, which saves time and helps prevent errors.

Beginning with ONTAP 9.7, a totally redesigned ONTAP System Manager simplifies ONTAP management with an intuitive graphical user interface. The new dashboard shows key cluster status and performance on one screen.

The documentation for ONTAP System Manager is totally redesigned as well. Easy-to-navigate content is quick and easy to use. Watch embedded videos for quick overviews of major management tasks.

For information on previous versions of System Manager, see the link:https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center].

video::XkPoq3E3MeU[youtube, width=848, height=480]

== Benefits of using ONTAP System Manager

* Fast, simple configuration
Simplified workflows for ONTAP setup and management of common tasks.
* Smart defaults
Enable you to create best-practice configurations based on proven deployments.
* Extensive administrative capabilities
Easily configure and provision storage for file sharing, application and database workloads.
* Integrated management
System Manager comes bundled with the ONTAP 9 platform, eliminating the need for a separate installation.

//== Learn more about ONTAP System Manager
//_Add link to video when available_
