---
sidebar: sidebar
permalink: metrocluster-setup-l3-task.html
keywords: metrocluster, layer 3, edit, gateway, netmask, net mask, configuration, configure
summary: "Beginning with ONTAP 9.10.1, you can change the IP address and mask, and gateway of a MetroCluster IP interface."
---

= Modify address, netmask, and gateway in a MetroCluster IP
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP 9.10.1, you can change the following properties of a MetroCluster IP interface: IP address and mask, and gateway. You can use any combination of parameters to update.

You might need to update these properties, for example, if a duplicate IP address is detected or if a gateway needs to change in the case of a layer 3 network due to router configuration changes. You can only change one interface at a time. There will be traffic disruption on that interface until the other interfaces are updated and connections are reestablished.

NOTE: You must make the changes on each port. Similarly, network switches also need to update their configuration. For example, if the gateway is updated, ideally it is changed on both nodes of an HA pair, since they are same. Plus the switch connected to those nodes also needs to update its gateway.

.Step
Update the IP address, netmask, and gateway for a each node and interface.
// IE-375
// 08 DEC 2021, BURT 1430515
