settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    lipi_enabled: true
  search: ontap, ontap-metrocluster, ontap-fli, ontap-automation, ontap-cli

sidebar:
  entries:
    - title: ONTAP docs
      url: /index.html
    - section: release-notes
    - section: introduction-concepts
    - section: setup-upgrade
    - section: cluster-admin
    - section: volume-admin
    - section: network-management
    - section: nas-management
    - section: san-management
    - section: object-storage-management
    - section: authentication-access-control
    - section: security-encryption
    - section: data-protection-disaster-recovery
    - section: event-performance-monitoring
    - title: ONTAP manual pages 
      url: /concepts/manual-pages.html
    - title: Legal notices
      url: /legal-notices.html

product-family: 
  name: ONTAP
  repo: ontap-family
 
