jekyll: bn-index-split
settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: false
    lipi_enabled: false
  search: ontap, ontap-metrocluster, ontap-sm-classic, ontap-fli, ontap-automation, ontap-cli-9141

sidebar:
  entries:
    - title: ONTAP docs
      url: /index.html
    - section: release-notes
    - title: System Manager integration with BlueXP
      url: /sysmgr-integration-bluexp-concept.html  
    - section: introduction-concepts
    - section: setup-upgrade
    - section: cluster-admin
    - section: volume-admin
    - section: network-management
    - section: nas-management
    - section: san-management
    - section: object-storage-management
    - section: authentication-access-control
    - section: security-encryption
    - section: data-protection-disaster-recovery
    - section: event-performance-monitoring
    - title: ONTAP manual pages 
      url: /concepts/manual-pages.html
    - title: Legal notices
      url: /legal-notices.html

product-family: 
  name: ONTAP
  repo: ontap-family
  sidebar_label: All ONTAP product documentation
