---
sidebar: sidebar
permalink: sysmgr-integration-bluexp-concept.html
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud
summary: Beginning with ONTAP 9.12.1, System Manager is fully integrated with BlueXP.  With BlueXP, you can manage your hybrid multicloud infrastructure from a single control plane while retaining the familiar System Manager dashboard.
---
= System Manager integration with BlueXP
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP 9.12.1, System Manager is fully integrated with BlueXP.  With BlueXP, you can manage your hybrid multicloud infrastructure from a single control plane while retaining the familiar System Manager dashboard.

== Integration overview

When you access System Manager on an on-premises ONTAP cluster running ONTAP 9.12.1 or later with connectivity to the BlueXP service, you’ll be prompted to manage the cluster directly from BlueXP. From BlueXP, you’ll have access to the System Manager interface that you’re used to, plus access to BlueXP functionality.

BlueXP enables you to create and administer cloud storage (for example, Cloud Volumes ONTAP), use NetApp’s data services (for example, Cloud Backup), and control many on-premise and edge storage devices.

== Manage your ONTAP clusters from BlueXP

When you’re ready to manage your ONTAP clusters from BlueXP, you can follow the link that appears when you try to access System Manager, or you can go directly to BlueXP. Going directly to BlueXP provides an advantage, if you’d like to use BlueXP’s data services to back up data, scan and categorize your data, and more.

=== Use the link from System Manager

When you connect to the cluster management network interface from your web browser, you’ll be prompted to manage the cluster with System Manager in BlueXP or to use System Manager directly. To use System Manager in BlueXP, perform the following steps:

.Steps

. Open a web browser and enter the IP address of the cluster management network interface.
+
If the cluster has connectivity to BlueXP, a login prompt displays.

. Click *Continue to BlueXP* to follow the link to BlueXP.

. On the BlueXP login page, select *Log in with your NetApp Support Site Credentials* and enter your credentials.
+
If you’ve already used BlueXP and have a login using an email and password, then you’ll need to continue using that login option instead.
+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html[Learn more about logging in to BlueXP^].

. If you’re prompted, enter a name for your new BlueXP account.
+
In most cases, BlueXP automatically creates an account for you based on data from your cluster.

. Enter the cluster administrator credentials for the cluster.

.Result

System Manager displays and you can now manage the cluster from BlueXP.

=== Discover your clusters directly from BlueXP

BlueXP provides two ways to discover and manage your clusters:

* Direct discovery for management through System Manager
+
This is the same discovery option described in the previous section with which you follow the redirect.

* Discovery through a Connector 
+
The Connector is software installed in your environment which allows you to access management functions through System Manager and also access BlueXP cloud services that provide features such as data replication, backup and recovery, data classification, data tiering, and more.

Go to the https://docs.netapp.com/us-en/cloud-manager-family/index.html[BlueXP documentation^] to learn more about these discovery and management options.

== Learn more about BlueXP

* https://docs.netapp.com/us-en/cloud-manager-family/concept-overview.html[BlueXP overview^]

* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html[Manage your NetApp AFF and FAS systems through BlueXP^]

// ONTAPDOC-724, 2022 DEC 06
