---
sidebar: sidebar
permalink: task_nas_provision_linux_nfs.html
keywords: netapp, ontap, provisioning, nas, linux, servers, provision, LIF, network interface
summary: Create volumes to provide storage for Linux servers using the NFS protocol
---

= Provision NAS storage for Linux servers using NFS
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Create volumes to provide storage for Linux servers using the NFS protocol.

This procedure creates new volumes on an link:task_nas_enable_linux_nfs.html[existing NFS-enabled storage VM].

include::_include/98_qos_enabled_by_default.adoc[]

.Steps

. Create a new volume: click *Storage > Volumes* and then click *Add*.
include::_include/98_qos_how_to_modify.adoc[]

.. The default export policy grants full access to all users. You can add more restrictive rules to the export policy later.

. Switch to a Linux system to verify access.

.. Create and mount the volume using the network interface of the storage VM.

.. On the newly mounted volume, create a test file, write text to it, and then delete the file.

After verifying access, you might want to link:task_nas_provision_export_policies.html[restrict client access with the volume’s export policy] and set any desired UNIX ownership and permissions on the mounted volume.
