---
sidebar: sidebar
permalink: task_cp_monitor_cluster_performance_ci.html
keywords: netapp, ontap, cluster, performance, monitor, monitoring, headroom, cpu, cpus, Cloud Insights, troubleshoot, optimize, private data center, Kafka, MongoDB, Nginx, Active IQ Unified Manager, cluster performance, monitor performance
summary: With Cloud Insights, you can monitor, troubleshoot, and optimize all your resources including your public clouds and your private data centers.
---
= Monitor cluster performance with Cloud Insights
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Cloud Insights is a monitoring tool that gives you visibility into your complete infrastructure. With Cloud Insights, you can monitor, troubleshoot, and optimize all your resources including your public clouds and your private data centers.

== Cloud Insights comes in two editions

Cloud Insights Basic Edition is designed specifically to monitor and optimize your NetApp Data Fabric assets. It provides advanced analytics for the connections between all NetApp resources including HCI and All Flash FAS (AFF) within the environment free of charge.

Cloud Insights Standard Edition focuses not only on NetApp Data Fabric-enabled infrastructure components, but also on multi-vendor and multi-cloud environments. With its enriched capabilities, you can access support for over 100 services and resources.

In today’s world, with resources in play from your on-premises data centers to multiple public clouds, it’s crucial to have the complete picture from the application itself to the backend disk of the storage array. The additional support for application monitoring (like Kafka, MongoDB, and Nginx) gives you the information and knowledge you need to operate at the optimal level of utilization as well as with the perfect risk buffer.

Both editions (Basic and Standard) can integrate with NetApp Digital Advisor Unified Manager. Customers who use Digital Advisor Unified Manager can see join information inside the Cloud Insights user interface. Notifications posted on Digital Advisor Unified Manager are not overlooked and can be correlated to events in Cloud Insights. In other words, you get the best of both worlds.

== Monitor, troubleshoot, and optimize all your resources

Cloud Insights helps you significantly reduce the time to resolve issues and prevent them from impacting end users.  It also helps you reduce cloud infrastructure costs.  Your exposure to insider threats is reduced by protecting your data with actionable intelligence.

Cloud Insights gives you visibility to your entire hybrid infrastructure in one place—from the public cloud to your data center.  You can instantly create relevant dashboards that can be customized to your specific needs. You can also create targeted and conditional  alerts that are specific and relevant to your organization’s needs.

Advanced anomaly detection helps you proactively fix issues before they arise.  You can view resource contention and degradation automatically to quickly restore impacted workloads.  Troubleshooting goes more quickly with the automatically built hierarchy of relationships between the different components in your stack.

You can identify unused or abandoned resources across your environment, which helps you discover opportunities to right-size the infrastructure and optimize your entire spend.

Cloud Insights visualizes your system topology to gain an understanding of your Kubernetes architecture. You can monitor the health of your Kubernetes clusters, including which nodes are in trouble, and zoom in when you see a problem.

Cloud Insights helps you protect organizational data from being misused by malicious or compromised users through advanced machine learning and anomaly detection that gives you actionable intelligence on insider threats.

Cloud Insights helps you to visualize Kubernetes metrics so you can fully understand the relations between your pods, nodes, and clusters. You’re able to assess the health of a cluster or a working pod, as well as the load it is currently processing—enabling you to take command of your K8S cluster and to control both the health and the cost of your deployment.

.Related links

* link:https://docs.netapp.com/us-en/ontap/task_cp_monitor_cluster_performance_ci.html[Learn more about Cloud Insights^]
* link:https://docs.netapp.com/us-en/cloudinsights/task_cloud_insights_onboarding_1.html[Get started with Cloud Insights^]

// 2024 Mar 19, Git Issue 1290