---
sidebar: sidebar
permalink: task_nas_provision_linux_nfs.html
keywords: netapp, ontap, provisioning, nas, linux, servers, provision, LIF, network interface
summary: Create volumes to provide storage for Linux servers using the NFS protocol with ONTAP System Manager (9.7 and later)
---

= Provision NAS storage for Linux servers using NFS
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Create volumes to provide storage for Linux servers using the NFS protocol with ONTAP System Manager (9.7 and later).

This procedure creates new volumes on an link:task_nas_enable_linux_nfs.html[existing NFS-enabled storage VM]. You can accept system defaults when configuring volumes or specify custom configurations.

You can create FlexVol volumes, or for large file systems with high performance requirements, you can create FlexGroup volumes.  See also link:task_nas_provision_flexgroup.html[Provision NAS storage for large file systems using FlexGroup volumes].

You can also save the specifications of this volume to an Ansible Playbook. For more details, go to link:task_admin_use_ansible_playbooks_add_edit_volumes_luns.html[Use Ansible Playbooks to add or edit volumes or LUNs].

If you want details about the range of ONTAP NFS protocol capabilities, consult the link:nfs-admin/index.html[NFS reference overview].

.Steps

. Add a new volume in an NFS-enabled storage VM.

.. Click *Storage > Volumes* and then click *Add*.

.. Enter a name, select the storage VM, and enter a size.
+
Only storage VMs configured with the NFS protocol are listed. If only one storage VM configured with the SMB protocol is available, the *Storage VM* field is not shown.
+
*** If you click *Save* at this point, System Manager uses system defaults to create and add a FlexVol volume.
+
NOTE: The default export policy grants full access to all users.

*** You can click *More options* to customize the configuration of the volume to enable services such as authorization, quality of service, and data protection.  Refer to <<Customize the volume configuration>>, then return here to complete the following steps.

. [[step2-complete-prov,Step 2 in the workflow]] On a Linux client, do the following to verify access.

.. Create and mount the volume using the network interface of the storage VM.

.. On the newly mounted volume, create a test file, write text to it, and then delete the file.

+
After verifying access, you can link:task_nas_provision_export_policies.html[restrict client access with the volume's export policy] and set any desired UNIX ownership and permissions on the mounted volume.

== Customize the volume configuration

include::_include/nas_provision_more_options.adoc[]

NOTE: After you save the volume, return to <<step2-complete-prov>> to complete provisioning for Linux servers using NFS.

== Other ways to do this in ONTAP

|===

h| To perform this task with... h| Refer to...

| System Manager Classic (ONTAP 9.7 and earlier) | link:https://docs.netapp.com/us-en/ontap-system-manager-classic/nfs-config/index.html[NFS configuration overview^]
| The ONTAP command line interface (CLI) | link:nfs-config/index.html[NFS configuration overview with the CLI]

|===

// BURT 1395879, 16 JUN 2021
// BURT 1419119, 09 DEC 2021
// BURT 1448684, 10 JAN 2022
