---
sidebar: sidebar
permalink: task_admin_monitor_capacity_in_sm.html
keywords: used storage, local tier capacity, aggregate capacity, add capacity, used capacity, available capacity, total capacity, inactive data, overprovision, overflows, snapshot copy reserves, reserves, clone, maximum capacity limit, storage VM, allocated
summary: "Using System Manager, you can monitor how much storage capacity has been used and how much is still available for a cluster, a local tier, or a storage VM."
---
= Monitor capacity in System Manager
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Using System Manager, you can monitor how much storage capacity has been used and how much is still available for a cluster, a local tier, or a storage VM.

With each version of ONTAP, System Manager provides more robust capacity monitoring information:

* Beginning with ONTAP 9.10.1, System Manager lets you view historical data about the cluster’s capacity and projections about how much capacity will be used or available in the future. You can also monitor the capacity of local tiers and volumes.  

* Beginning with ONTAP 9.12.1, System Manager displays the amount of committed capacity for a local tier.

* Beginning with ONTAP 9.13.1, you can enable a maximum capacity limit for a storage VM and set a threshold to trigger alerts when the used storage reaches a certain percentage of the maximum capacity.

NOTE: Measurements of used capacity are displayed differently depending on your ONTAP version.  Learn more in link:./concepts/capacity-measurements-in-sm-concept.html[Capacity measurements in System Manager].

== View the capacity of a cluster

You can view capacity measurements for a cluster on the Dashboard in System Manager.

.Before you begin

To view data related to the capacity in the cloud, you must have an account with Active IQ Digital Advisor and be connected.

.Steps

. In System Manager, click *Dashboard*. 

. In the *Capacity* section, you can view the following:
+
--
* Total used capacity of the cluster
* Total available capacity of the cluster
* Percentages of used and available capacity.
* Ratio of data reduction.
* Amount of capacity used in the cloud.
* History of capacity usage.
* Projection of capacity usage
--
+
NOTE: In System Manager, capacity representations do not account for root storage tier (aggregate) capacities.

. Click the chart to view more details about the capacity of the cluster.
+
Capacity measurements are shown in two bar charts:
+
--
** The top chart displays the physical capacity:  the size of physical used, reserved, and available space.

** The bottom chart displays the logical capacity:  the size of client data, Snapshot copies, and clones, and the total logical used space.
--
+
Below the bar charts are measurements for data reduction:
+
--
** Data reduction ratio for only the client data (Snapshot copies and clones are not included).

** Overall data reduction ratio.
--

For more information, see link:./concepts/capacity-measurements-in-sm-concept.html[Capacity measurements in System Manager].

== View the capacity of a local tier

You can view details about the capacity of local tiers.  Beginning with ONTAP 9.12.1, the *Capacity* view also includes the amount of committed capacity for a local tier, enabling you to determine whether you need to add capacity to the local tier to accommodate the committed capacity and avoid running out of free space.

.Steps

. Click *Storage > Tiers*.

. Select the name of the local tier.

. On the *Overview* page, in the *Capacity* section, the capacity is show in a bar chart with three measurements:
+
* Used and reserved capacity

* Available capacity

* Committed capacity (beginning with ONTAP 9.12.1)

. Click the chart to view details about the capacity of the local tier.  
+
Capacity measurements are shown in two bar charts:
+
--
* The top bar chart displays physical capacity: the size of physical used, reserved, and available space.
* The bottom bar chart displays logical capacity:  the size of client data, Snapshot copies, and clones, and the total of logical used space.
--
+
Below the bar charts are measurements ratios for data reduction:
+
--
* Data reduction ratio for only the client data (Snapshot copies and clones are not included).
* Overall data reduction ratio. 
--

For more information, see link:./concepts/capacity-measurements-in-sm-concept.html[Capacity measurements in System Manager].

.Optional actions

* If the committed capacity is larger than the capacity of the local tier, you might consider adding capacity to the local tier before it runs out of free space.  See link:./disks-aggregates/add-disks-local-tier-aggr-task.html[Add capacity to a local tier (add disks to an aggregate)].

* You can also view the storage that specific volumes use in the local tier by selecting the *Volumes* tab.

== View the capacity of the volumes in a storage VM
// This heading is linked to directly from System Manager.  Do not alter heading without notifying Eng.

You can view how much storage is used by the volumes in a storage VM and how much capacity is still available.  The total measurement of used and available storage is called "capacity across volumes". 

.Steps

. Select *Storage* > *Storage VMs*.

. Click on the name of the storage VM.

. Scroll to the *Capacity* section, which shows a bar chart with the following measurements:
+
--
** *Physical used*:  Sum of physical used storage across all volumes in this storage VM.
** *Available*:  Sum of available capacity across all volumes in this storage VM.
** *Logical used*:  Sum of logical used storage across all volumes in this storage VM.
--

For more details about the measurements, see link:./concepts/capacity-measurements-in-sm-concept.html[Capacity measurements in System Manager].

[[view-max-cap-limit-svm]]

== View the maximum capacity limit of a storage VM 
// This heading is linked to directly from System Manager.  Do not alter heading without notifying Eng.

Beginning with ONTAP 9.13.1, you can view the maximum capacity limit of a storage VM.  

.Before you begin

You must link:manage-max-cap-limit-svm-in-sm-task.html[enable the maximum capacity limit of a storage VM] before you can view it.

.Steps

. Select *Storage* > *Storage VMs*.
+ 
You can view the maximum capacity measurements in two ways:
+
--
** In the row for the storage VM, view the *Maximum Capacity* column which contains a bar chart that shows the used capacity, available capacity, and maximum capacity.
** Click the name of the storage VM. On the *Overview* tab, scroll to view the maximum capacity, allocated capacity, and capacity alert threshold values in the left column. 
--

.Related information

* link:manage-max-cap-limit-svm-in-sm-task.html#edit-max-cap-limit-svm[Edit the maximum capacity limit of a storage VM]
* link:./concepts/capacity-measurements-in-sm-concept.html[Capacity measurements in System Manager]

// 2021 Mar 31, JIRA IE-230
// 2021 Jun 24, TN-0060
// 2022 Jan 06, JIRA IE-381
// 2022 Oct 04, ONTAPDOC-589
// 2023 FEB 08, ONTAPDOC-742
// 2023 MAY 05, ONTAPDOC-966
