---
sidebar: sidebar
permalink: task_nas_file_system_analytics_view.html
keywords: netapp, ontap, data, file, files, system, analytics, explorer, File System Analytics, File System Analytics Explorer, volume, volumes, ONTAP System Manager, system manager explorer, directory, directories, subdirectory, subdirectories, object, tree, subtree, tree view, history, historical data, active data, inactive data
summary: After enabling File System Analytics, the System Manager Explorer tab shows a default view of the selected volume, displaying the volume’s root directory contents sorted by the space used in each subtree.
---

= View file system activity
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After File System Analytics is enabled, by default, you can view the root directory contents of a selected volume sorted by the spaced used in each subtree

Clicking on any file system object allows you to browse the file system and to display detailed information about each object in a directory. Information about directories can also be displayed graphically. Over time, historical data is displayed for each subtree. Space used is not sorted if there are more than 3000 records.

The file system analytics *Explorer* screen consists of three areas:

*	Tree view of directories and subdirectories; expandable list showing name, size, modify history, and access history.
*	Files; showing name, size, and accessed time for the object selected in the directory list.
*	Active and inactive data comparison for the object selected in the directory list.

Accessed time is shown by default. However, if the volume default has been altered from the CLI, by setting the `-atime-update` option to `false` with the `volume modify` command, only last modified time is shown. For example:

  * The tree view will not display the *access history*.
  * The files view will be altered.
  * The active/inactive data view will be based on modified time (`mtime`).

Using these displays, you can examine the following:

*	File system locations consuming the most space
*	Detailed information about a directory tree, including file and subdirectory count within directories and subdirectories
*	File system locations that contain old data (for example, scratch, temp, or log trees)

Keep the following points in mind when interpreting file system analytics output:

* File system analytics show where and when your data is in use, not how much data is being processed.  For example, large space consumption by recently accessed or modified files does not necessarily indicate high system processing loads.
* The way that the *Volume Explorer* tab calculates space consumption for file system analytics might differ from other tools.  In particular, there could be significant differences compared to the consumption reported in the *Volume Overview* if the volume has storage efficiency features enabled. This is because the *Volume Explorer* tab does not include efficiency savings.


.Steps
. Click *Storage > Volumes*, select the desired volume, then click *Explorer*.

//28Sep2020, BURT 1289113, forry
