---
sidebar: sidebar
permalink: task_san_configure_protection_for_business.html
keywords: netapp, ontap, System Manager, LUNs, source cluster, protect, protection, storage VM, volume, volumes, source, destination, cluster, IOPS activity
summary: Configuring protection for business continuity involves selecting LUNs on the ONTAP source cluster and adding them to a consistency group. Open System Manager from a browser on the source cluster to begin configuring protection for business continuity.
---

= Configure protection for business continuity
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Configuring protection for business continuity involves selecting LUNs on the ONTAP source cluster and adding them to a consistency group. Open System Manager from a browser on the source cluster to begin configuring protection for business continuity.

== About this task

*	LUNs must reside on the same storage VM.
*	LUNs can reside on different volumes.
*	The source and destination cluster cannot be the same.

.Steps
.	Choose the LUNs you want to protect and add them to a protection group: *Protection > Overview > Protect for Business Continuity > Protect LUNs*.
.	Select one or more LUNs to protect on the source cluster.
.	Select the destination cluster and SVM.
.	*Initialize relationship* is selected by default. Click *Save* to begin protection.
.	Go to *Dashboard > Performance* to verify IOPS activity for the LUNs.
.	On the destination cluster, use System Manager to verify that the protection for business continuity relationship is in sync: *Protection > Relationships*.

//2Oct2020, BURT 1318823, lenida
