---
sidebar: sidebar
permalink: task_nas_file_system_analytics_view.html
keywords: netapp, ontap, data, file, files, system, analytics, explorer, File System Analytics, File System Analytics Explorer, volume, volumes, ONTAP System Manager, system manager explorer, directory, directories, subdirectory, subdirectories, object, tree, subtree, tree view, history, historical data, active data, inactive data
summary: After enabling File System Analytics, the System Manager Explorer tab shows a default view of the selected volume, displaying the volume’s root directory contents sorted by the space used in each subtree.
---

= View file system activity
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After enabling File System Analytics, the System Manager *Explorer* tab shows a default view of the selected volume, displaying the volume’s root directory contents sorted by the space used in each subtree.

Clicking on any file system object allows you to browse the file system and to display detailed information about each object in a directory. Information about directories can also be displayed graphically. Over time, historical data is displayed for each subtree. Space used is not sorted if there are more than 3000 records.

The File System Analytics Explorer screen consists of three areas:

*	Tree view of directories and subdirectories; expandable list showing name, size, modify history, and access history.
*	Files; showing name, size, and accessed time for the object selected in the directory list.
*	Active and inactive data comparison for the object selected in the directory list.

NOTE: Accessed time is shown by default. However, if the volume default has been altered from the CLI, by setting the `-atime-update` option to false with the volume modify command, only last modified time is shown. For example:
  * The tree view will not display the *access history*.
  * The files view will be altered.
  * The active/inactive data view will be based on modified time (`mtime`).

Using these displays, you can examine the following:

*	file system locations consuming the most space
*	detailed information about a directory tree, including file and subdirectory count within directories and subdirectories
*	file system locations that contain old data (for example, scratch, temp, or log trees)

Note the following points when interpreting File System Analytics output:

* File System Analytics shows where and when your data are in use, not how much data is being processed.  For example, large space consumption by recently accessed or modified files does not necessarily indicate high system processing loads.
* The way that the Volume Explorer tab calculates space consumption for File System Analytics might differ from other tools.  In particular, there could be significant differences compared to the consumption reported in the Volume Overview if the volume has storage efficiency features enabled. This is because the Explorer tab does not include efficiency savings.


.Steps
. Click *Storage > Volumes*, select the desired volume, then click *Explorer*.

//28Sep2020, BURT 1289113, forry
