---
sidebar: sidebar
permalink: task_nas_provision_nfs_vmware.html
keywords: netapp, ontap, provisioning, nas, vmware, datastores, nfs, provision, using, virtual storage console for vmware vsphere, vsc, esxi, host, vcenter, server
summary: Before using Virtual Storage Console for VMware vSphere (VSC) to provision NFS volumes on an ONTAP based storage system for ESXi hosts, enable NFS using System Manager for ONTAP 9.7 or later.
---

= Provision NFS storage for VMware datastores
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Before using Virtual Storage Console for VMware vSphere (VSC) to provision NFS volumes on an ONTAP based storage system for ESXi hosts, enable NFS using System Manager for ONTAP 9.7 or later.

After creating an link:task_nas_enable_linux_nfs.html[NFS-enabled storage VM] in System Manager, you then provision NFS volumes and manage datastores using VSC.

Beginning with VSC 7.0, VSC is part of the https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html[ONTAP Tools for VMware vSphere virtual appliance^], which includes VSC, vStorage APIs for Storage Awareness (VASA) Provider, and Storage Replication Adapter (SRA) for VMware vSphere capabilities.

Be sure to check the https://imt.netapp.com/matrix/[NetApp Interoperability Matrix^] to confirm compatibility between your current ONTAP and VSC releases.

To set up NFS access for ESXi hosts to datastores using System Manager Classic (for ONTAP 9.7 and earlier releases), see https://docs.netapp.com/us-en/ontap-system-manager-classic/nfs-config-esxi/index.html[NFS configuration for ESXi using VSC overview^]

For more information, see https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html[TR-4597: VMware vSphere for ONTAP^] and the documentation for your VSC release.

// 2022-02-16, BURT 1416400
