---
sidebar: sidebar
permalink: task_metrocluster_switchover_switchback.html
keywords: switchover, switchback, switch over, switch back
summary: You can switchover from one MetroCluster site to the other to perform maintenance or recover from an issue
---

= MetroCluster switchover and switchback
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

You can switchover from one MetroCluster site to the other to perform maintenance or recover from an issue…

.Steps

.	Click *(Return to classic version)*.

.	Click *Configuration > MetroCluster*.
+
System Manager verifies whether a negotiated switchover is possible.

.	Perform one of the following substeps when the validation process has completed:

..	If validation fails, but Site B is up, then an error has occurred, such as a problem with a subsystem or NVram mirroring is not synchronized

...	Fix the issue that is causing the error, click *Close*, and then start again at Step 2.

... Halt the Site B nodes, click *Close*, and then perform the steps in link:https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.onc-sm-help-960%2FGUID-B92E35D8-92E5-4F77-897F-3C0BDC1520C3.html[Performing an unplanned switchover].

..	If validation fails, and Site B is down, then most likely there is a connection problem. Verify that Site B is really down, then perform the steps in link:https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.onc-sm-help-960%2FGUID-B92E35D8-92E5-4F77-897F-3C0BDC1520C3.html[Performing an unplanned switchover].

.	Click *Switchover from Site B to Site A* to initiate the switchover process

.	Click *Switch to the new experience*.
