---
sidebar: sidebar
permalink: task_nas_file_system_analytics_view.html
keywords: explorer, file system analytics, inactive data, capacity analytics, active data, historical data
summary: After enabling File System Analytics, the Explorer screen enables you to view capacity analytics, set inactive data periods, and explore other data about your file systems. 
---

= View file system activity in ONTAP
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After File System Analytics (FSA) is enabled, you can view the root directory contents of a selected volume sorted by the space used in each subtree.

Select any file system object to browse the file system and to display detailed information about each object in a directory. Information about directories can also be displayed graphically. Over time, historical data is displayed for each subtree. Space used is not sorted if there are more than 3000 directories.

== Explorer

The File System Analytics *Explorer* screen consists of three areas:

*	Tree view of directories and subdirectories; expandable list showing name, size, modify history, and access history.
*	Files; showing name, size, and accessed time for the object selected in the directory list.
*	Active and inactive data comparison for the object selected in the directory list.
+
Beginning with ONTAP 9.9.1, you can customize the range to be reported. The default value is one year. Based on these customizations, you can take corrective actions, such as moving volumes and modifying the tiering policy.

Accessed time is shown by default. However, if the volume default has been altered from the CLI (by setting the `-atime-update` option to `false` with the `volume modify` command), then only last modified time is shown. For example:

  * The tree view will not display the *access history*.
  * The files view will be altered.
  * The active/inactive data view will be based on modified time (`mtime`).

Using these displays, you can examine the following:

*	File system locations consuming the most space
*	Detailed information about a directory tree, including file and subdirectory count within directories and subdirectories
*	File system locations that contain old data (for example, scratch, temp, or log trees)

Keep the following points in mind when interpreting FSA output:

* FSA show where and when your data is in use, not how much data is being processed. For example, large space consumption by recently accessed or modified files does not necessarily indicate high system processing loads.
* The way that the *Volume Explorer* tab calculates space consumption for FSA might differ from other tools. In particular, there could be significant differences compared to the consumption reported in the *Volume Overview* if the volume has storage efficiency features enabled. This is because the *Volume Explorer* tab does not include efficiency savings.
* Due to space limitations in the directory display, it is not possible to view a directory depth greater than 8 levels in the _List View_. To view directories more than 8 levels deep, you must switch to _Graphical View_, locate the desired directory, then switch back to _List View_. This will allow additional screen space in the display.

.Steps

. View the root directory contents of a selected volume:
+
[cols="2", options="header"]
|===
|In ONTAP 9.8 and 9.9.1 |Beginning with ONTAP 9.10.1
|Click *Storage > Volumes*, select the desired volume, then click *Explorer*.
|Select *Storage > Volumes*, select the desired volume. From the individual volume menu, select *File System > Explorer*.
|===


// 2025 Jan 21, ONTAPDOC-1070
//2021-04-13, BURT 1382699
//2020-09-28, BURT 1289113
