---
sidebar: sidebar
permalink: task_metrocluster_troubleshooting.html
keywords: system manager, troubleshoot, error, event, problem, metrocluster, maintenance, fix, correction, health, check
summary: You can switchover from one MetroCluster site to the other to perform maintenance or recover from an issue.
---

= Troubleshoot problems with IP MetroCluster configurations
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP 9.8, System Manager monitors the health of IP MetroCluster configurations and helps you identify and correct problems that might occur.


== Overview of the MetroCluster Health Check

System Manager periodically checks the health of your IP MetroCluster configuration.  When you view the MetroCluster section in the Dashboard, usually the message is "MetroCluster systems are healthy."

However, when a problem occurs, the message will show the number of events. You can click on that message and view the results of the health check for the following components:

* Node
* Network Interface
* Tier (Storage)
* Cluster
* Connection
* Volume
* Configuration Replication

The *Status* column identifies which components have problems, and the *Details* column suggests how to correct the problem.

== MetroCluster troubleshooting

.Steps

. In System Manager, select *Dashboard*.

. In the *MetroCluster* section, notice the message.

.. If the message indicates that your MetroCluster configuration is healthy, and the connections between the clusters and the ONTAP Mediator are healthy (shown with check marks), then you have no problems to correct.

.. If the message lists the number of events, or the connections have gone down (shown with an "X"), then continue to the next step.

. Click the message that shows the number of events.
+
The MetroCluster Health Report displays.

. Troubleshoot the problems that appear in the report using the suggestions in the *Details* column.

. When all the problems have been corrected, click *Check MetroCluster Health*.
+
NOTE: The MetroCluster Health Check uses an intensive amount of resources, so it is recommended that you perform all your troubleshooting tasks before running the check.

+
The MetroCluster Health Check runs in the background.  You can work on other tasks while you wait for it to finish.
// 07 OCT 2020, BURT 1323833 new topic for 9.8
// 23 OCT 2020, review comment:  Applies only to IP sites
// 09 DEC 2021, BURT 1430515
