---
sidebar: sidebar
permalink: task_object_provision_enable_s3_server.html
keywords: netapp, ontap, System Manager, S3, S3 server, storage VM, storage VMs, S3 client, client, clients, server, certificate, network, protocol, protocol servers, configure protocols, Fully Qualified Domain Name, FQDN, client, client access, network, network interface, network interfaces, DNS
summary: Add a storage VM with an S3 server for serving content to S3 clients.
---

= Enable an S3 server on a storage
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Add a storage VM with an S3 server for serving content to S3 clients.

Although an S3 server can coexist in a storage VM with other protocol servers, it is a best practice to create a dedicated storage VM for the S3 object store.

You should be prepared to enter an S3 server name (FQDN) and IP addresses for interface role Data. If you are using an external-CA signed certificate, you will be prompted to enter it during this procedure; you also have the option to use a system-generated certificate.

.Steps
.	Enable S3 on a new storage VM.
..	Add a new storage VM: click *Storage > Storage VMs*, then click *Add*.
If this is a new system with no existing storage VMs: click *Dashboard > Configure Protocols*.
..	Click *Enable S3*, then enter the S3 Server Name.
This will be the Fully Qualified Domain Name (FQDN) that clients will use.
..	Select the certificate type.
Whether you select system-generated certificate or one of your own, it will be required for client access.
..	Enter the network interfaces.
.	If you selected the system-generated certificate, you see the certificate information when the new storage VM creation is confirmed. Click *Download* and save it for client access.
+
* The secret key will not be displayed again.
* If you need the certificate information again: click *Storage > Storage VMs*, select the storage VM, and click *Settings*.

If this is a new SVM, you should also configure DNS for host-name resolution.

//09Oct2020, BURT 1290604, forry
