---
sidebar: sidebar
permalink: task_nas_provision_windows_smb.html
keywords: netapp, ontap, provisioning, nas, windows, servers, provision, smb, cifs
summary: create volumes to provide storage for windows servers using the smb/cifs protocol
---

= Provision NAS storage for Windows servers using SMB/CIFS
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Create volumes to provide storage for Windows servers using the SMB/CIFS protocol.

This procedure creates new volumes on an _existing SMB-enabled storage VM_.
//add link above when file is created

.Steps

. Create a new volume: click *Storage > Volumes* and then click *Add*.

** The default share grants full access to all users. You can modify the Access Control List (ACL) later.

. Switch to a Windows client to verify that the share is accessible.

.. In Windows Explorer, map a drive to the share in the following format: \\_SMB_Server_Name_\_Share_Name_

.. On the newly created drive, create a test file, write text to it, and then delete the file.

After verifying access, you might want to link:task_nas_provision_export_policies.html[restrict client access with the share ACL] and set any desired security properties on the mapped drive.
