---
sidebar: sidebar
permalink: task_admin_monitor_risks.html
keywords: system manager, monitor, risk, risks, suggestion, suggestions, mitigate, active iq, category, categories, mitigation, impact, impacts, corrections, corrective action, corrective actions, acknowledge risk, dismiss, undismiss, restore, unacknowledge
summary: "Using System Manager with ONTAP 9.10.0 or later, you can monitor the risks reported by Digital Advisor."
---

= Monitor risks
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP 9.10.0, you can use System Manager to monitor the risks reported by Digital Advisor.  Beginning with ONTAP 9.10.1, you can use System Manager to also acknowledge the risks.

NetApp Digital Advisor reports opportunities to reduce risk and improve the performance and efficiency of your storage environment. With System Manager, you can learn about risks reported by Digital Advisor and receive actionable intelligence that helps you administer storage and achieve higher availability, improved security, and better storage performance.

[[link_active_iq]]
== Link to your Digital Advisor account

To receive information about risks from Digital Advisor, you should first link to your Digital Advisor account from System Manager.

.Steps

. In System Manager, click *Cluster > Settings*.
. Under *Digital Advisor Registration*, click *Register*.
. Enter your credentials for Digital Advisor.
. After your credentials are authenticated, click *Confirm to link Digital Advisor with System Manager*.

== View the number of risks

Beginning with ONTAP 9.10.0, you can view from the dashboard in System Manager the number of risks reported by Digital Advisor.

.Before you begin

You must establish a connection from System Manager to your Digital Advisor account.  Refer to <<link_active_iq,Link to your Digital Advisor account>>.

.Steps

. In System Manager, click *Dashboard*.
. In the *Health* section, view the number of reported risks.
+
NOTE: You can view more detailed information about each risk by clicking the message showing the number of risks.  See <<view_risk_details,View details of risks>>.

[[view_risk_details]]
== View details of risks

Beginning with ONTAP 9.10.0, you can view from System Manager how the risks reported by Digital Advisor are categorized by impact areas.  You can also view detailed information about each reported risk, its potential impact on your system, and corrective actions you can take.

.Before you begin

You must establish a connection from System Manager to your Digital Advisor account. Refer to <<link_active_iq,Link to your Digital Advisor account>>.

.Steps

. Click *Events > All Events*.
. In the *Overview* section, under *Digital Advisor Suggestions*, view the number of risks in each impact area category. The risk categories include:
+
* Performance & efficiency
* Availability & protection
* Capacity
* Configuration
* Security

. Click on the *Digital Advisor Suggestions* tab to view information about each risk, including the following:
+
* Level of impact to your System
* Category of the risk
* Nodes that are affected
* Type of mitigation needed
* Corrective actions you can take

== Acknowledge risks

Beginning with ONTAP 9.10.1, you can use System Manager to acknowledge any of the open risks.

.Steps

. In System Manager, display the list of risks by performing the procedure in <<view_risk_details,View details of risks>>.

. Click on the risk name of an open risk that you want to acknowledge.

. Enter information into the following fields:
+
* Reminder (date)
* Justification
* Comments

. Click *Acknowledge*.
+
NOTE: After you acknowledge a risk, it takes a few minutes for the change to be reflected in the list of Digital Advisor suggestions.

== Unacknowledge risks

Beginning with ONTAP 9.10.1, you can use System Manager to unacknowledge any risk that was previously acknowledged.

.Steps

. In System Manager, display the list of risks by performing the procedure in <<view_risk_details,View details of risks>>.

. Click on the risk name of an acknowledged risk that you want to unacknowledge.

. Enter information into the following fields:
+
* Justification
* Comments

. Click *Unacknowledge*.
+
NOTE: After you unacknowledge a risk, it takes a few minutes for the change to be reflected in the list of Digital Advisor suggestions.

// 04 AUG 2021, JIRA IE-384
// 01 NOV 2021, JIRA IE-381
