---
sidebar: sidebar
permalink: task_admin_troubleshoot_hardware_problems.html
keywords: netapp, ontap, troubleshoot, hardware, controller, fan, switch, system, problems, errors, issues, card, high temperature, heat, port, FRU
summary: You can view the configuration of nodes, disk shelves, and storage switches on your network and troubleshoot problems that might arise.
---

= Troubleshoot hardware problems
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
With ONTAP 9.8 and later, you can use System Manager to view the configuration of AFF hardware on your network and troubleshoot problems that might arise.

//BURT 1346974, 09 OCT 2020, thomi, new topic for 9.8
The  hardware visualization feature enables users to quickly visualize hardware status and any potential connection issues.

video::Jdf5dxSQsDY[youtube, width=848, height=480]

.Before you Start

For ONTAP 9.8, System Manager provides a _preview_ of the capability to view AFF hardware configurations.  Starting with ONTAP 9.9.1, you can view all AFF hardware configurations.

.Steps

To view AFF hardware configurations, perform the following steps:

. In System Manager, select *Cluster > Hardware*.

. Hover your mouse over components to view status and other details.
+
You can view various types of information:

* <<Information about controllers>>
* <<Information about disk shelves>>
* <<Information about storage switches>>

== Information about controllers

You can view the following:

*Nodes*:

* Rear views are displayed.
* Models with an internal disk shelf also show the disk layout in the front view.
* You can view the following platform models:
+
[cols="35,65"]
|===
|If your system is running...|Then you can view...

|ONTAP 9.8
|C190, A220, A300, A400, and A700

|ONTAP 9.9.1
|C190, A220, A250, A300, A320, A400, A700, A700s, A800, FAS500f
|===

*Ports*:

* Console ports are not shown.
* A port is red if it is down.
* The status of a port and other details are shown when you hover over the port.

*FRUs*:

Information about FRUs appears only when the state of a FRU is non-optimal.

* Failed PSUs in nodes or chassis.
* High temperatures detected in nodes.
* Failed fans on the nodes or chassis.

*Adapter cards*:

* Cards with defined part number fields are shown in the slots if external cards has been inserted.
* Ports on cards are shown.
* Certain cards are shown with specific images of the cards.  If the card is not in the list of supported part numbers, then a generic graphic is displayed.

== Information about disk shelves

You can view the following:

*Disk shelves*:

* Front and rear views are displayed.
* You can view the following disk shelf models:
+
[cols="35,65"]
|===
|If your system is running...|Then you can view...

|ONTAP 9.8
|DS4243, DS4486, DS212C, DS2245, DS224C, and NS224

|ONTAP 9.9.1
|All supported disk shelf models
|===

*Shelf ports*:

* Port status is displayed.
* Remote port information is shown if the port is connected.

*Shelf FRUs*:

* PSU failure information is shown.

== Information about storage switches

* The display shows switches that act as storage switches used to connect shelves to nodes.
* Starting with 9.9.1, System Manager displays information about a switch that acts as both a storage switch and a cluster, which can also be shared between nodes of an HA pair.
* You can view the following storage switch models:
+
[cols="35,65"]
|===
|If your system is running... |Then you can view...

|ONTAP 9.8
|X190100 (Cisco Nexus 3232)

|ONTAP 9.9.1
|X190100 (Cisco Nexus 3232)
N9K-C9336C-FX2
|===

* You can view the following:

** *Storage switch* information includes switch name, IP address, serial number, SNMP version, and system version.

** *Storage switch port* information includes identity name, identity index, state, and other details, including remote connection.

// BURT 1346974, 09 OCT 2020, thomi, new topic for 9.8
// JIRA IE-236, 30 MAR 2021, thomi, added content for 9.9.1
// JIRA IE-237, 31 MAR 2021, thomi, updated topic for 9.9.1
