---
sidebar: sidebar
permalink: task_nas_provision_flexgroup.html
keywords: netapp, ontap, provision, provisioning, nas, large file systems, using, FlexGroup, windows, servers, cifs, smb, FlexVol volume limits, load distribution, work load, workload, balancing, data
summary: A FlexGroup volume is a scalable NAS container that provides high performance along with automatic load distribution. FlexGroup volumes provide massive capacity (in petabytes), which considerably exceeds the FlexVol volume limits, without adding  any management overhead.
---

= Provision NAS storage for large file systems using FlexGroup volumes
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
A FlexGroup volume is a scalable NAS container that provides high performance along with automatic load distribution. FlexGroup volumes provide massive capacity (in petabytes), which considerably exceeds the FlexVol volume limits, without adding  any management overhead.

The topics in this section show you how to manage FlexGroup volumes with System Manager in ONTAP 9.7 and later releases. If you are using the classic System Manager (available only in ONTAP 9.7 and earlier), see this topic:

* https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_creating_flexgroup_volumes.html[Create FlexGroup volumes^]

Beginning with ONTAP 9.9.1, SnapMirror fanout relationships of two or more FlexGroup volumes are supported, with a maximum of eight fanout legs. System Manager does not support SnapMirror cascading FlexGroup volume relationships.

ONTAP automatically selects the local tiers required for creating the FlexGroup volume.

include::_include/98_qos_enabled_by_default.adoc[]

.Steps

. Click *Storage > Volumes*.
. Click *Add*.
. Click *More Options* and then select *Distribute volume data across the cluster*.
+
include::_include/98_qos_how_to_modify.adoc[]

== Videos

=== Create and manage a FlexGroup volume

video::gB-yF1UTv2I[youtube, width=848, height=480]

== FlexGroup volumes - Do more with less

video::0B4nlChf0b4[youtube, width=848, height=480]

// 11 APR 2024, minor edit to include format
// 12 APR 2021, JIRA IE-242
// 07 DEC 2021, BURT 1430515
