---
sidebar: sidebar
permalink: task_dp_configure_storage_vm_dr.html
keywords: netapp, ontap, system manager, VM, storage, destination, source, source storage VM, disaster, protection, protection relationship, relationship, relationships, recovery
summary: Using System Manager, you can create an storage VM disaster recovery relationship to replicate one storage VM configuration to another. In the event of a disaster at the primary site, you can quickly activate the destination storage VM.
---

= Configure storage VM disaster recovery
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Using System Manager, you can create an storage VM disaster recovery (storage VM DR) relationship to replicate one storage VM configuration to another. In the event of a disaster at the primary site, you can quickly activate the destination storage VM.

Complete this procedure from the destination. If you need to create a new protection policy, for instance, when your source storage VM has SMB configured, you should use System Manager to create the policy and select the *Copy source storage VM configuration* option in the *Add Protection Policy* window.
For details see link:task_dp_create_custom_data_protection_policies.html#[Create custom data protection policies].

.Steps

. On the destination cluster, click *Protection > Relationships*.

. Under *Relationships*, click Protect and choose *Storage VMs (DR)*.

. Select a protection policy. If you created a custom protection policy, select it, then choose the source cluster and storage VM you want to replicate. You can also create a new destination storage VM by entering a new storage VM name.

. Click *Save*.

// 01 APR 2021, BURT 1381353
// 09 APR 2021, added link to Create custom policies topic and changed step 3 to specify new destination SVM
// 07 DEC 2021, BURT 1430515
// 4 FEB 2022, 1451789 