---
sidebar: sidebar
permalink: task_nas_provision_windows_smb.html
keywords: netapp, ontap, provisioning, nas, windows, servers, provision, smb, cifs, SMB, share name
summary: Create volumes to provide storage for Windows servers using the SMB protocol.
---

= Provision NAS storage for Windows servers using SMB
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Create volumes to provide storage for Windows servers using the SMB protocol.

This procedure creates new volumes on an link:task_nas_enable_windows_smb.html[existing SMB-enabled storage VM]. You can accept systems defaults when configuring volumes or specify custom configurations.

You can create FlexVol volumes, or for large file systems with high performance requirements, you can create FlexGroup volumes.  See also link:task_nas_provision_flexgroup.html[Provision NAS storage for large file systems using FlexGroup volumes].

You can also save the specifications of this volume to an Ansible Playbook. For more details, go to link:task_admin_use_ansible_playbooks_add_edit_volumes_luns.html[Use Ansible Playbooks to add or edit volumes or LUNs].

.Steps

. Add a new volume in an SMB-enabled storage VM.

.. Click *Storage > Volumes* and then click *Add*.

.. Enter a name, select the storage VM, and enter a size.
+
Only storage VMs configured with the SMB protocol are listed. If only one storage VM configured with the SMB protocol is available, the *Storage VM* field is not shown.
+
*** If you click *Save* at this point, System Manager uses system defaults to create and add a FlexVol volume.

*** You can click *More options* to customize the configuration of the volume to enable services such as authorization, quality of service, and data protection.  Refer to <<Customize the volume configuration>>, then return here to complete the following steps.

. [[step2,Step 2 in the workflow]] Switch to a Windows client to verify that the share is accessible.

.. In Windows Explorer, map a drive to the share in the following format: `+\\_SMB_Server_Name__Share_Name_+`

.. On the newly created drive, create a test file, write text to it, and then delete the file.

After verifying access, you can link:task_nas_provision_export_policies.html[restrict client access with the share ACL] and set any desired security properties on the mapped drive.

== Customize the volume configuration

include::_include/nas_provision_more_options.adoc[]

NOTE: After you save the volume, return to <<step2>> to complete provisioning for Windows servers using SMB.

// 16 JUN 2021, BURT 1395879
