---
permalink: element-replication/create-relationship-element-destination-task.html
sidebar: sidebar
keywords: create, relationship, ontap, source, element, destination, snapshot, snap shot, lun, migrate, data, snap mirror, snapmirror, replicate, replication
summary: "Beginning with ONTAP 9.4, you can use SnapMirror to replicate Snapshot copies of a LUN created on an ONTAP source back to an Element destination. You might be using the LUN to migrate data from ONTAP to Element software."
---
= Create a relationship from an ONTAP source to an Element destination
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.4, you can use SnapMirror to replicate Snapshot copies of a LUN created on an ONTAP source back to an Element destination. You might be using the LUN to migrate data from ONTAP to Element software.

.Before you begin

* The Element destination node must have been made accessible to ONTAP.
* The Element volume must have been enabled for SnapMirror replication.

.About this task

You must specify the Element destination path in the form `<hostip:>/lun/<name>`, where "`lun`" is the actual string "`lun`" and `name` is the name of the Element volume.

Replication rules are as follows:

* The replication relationship must have a policy of type "`async-mirror`".
+
You can use a default or custom policy.

* Only iSCSI LUNs are supported.
* You cannot replicate more than one LUN from an ONTAP volume to an Element volume.
* You cannot replicate a LUN from an ONTAP volume to multiple Element volumes.

.Step

. Create a replication relationship from an ONTAP source to an Element destination:
+
`snapmirror create -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -type XDP -schedule schedule -policy <policy>`
+
For complete command syntax, see the man page.
+
The following example creates a SnapMirror DR relationship using the default `MirrorLatest` policy:
+
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy MirrorLatest
----
+
The following example creates a SnapMirror DR relationship using the custom `my_mirror` policy:
+
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy my_mirror
----

.After you finish

Use the `snapmirror show` command to verify that the SnapMirror relationship was created. For complete command syntax, see the man page.

// 08 DEC 2021, BURT 1430515
