---
permalink: element-replication/create-custom-replication-policy-concept.html
sidebar: sidebar
keywords: create, custom, replication, policy, policies, relationship, compress data, snapmirror, snap mirror, snapshot
summary: "You can create a custom replication policy if the default policy for a relationship is not suitable. You might want to compress data in a network transfer, for example, or modify the number of attempts SnapMirror makes to transfer Snapshot copies."
---
= Create a custom replication policy
:icons: font
:imagesdir: ../media/

[.lead]

You can use a default or custom policy when you create a replication relationship. For a custom unified replication policy, you must define one or more _rules_ that determine which Snapshot copies are transferred during initialization and update.

You can create a custom replication policy if the default policy for a relationship is not suitable. You might want to compress data in a network transfer, for example, or modify the number of attempts SnapMirror makes to transfer Snapshot copies.

.About this task

The _policy type_ of the replication policy determines the type of relationship it supports. The table below shows the available policy types.

[cols="2*"]
|===

h| Policy type h| Relationship type

a|
async-mirror
a|
SnapMirror DR
a|
mirror-vault
a|
Unified replication
|===

.Step

. Create a custom replication policy:
+
`snapmirror policy create -vserver _SVM_ -policy policy -type async-mirror|mirror-vault -comment _comment_ -tries _transfer_tries_ -transfer-priority low|normal -is-network-compression-enabled true|false`
+
For complete command syntax, see the man page.
+
Beginning with ONTAP 9.5, you can specify the schedule for creating a common Snapshot copy schedule for SnapMirror synchronous relationships by using the `-common-snapshot-schedule` parameter. By default, the common Snapshot copy schedule for SnapMirror synchronous relationships is one hour. You can specify a value from 30 minutes to two hours for the Snapshot copy schedule for SnapMirror synchronous relationships.
+
The following example creates a custom replication policy for SnapMirror DR that enables network compression for data transfers:
+
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy DR_compressed -type async-mirror -comment “DR with network compression enabled” -is-network-compression-enabled true
----
+
The following example creates a custom replication policy for unified replication:
+
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_unified -type mirror-vault
----

.After you finish

For "`mirror-vault`" policy types, you must define rules that determine which Snapshot copies are transferred during initialization and update.

Use the `snapmirror policy show` command to verify that the SnapMirror policy was created. For complete command syntax, see the man page.

// 2024-Aug-30, ONTAPDOC-2346
// 08 DEC 2021, BURT 1430515
