---
permalink: element-replication/index.html
sidebar: sidebar
keywords: decide, replication, netapp element software, ontap, business continuity, element, system, snapmirror, replicate, snapshot, copies, volume
summary: "You can ensure business continuity on an Element system by using SnapMirror to replicate Snapshot copies of an Element volume to an ONTAP destination."
---
= Replication between NetApp Element software and ONTAP overview
:icons: font
:imagesdir: ../media/

[.lead]
You can ensure business continuity on an Element system by using SnapMirror to replicate Snapshot copies of an Element volume to an ONTAP destination. In the event of a disaster at the Element site, you can serve data to clients from the ONTAP system, and then reactivate the Element system when service is restored.

Beginning with ONTAP 9.4, you can replicate Snapshot copies of a LUN created on an ONTAP node back to an Element system. You might have created a LUN during an outage at the Element site, or you might be using a LUN to migrate data from ONTAP to Element software.

You should work with Element to ONTAP backup if the following apply:

* You want to use best practices, not explore every available option.
* You want to use the ONTAP command-line interface (CLI), not System Manager or an automated scripting tool.
* You are using iSCSI to serve data to clients.

link:https://docs.netapp.com/us-en/element-software/storage/element-replication-index.html[Configure replication of NetApp Element software and ONTAP^].

// 2024 AUG 30, ONTAPDOC-1436