---
permalink: tape-backup/access-event-log-files-backup-restore-operations-task.html
sidebar: sidebar
keywords: access, event, log, files, rdfile, nodeshell, tap, backup, monitor, restore, operations
summary: "You can access the event log files for tape backup and restore operations in the /etc/log/ directory by using the rdfile command at the nodeshell. You can view these event log files to monitor tape backup and restore operations."
---
= Access the event log files
:icons: font
:imagesdir: ../media/

[.lead]
You can access the event log files for tape backup and restore operations in the `/etc/log/` directory by using the `rdfile` command at the nodeshell. You can view these event log files to monitor tape backup and restore operations.

.About this task

With additional configurations, such as an access-control role with access to the `spi` web service or a user account set up with the `http` access method, you can also use a web browser to access these log files.

.Steps

. To access the nodeshell, enter the following command:
+
`*node run -node _node_name_*`
+
`node_name` is the name of the node.

. To access the event log files for tape backup and restore operations, enter the following command:
+
`*rdfile /etc/log/backup*`

.Related information

link:../system-admin/index.html[System administration]
