---
permalink: tape-backup/before-restoring-data-concept.html
sidebar: sidebar
keywords: considerations, restore, file, data, original, path, destination, operation, required, space
summary: "You can restore backed-up data to its original path or to a different destination. If you are restoring backed-up data to a different destination, you must prepare the destination for the restore operation."
---
= Considerations before restoring data with ONTAP NDMP
:icons: font
:imagesdir: ../media/

[.lead]
You can restore backed-up data to its original path or to a different destination. If you are restoring backed-up data to a different destination, you must prepare the destination for the restore operation.

Before restoring data either to its original path or to a different destination, you must have the following information and meet the following requirements:

* The level of the restore
* The path to which you are restoring the data
* The blocking factor used during the backup
* If you are doing an incremental restore, all tapes must be in the backup chain
* A tape drive that is available and compatible with the tape to be restored from

Before restoring data to a different destination, you must perform the following operations:

* If you are restoring a volume, you must create a new volume.
* If you are restoring a qtree or a directory, you must rename or move files that are likely to have the same names as files you are restoring.

[NOTE]
====
In ONTAP 9, qtree names support the Unicode format. The earlier releases of ONTAP do not support this format. If a qtree with Unicode names in ONTAP 9 is copied to an earlier release of ONTAP using the `ndmpcopy` command or through restoration from a backup image in a tape, the qtree is restored as a regular directory and not as a qtree with Unicode format.
====

[NOTE]
====
If a restored file has the same name as an existing file, the existing file is overwritten by the restored file. However, the directories are not overwritten.
====

To rename a file, directory, or qtree during restore without using DAR, you must set the EXTRACT environment variable to `E`.

== Required space on the destination storage system

You require about 100 MB more space on the destination storage system than the amount of data to be restored.

[NOTE]
====
The restore operation checks for volume space and inode availability on the destination volume when the restore operation starts. Setting the FORCE environment variable to `Y` causes the restore operation to skip the checks for volume space and inode availability on the destination path. If there is not enough volume space or inodes available on the destination volume, the restore operation recovers as much data allowed by the destination volume space and inode availability. The restore operation stops when there is no more volume space or inodes left.
====
