---
permalink: tape-backup/data-backup-dump-concept.html
sidebar: sidebar
keywords: dump, engine, flexvol, volumes, backup, recovery, snapshot, copy, tape, device
summary: "Dump is a snapshot based backup and recovery solution from ONTAP that helps you to back up files and directories from a snapshot to a tape device and restore the backed up data to a storage system."
---
= About dump engine for FlexVol volumes
:icons: font
:imagesdir: ../media/

[.lead]
Dump is a snapshot based backup and recovery solution from ONTAP that helps you to back up files and directories from a snapshot to a tape device and restore the backed up data to a storage system.

You can back up your file system data, such as directories, files, and their associated security settings, to a tape device by using the dump backup. You can back up an entire volume, an entire qtree, or a subtree that is neither an entire volume nor an entire qtree.

You can perform a dump backup or restore by using NDMP-compliant backup applications.

When you perform a dump backup, you can specify the snapshot to be used for a backup. If you do not specify a snapshot for the backup, the dump engine creates a snapshot for the backup. After the backup operation is completed, the dump engine deletes this snapshot.

You can perform level-0, incremental, or differential backups to tape by using the dump engine.

[NOTE]
====
After reverting to a release earlier than Data ONTAP 8.3, you must perform a baseline backup operation before performing an incremental backup operation.
====

.Related information

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ug-rdg/home.html[Upgrade, revert, or downgrade]
