---
permalink: tape-backup/dump-storage-failover-arl-operations-concept.html
sidebar: sidebar
keywords: dump, workd, storage, failover, arl, operations, override, aggregate, relocation, takeover, giveback, cab, extension
summary: "Before you perform dump backup or restore operations, you should understand how these operations work with storage failover (takeover and giveback) or aggregate relocation (ARL) operations. The -override-vetoes option determines the behavior of dump engine during a storage failover or ARL operation."
---
= How dump works with storage failover and ARL operations
:icons: font
:imagesdir: ../media/

[.lead]
Before you perform dump backup or restore operations, you should understand how these operations work with storage failover (takeover and giveback) or aggregate relocation (ARL) operations. The `-override-vetoes` option determines the behavior of dump engine during a storage failover or ARL operation.

When a dump backup or restore operation is running and the `-override-vetoes` option is set to `false`, a user-initiated storage failover or ARL operation is stopped. However, if the `–override-vetoes` option is set to `true`, then the storage failover or ARL operation is continued and the dump backup or restore operation is aborted. When a storage failover or ARL operation is automatically initiated by the storage system, an active dump backup or restore operation is always aborted. You cannot restart dump backup and restore operations even after storage failover or ARL operations complete.

== Dump operations when CAB extension is supported

If the backup application supports CAB extension, you can continue performing incremental dump backup and restore operations without reconfiguring backup policies after a storage failover or ARL operation.

== Dump operations when CAB extension is not supported

If the backup application does not support CAB extension, you can continue performing incremental dump backup and restore operations if you migrate the LIF configured in the backup policy to the node that hosts the destination aggregate. Otherwise, after the storage failover and ARL operation, you must perform a baseline backup prior to performing the incremental backup operation.

[NOTE]
====
For storage failover operations, the LIF configured in the backup policy must be migrated to the partner node.
====

.Related information

https://docs.netapp.com/us-en/ontap/high-availability/index.html[High Availability]
