---
permalink: tape-backup/dump-backup-restore-operations-mcc-config-concept.html
sidebar: sidebar
keywords: dump, backup, restore, opartion, metrocluster, configuration, switchback, switchover
summary: "Before you perform dump backup and restore operations in a MetroCluster configuration, you must understand how dump operations are affected when a switchover or switchback operation occurs."
---
= How dump backup and restore operations are affected in an ONTAP MetroCluster configurations
:icons: font
:imagesdir: ../media/

[.lead]
Before you perform dump backup and restore operations in a MetroCluster configuration, you must understand how dump operations are affected when a switchover or switchback operation occurs.

== Dump backup or restore operation followed by switchover

Consider two clusters: cluster 1 and cluster 2. During a dump backup or restore operation on cluster 1, if a switchover is initiated from cluster 1 to cluster 2, then the following occurs:

* If the value of the `override-vetoes` option is `false`, then the switchover is aborted and the backup or restore operation continues.
* If the value of the option is `true`, then the dump backup or restore operation is aborted and the switchover continues.

== Dump backup or restore operation followed by switchback

A switchover is performed from cluster 1 to cluster 2 and a dump backup or restore operation is initiated on cluster 2. The dump operation backs up or restores a volume that is located on cluster 2. At this point, if a switchback is initiated from cluster 2 to cluster 1, then the following occurs:

* If the value of the `override-vetoes` option is `false`, then the switchback is cancelled and the backup or restore operation continues.
* If the value of the option is `true`, then the backup or restore operation is aborted and the switchback continues.

== Dump backup or restore operation initiated during a switchover or switchback

During a switchover from cluster 1 to cluster 2, if a dump backup or restore operation is initiated on cluster 1, then the backup or restore operation fails and the switchover continues.

During a switchback from cluster 2 to cluster 1, if a dump backup or restore operation is initiated from cluster 2, then the backup or restore operation fails and the switchback continues.
