---
permalink: tape-backup/dump-restore-event-log-message-format-concept.html
sidebar: sidebar
keywords: event, dump, restore, log, message,
summary: "For each dump and restore event, a message is written to the backup log file."
---
= ONTAP dump and restore event log message format 
:icons: font
:imagesdir: ../media/

[.lead]
For each dump and restore event, a message is written to the backup log file.

The format of the dump and restore event log message is as follows:

`_type timestamp identifier event (event_info)_`

The following list describes the fields in the event log message format:

* Each log message begins with one of the type indicators described in the following table:
+
[options="header"]
|===
| Type| Description
a|
log
a|
Logging event
a|
dmp
a|
Dump event
a|
rst
a|
Restore event
|===

* `timestamp` shows the date and time of the event.
* The `identifier` field for a dump event includes the dump path and the unique ID for the dump. The `identifier` field for a restore event uses only the restore destination path name as a unique identifier. Logging-related event messages do not include an `identifier` field.

== Learn about ONTAP logging events
The event field of a message that begins with a log specifies the beginning of a logging or the end of a logging.

It contains one of the events shown in the following table:

[options="header"]
|===
| Event| Description
a|
Start_Logging
a|
Indicates the beginning of logging or that logging has been turned back on after being disabled.
a|
Stop_Logging
a|
Indicates that logging has been turned off.
|===

== Learn about ONTAP dump events
The event field for a dump event contains an event type followed by event-specific information within parentheses.

The following table describes the events, their descriptions, and the related event information that might be recorded for a dump operation:

[options="header"]
|===
| Event| Description| Event information
a|
Start
a|
NDMP dump is started
a|
Dump level and the type of dump
a|
End
a|
Dumps completed successfully
a|
Amount of data processed
a|
Abort
a|
The operation is cancelled
a|
Amount of data processed
a|
Options
a|
Specified options are listed
a|
All options and their associated values, including NDMP options
a|
Tape_open
a|
The tape is open for read/write
a|
The new tape device name
a|
Tape_close
a|
The tape is closed for read/write
a|
The tape device name
a|
Phase-change
a|
A dump is entering a new processing phase
a|
The new phase name
a|
Error
a|
A dump has encountered an unexpected event
a|
Error message
a|
Snapshot
a|
A snapshot is created or located
a|
The name and time of the snapshot
a|
Base_dump
a|
A base dump entry in the internal metafile has been located
a|
The level and time of the base dump (for incremental dumps only)
|===

== Learn about ONTAP restore events
The event field for a restore event contains an event type followed by event-specific information in parentheses.

The following table provides information about the events, their descriptions, and the related event information that can be recorded for a restore operation:

[options="header"]
|===
| Event| Description| Event information
a|
Start
a|
NDMP restore is started
a|
Restore level and the type of restore
a|
End
a|
Restores completed successfully
a|
Number of files and amount of data processed
a|
Abort
a|
The operation is cancelled
a|
Number of files and amount of data processed
a|
Options
a|
Specified options are listed
a|
All options and their associated values, including NDMP options
a|
Tape_open
a|
The tape is open for read/write
a|
The new tape device name
a|
Tape_close
a|
The tape is closed for read/write
a|
The tape device name
a|
Phase-change
a|
Restore is entering a new processing phase
a|
The new phase name
a|
Error
a|
Restore encounters an unexpected event
a|
Error message
|===
