---
permalink: tape-backup/event-logging-concept.html
sidebar: sidebar
keywords: monitor, tape, backup, restore, operations, flexvol, volumes
summary: "You can view the event log files to monitor the tape backup and restore operations. ONTAP automatically logs significant backup and restore events and the time at which they occur in a log file named backup in the controller’s /etc/log/ directory. By default, event logging is set to on."
---
= Monitor ONTAP tape backup and restore operations for FlexVol volumes
:icons: font
:imagesdir: ../media/

[.lead]
You can view the event log files to monitor the tape backup and restore operations. ONTAP automatically logs significant backup and restore events and the time at which they occur in a log file named `backup` in the controller's `/etc/log/` directory. By default, event logging is set to `on`.

You might want to view event log files for the following reasons:

* Checking whether a nightly backup was successful
* Gathering statistics on backup operations
* For using the information in past event log files to help diagnose problems with backup and restore operations

Once every week, the event log files are rotated. The `/etc/log/backup` file is renamed to `/etc/log/backup.0`, the `/etc/log/backup.0` file is renamed to `/etc/log/backup.1`, and so on. The system saves the log files for up to six weeks; therefore, you can have up to seven message files (`/etc/log/backup.[0-5]` and the current `/etc/log/backup` file).
