---
permalink: tape-backup/index.html
sidebar: sidebar
keywords: tape, backup, flexvol, volumes, overview, ndmp, network, data, management, protocol, sump, smtape
summary: "ONTAP supports tape backup and restore through Network Data Management Protocol."
---
= Tape backup of FlexVol volumes overview
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP supports tape backup and restore through Network Data Management Protocol (NDMP). NDMP allows you to back up data in storage systems directly to tape, resulting in efficient use of network bandwidth. ONTAP supports both dump and SMTape engines for tape backup.

You can perform a dump or SMTape backup or restore by using NDMP-compliant backup applications. Only NDMP version 4 is supported.

== Tape backup using dump

Dump is a snapshot based backup in which your file system data is backed up to tape. The ONTAP dump engine backs up files, directories, and the applicable access control list (ACL) information to tape. You can back up an entire volume, an entire qtree, or a subtree that is not an entire volume or an entire qtree. Dump supports baseline, differential, and incremental backups.

== Tape backup using SMTape

SMTape is a snapshot based disaster recovery solution from ONTAP that backs up blocks of data to tape. You can use SMTape to perform volume backups to tapes. However, you cannot perform a backup at the qtree or subtree level. SMTape supports baseline, differential, and incremental backups.

Beginning in ONTAP 9.13.1, Tape backup using SMTape is supporting with xref:../snapmirror-active-sync/interoperability-reference.html[SnapMirror active sync].

// 2024 april 26, ontapdoc-1659
// ontapdoc-915, 16 april 2023