---
permalink: tape-backup/manage-node-scoped-ndmp-mode-concept.html
sidebar: sidebar
keywords: manage, node, scope, ndmp, mode, flexvol, volume, command, option, backup, restore
summary: "You can manage NDMP at the node level by using NDMP options and commands. You can modify the NDMP options by using the options command. You must use NDMP-specific credentials to access a storage system to perform tape backup and restore operations."
---
= Learn about managing ONTAP node-scoped NDMP mode for FlexVol volumes
:icons: font
:imagesdir: ../media/

[.lead]
You can manage NDMP at the node level by using NDMP options and commands. You can modify the NDMP options by using the `options` command. You must use NDMP-specific credentials to access a storage system to perform tape backup and restore operations.

Learn more about `options` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=options[ONTAP command reference^].

== Commands for managing node-scoped NDMP mode in ONTAP
You can use the `system services ndmp` commands to manage NDMP at a node level. Some of these commands are deprecated and will be removed in a future major release.

You can use the following NDMP commands only at the advanced privilege level:

* `system services ndmp service terminate`
* `system services ndmp service start`
* `system services ndmp service stop`
* `system services ndmp log start`
* `system services ndmp log stop`

[options="header"]
|===
| If you want to...| Use this command...
a|
Enable NDMP service
a|
`system services ndmp on`*
a|
Disable NDMP service
a|
`system services ndmp off`*
a|
Display NDMP configuration
a|
`system services ndmp show`*
a|
Modify NDMP configuration
a|
`system services ndmp modify`*
a|
Display the default NDMP version
a|
`system services ndmp version`*
a|
Display NDMP service configuration
a|
`system services ndmp service show`
a|
Modify NDMP service configuration
a|
`system services ndmp service modify`
a|
Display all NDMP sessions
a|
`system services ndmp status`
a|
Display detailed information about all NDMP sessions
a|
`system services ndmp probe`
a|
Terminate the specified NDMP session
a|
`system services ndmp kill`
a|
Terminate all NDMP sessions
a|
`system services ndmp kill-all`
a|
Change the NDMP password
a|
`system services ndmp password`*
a|
Enable node-scoped NDMP mode
a|
`system services ndmp node-scope-mode on`*
a|
Disable node-scoped NDMP mode
a|
`system services ndmp node-scope-mode off`*
a|
Display the node-scoped NDMP mode status
a|
`system services ndmp node-scope-mode status`*
a|
Forcefully terminate all NDMP sessions
a|
`system services ndmp service terminate`
a|
Start the NDMP service daemon
a|
`system services ndmp service start`
a|
Stop the NDMP service daemon
a|
`system services ndmp service stop`
a|
Start logging for the specified NDMP session
a|
`system services ndmp log start`*
a|
Stop logging for the specified NDMP session
a|
`system services ndmp log stop`*
|===
* These commands are deprecated and will be removed in a future major release.

Learn more about `system services ndmp` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+services+ndmp[ONTAP command reference^].

== User authentication in a node-scoped NDMP mode
In the node-scoped NDMP mode, you must use NDMP specific credentials to access a storage system in order to perform tape backup and restore operations.

The default user ID is "`root`". Before using NDMP on a node, you must ensure that you change the default NDMP password associated with the NDMP user. You can also change the default NDMP user ID.

.Related information

xref:commands-manage-node-scoped-ndmp-reference.adoc[Commands for managing node-scoped NDMP mode]

xref:node-scoped-ndmp-mode-concept.adoc[What node-scoped NDMP mode is]


// 2025 Jan 17, ONTAPDOC-2569