---
permalink: tape-backup/ndmp-modes-concept.html
sidebar: sidebar
keywords: ndmp, mode, operation, backup, restore, node, level, svm
summary: "You can choose to perform tape backup and restore operations either at the node level or at the storage virtual machine (SVM) level. To perform these operations successfully at the SVM level, NDMP service must be enabled on the SVM."
---
= Learn about ONTAP NDMP modes of operation
:icons: font
:imagesdir: ../media/

[.lead]
You can choose to perform tape backup and restore operations either at the node level or at the storage virtual machine (SVM) level. To perform these operations successfully at the SVM level, NDMP service must be enabled on the SVM.

If you upgrade from Data ONTAP 8.2 to Data ONTAP 8.3, the NDMP mode of operation used in 8.2 will continue to be retained post the upgrade from 8.2 to 8.3.

If you install a new cluster with Data ONTAP 8.2 or later, NDMP is in the SVM-scoped NDMP mode by default. To perform tape backup and restore operations in the node-scoped NDMP mode, you must explicitly enable the node-scoped NDMP mode.

// 2023 DEC 15, ontap-issues-1184

== Learn about node-scoped ONTAP NDMP mode
In the node-scoped NDMP mode, you can perform tape backup and restore operations at the node level. The NDMP mode of operation used in Data ONTAP 8.2 will continue to be retained post the upgrade from 8.2 to 8.3.

In the node-scoped NDMP mode, you can perform tape backup and restore operations on a node that owns the volume. To perform these operations, you must establish NDMP control connections on a LIF hosted on the node that owns the volume or tape devices.

[NOTE]
====
This mode is deprecated and will be removed in a future major release.
====

== Learn about SVM-scoped ONTAP NDMP mode
You can perform tape backup and restore operations at the storage virtual machine (SVM) level successfully if the NDMP service is enabled on the SVM. You can back up and restore all volumes hosted across different nodes in the SVM of a cluster if the backup application supports the CAB extension.

An NDMP control connection can be established on different LIF types. In the SVM-scoped NDMP mode, these LIFs belong to either the data SVM or admin SVM. The connection can be established on a LIF only if the NDMP service is enabled on the SVM that owns this LIF.

A data LIF belongs to the data SVM and the intercluster LIF, node-management LIF, and cluster-management LIF belong to the admin SVM.

In the SVM-scoped NDMP mode, the availability of volumes and tape devices for backup and restore operations depends on the LIF type on which the NDMP control connection is established and the status of the CAB extension. If your backup application supports the CAB extension and a volume and the tape device share the same affinity, then the backup application can perform a local backup or restore operation, instead of a three-way backup or restore operation.

.Related information

xref:commands-manage-node-scoped-ndmp-reference.adoc[Commands for managing node-scoped NDMP mode]

