---
permalink: tape-backup/ndmp-management-concept.html
sidebar: sidebar
keywords: understand, ndmp, flexvol, volume, network, data, management, protocol, storage, devices, systems, tape, library
summary: "The Network Data Management Protocol (NDMP) is a standardized protocol for controlling backup, recovery, and other types of data transfer between primary and secondary storage devices, such as storage systems and tape libraries."
---
= Learn about NDMP for ONTAP FlexVol volumes
:icons: font
:imagesdir: ../media/

[.lead]
The Network Data Management Protocol (NDMP) is a standardized protocol for controlling backup, recovery, and other types of data transfer between primary and secondary storage devices, such as storage systems and tape libraries.

By enabling NDMP support on a storage system, you enable that storage system to communicate with NDMP-enabled network-attached backup applications (also called _Data Management Applications_ or _DMAs_), data servers, and tape servers participating in backup or recovery operations. All network communications occur over TCPIP or TCP/IPv6 network. NDMP also provides low-level control of tape drives and medium changers.

You can perform tape backup and restore operations in either node-scoped NDMP mode or storage virtual machine (SVM) scoped NDMP mode.

You must be aware of the considerations that you have to take into account while using NDMP, list of environment variables, and supported NDMP tape backup topologies. You can also enable or disable the enhanced DAR functionality. The two authentication methods supported by ONTAP for authenticating NDMP access to a storage system are: plaintext and challenge.

.Related information

xref:environment-variables-supported-concept.adoc[Environment variables supported by ONTAP]
