---
permalink: tape-backup/restore-events-concept.html
sidebar: sidebar
keywords: restore, events, parenthesis, type
summary: "The event field for a restore event contains an event type followed by event-specific information in parentheses."
---
= What restore events are
:icons: font
:imagesdir: ../media/

[.lead]
The event field for a restore event contains an event type followed by event-specific information in parentheses.

The following table provides information about the events, their descriptions, and the related event information that can be recorded for a restore operation:

[options="header"]
|===
| Event| Description| Event information
a|
Start
a|
NDMP restore is started
a|
Restore level and the type of restore
a|
End
a|
Restores completed successfully
a|
Number of files and amount of data processed
a|
Abort
a|
The operation is cancelled
a|
Number of files and amount of data processed
a|
Options
a|
Specified options are listed
a|
All options and their associated values, including NDMP options
a|
Tape_open
a|
The tape is open for read/write
a|
The new tape device name
a|
Tape_close
a|
The tape is closed for read/write
a|
The tape device name
a|
Phase-change
a|
Restore is entering a new processing phase
a|
The new phase name
a|
Error
a|
Restore encounters an unexpected event
a|
Error message
|===
