---
permalink: tape-backup/smtape-storage-failover-arl-concept.html
sidebar: sidebar
keywords: smtape, storage, failover, arl, operation, aggregate, relocation
summary: "Before you perform SMTape backup or restore operations, you should understand how these operations work with storage failover (takeover and giveback) or aggregate relocation (ARL) operation. The -override-vetoes option determines the behavior of SMTape engine during a storage failover or ARL operation."
---
= How SMTape works with storage failover and ARL operations
:icons: font
:imagesdir: ../media/

[.lead]
Before you perform SMTape backup or restore operations, you should understand how these operations work with storage failover (takeover and giveback) or aggregate relocation (ARL) operation. The `-override-vetoes` option determines the behavior of SMTape engine during a storage failover or ARL operation.

When an SMTape backup or restore operation is running and the `-override-vetoes` option is set to `false`, a user-initiated storage failover or ARL operation is stopped and the backup or restore operation complete. If the backup application supports CAB extension, then you can continue performing incremental SMTape backup and restore operations without reconfiguring backup policies. However, if the `–override-vetoes` option is set to `true`, then the storage failover or ARL operation is continued and the SMTape backup or restore operation is aborted.

.Related information

link:../networking/networking_reference.html[Network management]

https://docs.netapp.com/us-en/ontap/high-availability/index.html[High Availability]
