---
permalink: tape-backup/smtape-capabilities-concept.html
sidebar: sidebar
keywords: smtap, capabilities, snapshot, copy, preservation, deduplication, compression, restored, volume, backup, restore
summary: "SMTape capabilities such as backup of snapshots, incremental and differential backups, preservation of deduplication and compression features on restored volumes, and tape seeding help you optimize your tape backup and restore operations."
---
= SMTape capabilities
:icons: font
:imagesdir: ../media/

[.lead]
SMTape capabilities such as backup of snapshots, incremental and differential backups, preservation of deduplication and compression features on restored volumes, and tape seeding help you optimize your tape backup and restore operations.

SMTape provides the following capabilities:

* Provides a disaster recovery solution
* Enables incremental and differential backups
* Backs up snapshots
* Enables backup and restore of deduplicated volumes and preserves deduplication on the restored volumes
* Backs up compressed volumes and preserves compression on the restored volumes
* Enables tape seeding

SMTape supports the blocking factor in multiples of 4 KB, in the range of 4 KB through 256 KB.

[NOTE]
====
You can restore data to volumes created across up to two major consecutive ONTAP releases only.
====
