---
permalink: tape-backup/supported-ndmp-authentication-methods-concept.html
sidebar: sidebar
keywords: ndmp, authentication, method, requests, plaintext, challenge
summary: "You can specify an authentication method to allow NDMP connection requests. ONTAP supports two methods for authenticating NDMP access to a storage system: plaintext and challenge."
---
= ONTAP supported NDMP authentication methods
:icons: font
:imagesdir: ../media/

[.lead]
You can specify an authentication method to allow NDMP connection requests. ONTAP supports two methods for authenticating NDMP access to a storage system: plaintext and challenge.

In node-scoped NDMP mode, both challenge and plaintext are enabled by default. However, you cannot disable challenge. You can enable and disable plaintext. In the plaintext authentication method, the login password is transmitted as clear text.

In the storage virtual machine (SVM)-scoped NDMP mode, by default the authentication method is challenge. Unlike the node-scoped NDMP mode, in this mode you can enable and disable both plaintext and challenge authentication methods.

.Related information

xref:user-authentication-node-scoped-ndmp-mode-concept.adoc[User authentication in a node-scoped NDMP mode]

xref:user-authentication-svm-scoped-ndmp-mode-concept.adoc[User authentication in the SVM-scoped NDMP mode]
