---
permalink: tape-backup/tape-device-name-format-concept.html
sidebar: sidebar
keywords: tape, device, name, format, rewind, type, alias, compression
summary: "Each tape device has an associated name that appears in a defined format. The format includes information about the type of device, rewind type, alias, and compression type."
---
= Format of an ONTAP tape device name
:icons: font
:imagesdir: ../media/

[.lead]
Each tape device has an associated name that appears in a defined format. The format includes information about the type of device, rewind type, alias, and compression type.

The format of a tape device name is as follows:

`rewind_type` `st` `alias_number` `compression_type`

`rewind_type` is the rewind type.

The following list describes the various rewind type values:

* *r*
+
ONTAP rewinds the tape after it finishes writing the tape file.

* *nr*
+
ONTAP does not rewind the tape after it finishes writing the tape file. You must use this rewind type when you want to write multiple tape files on the same tape.

* *ur*
+
This is the unload/reload rewind type. When you use this rewind type, the tape library unloads the tape when it reaches the end of a tape file, and then loads the next tape, if there is one.
+
You must use this rewind type only under the following circumstances:

 ** The tape drive associated with this device is in a tape library or is in a medium changer that is in the library mode.
 ** The tape drive associated with this device is attached to a storage system.
 ** Sufficient tapes for the operation that you are performing are available in the library tape sequence defined for this tape drive.

[NOTE]
====
If you record a tape using a no-rewind device, you must rewind the tape before you read it.
====

`st` is the standard designation for a tape drive.

`alias_number` is the alias that ONTAP assigns to the tape drive. When ONTAP detects a new tape drive, ONTAP assigns an alias to the tape drive.

`compression_type` is a drive-specific code for the density of data on the tape and the type of compression.

The following list describes the various values for `compression_type`:

* *a*
+
Highest compression

* *h*
+
High compression

* *m*
+
Medium compression

* *l*
+
Low compression

.Examples

`nrst0a` specifies a no-rewind device on tape drive 0 using the highest compression.

.Example of a listing of tape devices

The following example shows the tape devices associated with HP Ultrium 2-SCSI:

----

           Tape drive (fc202_6:2.126L1)  HP      Ultrium 2-SCSI
    rst0l  -  rewind device,        format is: HP (200GB)
    nrst0l -  no rewind device,     format is: HP (200GB)
    urst0l -  unload/reload device, format is: HP (200GB)
    rst0m  -  rewind device,        format is: HP (200GB)
    nrst0m -  no rewind device,     format is: HP (200GB)
    urst0m -  unload/reload device, format is: HP (200GB)
    rst0h  -  rewind device,        format is: HP (200GB)
    nrst0h -  no rewind device,     format is: HP (200GB)
    urst0h -  unload/reload device, format is: HP (200GB)
    rst0a  -  rewind device,        format is: HP (400GB w/comp)
    nrst0a -  no rewind device,     format is: HP (400GB w/comp)
    urst0a -  unload/reload device, format is: HP (400GB w/comp)
----

The following list describes the abbreviations in the preceding example:

* GB--Gigabytes; this is the capacity of the tape.
* w/comp--With compression; this shows the tape capacity with compression.
