---
permalink: tape-backup/user-authentication-svm-scoped-ndmp-mode-concept.html
sidebar: sidebar
keywords: user, authentication, svm, ndmp, node, vsadmin, backup, role, storage, virutal, machine, user
summary: "In the storage virtual machine (SVM)-scoped NDMP mode, NDMP user authentication is integrated with role-based access control. In the SVM context, the NDMP user must have either the “vsadmin” or “vsadmin-backup” role. In a cluster context, the NDMP user must have either the “admin” or “backup” role."
---
= User authentication in the SVM-scoped NDMP mode
:icons: font
:imagesdir: ../media/

[.lead]
In the storage virtual machine (SVM)-scoped NDMP mode, NDMP user authentication is integrated with role-based access control. In the SVM context, the NDMP user must have either the "`vsadmin`" or "`vsadmin-backup`" role. In a cluster context, the NDMP user must have either the "`admin`" or "`backup`" role.

Apart from these pre-defined roles, a user account associated with a custom role can also be used for NDMP authentication provided that the custom role has the "`vserver services ndmp`" folder in its command directory and the access level of the folder is not "`none`". In this mode, you must generate an NDMP password for a given user account, which is created through role-based access control. Cluster users in an admin or backup role can access a node-management LIF, a cluster-management LIF, or an intercluster LIF. Users in a vsadmin-backup or vsadmin role can access only the data LIF for that SVM. Therefore, depending on the role of a user, the availability of volumes and tape devices for backup and restore operations vary.

This mode also supports user authentication for NIS and LDAP users. Therefore, NIS and LDAP users can access multiple SVMs with a common user ID and password. However, NDMP authentication does not support Active Directory users.

In this mode, a user account must be associated with the SSH application and the "`User password`" authentication method.

.Related information

xref:commands-manage-svm-scoped-ndmp-reference.adoc[Commands for managing SVM-scoped NDMP mode]

link:../system-admin/index.html[System administration]

