---
permalink: tape-backup/workflow-task.html
sidebar: sidebar
keywords: perform, tape, backup, restore, flexvol, volume, ndmp, backup, application
summary: "You can perform tape backup and restore operations by using an NDMP-enabled backup application."
---
= Tape backup and restore workflow in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
You can perform tape backup and restore operations by using an NDMP-enabled backup application.

.About this task

The tape backup and restore workflow provides an overview of the tasks that are involved in performing tape backup and restore operations. For detailed information about performing a backup and restore operation, see the backup application documentation.

.Steps

. Set up a tape library configuration by choosing an NDMP-supported tape topology.
. Enable NDMP services on your storage system.
+
You can enable the NDMP services either at the node level or at the storage virtual machine (SVM) level. This depends on the NDMP mode in which you choose to perform the tape backup and restore operation.

. Use NDMP options to manage NDMP on your storage system.
+
You can use NDMP options either at the node level or at the SVM level. This depends on the NDMP mode in which you choose to perform the tape backup and restore operation.
+
You can modify the NDMP options at the node level by using the `system services ndmp modify` command and at the SVM level by using the `vserver services ndmp modify` command. 
Learn more about `system services ndmp modify`and `vserver services ndmp modify` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=services+ndmp+modify[ONTAP command reference^].

. Perform a tape backup or restore operation by using an NDMP-enabled backup application.
+
ONTAP supports both dump and SMTape engines for tape backup and restore.
+
For more information about using the backup application (also called _Data Management Applications_ or _DMAs_) to perform backup or restore operations, see your backup application documentation.

.Related information

xref:common-ndmp-topologies-reference.adoc[Common NDMP tape backup topologies]

xref:data-backup-dump-concept.adoc[Understanding dump engine for FlexVol volumes]


// 2025 Jan 17, ONTAPDOC-2569