---
permalink: software_setup/concept_decide_whether_to_use_ontap_cli.html
sidebar: software_setup_sidebar
keywords:
summary: You should only use the ONTAP CLI to perform your initial cluster setup if it not supported with your version of ONTAP System Manager.
---
= Decide whether to use the ONTAP CLI for cluster setup
:icons: font
:imagesdir: ../media/

[.lead]
While you can set up new clusters with the ONTAP CLI, NetApp recommends that you use ONTAP System Manager whenever possible to simplify the cluster setup process. Use these procedures only if your version of ONTAP System Manager does not support initial cluster setup for your planned ONTAP deployment.

Before completing any of these procedures, you should have installed, cabled and powered on your new storage system according to the installation and setup instructions for your platform model.
See the link:https://docs.netapp.com/platstor/index.jsp[AFF and FAS Documentation Center]

In ONTAP 9.7 and earlier, System Manager does not support new cluster setup for MetroCluster configurations or deployments that require IPv6 networking.
*QUESTION: IS THIS TRUE?*

If you are configuring a FlexArray on non-NetApp disks, you need to use the ONTAP CLI to configure root volumes on the array LUNs, and then use the Cluster Setup wizard to set up your cluster.
For more information, see the link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html?cp=9_2[FlexArray Virtualization Installation and Requirements Reference].
*QUESTION: IS THIS TRUE FOR ALL VERSIONS OF ONTAP 9?*

*QUESTION: Are there other limitations to cluster setup capability for ONTAP System Manager in 9.7 and later?*
