---
permalink: software_setup/concept_additional_system_configuration_tasks_to_complete.html
sidebar: sidebar
keywords: ontap, software, setup, additional, system, configuration, tasks
summary: 'After setting up a cluster, you can use either ONTAP System Manager or the ONTAP command-line interface \(CLI\) to continue configuring the cluster.'
---
= Additional system configuration tasks to complete
:icons: font
:imagesdir: ../media/

[.lead]
After setting up a cluster, you can use either ONTAP System Manager or the ONTAP command-line interface (CLI) to continue configuring the cluster.

[cols=2*,options="header"]
|===
| System configuration task| Resource
a|
Configure networking:

* Create broadcast domains
* Create subnets
* Create IP spaces

a|
link:/networking/set_up_nas_path_failover_98_and_later_cli.html[Setting up the network]

a|
Set up the Service Processor
a|
link:../system-admin/index.html[System administration]

a|
Lay out your aggregates
a|
link:../disks-aggregates/index.html[Disk and aggregate management]

a|
Create and configure data storage virtual machines (SVMs)
a|

link:../nfs-config/index.html[NFS configuration]

link:/smb-config/index.html[SMB configuration]

link:../san-admin/index.html[SAN administration]

a|
Configure event notifications
a|
link:../error-messages/config-workflow-task.html[EMS configuration]

|===
