---
permalink: software_setup/task_configuring_important_ems_events_to_send_email_notifications.html
sidebar: software_setup_sidebar
keywords:
summary: 'To receive email notifications of the most important events, you must configure the EMS to send email messages for events that signal important activity.'
---
= Configuring important EMS events to send email notifications
:icons: font
:imagesdir: ../media/

[.lead]
To receive email notifications of the most important events, you must configure the EMS to send email messages for events that signal important activity.

DNS must be configured on the cluster to resolve the email addresses.

You can perform this task any time the cluster is running by entering the commands on the ONTAP command line.

. Configure the event SMTP mail server settings: `event config modify -mail-server mailhost.your_domain -mail-from cluster_admin@your_domain`
. Create an email destination for event notifications: `event notification destination create -name storage-admins -email your_email@your_domain`
. Configure the important events to send email notifications: `event notification create -filter-name important-events -destinations storage_admins`
