---
permalink: software_setup/task_configuring_snmp_traphosts_to_receive_event_notifications.html
sidebar: software_setup_sidebar
keywords:
summary: 'To receive event notifications on an SNMP traphost, you must configure a traphost.'
---
= Configuring SNMP traphosts to receive event notifications
:icons: font
:imagesdir: ../media/

[.lead]
To receive event notifications on an SNMP traphost, you must configure a traphost.

* SNMP and SNMP traps must be enabled on the cluster.
+
NOTE: SNMP and SNMP traps are enabled by default.

* DNS must be configured on the cluster to resolve the traphost names.

If you do not already have an SNMP traphost configured to receive event notifications (SNMP traps), you must add one.

You can perform this task any time the cluster is running by entering the commands on the ONTAP command line.

. If your environment does not already have an SNMP traphost configured to receive event notifications, add one: `system snmp traphost add -peer-address snmp_traphost_name`
+
All event notifications that are supported by SNMP by default are forwarded to the SNMP traphost.
