---
permalink: software_setup/task_synchronize_the_system_time_across_the_cluster.html
sidebar: sidebar
keywords: ontap, software, setup, synchronize, system, time, across, cluster
summary: 'Synchronizing the time ensures that every node in the cluster has the same time, and prevents CIFS and Kerberos failures.'
---
= Synchronize the system time across an ONTAP cluster
:icons: font
:imagesdir: ../media/

[.lead]
Synchronizing the time ensures that every node in the cluster has the same time, and prevents CIFS and Kerberos failures.

A Network Time Protocol (NTP) server should be set up at your site. Beginning with ONTAP 9.5, you can set up your NTP server with symmetric authentication.
For more information, see documentation for link:../system-admin/manage-cluster-time-concept.html[managing the cluster time (cluster administrators only)].

You synchronize the time across the cluster by associating the cluster with one or more NTP servers.

. Verify that the system time and time zone is set correctly for each node:
+
[source, cli]
----
cluster date show
----
+
All nodes in the cluster should be set to the same time zone.
+
This example shows the date and time zone for each node in the cluster.
+
----
cluster1::> cluster date show
Node         Date                Time zone
------------ ------------------- -----------------
cluster1-01  01/06/2015 09:35:15 America/New_York
cluster1-02  01/06/2015 09:35:15 America/New_York
cluster1-03  01/06/2015 09:35:15 America/New_York
cluster1-04  01/06/2015 09:35:15 America/New_York
4 entries were displayed.
----

. Change the date or time zone for all of the nodes:
+
[source, cli]
----
cluster date modify
----
+
This example changes the time zone for the cluster to be GMT:
+
----
cluster1::> cluster date modify -timezone GMT
----

. Associate the cluster with your NTP server:
+
To set up your NTP server without symmetric authentication enter the following command: 
+
[source,cli]
----
cluster time-service ntp server create -server <server_name>
----
+
To set up your NTP server with symmetric authentication, enter the following command:
+
[source,cli]
----
cluster time-service ntp server create -server <server_ip_address> -key-id <key_id>
----
+
NOTE: Symmetric authentication is available beginning with ONTAP 9.5. It is not available in ONTAP 9.4 or earlier.
+
This example assumes that DNS has been configured for the cluster. If you have not configured DNS, you must specify the IP address of the NTP server:
+
----
cluster1::> cluster time-service ntp server create -server ntp1.example.com
----
. Verify that the cluster is associated with an NTP server: 
+
[source,cli]
----
cluster time-service ntp server show
----
+
This example shows that the cluster is associated with the NTP server ntp1.example.com.
+
----
cluster1::> cluster time-service ntp server show
Server               Version
-------------------- -----------
ntp1.example.com     auto
----

== Commands for managing symmetric authentication on NTP servers

Beginning with ONTAP 9.5, Network Time Protocol (NTP) version 3 is supported. NTPv3 includes symmetric authentication using SHA-1 keys which increases network security.

[cols=2*,options="header"]
|===
| To do this...| Use this command...

a|
Configure an NTP server without symmetric authentication
a|
[source,cli]
----
cluster time-service ntp server create -server server_name
----
a|
Configure an NTP server with symmetric authentication
a|
[source,cli]
----
cluster time-service ntp server create -server server_ip_address -key-id key_id
----
a|
Enable symmetric authentication for an existing NTP server

An existing NTP server can be modified to enable authentication by adding the required key-id.

a|
[source,cli]
----
cluster time-service ntp server modify -server server_name -key-id key_id
----
a|
Configure a shared NTP key
a|
[source,cli]
----
cluster time-service ntp key create -id shared_key_id -type shared_key_type -value shared_key_value
----

*Note:* Shared keys are referred to by an ID. The ID, its type, and value must be identical on both the node and the NTP server

a|
Configure an NTP server with an unknown key ID
a|
[source,cli]
----
cluster time-service ntp server create -server server_name -key-id key_id
----
a|
Configure a server with a key ID not configured on the NTP server.
a|
[source,cli]
----
cluster time-service ntp server create -server server_name -key-id key_id
----

*Note:* The key ID, type, and value must be identical to the key ID, type, and value configured on the NTP server.

a|
Disable symmetric authentication
a|
[source,cli]
----
cluster time-service ntp server modify -server server_name -authentication disabled
----
|===

.Related information
* link:../system-admin/index.html[System administration]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+time-service+ntp[cluster time-service ntp^]
// 2025 Mar 25, ONTAPDOC 1325