---
permalink: software_setup/task_create_the_cluster_on_the_first_node.html
sidebar: sidebar
keywords: ontap, software, setup, create, cluster, first, node
summary: 'You use the Cluster Setup wizard to create the cluster on the first node. The wizard helps you to configure the cluster network that connects the nodes \(if the cluster consists of two or more nodes\), create the cluster admin storage virtual machine \(SVM\), add feature license keys, and create the node management interface for the first node.'
---
= Create the cluster on the first node
:icons: font
:imagesdir: ../media/

[.lead]
You use the Cluster Setup wizard to create the cluster on the first node. The wizard helps you to configure the cluster network that connects the nodes, create the cluster admin storage virtual machine (SVM), add feature license keys, and create the node management interface for the first node.

. Power on all the nodes you are adding to the cluster. This is required to enable discovery for your cluster setup.
. Connect to the console of the first node. *QUESTION: Are there any other discovery requirements? Should we talk about DHCP?*
+
The node boots, and then the Cluster Setup wizard starts on the console.
+
----
Welcome to the cluster setup wizard....
----

. Acknowledge the AutoSupport statement.
+
----
Type yes to confirm and continue {yes}: yes
----
+
NOTE: AutoSupport is enabled by default.

. Follow the instructions on the screen to assign an IP address to the node.


. If you are using the GUI wizard to perform setup, follow the instructions to complete setup in your web browser. If you are using the CLI wizard to perform setup, press Enter to continue.
+
----
Use your web browser to complete cluster setup by accessing
https://10.63.11.29

Otherwise, press Enter to complete cluster setup using the
command line interface:

Do you want to create a new cluster or join an existing cluster? {create, join}:
----

. Create a new cluster: `create`
. Accept the system defaults or enter your own values.
. After setup is completed, log in to the cluster and verify that the cluster is active and the first node is healthy by entering the ONTAP CLI command: `cluster show`
+
The following example shows a cluster in which the first node (cluster1-01) is healthy and eligible to participate:
+
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
----
+
You can access the Cluster Setup wizard to change any of the values you entered for the admin SVM or node SVM by using the `cluster setup` command.
