---
permalink: asa/support-limitations.html
sidebar: sidebar
keywords:  all flash san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify
summary: All-Flash SAN Array (ASA) configuration limits and support varies by ONTAP version. 
---

= All-Flash SAN Array configuration limits and support
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

All-Flash SAN Array (ASA) configuration limits and support varies by ONTAP version. 

The most current details on supported configuration limits are available in link:https://hwu.netapp.com/[NetApp Hardware Universe^].


== SAN protocols and supported number of nodes per cluster

// start tabbed area

[role="tabbed-block"]
====

.Non-MetroCluster configurations
--
The following table shows the ASA support for SAN protocols and the supported number of nodes per cluster in non-MetroCluster configurations:

[cols=3*,options="header"]
|===
| Beginning with ONTAP...  
| Protocol support
| Max nodes per cluster

| 9.11.1

a| 
* NVMe/TCP  
* NVMe/FC 
a|
12       

| 9.10.1

a| 
* NVMe/TCP  
a|
2


.2+|
9.9.1
a| 
* NVMe/FC 
a|
2

a| 
* FC 
* iSCSI
a|
12


| 9.7
a| 
* FC
* iSCSI 
a| 
2

|===
--

.MetroCluster IP configurations
--
The following table shows the ASA support for SAN protocols and the supported number of nodes per cluster in MetroCluster IP configurations:

[cols=3*,options="header"]
|===
| Beginning with ONTAP...
| Protocol support
| Max nodes per cluster

| 9.15.1  a|
* NVMe/TCP  | 2 nodes per cluster in four-node MetroCluster IP configurations 
| 9.12.1

a| 
* NVMe/FC 
a| 
2 nodes per cluster in four-node MetroCluster IP configurations


|9.9.1

a| 
* FC 
* iSCSI
a|
4 nodes per cluster in eight-node MetroCluster IP configurations 

| 9.7
a| 
* FC
* iSCSI 
a| 
2 nodes per cluster in four-node MetroCluster IP configurations 

|===

--

====

// end tabbed area

== Support for persistent ports

Beginning with ONTAP 9.8, persistent ports are enabled by default on All-Flash SAN Arrays (ASAs) that are configured to use the FC protocol. Persistent ports are only available for FC and require zone membership identified by World Wide Port Name (WWPN).

Persistent ports reduce the impact of takeovers by creating a shadow LIF on the corresponding physical port of the HA partner. When a node is taken over, the shadow LIF on the partner node assumes the identity of the original LIF, including the WWPNe. Before the status of path to the taken over node is changed to faulty, the shadow LIF appears as an Active/Optimized path to the host MPIO stack, and I/O is shifted. This reduces I/O disruption because the host always sees the same number of paths to the target, even during storage failover operations.

For persistent ports, the following FCP port characteristics should be identical within the HA pair: 

* FCP port counts
* FCP port names
* FCP port speeds
* FCP LIF WWPN-based zoning

If any of these characteristics are not identical within the HA pair, the following EMS message is generated:

`EMS : scsiblade.lif.persistent.ports.fcp.init.error`

For more information on persistent ports, see link:http://www.netapp.com/us/media/tr-4080.pdf[NetApp Technical Report 4080: Best Practices for Modern SAN^].

// 2023 Dec 11, Jira 1527
// 2023 Sept 12, Jira 1326
// 2023 Mar 02, Issue 827
// 2022-oct-06, IE-618, IE-631
// BURT 1448684, 10 JAN 2022
// BURT 1416205, 12 SEPT 2022
