---
sidebar: sidebar
permalink: high-availability/ha-pair-encryption.html
keywords: cluster network, encryption, TLS, data-in-flight
summary: Configure encryption communication between HA pair nodes
---

= Configure encryption for ONTAP HA traffic
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.18.1, you can configure encryption for network traffic between HA pair nodes. This encryption protects customer data and metadata sent between nodes in an HA pair.

.About this task
* Encryption for HA pair communication is disabled by default.
* Enabling or disabling HA pair encryption affects all HA pairs in the cluster. You cannot enable or disable encryption for individual HA pairs.
* When you enable encryption for HA pair communication, all customer data and metadata is encrypted when transmitted between HA pair nodes. Some traffic, such as filesystem metadata and heartbeat messages, is not encrypted.

.Before you begin
* You must be an ONTAP administrator at the `cluster` privilege level to perform the following procedure.
* An external key management server (KMS) is required to manage encryption keys for HA pair communication. The KMS must be configured before you can enable HA pair encryption.

.Steps

. View the current encryption status for HA pair communication:
+
[source, cli]
----
security ha-network show
----
This command shows the current status of HA pair encryption for each node:
+
```
security ha-network show
Node                  Enabled             
--------------------- --------------------
node1                 true                  
node2                 true                  
node3                 true
node4                 true
4 entries were displayed.
```

. Enable or disable encryption for HA pair communication:
+
[source, cli]
----
security ha-network modify -enabled <true|false>
----
This command enables or disables encrypted communication for all HA pairs.

// 9-24-25 ONTAPDOC-3258