---
sidebar: sidebar
permalink: high-availability/ha_automatic_giveback_commands.html
keywords: ontap, high, availability, ha, pair, automatic, giveback, commands
summary: Automatic giveback commands
---

= Automatic giveback commands
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
By default, the take-over partner node automatically gives back storage when the off-line node is brought back on line, thus restoring the high-availability pair relationship. In most cases, this is the desired behavior. If you need to disable automatic giveback - for example, if you want to investigate the cause of the takeover before giving back – you need to be aware of the interaction of non-default settings.

|===

h| If you want to... h|Use this command...

a|
Enable automatic giveback so that giveback occurs as soon as the taken-over node boots, reaches the Waiting for Giveback state, and the Delay before Auto Giveback period has expired.

The default setting is true.
a|
`storage failover modify ‑node _nodename_ ‑auto‑giveback true`
a|
Disable automatic giveback. The default setting is true.

*Note:* Setting this parameter to false does not disable automatic giveback after takeover on panic; automatic giveback after takeover on panic must be disabled by setting the `‑auto‑giveback‑after‑panic` parameter to false.
a|
`storage failover modify ‑node _nodename_ ‑auto‑giveback false`
a|
Disable automatic giveback after takeover on panic (this setting is enabled by default).
a|
`storage failover modify ‑node _nodename_ ‑auto‑giveback‑after‑panic false`

a|
Delay automatic giveback for a specified number of seconds (the default is 600). This option determines the minimum time that a node remains in takeover before performing an automatic giveback.
a|
`storage failover modify ‑node _nodename_ ‑delay‑seconds _seconds_`

|===

== How variations of the storage failover modify command affect automatic giveback

The operation of automatic giveback depends on how you configure the parameters of the storage failover modify command.

The following table lists the default settings for the `storage failover modify` command parameters that apply to takeover events not caused by a panic.


|===

h| Parameter  h| Default setting
a|
`-auto-giveback _true_ \| _false_`
a|
`_true_`
a|
`-delay-seconds _integer_ (seconds)`
a|
600
a|
`-onreboot _true_ \| _false_`
a|
`_true_`
|===


The following table describes how combinations of the `-onreboot` and `-auto-giveback` parameters affect automatic giveback for takeover events not caused by a panic. 

|===

h| `storage failover modify` parameters used h|Cause of takeover h|Does automatic giveback occur?

.2+a|
`-onreboot _true_`

`-auto-giveback _true_`
|reboot command | Yes
| halt command, or power cycle operation issued from the Service Processor | Yes

.2+a|
`-onreboot _true_`

`-auto-giveback _false_`

|reboot command |Yes
|halt command, or power cycle operation issued from the Service Processor |No

.2+a|
`-onreboot _false_`

`-auto-giveback _true_`

|reboot command |N/A
In this case, takeover does not occur
|halt command, or power cycle operation issued from the Service Processor |Yes

.2+a|
`-onreboot _false_`

`-auto-giveback _false_`

|reboot command
|No

|halt command, or power cycle operation issued from the Service Processor
|No
|===

The `-auto-giveback` parameter controls giveback after panic and all other automatic takovers. If the `-onreboot` parameter is set to `true` and a takeover occurs due to a reboot, then automatic giveback is always performed, regardless of whether the `-auto-giveback` parameter is set to `true`.

The `-onreboot` parameter applies to reboots and halt commands issued from ONTAP. When the `-onreboot` parameter is set to false, a takeover does not occur in the case of a node reboot. Therefore, automatic giveback cannot occur, regardless of whether the `-auto-giveback` parameter is set to true. A client disruption occurs.

== The effects of automatic giveback parameter combinations that apply to panic situations.

The following table lists the `storage failover modify` command parameters that apply to panic situations:


|===

h| Parameter h| Default setting

a|
`-onpanic _true \| false_`
a|
`_true_`

a|
`-auto-giveback-after-panic _true \| false_`

(Privilege: Advanced)

a|
`_true_`

a|
`-auto-giveback _true \| false_`
a|
`_true_`
|===


The following table describes how parameter combinations of the `storage failover modify` command affect automatic giveback in panic situations.

NOTE: Be aware that takeover can occur for other reasons in the event of a node panic. For example, if a node panics but the panic packet is not received by its partner, the partner might perform a heartbeat loss takeover. In this case, giveback would not be controlled by the `-auto-giveback-after-panic` parameter but would instead be controlled by the `-onfailure` parameter.


[cols="60,40"]
|===

h| `storage failover` parameters used h| Does automatic giveback occur after panic?

|`-onpanic true`
`-auto-giveback true`
`-auto-giveback-after-panic true`
|Yes
|`-onpanic true`
`-auto-giveback true`
`-auto-giveback-after-panic false`
|No
|`-onpanic true`
`-auto-giveback false`
`-auto-giveback-after-panic true`
|Yes
|`-onpanic true`
`-auto-giveback false`
`-auto-giveback-after-panic false`
|No
|`-onpanic false`
If `-onpanic` is set to `false`, takeover/giveback does not occur, regardless of the value set for `-auto-giveback` or `-auto-giveback-after-panic`
|No
|===

[NOTE]
====
If you modify the default settings, the `-onpanic` parameter can override automatic giveback, as shown in the table above.

* If the `-onpanic` parameter is set to `true`, automatic giveback is always performed if a panic occurs unless you have changed the default settings for the `-auto-giveback` and `-auto-giveback-after-panic` parameters. If both of these parameters are changed from their default (`true`) to `false`, then an automatic giveback will not occur after a panic, even if the `-onpanic` parameter is set to `true`.

*  If the `-onpanic` parameter is set to `false`, a takeover does not occur and clients experience a disruption in ONTAP data services. Therefore, automatic giveback cannot occur, even if the `-auto-giveback-after-panic` parameter is set to `true`.
====

// Start snippet: complex admonition - sample with bulleted list
// 1 placeholder: LABEL (all caps)

[NOTE]
====
* Takeover might occur for other reasons during node panic.  In such cases, giveback is not controlled by the `auto-giveback-after-panic` setting.
* If the `-onpanic` parameter is set to `true`, automatic giveback is always performed if a panic occurs unless you have changed the default settings for the `-auto-giveback` and `-auto-giveback-after-panic` parameters. If both of these parameters are changed from their default (`true`) to `false`, then an automatic giveback will not occur after a panic, even if the `-onpanic` parameter is set to `true`.
* If the `-onpanic` parameter is set to `false`, takeover does not occur. Therefore, automatic giveback cannot occur, even if the `-auto-giveback-after-panic` parameter is set to `true`. A client disruption occurs.
====
// End snippet


//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-04-14 10:46:21.398175
//
// 26 jan 2022, issue #322
// 08 Aug 2022, BURT 1488610
