---
sidebar: sidebar
permalink: high-availability/ha_manual_giveback.html
keywords: ontap, high, availability, ha, pair, manual, giveback, interrupted, vetoed, veto, commands, performing, perform
summary: "You can perform a normal giveback, a giveback in which you terminate processes on the partner node, or a forced giveback."
---

= Performing a manual giveback
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can perform a normal giveback, a giveback in which you terminate processes on the partner node, or a forced giveback.

NOTE: Prior to performing a giveback, you must remove the failed drives in the taken-over
system as described in the Disks and Aggregates Power Guide

== If giveback is interrupted

If the takeover node experiences a failure or a power outage during the giveback process, that process stops and the takeover node returns to takeover mode until the failure is repaired or the power is restored.

However, this depends upon the stage of giveback in which the failure occurred. If the node encountered failure or a power outage during partial giveback state (after it has given back the root aggregate), it will not return to takeover mode. Instead, the node returns to partial-giveback mode.  If this occurs, complete the process by repeating the giveback operation.


== If giveback is vetoed

If giveback is vetoed, you must check the EMS messages to determine the cause. Depending on the reason or reasons, you can decide whether you can safely override the vetoes

== Commands for performing a manual giveback

You can manually initiate a giveback on a node in an HA pair to return storage to the original owner after completing maintenance or resolving any issues that caused the takeover.

[cols=2*,options="header"]
|===
|If you want to... |Use this command...

|===
