---
sidebar: high-availability_sidebar
permalink: high-availability/index.html
keywords: high availability, ha, overview
summary: "Takeover is the process in which a node assumes control of its partner's storage. Giveback is the process in which the storage is returned to the partner."
---

= High Availability Reference
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2021-04-14 10:46:21.249224
//

[.lead]
The HA pair controller configuration consists of a pair of matching FAS storage controllers (local node and partner node); each of these nodes are connected to the other’s disk shelves. When one node in an HA pair encounters an error and stops processing data, its partner detects the failed status of the partner and takes over all data processing from that controller.

Takeover is the process in which a node assumes control of its partner's storage.

Giveback is the process in which the storage is returned to the partner.

By default, takeovers occur automatically when:

* A software or system failure occurs on a node that leads to a panic. The HA pair controllers automatically fail over to their partner node. After the partner has recovered from the panic and booted up, the node automatically performs a giveback, returning the partner to normal operation.
* A system failure occurs and cannot reboot. For example, when a node fails with power loss, HA pair controllers automatically fail over to their partner node and serve data from the surviving storage controller.

[NOTE]
If the storage for a node also loses power at the same time, a standard takeover is not possible.

* Heartbeat messages are not received from the node's partner. This could happen if the partner experienced a hardware or software failure that did not result in a panic but still prevented it from functioning correctly, for example, an interconnect failure.
* You halt one of the nodes without using the `-f` or `-inhibit-takeover true` parameter.

[NOTE]
In a two-node cluster with cluster HA enabled, halting or rebooting a node using the `‑inhibit‑takeover true` parameter causes both nodes to stop serving data unless you first disable cluster HA and then assign epsilon to the node that you want to remain online.

* You reboot one of the nodes without using the `‑inhibit‑takeover true` parameter. (The `‑oneboot` parameter of the `storage failover` command is enabled by default.)
* The remote  management device (Service Processor) detects failure of the partner node. (Not applicable if you disable hardware-assisted takeover.)

You can also manually initiate takeovers with the `storage failover takeover` command.
