---
permalink: nas-audit/basic-auditing-concept.html
sidebar: sidebar
keywords: basic audit concepts
summary: "To understand auditing in ONTAP, you should be aware of some basic auditing concepts."
---
= Learn the fundamental ONTAP auditing concepts
:icons: font
:imagesdir: ../media/

[.lead]
To understand auditing in ONTAP, you should be aware of some basic auditing concepts.

* *Staging files*
+
The intermediate binary files on individual nodes where audit records are stored prior to consolidation and conversion. Staging files are contained in staging volumes.

* *Staging volume*
+
A dedicated volume created by ONTAP to store staging files. There is one staging volume per aggregate. Staging volumes are shared by all audit-enabled storage virtual machines (SVMs) to store audit records of data access for data volumes in that particular aggregate. Each SVM's audit records are stored in a separate directory within the staging volume.
+
Cluster administrators can view information about staging volumes, but most other volume operations are not permitted. Only ONTAP can create staging volumes. ONTAP automatically assigns a name to staging volumes. All staging volume names begin with `MDV_aud_` followed by the UUID of the aggregate containing that staging volume (for example: `MDV_aud_1d0131843d4811e296fc123478563412`.)

* *System volumes*
+
A FlexVol volume that contains special metadata, such as metadata for file services audit logs. The admin SVM owns system volumes, which are visible across the cluster. Staging volumes are a type of system volume.

* *Consolidation task*
+
A task that gets created when auditing is enabled. This long-running task on each SVM takes the audit records from staging files across the member nodes of the SVM. This task merges the audit records in sorted chronological order, and then converts them to a user-readable event log format specified in the auditing configuration--either the EVTX or XML file format. The converted event logs are stored in the audit event log directory that is specified in the SVM auditing configuration.
