---
permalink: nas-audit/certificates-disaster-recovery-non-id-preserve-concept.html
sidebar: sidebar
keywords: certificates, replicate, svm, disaster recovery, relationships, non-ID-preserve, configuration
summary: "Security certificates used for SSL authentication when making connections to FPolicy servers do not replicate to SVM disaster recovery destinations with non-ID-preserve configurations. Although the FPolicy external-engine configuration on the SVM is replicated, security certificates are not replicated. You must manually install the security certificates on the destination."
---
= ONTAP FPolicy certificates do not replicate in SVM disaster recovery relationships with a non-ID-preserve configuration
:icons: font
:imagesdir: ../media/

[.lead]
Security certificates used for SSL authentication when making connections to FPolicy servers do not replicate to SVM disaster recovery destinations with non-ID-preserve configurations. Although the FPolicy external-engine configuration on the SVM is replicated, security certificates are not replicated. You must manually install the security certificates on the destination.

When you set up the SVM disaster recovery relationship, the value you select for the `-identity-preserve` option of the `snapmirror create` command determines the configuration details that are replicated in the destination SVM.

If you set the `-identity-preserve` option to `true` (ID-preserve), all of the FPolicy configuration details are replicated, including the security certificate information. You must install the security certificates on the destination only if you set the option to `false` (non-ID-preserve).

.Related information
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html[snapmirror create^]


// 2025 July 01, ONTAPDOC-2960
// 2025 June 17, ONTAPDOC-3078