---
permalink: nas-audit/commands-modify-auditing-config-reference.html
sidebar: sidebar
keywords: commands, modify, audit, configurations
summary: "If you want to change an auditing setting, you can modify the current configuration at any time, including modifying the log path destination and log format, modifying the categories of events to audit, how to automatically save log files, and specify the maximum number of log files to save."
---
= ONTAP commands for modifying auditing configurations
:icons: font
:imagesdir: ../media/

[.lead]
If you want to change an auditing setting, you can modify the current configuration at any time, including modifying the log path destination and log format, modifying the categories of events to audit, how to automatically save log files, and specify the maximum number of log files to save.

[cols="30,50]
|===

h| If you want to... h| Use this command...

a|
Modify the log destination path
a|
`vserver audit modify` with the `-destination` parameter
a|
Modify the category of events to audit

a|
`vserver audit modify` with the `-events` parameter

NOTE: To audit central access policy staging events, the Dynamic Access Control (DAC) SMB server option must be enabled on the storage virtual machine (SVM).

a|
Modify the log format
a|
`vserver audit modify` with the `-format` parameter

a|
Enabling automatic saves based on internal log file size
a|
`vserver audit modify` with the `-rotate-size` parameter

a|
Enabling automatic saves based on a time interval
a|
`vserver audit modify` with the `-rotate-schedule-month`, `-rotate-schedule-dayofweek`, `-rotate-schedule-day`, `-rotate-schedule-hour`, and `-rotate-schedule-minute` parameters

a|
Specifying the maximum number of saved log files
a|
`vserver audit modify` with the `-rotate-limit` parameter

|===

// 2021-12-20, BURT 1445868
// 4 FEB 2022, BURT 1451789 