---
permalink: nas-audit/display-connections-external-fpolicy-servers-task.html
sidebar: sidebar
keywords: display, information, connections, external fpolicy servers
summary: "You can display status information about connections to external FPolicy servers (FPolicy servers) for the cluster or for a specified storage virtual machine (SVM). This information can help you determine which FPolicy servers are connected."
---

= Display information about connections to external ONTAP FPolicy servers

:icons: font
:imagesdir: ../media/

[.lead]
You can display status information about connections to external FPolicy servers (FPolicy servers) for the cluster or for a specified storage virtual machine (SVM). This information can help you determine which FPolicy servers are connected.

.About this task

If you do not specify any parameters, the command displays the following information:

* SVM name
* Node name
* FPolicy policy name
* FPolicy server IP address
* FPolicy server status
* FPolicy server type

In addition to displaying information about FPolicy connections on the cluster or a specific SVM, you can use command parameters to filter the command's output by other criteria.

You can specify the `-instance` parameter to display detailed information about listed policies. Alternatively, you can use the `-fields` parameter to display only the indicated fields in the command output. You can enter `?` after the `-fields` parameter to find out which fields you can use.

.Step

. Display filtered information about connection status between the node and the FPolicy server by using the appropriate command:
+
[cols="35,65"]
|===

h| If you want to display connection status information about FPolicy servers... h| Enter...

a|
That you specify
a|
`vserver fpolicy show-engine -server IP_address`
a|
For a specified SVM
a|
`vserver fpolicy show-engine -vserver vserver_name`
a|
That are attached with a specified policy
a|
`vserver fpolicy show-engine -policy-name policy_name`
a|
With the server status that you specify
a|
`vserver fpolicy show-engine -server-status status`

The server status can be one of the following:

 ** `connected`
 ** `disconnected`
 ** `connecting`
 ** `disconnecting`

a|
With the specified type
a|
`vserver fpolicy show-engine -server-type type`

The FPolicy server type can be one of the following:

 ** `primary`
 ** `secondary`

a|
That were disconnected with the specified reason
a|
`vserver fpolicy show-engine -disconnect-reason text`

Disconnect can be due to multiple reasons. The following are common reasons for disconnect:

 ** `Disconnect command received from CLI.`
 ** `Error encountered while parsing notification response from FPolicy server.`
 ** `FPolicy Handshake failed.`
 ** `SSL handshake failed.`
 ** `TCP Connection to FPolicy server failed.`
 ** `The screen response message received from the FPolicy server is not valid.`

+
|===

.Example

This example displays information about external engine connections to FPolicy servers on SVM vs1.example.com:

----
cluster1::> vserver fpolicy show-engine -vserver vs1.example.com
FPolicy                                              Server-       Server-
Vserver         Policy    Node         Server        status        type
--------------- --------- ------------ ------------- ------------- ---------
vs1.example.com policy1   node1        10.1.1.2      connected     primary
vs1.example.com policy1   node1        10.1.1.3      disconnected  primary
vs1.example.com policy1   node2        10.1.1.2      connected     primary
vs1.example.com policy1   node2        10.1.1.3      disconnected  primary
----

This example displays information only about connected FPolicy servers:

----
cluster1::> vserver fpolicy show-engine -fields server -server-status connected
node       vserver         policy-name server
---------- --------------- ----------- -------
node1      vs1.example.com policy1     10.1.1.2
node2      vs1.example.com policy1     10.1.1.2
----
