---
permalink: nas-audit/display-fpolicy-passthrough-read-connection-task.html
sidebar: sidebar
keywords: display, information, fpolicy, passthrough-read, connection status
summary: "You can display information about FPolicy passthrough-read connection status to external FPolicy servers (FPolicy servers) for the cluster or for a specified storage virtual machine (SVM). This information can help you determine which FPolicy servers have passthrough-read data connections and for which FPolicy servers the passthrough-read connection is disconnected."
---
= Display information about ONTAP FPolicy passthrough-read connection status
:icons: font
:imagesdir: ../media/

[.lead]
You can display information about FPolicy passthrough-read connection status to external FPolicy servers (FPolicy servers) for the cluster or for a specified storage virtual machine (SVM). This information can help you determine which FPolicy servers have passthrough-read data connections and for which FPolicy servers the passthrough-read connection is disconnected.

.About this task

If you do not specify any parameter, the command displays the following information:

* SVM name
* FPolicy policy name
* Node name
* FPolicy server IP address
* FPolicy passthrough-read connection status

In addition to displaying information about FPolicy connections on the cluster or a specific SVM, you can use command parameters to filter the command's output by other criteria.

You can specify the `-instance` parameter to display detailed information about listed policies. Alternatively, you can use the `-fields` parameter to display only the indicated fields in the command output. You can enter `?` after the `-fields` parameter to find out which fields you can use.

.Step

. Display filtered information about connection status between the node and the FPolicy server by using the appropriate command:
+
[cols="35,65"]
|===

h| If you want to display connection status information about... h| Enter the command...

a|
FPolicy passthrough-read connection status for the cluster
a|
`vserver fpolicy show-passthrough-read-connection`
a|
FPolicy passthrough-read connection status for a specified SVM
a|
`vserver fpolicy show-passthrough-read-connection -vserver vserver_name`
a|
FPolicy passthrough-read connection status for a specified policy
a|
`vserver fpolicy show-passthrough-read-connection -policy-name policy_name`
a|
Detailed FPolicy passthrough-read connection status for a specified policy
a|
`vserver fpolicy show-passthrough-read-connection -policy-name policy_name -instance`
a|
FPolicy passthrough-read connection status for the status that you specify
a|
`vserver fpolicy show-passthrough-read-connection -policy-name policy_name -server-status status`     The server status can be one of the following:

 ** `connected`
 ** `disconnected`

+
|===

.Example

The following command displays information about passthrough-read connections from all FPolicy servers on the cluster:

----
cluster1::> vserver fpolicy show-passthrough-read-connection
                                            FPolicy           Server
Vserver          Policy Name   Node         Server            Status
---------------  ------------- ------------ ----------------- --------------
vs2.example.com  pol_cifs_2    FPolicy-01   2.2.2.2           disconnected
vs1.example.com  pol_cifs_1    FPolicy-01   1.1.1.1           connected
----

The following command displays detailed information about passthrough-read connections from FPolicy servers configured in the "`pol_cifs_1`" policy:

----
cluster1::> vserver fpolicy show-passthrough-read-connection -policy-name pol_cifs_1 -instance

                                             Node: FPolicy-01
                                          Vserver: vs1.example.com
                                           Policy: pol_cifs_1
                                           Server: 1.1.1.1
                Session ID of the Control Channel: 8cef052e-2502-11e3-88d4-123478563412
                                    Server Status: connected
      Time Passthrough Read Channel was Connected: 9/24/2013 10:17:45
   Time Passthrough Read Channel was Disconnected: -
Reason for Passthrough Read Channel Disconnection: none
----

// 2025 June 17, ONTAPDOC-3078