---
permalink: nas-audit/display-audit-config-task.html
sidebar: sidebar
keywords: display, information, audit configurations
summary: "You can display information about auditing configurations. The information can help you determine whether the configuration is what you want in place for each SVM. The displayed information also enables you to verify whether an auditing configuration is enabled."
---
= Display information about auditing configurations
:icons: font
:imagesdir: ../media/

[.lead]
You can display information about auditing configurations. The information can help you determine whether the configuration is what you want in place for each SVM. The displayed information also enables you to verify whether an auditing configuration is enabled.

.About this task

You can display detailed information about auditing configurations on all SVMs or you can customize what information is displayed in the output by specifying optional parameters. If you do not specify any of the optional parameters, the following is displayed:

* SVM name to which the auditing configuration applies
* The audit state, which can be `true` or `false`
+
If the audit state is `true`, auditing is enabled. If the audit state is `false`, auditing is disabled.

* The categories of events to audit
* The audit log format
* The target directory where the auditing subsystem stores consolidated and converted audit logs

.Step

. Display information about the auditing configuration by using the `vserver audit show` command.
+
For more information about using the command, see the man pages.

.Examples

The following example displays a summary of the auditing configuration for all SVMs:

----
cluster1::> vserver audit show

 Vserver     State  Event Types Log Format Target Directory
 ----------- ------ ----------- ---------- --------------------
 vs1         false  file-ops    evtx       /audit_log
----

The following example displays, in list form, all auditing configuration information for all SVMs:

----
cluster1::> vserver audit show -instance

                             Vserver: vs1
                      Auditing state: true
                Log Destination Path: /audit_log
       Categories of Events to Audit: file-ops
                          Log Format: evtx
                 Log File Size Limit: 100MB
        Log Rotation Schedule: Month: -
  Log Rotation Schedule: Day of Week: -
          Log Rotation Schedule: Day: -
         Log Rotation Schedule: Hour: -
       Log Rotation Schedule: Minute: -
                  Rotation Schedules: -
            Log Files Rotation Limit: 0
----
