---
permalink: nas-audit/enable-audit-svm-task.html
sidebar: sidebar
keywords: enable, audit, svm
summary: "After you finish setting up the auditing configuration, you must enable auditing on the storage virtual machine \(SVM\)."
---
= Enable auditing on the SVM
:icons: font
:imagesdir: ../media/

[.lead]
After you finish setting up the auditing configuration, you must enable auditing on the storage virtual machine (SVM).

.Before you begin

The SVM audit configuration must already exist.

.About this task

When an SVM disaster recovery ID discard configuration is first started (after the SnapMirror initialization is complete) and the SVM has an auditing configuration, ONTAP automatically disables the auditing configuration. Auditing is disabled on the read-only SVM to prevent the staging volumes from filling up. You can enable auditing only after the SnapMirror relationship is broken and the SVM is read-write.

.Steps

. Enable auditing on the SVM:
+
`vserver audit enable -vserver vserver_name`
+
`vserver audit enable -vserver vs1`


.Related information

* link:create-auditing-config-task.html[Create the auditing configuration]
* link:verify-auditing-config-task.html[Verify the auditing configuration]

// 2024 Aug 7, ontapdoc-2278