---
permalink: nas-audit/enable-fpolicy-policy-task.html
sidebar: sidebar
keywords: enable, fpolicy policy
summary: "After you are through configuring an FPolicy policy configuration, you enable the FPolicy policy. Enabling the policy sets its priority and starts file access monitoring for the policy."
---
= Enable the FPolicy policy
:icons: font
:imagesdir: ../media/

[.lead]
After you are through configuring an FPolicy policy configuration, you enable the FPolicy policy. Enabling the policy sets its priority and starts file access monitoring for the policy.

.Before you begin

The FPolicy policy must exist with an associated external engine (if the policy is configured to use external FPolicy servers) and must have at least one associated FPolicy event. The FPolicy policy scope must exist and must be assigned to the FPolicy policy.

.About this task

The priority is used when multiple policies are enabled on the storage virtual machine (SVM) and more than one policy has subscribed to the same file access event. Policies that use the native engine configuration have a higher priority than policies for any other engine, regardless of the sequence number assigned to them when enabling the policy.

[NOTE]
====
A policy cannot be enabled on the admin SVM.
====

.Steps

. Enable the FPolicy policy by using the `vserver fpolicy enable` command.
+
`vserver fpolicy enable -vserver-name vs1.example.com -policy-name policy1 -sequence-number 1`

. Verify that the FPolicy policy is enabled by using the `vserver fpolicy show` command.
+
`vserver fpolicy show -vserver vs1.example.com`
+
----

                                   Sequence
Vserver          Policy Name         Number  Status   Engine
---------------  ----------------- --------  -------- ---------
vs1.example.com  policy1                  1  on       engine1
----
