---
permalink: nas-audit/fpolicy-services-svm-namespaces-concept.html
sidebar: sidebar
keywords: fpolicy, services, work, svm, namespaces
summary: "ONTAP provides a unified storage virtual machine (SVM) namespace. Volumes across the cluster are joined together by junctions to provide a single, logical file system. The FPolicy server is aware of the namespace topology and provides FPolicy services across the namespace."
---
= Learn about ONTAP FPolicy services across SVM namespaces
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP provides a unified storage virtual machine (SVM) namespace. Volumes across the cluster are joined together by junctions to provide a single, logical file system. The FPolicy server is aware of the namespace topology and provides FPolicy services across the namespace.

The namespace is specific to and contained within the SVM; therefore, you can see the namespace only from the SVM context. Namespaces have the following characteristics:

* A single namespace exists in each SVM, with the root of the namespace being the root volume, represented in the namespace as slash (/).
* All other volumes have junction points below the root (/).
* Volume junctions are transparent to clients.
* A single NFS export can provide access to the complete namespace; otherwise, export policies can export specific volumes.
* SMB shares can be created on the volume or on qtrees within the volume, or on any directory within the namespace.
* The namespace architecture is flexible.
+
Examples of typical namespace architectures are as follows:

 ** A namespace with a single branch off of the root
 ** A namespace with multiple branches off of the root
 ** A namespace with multiple unbranched volumes off of the root


// 2025 June 17, ONTAPDOC-3078