---
permalink: nas-audit/fpolicy-external-fpolicy-servers-concept.html
sidebar: sidebar
keywords: fpolicy, works, external fpolicy servers
summary: "After FPolicy is configured and enabled on the storage virtual machine (SVM), FPolicy runs on every node on which the SVM participates. FPolicy is responsible for establishing and maintaining connections with external FPolicy servers (FPolicy servers), for notification processing, and for managing notification messages to and from FPolicy servers."
---
= How FPolicy works with external FPolicy servers overview 
:icons: font
:imagesdir: ../media/

[.lead]
After FPolicy is configured and enabled on the storage virtual machine (SVM), FPolicy runs on every node on which the SVM participates. FPolicy is responsible for establishing and maintaining connections with external FPolicy servers (FPolicy servers), for notification processing, and for managing notification messages to and from FPolicy servers.

Additionally, as part of connection management, FPolicy has the following responsibilities:

* Ensures that file notification flows through the correct LIF to the FPolicy server.
* Ensures that when multiple FPolicy servers are associated with a policy, load balancing is done when sending notifications to the FPolicy servers.
* Attempts to reestablish the connection when a connection to an FPolicy server is broken.
* Sends the notifications to FPolicy servers over an authenticated session.
* Manages the passthrough-read data connection established by the FPolicy server for servicing client requests when passthrough-read is enabled.
