---
permalink: nas-audit/persistent-stores.html
sidebar: sidebar
keywords: overview, persistent store, fpolicy
summary: "Beginning with ONTAP 9.14.1, FPolicy allows you to setup a persistent store to capture file access events for asynchronous non-mandatory policies in the SVM. Persistent stores can help decouple client I/O processing from the FPolicy notification processing to reduce client latency. Synchronous and asynchronous mandatory configurations are not supported."
---
= FPolicy persistent stores
:icons: font
:imagesdir: ../media/

// 15-May-2024 ONTAPDOC-1910
// 15-April-2024 ONTAPDOC-1605
// 20 to 25 OCT 2023, ONTAPDOC-1344 updates
// 17 OCT 2023, ONTAPDOC-1344 

[.lead]
Persistent stores can help decouple client I/O processing from FPolicy notification processing to reduce client latency. Beginning with ONTAP 9.14.1, you can set up an FPolicy persistent store to capture file access events for asynchronous non-mandatory policies in the SVM. Synchronous (either mandatory or non-mandatory) and asynchronous mandatory configurations are not supported.

This feature is only available in FPolicy external mode. The partner application you use needs to support this feature. You should work with your partner to ensure this FPolicy configuration is supported.

Beginning with ONTAP 9.15.1, FPolicy persistent store configuration is simplified. The `persistent-store create` command automates volume creation for the SVM and configures the volume with persistent store best practices.  

For more information on persistent store best practices, refer to link:requirements-best-practices-fpolicy-concept.html[Requirements, considerations, and best practices for configuring FPolicy].

For information on adding persistent stores, refer to link:create-persistent-stores.html[Create persistent stores]. 
