---
permalink: nas-audit/supported-file-operation-filter-fpolicy-nfsv4-concept.html
sidebar: sidebar
keywords: ontap 9, supported file operation, filter combinations, fpolicy, monitor, nfsv4
summary: "When you configure your FPolicy event, you need to be aware that only certain combinations of file operations and filters are supported for monitoring NFSv4 file access operations."
---
= Supported file operation and filter combinations that FPolicy can monitor for NFSv4
:icons: font
:imagesdir: ../media/

[.lead]
When you configure your FPolicy event, you need to be aware that only certain combinations of file operations and filters are supported for monitoring NFSv4 file access operations.

The list of supported file operation and filter combinations for FPolicy monitoring of NFSv4 file access events is provided in the following table:

[cols="30,70"]
|===

h| Supported file operations h| Supported filters

a|
close
a|
offline-bit, exclude-directory
a|
create
a|
offline-bit
a|
create_dir
a|
Currently no filter is supported for this file operation.
a|
delete
a|
offline-bit
a|
delete_dir
a|
Currently no filter is supported for this file operation.
a|
getattr
a|
offline-bit, exclude-directory
a|
link
a|
offline-bit
a|
lookup
a|
offline-bit, exclude-directory
a|
open
a|
offline-bit, exclude-directory
a|
read
a|
offline-bit, first-read
a|
write
a|
offline-bit, first-write, write-with-size-change
a|
rename
a|
offline-bit
a|
rename_dir
a|
Currently no filter is supported for this file operation.
a|
setattr
a|
offline-bit, setattr_with_owner_change, setattr_with_group_change, setattr_with_mode_change, setattr_with_sacl_change, setattr_with_dacl_change, setattr_with_modify_time_change, setattr_with_access_time_change, setattr_with_size_change, exclude_directory
a|
symlink
a|
offline-bit
|===

Beginning with ONTAP 9.13.1, users can receive notifications for failed file operations due to lack of permissions. The list of supported access denied file operation and filter combinations for FPolicy monitoring of NFSv4 file access events is provided in the following table:

[cols="30,70"]
|===

h| Supported access denied file operation h| Supported filters

a|
access
a|
NA
a|
create
a|
NA
a|
create_dir
a|
NA
a|
delete
a|
NA
a|
delete_dir
a|
NA
a|
link
a|
NA
a|
open
a|
NA
a|
read
a|
NA
a|
rename
a|
NA
a|
rename_dir
a|
NA
a|
setattr
a|
NA
a|
write
a|
NA
|===

// 2023 Apr 13, Jira IDR-227