---
permalink: nas-audit/two-parts-fpolicy-solution-concept.html
sidebar: sidebar
keywords: two parts, fpolicy, solution
summary: "There are two parts to an FPolicy solution. The ONTAP FPolicy framework manages activities on the cluster and sends notifications to external FPolicy servers. External FPolicy servers process notifications sent by ONTAP FPolicy."
---
= What the two parts of the FPolicy solution are
:icons: font
:imagesdir: ../media/

[.lead]
FPolicy is a file access notification framework that is used to monitor and manage file access events on storage virtual machines (SVMs).

There are two parts to an FPolicy solution. The ONTAP FPolicy framework manages activities on the cluster and sends notifications to external FPolicy servers. External FPolicy servers process notifications sent by ONTAP FPolicy.

The ONTAP framework creates and maintains the FPolicy configuration, monitors file events, and sends notifications to external FPolicy servers. ONTAP FPolicy provides the infrastructure that allows communication between external FPolicy servers and storage virtual machine (SVM) nodes.

The FPolicy framework connects to external FPolicy servers and sends notifications for certain file system events to the FPolicy servers when these events occur as a result of client access. The external FPolicy servers process the notifications and send responses back to the node. What happens as a result of the notification processing depends on the application and whether the communication between the node and the external servers is asynchronous or synchronous.
