---
permalink: nas-audit/view-audit-event-logs-concept.html
sidebar: sidebar
keywords: view, audit event logs
summary: "You can use audit event logs to determine whether you have adequate file security and whether there have been improper file and folder access attempts. You can view and process audit event logs saved in the EVTX or XML file formats."
---
= View and process ONTAP audit event logs
:icons: font
:imagesdir: ../media/

[.lead]
You can use audit event logs to determine whether you have adequate file security and whether there have been improper file and folder access attempts. You can view and process audit event logs saved in the `EVTX` or `XML` file formats.

* `EVTX` file format
+
You can open the converted `EVTX` audit event logs as saved files using Microsoft Event Viewer.
+
There are two options that you can use when viewing event logs using Event Viewer:

 ** General view
+
Information that is common to all events is displayed for the event record. In this version of ONTAP, the event-specific data for the event record is not displayed. You can use the detailed view to display event-specific data.

 ** Detailed view
+
A friendly view and an XML view are available. The friendly view and the XML view display both the information that is common to all events and the event-specific data for the event record.

* `XML` file format
+
You can view and process `XML` audit event logs on third-party applications that support the `XML` file format. XML viewing tools can be used to view the audit logs provided you have the XML schema and information about definitions for the XML fields. For more information about the XML schema and definitions, see the https://library.netapp.com/ecm/ecm_get_file/ECMLP2875022[ONTAP Auditing Schema Reference].

== How active audit logs are viewed using Event Viewer

If the audit consolidation process is running on the cluster, the consolidation process appends new records to the active audit log file for audit-enabled storage virtual machines (SVMs). This active audit log can be accessed and opened over an SMB share in Microsoft Event Viewer.

In addition to viewing existing audit records, Event Viewer has a refresh option that enables you to refresh the content in the console window. Whether the newly appended logs are viewable in Event Viewer depends on whether oplocks are enabled on the share used to access the active audit log.

[cols="30,70"]
|===

h| Oplocks setting on the share h| Behavior

a|
Enabled
a|
Event Viewer opens the log that contains events written to it up to that point in time. The refresh operation does not refresh the log with new events appended by the consolidation process.
a|
Disabled
a|
Event Viewer opens the log that contains events written to it up to that point in time. The refresh operation refreshes the log with new events appended by the consolidation process.
|===

[NOTE]
====
This information is applicable only for `EVTX` event logs. `XML` event logs can be viewed through SMB in a browser or through NFS using any XML editor or viewer.
====
