---
permalink: san-config/benefits-vlans-iscsi-concept.html
sidebar: sidebar
keywords: benefits, using, vlans, iscsi, configurations
summary: "A VLAN consists of a group of switch ports grouped together into a broadcast domain. A VLAN can be on a single switch or it can span multiple switch chassis. Static and dynamic VLANs enable you to increase security, isolate problems, and limit available paths within your IP network infrastructure."
---
= Benefits of using VLANs in iSCSI configurations
:icons: font
:imagesdir: ../media/

[.lead]
A VLAN consists of a group of switch ports grouped together into a broadcast domain. A VLAN can be on a single switch or it can span multiple switch chassis. Static and dynamic VLANs enable you to increase security, isolate problems, and limit available paths within your IP network infrastructure.

When you implement VLANs in large IP network infrastructures, you derive the following benefits:

* Increased security.
+
VLANs enable you to leverage existing infrastructure while still providing enhanced security because they limit access between different nodes of an Ethernet network or an IP SAN.

* Improved Ethernet network and IP SAN reliability by isolating problems.
* Reduction of problem resolution time by limiting the problem space.
* Reduction of the number of available paths to a particular iSCSI target port.
* Reduction of the maximum number of paths used by a host.
+
Having too many paths slows reconnect times. If a host does not have a multipathing solution, you can use VLANs to allow only one path.
