---
permalink: san-config/configure-fc-adapters-initiator-mode-task.html
sidebar: sidebar
keywords: configure, fc adapters, initiator mode
summary: "You can configure individual FC ports of onboard adapters and certain FC adapter cards for initiator mode. Initiator mode is used to connect the ports to tape drives, tape libraries, or third-party storage with FlexArray Virtualization or Foreign LUN Import (FLI)."
---
= Configure FC adapters for initiator mode
:icons: font
:imagesdir: ../media/

[.lead]
You can configure individual FC ports of onboard adapters and certain FC adapter cards for initiator mode. Initiator mode is used to connect the ports to tape drives, tape libraries, or third-party storage with FlexArray Virtualization or Foreign LUN Import (FLI).

.What you'll need

* LIFs on the adapter must be removed from any port sets of which they are members.
* All LIF's from every storage virtual machine (SVM) using the physical port to be modified must be migrated or destroyed before changing the personality of the physical port from target to initiator.

.About this task

Each onboard FC port can be individually configured as an initiator or a target. Ports on certain FC adapters can also be individually configured as either a target port or an initiator port, just like the onboard FC ports. A list of adapters that can be configured for target mode is available in the _Hardware Universe_.

[NOTE]
====
NVMe/FC does support initiator mode.
====

.Steps

. Remove all LIFs from the adapter:
+
`network interface delete -vserver _SVM_name_ -lif _lif_name_,_lif_name_`
. Take your adapter offline:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -status-admin down`
+
If the adapter does not go offline, you can also remove the cable from the appropriate adapter port on the system.

. Change the adapter from target to initiator:
+
`system hardware unified-connect modify -t initiator _adapter_port_`
. Reboot the node hosting the adapter you changed.
. Verify that the FC ports are configured in the correct state for your configuration:
+
`system hardware unified-connect show`
. Bring the adapter back online:
+
`node run -node _node_name_ storage enable adapter _adapter_port_`

*Related information*

https://hwu.netapp.com[NetApp Hardware Universe]
