---
permalink: san-config/fc-switch-config-best-practices-concept.html
sidebar: sidebar
keywords: fc, switch, configuration, best, practices
summary: "For best performance, you should consider certain best practices when configuring your FC switch."
---
= FC switch configuration best practices
:icons: font
:imagesdir: ../media/

[.lead]
For best performance, you should consider certain best practices when configuring your FC switch.

A fixed link speed setting is the best practice for FC switch configurations, especially for large fabrics because it provides the best performance for fabric rebuilds and can significantly save time. Although autonegotiation provides the greatest flexibility, FC switch configuration does not always perform as expected, and it adds time to the overall fabric-build sequence.

All of the switches that are connected to the fabric must support N_Port ID virtualization (NPIV) and must have NPIV enabled. ONTAP uses NPIV to present FC targets to a fabric.

For details about which environments are supported, see the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].

For FC and iSCSI best practices, see https://www.netapp.com/pdf.html?item=/media/10680-tr4080pdf.pdf[NetApp Technical Report 4080: Best Practices for Modern SAN^].

// 2023 Dec 15, Jira 1527
