---
permalink: san-config/fc-target-port-config-recommendations-concept.html
sidebar: sidebar
keywords: fc, target, port, configuration, recommendations
summary: "For best performance and highest availability, you should use the recommended FC target port configuration."
---
= Determine supported FC target port speeds for your ONTAP system
:icons: font
:imagesdir: ../media/

[.lead]
FC target ports can be configured and used for the FC-NVMe protocol in the exact same way they are configured and used for the FC protocol. 

For best performance and highest availability, you should use the recommended target port configuration listed in https://hwu.netapp.com[NetApp Hardware Universe^] for your specific ONTAP system.

Each onboard FC port and expansion adapter port can be configured individually for different speeds as supported.  Supported speeds vary based upon your ONTAP system and HBAs.   All target ports used by a given host should be set to the same speed.
 
BEST PRACTICE: As a best practice, you should configure a common speed across all your initiator, switch, and target ports. If port and initiator speeds are different, and a common speed cannot be negotiated, a session cannot be established.  Using auto-negotiation to establish your port speed is not recommended.  Auto-negotiation can slow session establishment and reconnection after an interruption.

Supported speeds are listed in the NetApp Hardware Universe under *Supported Adapter Cards* for each ONTAP system.

.Steps
 
. Go to link:https://hwu.netapp.com[NetApp Hardware Universe^].
. Select *Products*.
. Under *Platforms*, select your system type.
. Select your specific system, and then select your ONTAP version.
. Select *Show Results*, and then select *Supported Adapter Cards*.
+
FC adapter cards are listed under *Category* as “Block Access (Target)” and the supported speeds are listed under *Supported Protocol(s)*.

// 2026 Aug 7, ONTAPDOC-4124
// 2026 Jan 20, ONTAPDOC-3283
// 2025 Apr 30, ONTAPDOC 2986
// 2024 Dec 04, ONTAPDOC-2579
// 2023 Dec 06, ONTAPDOC-1007