---
permalink: san-config/fc-target-port-supported-speeds-reference.html
sidebar: sidebar
keywords: fc, target, port, supported, speeds
summary: "FC target ports can be configured to run at different speeds. You should set the target port speed to match the speed of the device to which it connects. All target ports used by a given host should be set to the same speed."
---
= FC target port supported speeds
:icons: font
:imagesdir: ../media/

[.lead]
FC target ports can be configured to run at different speeds. You should set the target port speed to match the speed of the device to which it connects. All target ports used by a given host should be set to the same speed. 

FC target ports can be used for FC-NVMe configurations in the exact same way they are used for FC configurations.

You should set the target port speed to match the speed of the device to which it connects instead of using autonegotiation. A port that is set to autonegotiation can take longer to reconnect after a takeover/giveback or other interruption.

You can configure onboard ports and expansion adapters to run at the following speeds. Each controller and expansion adapter port can be configured individually for different speeds as needed.
[cols="4*",options="header"]
|===
| 4 Gb ports| 8 Gb ports| 16 Gb ports| 32 Gb ports
a|

* 4 Gb
* 2 Gb
* 1 Gb

a|

* 8 Gb
* 4 Gb
* 2 Gb

a|

* 16 Gb
* 8 Gb
* 4 Gb

a|

* 32 Gb
* 16 Gb
* 8 Gb

|===

[NOTE]
====
UTA2 ports can use an 8 Gb SFP+ adapter to support 8, 4, and 2 Gb speeds, if required.
====
