---
permalink: san-config/fibre-channel-fcoe-zoning-concept.html
sidebar: sidebar
keywords: fibre, channel, fcoe zoning
summary: "An FC, FC-NVMe or FCoE zone is a logical grouping of one or more ports within a fabric. For devices to be able see each other, connect, create sessions with one another, and communicate, both ports need to have a common zone membership. Single initiator zoning is recommended."
---
= Fibre Channel and FCoE zoning overview
:icons: font
:imagesdir: ../media/

[.lead]
An FC, FC-NVMe or FCoE zone is a logical grouping of one or more ports within a fabric. For devices to be able see each other, connect, create sessions with one another, and communicate, both ports must be members of the same zone. 

Zoning increases security by limiting access and connectivity to end-points that share a common zone. Ports that are not in the same zone cannot communicate with one another. This reduces or eliminates _crosstalk_ between initiator HBAs.  Should connectivity issues occur, zoning helps to isolate problems to a specific set of ports, thereby decreasing time to resolution.

Zoning reduces the number of available paths to a particular port and reduces the number of paths between a host and the storage system. For example, some host OS multipathing solutions have a limit on the number of paths they can manage. Zoning can reduce the number of paths visible to the host so that paths to the host do not exceed the maximum allowed by the host OS.

== World Wide Name-based zoning 

Zoning based on World Wide Name (WWN) specifies the WWN of the members to be included within the zone. Although World Wide Node Name (WWNN) zoning is possible with some switch vendors, when zoning in ONTAP, you must use World Wide Port Name (WWPN) zoning.

WWPN zoning is required to properly define a specific port and to use NPIV effectively.  FC switches should be zoned using the WWPNs of the target's logical interfaces (LIFs), not the WWPNs of the physical ports on the node. The WWPNs of the physical ports start with "`50`" and the WWPNs of the LIFs start with "`20`".

WWPN zoning provides flexibility because access is not determined by where the device is physically connected to the fabric. You can move a cable from one port to another without reconfiguring zones.

// 2025 Feb 06, ONTAPDOC 2680