---
permalink: san-config/index.html
sidebar: sidebar
keywords: san, configure, configuration, fc, iscsi, nvme, host, fcoe, topology, topologies, connect, connecting, limits
summary: "Supported FC-NVMe, FC, iSCSI, and FCoE topologies for connecting host computers to nodes, and supported limits for SAN components."
---
= SAN configuration overview
:icons: font
:imagesdir: ../media/

[.lead]
A storage area network (SAN) consists of a storage solution connected to hosts over a SAN transport protocol such as iSCSI or FC. You can configure your SAN so that your storage solution attaches to your hosts through one or more switches.  If you are using iSCSI, you can also configure your SAN so that your storage solution attaches directly to your host without using a switch.  

In a SAN, multiple hosts, using different operating systems, such as Windows, Linux, or UNIX, can access the storage solution at the same time.  You can use link:../san-admin/selective-lun-map-concept.html[Selective LUN mapping] and link:../san-admin/create-port-sets-binding-igroups-task.html[portsets] to limit data access between the hosts and the storage.

For iSCSI, the network topology between the storage solution and the hosts is referred to as a network.  For FC, FC/NVMe and FCoE the network topology between the storage solution and the hosts is referred to as a fabric. To create redundancy, which protects you against loss of data access, you should set up your SAN with HA pairs in a multi-network or multi-fabric configuration.  Configurations using single nodes or single networks/fabrics are not fully redundant so are not recommended.  

After your SAN is configured, you can link:../san-admin/provision-storage.html[provision storage for iSCSI or FC], or you can link:../san-admin/create-nvme-namespace-subsystem-task.html[provision storage for FC/NVMe].  Then you can connect to your hosts to begin servicing data.

SAN protocol support varies based on your version of ONTAP, your platform and your configuration. For details on your specific configuration, see the link:https://imt.netapp.com/matrix/[NetApp Interoperability Matrix Tool]. 


.Related information

* link:../san-admin/index.html[SAN administration overview]
* link:../nvme/support-limitations.html[NVMe configuration, support and limitations]

// 2024 Mar 05, Jira 1680
// BURT 1448684, 10 JAN 2022
