---
permalink: san-config/manage-systems-fc-adapters-concept.html
sidebar: sidebar
keywords: manage, systems with fc adapters
summary: "Commands are available to manage onboard FC adapters and FC adapter cards. These commands can be used to configure the adapter mode, display adapter information, and change the speed."
---
= Managing systems with FC adapters overview
:icons: font
:imagesdir: ../media/

[.lead]
Onboard FC adapters and some FC expansion adapter cards can be individually configured as either initiators or targets ports. The ports on some FC expansion adapters are configured as initiators or targets at the factory and cannot be changed.  Additional FC ports are also available through supported UTA2 cards configured with FC SFP+ adapters.

Initiator ports can be used to connect directly to back-end disk shelves, and possibly foreign storage arrays. Target ports can be used to connect only to FC switches. 

The number of onboard ports and CNA/UTA2 ports configured for FC varies depending on the model of the controller.  The supported target expansion adapters also varies depending on controller model. See link:https://hwu.netapp.com[NetApp Hardware Universe^] for a complete list of onboard FC ports and supported target expansion adapters for your controller model. 

// 2025, Feb 03, ONTAPDOC-2680
// 2023-12-07, ONTAPDOC-1007
