---
permalink: san-config/prevent-loss-connectivity-x1133a-r6-adapter-concept.html
sidebar: sidebar
keywords: how, prevent, loss, connectivity, using, x1133a-r6, adapter
summary: "You can prevent loss of connectivity during a port failure by configuring your system with redundant paths to separate X1133A-R6 HBAs."
---
= Avoid connectivity loss to an ONTAP system using an X1133A-R6 adapter
:icons: font
:imagesdir: ../media/

[.lead]
You can prevent loss of connectivity during a port failure by configuring your system with redundant paths to separate X1133A-R6 HBAs.

The X1133A-R6 HBA is a 4-port, 16 Gb FC adapter consisting of two 2-port pairs. The X1133A-R6 adapter can be configured as target mode or initiator mode. Each 2-port pair is supported by a single ASIC (for example, Port 1 and Port 2 on ASIC 1 and Port 3 and Port 4 on ASIC 2). Both ports on a single ASIC must be configured to operate in the same mode, either target mode or initiator mode. If an error occurs with the ASIC supporting a pair, both ports in the pair go offline.

To prevent this loss of connectivity, you configure your system with redundant paths to separate X1133A-R6 HBAs, or with redundant paths to ports supported by different ASICs on the HBA.
