---
permalink: san-config/set-queue-depths-solaris-hosts-task.html
sidebar: sidebar
keywords: set, queue, depths, solaris, hosts
summary: "You can set the LUN and HBA queue depth for your Solaris hosts."
---
= Set queue depths on Solaris hosts
:icons: font
:imagesdir: ../media/

[.lead]
You can set the LUN and HBA queue depth for your Solaris hosts.

.About this task

* For LUN queue depth: The number of LUNs in use on a host multiplied by the per-LUN throttle (lun-queue-depth) must be less than or equal to the tgt-queue-depth value on the host.
* For queue depth in a Sun stack: The native drivers do not allow for per LUN or per target `max_throttle` settings at the HBA level. The recommended method for setting the `max_throttle` value for native drivers is on a per-device type (VID_PID) level in the `/kernel/drv/sd.conf` and `/kernel/drv/ssd.conf` files. The host utility sets this value to 64 for MPxIO configurations and 8 for Veritas DMP configurations.

.Steps

. `# cd/kernel/drv`
. `# vi lpfc.conf`
. Search for `/tft-queue (/tgt-queue)`
+
`tgt-queue-depth=32`
+
[NOTE]
====
The default value is set to 32 at installation.
====
. Set the desired value based on the configuration of your environment.
. Save the file.
. Reboot the host using the `+sync; sync; sync; reboot -- -r+` command.
