---
permalink: san-config/setting-queue-depths-hp-ux-hosts-concept.html
sidebar: sidebar
keywords: set, queue, depths, hp-ux, hosts
summary: "You can change the LUN or device queue depth on HP-UX hosts using the kernel parameter scsi_max_qdepth. You can change the HBA queue depth using the kernel parameter max_fcp_reqs."
---
= Set queue depths on HP-UX hosts
:icons: font
:imagesdir: ../media/

[.lead]
You can change the LUN or device queue depth on HP-UX hosts using the kernel parameter `scsi_max_qdepth`. You can change the HBA queue depth using the kernel parameter `max_fcp_reqs`.

* The default value for `scsi_max_qdepth` is 8. The maximum value is 255.
+
`scsi_max_qdepth` can be dynamically changed on a running system using the `-u` option on the `kmtune` command. The change will be effective for all devices on the system. For example, use the following command to increase the LUN queue depth to 64:
+
`kmtune -u -s scsi_max_qdepth=64`
+
It is possible to change queue depth for individual device files using the `scsictl` command. Changes using the `scsictl` command are not persistent across system reboots. To view and change the queue depth for a particular device file, execute the following command:
+
`scsictl -a /dev/rdsk/c2t2d0`
+
`scsictl -m queue_depth=16 /dev/rdsk/c2t2d0`

* The default value for `max_fcp_reqs` is 512. The maximum value is 1024.
+
The kernel must be rebuilt and the system must be rebooted for changes to `max_fcp_reqs` to take effect. To change the HBA queue depth to 256, for example, use the following command:
+
`kmtune -u -s max_fcp_reqs=256`
