---
permalink: san-config/support-shared-san-config-concept.html
sidebar: sidebar
keywords: requirements, shared, san, configurations
summary: "Shared SAN configurations are defined as hosts that are attached to both ONTAP storage systems and other vendors’ storage systems. Accessing ONTAP storage systems and other vendors’ storage systems from a single host is supported as long as several requirements are met."
---
= Requirements for SAN hosts connected to ONTAP and non-NetApp systems
:icons: font
:imagesdir: ../media/

[.lead]
Shared SAN configurations are defined as hosts that are attached to both ONTAP storage systems and other vendors' storage systems. Accessing ONTAP storage systems and other vendors' storage systems from a single host is supported as long as several requirements are met.

For all of the host operating systems, it is a best practice to use separate adapters to connect to each vendor's storage systems. Using separate adapters reduces the chances of conflicting drivers and settings. For connections to an ONTAP storage system, the adapter model, BIOS, firmware, and driver must be listed as supported in the NetApp Interoperability Matrix Tool.

You should set the required or recommended timeout values and other storage parameters for the host. You must always install the NetApp software or apply the NetApp settings last.

* For AIX, you should apply the values from the AIX Host Utilities version that is listed in the Interoperability Matrix Tool for your configuration.
* For ESX, you should apply host settings by using Virtual Storage Console for VMware vSphere.
* For HP-UX, you should use the HP-UX default storage settings.
* For Linux, you should apply the values from the Linux Host Utilities version that is listed in the Interoperability Matrix Tool for your configuration.
* For Solaris, you should apply the values from the Solaris Host Utilities version that is listed in the Interoperability Matrix Tool for your configuration.
* For Windows, you should install the Windows Host Utilities version that is listed in the Interoperability Matrix Tool for your configuration.

.Related information

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]
