---
permalink: san-config/supported-fc-ports-concept.html
sidebar: sidebar
keywords: supported, fc, ports
summary: "The number of onboard FC ports and CNA/UTA2 ports configured for FC varies based on the model of the controller. FC ports are also available through supported FC target expansion adapters or additional UTA2 cards configured with FC SFP+ adapters."
---
= Supported FC ports
:icons: font
:imagesdir: ../media/

[.lead]
The number of onboard FC ports and CNA/UTA2 ports configured for FC varies based on the model of the controller. FC ports are also available through supported FC target expansion adapters or additional UTA2 cards configured with FC SFP+ adapters.

== Onboard FC, UTA, and UTA2 ports

* Onboard ports can be individually configured as either target or initiator FC ports.
* The number of onboard FC ports differs depending on controller model.
+
The https://hwu.netapp.com[NetApp Hardware Universe^] contains a complete list of onboard FC ports on each controller model.

* FAS2520 systems do not support FC.

== Target expansion adapter FC ports

* Available target expansion adapters differ depending on controller model.
+
The https://hwu.netapp.com[NetApp Hardware Universe^] contains a complete list of target expansion adapters for each controller model.

* The ports on some FC expansion adapters are configured as initiators or targets at the factory and cannot be changed.
+
Others can be individually configured as either target or initiator FC ports, just like the onboard FC ports. A complete list is available in https://hwu.netapp.com[NetApp Hardware Universe^].

// 2023-12-07, ONTAPDOC-1007