---
permalink: san-config/update-emulex-hba-queue-depths-task.html
sidebar: sidebar
keywords: update, emulex, hba, queue, depths, linux, host
summary: "You can update the queue depths of an Emulex HBA on a Linux host. To make the updates persistent across reboots, you must then create a new RAM disk image and reboot the host."
---
= Update Emulex HBA queue depths on a Linux host
:icons: font
:imagesdir: ../media/

[.lead]
You can update the queue depths of an Emulex HBA on a Linux host. To make the updates persistent across reboots, you must then create a new RAM disk image and reboot the host.

.Steps

. Identify the queue depth parameters to be modified:
+
`modinfo lpfc|grep queue_depth`
+
The list of queue depth parameters with their description is displayed. Depending on your operating system version, you can modify one or more of the following queue depth parameters:

 ** `lpfc_lun_queue_depth`: Maximum number of FC commands that can be queued to a specific LUN (uint)
 ** `lpfc_hba_queue_depth`: Maximum number of FC commands that can be queued to an lpfc HBA (uint)
 ** `lpfc_tgt_queue_depth`: Maximum number of FC commands that can be queued to a specific target port (uint)
+
The `lpfc_tgt_queue_depth` parameter is applicable only for Red Hat Enterprise Linux 7.x systems, SUSE Linux Enterprise Server 11 SP4 systems and 12.x systems.

. Update the queue depths by adding the queue depth parameters to the `/etc/modprobe.conf` file for a Red Hat Enterprise Linux 5.x system and to the `/etc/modprobe.d/scsi.conf` file for a Red Hat Enterprise Linux 6.x or 7.x system, or a SUSE Linux Enterprise Server 11.x or 12.x system.
+
Depending on your operating system version, you can add one or more of the following commands:

 ** `options lpfc lpfc_hba_queue_depth=new_queue_depth`
 ** `options lpfc lpfc_lun_queue_depth=new_queue_depth`
 ** `options lpfc_tgt_queue_depth=new_queue_depth`

. Create a new RAM disk image, and then reboot the host to make the updates persistent across reboots.
+
For more information, see the _System Administration Reference Guide_ for your version of Linux operating system.

. Verify that the queue depth values are updated for each of the queue depth parameter that you have modified:
+
`cat /sys/class/scsi_host/host_number/lpfc_lun_queue_depth``cat /sys/class/scsi_host/host_number/lpfc_tgt_queue_depth``cat /sys/class/scsi_host/host_number/lpfc_hba_queue_depth`
+
----
root@localhost ~]#cat /sys/class/scsi_host/host5/lpfc_lun_queue_depth
      30
----
+
The current value of the queue depth is displayed.

.Related information

link:../system-admin/index.html[System administration]
