---
permalink: upgrade/arp-warning-clear.html
sidebar: sidebar
keywords: ontap, upgrade, ransomware, protection, security, arp
summary: 'Before upgrading ONTAP, configure LDAP clients using SSLv3 for secure communications with LDAP servers to use TLS. SSL will not be available after the upgrade.'
---
= Respond to abnormal activity warnings in Autonomous Ransomware Protection (ARP)
:icons: font
:imagesdir: ../media/

[.lead]
Before you upgrade to ONTAP 9.16.1 or later, you should respond to any abnormal activity warnings reported by Autonomous Ransomware Protection (ARP). Because of the change in ARP to a machine learning/artificial intelligence (AI)-based model, any active warnings from the existing ARP (ONTAP 9.15.1 or earlier) will be lost after upgrade unless you first resolve them.

.Steps

. Respond to any abnormal activity warnings reported by link:../anti-ransomware/respond-abnormal-task.html[ARP] and resolve any potential issues.

. Confirm the resolution of these issues before upgrading by selecting *Update and Clear Suspect File Types* to record your decision and resume normal ARP monitoring.

// 2024-9-26, ontapdoc-2204