---
permalink: upgrade/concept_upgrade_methods.html
sidebar: sidebar
keywords: upgrade, methods, andu, ndu, automated, automatic, system manager, cli, nondisruptive, disruptive
summary: 'The method you use to upgrade depends upon your configuration.  If available, the automated nondisruptive upgrade (ANDU) using System Manager is the preferred method.'
---
= Which ONTAP upgrade method should I use?
:icons: font
:imagesdir: ../media/

[.lead]
The method you use to upgrade -- nondisruptive or disruptive, automated or manual -- depends upon your configuration.  If available, the automated nondisruptive upgrade (ANDU) using System Manager is the preferred method.

*Nondisruptive upgrades* +
Nondisruptive upgrades take advantage of ONTAP’s high-availability (HA) failover technology to ensure that clusters continue to serve data during the upgrade. There are two types of nondisruptive upgrade processes.

*	_Batch_ updates +
In a batch update, the cluster is divided into several batches, each of which contains multiple HA pairs.  In the first batch, half of the nodes are upgraded, followed by their HA partners. The process is then repeated sequentially for the remaining batches.

*	_Rolling_ updates +
In a rolling update, a node is taken offline and upgraded while its partner takes over its storage. When the node upgrade is complete, the partner node gives control back to the original owning node and the process is repeated, this time on the partner node. Each additional HA pair is upgraded in sequence until all HA pairs are running the target release. +
*Note:* The term _rolling upgrade_ is frequently used in the software industry for software upgrades that don't cause disruptions in service and hence is often synonymous with "nondisruptive upgrade". In ONTAP 9 upgrades, a _rolling update_ is one of the processes that can be used for nondisruptive upgrades.

Nondisruptive upgrades can be performed using an _automated_ or _manual_ method.

* *Automated nondisruptive upgrade (ANDU)*

**	When an administrator initiates an ANDU, ONTAP automatically installs the target ONTAP image on each node, validates the cluster components to ensure that the cluster can be upgraded nondisruptively, and then executes a batch or rolling update in the background.
***	Batch updates are the default for clusters of 8 nodes or more.
***	Rolling updates are the default for clusters with fewer than 8 nodes. Rolling updates can also be selected explicitly for clusters with 8 nodes or more.

**	An ANDU can be executed using System Manager or the ONTAP command line interface (CLI). If available for your configuration, ANDU using System Manager is the recommended method of upgrade.

* *Manual nondisruptive upgrade*

**	An administrator must manually confirm upgrade readiness of the cluster components on each node, then manually perform rolling update process steps in the foreground.
**	Manual nondisruptive upgrades are executed using the ONTAP CLI.
**	You should only use a manual method if ANDU is not supported for your configuration.

*Disruptive upgrades* +
In a disruptive upgrade, storage failover is disabled for each HA pair, and then each node is rebooted one at a time. Disruptive upgrades can be performed more quickly than nondisruptive upgrades, and require fewer steps to complete. However, you should not perform a disruptive upgrade unless you can take the cluster offline for the duration of the upgrade. If you are operating in a SAN environment, you should be prepared to shut down or suspend all SAN clients before performing a disruptive upgrade. Disruptive upgrades are performed using the ONTAP CLI.

== Methods for non-MetroCluster configurations

Clusters with 2 or more nodes can use any of the following upgrade methods, which are listed in order of recommended usage.

* xref:task_upgrade_andu_sm.html[Automated nondisruptive using System Manager]
* xref:task_upgrade_andu_cli.html[Automated nondisruptive using the CLI]
* xref:task_upgrade_nondisruptive_manual_cli.html[Manual nondisruptive]
* xref:task_updating_an_ontap_cluster_disruptively.html[Manual disruptive]

Single node clusters must use one of disruptive methods, although the automated method is recommended.

* xref:task_upgrade_disruptive_automated_cli.html[Automated disruptive]
* xref:task_updating_an_ontap_cluster_disruptively.html[Manual disruptive]

== Methods for MetroCluster configurations

The upgrade methods available for each configuration are listed in order of recommended usage.

[cols=3*,options="header"]
|===
| ONTAP version
| Number of nodes
| Upgrade method

| 9.3 or later | 2,4 a| * xref:task_upgrade_andu_sm.html[Automated nondisruptive using System Manager]
* xref:task_upgrade_andu_cli.html[Automated nondisruptive using the CLI]
* xref:task_updating_an_ontap_cluster_disruptively.html[Manual disruptive]
| 9.3 or later | 8 a| * xref:task_upgrade_andu_cli.html[Automated nondisruptive using the CLI]
* xref:task_updating_a_four_or_eight_node_mcc.html[Manual nondisruptive]
* xref:task_updating_an_ontap_cluster_disruptively.html[Manual disruptive]
| 9.2 or earlier | 2 a| * xref:task_updating_a_two_node_metrocluster_configuration_in_ontap_9_2_and_earlier.html[Manual nondisruptive (for 2-node clusters)]
* xref:task_updating_an_ontap_cluster_disruptively.html[Manual disruptive using the CLI]
| 9.2 or earlier | 4, 8 a| * xref:task_updating_a_four_or_eight_node_mcc.html[Manual nondisruptive]
* xref:task_updating_an_ontap_cluster_disruptively.html[Manual disruptive]
| 9.0 or later | 4, 8 (patch only) | xref:task_upgrade_andu_sm.html[Automated nondisruptive using System Manager]
| 9.2 or earlier | 2, 4, 8 (patch only) | xref:task_upgrade_andu_sm.html[Automated nondisruptive using System Manager]
|===

// 2022-03-07, BURT 1458608
//2021-12-22, BURT 1447276
