---
permalink: upgrade/concept_mixed_version_requirements.html
sidebar: sidebar
keywords: ontap, upgrade, mixed, version, requirements
summary: 'Beginning with ONTAP 9.3, by default, you cannot add new nodes to the cluster that are running a version of ONTAP that is different from the version running on the existing nodes.'
---
= Mixed version requirements
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.3, by default, you cannot add new nodes to the cluster that are running a version of ONTAP that is different from the version running on the existing nodes.

If you plan to add new nodes to your cluster that are running a version of ONTAP that is later than the nodes in your existing cluster, you should upgrade the nodes in your cluster to the later version first, then add the new nodes.

Mixed version clusters are not recommended, but in certain cases you might need to temporarily enter a mixed version state. For example, you need to enter a mixed version state if you are upgrading to a later version of ONTAP that is not supported on certain nodes in your existing cluster. In this case, you should upgrade the nodes that do support the later version of ONTAP, then remove the nodes that do not support the version of ONTAP you are upgrading to using the following command:

[cols=2, options="header"]
|===
// header row

a| ONTAP version
a| Command

a| ONTAP 9.3
a| `cluster unjoin -skip-last-low-version-node-check` 

a| ONATP 9.4 and later
a| `cluster remove-node -skip-last-low-version-node-check`
|===

You might also need to enter a mixed version state for a technical refresh or an interrupted upgrade. In such cases you can override ONTAP default behavior and add nodes of a different version using the `cluster add-node -allow-mixed-version-join` advanced privilege command.

When you have to enter a mixed version state, you should complete the upgrade as quickly as possible. An HA pair must not run an ONTAP version from a release that is different from other HA pairs in the cluster for more than seven days. For correct cluster operation, the period the cluster is in a mixed version state should be as short as possible.

When the cluster is in a mixed version state, you should not enter any commands that alter the cluster operation or configuration except as necessary to satisfy the upgrade requirements.

// 2022-04-25, BURT 1454366
