---
permalink: upgrade/concept_verify_svm_routing.html
sidebar: sidebar
keywords: ontap, upgrade, verify, verifying, svm, routing
summary: 'Before you upgrade ONTAP, ensure that the default SVM route is able to reach any network address that is not reachable by a more specific route.'
---
= Verify ONTAP cluster SVM routing configuration before an upgrade
:icons: font
:imagesdir: ../media/

[.lead]
To avoid disruption, before you upgrade your ONTAP software, you should ensure that the default SVM route is able to reach any network address that is not reachable by a more specific route. It is a best practice to configure one default route for an SVM. For more information, see link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU134[SU134: Network access might be disrupted by incorrect routing configuration in ONTAP^].

The routing table for an SVM determines the network path the SVM uses to communicate with a destination. It's important to understand how routing tables work so that you can prevent network problems before they occur.

Routing rules are as follows:

* ONTAP routes traffic over the most specific available route.
* ONTAP routes traffic over a default gateway route (having 0 bits of netmask) as a last resort, when more specific routes are not available.

In the case of routes with the same destination, netmask, and metric, there is no guarantee that the system will use the same route after a reboot or after an upgrade. This can especially be an issue if you have configured multiple default routes.

// 2025-Jan-3, ONTAPDOC-2606
// 2023 Dec 12, ONTAPDOC 1275
// 2023 Aug 28, ONTAPDOC 1257
