---
permalink: upgrade/concept_considerations_for_session_oriented_protocols.html
sidebar: sidebar
keywords: ontap, upgrade, update, considerations, session-oriented, protocols, impact, io, client, session, disruption, disrupted, smb, hyper-v, sql, server, ndo, nondisruptive, continuous availability, nfsv4.x, ndmp, backup, restores
summary: 'Clusters and session-oriented protocols might cause adverse effects on clients and applications in certain areas such as I/O service during upgrades.'
---
= Considerations for session-oriented protocols
:icons: font
:imagesdir: ../media/

[.lead]
Clusters and session-oriented protocols might cause adverse effects on clients and applications in certain areas such as I/O service during upgrades.

If you are using session-oriented protocols, consider the following:

* SMB
+
If you serve continuously available (CA) shares with SMBv3, you can use the automated
nondisruptive upgrade method (with System Manager or the CLI), and no disruption is
experienced by the client.
+
If you are serving shares with SMBv1 or SMBv2, or non-CA shares with SMBv3, client sessions are disrupted during upgrade takeover and reboot operations. You should direct users to end their sessions before you upgrade.
+
Hyper-V and SQL Server over SMB support nondisruptive operations (NDOs). If you configured a Hyper-V or SQL Server over SMB solution, the application servers and the contained virtual machines or databases remain online and provide continuous availability during the ONTAP upgrade.

* NFSv4.x
+
NFSv4.x clients will automatically recover from connection losses experienced during the upgrade using normal NFSv4.x recovery procedures. Applications might experience a temporary I/O delay during this process.

* NDMP
+
State is lost and the client user must retry the operation.

* Backups and restores
+
State is lost and the client user must retry the operation.
+
IMPORTANT: Do not initiate a backup or restore during or immediately before an upgrade. Doing so might result in data loss.

* Applications (for example, Oracle or Exchange)
+
Effects depend on the applications. For timeout-based applications, you might be able to change the timeout setting to longer than the ONTAP reboot time to minimize adverse effects.

// 2023 Dec 18, Jira 1275
// 2023 Jan 19, ontap-issues-754
// 2022 Feb 24, BURT 1404661
