---
permalink: upgrade/concept_upgrade_requirements_for_metrocluster_configurations.html
sidebar: sidebar
keywords: ontap, upgrade, update, requirements, metrocluster, configuration, mcc, general, normal, operations, switchover
summary: 'Before you upgrade your ONTAP software on a MetroCluster configuration, your clusters must meet certain requirements.'
---
= Check ONTAP upgrade requirements for MetroCluster configurations
:icons: font
:imagesdir: ../media/

[.lead]
Before you upgrade your ONTAP software on a MetroCluster configuration, your clusters must meet certain requirements. 

* Both clusters must be running the same version of ONTAP.
+
You can verify the ONTAP version by using the version command.

* If you're performing a major ONTAP upgrade, the MetroCluster configuration must be in normal mode.

* If you're performing a patch ONTAP upgrade, the MetroCluster configuration can be in either normal or switchover mode.

* For all configurations except two-node clusters, you can nondisruptively upgrade both clusters at the same time.
+
For nondisruptive upgrade in two-node clusters, the clusters must be upgraded one node at a time.

* The aggregates in both clusters must not be in resyncing RAID status.
+
During MetroCluster healing, the mirrored aggregates are resynchronized. You can verify if the MetroCluster configuration is in this state by using the `storage aggregate plex show -in-progress true` command. If any aggregates are being synchronized, you should not perform an upgrade until the resynchronization is complete.

* Negotiated switchover operations will fail while the upgrade is in progress.
+
To avoid issues with upgrade or revert operations, do not attempt an unplanned switchover during an upgrade or revert operation unless all nodes on both clusters are running the same version of ONTAP.

== Configuration requirements for MetroCluster normal operation

* The source SVM LIFs must be up and located on their home nodes.
+
Data LIFs for the destination SVMs are not required to be up or to be on their home nodes.

* All aggregates at the local site must be online.
* All root and data volumes owned by the local cluster's SVMs must be online.

== Configuration requirements for MetroCluster switchover

* All LIFs must be up and located on their home nodes.
* All aggregates must be online, except for the root aggregates at the DR site.
+
Root aggregates at the DR site are offline during certain phases of switchover.

* All volumes must be online.

.Related information

link:task_verifying_the_networking_and_storage_status_for_metrocluster_cluster_is_ready.html[Verifying networking and storage status for MetroCluster configurations]

// 2025-Jan-3, ONTAPDOC-2606
// 2023 Aug 30, Jira 1257
// 09 DEC 2021, BURT 1430515
