---
permalink: upgrade/confirm-configuration.html
sidebar: sidebar
keywords: ontap, upgrade, before, confirm, configuration, hardware, cluster management switches, metrocluster ip switches, san, target, release
summary: 'Before you upgrade ONTAP, you should confirm that your configuration is supported in the target release.'
---
= Confirm ONTAP support for your configuration
:icons: font
:imagesdir: ../media/

[.lead]

Before you upgrade ONTAP, you should confirm that your configuration can support the target release.

== All configurations

Use https://hwu.netapp.com[NetApp Hardware Universe^] to confirm that your hardware platform and cluster and management switches are supported in the target ONTAP release.  Cluster and management switches include the cluster network switches (NX-OS), management network switches (IOS), and reference configuration file (RCF).  If your cluster and management switches are supported, but are not running the minimum software versions required for the target ONTAP release, upgrade your switches to supported software versions.

* https://mysupport.netapp.com/site/info/broadcom-cluster-switch[NetApp Downloads: Broadcom Cluster Switches^]
* https://mysupport.netapp.com/site/info/cisco-ethernet-switch[NetApp Downloads: Cisco Ethernet Switches^]
* https://mysupport.netapp.com/site/info/netapp-cluster-switch[NetApp Downloads: NetApp Cluster Switches^]

[NOTE]
If you need to upgrade your switches, NetApp recommends that you complete the ONTAP software upgrade first, then perform the software upgrade for your switches.  

== MetroCluster configurations

Before you upgrade ONTAP, if you have a MetroCluster configuration, use the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] to confirm that your MetroCluster IP switches are supported in the target release.

== SAN configurations

Before you upgrade ONTAP, if your cluster is configured for SAN, use the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] to confirm that the SAN configuration is fully supported.

All SAN components--including the target ONTAP software version, host OS and patches, required Host Utilities software, multipathing software, and adapter drivers and firmware--should be supported.


// 2023 Aug 21, Jira 1183
//BURT 1381609; 2021-May-26
