---
permalink: upgrade/download-software-image.html
sidebar: sidebar
keywords: ontap, software, image, download, downloading, upgrade
summary: 'Before you upgrade ONTAP, you must first download the ONTAP software from the NetApp Support site.'
---
= Download the ONTAP software image
:icons: font
:imagesdir: ../media/

[.lead]

Before you upgrade ONTAP, you must first download the target ONTAP software image from the NetApp Support site. Depending on your ONTAP release, you can download the ONTAP software to an HTTPs, HTTP or FTP server on your network, or to a local folder.

[cols=2,options="header"]
|===
| If you are running... | You can download the image to this location... 

| ONTAP 9.6 and later 
a| 
* An HTTPS server +
The server's CA certificate must be installed on the local system. 
* A local folder
* An HTTP or FTP server

| ONTAP 9.4 and later 
a| 
* A local folder 
* An HTTP or FTP server

| ONTAP 9.0 and later 
| An HTTP or FTP server 
|===

.About this task

* If you are performing an automated nondisruptive upgrade using a link:concept_upgrade_paths.html#types-of-upgrade-paths[direct multi-hop upgrade path], you need to download the software package for both the intermediate ONTAP version and the target ONTAP version required for your upgrade.  For example, if you are upgrading from ONTAP 9.8 to ONTAP 9.13.1, you must download the software packages for both ONTAP 9.12.1 and ONTAP 9.13.1.  See link:concept_upgrade_paths.html#supported-upgrade-paths-for-on-premises-ontap-and-ontap-select[supported upgrade paths] to determine if your upgrade path requires you to download an intermediate software package.

* If you are upgrading a system with NetApp Volume Encryption to ONTAP 9.5 or later, you must download the ONTAP software image for non-restricted countries, which includes NetApp Volume Encryption.
+
If you use the ONTAP software image for restricted countries to upgrade a system with NetApp Volume Encryption, the system panics and you lose access to your volumes.

* You do not need to download a separate software package for your firmware. The firmware update for your cluster is included with the ONTAP software upgrade package and is copied to each node’s boot device. The new firmware is then installed as part of the upgrade process.

.Steps

. Locate the target ONTAP software in the link:https://mysupport.netapp.com/site/products/all/details/ontap9/downloads-tab[Software Downloads] area of the NetApp Support Site.
+
For an ONTAP Select upgrade, select *ONTAP Select Node Upgrade*.

. Copy the software image (for example, 97_q_image.tgz) to the appropriate location.
+
Depending on your ONTAP release, the location will be a directory an HTTP, HTTPS or FTP server from which the image will be served to the local system, or to a local folder on the storage system.

// 2023 Aug 30, Jira 1257
// 2023 Aug 08, Jira 1256
// 2023 Aug 8, Jira 1183
// 2023 March 03, Issue 833
// 2022-01-17, ontap-issue-189
// 2023 Aug 8, Jira 1183