---
permalink: upgrade/index.html
sidebar: sidebar
keywords: upgrade, ontap
summary: 'Should I upgrade or update ONTAP, ONTAP in the cloud or ONTAP select?'
---
= When should I upgrade ONTAP?
:icons: font
:imagesdir: ../media/

[.lead]

When you upgrade your ONTAP software, you are able to take advantage of the latest features, fixes, and improvements.  

You can use these procedures to upgrade on-premises ONTAP and ONTAP select.  

* To upgrade ONTAP in the cloud, see https://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html[Upgrading Cloud Volumes ONTAP software^].  
* To upgrade ONTAP select see the general procedure for link:https://docs.netapp.com/us-en/ontap-select/concept_adm_upgrading_nodes.html#general-procedure[Upgrading the ONTAP Select nodes].  

You should perform ONTAP software upgrades and service updates as follows:

* *ONTAP upgrades*
+
New ONTAP releases are entitled to full support for 3 years. NetApp recommends that you run the newest release for 1 year after general availability (GA) and then use the remaining time within the full support window to plan for your transition to a newer ONTAP release. 

* *Service updates*
+
Service updates deliver timely fixes for critical bugs that cannot wait for the next ONTAP feature release. Non-critical service updates should be applied every 3-6 months. Critical service updates should be applied as soon as possible.

NOTE: NetApp releases new ONTAP versions and service updates on the cadence model described in the link:https://mysupport.netapp.com/site/info/ontap-release-model[ONTAP Release Model].  You can use this information to help determine when you want to upgrade based on the release schedule. 

// 2023 Jul 25, Jira 1183
// BURT 1448684, 10 JAN 2022
