---
permalink: upgrade/index.html
sidebar: sidebar
keywords: upgrade, ontap
summary: 'Should I upgrade or update ONTAP, ONTAP in the cloud or ONTAP select?'
---
= ONTAP upgrade overview
:icons: font
:imagesdir: ../media/

[.lead]

When you upgrade your ONTAP software, you can take advantage of new and enhanced features and functionality that can help you reduce costs, accelerate critical workloads, and expand the scope of data protection available to your organization. 

A major ONTAP upgrade consists of moving from a lower to higher ONTAP numbered release. An example would be an upgrade of your cluster from ONTAP 9.8 to ONTAP 9.12.1.  A minor (or patch) upgrade consists of moving from a lower ONTAP version to a higher ONTAP version within the same numbered release. An example would be an upgrade of your cluster from ONTAP 9.12.1P1 to 9.12.1P4. 

link:task_upgrade_andu_sm.html[Automated Non-Disruptive Upgrade (ANDU) using System Manager] is the recommended method to perform both major and minor ONTAP software upgrades.  ANDU takes advantage of ONTAP’s high-availability (HA) failover technology to ensure that clusters continue to serve data without interruption during the upgrade. 

Note: Beginning with ONTAP 9.12.1, System Manager is fully integrated with BlueXP. If BlueXP is configured on your system, you can upgrade through the BlueXP working environment.

In addition to the simplicity offered by the ANDU process, you can also link:https://docs.netapp.com/us-en/active-iq/task_view_upgrade.html[use Upgrade Advisor] in Active IQ Digital Advisor to further simplify your upgrade experience. Upgrade Advisor provides intelligence that helps you minimize uncertainty and risk by assessing your system and creating an upgrade plan specific to your configuration.  

You can use this information to upgrade on-premises ONTAP.  For information about upgrading ONTAP in the cloud, see link:https://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html[Upgrading Cloud Volumes ONTAP software].

// 2023 Jul 25, Jira 1183
// BURT 1448684, 10 JAN 2022
