---
permalink: upgrade/index.html
sidebar: sidebar
keywords: upgrade, ontap, prepare, before, 
summary: 'Should I upgrade or update ONTAP, ONTAP in the cloud or ONTAP select?'
---
= ONTAP upgrade overview
:icons: font
:imagesdir: ../media/

[.lead]

When you upgrade your ONTAP software, you can take advantage of new and enhanced features and functionality that can help you reduce costs, accelerate critical workloads, and expand the scope of data protection available to your organization. 

A major ONTAP upgrade consists of moving from a lower to higher ONTAP numbered release. An example would be an upgrade of your cluster from ONTAP 9.8 to ONTAP 9.12.1.  A minor (or patch) upgrade consists of moving from a lower ONTAP version to a higher ONTAP version within the same numbered release. An example would be an upgrade of your cluster from ONTAP 9.12.1P1 to 9.12.1P4. 

Before you upgrade, you should link:prepare.html[prepare for the upgrade]. If you have an active SupportEdge contract for Active IQ Digital Advisor, link:create-upgrade-plan.html#plan-your-upgrade-with-upgrade-advisor[plan your upgrade with Upgrade Advisor]. Upgrade Advisor provides intelligence that helps you minimize uncertainty and risk by assessing your cluster and creating an upgrade plan specific to your configuration. 

After you prepare for your upgrade, it is recommended that you perform your major or minor upgrade using link:task_upgrade_andu_sm.html[Automated Non-Disruptive Upgrade (ANDU) from with System Manager].  ANDU takes advantage of ONTAP’s high-availability (HA) failover technology to ensure that clusters continue to serve data without interruption during the upgrade. 

[NOTE]
Beginning with ONTAP 9.12.1, System Manager is fully integrated with BlueXP. If BlueXP is configured on your system, you can upgrade through the BlueXP working environment.

If you want assistance upgrading your ONTAP software, a link:https://www.netapp.com/pdf.html?item=/media/19393-netapp-managed-upgrade-service-description.pdf[Managed Upgrade] is offered through NetApp Professional Services.  The Managed Upgrade Service and other levels of upgrade support are also available to clusters covered by certain link:https://www.netapp.com/services/support/supportedge/[SupportEdge Services].

Use this information to upgrade on-premises ONTAP.  For information about upgrading ONTAP in the cloud, see link:https://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html[Upgrading Cloud Volumes ONTAP software].


// 2023 Aug 10, Jira 1259
// 2023 Aug 07, Jira 1183
// BURT 1448684, 10 JAN 2022
