---
permalink: upgrade/index.html
sidebar: sidebar
keywords: upgrade overview, upgrade, digital advisor, summary, upgrade ontap, upgrading ontap, upgrade, upgrading, ontap, software, on-premise, prepare, preparation, major upgrade, minor upgrade, patch upgrade, upgrade assistance, upgrade help, upgrade technical support
summary: "An ONTAP upgrade allows you to take advantage of new and enhanced features. Follow recommended steps to prepare for your upgrade before you begin."
---
= Learn about ONTAP upgrade
:icons: font
:imagesdir: ../media/

[.lead]
When you upgrade your ONTAP software, you can take advantage of new and enhanced ONTAP features that can help you reduce costs, accelerate critical workloads, improve security, and expand the scope of data protection available to your organization.  

A major ONTAP upgrade consists of moving from a lower to higher ONTAP numbered release. An example would be an upgrade of your cluster from ONTAP 9.8 to ONTAP 9.12.1. A minor (or patch) upgrade consists of moving from a lower ONTAP version to a higher ONTAP version within the same numbered release. An example would be an upgrade of your cluster from ONTAP 9.12.1P1 to 9.12.1P4.  

To get started, you should prepare for the upgrade. If you have an active SupportEdge contract for Active IQ Digital Advisor (also known as Digital Advisor), you should link:create-upgrade-plan.html[prepare to upgrade with Upgrade Advisor]. Upgrade Advisor provides intelligence that helps you minimize uncertainty and risk by assessing your cluster and creating an upgrade plan specific to your configuration. If you don't have an active SupportEdge contract for Active IQ Digital Advisor, you should link:prepare.html[prepare to upgrade without Upgrade Advisor]. 

After you prepare for your upgrade, it is recommended that you perform upgrades using link:task_upgrade_andu_sm.html[automated non-disruptive upgrade (ANDU) from System Manager]. ANDU takes advantage of ONTAP's high-availability (HA) failover technology to ensure that clusters continue to serve data without interruption during the upgrade. 

[NOTE]
Beginning with ONTAP 9.12.1, System Manager is fully integrated with BlueXP. If BlueXP is configured on your system, you can upgrade through the BlueXP working environment.

If you want assistance upgrading your ONTAP software, NetApp Professional Services offers a link:https://www.netapp.com/pdf.html?item=/media/8144-sd-managed-upgrade-service.pdf[Managed Upgrade Service^]. If you are interested in using this service, contact your NetApp sales representative or link:https://www.netapp.com/forms/sales-contact/[submit NetApp's sales inquiry form^]. The Managed Upgrade Service as well as other types of upgrade support are available to customers with link:https://www.netapp.com/pdf.html?item=/media/8845-supportedge-expert-service.pdf[SupportEdge Expert Services^] at no additional cost.

.Related information

* link:concept_upgrade_paths.html[Supported upgrade paths]

// 2025-2-11, GH-1642
// 2024-Dec-17, ONTAPDOC-2606
// 2024 Dec 03 ONTAPDOC-2497
// 2023 Sept 6, ONTAPDOC-1333
// 2023 Aug 30, ONTAPDOC-1257
// 2023 Aug 10, Jira 1259
// 2023 Aug 07, Jira 1183
// BURT 1448684, 10 JAN 2022
