---
permalink: upgrade/prepare.html
sidebar: sidebar
keywords: upgrade, ontap, prepare, digital advisor, preparation, before you upgrade, plan, upgrade overview, upgrade summary
summary: 'Preparing for an ONTAP upgrade helps you identify and mitigate upgrade risks or blockers and account for special considerations applicable to your configuration.'
---
= Prepare for an ONTAP software upgrade without Upgrade Advisor
:icons: font
:imagesdir: ../media/

[.lead]
Properly preparing for an ONTAP software upgrade helps you identify and mitigate potential upgrade risks or blockers before you begin the upgrade process. During upgrade preparation, you can also identify any special considerations you might need to account for before you upgrade. For example, if SSL FIPs mode is enabled on your cluster and the administrator accounts use SSH public keys for authentication, you need to verify that the host key algorithm is supported in your target ONTAP release.  

If you have an active SupportEdge contract for link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html[Digital Advisor^], link:create-upgrade-plan.html[plan your upgrade with Upgrade Advisor]. If you do not have access to Active IQ Digital Advisor (also known as Digital Advisor), you should do the following to prepare for an ONTAP upgrade.

. link:choose-target-version.html[Choose your target ONTAP release].

. Review the upgrade cautions and the known problems and limitations listed in the link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508 [ONTAP 9 Release Notes] for your target release.
+
The upgrade cautions describe potential issues that you should be aware of before upgrading. The known problems and limitations describe potentially unexpected system behavior that you might experience after upgrading.
+
You must sign in with your NetApp account or create an account to access the Release Notes

. link:confirm-configuration.html[Confirm ONTAP support for your hardware configuration].
+
Your hardware platform, cluster management switches and MetroCluster IP switches must support the target release.  If your cluster is configured for SAN, the SAN configuration must be fully supported. 

. link:task_check_for_common_configuration_errors_using_config_advisor.html[Use Active IQ Config Advisor to verify that you have no common configuration errors.]

. Review the supported ONTAP link:concept_upgrade_paths.html#supported-upgrade-paths[upgrade paths] to determine if you can perform a direct upgrade or if you need to complete the upgrade in stages.

. link:task_verifying_the_lif_failover_configuration.html[Verify your LIF failover configuration].
+
Before you perform an upgrade, you need to verify that the cluster's failover policies and failover groups are configured correctly.

. link:concept_verify_svm_routing.html[Verify your SVM routing configuration].

. link:special-considerations.html[Verify special considerations] for your cluster.
+
If certain configurations exist on your cluster, there are specific actions you need to take before you begin an ONTAP software upgrade.

. link:reboot-sp-bmc.html[Reboot the SP or BMC].

// 2025 Feb 11, Git Issue 1643
// 2023 Dec 12, ONTAPDOC 1275
// 2023 Aug 30, ONTAPDOC-1257
// 2023 Aug 28, Jira 1258