---
permalink: upgrade/prepare.html
sidebar: sidebar
keywords: upgrade, ontap, prepare, preparation, before you upgrade, plan
summary: 'Prepare for an ONTAP software upgrade'
---

= Prepare for an ONTAP upgrade
:icons: font
:imagesdir: ../media/

[.lead]

Properly preparing for an ONTAP upgrade helps create a smooth upgrade process by identifying and mitigating potential risks and blockers in advance.

. link:choose-target-version.html[Choose your target ONTAP release].

. Review the link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP release notes^] for the target release.
+
The “Upgrade cautions” section describes potential issues that you should be aware of before upgrading to the new release. The “New and changed features” and “Known problems and limitations” sections describe new system behavior after upgrading to the new release.

. link:confirm-configuration.html[Confirm that your configuration can support the target release].
+
Your hardware platform, cluster management switches and MetroCluster IP switches must support the target release.  Also, if your cluster is configured for SAN, the SAN configuration must be fully supported. 

. link:task_check_for_common_configuration_errors_using_config_advisor.html[Use Active IQ Config Advisor to verify that you have not common configuration errors.]

. Review the link:concept_upgrade_paths.html#supported-upgrade-paths-for-on-premises-ontap-and-ontap-select[supported ONTAP upgrade paths] to determine if you can perform a direct upgrade or if you must complete the upgrade in stages.

. If you have an active SupportEdge contract for Active IQ Digital Advisor, link:create-upgrade-plan.html[plan your upgrade with Upgrade Advisor].
+
If you do not have access to Active IQ Digital Advisor, create your own upgrade plan.

. link:concept_verify_svm_routing.html[Verify SVM routing].

. link:special-considerations.html[Verify special considerations] for your cluster.

. link:concept_how_firmware_is_updated_during_upgrade.html[Reboot SP or BMC]


.Related information

* link:https://mysupport.netapp.com/site/info/version-support[Software version support]

// 2023 Jul 25, Jira 1183