---
permalink: upgrade/remove-ems-lif-service-task.html
sidebar: sidebar
keywords: ontap, upgrade, after, post, ems, event, management, system, lifs, messages, not, delivered
summary: 'After upgrading from ONTAP 9.7 or earlier to 9.8 or later, if you are using EMS, you might need to remove the EMS LIF service from certain network service polices.'
---
= Remove EMS LIF service from network service policies after an ONTAP upgrade
:icons: font
:imagesdir: ../media/

[.lead]
If you have Event Management System (EMS) messages set up before you upgrade from ONTAP 9.7 or earlier to ONTAP 9.8 or later, after the upgrade, your EMS messages might not be delivered.  

During the upgrade, management-ems, which is the EMS LIF service, is added to all existing service polices.  This allows EMS messages to be sent from any of the LIFs associated with any of the service polices.  If the selected LIF does not have reachability to the event notification destination, the message is not delivered. 

To prevent this, after the upgrade, you should remove the EMS LIF service from the network service polices that do not provide reachability to the destination.

.Steps

. Identify the LIFs and associated network service polices through which EMS messages can be sent:
+
[source,cli]
----
network interface show -fields service-policy -services management-ems
----
+
----
vserver        lif            service-policy
-------------- ------------ ------------------
cluster-1      cluster_mgmt 
                                      default-management
cluster-1      node1-mgmt
                                      default-management
cluster-1      node2-mgmt
                                      default-management
cluster-1      inter_cluster
                                      default-intercluster
4 entries were displayed.
----

. Check each LIF for connectivity to the EMS destination:
+
[source,cli]
----
network ping -lif <lif_name> -vserver <svm_name> -destination <destination_address>
----
+
Perform this on each node.
+
.Examples
+
----
cluster-1::> network ping -lif node1-mgmt -vserver cluster-1 -destination 10.10.10.10
10.10.10.10 is alive 

cluster-1::> network ping -lif inter_cluster -vserver cluster-1 -destination 10.10.10.10
no answer from 10.10.10.10
----

. Enter advanced privilege level:
+
[source,cli]
----
set advanced
----

. For the LIFs that do not have reachability, remove the management-ems LIF service from the corresponding service polices:
+
[source,cli]
----
network interface service-policy remove-service -vserver <svm_name> -policy <service_policy_name> -service management-ems
----

. Verify that the management-ems LIF is now only associated with the LIFs that provide reachability to the EMS destination:
+
[source,cli]
----
network interface show -fields service-policy -services management-ems
----

.Related Links

link:https://docs.netapp.com/us-en/ontap/networking/lifs_and_service_policies96.html#service-policies-for-system-svms.[LIFs and service polices in ONTAP 9.6 and later]

// 2025-Jan-3, ONTAPDOC-2606
// 2024-7-9 ontapdoc-2192
// 2023 Dec 12, ONTAPDOC 1275
// 2023 Aug 30, ONTAPDOC 1257