---
sidebar: sidebar
permalink: upgrade/resume-upgrade-after-andu-error.html
keywords: netapp, ontap, automate, automatic, automated, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu
summary: You can nondisruptively update the version of ONTAP on your cluster.
---

= Resume ONTAP software upgrade after an error in the automated upgrade process
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

If an automated ONTAP software upgrade pauses because of an error, you should resolve the error and then continue the upgrade.  After the error is resolved, you can choose to continue the automated upgrade process or you can cancel it and complete the upgrade process manually. If you choose to continue the automated upgrade, do not perform any of the upgrade steps manually.

.Steps


// start tabbed area

[role="tabbed-block"]
====
.System Manager
--

. Depending on the ONTAP version that you are running, perform one of the following steps:
+

|===

h| If you are running... h| Then...

a| ONTAP 9.8 or later
a| Click *Cluster* > *Overview*

a| ONTAP 9.7, 9.6, or 9.5
a| Click *Configuration* > *Cluster* > *Update*.

a| ONTAP 9.4 or earlier
a| * Click *Configuration* > *Cluster Update*.
* Then in the right corner of the *Overview* pane, click the three blue vertical dots, and *ONTAP Update*.

|===

. Continue the automated upgrade or cancel it and continue manually.
+

|===

h| If you want to... h| Then...

a|
Resume the automated upgrade
a|
Click *Resume*.
a|
Cancel the automated upgrade and continue manually
a|
Click *Cancel*.
|===
--

.CLI
--

. View the upgrade error:
+
[source, cli]
----
cluster image show-update-progress
----
. Resolve the error.

. Resume the update:
+
|===

h| If you want to... h| Enter the following command...

a| Resume the automated upgrade
a|
[source, cli]
----
cluster image resume-update
----

a| Cancel the automated upgrade and continue manually

a| 
[source, cli]
----
cluster image cancel-update
----
|===

--

====
// end tabbed area

.After you finish

link:task_what_to_do_after_upgrade.html[Perform post-upgrade checks].

// 2023 Oct 13, Jira 1415
