---
permalink: upgrade/snapmirror-cascade-relationship-blocked.html
sidebar: sidebar
keywords: ontap, upgrade, 9.9.1. 9.10.1, update, cascade, LTR, long term retention, snapshots, considerations, secondary storage
summary: "If you have a SnapMirror cascade relationship configured on your cluster, you might need to disable long-term retention (LTR) snapshots before you upgrade"
---
= Disable long-term retention snapshots before ONTAP upgrade
:icons: font
:imagesdir: ../media/

[.lead]
In a relationship of cascaded volumes, long-term retention (LTR) snapshots are supported only on the final SnapMirror destination volume of the cascade in all versions of ONTAP 9. Enabling LTR snapshots on any middle volume in the cascade results in missed backups and snapshots. 

Learn more about link:../data-protection/long-term-retention-snapshots-concept.html[long-term retention snapshots^].

If you have an unsupported configuration in which LTR snapshots have been enabled on any middle volume of a cascade, contact technical support and reference link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/Cascading_a_volume_with_Long-Term_Retention_(LTR)_snapshots_enabled_is_not_supported[Knowledge Base article Cascading a volume with Long-Term Retention (LTR) snapshots enabled is not supported^] for assistance.

The following ONTAP versions do not allow you to enable LTR snapshots on any volume in a cascade except the final SnapMirror destination volume.  

* 9.15.1 and later
* 9.14.1P2 and P4-P14
* 9.13.1P9-P17
* 9.12.1 P12-P19
* 9.11.1P15-P20
* 9.10.1P18-P20
* 9.9.1P20

Before upgrading from an ONTAP version that allows you to enable LTR snapshots on middle volumes of a cascade to an ONTAP version that blocks it, you need to disable LTR snapshots to avoid missed backups and snapshots.

You need to take action in the following scenarios:

* Long-Term Retention (LTR) snapshots are configured on the "B" volume in an "A > B > C" SnapMirror cascade or on another middle SnapMirror destination volume in your larger cascade. 
* LTR snapshots are defined by a schedule applied to a SnapMirror policy rule. This rule does not replicate snapshots from the source volume but creates them directly on the destination volume. 
+
NOTE: For more information on schedules and SnapMirror policies, see the Knowledge Base article https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_does_the_schedule_parameter_in_an_ONTAP_9_SnapMirror_policy_rule_work[How does the "schedule" parameter in an ONTAP 9 SnapMirror policy rule work?^].

.Steps

. Remove the LTR rule from the SnapMirror policy on the middle volume of the cascade:
+
----
Secondary::> snapmirror policy remove-rule -vserver <> -policy <> -snapmirror-label <>
----
+
Learn more about `snapmirror policy remove-rule` in the link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-remove-rule.html[ONTAP command reference^].

. Add the rule again for the SnapMirror label without the LTR schedule:
+
----
Secondary::> snapmirror policy add-rule -vserver <> -policy <> -snapmirror-label <> -keep <>
----
+
NOTE: Removing LTR snapshots from the SnapMirror policy rules means SnapMirror will pull the snapshots with the given label from the source volume. You might also need to add or modify a schedule on the source volume's snapshot policy to create properly labeled snapshots.

+
Learn more about `snapmirror policy add-rule` in the link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html[ONTAP command reference^].

. If necessary, modify (or create) a schedule on the source volume snapshot policy to allow snapshots to be created with a SnapMirror label:
+
----
Primary::> volume snapshot policy modify-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <>
----
+
----
Primary::> volume snapshot policy add-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <> -count <>
----

NOTE: LTR snapshots can still be enabled on the final SnapMirror destination volume within a SnapMirror cascade configuration.


// 2025-Oct-6, ONTAPDOC-3355
// 2025 July 24, ONTAPDOC-2960
// 2024-July 1, ONTAPDOC-2127