---
permalink: upgrade/task_check_for_common_configuration_errors_using_config_advisor.html
sidebar: sidebar
keywords: upgrade, common, configuration, errors, check, config, advisor, before upgrade, before upgrading
summary: 'You can use the Active IQ Config Advisor tool to check for common configuration errors.'
---
= Identify configuration errors with Active IQ Config Advisor
:icons: font
:imagesdir: ../media/

[.lead]
Before you upgrade ONTAP, you can use the Active IQ Config Advisor tool to check for common configuration errors.

Active IQ Config Advisor is a configuration validation tool for NetApp systems. It can be deployed at both secure sites and nonsecure sites for data collection and system analysis.

NOTE: Support for Active IQ Config Advisor is limited and is available only online.

.Steps

. Log in to the link:https://mysupport.netapp.com/site/global/[NetApp Support Site^], and then click *TOOLS* > *Tools*.
. Under *Active IQ Config Advisor*, click https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Download App^].
. Download, install, and run Active IQ Config Advisor.
. After running Active IQ Config Advisor, review the tool's output, and follow the recommendations that are provided to address any issues discovered by the tool.

// 2023 Aug 30, ONTAPDOC-1257
// 2022 Apr, 25, BURT 1454366
