---
permalink: upgrade/task_verifying_the_san_configuration.html
sidebar: sidebar
keywords: ontap, upgrade, verify, verifying, san, configuration
summary: 'Upgrading in a SAN environment changes which paths are direct. Therefore, before performing an upgrade, you should verify that each host is configured with the correct number of direct and indirect paths, and that each host is connected to the correct LIFs.'
---
= Verify SAN host configuration before an ONTAP upgrade
:icons: font
:imagesdir: ../media/

[.lead]
Upgrading ONTAP in a SAN environment changes which paths are direct. Before you upgrade a SAN cluster, you should verify that each host is configured with the correct number of direct and indirect paths, and that each host is connected to the correct LIFs. 

.Steps

. On each host, verify that a sufficient number of direct and indirect paths are configured, and that each path is active.
+
Each host must have a path to each node in the cluster.

. Verify that each host is connected to a LIF on each node.
+
You should record the list of initiators for comparison after the upgrade.
+
[cols=2*,options="header"]
|===
| For...| Enter...
a|
iSCSI
a|
`iscsi initiator show -fields igroup,initiator-name,tpgroup`
a|
FC
a|
`fcp initiator show -fields igroup,wwpn,lif`
|===

// 2023 Aug 07, Jira 1183
