---
permalink: upgrade/task_verifying_that_the_netgroup_file_is_present_on_all_nodes.html
sidebar: sidebar
keywords: ontap, upgrade, verifying, verify, netgroup file, present, nodes
summary: 'If you have loaded netgroups into storage virtual machines \(SVMs\), before you upgrade or revert, you must verify that the netgroup file is present on each node. A missing netgroup file on a node can cause an upgrade or revert to fail.'
---
= Verifying that the netgroup file is present on all nodes
:icons: font
:imagesdir: ../media/

[.lead]
If you have loaded netgroups into storage virtual machines (SVMs), before you upgrade or revert, you must verify that the netgroup file is present on each node. A missing netgroup file on a node can cause an upgrade or revert to fail.

The _NFS Reference_ contains more information about netgroups and loading them from a URI.

. Set the privilege level to advanced: `set -privilege advanced`
. Display the netgroup status for each SVM: `vserver services netgroup status`
. Verify that for each SVM, each node shows the same netgroup file hash value: `vserver services name-service netgroup status`
+
If this is the case, you can skip the next step and proceed with the upgrade or revert. Otherwise, proceed to the next step.

. On any one node of the cluster, manually load the netgroup file: `vserver services netgroup load -vserver vserver_name -source uri`
+
This command downloads the netgroup file on all nodes. If a netgroup file already exists on a node, it is overwritten.

*Related information*

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-nfs/home.html[NFS management]
