---
permalink: upgrade/task_verify_cluster_after_upgrade.html
sidebar: sidebar
keywords: ontap, upgrade, upgrade, verify, status, health, post, after
summary: 'After you upgrade you should verify your cluster.'
---
= Post-upgrade cluster verification
:icons: font
:imagesdir: ../media/

[.lead]
After you upgrade, you should verify your cluster version, cluster health, and storage health.

.Before you begin

NOTE: If you are using a MetroCluster FC configuration, you also need to verify that the cluster is enabled for automatic unplanned switchover.

== Verify cluster version

After all of the HA pairs have been upgraded, you must use the version command to verify that all of the nodes are running the target release.

The cluster version is the lowest version of ONTAP running on any node in the cluster. If the cluster version is not the target ONTAP release, you can upgrade your cluster.

. Verify that the cluster version is the target ONTAP release:
+
`version`
. If the cluster version is not the target ONTAP release, you can verify the upgrade status of all nodes:
+
`system node upgrade-revert show`

== Verify cluster health
:icons: font
:imagesdir: ../media/

After you upgrade a cluster, you should verify that the nodes are healthy and eligible to participate in the cluster, and that the cluster is in quorum.

. Verify that the nodes in the cluster are online and are eligible to participate in the cluster:
+
`cluster show`
+
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node0                 true    true
node1                 true    true
----
+
If any node is unhealthy or ineligible, check EMS logs for errors and take corrective action.

. Set the privilege level to advanced:
+
`set -privilege advanced`
+
Enter "`y`" to continue.

. Verify the configuration details for each RDB process.
 ** The relational database epoch and database epochs should match for each node.
 ** The per-ring quorum master should be the same for all nodes.
+
Note that each ring might have a different quorum master.

+

|===

h| To display this RDB process... h| Enter this command...

a|
Management application
a|
`cluster ring show -unitname mgmt`
a|
Volume location database
a|
`cluster ring show -unitname vldb`
a|
Virtual-Interface manager
a|
`cluster ring show -unitname vifmgr`
a|
SAN management daemon
a|
`cluster ring show -unitname bcomd`
|===

+
This example shows the volume location database process:

+
----
cluster1::*> cluster ring show -unitname vldb
Node      UnitName Epoch    DB Epoch DB Trnxs Master    Online
--------- -------- -------- -------- -------- --------- ---------
node0     vldb     154      154      14847    node0     master
node1     vldb     154      154      14847    node0     secondary
node2     vldb     154      154      14847    node0     secondary
node3     vldb     154      154      14847    node0     secondary
4 entries were displayed.
----

. If you are operating in a SAN environment, verify that each node is in a SAN quorum: `event log show  -severity informational -message-name scsiblade.*`
+
The most recent scsiblade event message for each node should indicate that the scsi-blade is in quorum.
+
----
cluster1::*> event log show  -severity informational -message-name scsiblade.*
Time             Node       Severity       Event
---------------  ---------- -------------- ---------------------------
MM/DD/YYYY TIME  node0      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
MM/DD/YYYY TIME  node1      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
----


.Related information

link:../system-admin/index.html[System administration]

== Verify that automatic unplanned switchover is enabled

After you upgrade a cluster, you should verify that automatic unplanned switchover is enabled.

.About this task

NOTE: This procedure is performed only for MetroCluster FC configurations.  If you are using a MetroCluster IP configuration, skip this procedure.

.Steps

. Check whether automatic unplanned switchover is enabled:
+
`metrocluster show`
+
If automatic unplanned switchover is enabled, the following statement appears in the command output:
+
----
AUSO Failure Domain  auso-on-cluster-disaster
----

. If the statement does not appear, enable an automatic unplanned switchover:
+
`metrocluster modify -auto-switchover-failure-domain auso-on-cluster-disaster`

. Verify that an automatic unplanned switchover has been enabled by repeating Step 1.

// BURT 1387815, 21 FEB 2022

== Verify storage health

After you upgrade a cluster, you should verify the status of your disks, aggregates, and volumes.

. Verify disk status:
+

|===

h| To check for... h| Do this...

a|
Broken disks
a|

.. Display any broken disks:
+
`storage disk show -state broken`
.. Remove or replace any broken disks.

a|
Disks undergoing maintenance or reconstruction
a|

.. Display any disks in maintenance, pending, or reconstructing states:
+
`storage disk show -state maintenance\|pending\|reconstructing`
.. Wait for the maintenance or reconstruction operation to finish before proceeding.

+
|===

. Verify that all aggregates are online by displaying the state of physical and logical storage, including storage aggregates:
+
`storage aggregate show -state !online`
+
This command displays the aggregates that are _not_ online. All aggregates must be online before and after performing a major upgrade or reversion.
+
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----

. Verify that all volumes are online by displaying any volumes that are _not_ online:
+
`volume show -state !online`
+
All volumes must be online before and after performing a major upgrade or reversion.
+
----
cluster1::> volume show -state !online
There are no entries matching your query.
----

. Verify that there are no inconsistent volumes:
+
`volume show -is-inconsistent true`
+
See the Knowledge Base article link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Volume_Showing_WAFL_Inconsistent[Volume Showing WAFL Inconsistent] on how to address the inconsistent volumes.

.Related information

link:../disks-aggregates/index.html[Disk and aggregate management]

// 2022-04-25, BURT 1454366
// BURT 1387815, 21 FEB 2022
// 2022-06-27, Jira KDA-1528
