---
permalink: upgrade/task_reviewing_pre_update_resources.html
sidebar: sidebar
keywords: ontap, upgrade, resources, review, before
summary: 'Before updating the ONTAP software, you should review resources to understand issues you must resolve, understand new system behavior in the target release, and confirm hardware support.'
---
= Resources to read before you upgrade
:icons: font
:imagesdir: ../media/

[.lead]
If you don't use link:https://aiq.netapp.com/[Active IQ^] Upgrade Advisor, you need to review a number of NetApp resources before upgrading your ONTAP software.  These resources will help you understand issues you must resolve, new system behavior in the target release, and confirm hardware support.

. Review the _Release Notes_ for the target release.
+
https://library.netapp.com/ecmdocs/ECMLP2492508/html/frameset.html[ONTAP 9 Release Notes]
+
The "`Important cautions`" section describes potential issues that you should be aware of before upgrading to the new release. The "`New and changed features`" and "`Known problems and limitations`" sections describe new system behavior after upgrading to the new release.

. Confirm that your hardware platform is supported in the target release.
+
https://hwu.netapp.com[NetApp Hardware Universe^]

. Confirm that your cluster and management switches are supported in the target release.
+
You can upgrade in a transitional state, but ultimately your NX-OS (cluster network switches), IOS (management network switches), and reference configuration file (RCF) software versions should be compatible with the version of ONTAP to which you are upgrading.
//BURT 1381609; 2021-May-26
+
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]

. If your cluster and management switches do not have the minimum software versions for the target ONTAP release, upgrade to supported software versions.
+
http://mysupport.netapp.com/NOW/download/software/cm_switches/[NetApp Downloads: Cisco Ethernet Switch]
+
http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/[NetApp Downloads: NetApp Ethernet Switch]

. If your cluster is configured for SAN, confirm that the SAN configuration is fully supported.
+
All SAN components--including the target ONTAP software version, host OS and patches, required Host Utilities software, multipathing software, and adapter drivers and firmware--should be supported.
+
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]

. If you are transitioning from 7-Mode using the 7-Mode Transition Tool, confirm that the tool supports transition to the ONTAP version to which you are upgrading.
+
All the projects in the tool must be in the completed or aborted state before you upgrade the 7-Mode Transition Tool that supports the ONTAP version to which you are upgrading.
+
link:https://docs.netapp.com/us-en/ontap-7mode-transition/install-admin/index.html[7-Mode Transition Tool installation and administration]
