---
permalink: upgrade/task_preparing_snapmirror_relationships_for_a_nondisruptive_upgrade_or_downgrade.html
sidebar: sidebar
keywords: ontap, upgrade, snapmirror, operations, quisce
summary: 'Before upgrading ONTAP, you need to quiesced SnapMirror operations and each peered SVM must have a unique name across the clusters'
---
= Quiesce SnapMirror DP operations before upgrading ONTAP
:icons: font
:imagesdir: ../media/

[.lead]

Before you upgrade ONTAP on a cluster with SnapMirror data protection (DP), SnapMirror operations must be quiesced for each node that contains destination volumes, and each peered SVM must have a unique name across the clusters. It is best practice to use a unique fully qualified domain name (FQDN) for each SVM, for example, "`dataVerser.HQ`" or "`mirrorVserver.Offsite`". 

[NOTE]
SnapMirror operations do not need to be quiesced for clusters with SnapMirror extended data protection (XDP).

To prevent SnapMirror transfers from failing, you must quiesce SnapMirror operations before you upgrade ONTAP. Alternatively, you can quiesce SnapMirror transfers on a particular destination volume and upgrade the owning destination node before upgrading source nodes so the SnapMirror transfers for all other destination volumes can continue. The following table describes the two options for suspending SnapMirror operations.

[cols=3*,options="header"]
|===
| Option| Description| Upgrade destination nodes before source nodes?
a|
Suspend SnapMirror operations for the duration of the NDU (nondisruptive upgrade).
a|
The simplest method for upgrading in a SnapMirror environment is to suspend all SnapMirror operations, perform the upgrade, and then resume the SnapMirror operations. However, no SnapMirror transfers will occur during the entire NDU. You must use this method if your cluster contains nodes that are mirroring volumes to each other.
a|
No, the nodes can be upgraded in any order.
a|
Suspend SnapMirror operations one destination volume at a time.
a|
You can suspend SnapMirror transfers for a particular destination volume, upgrade the node (or HA pair) that contains the destination volume, upgrade the node (or HA pair) that contains the source volume, and then resume the SnapMirror transfers for the destination volume. By using this method, SnapMirror transfers for all other destination volumes can continue while the nodes that contain the original destination and source volumes are upgraded.
a|
Yes.
|===

.Steps

. Determine the destination path for each SnapMirror relationship:
+
[source,cli]
----
snapmirror show
----

. For each destination volume, suspend future SnapMirror transfers: 
+
[source,cli]
----
snapmirror quiesce -destination-path destination
----
+
If there are no active transfers for the SnapMirror relationship, this command sets its status to "Quiesced". If the relationship has active transfers, the status is set to "Quiescing" until the transfer is completed, and then the status becomes "Quiesced".
+
This example quiesces transfers involving the destination volume "vol1" from "SVMvs0.example.com":
+
----
cluster1::> snapmirror quiesce -destination-path vs0.example.com:vol1
----

. Verify that all SnapMirror relationships are quiesced: 
+
[source,cli]
snapmirror show -status !Quiesced
+
This command displays any SnapMirror relationships that are _not_ quiesced.
+
This example shows that all SnapMirror relationships are quiesced:
+
----
cluster1::> snapmirror show -status !Quiesced
There are no entries matching your query.
----

. If any SnapMirror relationships are currently being transferred, do one of the following options:
+
[cols=2*,options="header"]
|===
| Option| Description
a|
Wait for the transfers to finish before performing the ONTAP upgrade.
a|
After each transfer finishes, the relationship changes to "Quiesced" status.
a|
Stop the transfers: 

`snapmirror abort -destination-path destination -h`    

*Note:* You must use the `-foreground true` parameter if you are terminating load-sharing mirror transfers.
a|
This command stops the SnapMirror transfer and restores the destination volume to the last Snapshot copy that was successfully transferred. The relationship is set to "Quiesced" status.
|===

// 2024 Jan 18, ONTAPDOC 1585
// 2023 Dec 12, ONTAPDOC 1275
// 2023 Aug 07, ONTAPDOC 1183
