---
permalink: upgrade/task-change-svm-42v-xattrs-option.html
sidebar: sidebar
keywords: ontap, upgrade, svm, xattr, nfsv4.2
summary: "Before you upgrade ONTAP 9.12.1 and later, ensure you give an explicit value for an NFSv4.2 extended attributes option to prevent NFS response errors."
---
= Assign an explicit value to the v4.2-xattrs option
:icons: font
:imagesdir: ../media/

[.lead]
If you have an NFSv4.2 client, before you upgrade from certain releases and patches of ONTAP 9.12.1 and later you need to give an explicit value for the NFSv4.2 extended attributes option to prevent NFS response errors after upgrade.

If the `v4.2-xattrs` option is never explicitly assigned a value before the ONTAP upgrade to affected versions, NFSv4.2 clients are not informed that the server's extended attributes option has changed. This causes NFS response errors to specific `xattrs` calls due to a client and server mismatch.

.Before you begin

You need to assign an explicit value for the NFSv4.2 extended attributes option if the following is true:

* You are using NFSv4.2 with an SVM created using ONTAP 9.11.1 or earlier
* You are upgrading ONTAP from any of these affected releases and patches:

** 9.12.1RC1 to 9.12.1P11
** 9.13.1RC1 to 9.13.1P8
** 9.14.1RC1 to 9.14.1P1

.About this task

You must be running ONTAP 9.12.1 or later to set the value using the command described in this procedure.

If `v4.2-xattrs` is already set to `enabled`, it should still be explicitly set to `enabled` to avoid future disruption. If you set `v4.2-xattrs` to disabled, NFSv4.2 clients can receive "invalid argument" responses until they are remounted or the `v4.2-xattrs` option is set to `enabled`.

.Steps

* Assign an explicit value to the `v4.2-xattrs` option: 
+
[source,cli]
----
nfs modify -v4.2-xattrs <enabled/disabled> -vserver <vserver_name>
----

.Related information

https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-Issues/CONTAP-120160[NFS v4.2-xattrs field getting flipped after upgrades^]

// 2024-Oct-1, ONTAPDOC-2408 and CONTAP-323592