---
permalink: upgrade/task_plan_with_upgrade_advisor.html
sidebar: sidebar
keywords: ontap, upgrade, plan, planning, upgrade advisor, advisor, active iq
summary: 'The Upgrade Advisor service in Active IQ Digital Advisor provides intelligence that helps you plan your upgrade and minimizes uncertainty and risk.'
---
= Plan your upgrade with Upgrade Advisor
:icons: font
:imagesdir: ../media/

[.lead]
The Upgrade Advisor service in link:https://aiq.netapp.com/[Active IQ Digital Advisor] provides intelligence that helps you plan your upgrade and minimizes uncertainty and risk.

Active IQ identifies issues in your environment that can be resolved by upgrading to a newer version of ONTAP. The Upgrade Advisor service helps you plan for a successful upgrade and provides a report of issues you might need to be aware of in the ONTAP version you're upgrading to.

NOTE: An active https://www.netapp.com/us/services/support-edge.aspx[SupportEdge Services] contract is required for Active IQ.

. https://aiq.netapp.com/[Launch Active IQ^]

. In Active IQ link:https://docs.netapp.com/us-en/active-iq/task_view_risk_and_take_action.html[view risks associated with your cluster and manually take corrective actions].
+
Risks included in the *SW Config Change*, *HW Config Change*, and *HW Replacement* categories must be resolved prior to performing an ONTAP upgrade.

. Review the recommended upgrade path and link:https://docs.netapp.com/us-en/active-iq/task_view_upgrade.html[generate your upgrade plan^].


// 2023 Jul 25, Jira 1183
//2023 June 14, Jira 1002