---
permalink: upgrade/task_preparing_all_load_sharing_mirrors_for_a_major_upgrade.html
sidebar: upgrade_sidebar
keywords: ontap, upgrade, prepare, preparing, load-sharing, load, sharing, mirrors
summary: 'Before performing a major upgrade from ONTAP 8.3, you should move all of the load-sharing mirror source volumes to an aggregate on the node that you will upgrade last. This ensures that load-sharing mirror destination volumes are the same or later versions of ONTAP.'
---
= Prepare all load-sharing mirrors for a major upgrade
:icons: font
:imagesdir: ../media/

[.lead]
Before performing a major upgrade from ONTAP 8.3, you should move all of the load-sharing mirror source volumes to an aggregate on the node that you will upgrade last. This ensures that load-sharing mirror destination volumes are the same or later versions of ONTAP.

. Record the locations of all load-sharing mirror source volumes.
+
Knowing where the load-sharing mirror source volumes came from helps facilitate returning them to their original locations after the major upgrade.

. Determine the node and aggregate to which you will move the load-sharing mirror source volumes.
. Move the load-sharing mirror source volumes to the node and aggregate by using the volume move start command.
