---
permalink: upgrade/task_verify_cluster_after_upgrade.html
sidebar: sidebar
keywords: ontap, upgrade, upgrade, verify, status, health, post, after
summary: 'After you upgrade you should verify your cluster.'
---
= Verify your cluster after ONTAP upgrade
:icons: font
:imagesdir: ../media/

[.lead]
After you upgrade ONTAP, you should verify your cluster version, cluster health, and storage health.  If your cluster is in a MetroCluster FC configuration, you also need to verify that the cluster is enabled for automatic unplanned switchover.


== Verify cluster version

After all the HA pairs have been upgraded, you must use the version command to verify that all of the nodes are running the target release.

The cluster version is the lowest version of ONTAP running on any node in the cluster. If the cluster version is not the target ONTAP release, you can upgrade your cluster.

. Verify that the cluster version is the target ONTAP release:
+
`version`
. If the cluster version is not the target ONTAP release, you should verify the upgrade status of all nodes:
+
`system node upgrade-revert show`

== Verify cluster health
:icons: font
:imagesdir: ../media/

After you upgrade a cluster, you should verify that the nodes are healthy and eligible to participate in the cluster, and that the cluster is in quorum.

. Verify that the nodes in the cluster are online and are eligible to participate in the cluster:
+
`cluster show`
+
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node0                 true    true
node1                 true    true
----
+
If any node is unhealthy or ineligible, check EMS logs for errors and take corrective action.

. Set the privilege level to advanced:
+
`set -privilege advanced`

. Verify the configuration details for each RDB process.
 ** The relational database epoch and database epochs should match for each node.
 ** The per-ring quorum master should be the same for all nodes.
+
Note that each ring might have a different quorum master.

+

|===

h| To display this RDB process... h| Enter this command...

a|
Management application
a|
`cluster ring show -unitname mgmt`
a|
Volume location database
a|
`cluster ring show -unitname vldb`
a|
Virtual-Interface manager
a|
`cluster ring show -unitname vifmgr`
a|
SAN management daemon
a|
`cluster ring show -unitname bcomd`
|===

+
This example shows the volume location database process:

+
----
cluster1::*> cluster ring show -unitname vldb
Node      UnitName Epoch    DB Epoch DB Trnxs Master    Online
--------- -------- -------- -------- -------- --------- ---------
node0     vldb     154      154      14847    node0     master
node1     vldb     154      154      14847    node0     secondary
node2     vldb     154      154      14847    node0     secondary
node3     vldb     154      154      14847    node0     secondary
4 entries were displayed.
----

. If you are operating in a SAN environment, verify that each node is in a SAN quorum: `cluster kernel-service show`
+
----
cluster1::*> cluster kernel-service show
Master            Cluster           Quorum        Availability  Operational
Node              Node              Status        Status        Status
----------------- ----------------- ------------- ------------- -------------
cluster1-01       cluster1-01       in-quorum     true          operational
                  cluster1-02       in-quorum     true          operational
2 entries were displayed.
----


.Related information

link:../system-admin/index.html[System administration]

== Verify automatic unplanned switchover is enabled (MetroCluster FC configurations only)

If your cluster is in a MetroCluster FC configuration, you should verify that automatic unplanned switchover is enabled after you upgrade ONTAP.

.About this task

NOTE: This procedure is performed only for MetroCluster FC configurations.  If you are using a MetroCluster IP configuration, skip this procedure.

.Steps

. Check whether automatic unplanned switchover is enabled:
+
`metrocluster show`
+
If automatic unplanned switchover is enabled, the following statement appears in the command output:
+
----
AUSO Failure Domain  auso-on-cluster-disaster
----

. If the statement does not appear, enable an automatic unplanned switchover:
+
`metrocluster modify -auto-switchover-failure-domain auso-on-cluster-disaster`

. Verify that an automatic unplanned switchover has been enabled by repeating Step 1.

// BURT 1387815, 21 FEB 2022


.Related information

link:../disks-aggregates/index.html[Disk and aggregate management]

// 2023 Aug 30, ONTAPDOC 1257
// 2023 Aug 30, ONTAPDOC-1287
// 2022-04-25, BURT 1454366
// BURT 1387815, 21 FEB 2022
// 2022-06-27, Jira KDA-1528
