---
permalink: upgrade/task_preparing_to_upgrade_nodes_using_netapp_storage_encryption_with_external_key_management_servers.html
sidebar: sidebar
keywords: ontap, upgrade, prepare, preparing, nodes, netapp, storage, encryption, nse, external, key management, servers
summary: 'If you are using NetApp Storage Encryption \(NSE\) on ONTAP 9.2 or earlier and upgrading to ONTAP 9.3 or later, you must use the command line interface \(CLI\) to delete any existing external key management \(KMIP\) server connections before performing the upgrade.'
---
= Delete existing external key management server connections before upgrading
:icons: font
:imagesdir: ../media/

[.lead]
If you are using NetApp Storage Encryption (NSE) on ONTAP 9.2 or earlier and upgrading to ONTAP 9.3 or later, you must use the command line interface (CLI) to delete any existing external key management (KMIP) server connections before performing the upgrade.

. Verify that the NSE drives are unlocked, open, and set to the default manufacture secure ID 0x0:
+
`storage encryption disk show -disk*`
. Enter the advanced privilege mode:
+
`set -privilege advanced`

. Use the default manufacture secure ID 0x0 to assign the FIPS key to the self-encrypting disks (SEDs): `storage encryption disk modify -fips-key-id 0x0 -disk *`
. Verify that assigning the FIPS key to all disks is complete: `storage encryption disk show-status`
. Verify that the *mode* for all disks is set to data: `storage encryption disk show`
. View the configured KMIP servers: `security key-manager show`
. Delete the configured KMIP servers: `security key-manager delete -address kmip_ip_address`
. Delete the external key manager configuration:``security key-manager delete-kmip-config``
+
NOTE: This step does not remove the NSE certificates.

After the upgrade is complete, you must reconfigure the KMIP server connections.

.Related information

xref:task_reconfiguring_kmip_servers_connections_after_upgrading_to_ontap_9_3_or_later.adoc[Reconfiguring KMIP server connections after upgrading to ONTAP 9.3 or later]
