---
permalink: upgrade/task_obtaining_ontap_software_images.html
sidebar: sidebar
keywords: 
summary: 'For ONTAP 9.4 and later, you can copy the ONTAP software image from the NetApp Support Site to a local folder. For upgrades from ONTAP 9.3 or earlier, you must copy the ONTAP software image to an HTTP server or FTP server on your network.'
---
= Obtaining ONTAP software images
:icons: font
:imagesdir: ../media/

[.lead]
For ONTAP 9.4 and later, you can copy the ONTAP software image from the NetApp Support Site to a local folder. For upgrades from ONTAP 9.3 or earlier, you must copy the ONTAP software image to an HTTP server or FTP server on your network.

To upgrade, revert, or downgrade the cluster to the target release of ONTAP, you require access to software images. Software images, firmware version information, and the latest firmware for your platform model are available on the NetApp Support Site. You should note the following important information:

* Software images are specific to platform models.
+
You must obtain the correct image for your cluster.

* Software images include the latest version of system firmware that was available when a given version of ONTAP was released.
* If you are upgrading a system with NetApp Volume Encryption to ONTAP 9.5 or later, you must download the ONTAP software image for non-restricted countries, which includes NetApp Volume Encryption.
+
If you use the ONTAP software image for restricted countries to upgrade a system with NetApp Volume Encryption, the system panics and you lose access to your volumes.

* If you are upgrading from ONTAP 9.3 to 9.7, you must copy the software image for ONTAP 9.5 and 9.7.

. Locate the target ONTAP software in the Software Downloads area of the NetApp Support Site.
. Copy the software image.
 ** For ONTAP 9.3 or earlier, copy the software image (for example, 93_q_image.tgz) from the NetApp Support Site to the directory on the HTTP server or FTP server from which the image will be served
 ** For ONTAP 9.4 or later, copy the software image (for example, 97_q_image.tgz) from the NetApp Support Site to the directory on the HTTP server or FTP server from which the image will be served or to a local folder.

*Related information*

http://mysupport.netapp.com/NOW/cgi-bin/software[NetApp Downloads: Software]
