---
permalink: upgrade/when-to-upgrade.html
sidebar: sidebar
keywords: upgrade, ontap
summary: 'Should I upgrade or update ONTAP, ONTAP in the cloud or ONTAP select?'
---
= When should I upgrade ONTAP?
:icons: font
:imagesdir: ../media/

[.lead]

You should upgrade your ONTAP software on a regular cadence. Upgrading ONTAP allows you to take advantage of new and enhanced features and functionality and implement current fixes for known issues.

== Major ONTAP upgrades

A major ONTAP upgrade or feature release typically includes:

** New ONTAP features
** Key infrastructure changes, such as fundamental changes to NetApp WAFL® operation or RAID operation
** File system changes that require following a specific upgrade process to move to the new release 
** Support for new NetApp-engineered hardware systems 
** Support for replacement hardware components such as newer network interface cards or host bus adapters

New ONTAP releases are entitled to full support for 3 years. NetApp recommends that you run the newest release for 1 year after general availability (GA) and then use the remaining time within the full support window to plan for your transition to a newer ONTAP release. 

== Minor (patch) ONTAP upgrades

Patch upgrades deliver timely fixes for critical bugs that cannot wait for the next major ONTAP feature release. Non-critical patch upgrades should be applied every 3-6 months. Critical patch upgrades should be applied as soon as possible.

== ONTAP release dates and support levels

Starting with the ONTAP 9.8 software release, NetApp delivers an ONTAP feature release two times per calendar year. Though plans are subject to change, the intent is to deliver new ONTAP releases in the second and fourth quarter of each calendar year. Use this information to plan the time frame of your upgrade to take advantage of the latest ONTAP release.

[cols="50,50"*,options="header"]
|===
| Version # | Release date
a|
9.13.1
a|
MAY 2023
a|
9.12.1
a|
FEBRUARY 2023
a|
9.11.1
a|
JULY 2022
a|
9.10.1
a|
JANUARY 2022
a|
9.9.1
a|
JUNE 2021
a|
9.8
a|
DECEMBER 2020
a|
9.7
a|
JANUARY 2019
2+a|
[NOTE]
If you are running a version prior to 9.7, it is likely to be on Limited Support or Self-Service Support. Please consider upgrading to versions with full support.
|===

[cols="20,10,10,10,10,10,10,10,10"*,options="header"]
|===
| Support level 3+|Full support 2+| Limited support 3+|Self-service support
a|
Year
a|
1
a|
2
a|
3
a|
4
a|
5
a|
6
a|
7
a|
8
a|
Access to online documentation
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Technical support
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|

a|

a|

a|
Root-cause analysis
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|

a|

a|

a|
Online software
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|

a|

a|

a|
Service updates (patch releases [P-releases])
a|
Yes
a|
Yes
a|
Yes
a|

a|

a|

a|

a|

a|
Alerts about vulnerabilities
a|
Yes
a|
Yes
a|
Yes
a|

a|

a|

a|

a|
|===

.Related information

* Learn link:https://review.docs.netapp.com/us-en/ontap_chandaj-hotfix-pocv2/whats-new.html[what's new in currently supported ONTAP releases^].
* Learn more about the link:https://mysupport.netapp.com/site/info/ontap-release-model[ONTAP release model].
* Learn more about link:https://mysupport.netapp.com/site/info/version-support[ONTAP software version support].

// 2023 Jul 25, Jira 1183
// BURT 1448684, 10 JAN 2022
