---
permalink: zero-trust-overview.html
sidebar: sidebar
keywords: zero trust, netapp, ontap, architect, data centric, fpolicy
summary: 'Zero Trust traditionally has been a network-centric approach of architecting micro core and perimeter (MCAP) to protect data, services, applications, or assets with controls known as a segmentation gateway.'
---

= NetApp and Zero Trust
:icons: font
:imagesdir: ../media/

[.lead]
Zero Trust traditionally has been a network-centric approach of architecting micro core and perimeter (MCAP) to protect data, services, applications, or assets with controls known as a segmentation gateway. NetApp ONTAP is taking a data-centric approach to Zero Trust in which the storage management system becomes the segmentation gateway to protect and monitor access of our customer's data. In particular, the FPolicy Zero Trust engine and the FPolicy partner ecosystem becomes a control center to gain a detailed understanding of normal and aberrant data access patterns and identify insider threats.

Data is the most important asset your organization has. Insider threats are the cause of 18% of data breaches, according to the 2022 https://enterprise.verizon.com/resources/reports/dbir/[Verizon Data Breach Investigations Report]. For example, the insiders https://www.washingtonpost.com/world/national-security/judge-to-sentence-bradley-manning-today/2013/08/20/85bee184-09d0-11e3-b87c-476db8ac34cd_story.html?utm_term=.b0b5f3a01aed[Chelsea (formerly Bradley) Manning] and https://www.washingtonpost.com/politics/intelligence-leaders-push-back-on-leakers-media/2013/06/09/fff80160-d122-11e2-a73e-826d299ff459_story.html?utm_term=.258cee25b1c7[Edward Snowden] leaked classified data, but they did not need to have access to that data to perform their jobs. So, who should be trusted? Nobody. Organizations need to ramp up their vigilance to DEFCON 1—but how? By deploying industry-leading Zero Trust controls around data with NetApp ONTAP data management software.

== What Is Zero Trust?

The Zero Trust model was first developed by https://www.brighttalk.com/webcast/10903/235239/how-to-enable-zero-trust-security-for-your-data-center[John Kindervag] at Forrester Research. It envisions network security from the inside-out rather than from the outside-in. The inside-out Zero Trust approach identifies a microcore and perimeter (MCAP). The MCAP is an interior definition of data, services, applications, and assets to be protected with a comprehensive set of controls. The concept of a secure outer perimeter is obsolete. Entities that are trusted and allowed to successfully authenticate through the perimeter can then make the organization vulnerable to attacks. Insiders, by definition, are already inside the secure perimeter. Employees, contractors, and partners are insiders, and they must be enabled to operate with appropriate controls for performing their roles within your organization’s infrastructure.

Although Zero Trust is over 10 years old, it has recently received a lot attention. Zero Trust was a central topic at the recent Black Hat and RSA security conferences.

Zero Trust was mentioned as a technology that offers promise to the DoD in September 2019 https://media.defense.gov/2019/Jul/12/2002156622/-1/-1/1/DOD-DIGITAL-MODERNIZATION-STRATEGY-2019.PDF[FY19-23 DoD Digital Modernization Strategy]. It defines Zero Trust as, “A cybersecurity strategy that embeds security throughout the architecture for the purpose of stopping data breaches. This data-centric security model eliminates the idea of trusted or untrusted networks, devices, personas, or processes and shifts to multi-attribute based confidence levels that enable authentication and authorization policies under the concept of least privileged access. Implementing zero trust requires rethinking how we utilize existing infrastructure to implement security by design in a simpler and more efficient way while enabling unimpeded operations.”

In August of 2020, the NIST published https://csrc.nist.gov/publications/detail/sp/800-207/final[Special Pub 800-207 Zero Trust Architecture] (ZTA). ZTA focuses on protecting resources, not network segments, because the network location is no longer seen as the prime component of the security posture of the resource. Resources are data and computing. ZTA strategies are for enterprise network architects. ZTA introduces some new terminology from the original Forrester concepts. Protection mechanisms called the policy decision point (PDP) and the policy enforcement point (PEP) are analogous to a Forrester segmentation gateway. ZTA introduces four deployment models:

* Device-agent or gateway-based deployment
* Enclave-based deployment (somewhat analogous to the Forrester MCAP)
* Resource portal-based deployment
* Device application sandboxing 

For the purposes of this technical report, we use Forrester Research concepts and terminology rather than the NIST ZTA.

== Security resources
For information about reporting vulnerabilities and incidents, NetApp security responses, and customer confidentiality, see the https://www.netapp.com/company/trust-center/security/[NetApp security portal].