---
permalink: zero-trust-learn-more.html
sidebar: sidebar
keywords: zero trust, ontap, learn, resource, reference
summary: 'Learn more about the information described in the ONTAP Zero Trust content.'
---
= Learn more about ONTAP Zero Trust content
:icons: font
:imagesdir: ../media/

[.lead]
To learn more about the information described in the ONTAP Zero Trust content, refer to the following documents and/or websites:

* Verizon Data Breach Investigations Report +
https://enterprise.verizon.com/resources/reports/dbir/
* Bradley Manning sentenced to 35 years in Wikileaks case +
https://www.washingtonpost.com/world/national-security/judge-to-sentence-bradley-manning-today/2013/08/20/85bee184-09d0-11e3-b87c-476db8ac34cd_story.html
* Edward Snowden comes forward as the source of NSA leaks +
https://www.washingtonpost.com/politics/intelligence-leaders-push-back-on-leakers-media/2013/06/09/fff80160-d122-11e2-a73e-826d299ff459_story.html
* DoD Digital Modernization Strategy +
https://media.defense.gov/2019/Jul/12/2002156622/-1/-1/1/DOD-DIGITAL-MODERNIZATION-STRATEGY-2019.PDF
* NIST SP 800-207 Zero Trust Architecture +
https://csrc.nist.gov/publications/detail/sp/800-207/final
* NetApp Partner Connect: Security Alliance Partners +
https://www.netapp.com/partners/partner-connect/#t=Partners&sort=%40partnerweight%20descending&layout=card&numberOfResults=25&f:@facet_language_mktg=[English]&f:@facet_partnertype_mktg=[Technology%20Alliance]&f:@facet_techsolution_mktg=[Security][https://www.netapp.com/partners/partner-connect/#t=Partners&sort=%40partnerweight%20descending&layout=card&numberOfResults=25&f:@facet_language_mktg=[English]&f:@facet_partnertype_mktg=[Technology%20Alliance]&f:@facet_techsolution_mktg=[Security]]
* Using FPolicy for file monitoring and management on SVMs +
https://docs.netapp.com/us-en/ontap/nas-audit/two-parts-fpolicy-solution-concept.html
* PCI-DSS 3.2 ONTAP 9 +
https://www.netapp.com/us/media/tr-4401.pdf
* General Data Protection Regulation (GDPR) +
https://www.netapp.com/us/info/gdpr.aspx
* Summary of HIPPA Privacy Rule +
https://www.hhs.gov/hipaa/for-professionals/privacy/laws-regulations/index.html
* NetApp BlueXP Classification +
https://bluexp.netapp.com/netapp-cloud-data-sense
* Multi-admin verification +
https://docs.netapp.com/us-en/ontap/multi-admin-verify/index.html
* Tamperproof Snapshot copy locking +
https://docs.netapp.com/us-en/ontap/snaplock/snapshot-lock-concept.html
* Multifactor authentication in ONTAP 9 +
https://www.netapp.com/us/media/tr-4647.pdf
* NetApp Storage Encryption, NVMe Self-Encrypting Drives, NetApp Volume
Encryption, and NetApp Aggregate Encryption +
https://www.netapp.com/us/media/ds-3898.pdf
* NetApp Storage Encryption +
https://www.netapp.com/us/media/ds-3213-en.pdf
* NetApp Volume Encryption and NetApp Aggregate Encryption +
https://www.netapp.com/us/media/ds-3899.pdf
* NetApp Cryptographic Module FIPS-140-2 Certificate +
https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4144
* Quantum Ready Data-At-Rest Encryption by NetApp +
https://www.netapp.com/us/media/sb-3952.pdf
* Innovating with Security: NetApp and Ontrack win Flash Memory Summit
Award +
https://blog.netapp.com/flash-memory-summit-award/
* Enabling onboard key management +
https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nve-task.html
* NetApp Interoperability Matrix Tool +
https://mysupport.netapp.com/matrix/imt.jsp?components=69551;&solution=1156&isHWU&src=IMT
* Configuring external key management +
https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-external-key-management-concept.html
* Commercial Solutions for Classified +
https://www.netapp.com/blog/netapp-ontap-CSfC-validation/
* ONTAP IPsec +
https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html
* Security config modify to enable FIPS mode +
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-950/security__config__modify.html
* Enabling cluster peering encryption on an existing peer relationship +
https://docs.netapp.com/us-en/ontap/peering/enable-cluster-peering-encryption-existing-task.html
* Storage Workload Security (Cloud Secure) +
https://docs.netapp.com/us-en/cloudinsights/cs_intro.html
* Get Started with Automating your Dev Work Flows with NetApp and
Ansible +
https://www.netapp.com/us/getting-started-with-netapp-approved-ansible-modules/index.aspx
* Ansible module specific to the NetApp DoD Unified Capabilities (UC)
Deployment Guide. +
https://github.com/NetApp/ansible/tree/master/nar_ontap_security_ucd_guide
* Administrator Authentication and RBAC +
https://docs.netapp.com/us-en/ontap/authentication/index.html
* ONTAP Data-at-Rest Encryption +
https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html
* TR-4569 Security Hardening Guide for NetApp ONTAP 9 +
https://www.netapp.com/us/media/tr-4569.pdf