---
permalink: performance-admin/adaptive-policy-template-task.html
sidebar: sidebar
keywords: qos, throughput floor, throughput ceiling, adaptive policy group template
summary: Enforce a throughput floor and ceiling at the SVM level using an adaptive policy group template.
---
= Set an adaptive policy group template
:icons: font
:imagesdir: ../media/

[.lead]
Beginning in ONTAP 9.13.1, you can enforce throughput floors and ceilings at the SVM level using an adaptive policy group template. 

.About this task
* The adaptive policy group template is a default policy `apg1`. The policy can be modified at any time. It can only be set with the CLI or ONTAP REST API and can only be applied to existing SVMs. 
* The adaptive policy group template only impacts volumes created on or migrated to the SVM after you set the policy. Existing volumes on the SVM retain their existing status. 
+
If you disable the adaptive policy group template, volumes on the SVM retain their existing policies. Only volumes subsequently created on or migrated to the SVM will be impacted by the disablement. 
* You cannot set an adaptive policy group template on an SVM with a QoS policy group. 
* Adaptive policy group templates are designed for AFF platforms. An adaptive policy group template can be set on other platforms, but the policy may not enforce a minimum throughput. Similarly, you can add an adaptive policy group template to an SVM in a FabricPool aggregate or in an aggregate that does not support a minimum throughput, however the throughput floor will not be enforced.  
* If the SVM is in a MetroCluster configuration or an SnapMirror relationship, the adaptive policy group template will be enforced on the mirrored SVM. 

.Steps
. Modify the SVM to apply the adaptive policy group template:
`vserver modify -qos-adaptive-policy-group-template apg1`
. Confirm the policy was set:
`vserver show -fields qos-adaptive-policy-group`

// 27 march 2023, ontapdoc-780
