---
permalink: performance-admin/check-fc-adapter-port-speed-task.html
sidebar: sidebar
keywords: check, fc, adapter, port, speed
summary: "The adapter target port speed should match the speed of the device to which it connects, to optimize performance. If the port is set to autonegotiation, it can take longer to reconnect after a takeover and giveback or other interruption."
---
= Check the FC adapter port speed
:icons: font
:imagesdir: ../media/

[.lead]
The adapter target port speed should match the speed of the device to which it connects, to optimize performance. If the port is set to autonegotiation, it can take longer to reconnect after a takeover and giveback or other interruption.

.What you'll need

All LIFs that use this adapter as their home port must be offline.

.Steps

. Take the adapter offline:
+
`network fcp adapter modify -node _nodename_ -adapter _adapter_ -state _down_`
+
Learn more about `network fcp adapter modify` in the link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-modify.html[ONTAP command reference^].
. Check the maximum speed of the port adapter:
+
`fcp adapter show -instance`
+
Learn more about `fcp adapter show` in the link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-show.html[ONTAP command reference^].
. Change the port speed, if necessary:
+
`network fcp adapter modify -node _nodename_ -adapter _adapter_ -speed {1|2|4|8|10|16|auto}`
. Bring the adapter online:
+
`network fcp adapter modify -node _nodename_ -adapter _adapter_ -state up`
. Bring all the LIFs on the adapter online:
+
`network interface modify -vserver * -lif * { -home-node node1 -home-port e0c } -status-admin up`
+
Learn more about `network interface modify` in the link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html[ONTAP command reference^].

.Example

The following example changes the port speed of adapter `0d` on `node1` to 2 Gbps:

----
cluster1::> network fcp adapter modify -node node1 -adapter 0d -speed 2
----

// 2025 Apr 24, ONTAPDOC-2960