---
permalink: performance-admin/check-network-settings-task.html
sidebar: sidebar
keywords: check, mtu, network, setting, storage, system
summary: "You can change the network settings on the storage system if they are not the same as on the client or data switches. Whereas the management network MTU setting is set to 1500, the data network MTU size should be 9000."
---
= Check the MTU network setting on the storage system
:icons: font
:imagesdir: ../media/

[.lead]
You can change the network settings on the storage system if they are not the same as on the client or data switches. Whereas the management network MTU setting is set to 1500, the data network MTU size should be 9000.

== About this task
All ports within a broadcast-domain have the same MTU size, with the exception of the e0M port handling management traffic. If the port is part of a broadcast-domain, use the `broadcast-domain modify` command to change the MTU for all ports within the modified broadcast-domain. For more information, and to complete this task using System Manager, see the https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-2AF31CD0-5D75-49D5-9F42-61FEA1C1C9F5.html[System Manager documentation].

.Steps

. Check the MTU port setting on the storage system:
+
`network port show -instance`
. Change the MTU port setting to 9000:
+
`network port modify -node _nodename_ -port _port_ -mtu 9000`

.Example

The following example changes the MTU port setting for `e0a` to 9000:

----
cluster1::*> network port modify -node node0 -port e0a -mtu 9000
----
