---
permalink: performance-admin/enable-disable-throughput-floors-v2-task.html
sidebar: sidebar
keywords: enable, disable, throughput, floors v2
summary: "You can enable or disable throughput floors v2 on AFF. The default is enabled. With floors v2 enabled, throughput floors can be met when controllers are heavily used at the expense of higher latency on other workloads. Floors v2 applies to both QoS and Adaptive QoS."
---
= Enable or disable ONTAP throughput floors v2
:icons: font
:imagesdir: ../media/

[.lead]
You can enable or disable throughput floors v2 on AFF. The default is enabled. With floors v2 enabled, throughput floors can be met when controllers are heavily used at the expense of higher latency on other workloads. Floors v2 applies to both QoS and Adaptive QoS.

.Steps

. Change to advanced privilege level:
+
`set -privilege advanced`

. Enter one of the following commands:
+
[options="header"]
|===
| If you want to...| Use this command:
a|
Disable floors v2
a|
`qos settings throughput-floors-v2 -enable false`
a|
Enable floors v2
a|
`qos settings throughput-floors-v2 -enable true`
|===
+
[NOTE]
====
To disable throughput floors v2 in an MetroCluster cluster, you must run the

`qos settings throughput-floors-v2 -enable false`

command on both the source and destination clusters.
====
+
----
cluster1::*> qos settings throughput-floors-v2 -enable false
----
+
Learn more about `qos settings throughput-floors-v2` in the link:https://docs.netapp.com/us-en/ontap-cli/qos-settings-throughput-floors-v2.html[ONTAP command reference^].

// 2025 July 15, ONTAPDOC-3132
// 2025 May 27, ONTAPDOC-2960