---
permalink: performance-admin/index.html
sidebar: sidebar
keywords: decide, performance, management
summary: "This content describes how to set up basic performance management tasks, and how to identify and resolve common performance issues."
---
= Performance management overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to set up basic performance management tasks, and how to identify and resolve common performance issues.

You should use this content if you want to monitor cluster performance, and the following assumptions apply to your situation:

* You want to use best practices, not explore every available option.
* You do not want to read a lot of conceptual background.
* You want to display system status and alerts, monitor cluster performance, and perform root-cause analysis by using Active IQ Unified Manager (formerly OnCommand Unified Manager), in addition to the ONTAP command-line interface.
* You are using the ONTAP command-line interface to configure storage quality of service (QoS).
+
QoS is also available in System Manager, NSLM, WFA, VSC (VMware Plug-in), and APIs.

* You want to install Unified Manager by using a virtual appliance, instead of a Linux or Windows-based installation.
* You're willing to use a static configuration rather than DHCP to install the software.
* You can access ONTAP commands at the advanced privilege level.
* You are a cluster administrator with the "admin" role.

If these assumptions are not correct for your situation, you should see the following resources:

* http://docs.netapp.com/ocum-98/topic/com.netapp.doc.onc-um-isg/home.html[Active IQ Unified Manager 9.8 Installation]
* link:../system-admin/index.html[System administration]
* link:../performance-config/index.html[Performance monitoring setup]
