---
permalink: performance-admin/worksheet-reference.html
sidebar: sidebar
keywords: active iq unified manager, worksheet
summary: "Before you install, configure, and connect Active IQ Unified Manager, you should have specific information about your environment readily available. You can record the information in the worksheet."
---
= Active IQ Unified Manager worksheet
:icons: font
:imagesdir: ../media/

[.lead]
Before you install, configure, and connect Active IQ Unified Manager, you should have specific information about your environment readily available. You can record the information in the worksheet.

== Unified Manager installation information

|===

h| Virtual machine on which software is deployed h| Your value

a|
ESXi server IP address
a|

a|
Host fully qualified domain name
a|

a|
Host IP address
a|

a|
Network mask
a|

a|
Gateway IP address
a|

a|
Primary DNS address
a|

a|
Secondary DNS address
a|

a|
Search domains
a|

a|
Maintenance user name
a|

a|
Maintenance user password
a|

|===

== Unified Manager configuration information

|===

h| Setting h| Your value

a|
Maintenance user email address
a|

a|
NTP server
a|

a|
SMTP server host name or IP address
a|

a|
SMTP user name
a|

a|
SMTP password
a|

a|
SMTP default port
a|
25 (Default value)
a|
Email from which alert notifications are sent
a|

a|
LDAP bind distinguished name
a|

a|
LDAP bind password
a|

a|
Active Directory administrator name
a|

a|
Active Directory password
a|

a|
Authentication server base distinguished name
a|

a|
Authentication server host name or IP address
a|

|===

== Cluster information

Capture the following information for each cluster on Unified Manager.

|===

h| Cluster 1 of N h| Your value

a|
Host name or cluster-management IP address
a|

a|
ONTAP administrator user name

NOTE: The administrator must have been assigned the "admin" role.
a|

a|
ONTAP administrator password
a|

a|
Protocol (HTTP or HTTPS)
a|

|===

.Related information

link:../authentication/index.html[Administrator authentication and RBAC]

// BURT 1453025, 2022 NOV 28
