---
permalink: peering/add-svm-intercluster-relationship-93-later-task.html
sidebar: sidebar
keywords: add, intercluster, svm, peer, vserver peer create
summary: "If you create an SVM after configuring a cluster peer relationship, you will need to add a peer relationship for the SVM manually. You can use the vserver peer create command to create a peer relationship between SVMs. After the peer relationship has been created, you can run vserver peer accept on the remote cluster to authorize the peer relationship."
---
= Add an intercluster SVM peer relationship in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
If you create an SVM after configuring a cluster peer relationship, you will need to add a peer relationship for the SVM manually. You can use the `vserver peer create` command to create a peer relationship between SVMs. After the peer relationship has been created, you can run `vserver peer accept` on the remote cluster to authorize the peer relationship.

.Before you begin

The source and destination clusters must be peered.

.About this task

You can create a peer relationships between SVMs in the same cluster for local data backup. For more information, see the `vserver peer create` man page.

Administrators occasionally use the `vserver peer reject` command to reject a proposed SVM peer relationship. If the relationship between SVMs is in the `rejected` state, you must delete the relationship before you can create a new one. For more information, see the `vserver peer delete` man page.

.Steps

. On the data protection source cluster, create a peer relationship with an SVM on the data protection destination cluster:
+
`vserver peer create -vserver _local_SVM_ -peer-vserver _remote_SVM_ -applications snapmirror|file-copy|lun-copy -peer-cluster _remote_cluster_`
+
The following example creates a peer relationship between the local SVM``pvs1`` and the remote SVM``vs1``
+
----
cluster01::> vserver peer create -vserver pvs1 -peer-vserver vs1 -applications snapmirror -peer-cluster cluster02
----
+
If the local and remote SVMs have the same names, you must use a _local name_ to create the SVM peer relationship:
+
----
cluster01::> vserver peer create -vserver vs1 -peer-vserver
vs1 -applications snapmirror -peer-cluster cluster01
-local-name cluster1vs1LocallyUniqueName
----

. On the data protection source cluster, verify that the peer relationship has been initiated:
+
`vserver peer show-all`
+
Learn more about `vserver peer show-all` in the link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-show-all.html[ONTAP command reference^].
+
The following example shows that the peer relationship between SVM``pvs1`` and SVM``vs1`` has been initiated:
+
----
cluster01::> vserver peer show-all
            Peer        Peer                      Peering
Vserver     Vserver     State      Peer Cluster   Applications
--------    --------    ---------  -------------  ------------
pvs1        vs1         initiated   Cluster02       snapmirror
----

. On the data protection destination cluster, display the pending SVM peer relationship:
+
`vserver peer show`
+
Learn more about `vserver peer show` in the link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-show.html[ONTAP command reference^].
+
The following example lists the pending peer relationships for `cluster02`:
+
----
cluster02::> vserver peer show

                   Peer               Peer
Vserver            Vserver            State
-----------        -----------        ------------
vs1                pvs1               pending
----

. On the data protection destination cluster, authorize the pending peer relationship:
+
`vserver peer accept -vserver _local_SVM_ -peer-vserver _remote_SVM_`
+
Learn more about `vserver peer accept` in the link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-accept.html[ONTAP command reference^].
+
The following example authorizes the peer relationship between the local SVM `vs1` and the remote SVM `pvs1`:
+
----
cluster02::> vserver peer accept -vserver vs1 -peer-vserver pvs1
----

. Verify the SVM peer relationship:
+
`vserver peer show`
+
----
cluster01::> vserver peer show
            Peer        Peer                           Peering        Remote
Vserver     Vserver     State        Peer Cluster      Applications   Vserver
----------- ----------- ------------ ----------------- -------------- ---------
pvs1        vs1         peered       cluster02         snapmirror     vs1
----


// 2025 Jan 17, ONTAPDOC-2569
