---
permalink: peering/create-intercluster-svm-peer-relationship-93-later-task.html
sidebar: sidebar
keywords: create, intercluster, svm, peer, relationship
summary: "You can use the vserver peer create command to create a peer relationship between SVMs on local and remote clusters."
---
= Create an intercluster SVM peer relationship (ONTAP 9.3 and later)
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `vserver peer create` command to create a peer relationship between SVMs on local and remote clusters.

.What you'll need

* The source and destination clusters must be peered.
* The clusters must be running ONTAP 9.3.
* You must have "pre-authorized" peer relationships for the SVMs on the remote cluster.
+
For more information, see xref:create-cluster-relationship-93-later-task.adoc[Creating a cluster peer relationship (ONTAP 9.3 and later)].

.About this task

Previous releases of ONTAP let you authorize a peer relationship for only one SVM at a time. You needed to run the `vserver peer accept` command each time you authorized a pending SVM peer relationship.

Starting in ONTAP 9.3, you can "pre-authorize" peer relationships for multiple SVMs by listing the SVMs in the `-initial-allowed-vserver` option when you create a cluster peer relationship. For more information, see xref:create-cluster-relationship-93-later-task.adoc[Creating a cluster peer relationship (ONTAP 9.3 and later)].

.Steps

. On the data protection destination cluster, display the SVMs that are pre-authorized for peering:
+
`vserver peer permission show`
+
----
cluster02::> vserver peer permission show
Peer Cluster         Vserver               Applications
-------------------  --------------------  --------------------
cluster02            vs1,vs2               snapmirror
----

. On the data protection source cluster, create a peer relationship to a pre-authorized SVM on the data protection destination cluster:
+
`vserver peer create -vserver _local_SVM_ -peer-vserver _remote_SVM_`
+
For complete command syntax, see the man page.
+
The following example creates a peer relationship between the local SVM `pvs1` and the pre-authorized remote SVM `vs1`:
+
----
cluster01::> vserver peer create -vserver pvs1 -peer-vserver vs1
----

. Verify the SVM peer relationship:
+
`vserver peer show`
+
----
cluster01::> vserver peer show
            Peer        Peer                           Peering        Remote
Vserver     Vserver     State        Peer Cluster      Applications   Vserver
----------- ----------- ------------ ----------------- -------------- ---------
pvs1        vs1         peered       cluster02         snapmirror     vs1
----
