---
permalink: peering/enable-cluster-peering-encryption-existing-task.html
sidebar: sidebar
keywords: enable, cluster, peering, encryption, existing, peer, relationship
summary: "Beginning with ONTAP 9.6, cluster peering encryption is enabled by default on all newly created cluster peering relationships. Cluster peering encryption uses a pre-shared key (PSK) and the Transport Security Layer (TLS) to secure cross-cluster peering communications. This adds an additional layer of security between the peered clusters."
---
= Enable cluster peering encryption on an existing peer relationship
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.6, cluster peering encryption is enabled by default on all newly created cluster peering relationships. Cluster peering encryption uses a pre-shared key (PSK) and the Transport Security Layer (TLS) to secure cross-cluster peering communications. This adds an additional layer of security between the peered clusters.

.About this task

Cluster peering encryption must be enabled manually for peering relationship created prior to upgrading to ONTAP 9.6. Cluster peering encryption is not available for clusters running ONTAP 9.5 or earlier. Therefore, both clusters in the peering relationship must be running ONTAP 9.6 in order to enable cluster peering encryption.

.Steps

. On the destination cluster, enable encryption for communications with the source cluster:
+
`cluster peer modify _source_cluster_ -auth-status-admin use-authentication -encryption tls-psk`
. When prompted enter a passphrase.
. On the data protection source cluster, enable encryption for communication with the data protection destination cluster:
+
`cluster peer modify _data_protection_destination_cluster_ -auth-status-admin use-authentication -encryption tls-psk`
. When prompted, enter the same passphrase entered on the destination cluster.
