---
permalink: peering/enable-cluster-peering-encryption-existing-task.html
sidebar: sidebar
keywords: enable, cluster, peering, encryption, existing, peer, relationship
summary: "Beginning with ONTAP 9.6, cluster peering encryption is enabled by default on all newly created cluster peering relationships. Cluster peering encryption uses a pre-shared key (PSK) and the Transport Security Layer (TLS) to secure cross-cluster peering communications. This adds an additional layer of security between the peered clusters."
---

= Enable ONTAP cluster peering encryption on peer relationships
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.6, cluster peering encryption is enabled by default on all newly created cluster peering relationships. Cluster peering encryption uses a pre-shared key (PSK) and the Transport Security Layer (TLS) to secure cross-cluster peering communications. This adds an additional layer of security between the peered clusters.

.About this task

If you are upgrading peered clusters to ONTAP 9.6 or later, and the peering relationship was created in ONTAP 9.5 or earlier, cluster peering encryption must be enabled manually after upgrading. Both clusters in the peering relationship must be running ONTAP 9.6 or later in order to enable cluster peering encryption.

.Steps

. On the destination cluster, enable encryption for communications with the source cluster:
+
`cluster peer modify _source_cluster_ -auth-status-admin use-authentication -encryption-protocol-proposed tls-psk`
. When prompted enter a passphrase.
. On the data protection source cluster, enable encryption for communication with the data protection destination cluster:
+
`cluster peer modify _data_protection_destination_cluster_ -auth-status-admin use-authentication -encryption-protocol-proposed tls-psk`
. When prompted, enter the same passphrase entered on the destination cluster.

Learn more about `cluster peer modify` in the link:https://docs.netapp.com/us-en/ontap-cli/cluster-peer-modify.html[ONTAP command reference^].

// 2025 Apr 17, ONTAPDOC-2960
// 2025-04-03, ONTAPDOC-2920
// 2022-01-21, BURT 1401451
// BURT 1428244, 2021-11-15
