---
permalink: peering/index.html
sidebar: sidebar
keywords: decide, cluster, svm, peering, peer, relationships, source, destination, svm, storage, virtual, machines
summary: "This content describes how to create peer relationships between source and destination clusters and between source and destination storage virtual machines (SVMs)."
---
= Cluster and SVM peering overview with the CLI
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to create peer relationships between source and destination clusters and between source and destination storage virtual machines (SVMs). You must create peer relationships between these entities before you can replicate Snapshot copies using SnapMirror.

ONTAP 9.3 offers enhancements that simplify the way you configure peer relationships between clusters and SVMs. This content describes the cluster and SVMs peering procedure for all ONTAP 9 versions. You should use the appropriate procedure for your version of ONTAP.

You should use this content if you want to use the command-line interface (CLI), not ONTAP System Manager or an automated scripting tool.
