---
permalink: peering/peering-basics-concept.html
sidebar: sidebar
keywords: peer, basics
summary: "Clusters and SVMs in peer relationships communicate over the intercluster network using intercluster logical interfaces (LIFs). An intercluster LIF is a LIF that supports the 'intercluster-core' network interface service and is typically created using the 'default-intercluster' network interface service policy. You must create intercluster LIFs on every node in the clusters being peered."
---
= Peering basics
:icons: font
:imagesdir: ../media/

[.lead]
You must create _peer relationships_ between source and destination clusters and between source and destination SVMs before you can replicate snapshots using SnapMirror. A peer relationship defines network connections that enable clusters and SVMs to exchange data securely.

Clusters and SVMs in peer relationships communicate over the intercluster network using _intercluster logical interfaces (LIFs)._ An intercluster LIF is a LIF that supports the "intercluster-core" network interface service and is typically created using the "default-intercluster" network interface service policy. You must create intercluster LIFs on every node in the clusters being peered.

Intercluster LIFs use routes that belong to the system SVM to which they are assigned. ONTAP automatically creates a system SVM for cluster-level communications within an IPspace.

Fan-out and cascade topologies are both supported. In a cascade topology, you need only create intercluster networks between the primary and secondary clusters and between the secondary and tertiary clusters. You need not create an intercluster network between the primary and the tertiary cluster.

[NOTE]
====
It is possible (but not advisable) for an administrator to remove the intercluster-core service from the default-intercluster service policy. If this occurs, LIFs created using "default-intercluster" will not actually be intercluster LIFs. To confirm that the default-intercluster service policy contains the intercluster-core service, use the following command:

`network interface service-policy show -policy default-intercluster`
====

// 2024-Aug-6, ONTAPDOC-2272