---
permalink: peering/remove-snapmirror-encryption-existing-relationship-task.html
sidebar: sidebar
keywords: remove, cluster, peering, encryption, existing, peer, relationship
summary: "By default, cluster peering encryption is enabled on all peer relationships created in ONTAP 9.6 or later. If you do not want to use encryption for cross-cluster peering communications, you can disable it."
---
= Remove cluster peering encryption from an existing peer relationship
:icons: font
:imagesdir: ../media/

[.lead]
By default, cluster peering encryption is enabled on all peer relationships created in ONTAP 9.6 or later. If you do not want to use encryption for cross-cluster peering communications, you can disable it.

.Steps

. On the destination cluster, modify communications with the source cluster to discontinue use of cluster peering encryption :
** To remove encryption, but maintain authentication enter:
+
[source,cli]
----
cluster peer modify _source_cluster_ -auth-status-admin use-authentication -encryption-protocol-proposed none
----
** To remove encryption and authentication, enter:
+
[source,cli]
----
cluster peer modify _source_cluster_ -auth-status no-authentication
----
. When prompted enter a passphrase.
. On the source cluster, disable encryption for communication with the destination cluster:
** To remove encryption, but maintain authentication enter:
+
[source,cli]
----
cluster peer modify _destination_cluster_ -auth-status-admin use-authentication -encryption-protocol-proposed none
----
** To remove encryption and authentication, enter:
+
[source,cli]
----
cluster peer modify _destination_cluster_ -auth-status no-authentication
----
. When prompted, enter the same passphrase entered on the destination cluster.

//2024 Jan 25, GitIssue 1233