---
permalink: san-admin/asa-iscsi-lif-fo-task.html
sidebar: sidebar
keywords: failover, iscsi, all san array, cli, system manager, auto-revert, revert network interface
summary: After you upgrade to ONTAP 9.11.1 or later, you should manually enable automatic LIF failover on all iSCSI LIFs created in ONTAP 9.10.1 or earlier. 
---
= Enable or disable automatic iSCSI LIF failover
:icons: font
:imagesdir: ../media/

[.lead]

After you upgrade to ONTAP 9.11.1 or later, you should manually enable automatic LIF failover on all iSCSI LIFs created in ONTAP 9.10.1 or earlier.   

Beginning with ONTAP 9.11.1, you can enable automatic LIF failover for iSCSI LIFs on All-flash SAN Array platforms. If a storage failover occurs, the iSCSI LIF is automatically migrated from its home node or port to its HA partner node or port and then back once the failover is complete.  Or, if the port for iSCSI LIF becomes unhealthy, the LIF is automatically migrated to a healthy port in its current home node and then back to its original port once the port is healthy again.  The enables SAN workloads running on iSCSI to resume I/O service faster after a failover is experienced.

In ONTAP 9.11.1 and later, by default, newly created iSCSI LIFs are enabled for automatic LIF failover if one of the following conditions is true:

* There are no iSCSI LIFs on the SVM 
* All iSCSI LIFs on the SVM are enabled for automatic LIF failover

== Enable automatic iSCSI LIF failover

By default, iSCSI LIFs created in ONTAP 9.10.1 and earlier are not enabled for automatic LIF failover.  If there are iSCSI LIFs on the SVM that are not enabled for automatic LIF failover, your newly created LIFs will not be enabled for automatic LIF failover either.  If automatic LIF failover is not enabled and there is a failover event your iSCSI LIFs will not migrate.  

Learn more about link:../networking/configure_lifs_@cluster_administrators_only@_overview.html#lif-failover-and-giveback[LIF failover and giveback].

.Step

. Enable automatic failover for an iSCSI LIF:
+
[source,cli]
----
network interface modify -vserver SVM_name -lif iscsi_lif –failover-policy sfo-partner-only -auto-revert true
----
+
To update all iSCSI LIFs on the SVM, use `-lif*` instead of `lif`.

== Disable automatic iSCSI LIF failover

If you previously enabled automatic iSCSI LIF failover on iSCSI LIFs created in ONTAP 9.10.1 or earlier, you have the option to disable it.

.Step

. Disable automatic failover for an iSCSI LIF:
+
[source,cli]
----
network interface modify -vserver SVM_name -lif iscsi_lif –failover-policy disabled -auto-revert false
----
+
To update all iSCSI LIFs on the SVM, use `-lif*` instead of `lif`.

.Related Information

* link:../networking/create_a_lif.html[Create a LIF]
* Manually link:../networking/migrate_a_lif.html[migrate a LIF]
* Manually link:../networking/revert_a_lif_to_its_home_port.html[revert a LIF to its home port]
* link:.../networking/configure_failover_settings_on_a_lif.html[Configure failover settings on a LIF]


// 2023, Dec 18, ONTAPDOC-1457
// 2023, Dec 11, ONTAPDOC-1457
// 7 DEC 2023, ONTAPDOC-1457
// 22 MAR 2022, Jira IE-523