---
permalink: san-admin/backup-lun-host-backup-system-task.html
sidebar: sidebar
keywords: back up, lun, through, host, backup, system
summary: "You can use a cloned LUN from a snapshot as source data for the host backup system."
---
= Back up a LUN through a host backup system
:icons: font
:imagesdir: ../media/

[.lead]
You can use a cloned LUN from a snapshot as source data for the host backup system.

.What you'll need

A production LUN must exist and be mapped to an igroup that includes the WWPN or initiator node name of the application server. The LUN must also be formatted and accessible to the host

.Steps

. Save the contents of the host file system buffers to disk.
+
You can use the command provided by your host operating system, or you can use SnapDrive for Windows or SnapDrive for UNIX. You can also opt to make this step part of your SAN backup pre-processing script.

. Use the `volume snapshot create` command to create a snapshot of the production LUN.
+
`volume snapshot create -vserver vs0 -volume vol3 -snapshot vol3_snapshot -comment "Single snapshot" -foreground false`

. Use the `volume file clone create` command to create a clone of the production LUN.
+
`volume file clone create -vserver vs3 -volume vol3 -source-path lun1 -snapshot-name snap_vol3 -destination-path lun1_backup`

. Use the `lun igroup create` command to create an igroup that includes the WWPN of the backup server.
+
`lun igroup create -vserver vs3 -igroup igroup3 -protocol fc -ostype windows -initiator 10:00:00:00:c9:73:5b:91`

. Use the `lun mapping create` command to map the LUN clone you created in Step 3 to the backup host.
+
`lun mapping create -vserver vs3 -volume vol3 -lun lun1_backup -igroup igroup3`
+
You can opt to make this step part of your SAN backup application's post-processing script.

. From the host, discover the new LUN and make the file system available to the host.
+
You can opt to make this step part of your SAN backup application's post-processing script.

. Back up the data in the LUN clone from the backup host to tape by using your SAN backup application.
. Use the `lun modify` command to take the LUN clone offline.
+
`lun modify -vserver vs3 -path /vol/vol3/lun1_backup -state offline`

. Use the `lun delete` to remove the LUN clone.
+
`lun delete -vserver vs3 -volume vol3 -lun lun1_backup`

. Use the `volume snapshot delete` command to remove the snapshot.
+
`volume snapshot delete -vserver vs3 -volume vol3 -snapshot vol3_snapshot`
