---
permalink: san-admin/backup-lun-host-backup-system-task.html
sidebar: sidebar
keywords: back up, lun, through, host, backup, system
summary: "You can use a cloned LUN from a snapshot as source data for the host backup system."
---
= Use a host backup system to protect a LUN on your ONTAP storage system
:icons: font
:imagesdir: ../media/

[.lead]
You can use a cloned LUN from a snapshot as source data for the host backup system.

.Before you begin

A production LUN must exist and be mapped to an igroup that includes the WWPN or initiator node name of the application server. The LUN must also be formatted and accessible to the host

.Steps

. Save the contents of the host file system buffers to disk.
+
You can use the command provided by your host operating system. You can also opt to make this step part of your SAN backup pre-processing script.

. Create a snapshot of the production LUN.
+
[source,cli]
----
volume snapshot create -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot> -comment <comment> -foreground false
----

. Create a clone of the production LUN.
+
[source,cli]
----
volume file clone create -vserver <SMV_name> -volume <volume> -source-path <path> -snapshot-name <snapshot> -destination-path <destination_path> 
----

. Create an igroup that includes the WWPN of the backup server.
+
[source,cli]
----
lun igroup create -vserver <SVM_name> -igroup <igroup> -protocol <protocol> -ostype <os_type> -initiator <initiator>
----

. Map the LUN clone you created in Step 3 to the backup host.
+
[source,cli]
----
lun mapping create -vserver <SVM_name> -volume <volume_name> -lun <lun_name> -igroup <igroup>
----
+
You can opt to make this step part of your SAN backup application's post-processing script.

. From the host, discover the new LUN and make the file system available to the host.
+
You can opt to make this step part of your SAN backup application's post-processing script.

. Back up the data in the LUN clone from the backup host to tape by using your SAN backup application.

. Take the LUN clone offline.
+
[source,cli]
----
lun modify -vserver <SVM_name> -path <path> -state offline
----

. Remove the LUN clone.
+
[source,cli]
----
lun delete -vserver <SVM_name> -volume <volume> -lun <lun_name>
----

. Remove the snapshot.
+
[source,cli]
----
volume snapshot delete -vserver <SVM_name> -volume <volume> -snapshot <snapshot>
----

// 2025 Apr22, ONTAPDOC-2974
// 2025 Apr 24, ONTAPDOC-2960
