---
permalink: san-admin/commands-manage-fc-adapters-reference.html
sidebar: sidebar
keywords: commands, managing, fc, adapters
summary: "You can use FC commands to manage FC target adapters, FC initiator adapters, and onboard FC adapters for your storage controller. The same commands are used to manage FC adapters for the FC protocol and the FC-NVMe protocol."
---
= Commands for managing FC adapters
:icons: font
:imagesdir: ../media/

[.lead]
You can use FC commands to manage FC target adapters, FC initiator adapters, and onboard FC adapters for your storage controller. The same commands are used to manage FC adapters for the FC protocol and the FC-NVMe protocol.

FC initiator adapter commands work only at the node level. You must use the `run -node _node_name_` command before you can use the FC initiator adapter commands.

== Commands for managing FC target adapters
[cols="2*",options="header"]
|===
| If you want to...| Use this command...
a|
Display FC adapter information on a node
a|
`network fcp adapter show`
a|
Modify FC target adapter parameters
a|
`network fcp adapter modify`
a|
Display FC protocol traffic information
a|
`run -node _node_name_ sysstat -f`
a|
Display how long the FC protocol has been running
a|
`run -node _node_name_ uptime`
a|
Display adapter configuration and status
a|
`run -node _node_name_ sysconfig -v _adapter_`
a|
Verify which expansion cards are installed and whether there are any configuration errors
a|
`run -node _node_name_ sysconfig -ac`
a|
View a man page for a command
a|
`man <command_name>`
|===

== Commands for managing FC initiator adapters
[cols="2*",options="header"]
|===
| If you want to...| Use this command...
a|
Display information for all initiators and their adapters in a node
a|
`run -node _node_name_ storage show adapter`
a|
Display adapter configuration and status
a|
`run -node _node_name_ sysconfig -v _adapter_`
a|
Verify which expansion cards are installed and whether there are any configuration errors
a|
`run -node _node_name_ sysconfig -ac`
|===

== Commands for managing onboard FC adapters
[cols="2*",options="header"]
|===
| If you want to...| Use this command...
a|
Display the status of the onboard FC ports
a|
`run -node _node_name_ system hardware unified-connect show`
|===

Learn more about the commands described in this procedure in the link:https://docs.netapp.com/us-en/ontap-cli/[ONTAP command reference^].

// 2025 Apr 08, ONTAPDOC-2758