---
permalink: san-admin/configure-backup-vaults-san-environment-concept.html
sidebar: sidebar
keywords: configure, using, snapvault, backups, san, environment
summary: "SnapVault configuration and use in a SAN environment is very similar to configuration and use in a NAS environment, but restoring LUNs in a SAN environment requires some special procedures."
---
= Configure and use SnapVault backups in a SAN environment overview
:icons: font
:imagesdir: ../media/

[.lead]
SnapVault configuration and use in a SAN environment is very similar to configuration and use in a NAS environment, but restoring LUNs in a SAN environment requires some special procedures.

SnapVault backups contain a set of read-only copies of a source volume. In a SAN environment you always back up entire volumes to the SnapVault secondary volume, not individual LUNs.

The procedure for creating and initializing the SnapVault relationship between a primary volume containing LUNs and a secondary volume acting as a SnapVault backup is identical to the procedure used with FlexVol volumes used for file protocols. This procedure is described in detail in link:../data-protection/index.html[Data Protection].

It is important to ensure that LUNs being backed up are in a consistent state before the Snapshot copies are created and copied to the SnapVault secondary volume. Automating the snapshot creation with SnapCenter ensures that backed up LUNs are complete and usable by the original application.

There are three basic choices for restoring LUNs from a SnapVault secondary volume:

* You can map a LUN directly from the SnapVault secondary volume and connect a host to the LUN to access the contents of the LUN.
+
The LUN is read-only and you can map only from the most recent snapshot in the SnapVault backup. Persistent reservations and other LUN metadata are lost. If desired, you can use a copy program on the host to copy the LUN contents back to the original LUN if it is still accessible.
+
The LUN has a different serial number from the source LUN.

* You can clone any snapshot in the SnapVault secondary volume to a new read-write volume.
+
You can then map any of the LUNs in the volume and connect a host to the LUN to access the contents of the LUN. If desired, you can use a copy program on the host to copy the LUN contents back to the original LUN if it is still accessible.

* You can restore the entire volume containing the LUN from any snapshot in the SnapVault secondary volume.
+
Restoring the entire volume replaces all of the LUNs, and any files, in the volume. Any new LUNs created since the snapshot was created are lost.
+
The LUNs retain their mapping, serial numbers, UUIDs, and persistent reservations.
