---
permalink: san-admin/configure-nvme-lif-task.html
sidebar: sidebar
keywords: configure, nvme, lif
summary: "Certain requirements must be met when configuring NVMe LIFs."
---
= Configure an NVMe LIF
:icons: font
:imagesdir: ../media/

[.lead]
Certain requirements must be met when configuring NVMe LIFs.

.What you'll need

NVMe must be supported by the FC adapter on which you create the LIF. Supported adapters are listed in the _Hardware Universe_.

https://hwu.netapp.com[NetApp Hardware Universe]

.About this task

The following rules apply when creating an NVMe LIF:

* NVMe can be the only data protocol on data LIFs.
* You should configure one management LIF for every SVM that supports SAN.
* For ONTAP 9.5 and later:
 ** You can only configure two NVMe LIFs per node on a maximum of four nodes.
 ** You must configure an NVMe LIF on the node containing the namespace and on node's HA partner.
* For ONTAP 9.4 only:
 ** NVMe LIFs and namespaces must be hosted on the same node.
 ** Only one NVMe data LIF can be configured per SVM.

.Steps

. Create the LIF:
+
`network interface create -vserver _SVM_name_ -lif _LIF_name_ -role _LIF_role_ -data-protocol fc-nvme -home-node _home_node_ -home-port`
+
`_home_port_`
. Verify that the LIF was created:
+
`network interface show -vserver _SVM_name_`
