---
permalink: san-admin/configure-return-fqdn-host-iscsi-discovery-task.html
sidebar: sidebar
keywords: configure, iscsi, lifs, return, fqdn, host, sendtargets discovery operation
summary: "Beginning with ONTAP 9, iSCSI LIFs can be configured to return a Fully Qualified Domain Name (FQDN) when a host OS sends an iSCSI SendTargets Discovery Operation. Returning a FQDN is useful when there is a Network Address Translation (NAT) device between the host OS and the storage service."
---
= Configure iSCSI LIFs to return FQDN to host iSCSI SendTargets Discovery Operation
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9, iSCSI LIFs can be configured to return a Fully Qualified Domain Name (FQDN) when a host OS sends an iSCSI SendTargets Discovery Operation. Returning a FQDN is useful when there is a Network Address Translation (NAT) device between the host OS and the storage service.

.About this task

IP addresses on one side of the NAT device are meaningless on the other side, but FQDNs can have meaning on both sides.

[NOTE]
====
The FQDN value interoperability limit is 128 characters on all host OS.
====

.Steps

. Change the privilege setting to advanced:
+
`set -privilege advanced`
. Configure iSCSI LIFs to return FQDN:
+
`vserver iscsi interface modify -vserver _SVM_name_ -lif _iscsi_LIF_name_ -sendtargets_fqdn FQDN`
+
In the following example, the iSCSI LIFs are configured to return storagehost-005.example.com as the FQDN.
+
`vserver iscsi interface modify -vserver vs1 -lif vs1_iscsi1 -sendtargets-fqdn storagehost-005.example.com`

. Verify that sendtargets is the FQDN:
+
`vserver iscsi interface show -vserver _SVM_name_ -fields sendtargets-fqdn`
+
In this example, storagehost-005.example.com is displayed in the sendtargets-fqdn output field.
+
----
cluster::vserver*> vserver iscsi interface show -vserver vs1 -fields sendtargets-fqdn
vserver lif        sendtargets-fqdn
------- ---------- ---------------------------
vs1     vs1_iscsi1 storagehost-005.example.com
vs1     vs1_iscsi2 storagehost-006.example.com
----

.Related information

https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html[ONTAP 9 command reference]
