---
permalink: san-admin/create-flexclone-luns-snapshot-copy-volume-task.html
sidebar: sidebar
keywords: create, flexclone, luns, snapshot, copy, volume
summary: "You can use a Snapshot copy in your volume to create FlexClone copies of your LUNs. FlexClone copies of LUNs are both readable and writeable."
---
= Create FlexClone LUNs from a Snapshot copy in a volume
:icons: font
:imagesdir: ../media/

[.lead]
You can use a Snapshot copy in your volume to create FlexClone copies of your LUNs. FlexClone copies of LUNs are both readable and writeable.

.What you'll need

A FlexClone license must be installed. This license is included with link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one[ONTAP One].

.About this task

The FlexClone LUN inherits the space reservations attribute of the parent LUN. A space-reserved FlexClone LUN requires as much space as the space-reserved parent LUN. If the FlexClone LUN is not space-reserved, the volume must have enough space to accommodate changes to the clone.

.Steps

. Verify that the LUN is not mapped or being written to.
. Create a Snapshot copy of the volume that contains the LUNs:
+
`volume snapshot create -vserver _vserver_name_ -volume _volume_name_ -snapshot _snapshot_name_`
+
You must create a Snapshot copy (the backing Snapshot copy) of the LUN you want to clone.

. Create the FlexClone LUN from the Snapshot copy:
+
`file clone create -vserver _vserver_name_ -volume _volume_name_ -source-path _source_path_ -snapshot-name _snapshot_name_ -destination-path _destination_path_`
+
If you need the FlexClone LUN to be available for automatic deletion, you include `-autodelete true`. If you are creating this FlexClone LUN in a volume using semi-thick provisioning, you must enable automatic deletion for all FlexClone LUNs.

. Verify that the FlexClone LUN is correct:
+
`lun show -vserver _vserver_name_`
+
----

Vserver Path                      State    Mapped    Type     Size
------- ----------------------    -------- --------- -------- -------
vs1     /vol/vol1/lun1_clone      online   unmapped windows   47.07MB
vs1     /vol/vol1/lun1_snap_clone online   unmapped windows   47.07MB
----

// 2024-Mar-28, ONTAPDOC-1366