---
permalink: san-admin/create-nvme-namespace-subsystem-task.html
sidebar: sidebar
keywords: create, nvme, namespace, subsystem
summary: "For systems using the NVMe protocol, you must create one or more NVMe namespaces and subsystems. Each namespace can then be mapped to an NVMe subsystem to allow data access from your host system."
---
= Provision NVMe storage 
:icons: font
:imagesdir: ../media/

[.lead]
If a procedure for your specific host is not available, you can use these steps to create namespaces and provision storage for any NVMe supported host.

Namespaces appear to Linux as SCSI disk devices.

This procedure creates new namespaces on an existing storage VM. Your storage VM must be configured for NVME, and your FC or TCP transport should already be set up.

Beginning with ONTAP 9.8, when you provision storage, QoS is enabled by default. You can disable QoS or choose a custom QoS policy during the provisioning process or at a later time.

[role="tabbed-block"]
====

.System Manager
--

Using ONTAP System Manager (9.7 and later), create namespaces to provide storage using the NVMe protocol. 

.Steps

. In System Manager, click *Storage > NVMe Namespaces* and then click *Add*.
+
If you need to create a new subsystem, click *More Options*.
+
. If you are running ONTAP 9.8 or later and you want to disable QoS or choose a custom QoS policy, click *More Options* and then, under *Storage and Optimization* select *Performance Service Level*.

[start=2]
. Zone your FC switches by WWPN. Use one zone per initiator and include all target ports in each zone.

. On your host, discover the new namespaces.

. Initialize the namespace and format it with a file system.

. Verify that your host can write and read data on the namespace.

--

.CLI
--
Using the ONTAP CLI, create namespaces to provide storage using the NVMe protocol.

This procedure creates an NVMe namespace and subsystem on an existing storage VM which has already been configured for the NVMe protocol, then maps the namespace to the subsystem to allow data access from your host system.

If you need to configure the storage VM for NVMe, see link:configure-svm-nvme-task.html[Configure an SVM for NVMe].

.Steps

. Verify that the SVM is configured for NVMe:
+
`vserver show -vserver _SVM_name_ -fields allowed-protocols`
+
`NVMe` should be displayed under the `allowed-protocols` column.

. Create the NVMe namespace:
+
`vserver nvme namespace create -vserver _SVM_name_ -path _path_ -size _size_of_namespace_ -ostype _OS_type_`
. Create the NVMe subsystem:
+
`vserver nvme subsystem create -vserver _SVM_name_ -subsystem _name_of_subsystem_ -ostype _OS_type_`
+
The NVMe subsystem name is case sensitive. It must contain 1 to 96 characters. Special characters are allowed.

. Verify that the subsystem was created:
+
`vserver nvme subsystem show -vserver _SVM_name_`
+
The `nvme` subsystem should be displayed under the `Subsystem` column.

. Obtain the NQN from the host.

. Add the host NQN to the subsystem:
+
`vserver nvme subsystem host add -vserver _SVM_name_ -subsystem _subsystem_name_ -host-nqn _Host_NQN_:subsystem._subsystem_name_`

. Map the namespace to the subsystem:
+
`vserver nvme subsystem map add -vserver _SVM_name_ -subsystem _subsystem_name_ -path _path_`
+
A namespace can only be mapped to a single subsystem.

. Verify that the namespace is mapped to the subsystem:
+
`vserver nvme namespace show -vserver _SVM_name_ -instance`
+
The subsystem should be listed as the `Attached subsystem`.
--
====

== About NVMe subsystems

An NVMe subsystem includes one or more controllers, one or more namespaces, one or more non-volatile memory (NVM) subsystem ports (FC-NVMe or RDMA transport ports), an NVM storage medium, and an interface between the controllers and the NVM storage medium. For controller mapping and management, an NVM subsystem maps to a vserver in ONTAP.

An NVMe over Fabric (NVMeoF) subsystem is a separate kernel object that resides in the FreeBSD kernel. The NVMeoF subsystem interfaces with the following components:

* SAN components, such as BCOMKA, FCT, and VDOM
* WAFL
* RAS components, such as CM, ASUP, and EMS

All interfaces with NVMeoF subsystems adhere to the current definitions and patterns found in ONTAP.

// 2022 Mar 24, content moved as part of sm-classic rework
// 2023 Jan 16 include files in tabs replaced with text
