---
permalink: san-admin/create-nvme-namespace-subsystem-task.html
sidebar: sidebar
keywords: create, nvme, namespace, subsystem
summary: "For systems using the NVMe protocol, you must create one or more NVMe namespaces and subsystems. Each namespace can then be mapped to an NVMe subsystem to allow data access from your host system."
---
= Create an NVMe namespace and subsystem
:icons: font
:imagesdir: ../media/

[.lead]
For systems using the NVMe protocol, you must create one or more NVMe namespaces and subsystems. Each namespace can then be mapped to an NVMe subsystem to allow data access from your host system.

.What you'll need

The SVM must already be configured for NVMe.

.Steps

. Verify that the SVM is configured for NVMe:
+
`vserver show -vserver _SVM_name_ -fields allowed-protocols`
+
`NVMe` should be displayed under the `allowed-protocols` column.

. Create the NVMe namespace:
+
`vserver nvme namespace create -vserver _SVM_name_ -path _path_ -size _size_of_namespace_ -ostype _OS_type_`
. Create the NVMe subsystem:
+
`vserver nvme subsystem create -vserver _SVM_name_ -subsystem _name_of_subsystem_ -ostype _OS_type_`
. Verify that the subsystem was created:
+
`vserver nvme subsystem show -vserver _SVM_name_`
+
The `nvme` subsystem should be displayed under the `Subsystem` column.
