---
permalink: san-admin/enable-space-allocation.html
sidebar: sidebar
keywords: enable, space allocation, space reclamation, unmap, lun
summary: "Enable space allocation to allow the host and storage system to cooperate on space management."
---
= Enable space allocation for SAN
:icons: font
:imagesdir: ../media/

[.lead]
Enable space allocation to prevent your LUNs from being taken offline if they run out of space and to enable your host to reclaim space. 

Beginning with ONTAP 9.15.1, space allocation is enabled for newly created LUNs by default . Space allocation is disabled in ONTAP 9.14.1 and earlier by default.

Enabling space allocation allows the following benefits:

* LUNs are not taken offline if they run out of space.
+
When space allocation is enabled, if a LUN runs out of space, ONTAP communicates to the host that no free space is available for write operations, the LUN remains online and read operations continue to be serviced.  Depending upon the host configuration, the host retries write operations until it succeeds or the host filesystem is placed offline.
+
Write operations resume when additional free space becomes available to the LUN.
+
If space allocation is not enabled, when a LUN reaches a low space threshold, all I/O operations fail and the LUN is taken offline. The space issue must be resolved before the LUN is brought back online.  Rescanning LUN devices might also be required on the host to restore paths and devices to an operational state.

* A host can perform `SCSI UNMAP` (sometimes called `TRIM`) operations.
+
SCSI UNMAP operations allow a host to identify blocks of data on a LUN that are no longer required because they no longer contain valid data. Identification normally happens after file deletion. The storage system can then deallocate those data blocks so that the space can be consumed elsewhere. This deallocation greatly improves overall storage efficiency, especially with filesystems that have data high turnover.

.Before you begin
Enabling space allocation requires a host configuration that can correctly handle space allocation errors when a write cannot be completed. Leveraging `SCSI UNMAP` requires a configuration that can use logical block provisioning as defined in the SCSI SBC-3 standard. 

The following hosts currently support SCSI thin provisioning when you enable space allocation:

* Citrix XenServer 6.5 and later
* ESXi 5.0 and later
* Oracle Linux 6.2 UEK kernel and later
* Red Hat Enterprise Linux 6.2 and later
* SUSE Linux Enterprise Server 11 and later
* Solaris 11.1 and later
* Windows 

Space allocation is not supported on NVMe hosts.

.About this task

When you upgrade your cluster to ONTAP 9.15.1, the space allocation setting for all LUNs created prior to the software upgrade remains the same after the upgrade, regardless of host type. For example, if a LUN was created in ONTAP 9.13.1 for a VMware host with space allocation disabled, space allocation on that LUN remains disabled after upgrading to ONTAP 9.15.1. 

.Steps

. Enable space allocation:
+
[source,cli]
----
lun modify -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -space-allocation enabled
----

. Verify that space allocation is enabled:
+
[source,cli]
----
lun show -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -fields space-allocation
----

. Verify that space allocation is enabled on the host OS. 
+
NOTE: Some host configurations, ESX in particular, can automatically recognize the setting change and do not require user intervention. Other configurations might require a device rescan. Some filesystems and volume managers might require additional specific settings to enable space reclamation using `SCSI UNMAP`. Remounting of filesystems or a full OS reboot might be required. Consult the documentation for your specific host for guidance. 

// 2024-7-17 ontapdoc-2220
// 2024 June 3, ONTAPDOC-2034
// 2024 Apr 16, Jira 1662
// 2023, Mar 18, Jira 1793
// 2023 Nov 15, Jira 1446
// 2023 Nov 08, Git Issue 1139
// 2023 Oct 30, Git Issue 1139
// 2022 Nov 4, Git Issue 689
