---
permalink: san-admin/example-how-igroups-give-lun-access-reference.html
sidebar: sidebar
keywords: ontap 9.2, example, how, igroups, give, lun, access
summary: "You can create multiple igroups to define which LUNs are available to your hosts. For example, if you have a host cluster, you can use igroups to ensure that specific LUNs are visible to only one host in the cluster or to all of the hosts in the cluster."
---
= Example of how igroups give LUN access
:icons: font
:imagesdir: ../media/

[.lead]
You can create multiple igroups to define which LUNs are available to your hosts. For example, if you have a host cluster, you can use igroups to ensure that specific LUNs are visible to only one host in the cluster or to all of the hosts in the cluster.

The following table illustrates how four igroups give access to the LUNs for four different hosts that are accessing the storage system. The clustered hosts (Host3 and Host4) are both members of the same igroup (group3) and can access the LUNs mapped to this igroup. The igroup named group4 contains the WWPNs of Host4 to store local information that is not intended to be seen by its partner.
[cols="4*",options="header"]
|===
| Hosts with HBA WWPNs, IQNs, or EUIs| igroups| WWPNs, IQNs, EUIs added to igroups| LUNs mapped to igroups
a|
Host1, single-path (iSCSI software initiator)

iqn.1991-05.com.microsoft:host1

a|
group1
a|
iqn.1991-05.com.microsoft:host1
a|
`/vol/vol2/lun1`
a|
Host2, multipath (two HBAs)

10:00:00:00:c9:2b:6b:3c

10:00:00:00:c9:2b:02:3c

a|
group2
a|
10:00:00:00:c9:2b:6b:3c

10:00:00:00:c9:2b:02:3c

a|
`/vol/vol2/lun2`
a|
Host3, multipath, clustered with host 4

10:00:00:00:c9:2b:32:1b

10:00:00:00:c9:2b:41:02

a|
group3
a|
10:00:00:00:c9:2b:32:1b

10:00:00:00:c9:2b:41:02

10:00:00:00:c9:2b:51:2c

10:00:00:00:c9:2b:47:a2

a|
`/vol/vol2/qtree1/lun3`
a|
Host4, multipath, clustered (not visible to Host3)

10:00:00:00:c9:2b:51:2c

10:00:00:00:c9:2b:47:a2

a|
group4
a|
10:00:00:00:c9:2b:51:2c

10:00:00:00:c9:2b:47:a2

a|
`/vol/vol2/qtree2/lun4` `/vol/vol2/qtree1/lun5`

|===
