---
permalink: san-admin/examine-configured-used-space-lun-task.html
sidebar: sidebar
keywords: examine, configured, used, space, lun
summary: "Knowing the configured space and actual space used for your LUNs can help you determine the amount of space that can be reclaimed when doing space reclamation, the amount of reserved space that contains data, and the total configured size versus the actual size used for a LUN."
---
= Examine configured and used space of a LUN
:icons: font
:imagesdir: ../media/

[.lead]
Knowing the configured space and actual space used for your LUNs can help you determine the amount of space that can be reclaimed when doing space reclamation, the amount of reserved space that contains data, and the total configured size versus the actual size used for a LUN.

.Step

. View the configured space versus the actual space used for a LUN:
+
`lun show`
+
The following example show the configured space versus the actual space used by the LUNs in the vs3 storage virtual machine (SVM):
+
`lun show -vserver vs3 -fields path, size, size-used, space-reserve`
+
----
vserver path                    size    space-reserve size-used
------- -----------------       ------- ------------- ---------
vs3     /vol/vol0/lun1          50.01GB disabled      25.00GB
vs3     /vol/vol0/lun1_backup   50.01GB disabled      32.15GB
vs3     /vol/vol0/lun2          75.00GB disabled      0B
vs3     /vol/volspace/lun0      5.00GB  enabled       4.50GB
4 entries were displayed.
----
+
Learn more about `lun show` in the link:https://docs.netapp.com/us-en/ontap-cli/lun-show.html[ONTAP command reference^].

// 2025 Apr 24, ONTAPDOC-2960