---
permalink: san-admin/flexclone-luns-protect-your-data-concept.html
sidebar: sidebar
keywords: use, flexclone, luns, protect, your, data
summary: "A FlexClone LUN is a point-in-time, writeable copy of another LUN in an active volume or in a snapshot. The clone and its parent can be modified independently without affecting each other."
---
= Use FlexClone LUNs to protect your data overview
:icons: font
:imagesdir: ../media/

[.lead]
A FlexClone LUN is a point-in-time, writeable copy of another LUN in an active volume or in a snapshot. The clone and its parent can be modified independently without affecting each other.

A FlexClone LUN shares space initially with its parent LUN. By default, the FlexClone LUN inherits the space-reserved attribute of the parent LUN. For example, if the parent LUN is non-space-reserved, the FlexClone LUN is also non-space-reserved by default. However, you can create a non-space-reserved FlexClone LUN from a parent that is a space-reserved LUN.

When you clone a LUN, block sharing occurs in the background and you cannot create a volume snapshot until the block sharing is finished.

You must configure the volume to enable the FlexClone LUN automatic deletion function with the `volume snapshot autodelete modify` command. Otherwise, if you want FlexClone LUNs to be deleted automatically but the volume is not configured for FlexClone auto delete, none of the FlexClone LUNs are deleted.

When you create a FlexClone LUN, the FlexClone LUN automatic deletion function is disabled by default. You must manually enable it on every FlexClone LUN before that FlexClone LUN can be automatically deleted. If you are using semi-thick volume provisioning and you want the "`best effort`" write guarantee provided by this option, you must make _all_ FlexClone LUNs available for automatic deletion.

[NOTE]
====
When you create a FlexClone LUN from a snapshot, the LUN is automatically split from the snapshot by using a space-efficient background process so that the LUN does not continue to depend on the snapshot or consume any additional space. If this background split has not been completed and this snapshot is automatically deleted, that FlexClone LUN is deleted even if you have disabled the FlexClone auto delete function for that FlexClone LUN. After the background split is complete, the FlexClone LUN is not deleted even if that snapshot is deleted.
====

.Related information

link:../volumes/index.html[Logical storage management]
