---
permalink: san-admin/flexclone-luns-protect-your-data-concept.html
sidebar: sidebar
keywords: use, flexclone, luns, protect, your, data
summary: "A FlexClone LUN is a point-in-time, writeable copy of another LUN in an active volume or in a snapshot. The clone and its parent can be modified independently without affecting each other."
---
= Protect your data with ONTAP FlexClone LUNs
:icons: font
:imagesdir: ../media/

[.lead]
A FlexClone LUN is a point-in-time, writeable copy of another LUN in an active volume or in a snapshot. The clone and its parent can be modified independently without affecting each other.

You can use FlexClone LUNs to create multiple read/write copies of a LUN.

.Reasons to create FlexClone LUNs 

* You need to create a temporary copy of a LUN for testing purposes.
* You need to make a copy of your data available to additional users without giving them access to the production data.
* You want to create a clone of a database for manipulation and projection operations, while preserving the original data in an unaltered form.
* You want to access a specific subset of a LUN's data (a specific logical volume or file system in a volume group, or a specific file or set of files in a file system) and copy it to the original LUN, without restoring the rest of the data in the original LUN. This works on operating systems that support mounting a LUN and a clone of the LUN at the same time. SnapDrive for UNIX supports this with the `snap connect` command.
* You need multiple SAN boot hosts with the same operating system.

A FlexClone LUN shares space initially with its parent LUN. By default, the FlexClone LUN inherits the space-reserved attribute of the parent LUN. For example, if the parent LUN is non-space-reserved, the FlexClone LUN is also non-space-reserved by default. However, you can create a non-space-reserved FlexClone LUN from a parent that is a space-reserved LUN.

When you clone a LUN, block sharing occurs in the background and you cannot create a volume snapshot until the block sharing is finished.

You must configure the volume to enable the FlexClone LUN automatic deletion function with the `volume snapshot autodelete modify` command. Otherwise, if you want FlexClone LUNs to be deleted automatically but the volume is not configured for FlexClone auto delete, none of the FlexClone LUNs are deleted.

When you create a FlexClone LUN, the FlexClone LUN automatic deletion function is disabled by default. You must manually enable it on every FlexClone LUN before that FlexClone LUN can be automatically deleted. If you are using semi-thick volume provisioning and you want the "`best effort`" write guarantee provided by this option, you must make _all_ FlexClone LUNs available for automatic deletion.

[NOTE]
====
When you create a FlexClone LUN from a snapshot, the LUN is automatically split from the snapshot by using a space-efficient background process so that the LUN does not continue to depend on the snapshot or consume any additional space. If this background split has not been completed and this snapshot is automatically deleted, that FlexClone LUN is deleted even if you have disabled the FlexClone auto delete function for that FlexClone LUN. After the background split is complete, the FlexClone LUN is not deleted even if that snapshot is deleted.
====

.Related information

* link:../volumes/create-flexclone-file-flexclone-lun-task.html[Create a FlexClone LUN].
* link:../volumes/configure-flexvol-delete-flexclone-files-luns-task.html[Configure a FlexVol volume to automatically delete FlexClone LUNs].
* link:../volumes/prevent-flexclone-file-lun-automatic-deleted-task.html[Prevent a FlexClone LUN from being automatically deleted].

// 2025 Apr 22, ONTAPDOC-2974


