---
permalink: san-admin/increase-size-lun-task.html
sidebar: sidebar
keywords: increase, size, lun
summary: "Beginning with ONTAP 9.5, you can grow your LUN up to 16 TB regardless of its original size. In ONTAP 9.4 and earlier, you can only grow your LUN to approximately 10 times its original size, but not greater than 16 TB."
---
= Increase the size of a LUN
:icons: font
:imagesdir: ../media/

[.lead]
The size to which you can increase your LUN varies depending upon your version of ONTAP.

[cols=2, options="header"]
|===
| ONTAP version
| Maximum LUN size

| ONTAP 9.8 and later
a|
* 128 TB for All SAN Arrays (ASAs)
* 16 TB for non-ASAs

| ONTAP 9.5, 9.6,  9.7
| 16TB

| ONTAP 9.4 or earlier
| 10 times the original LUN size, but not greater than 16TB

For example, if you create a 100 GB LUN, you can only grow it to 1,000 GB.
|===

You do not need to take the LUN offline to increase the size. However, after you have increased the size, you must rescan the LUN on the host for the host to recognize the change in size.

See the Command Reference page for the `lun resize` command for more information about resizing a LUN.

[NOTE]
====
Solaris LUNs cannot be resized.
====

.Steps

. Increase the size of the LUN:
+
`lun resize -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -size _lun_size_`
. Verify the increased LUN size:
+
`lun show -vserver _vserver_name_`
+
[NOTE]
====
ONTAP operations round down the actual maximum size of the LUN so it is slightly less than the expected value. Also, actual LUN size might vary slightly based on the OS type of the LUN. To obtain the exact resized value, run the following commands in advanced mode:

`set -unit B`

`lun show -fields max-resize-size -volume _volume_name_ -lun _lun_name_`
====

. Rescan the LUN on the host.
. Follow your host documentation to make the newly created LUN size visible to the host file system.
