---
permalink: san-admin/index.html
sidebar: sidebar
keywords: decide, san, administration, host, provisioning, iscsi, fc, nvme
summary: "This content describes basic SAN host provisioning."
---
= SAN administration overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes basic SAN host provisioning. It shows you how to configure and manage LUNs, igroups, and targets using the iSCSI and FC protocols, and namespaces and subsystems using the NVMe/FC protocol.

*You should use this content* under the following circumstances:

* You want to understand the range of ONTAP SAN host provisioning capabilities.
* You want to perform less common configuration and maintenance tasks, not basic SAN configuration.
* You want to use the command-line interface (CLI), not ONTAP System Manager or an automated scripting tool.

*If you want to use ONTAP System Manager* to provision SAN hosts, you should choose the following documentation:

* https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help/GUID-DF04A607-30B0-4B98-99C8-CB065C64E670.html[Cluster management using System Manager] (for ONTAP 9.6 and earlier)
* https://docs.netapp.com/us-en/ontap/[NetApp Documentation: ONTAP System Manager] (for ONTAP 9.7 and later)

*If you want to create a basic SAN configuration using best practices*, you should choose among the following documentation:

* FC configuration for Windows
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-cpg/home.html[FC express configuration for Windows]

* FC configuration for ESX
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-esx-cpg/home.html[FC express configuration for ESXi using VSC]

* FC configuration for Red Hat Enterprise Linux
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-rhel-cg/home.html[FC express configuration for Red Hat Enterprise Linux]

* iSCSI configuration for Windows
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-cpg/home.html[iSCSI express configuration for Windows]

* iSCSI configuration for ESX
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-esx-cpg/home.html[iSCSI express configuration for ESXi using VSC]

* iSCSI configuration for Red Hat Enterprise Linux
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-rhel-cg/home.html[iSCSI express configuration for Red Hat Enterprise Linux]

*If you want to configure SAN host* you should use the following documentation:

* https://docs.netapp.com/us-en/ontap-sanhost/[NetApp Documentation: ONTAP SAN Host Configuration]

*If you require additional configuration or conceptual information*, you should choose among the following documentation:

* Best Practices for Scalable SAN
+
http://www.netapp.com/us/media/tr-4080.pdf[NetApp Technical Report 4080: Best Practices for Scalable SAN ONTAP 9]

* Conceptual background for SAN host provisioning
+
https://docs.netapp.com/us-en/ontap/concepts/index.html[ONTAP concepts]

* Configuration for All SAN Arrays
+
https://www.netapp.com/data-storage/san-storage-area-network/documentation/[All SAN Array documentation resources]

* Supported FC, iSCSI, NVMe/FC, and FCoE topologies for connecting host computers to nodes
+
https://docs.netapp.com/us-en/ontap/san-config/index.html[SAN configuration]

* FlexVol volumes, FlexClone technology, and storage efficiency features
+
https://docs.netapp.com/us-en/ontap/volumes/index.html[Logical storage management]

* Command reference
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands]

* Automation of management tasks
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61550[NetApp Documentation: OnCommand Workflow Automation (current releases)]

* SAN host and controller configuration limits
+
https://hwu.netapp.com[NetApp Hardware Universe]
