---
permalink: san-admin/lif-movement-concept.html
sidebar: sidebar
keywords: considerations, san, lif, movement
summary: "You only need to perform a LIF movement if you are changing the contents of your cluster, for example, adding nodes to the cluster or deleting nodes from the cluster. If you perform a LIF movement, you do not have to re-zone your FC fabric or create new iSCSI sessions between the attached hosts of your cluster and the new target interface."
---
= Considerations for SAN LIF movement
:icons: font
:imagesdir: ../media/

[.lead]
You only need to perform a LIF movement if you are changing the contents of your cluster, for example, adding nodes to the cluster or deleting nodes from the cluster. If you perform a LIF movement, you do not have to re-zone your FC fabric or create new iSCSI sessions between the attached hosts of your cluster and the new target interface.

You cannot move a SAN LIF using the `network interface move` command. SAN LIF movement must be performed by taking the LIF offline, moving the LIF to a different home node or port, and then bringing it back online in its new location. Asymmetric Logical Unit Access (ALUA) provides redundant paths and automatic path selection as part of any ONTAP SAN solution. Therefore, there is no I/O interruption when the LIF is taken offline for the movement. The host simply retries and then moves I/O to another LIF.

Using LIF movement, you can nondisruptively do the following:

* Replace one HA pair of a cluster with an upgraded HA pair in a way that is transparent to hosts accessing LUN data
* Upgrade a target interface card
* Shift the resources of a storage virtual machine (SVM) from one set of nodes in a cluster to another set of nodes in the cluster
