---
permalink: san-admin/lun-san-environments-concept.html
sidebar: sidebar
keywords: lun, guidelines
summary: "Before you begin setting up your LUNs on your cluster, you need to review LUN guidelines."
---
= LUN guidelines
:icons: font
:imagesdir: ../media/

[.lead]
The FC protocol and iSCSI protocol both provision storage through the use of LUNs. After you have setup your LUNs, you can perform various management tasks, such as increasing or decreasing the size of a LUN. After configuring your volume and setting the appropriate OS type, you must complete the steps that are necessary to setup your LUN.

== Prerequisites for setting up LUNs

Setting up LUNs involves creating a LUN, creating an igroup, and mapping the LUN to the igroup. Your system must meet certain prerequisites before you can set up your LUNs.

* The https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] must list your SAN configuration as supported.
* Your SAN environment must meet the SAN host and controller configuration limits specified in https://hwu.netapp.com[NetApp Hardware Universe^] for your version of the ONTAP software.
* A supported version of Host Utilities must be installed.
+
See https://docs.netapp.com/us-en/ontap-sanhost/index.html[ONTAP SAN Host Configuration] documentation for more information.

* You must have SAN LIFs on the LUN owning node and the owning node's HA partner.

== Guidelines for assigning LUN IDs

Typically, the default LUN ID begins with 0 and is assigned in increments of 1 for each additional mapped LUN. The host associates the LUN ID with the location and path name of the LUN. The range of valid LUN ID numbers depends on the host. For detailed information, see the documentation provided with your Host Utilities.

== Guidelines for mapping LUNs to igroups

* You can map a LUN to only one igroup.
* You can map a LUN to only one specific initiator through the igroup.
* You can add a single initiator to multiple igroups, but the initiator can be mapped to only one LUN.
* You cannot use the same LUN ID for two LUNs mapped to the same igroup.
* You should use the same protocol type for igroups and port sets.
