---
permalink: san-admin/map-nvme-namespace-subsystem-task.html
sidebar: sidebar
keywords: map, nvme, namespace, subsystem
summary: "You must map a namespace to a subsystem when using NVMe."
---
= Map an NVMe namespace to a subsystem
:icons: font
:imagesdir: ../media/

[.lead]
This procedure maps an NVMe namespace to a subsystem using the ONTAP CLI.  

Your namespace and subsystem should already be created.  If you need to create a namespace and subsystem, see link:create-nvme-namespace-subsystem-task.html[Provision NVMe storage].

.Steps

. Obtain the NQN from the host.

. Add the host NQN to the subsystem:
+
`vserver nvme subsystem host add -vserver _SVM_name_ -subsystem _subsystem_name_ -host-nqn _Host_NQN_:subsystem._subsystem_name_`

. Map the namespace to the subsystem:
+
`vserver nvme subsystem map add -vserver _SVM_name_ -subsystem _subsystem_name_ -path _path_`
+
A namespace can only be mapped to a single subsystem.

. Verify that the namespace is mapped to the subsystem:
+
`vserver nvme namespace show -vserver _SVM_name_ -instance`
+
The subsystem should be listed as the `Attached subsystem`.