---
permalink: san-admin/modify-slm-reporting-nodes-task.html
sidebar: sidebar
keywords: modify, slm, reporting-nodes, list
summary: "If you are moving a LUN or a volume containing LUNs to another high availability (HA) pair within the same cluster, you should modify the Selective LUN Map (SLM) reporting-nodes list before initiating the move to ensure that active, optimized LUN paths are maintained."
---
= Modify the SLM reporting-nodes list
:icons: font
:imagesdir: ../media/

[.lead]
If you are moving a LUN or a volume containing LUNs to another high availability (HA) pair within the same cluster, you should modify the Selective LUN Map (SLM) reporting-nodes list before initiating the move to ensure that active, optimized LUN paths are maintained.

.Steps

. Add the destination node and its partner node to the reporting-nodes list of the aggregate or volume:
+
`lun mapping add-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ [-destination-aggregate _aggregate_name_|-destination-volume _volume_name_]`
+
If you have a consistent naming convention, you can modify multiple LUN mappings at the same time by using `*-igroup*` instead of `igroup`.

. Rescan the host to discover the newly added paths.
. If your OS requires it, add the new paths to your multipath network I/O (MPIO) configuration.
. Run the command for the needed move operation and wait for the operation to finish.
. Verify that I/O is being serviced through the Active/Optimized path:
+
`lun mapping show -fields reporting-nodes`
. Remove the previous LUN owner and its partner node from the reporting-nodes list:
+
`lun mapping remove-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ -remote-nodes`
. Verify that the LUN has been removed from the existing LUN map:
+
`lun mapping show -fields reporting-nodes`
. Remove any stale device entries for the host OS.
. Change any multipathing configuration files if required.
. Rescan the host to verify removal of old paths. +
 See your host documentation for specific steps to rescan your hosts.
