---
permalink: san-admin/move-san-lifs-task.html
sidebar: sidebar
keywords: move, san, lifs
summary: "If a node needs to be taken offline, you can move a SAN LIF to preserve its configuration information, such as its WWPN, and avoid rezoning the switch fabric. Because a SAN LIF must be taken offline before it is moved, host traffic must rely on host multipathing software to provide nondisruptive access to the LUN. You can move SAN LIFs to any node in a cluster, but you cannot move the SAN LIFs between storage virtual machines (SVMs)."
---
= Move a SAN LIF
:icons: font
:imagesdir: ../media/

[.lead]
If a node needs to be taken offline, you can move a SAN LIF to preserve its configuration information, such as its WWPN, and avoid rezoning the switch fabric. Because a SAN LIF must be taken offline before it is moved, host traffic must rely on host multipathing software to provide nondisruptive access to the LUN. You can move SAN LIFs to any node in a cluster, but you cannot move the SAN LIFs between storage virtual machines (SVMs).

.Before you begin

If the LIF is a member of a port set, the LIF must have been removed from the port set before the LIF can be moved to a different node.

.About this task

The destination node and physical port for a LIF that you want to move must be on the same FC fabric or Ethernet network. If you move a LIF to a different fabric that has not been properly zoned, or if you move a LIF to an Ethernet network that does not have connectivity between iSCSI initiator and target, the LUN will be inaccessible when you bring it back online.

.Steps

. View the administrative and operational status of the LIF:
+
`network interface show -vserver _vserver_name_`
. Change the status of the LIF to `down` (offline):
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -status-admin down`
+
Learn more about `network interface modify` in the link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html[ONTAP command reference^].
. Assign the LIF a new node and port:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _node_name_ -home-port _port_name_`
. Change the status of the LIF to `up` (online):
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -status-admin up`
+
Learn more about `up` in the link:https://docs.netapp.com/us-en/ontap-cli/up.html[ONTAP command reference^].
. Verify your changes:
+
`network interface show -vserver _vserver_name_`

// 2025 Apr 28, ONTAPDOC-2960