---
permalink: san-admin/move-san-lifs-task.html
sidebar: sidebar
keywords: move, san, lifs
summary: "If a node needs to be taken offline, you can move a SAN LIF to preserve its configuration information, such as its WWPN, and avoid rezoning the switch fabric."
---
= Move an ONTAP SAN LIF
:icons: font
:imagesdir: ../media/

[.lead]
If a node needs to be taken offline, you can move a SAN LIF to preserve its configuration information, such as its WWPN.  Moving a LIF does not require re-zoning your FC fabric or creating new iSCSI sessions between cluster hosts and the target interface. You can move SAN LIFs to any node in the cluster, but not between storage virtual machines (SVMs).

You can move a LIF to nondisruptively do the following:

* Replace one HA pair of a cluster with an upgraded HA pair in a way that is transparent to hosts accessing LUN or namespace data
* Upgrade a target interface card
* Shift the resources of a storage virtual machine (SVM) from one set of nodes in a cluster to another set of nodes in the cluster

You cannot move a SAN LIF using the `network interface move` command. To move a SAN LIF, you must take it offline, move it to a new home node or port, and then bring it back online. Because a SAN LIF must be taken offline before it is moved, host traffic must rely on host multipathing software to provide nondisruptive access to the LUN. so that tere is no I/O interruption. 


.Before you begin

If the LIF is a member of a port set, the LIF must have been removed from the port set before the LIF can be moved to a different node.

.About this task

The destination node and physical port for a LIF that you want to move must be on the same FC fabric or Ethernet network. If you move a LIF to a different fabric that has not been properly zoned, or if you move a LIF to an Ethernet network that does not have connectivity between iSCSI initiator and target, the LUN will be inaccessible when you bring it back online.

.Steps

. View the administrative and operational status of the LIF:
+
[source,cli]
----
network interface show -vserver <SVM_name>
----
+
Learn more about `network interface show` in the link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html[ONTAP command reference^].

. Change the status of the LIF to `down` (offline):
+
[source,cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -status-admin down
----
+
Learn more about `network interface modify` in the link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html[ONTAP command reference^].

. Assign the LIF a new node and port:
+
[source,cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -home-node <node_name> -home-port <port_name>
----
. Change the status of the LIF to `up` (online):
+
[source,cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -status-admin up
----

. Verify your changes:
+
[source,cli]
----
network interface show -vserver <SVM_name>
----

// 2026 May 7, ONTAPDOC-3573
// 2025 Apr 29, ONTAPDOC-2960