---
permalink: san-admin/nvme-namespaces-considerations-concept.html
sidebar: sidebar
keywords: nvme, namespaces, considerations
summary: "To set up the NVMe protocol in your SAN environment, you must configure an SVM for NVMe, create namespaces and subsystems, configure an NVMe/FC LIF, and then map the namespaces to the subsystems."
---
= NVMe namespaces considerations
:icons: font
:imagesdir: ../media/

[.lead]
To set up the NVMe protocol in your SAN environment, you must configure an SVM for NVMe, create namespaces and subsystems, configure an NVMe/FC LIF, and then map the namespaces to the subsystems. There are certain considerations you should be aware of when working with NVMe namespaces.

* If you lose data in a LUN, it cannot be restored from a namespace, or vice versa.
* The space guarantee for namespaces is the same as the space guarantee of the containing volume.
* Beginning with ONTAP 9.6, namespaces support 512 byte blocks and 4096 byte blocks.
+
4096 is the default value. 512 should only be used if the host operating system does not support 4096 byte blocks.

* Namespaces do not support the following:
 ** Renaming
+
You cannot rename a namespace.

 ** Resizing
+
You cannot increase or decrease the size of a namespace.

 ** Inter-volume move
 ** Inter-volume copy
