---
permalink: san-admin/prerequisites-setup-luns-concept.html
sidebar: sidebar
keywords: prerequisites, setting up, luns, setup, san, provisioning, provision, system, requirements
summary: 'Setting up LUNs involves creating a LUN, creating an igroup, and mapping the LUN to the igroup. Your system must meet certain prerequisites before you can set up your LUNs.'
---
= System requirements to provision SAN storage
:icons: font
:imagesdir: ../media/

[.lead]
The FC protocol and iSCSI protocol both provision storage through the use of LUNs. This process involves creating a LUN, creating an igroup, and mapping the LUN to the igroup. Your system must meet certain requirements before you can set up your LUNs.

* The https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] must list your SAN configuration as supported.
* Your SAN environment must meet the SAN host and controller configuration limits specified in https://hwu.netapp.com[NetApp Hardware Universe^] for your version of the ONTAP software.
* A supported version of Host Utilities must be installed.
+
See https://docs.netapp.com/us-en/ontap-sanhost/index.html[ONTAP SAN Host Configuration] documentation for more information.

* You must have SAN LIFs on the LUN owning node and the owning node's HA partner.

.Related information

https://docs.netapp.com/us-en/ontap-sanhost/index.html[ONTAP SAN Host Configuration]

http://www.netapp.com/us/media/tr-4017.pdf[NetApp Technical Report 4017: Fibre Channel SAN Best Practices]
