---
permalink: san-admin/remove-lif-from-portset-task.html
sidebar: sidebar
keywords: remove, san, lif, port, set
summary: "If the LIF you want to delete or move is in a port set, you must remove the LIF from the port set before you can delete or move the LIF."
---
= Remove a SAN LIF from a port set
:icons: font
:imagesdir: ../media/

[.lead]
If the LIF you want to delete or move is in a port set, you must remove the LIF from the port set before you can delete or move the LIF.

.About this task

You need to do Step 1 in the following procedure only if one LIF is in the port set. You cannot remove the last LIF in a port set if the port set is bound to an initiator group. Otherwise, you can start with Step 2 if multiple LIFs are in the port set.

.Steps

. If only one LIF is in the port set, use the `lun igroup unbind` command to unbind the port set from the initiator group.
+
[NOTE]
====
When you unbind an initiator group from a port set, all of the initiators in the initiator group have access to all target LUNs mapped to the initiator group on all network interfaces.
====
+
`cluster1::>lun igroup unbind -vserver vs1 -igroup ig1`
+
Learn more about `lun igroup unbind` in the link:https://docs.netapp.com/us-en/ontap-cli/lun-igroup-unbind.html[ONTAP command reference^].

. Use the `lun portset remove` command to remove the LIF from the port set.
+
`cluster1::> port set remove -vserver vs1 -portset ps1 -port-name lif1`
+
Learn more about `lun portset remove` in the link:https://docs.netapp.com/us-en/ontap-cli/lun-portset-remove.html[ONTAP command reference^].

// 2025 Apr 24, ONTAPDOC-2960