---
permalink: san-admin/requirements-odx-concept.html
sidebar: sidebar
keywords: microsoft Offloaded Data Transfer, using, odx
summary: "If you plan to use ODX for copy offloads, you need to be familiar with volume support considerations, system requirements, and software capability requirements."
---
= Requirements for using ODX
:icons: font
:imagesdir: ../media/

[.lead]
If you plan to use ODX for copy offloads, you need to be familiar with volume support considerations, system requirements, and software capability requirements.

To use ODX, your system must have the following:

* ONTAP
+
ODX is automatically enabled in supported versions of ONTAP.

* Minimum source volume of 2 GB
+
For optimal performance, the source volume should be greater than 260 GB.

* Deduplication
+
ODX uses deduplication as part of the copy process. If you do not want deduplication on your SVM, you should disable ODX on that SVM.

* ODX support on the Windows client
+
ODX is supported in Windows Server 2012 or later and in Windows 8 or later. The Interoperability Matrix contains the latest information about supported Windows clients.
+
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

* Copy application support for ODX
+
The application that performs the data transfer must support ODX. Application operations that support ODX include the following:

 ** Hyper-V management operations, such as creating and converting virtual hard disks (VHDs), managing Snapshot copies, and copying files between virtual machines
 ** Windows Explorer operations
 ** Windows PowerShell copy commands
 ** Windows command prompt copy commands
The Microsoft TechNet Library contains more information about supported ODX applications on Windows servers and clients.

* If you use compressed volumes, the compression group size must be 8K.
+
32K compression group size is not supported.

ODX does not work with the following volume types:

* Source volumes with capacities of less than 2 GB
* Sparse volumes
* Read-only volumes
* Semi-thick provisioned volumes
