---
permalink: san-admin/san-provisioning-nvme-concept.html
sidebar: sidebar
keywords: san, provisioning, nvme
summary: "Beginning with ONTAP 9.4, NVMe/FC is supported in SAN environment. NVMe/FC enables storage administrators to provision namespaces and subsystems and then map the namespaces to subsystems, similar to the way LUNs are provisioned and mapped to igroups for FC and iSCSI."
---
= SAN provisioning with NVMe
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.4, NVMe/FC is supported in SAN environment. NVMe/FC enables storage administrators to provision namespaces and subsystems and then map the namespaces to subsystems, similar to the way LUNs are provisioned and mapped to igroups for FC and iSCSI.

An NVMe namespace is a quantity of non-volatile memory that can be formatted into logical blocks. Namespaces are the equivalent of LUNs for FC and iSCSI protocols, and an NVMe subsystem is analogous to an igroup. An NVMe subsystem can be associated with initiators so that namespaces within the subsystem can be accessed by the associated initiators.

[NOTE]
====
Although analogous in function, NVMe namespaces do not support all features supported by LUNs.
====

Beginning with ONTAP 9.5 a license is required to support host-facing data access with NVMe. If NVMe is enabled in ONTAP 9.4, a 90 day grace period is given to acquire the license after upgrading to ONTAP 9.5. If you have link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one[ONTAP One], the NVMe licenses is included. You can enable the license using the following command:

`system license add -license-code _NVMe_license_key_`

.Related information

https://www.netapp.com/pdf.html?item=/media/10681-tr4684pdf.pdf[NetApp Technical Report 4684: Implementing and Configuring Modern SANs with NVMe/FC^]

// 2024-Mar-28, ONTAPDOC-1366