---
permalink: san-admin/selective-lun-map-concept.html
sidebar: sidebar
keywords: select, selective, lun, map, slm, enabled, modify, reporting, nodes, list
summary: "Selective LUN Map (SLM) reduces the number of paths from the host to the LUN. With SLM, when a new LUN map is created, the LUN is accessible only through paths on the node owning the LUN and its HA partner."
---
= Selective LUN Map overview 
:icons: font
:imagesdir: ../media/

[.lead]
Selective LUN Map (SLM) reduces the number of paths from the host to the LUN. With SLM, when a new LUN map is created, the LUN is accessible only through paths on the node owning the LUN and its HA partner.

SLM enables management of a single igroup per host and also supports nondisruptive LUN move operations that do not require portset manipulation or LUN remapping.

Portsets can be used with SLM to further restrict access of certain targets to certain initiators. When using SLM with portsets, LUNs will be accessible on the set of LIFs in the portset on the node that owns the LUN and on that node's HA partner.

SLM is enabled by default on all new LUN maps.

== Determine whether SLM is enabled on a LUN map

If your environment has a combination of LUNs created in an ONTAP 9 release and LUNs transitioned from previous versions, you might need to determine whether Selective LUN Map (SLM) is enabled on a specific LUN.

You can use the information displayed in the output of the `lun mapping show -fields reporting-nodes, node` command to determine whether SLM is enabled on your LUN map. If SLM is not enabled, "-" is displayed in the cells under the "`reporting-nodes`" column of the command output. If SLM is enabled, the list of nodes displayed under the "`nodes`" column is duplicated in the "`reporting-nodes`" column.

== Modify the SLM reporting-nodes list

If you are moving a LUN or a volume containing LUNs to another high availability (HA) pair within the same cluster, you should modify the Selective LUN Map (SLM) reporting-nodes list before initiating the move to ensure that active, optimized LUN paths are maintained.

.Steps

. Add the destination node and its partner node to the reporting-nodes list of the aggregate or volume:
+
`lun mapping add-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ [-destination-aggregate _aggregate_name_|-destination-volume _volume_name_]`
+
If you have a consistent naming convention, you can modify multiple LUN mappings at the same time by using `_igroup_prefix*_` instead of `_igroup_name_`.

. Rescan the host to discover the newly added paths.
. If your OS requires it, add the new paths to your multipath network I/O (MPIO) configuration.
. Run the command for the needed move operation and wait for the operation to finish.
. Verify that I/O is being serviced through the Active/Optimized path:
+
`lun mapping show -fields reporting-nodes`
. Remove the previous LUN owner and its partner node from the reporting-nodes list:
+
`lun mapping remove-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ -remote-nodes`
. Verify that the LUN has been removed from the existing LUN map:
+
`lun mapping show -fields reporting-nodes`
. Remove any stale device entries for the host OS.
. Change any multipathing configuration files if required.
. Rescan the host to verify removal of old paths. +
 See your host documentation for specific steps to rescan your hosts.

// 2023 Jul 26, ONTAPDOC-1097
