---
permalink: san-admin/set-fractional-reserve-concept.html
sidebar: sidebar
keywords: considerations, setting, fractional, reserve
summary: "Fractional reserve, also called LUN overwrite reserve, enables you to turn off overwrite reserve for space-reserved LUNs and files in a FlexVol volume. This can help you maximize your storage utilization, but if your environment is negatively affected by write operations failing due to lack of space, you must understand the requirements that this configuration imposes."
---
= Considerations for setting fractional reserve
:icons: font
:imagesdir: ../media/

[.lead]
Fractional reserve, also called _LUN overwrite reserve_, enables you to turn off overwrite reserve for space-reserved LUNs and files in a FlexVol volume. This can help you maximize your storage utilization, but if your environment is negatively affected by write operations failing due to lack of space, you must understand the requirements that this configuration imposes.

The fractional reserve setting is expressed as a percentage; the only valid values are `0` and `100` percent. The fractional reserve setting is an attribute of the volume.

Setting fractional reserve to `0` increases your storage utilization. However, an application accessing data residing in the volume could experience a data outage if the volume is out of free space, even with the volume guarantee set to `volume`. With proper volume configuration and use, however, you can minimize the chance of writes failing. ONTAP provides a "`best effort`" write guarantee for volumes with fractional reserve set to `0` when _all_ of the following requirements are met:

* Deduplication is not in use
* Compression is not in use
* FlexClone sub-files are not in use
* All FlexClone files and FlexClone LUNs are enabled for automatic deletion
+
This is not the default setting. You must explicitly enable automatic deletion, either at creation time or by modifying the FlexClone file or FlexClone LUN after it is created.

* ODX and FlexClone copy offload are not in use
* Volume guarantee is set to `volume`
* File or LUN space reservation is `enabled`
* Volume Snapshot reserve is set to `0`
* Volume snapshot automatic deletion is `enabled` with a commitment level of `destroy`, a destroy list of `lun_clone,vol_clone,cifs_share,file_clone,sfsr`, and a trigger of `volume`
+
This setting also ensures that FlexClone files and FlexClone LUNs are deleted when necessary.

Note that if your rate of change is high, in rare cases the snapshot automatic deletion could fall behind, resulting in the volume running out of space, even with all of the above required configuration settings in use.

In addition, you can optionally use the volume autogrow capability to decrease the likelihood of volume snapshots needing to be deleted automatically. If you enable the autogrow capability, you must monitor the free space in the associated aggregate. If the aggregate becomes full enough that the volume is prevented from growing, more snapshots will probably be deleted as the free space in the volume is depleted.

If you cannot meet all of the above configuration requirements and you need to ensure that the volume does not run out of space, you must set the volume's fractional reserve setting to `100`. This requires more free space up front, but guarantees that data modification operations will succeed even when the technologies listed above are in use.

The default value and allowed values for the fractional reserve setting depend on the guarantee of the volume:
[cols="3*",options="header"]
|===
| Volume guarantee| Default fractional reserve| Allowed values
a|
Volume
a|
100
a|
0, 100
a|
None
a|
0
a|
0, 100
|===
