---
permalink: san-admin/space-reserved-luns-semi-thick-provisioning-concept.html
sidebar: sidebar
keywords: configuration, settings, space-reserved files, luns, semi-thick, volume, provisioning
summary: "This FlexVol volume and file or LUN configuration combination requires less storage to be allocated up front than the fully provisioned combination, but places restrictions on the efficiency technologies you can use for the volume. Overwrites are fulfilled on a best-effort basis for this configuration combination."
---
= Configuration settings for space-reserved files or LUNs with semi-thick volume provisioning
:icons: font
:imagesdir: ../media/

[.lead]
This FlexVol volume and file or LUN configuration combination requires less storage to be allocated up front than the fully provisioned combination, but places restrictions on the efficiency technologies you can use for the volume. Overwrites are fulfilled on a best-effort basis for this configuration combination.

The following settings are required to configure a space-reserved LUN in a volume using semi-thick provisioning:
[cols="2*",options="header"]
|===
| Volume setting| Value
a|
Guarantee
a|
Volume
a|
Fractional reserve
a|
0
a|
Snapshot reserve
a|
0
a|
Snapshot autodelete
a|
On, with a commitment level of destroy, a destroy list that includes all objects, the trigger set to volume, and all FlexClone LUNs and FlexClone files enabled for automatic deletion.
a|
Autogrow
a|
Optional; if enabled, aggregate free space must be actively monitored.
|===
[cols="2*",options="header"]
|===
| File or LUN setting| Value
a|
Space reservation
a|
Enabled
|===

== Technology restrictions

You cannot use the following volume storage efficiency technologies for this configuration combination:

* Compression
* Deduplication
* ODX and FlexClone Copy Offload
* FlexClone LUNs and FlexClone files not marked for automatic deletion (active clones)
* FlexClone subfiles
* ODX/Copy Offload

== Additional considerations

The following facts must be considered when employing this configuration combination:

* When the volume that supports that LUN runs low on space, protection data (FlexClone LUNs and files, snapshots) is destroyed.
* Write operations can time out and fail when the volume runs out of free space.

Compression is enabled by default for AFF platforms. You must explicitly disable compression for any volume for which you want to use semi-thick provisioning on an AFF platform.
