---
permalink: smb-config/create-qtree-task.html
sidebar: sidebar
keywords: create, qtree, contain, data, specify, properties, property, volume, command, create a qtree
summary: "You can create a qtree to contain your data and specify its properties by using the volume qtree create command."
---
= Create ONTAP SMB qtrees
:icons: font
:imagesdir: ../media/

[.lead]
You can create a qtree to contain your data and specify its properties by using the `volume qtree create` command.

.Before you begin

* The SVM and the volume that will contain the new qtree must already exist.
* The SVM security style must be NTFS, and SMB should be set up and running.

.Steps

. Create the qtree: `volume qtree create -vserver vserver_name { -volume volume_name -qtree qtree_name | -qtree-path qtree path } -security-style ntfs`
+
You can specify the volume and qtree as separate arguments or specify the qtree path argument in the format `/vol/volume_name/_qtree_name`.

. Verify that the qtree was created with the desired junction path: `volume qtree show -vserver vserver_name { -volume volume_name -qtree qtree_name | -qtree-path qtree path }`

.Example

The following example creates a qtree named qt01 located on SVM vs1.example.com that has a junction path `/vol/data1`:

----
cluster1::> volume qtree create -vserver vs1.example.com -qtree-path /vol/data1/qt01 -security-style ntfs
[Job 1642] Job succeeded: Successful

cluster1::> volume qtree show -vserver vs1.example.com -qtree-path /vol/data1/qt01

                      Vserver Name: vs1.example.com
                       Volume Name: data1
                        Qtree Name: qt01
  Actual (Non-Junction) Qtree Path: /vol/data1/qt01
                    Security Style: ntfs
                       Oplock Mode: enable
                  Unix Permissions: ---rwxr-xr-x
                          Qtree Id: 2
                      Qtree Status: normal
                     Export Policy: default
        Is Export Policy Inherited: true
----

// 2025 Apr 30, ONTAPDOC-2981