---
permalink: smb-config/create-local-user-accounts-task.html
sidebar: sidebar
keywords: create, local, user, account, authorize, access, data, contain, svm, sb, connection, local, user, authentication, create local user accounts
summary: "You can create a local user account that can be used to authorize access to data contained in the SVM over an SMB connection. You can also use local user accounts for authentication when creating an SMB session."
---
= Create local user accounts
:icons: font
:imagesdir: ../media/

[.lead]
You can create a local user account that can be used to authorize access to data contained in the SVM over an SMB connection. You can also use local user accounts for authentication when creating an SMB session.

.About this task

Local user functionality is enabled by default when the SVM is created.

When you create a local user account, you must specify a user name and you must specify the SVM with which to associate the account.

The `vserver cifs users-and-groups local-user` man pages contain details about optional parameters and naming requirements.

.Steps

. Create the local user: `vserver cifs users-and-groups local-user create -vserver vserver_name -user-name user_name optional_parameters`
+
The following optional parameters might be useful:

 ** `-full-name`
+
The users's full name.

 ** `-description`
+
A description for the local user.

 ** `-is-account-disabled {true|false}`
+
Specifies whether the user account is enabled or disabled. If this parameter is not specified, the default is to enable the user account.

+
The command prompts for the local user's password.

. Enter a password for the local user, and then confirm the password.
. Verify that the user was successfully created: `vserver cifs users-and-groups local-user show -vserver vserver_name`

.Example

The following example creates a local user "`SMB_SERVER01\sue`", with a full name "`Sue Chang`", associated with SVM vs1.example.com:

----
cluster1::> vserver cifs users-and-groups local-user create -vserver vs1.example.com ‑user-name SMB_SERVER01\sue -full-name "Sue Chang"

Enter the password:
Confirm the password:

cluster1::> vserver cifs users-and-groups local-user show
Vserver  User Name                  Full Name  Description
-------- -------------------------- ---------- -------------
vs1      SMB_SERVER01\Administrator            Built-in administrator account
vs1      SMB_SERVER01\sue            Sue Chang
----
