---
permalink: smb-config/index.html
sidebar: sidebar
keywords:
summary: 'You can use ONTAP 9 CLI commands to configure SMB client access to files contained in a new volume or qtree in a new or existing SVM.'
---
= SMB configuration overview with the CLI
:icons: font
:imagesdir: ../media/

[.lead]
You can use ONTAP 9 CLI commands to configure SMB client access to files contained in a new volume or qtree in a new or existing SVM.

[NOTE]
====
_SMB_ (Server Message Block) refers to modern dialects of the Common Internet File System (CIFS) protocol. You will still see _CIFS_ in the ONTAP command-line interface (CLI) and in OnCommand management tools.
====

Use these procedures if you want to configure SMB access to a volume or qtree in the following way:

* You want to use SMB version 2 or later.
* You want to serve SMB clients only, not NFS clients (not a multiprotocol configuration).
* NTFS file permissions will be used to secure the new volume.
* You have cluster administrator privileges, not SVM administrator privileges.
+
Cluster administrator privileges are required to create SVMs and LIFs. SVM administrator privileges are sufficient for other SMB configuration tasks.

* You want to use the CLI, not System Manager or an automated scripting tool.
+
To use System Manager to configure NAS multiprotocol access, see link:../task_nas_provision_nfs_and_smb.html[Provision NAS storage for both Windows and Linux using both NFS and SMB].

* You want to use best practices, not explore every available option.
+
Learn more about the commands described in this procedure in the link:https://docs.netapp.com/us-en/ontap-cli/[ONTAP command reference^].

If you want details about the range of ONTAP SMB protocol capabilities, consult the link:../smb-admin/index.html[SMB reference overview].

== Other ways to do this in ONTAP

|===

h| To perform these tasks with... h| Refer to...

| The redesigned System Manager (available with ONTAP 9.7 and later) | link:../task_nas_provision_windows_smb.html[Provision NAS storage for Windows servers using SMB]
| System Manager Classic (available with ONTAP 9.7 and earlier) | link:https://docs.netapp.com/us-en/ontap-system-manager-classic/smb-config/index.html[SMB configuration overview^]

|===

// 2025 Feb 17, ONTAPDOC-2758
// 2022-01-10, BURT 1414474
// BURT 1415747, 09 DEC 2021
// BURT 1448684, 10 JAN 2022
