---
permalink: smb-config/index.html
sidebar: sidebar
keywords:
summary: 'This content describes how to use ONTAP 9 CLI commands to configure SMB client access to files contained in a new volume or qtree in a new or existing SVM. It includes examples and advanced configuration options.'
---
= SMB configuration overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to use ONTAP 9 CLI commands to configure SMB client access to files contained in a new volume or qtree in a new or existing SVM. It includes examples and advanced configuration options.

[NOTE]
====
_SMB_ (Server Message Block) refers to modern dialects of the Common Internet File System (CIFS) protocol. You will still see _CIFS_ in the ONTAP command-line interface (CLI) and in OnCommand management tools.
====

You should use this content if you want to configure SMB access to a volume or qtree in the following way:

* You want to use SMB version 2 or later.
* You want to serve SMB clients only, not NFS clients (not a multiprotocol configuration).
* NTFS file permissions will be used to secure the new volume.
* You have cluster administrator privileges, not SVM administrator privileges.
+
Cluster administrator privileges are required to create SVMs and LIFs. SVM administrator privileges are sufficient for other SMB configuration tasks.

* You want to use the CLI, not ONTAP System Manager or an automated scripting tool.

* You want to use best practices, not explore every available option.
+
Details about command syntax are available from CLI help and ONTAP man pages.

* You do not want to read a lot of conceptual background.
+
Additional information about ONTAP technology and interaction with external services is available in the ONTAP Reference Library and in Technical Reports (TRs).

If this content is not suitable for your situation, you should see the following documentation instead:

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands]
* https://docs.netapp.com/us-en/ontap-sm-classic/nas-multiprotocol-config/index.html[SMB and NFS multiprotocol configuration with System Manager]
* https://docs.netapp.com/us-en/ontap-sm-classic/smb-config/index.html[SMB configuration with System Manager]
* link:../smb-admin/index.html[SMB management]
* link:../networking/index.html[Network management]
* http://www.netapp.com/us/media/tr-4543.pdf[NetApp Technical Report 4543: SMB Protocol Best Practices]
* http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61550[NetApp Documentation: OnCommand Workflow Automation (current releases)]
+
OnCommand Workflow Automation enables you to run prepackaged workflows that automate management tasks.
