---
sidebar: networking-reference_sidebar
permalink: networking-reference/delete_a_broadcast_domain97.html
keywords: delete, deleting, remove, removing, broadcast, domain
summary: Delete unnecessary broadcast domains; this moves associated ports to the "Default" IPspace
---

= Delete a broadcast domain
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-23 12:34:44.230384
//

[.lead]
If you no longer need a broadcast domain, you can delete it. This moves the ports associated with that broadcast domain to the "Default" IPspace.

.Before you begin

There must be no subnets, network interfaces, or SVMs associated with the broadcast domain you want to delete.

.About this task

* The system-created "Cluster" broadcast domain cannot be deleted.
* All failover groups related to the broadcast domain are removed when you delete the broadcast domain.

.Step

Delete a broadcast domain:

....
network port broadcast-domain delete -broadcast-domain <broadcast_domain_name> [-ipspace <ipspace_name>]
....

The following command deletes broadcast domain bcast1 in IPspace ipspace1:

....
network port broadcast-domain delete -broadcast-domain <bcast1> -ipspace <ipspace1>
....
