---
sidebar: networking-reference_sidebar
permalink: networking-reference/revert_a_lif_to_its_home_port.html
keywords: revert, home, port, home port, lif, logical, interface, migrate, migration, migrating, reverting, reversion, manual, manually, automatic, automatically, auto-revert
summary: Revert a LIF to its home port after it fails over or is migrated
---

= Revert a LIF to its home port
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-23 12:34:44.790206
//
// restructured: March 2021
//

[.lead]
You can revert a LIF to its home port after it fails over or is migrated to a different port either manually or automatically. If the home port of a particular LIF is unavailable, the LIF remains at its current port and is not reverted.

.About this task

* If you administratively bring the home port of a LIF to the up state before setting the automatic revert option, the LIF is not returned to the home port.
* The node management LIF does not automatically revert unless the value of the "auto-revert" option is set to true.
* You must ensure that the "auto-revert" option is enabled for the cluster LIFs to revert to their home ports.

.Step

Revert a LIF to its home port manually or automatically:

|===
|If you want to revert a LIF to its home port... |Then enter the following command...

|Manually
|network interface revert -vserver vserver_name -lif lif_name
|Automatically
|network interface modify -vserver vserver_name -lif lif_name -auto-revert true
|===
