---
permalink: disks-aggregates/assign-aggregates-svms-task.html
sidebar: sidebar
keywords: assign, aggregate, local tier, svm, storage vm, vserver
summary: "If you assign one or more local tiers (aggregates) to a storage virtual machine (storage VM or SVM, formerly known as Vserver), then you can use only those local tiers to contain volumes for that SVM. A"
---
= Assign local tiers (aggregates) to storage VMs (SVMs)
:icons: font
:imagesdir: ../media/

[.lead]
If you assign one or more local tiers (aggregates) to a storage virtual machine (storage VM or SVM, formerly known as Vserver), then you can use only those local tiers to contain volumes for that storage VM (SVM).

.Before you begin

The storage VM and the local tiers you want to assign to that storage VM must already exist.

.About this task

Assigning local tiers to your storage VMs helps you keep your storage VMs isolated from each other; this is especially important in a multi-tenancy environment.

.Steps

. Check the list of local tiers (aggregates) already assigned to the SVM:
+
`vserver show -fields aggr-list`
+
The aggregates currently assigned to the SVM are displayed. If there are no aggregates assigned, "`-`" is displayed.

. Add or remove assigned aggregates, depending on your requirements:
+

|===

h| If you want to... h| Use this command...

a|
Assign additional aggregates
a|
`vserver add-aggregates`
a|
Unassign aggregates
a|
`vserver remove-aggregates`
|===
The listed aggregates are assigned to or removed from the SVM. If the SVM already has volumes that use an aggregate that is not assigned to the SVM, a warning message is displayed, but the command is completed successfully. Any aggregates that were already assigned to the SVM and that were not named in the command are unaffected.

.Example

In the following example, the aggregates aggr1 and aggr2 are assigned to SVM svm1:

`vserver add-aggregates -vserver svm1 -aggregates aggr1,aggr2`

// BURT 1485072, 08-30-2022
