---
permalink: disks-aggregates/commands-display-space-usage-reference.html
sidebar: sidebar
keywords: commands, display, space usage, information
summary: "You use the storage aggregate and volume commands to see how space is being used in your aggregates and volumes and their Snapshot copies."
---
= Commands for displaying space usage information
:icons: font
:imagesdir: ../media/
:hardbreaks-option:

[.lead]
You use the `storage aggregate` and `volume` commands to see how space is being used in your aggregates and volumes and their Snapshot copies.

|===

h| To display information about... h| Use this command...

a|
Aggregates, including details about used and available space percentages, Snapshot reserve size, and other space usage information
a|
`storage aggregate show`
`storage aggregate show-space -fields snap-size-total,used-including-snapshot-reserve`

a|
How disks and RAID groups are used in an aggregate, and RAID status
a|
`storage aggregate show-status`
a|
The amount of disk space that would be reclaimed if you deleted a specific Snapshot copy
a|
`volume snapshot compute-reclaimable`
a|
The amount of space used by a volume
a|
`volume show -fields size,used,available,percent-used`
`volume show-space`

a|
The amount of space used by a volume in the containing aggregate
a|
`volume show-footprint`
|===

.Related information

* link:http://docs.netapp.com/us-en/ontap-cli[ONTAP 9 Commands^]

// 16 may 2024, ontapdoc-1986