---
permalink: disks-aggregates/commands-manage-ssd-storage-pools-reference.html
sidebar: sidebar
keywords: commands, manage, ssd, storage, pools
summary: "ONTAP provides the storage pool command for managing SSD storage pools."
---
= ONTAP commands for managing SSD storage pools 
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP provides the `storage pool` command for managing SSD storage pools.

|===

h| If you want to... h| Use this command...

a|
Display how much storage a storage pool is providing to which local tier
a|
`storage pool show-aggregate`
a|
Display how much cache would be added to the overall cache capacity for both RAID types (allocation unit data size)
a|
`storage pool show -instance`
a|
Display the disks in a storage pool
a|
`storage pool show-disks`
a|
Display the unallocated allocation units for a storage pool
a|
`storage pool show-available-capacity`
a|
Change the ownership of one or more allocation units of a storage pool from one HA partner to the other
a|
`storage pool reassign`
|===

.Related information
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-reassign.html[storage pool reassign^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-show.html[storage pool show^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-show-aggregate.html[storage pool show-aggregate^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-show-available-capacity.html[storage pool show-available-capacity^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-show-disks.html[storage pool show-disks^]


// 2025 Sep 09, ONTAPDOC-2960
// 2025-Mar-6, ONTAPDOC-2850
// 16 may 2024, ontapdoc-1986