---
permalink: disks-aggregates/commands-manage-aggregates-reference.html
sidebar: sidebar
keywords: commands, manage, aggregates
summary: "You use the storage aggregate command to manage your aggregates."
---
= Commands for managing aggregates
:icons: font
:imagesdir: ../media/

[.lead]
You use the `storage aggregate` command to manage your aggregates.

|===
h| If you want to... h| Use this command...

a|
Display the size of the cache for all Flash Pool aggregates
a|
`storage aggregate show -fields hybrid-cache-size-total -hybrid-cache-size-total >0`
a|
Display disk information and status for an aggregate
a|
`storage aggregate show-status`
a|
Display spare disks by node
a|
`storage aggregate show-spare-disks`
a|
Display the root aggregates in the cluster
a|
`storage aggregate show -has-mroot true`
a|
Display basic information and status for aggregates
a|
`storage aggregate show`
a|
Display the type of storage used in an aggregate
a|
`storage aggregate show -fields storage-type`
a|
Bring an aggregate online
a|
`storage aggregate online`
a|
Delete an aggregate
a|
`storage aggregate delete`
a|
Put an aggregate into the restricted state
a|
`storage aggregate restrict`
a|
Rename an aggregate
a|
`storage aggregate rename`
a|
Take an aggregate offline
a|
`storage aggregate offline`
a|
Change the RAID type for an aggregate
a|
`storage aggregate modify -raidtype`
|===

.Related information

* link:http://docs.netapp.com/us-en/ontap-cli[ONTAP 9 command reference^]

// 16 may 2024, ontapdoc-1986