---
permalink: disks-aggregates/commands-display-storage-shelves-reference.html
sidebar: sidebar
keywords: commands, display, information, storage, shelves
summary: "You use the storage shelf show command to display configuration and error information for your disk shelves."
---

= Commands for displaying information about storage shelves
:icons: font
:imagesdir: ../media/

[.lead]
You use the `storage shelf show` command to display configuration and error information for your disk shelves.

|===
h| If you want to display... h| Use this command...

a|
General information about shelf configuration and hardware status
a|
`storage shelf show`
a|
Detailed information for a specific shelf, including stack ID
a|
`storage shelf show -shelf`
a|
Unresolved, customer actionable, errors by shelf
a|
`storage shelf show -errors`
a|
Bay information
a|
`storage shelf show -bay`
a|
Connectivity information
a|
`storage shelf show -connectivity`
a|
Cooling information, including temperature sensors and cooling fans
a|
`storage shelf show -cooling`
a|
Information about I/O modules
a|
`storage shelf show -module`
a|
Port information
a|
`storage shelf show -port`
a|
Power information, including PSUs (power supply units), current sensors, and voltage sensors
a|
`storage shelf show -power`
|===

.Related information

* link:http://docs.netapp.com/us-en/ontap-cli[ONTAP 9 command reference^]

// 16 may 2024, ontapdoc-1986