---
permalink: disks-aggregates/commands-manage-disks-reference.html
sidebar: sidebar
keywords: commands, manage, disks
summary: "You can use the storage disk and storage aggregate commands to manage your disks."
---
= Commands for managing disks
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `storage disk` and `storage aggregate` commands to manage your disks.

|===

h| If you want to... h| Use this command...

a|
Display a list of spare disks, including partitioned disks, by owner
a|
`storage aggregate show-spare-disks`
a|
Display the disk RAID type, current usage, and RAID group by aggregate
a|
`storage aggregate show-status`
a|
Display the RAID type, current usage, aggregate, and RAID group, including spares, for physical disks
a|
`storage disk show -raid`
a|
Display a list of failed disks
a|
`storage disk show -broken`
a|
Display the pre-cluster (nodescope) drive name for a disk
a|
`storage disk show -primary-paths` (advanced)
a|
Illuminate the LED for a particular disk or shelf
a|
`storage disk set-led`
a|
Display the checksum type for a specific disk
a|
`storage disk show -fields checksum-compatibility`
a|
Display the checksum type for all spare disks
a|
`storage disk show -fields checksum-compatibility -container-type spare`
a|
Display disk connectivity and placement information
a|
`storage disk show -fields disk,primary-port,secondary-name,secondary-port,shelf,bay`
a|
Display the pre-cluster disk names for specific disks
a|
`storage disk show -disk diskname -fields diskpathnames`
a|
Display the list of disks in the maintenance center
a|
`storage disk show -maintenance`
a|
Display SSD wear life
a|
`storage disk show -ssd-wear`
a|
Unpartition a shared disk
a|
`storage disk unpartition` (available at diagnostic level)

a|
Zero all non-zeroed disks
a|
`storage disk zerospares`
a|
Stop an ongoing sanitization process on one or more specified disks
a|
`system node run -node nodename -command disk sanitize`
a|
Display storage encryption disk information
a|
`storage encryption disk show`
a|
Retrieve authentication keys from all linked key management servers
a|
`security key-manager restore`
|===

.Related information

* https://docs.netapp.com/us-en/ontap-cli[ONTAP command reference^]

// 16 may 2024, ontapdoc-1986