---
permalink: disks-aggregates/convert-raid-tec-dp-task.html
sidebar: sidebar
keywords: convert, raid-tec, raid-dp, raid policy
summary: "If you reduce the size of your local tier (aggregate) and no longer need triple parity, you can convert your RAID policy from RAID-TEC to RAID-DP and reduce the number of disks you need for RAID parity."
---
= Convert from RAID-TEC to RAID-DP
:icons: font
:imagesdir: ../media/

[.lead]
If you reduce the size of your local tier (aggregate) and no longer need triple parity, you can convert your RAID policy from RAID-TEC to RAID-DP and reduce the number of disks you need for RAID parity.

.Before you begin

The maximum RAID group size for RAID-TEC is larger than the maximum RAID group size for RAID-DP. If the largest RAID-TEC group size is not within the RAID-DP limits, you cannot convert to RAID-DP.

.About this task

To understand the implications of converting between RAID types, refer to the https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html#parameters[parameters^] for the `storage aggregate modify` command.

.Steps

. Verify that the aggregate is online and has a minimum of six disks:
+
`storage aggregate show-status -aggregate _aggregate_name_`
. Convert the aggregate from RAID-TEC to RAID-DP:
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_dp`
. Verify that the aggregate RAID policy is RAID-DP:
+
`storage aggregate show _aggregate_name_`

// BURT 1485072, 08-30-2022
// ONTAPDOC-2187 July 8, 2024
