---
permalink: disks-aggregates/convert-raid-dp-tec-task.html
sidebar: sidebar
keywords: convert, raid-dp, raid-tec, raid policy
summary: "If you want the added protection of triple-parity, you can convert from RAID-DP to RAID-TEC. RAID-TEC is recommended if the size of the disks used in your aggregate is greater than 4 TiB."
---
= Convert from RAID-DP to RAID-TEC
:icons: font
:imagesdir: ../media/

[.lead]
If you want the added protection of triple-parity, you can convert from RAID-DP to RAID-TEC. RAID-TEC is recommended if the size of the disks used in your local tier (aggregate) is greater than 4 TiB.

.Before you begin

The local tier (aggregate) that is to be converted must have a minimum of seven disks.

.About this task

* Hard disk drive (HDD) local tiers can be converted from RAID-DP to RAID-TEC. This includes HDD tiers in Flash Pool local tiers.
* Learn more about `storage aggregate modify` in the link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html#parameter[ONTAP command reference^]

.Steps

. Verify that the aggregate is online and has a minimum of six disks:
+
`storage aggregate show-status -aggregate _aggregate_name_`
. Convert the aggregate from RAID-DP to RAID-TEC:
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_tec`
. Verify that the aggregate RAID policy is RAID-TEC:
+
`storage aggregate show _aggregate_name_`

// 2024 Dec 19, ONTAPDOC-2569
// 2022, Nov 30, Issue 704
// 2022, Aug 30, BURT 1485072
// ONTAPDOC-2187 July 8, 2024
