---
permalink: disks-aggregates/create-ssd-storage-pool-task.html
sidebar: sidebar
keywords: create, provision, ssd, storage, flash, pool, add, cache, local tier, aggregate
summary: "You can create solid state drive (SSD) storage pools to provide SSD cache for two to four Flash Pool local tiers (aggregates)."
---
= Add cache to a local tier (aggregate) by creating an SSD storage pool
:icons: font
:imagesdir: ../media/

[.lead]
You can provision cache by converting an existing local tier (aggregate) to a Flash Pool local tier (aggregate) by adding solid state drives (SSDs).

You can create solid state drive (SSD) storage pools to provide SSD cache for two to four Flash Pool local tiers (aggregates). Flash Pool aggregates enable you to deploy flash as high performance cache for your working data set while using lower-cost HDDs for less frequently accessed data.

.About this task

* You must supply a disk list when creating or adding disks to a storage pool.
+
Storage pools do not support a `diskcount` parameter.

* The SSDs used in the storage pool should be the same size.

The procedure that you follow depends on the interface that you use--System Manager or the CLI.

[role="tabbed-block"]
====
.System Manager
--
*Use System Manager to add an SSD cache (ONTAP 9.7 only)*

NOTE:  Use the CLI procedure if you are using an ONTAP version other than 9.7

.Steps

.	Click *(Return to classic version)*.

.	Click *Storage > Aggregates & Disks > Aggregates*.

.	Select the local tier (aggregate), and then click *Actions > Add Cache*.

. Select the cache source as "storage pools" or "dedicated SSDs".

.	Click *(Switch to the new experience)*.

.	Click *Storage > Tiers* to verify the size of the new aggregate.

// BURT 1400860, 20 MAY 2021
--

.CLI

--
*Use the CLI to create an SSD storage pool*

.Steps

. Determine the names of the available spare SSDs:
+
`storage aggregate show-spare-disks -disk-type SSD`
+
The SSDs used in a storage pool can be owned by either node of an HA pair.

. Create the storage pool:
+
`storage pool create -storage-pool _sp_name_ -disk-list _disk1_,_disk2_,...`
. *Optional:* Verify the newly created storage pool:
+
`storage pool show -storage-pool _sp_name_`


--
====

.Results

After the SSDs are placed into the storage pool, they no longer appear as spares on the cluster, even though the storage provided by the storage pool has not yet been allocated to any Flash Pool caches. You cannot add SSDs to a RAID group as discrete drives; their storage can be provisioned only by using the allocation units of the storage pool to which they belong.

// BURT 1485072, 08-30-2022
