---
permalink: disks-aggregates/create-aggregates-auto-provision-task.html
sidebar: sidebar
keywords: ontap 9, create, aggregates, auto-provision
summary: "If the auto-provision method is appropriate in your environment, you run the storage aggregate auto-provision to generate aggregate layout recommendations. You can then create aggregates after reviewing and approving ONTAP recommendations."
---
= Create aggregates with auto-provision
:icons: font
:imagesdir: ../media/

[.lead]
If the auto-provision method is appropriate in your environment, you run the `storage aggregate auto-provision` to generate aggregate layout recommendations. You can then create aggregates after reviewing and approving ONTAP recommendations.

.What you'll need

ONTAP 9.2 or later must be running on your cluster.

.About this task

The default summary generated with the `storage aggregate auto-provision` command lists the recommended aggregates to be created, including names and usable size. You can view the list and determine whether you want to create the recommended aggregates when prompted.

You can also display a detailed summary by using the `-verbose` option, which displays the following reports:

* Per node summary of new aggregates to create, discovered spares, and remaining spare disks and partitions after aggregate creation
* New data aggregates to create with counts of disks and partitions to be used
* RAID group layout showing how spare disks and partitions will be used in new data aggregates to be created
* Details about spare disks and partitions remaining after aggregate creation

If you are familiar with the auto-provision method and your environment is correctly prepared, you can use the `-skip-confirmation` option to create the recommended aggregate without display and confirmation. The `storage aggregate auto-provision` command is not affected by the CLI session `-confirmations` setting.

The `storage aggregate auto-provision` man page contains more information about the aggregate layout recommendations.

.Steps

. Run the `storage aggregate auto-provision` command with the desired display options.
 ** no options: Display standard summary
 ** `-verbose` option: Display detailed summary
 ** `-skip-confirmation` option: Create recommended aggregates without display or confirmation
. After reviewing the display of recommended aggregates, respond to the prompt to create the recommended aggregates.
+
----
Do you want to create recommended aggregates? {y|n}:y

Info: Creating node1_SSD_1 ...
      Creating node2_SSD_1 ...
----

*Related information*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands]
