---
permalink: disks-aggregates/determine-space-usage-aggregate-concept.html
sidebar: sidebar
keywords: space, usage, aggregate, local tier, volume
summary: "You can view how much space is used by all volumes in one or more local tiers so that you can take actions to free more space."
---
= Determine space usage in an ONTAP local tier
:icons: font
:imagesdir: ../media/

[.lead]
You can view how much space is used by all volumes in one or more local tiers so that you can take actions to free more space.

include::_include/local-tier-aggregate-note.adoc[]

WAFL reserves a percentage of the total disk space for local tier level metadata and performance.  The space used for maintaining the volumes in the local tier comes out of the WAFL reserve and cannot be changed.  

In local tiers smaller than 30 TB, WAFL reserves 10% of the total disk space for local tier level metadata and performance. 

Beginning with ONTAP 9.12.1, in local tiers that are 30 TB or larger, the amount of reserved disk space for local tier level metadata and performance is reduced, resulting in 5% more usable space in local tiers. The availability of this space savings varies based on your platform and version of ONTAP.

[cols="30,30,40"*,options="header"]
|===
|Disk space reserved by ONTAP in local tiers 30 TB or greater
|Applies to platforms
|In ONTAP versions

|5%
|All AFF and FAS platforms 
|ONTAP 9.14.1 and later

|5%
|AFF platforms and FAS500f platforms
|ONTAP 9.12.1 and later

|10%
|All platforms
|ONTAP 9.11.1 and later

|===

You can view space usage by all volumes in one or more local tiers with the `aggregate show-space` command. This helps you see which volumes are consuming the most space in their containing local tiers so that you can take actions to free more space.

The used space in an local tier is directly affected by the space used in the FlexVol volumes it contains. Measures that you take to increase space in a volume also affect space in the local tier.

[NOTE]
Beginning with ONTAP 9.15.1, two new metadata counters are available. Together with changes to several existing counters, you can get a clearer view of the amount of user data allocated. See link:../volumes/determine-space-usage-volume-aggregate-concept.html[Determine space usage in a volume or local tier] for more information.

The following rows are included in the `aggregate show-space` command output:

* *Volume Footprints*
+
The total of all volume footprints within the local tier. It includes all of the space that is used or reserved by all data and metadata of all volumes in the containing local tier.

* *Aggregate Metadata*
+
The total file system metadata required by the local tier, such as allocation bitmaps and inode files.

* *Snapshot Reserve*
+
The amount of space reserved for local tier snapshots, based on volume size. It is considered used space and is not available to volume or local tier data or metadata.

* *Snapshot Reserve Unusable*
+
The amount of space originally allocated for local tier snapshot reserve that is unavailable for local tier snapshots because it is being used by volumes associated with the local tier. Can occur only for local tiers with a non-zero local tier snapshot reserve.

* *Total Used*
+
The sum of all space used or reserved in the local tier by volumes, metadata, or snapshots.

* *Total Physical Used*
+
The amount of space being used for data now (rather than being reserved for future use). Includes space used by local tier snapshots.

The following example shows the `aggregate show-space` command output for an local tier whose snapshot reserve is 5%. If the snapshot reserve was 0, the row would not be displayed.

....
cluster1::> storage aggregate show-space

						Aggregate : wqa_gx106_aggr1

      Feature                                   Used      Used%
      --------------------------------    ----------     ------
      Volume Footprints                      101.0MB         0%
      Aggregate Metadata                       300KB         0%
      Snapshot Reserve                        5.98GB         5%

      Total Used                              6.07GB         5%
      Total Physical Used                    34.82KB         0%
....

.Related Information

* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage[Knowledge Base article: Space Usage^]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/[Free up 5% of your storage capacity by upgrading to ONTAP 9.12.1^] 

// 2025-Mar-6, ONTAPDOC-2850
// 2024 May 17, ONTAP 9.15.1
// 2023 Nov 02, Jira 1119
// 2023 Feb 07, ONTAPDOC594
// 2022 Aug 30, BURT 1485072
