---
permalink: disks-aggregates/disk-partition-ownership-overview-concept.html
sidebar: sidebar
keywords: disk, partition, ownership, overview
summary: "You can manage the ownership of disks and partitions."
---
= Disk and partition ownership
:icons: font
:imagesdir: ../media/

[.lead]
You can manage the ownership of disks and partitions.

You can perform the following tasks:

* *link:display-partition-ownership-task.html[Display disk and partition ownership]*
+
You can view disk ownership to determine which node controls the storage.  You can also view the partition ownership on systems that use shared disks.

* *link:configure-auto-assignment-disk-ownership-task.html[Change settings for automatic assignment of disk ownership]*
+
You can select a non-default policy for automatically assigning disk ownership or disable automatic assignment of disk ownership.

* *link:manual-assign-disks-ownership-manage-task.html[Manually assign ownership of unpartitioned disks]*
+
If your cluster is not configured to use automatic disk ownership assignment, you must assign ownership manually.

* *link:manual-assign-ownership-partitioned-disks-task.html[Manually assign ownership of partitioned disks]*
+
You can set the ownership of the container disk or the partitions manually or by using auto-assignment--just as you do for unpartitioned disks.

* *link:remove-failed-disk-task.html[Remove a failed disk]*
+
A disk that has failed completely is no longer considered by ONTAP to be a usable disk, and you can immediately disconnect the disk from the shelf.

* *link:remove-ownership-disk-task.html[Remove ownership from a disk]*
+
ONTAP writes disk ownership information to the disk.  Before you remove a spare disk or its shelf from a node, you should remove its ownership information so that it can be properly integrated into another node.

// 2022 Nov 23, BURT 1352610
// 2022 Aug 30, BURT 1485072