---
permalink: disks-aggregates/disk-autoassignment-policy-concept.html
sidebar: sidebar
keywords: disk, autoassignment, policy
summary: "You can typically use the default autoassignment policy, which is equivalent to the stack policy for most systems, and to the bay policy for entry-level systems (AFF A2xx, FAS2xxx). However, for some configurations, you might need to change the autoassignment policy."
---
= Which disk autoassignment policy to use
:icons: font
:imagesdir: ../media/

[.lead]
You can typically use the default autoassignment policy, which is equivalent to the `stack` policy for most systems, and to the `bay` policy for entry-level systems (AFF A2xx, FAS2xxx). However, for some configurations, you might need to change the autoassignment policy.

You must select the appropriate autoassignment based on your configuration:

[cols="2*",options="header"]
|===
| If you are using...| Then use the autoassignment policy value of...

a|
Stand-alone entry-level system
a|
`stack`
a|
Entry-level systems in an HA configuration with a single, shared shelf
a|
`bay`
a|
Entry-level systems in an HA configuration with one stack of two or more shelves
a|
`shelf`
a|
MetroCluster configurations with one stack per node, two or more shelves
a|
`shelf`
a|
All other configurations
a|
`stack`
|===
