---
permalink: disks-aggregates/fast-zeroing-drives-concept.html
sidebar: sidebar
keywords: fast, zero, drives
summary: "Beginning in ONTAP 9.4, you can automatically and quickly zeros drives (both SSDs and HDDs) before provisioning without experiencing long wait times.."
---
= Fast zeroing of drives
:icons: font
:imagesdir: ../media/

[.lead]
Beginning in ONTAP 9.4, you can automatically and quickly zeros drives (both SSDs and HDDs) before provisioning without experiencing long wait times..

For systems that are freshly installed with ONTAP 9.4 or later or systems that are reinitialized with ONTAP 9.4 or later, drive zeroing takes place automatically and is complete in seconds.

If you need to manually zero a drive, you can use one of the following methods:

* Use the `storage disk zerospares` command.
+
Admin privileges are required to use this command.

* From the boot menu select one of the following options:
 ** `(4) Clean configuration and initialize all disks`
 ** `(9a) Unpartition all disks and remove their ownership information`
 ** `(9b) Clean configuration and initialize node with whole disks`

The fast zeroing enhancement does not support systems upgraded from a release earlier than ONTAP 9.4.

If any node on the cluster contains an aggregate with fast-zeroed drives, then you cannot revert the cluster to ONTAP 9.2 or earlier.
