---
permalink: disks-aggregates/fast-zeroing-drives-concept.html
sidebar: sidebar
keywords: fast, zero, drives
summary: "Beginning with ONTAP 9.4, you can automatically and quickly zeros drives (both SSDs and HDDs) before provisioning without experiencing long wait times."
---
= Fast zeroing of drives
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.4, you can automatically and quickly zero drives (both SSDs and HDDs) before provisioning without experiencing long wait times.

For systems that are freshly installed with ONTAP 9.4 or later or systems that are reinitialized with ONTAP 9.4 or later, drive zeroing takes place automatically and is completed in seconds.

If you need to manually zero a drive, you can use one of the following methods:

[role="tabbed-block"]
====
.CLI command
--
*Use a CLI command to fast-zero drives*

.About this task

Admin privileges are required to use this command.

.Steps

. Enter the CLI command:
+
`storage disk zerospares`

--

.Boot menu options

--
*Select options from the boot menu to fast-zero drives*

.About this task

* The fast zeroing enhancement does not support systems upgraded from a release earlier than ONTAP 9.4.

* If any node on the cluster contains a local tier (aggregate) with fast-zeroed drives, then you cannot revert the cluster to ONTAP 9.2 or earlier.


.Steps

. From the boot menu, select one of the following options:
+
* (4) Clean configuration and initialize all disks
* (9a) Unpartition all disks and remove their ownership information
* (9b) Clean configuration and initialize node with whole disks
--

====

// BURT 1485072, 06-17-2022
