---
permalink: disks-aggregates/fast-zeroing-drives-concept.html
sidebar: sidebar
keywords: fast, zero, drives
summary: "On systems freshly installed with ONTAP 9.4 or later and systems reinitialized with ONTAP 9.4 or later, _fast zeroing_ is used to zero drives."
---
= Manually Fast zero drives
:icons: font
:imagesdir: ../media/

[.lead]
On systems freshly installed with ONTAP 9.4 or later and systems reinitialized with ONTAP 9.4 or later, _fast zeroing_ is used to zero drives.  

With _fast zeroing_, drives are zeroed in seconds.  This is done automatically before provisioning and greatly reduces the time it takes to initialize the system, create aggregates, or expand aggregates when spare drives are added.

_Fast zeroing_ is supported on both SSDs and HDDs.  

NOTE: _Fast zeroing_ is not supported on systems upgraded from ONTAP 9.3 or earlier.  ONTAP 9.4 or later must be freshly installed or the system must be reinitialized. In ONTAP 9.3 and earlier, drives are also automatically zeroed by ONTAP; however, the process takes longer.

If you need to manually zero a drive, you can use one of the following methods.  In ONTAP 9.4 and later, manually zeroing a drive also takes only seconds.

[role="tabbed-block"]
====
.CLI command
--
*Use a CLI command to fast-zero drives*

.About this task

Admin privileges are required to use this command.

.Steps

. Enter the CLI command:
+
[source,cli]
----
storage disk zerospares
----

--

.Boot menu options

--
*Select options from the boot menu to fast-zero drives*

.About this task

* The fast zeroing enhancement does not support systems upgraded from a release earlier than ONTAP 9.4.

* If any node on the cluster contains a local tier (aggregate) with fast-zeroed drives, then you cannot revert the cluster to ONTAP 9.2 or earlier.


.Steps

. From the boot menu, select one of the following options:
+
* (4) Clean configuration and initialize all disks
* (9a) Unpartition all disks and remove their ownership information
* (9b) Clean configuration and initialize node with whole disks
--

====

// 2024 Fe 23, GitIssue 1249
// 2022, Dec 12, BURT 1495749
// BURT 1485072, 08-30-2022
