---
permalink: disks-aggregates/flash-pool-aggregate-caching-policies-concept.html
sidebar: sidebar
keywords: cache, flash pool, policy, local tier, aggregate
summary: "Caching policies are applied to volumes that reside in Flash Pool local tiers. You should understand how caching policies work before changing them."
---
= Flash Pool ONTAP local tier caching policies
:icons: font
:imagesdir: ../media/

[.lead]
Caching policies for the volumes in a Flash Pool local tier let you deploy Flash as a high performance cache for your working data set while using lower-cost HDDs for less frequently accessed data. If you are providing cache to two or more Flash Pool local tiers, you should use Flash Pool SSD partitioning to share SSDs across the local tiers in the Flash Pool.

Caching policies are applied to volumes that reside in Flash Pool local tiers. You should understand how caching policies work before changing them.

In most cases, the default caching policy of `auto` is the best caching policy to use. The caching policy should be changed only if a different policy provides better performance for your workload. Configuring the wrong caching policy can severely degrade volume performance; the performance degradation could increase gradually over time.

Caching policies combine a read caching policy and a write caching policy. The policy name concatenates the names of the read caching policy and the write caching policy, separated by a hyphen. If there is no hyphen in the policy name, the write caching policy is `none`, except for the `auto` policy.

Read caching policies optimize for future read performance by placing a copy of the data in the cache in addition to the stored data on HDDs. For read caching policies that insert data into the cache for write operations, the cache operates as a _write-through_ cache.

Data inserted into the cache by using the write caching policy exists only in cache; there is no copy in HDDs. Flash Pool cache is RAID protected. Enabling write caching makes data from write operations available for reads from cache immediately, while deferring writing the data to HDDs until it ages out of the cache.

If you move a volume from a Flash Pool local tier to a single-tier local tier, it loses its caching policy; if you later move it back to a Flash Pool local tier, it is assigned the default caching policy of `auto`. If you move a volume between two Flash Pool local tier, the caching policy is preserved.

== Change a caching policy

You can use the CLI to change the caching policy for a volume that resides on a Flash Pool local tier by using the `-caching-policy` parameter with the `volume create` command.

When you create a volume on a Flash Pool local tier, by default, the `auto` caching policy is assigned to the volume.


// 2025-Mar-6, ONTAPDOC-2850
// BURT 1485072, 08-30-2022
