---
permalink: disks-aggregates/manage-local-tiers-overview-concept.html
sidebar: sidebar
keywords: local tier, aggregate, prepare, add, create, disks, RAID, delete, manage local tier, manage aggregate
summary: "You can add local tiers (aggregates), manage their usage, and add capacity (disks) to them using System Manager or the CLI. "
---
= Manage local tiers (aggregates)
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager or the ONTAP CLI to add local tiers (aggregates), manage their usage, and add capacity (disks) to them.

You can perform the following tasks:

* link:add-local-tier-overview-task.html[Add (create) a local tier (aggregate)]
+
To add a local tier, you follow a specific workflow.  You determine the number of disks or disk partitions that you need for the local tier and decide which method to use to create the local tier.   You can add local tiers automatically by letting ONTAP assign the configuration, or you can manually specify the configuration.

* link:manage-use-local-tiers-overview-task.html[Manage the use of local tiers (aggregates)]
+
For existing local tiers, you can rename them, set their media costs, or determine their drive and RAID group information. You can modify the RAID configuration of a local tier and assign local tiers to storage VMs (SVMs).
You can modify the RAID configuration of a local tier and assign local tiers to storage VMs (SVMs). You can determine which volumes reside on a local tier and how much space they use on a local tier. You can control how much space that volumes can use. You can relocate local tier ownership with an HA pair.  You can also delete a local tier.

* link:add-capacity-local-tier-overview-task.html[Add capacity (disks) to a local tier (aggregate)]
+
Using different methods, you follow a specific workflow to add capacity.
You can add disks to a local tier and add drives to a node or shelf.
If needed, you can correct misaligned spare partitions.

// 2024 Feb 23, Git Issue 1249
// BURT 1485072, 08-30-2022
