---
permalink: disks-aggregates/manual-assign-ownership-root-data-data-task.html
sidebar: sidebar
keywords: manual, assign, disks, root-data-data partitioning
summary: "For root-data-data partitioning there are four owned entities (the container disk and the three partitions) collectively owned by the HA pair."
---
= Manually assign disks with root-data-data partitioning
:icons: font
:imagesdir: ../media/

[.lead]
For root-data-data partitioning there are four owned entities (the container disk and the three partitions) collectively owned by the HA pair.

.About this task

Root-data-data partitioning creates one small partition as the root partition and two larger, equally sized partitions for data.

Parameters must be used in the `disk assign` command to assign the proper partition of a root-data-data partitioned disk. You cannot use these parameters with disks that are part of a storage pool. The default value is false.

* The `[-data1 [true]]` parameter assigns the `_data1_` partition of a root-data1-data2 partitioned disk.
* The `[-data2 [true]]` parameter assigns the `_data2_` partition of a root-data1-data2 partitioned disk.

.Steps

. Display the current ownership for the partitioned disk:
+
`storage disk show -disk _disk_name_ -partition-ownership`
. Set the CLI privilege level to advanced:
+
`set -privilege advanced`
. Enter the appropriate command, depending on which ownership entity you want to assign ownership for:
+

|===

h| If you want to assign ownership for the... h| Use this command...

a|
Container disk
a|
`storage disk assign -disk disk_name -owner owner_name`
a|
Data1 partition
a|
`storage disk assign -disk disk_name -owner owner_name-data1 true`
a|
Data2 partition
a|
`storage disk assign -disk disk_name -owner owner_name-data2 true`
a|
Root partition
a|
`storage disk assign -disk disk_name -owner owner_name -root true`
|===

If any of the ownership entities are already owned, then you must include the `-force` option.
