---
permalink: disks-aggregates/manual-assign-ownership-partitioned-disks-task.html
sidebar: sidebar
keywords: manual, assign, disk, ownership, partition, disks
summary: "You can set the ownership of the container disk or the partitions manually or by using auto-assignment—just as you do for unpartitioned disks."
---
= Manually assign ownership of partitioned disks overview
:icons: font
:imagesdir: ../media/

[.lead]
Using the CLI, you can set the ownership of the container disk or the partitions manually or by using auto-assignment--just as you do for unpartitioned disks.

[NOTE]
====
If a container disk fails in a half-populated shelf and is replaced, ONTAP will not auto-assign ownership. In this case, any assignment of new disks will need to be done manually. To make auto-assign work on half-populated shelves, place disks equally on lower half and 6 on far right bays to begin with. That is, 6 disks from bays 0-5 and 6 disks from bays 18-23. After the container disk is assigned in an ADP-configured system, ONTAP's software will handle any partitioning and partition assignments that are required, without user intervention.
====

You can perform the following tasks in the CLI:



.Manually assign disks with root-data partitioning
[%collapsible]

====
For root-data partitioning, there are three owned entities (the container disk and the two partitions) collectively owned by the HA pair.

The container disk and the two partitions do not all need to be owned by the same node in the HA pair as long as they are all owned by one of the nodes in the HA pair. However, when you use a partition in a local tier (aggregate), it must be owned by the same node that owns the local tier.

.Steps

. Use the CLI to display the current ownership for the partitioned disk:
+
`storage disk show -disk _disk_name_ -partition-ownership`
. Set the CLI privilege level to advanced:
+
`set -privilege advanced`
. Enter the appropriate command, depending on which ownership entity you want to assign ownership for:
+

[cols="25,75"]
|===

h| If you want to assign ownership for the... h| Use this command...

a|
Container disk
a|
`storage disk assign -disk _disk_name_ -owner _owner_name_`
a|
Data partition
a|
`storage disk assign -disk _disk_name_ -owner _owner_name_ -data true`
a|
Root partition
a|
`storage disk assign -disk _disk_name_ -owner _owner_name_ -root true`
|===
+
If any of the ownership entities are already owned, then you must include the "`-force`" option.

====

.Manually assign disks with root-data-data partitioning
[%collapsible]

====
For root-data-data partitioning, there are four owned entities (the container disk and the three partitions) collectively owned by the HA pair.

Root-data-data partitioning creates one small partition as the root partition and two larger, equally sized partitions for data.

.About this task

Parameters must be used with the `disk assign` command to assign the proper partition of a root-data-data partitioned disk. You cannot use these parameters with disks that are part of a storage pool. The default value is "`false`".

* The `-data1 true` parameter assigns the "`data1`" partition of a root-data1-data2 partitioned disk.
* The `-data2 true` parameter assigns the "`data2`" partition of a root-data1-data2 partitioned disk.

.Steps

. Use the CLI to display the current ownership for the partitioned disk:
+
`storage disk show -disk _disk_name_ -partition-ownership`
. Set the CLI privilege level to advanced:
+
`set -privilege advanced`
. Enter the appropriate command, depending on which ownership entity you want to assign ownership for:
+

[cols="25,75"]
|===

h| If you want to assign ownership for the... h| Use this command...

a|
Container disk
a|
`storage disk assign -disk _disk_name_ -owner _owner_name_`
a|
Data1 partition
a|
`storage disk assign -disk _disk_name_ -owner _owner_name_ -data1 true`
a|
Data2 partition
a|
`storage disk assign -disk _disk_name_ -owner _owner_name_ -data2 true`
a|
Root partition
a|
`storage disk assign -disk _disk_name_ -owner _owner_name_ -root true`
|===

If any of the ownership entities are already owned, then you must include the "`-force`" option.
====

// BURT 1485072, 08-30-2022
