---
permalink: disks-aggregates/manual-assign-ownership-root-data-task.html
sidebar: sidebar
keywords: manual, assign, disks, root-data partitioning
summary: "For root-data partitioning, there are three owned entities (the container disk and the two partitions) collectively owned by the HA pair."
---
= Manually assign disks with root-data partitioning
:icons: font
:imagesdir: ../media/

[.lead]
For root-data partitioning, there are three owned entities (the container disk and the two partitions) collectively owned by the HA pair.

The container disk and the two partitions do not all need to be owned by the same node in the HA pair as long as they are all owned by one of the nodes in the HA pair. However, when you use a partition in a local tier (aggregate), it must be owned by the same node that owns the local tier.

The procedure you follow depends on the interface you use--System Manager or the CLI:

[role="tabbed-block"]
====
.System Manager
--
*Use System Manager to manually assign disks with root-data partitioning*

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

NEED to add this procedure

--

.CLI

--
*Use the CLI to manually assign disks with root-data partitioning*

.Steps

. Display the current ownership for the partitioned disk:
+
`storage disk show -disk _disk_name_ -partition-ownership`
. Set the CLI privilege level to advanced:
+
`set -privilege advanced`
. Enter the appropriate command, depending on which ownership entity you want to assign ownership for:
+

[cols="25,75"]
|===

h| If you want to assign ownership for the... h| Use this command...

a|
Container disk
a|
`storage disk assign -disk _disk_name_ -owner _owner_name_`
a|
Data partition
a|
`storage disk assign -disk _disk_name_ -owner _owner_name_ -data true`
a|
Root partition
a|
`storage disk assign -disk _disk_name_ -owner _owner_name_ -root true`
|===
+
If any of the ownership entities are already owned, then you must include the "`-force`" option.

--
====

// IE-539, 25 MAY 2022, restructuring
