---
permalink: disks-aggregates/raid-protection-levels-disks-concept.html
sidebar: sidebar
keywords: raid, protection, level, spare, disk, failure, parity, local tier, aggregate
summary: "ONTAP supports three levels of RAID protection for local tiers (aggregates). The level of RAID protection determines the number of parity disks available for data recovery in the event of disk failures."
---
= RAID protection levels for disks
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP supports three levels of RAID protection for local tiers (aggregates). The level of RAID protection determines the number of parity disks available for data recovery in the event of disk failures.

With RAID protection, if there is a data disk failure in a RAID group, ONTAP can replace the failed disk with a spare disk and use parity data to reconstruct the data of the failed disk.

* *RAID4*
+
With RAID4 protection, ONTAP can use one spare disk to replace and reconstruct the data from one failed disk within the RAID group.

* *RAID-DP*
+
With RAID-DP protection, ONTAP can use up to two spare disks to replace and reconstruct the data from up to two simultaneously failed disks within the RAID group.

* *RAID-TEC*
+
With RAID-TEC protection, ONTAP can use up to three spare disks to replace and reconstruct the data from up to three simultaneously failed disks within the RAID group.


// 2023 Jun 16, Jira 1084
// BURT 1485072, 08-30-2022
