---
permalink: disks-aggregates/sanitization-overview-concept.html
sidebar: sidebar
keywords: disks, disk sanitization, overwriting disks, disk sanitization process, formatting phase, pattern overwrite phase, data recovery
summary: "Disk sanitization is the process of physically obliterating data by overwriting disks or SSDs with specified byte patterns or random data so that recovery of the original data becomes impossible. Using the sanitization process ensures that no one can recover the data on the disks."
---

= Disk sanitization overview

:icons: font
:imagesdir: ../media/

[.lead]
Disk sanitization is the process of physically obliterating data by overwriting disks or SSDs with specified byte patterns or random data so that recovery of the original data becomes impossible. Using the sanitization process ensures that no one can recover the data on the disks.

This functionality is available through the nodeshell in all ONTAP 9 releases, and starting with ONTAP 9.6 in maintenance mode.

The disk sanitization process uses three successive default or user-specified byte overwrite patterns for up to seven cycles per operation. The random overwrite pattern is repeated for each cycle.

Depending on the disk capacity, the patterns, and the number of cycles, the process can take several hours. Sanitization runs in the background. You can start, stop, and display the status of the sanitization process. The sanitization process contains two phases: the "Formatting phase" and the "Pattern overwrite phase".

.Formatting phase

The operation performed for the formatting phase depends on the class of disk being sanitized, as shown in the following table:

|===

h| Disk class h| Formatting phase operation

|Capacity HDDs
|Skipped
|Performance HDDs
|SCSI format operation
|SSDs
|SCSI sanitize operation
|===

.Pattern overwrite phase

The specified overwrite patterns are repeated for the specified number of cycles.

When the sanitization process is complete, the specified disks are in a sanitized state. They are not returned to spare status automatically. You must return the sanitized disks to the spare pool before the newly sanitized disks are available to be added to another local tier.

// 2025-Mar-6, ONTAPDOC-2850
// 2022-01-24, BURT 1425677
