---
permalink: disks-aggregates/sanitization-not-performed-concept.html
sidebar: sidebar
keywords: disks, disk sanitization, unsupported disk sanitization, disk sanitization process
summary: "Disk sanitization is not supported for all disk types. In addition, there are circumstances in which disk sanitization cannot be performed."
---

= When disk sanitization cannot be performed

:icons: font
:imagesdir: ../media/

[.lead]
Disk sanitization is not supported for all disk types. In addition, there are circumstances in which disk sanitization cannot be performed.

* It is not supported on all SSD part numbers.
+
For information about which SSD part numbers support disk sanitization, see the https://hwu.netapp.com/[Hardware Universe^].

* It is not supported in takeover mode for systems in an HA pair.

* It cannot be performed on disks that were failed due to readability or writability problems.

* It does not perform its formatting phase on ATA drives.

* If you are using the random pattern, it cannot be performed on more than 100 disks at one time.

* It is not supported on array LUNs.

* If you sanitize both SES disks in the same ESH shelf at the same time, you see errors on the console about access to that shelf, and shelf warnings are not reported for the duration of the sanitization.
+
However, data access to that shelf is not interrupted.

// 24 JAN 2022, BURT 1425677
