---
permalink: disks-aggregates/set-media-cost-local-tier-task.html
sidebar: sidebar
keywords: media cost, local tier, aggregate, expense
summary: "Beginning with ONTAP 9.11.1, you can use System Manager to set the media cost of a local tier (aggregate)"
---
= Set media cost of a local tier (aggregate)
:icons: font
:imagesdir: ../media/

[.lead]

You can specify the media cost of a local tier (aggregate).

The procedure you follow depends on the interface that you use--System Manager or the CLI:

[role="tabbed-block"]
====
.System Manager

--
*Use System Manager to set the media cost of a local tier*

Beginning with ONTAP 9.11.1, you can use System Manager to set the media cost of a local tier (aggregate).

.Steps

. In System Manager, click *Storage > Tiers*, then click *Set Media Cost* in the desired local tier (aggregate) tiles.

. Select *active and inactive tiers* to enable comparison.

. Enter a currency type and amount.

When you enter or change the media cost, the change is made in all media types.
--

.CLI

--
*Use the CLI to set the media cost of a local tier (aggregate)*

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Need to add this procedure

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

--

====

// BURT 1485072, 06-16-2022
