---
permalink: disks-aggregates/set-cache-data-retention-policy-flash-pool-task.html
sidebar: sidebar
keywords: set, cache-retention policy, flash pool
summary: "You can assign cache-retention policies to volumes in Flash Pool local tiers (aggregates). Data in volumes with a high cache-retention policy remains in cache longer and data in volumes with a low cache-retention policy is removed sooner. This increases performance of your critical workloads by making high priority information accessible at a faster rate for a longer period of time."
---
= Set the cache-retention policy for Flash Pool local tiers (aggregates)
:icons: font
:imagesdir: ../media/

[.lead]
You can assign cache-retention policies to volumes in Flash Pool local tiers (aggregates). Data in volumes with a high cache-retention policy remains in cache longer and data in volumes with a low cache-retention policy is removed sooner. This increases performance of your critical workloads by making high priority information accessible at a faster rate for a longer period of time.

.Before you begin

You should know whether your system has any conditions that might prevent the cache-retention policy from having an impact on how long your data remains in cache.

.Steps

Use the CLI in advanced privilege mode to perform the following steps:

. Change the privilege setting to advanced:
+
`set -privilege advanced`
. Verify the volume's cache-retention policy:
+
By default the cache retention policy is "`normal`".

. Set the cache-retention policy:
+

|===

h| ONTAP Version h| Command

a|
ONTAP 9.0, 9.1
a|
`priority hybrid-cache set volume_name read-cache=read_cache_value write-cache=write_cache_value cache-retention-priority=cache_retention_policy`

Set `cache_retention_policy` to `high` for data that you want to remain in cache longer. Set `cache_retention_policy` to `low` for data that you want to remove from cache sooner.
a|
ONTAP 9.2 or later
a|
`volume modify -volume volume_name -vserver vserver_name -caching-policy policy_name.`
|===

. Verify that the volume's cache-retention policy is changed to the option you selected.
. Return the privilege setting to admin:
+
`set -privilege admin`

// BURT 1485072, 08-30-2022
