---
permalink: disks-aggregates/sizing-raid-groups-concept.html
sidebar: sidebar
keywords: consideration, size, raid groups
summary: "Configuring an optimum RAID group size requires a trade-off of factors. You must decide which factors—speed of RAID rebuild, assurance against risk of data loss due to drive failure, optimizing I/O performance, and maximizing data storage space—are most important for the aggregate that you are configuring."
---
= Considerations for sizing RAID groups
:icons: font
:imagesdir: ../media/

[.lead]
Configuring an optimum RAID group size requires a trade-off of factors. You must decide which factors--speed of RAID rebuild, assurance against risk of data loss due to drive failure, optimizing I/O performance, and maximizing data storage space--are most important for the aggregate that you are configuring.

When you create larger RAID groups, you maximize the space available for data storage for the same amount of storage used for parity (also known as the "`parity tax`"). On the other hand, when a disk fails in a larger RAID group, reconstruction time is increased, impacting performance for a longer period of time. In addition, having more disks in a RAID group increases the probability of a multiple disk failure within the same RAID group.

== HDD or array LUN RAID groups

You should follow these guidelines when sizing your RAID groups composed of HDDs or array LUNs:

* All RAID groups in an aggregate should have the same number of disks.
+
While you can have up to 50% less or more than the number of disks in different raid groups on one aggregate, this might lead to performance bottlenecks in some cases, so is best avoided.

* The recommended range of RAID group disk numbers is between 12 and 20.
+
The reliability of performance disks can support a RAID group size of up to 28, if needed.

* If you can satisfy the first two guidelines with multiple RAID group disk numbers, you should choose the larger number of disks.

== SSD RAID groups in Flash Pool aggregates

The SSD RAID group size can be different from the RAID group size for the HDD RAID groups in a Flash Pool aggregate. Usually, you should ensure that you have only one SSD RAID group for a Flash Pool aggregate, to minimize the number of SSDs required for parity.

== SSD RAID groups in SSD aggregates

You should follow these guidelines when sizing your RAID groups composed of SSDs:

* All RAID groups in an aggregate should have a similar number of drives.
+
The RAID groups do not have to be exactly the same size, but you should avoid having any RAID group that is less than one half the size of other RAID groups in the same aggregate when possible.

* For RAID-DP, the recommended range of RAID group size is between 20 and 28.
