---
permalink: disks-aggregates/update-disk-qualification-package-concept.html
sidebar: sidebar
keywords: update, desk, qualification, package
summary: "The Disk Qualification Package (DQP) adds full support for newly qualified drives. Before you update drive firmware or add new drive types or sizes to a cluster, you must update the DQP. A best practice is to also update the DQP regularly; for example, every quarter or semi-annually."
---
= Learn when to update the ONTAP Disk Qualification Package
:icons: font
:imagesdir: ../media/

[.lead]
The Disk Qualification Package (DQP) adds full support for newly qualified drives. Before you update drive firmware or add new drive types or sizes to a cluster, you must update the DQP. A best practice is to also update the DQP regularly; for example, every quarter or semi-annually.

You need to download and install the DQP in the following situations:

* Whenever you add a new drive type or size to the node
+
For example, if you already have 1-TB drives and add 2-TB drives, you need to check for the latest DQP update.

* Whenever you update the disk firmware
* Whenever newer disk firmware or DQP files are available
* Whenever you upgrade to a new version of ONTAP.
+
The DQP is not updated as part of an ONTAP upgrade.

.Related information

https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip[NetApp Downloads: Disk Qualification Package^]

https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware[NetApp Downloads: Disk Drive Firmware^]

// 31 JAN 2022, issue #352
