---
permalink: flexgroup/aggregate-space-requirements-concept.html
sidebar: sidebar
keywords: guideline, aggregate, space, provision, flexgroup, volume
summary: "You should be aware of the considerations and requirements when selecting the aggregates for provisioning a FlexGroup volume."
---
= Guidelines for aggregate space when provisioning a FlexGroup volume
:icons: font
:imagesdir: ../media/

[.lead]
You should be aware of the considerations and requirements when selecting the aggregates for provisioning a FlexGroup volume.

You must consider the following guidelines when creating a FlexGroup volume for obtaining the best performance results with a FlexGroup volume:

* A FlexGroup volume should span only aggregates that are on identical hardware systems.
+
The use of identical hardware systems helps in providing predictable performance across the FlexGroup volume.

* A FlexGroup volume should span aggregates with the same disk type and RAID group configurations.
+
For consistent performance, you must ensure that all of the aggregates are made of all SSDs, all HDDs, or all hybrid aggregates. Additionally, the aggregates should have the same number of drives and RAID groups across the FlexGroup volume.

* A FlexGroup volume can span parts of a cluster.
+
A FlexGroup volume does not have to be configured to span the entire cluster, but doing so can take greater advantage of the hardware resources that are available.

* When creating a FlexGroup volume, it is best if the aggregates on which the FlexGroup volume is deployed have the following characteristics:
 ** Approximately the same amount of free space should be available across multiple aggregates, especially when using thin provisioning.
 ** Approximately 3 percent of the free space should be reserved for aggregate metadata after creation of the FlexGroup volume.
* For FAS systems, it is best to have two aggregates per node and for AFF systems, you must have one aggregate per node for the FlexGroup volume.
* For each FlexGroup volume, you should create at least eight constituents that are distributed over two or more aggregates on FAS systems, and over one or more aggregates on AFF systems.

.Related information

http://www.netapp.com/us/media/tr-4571.pdf[NetApp Technical Report 4571: NetApp FlexGroup Best Practices and Implementation Guide]
