---
permalink: flexgroup/convert-flexvol-concept.html
sidebar: sidebar
keywords: consider, convert, flexvol, volume, flexgroup, autobalance, give back, giveback, revert, split, space limit, limit
summary: 'You should be aware of the features and operations that are supported before you decide to convert FlexVol volumes to FlexGroup volumes.'
---
= Learn about converting ONTAP FlexVol volumes to FlexGroup volumes
:icons: font
:imagesdir: ../media/

[.lead]
If you want to expand a FlexVol volume beyond its space limit, you can convert the FlexVol volume to a FlexGroup volume. Beginning with ONTAP 9.7, you can convert standalone FlexVol volumes or FlexVol volumes that are in a SnapMirror relationship to FlexGroup volumes.

== Considerations for converting FlexVol volumes to FlexGroup volumes

You should be aware of the link:supported-unsupported-config-concept.html[features and operations that are supported] before you decide to convert FlexVol volumes to FlexGroup volumes.

== Operations not supported during conversion

The following operations are not allowed when volume conversion is in progress:

* Volume move
* Aggregate relocation
* Planned takeover and giveback in a high-availability configuration
* Manual and automatic giveback in an high-availability configuration
* Cluster upgrade and revert
* FlexClone volume split
* Volume rehost
* Volume modify and autosize
* Volume rename
* Attaching an object store to an aggregate
* Negotiated switchover in MetroCluster configuration
* SnapMirror operations
* Restoring from a snapshot
* Quota operations
* Storage efficiency operations

You can perform these operations on the FlexGroup volume after successful conversion.

== Configurations that are not supported with FlexGroup volumes

* Offline or restricted volume
* SVM root volume
* SAN
* SMB 1.0
* NVMe namespaces
* Remote Volume Shadow Copy Service (VSS)

// 2025-Sept-23, CONTAP-546568
// 7-17-25,ontapdoc-3137
// 2-APR-2025 ONTAPDOC-2919
// 2023-Feb-14, Jira ONTAPDOC-882
// 29 OCT 2021, Jira IE-429
// 08 DEC 2021, BURT 1430515
