---
permalink: flexgroup/convert-flexvol-snapmirror-relationship-task.html
sidebar: sidebar
keywords: convert, flexvol, volume, snapmirror, relation, flexgroup
summary: "To convert a FlexVol volume SnapMirror relationship to a FlexGroup volume SnapMirror relationship in ONTAP, you must first convert the destination FlexVol volume followed by the source FlexVol volume."
---
= Convert a FlexVol volume SnapMirror relationship to a FlexGroup volume SnapMirror relationship
:icons: font
:imagesdir: ../media/

[.lead]
To convert a FlexVol volume SnapMirror relationship to a FlexGroup volume SnapMirror relationship in ONTAP, you must first convert the destination FlexVol volume followed by the source FlexVol volume.

.About this task

* FlexGroup conversion is supported only for SnapMirror asynchronous relationships.

* Conversion time depends on several variables. Some of the variables include:

** CPU of the controller
** Utilization of CPU by other applications
** Amount of data in the initial Snapshot copy
** Network bandwidth
** Bandwidth used by other applications

.Before you begin

* The FlexVol volume that is being converted must be online.
* The source FlexVol volume in the SnapMirror relationship must not be the source volume for multiple SnapMirror relationships.
+
Beginning with ONTAP 9.9.1, fanout SnapMirror relationships are supported for FlexGroup volumes. For more information, see link:https://docs.netapp.com/us-en/ontap/flexgroup/create-snapmirror-cascade-fanout-reference.html#considerations-for-creating-cascading-relationships[Considerations for creating SnapMirror cascade and fanout relationships for FlexGroups].

* The operations and configurations on the FlexVol volume must be compatible with the conversion process.
+
An error message is generated if the FlexVol volume has any incompatibility and the volume conversion is aborted. You can take corrective actions and retry the conversion.


.Steps

. Verify that the SnapMirror relationship is healthy: 
+
[source,cli]
----
snapmirror show
----
+
Only XDP type mirror relationships can be converted.
+
Example:
+
----
cluster2::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:src_dpv DP   vs2:dst_dpv  Snapmirrored
                                      Idle           -         true    -
vs0:src_xdp XDP  vs2:dst_xdp  Snapmirrored
                                      Idle           -         true    -
----

. Verify whether the source volume is compatible for conversion:
 .. Log in to the advance privilege mode: 
+
[source,cli]
----
set -privilege advanced
----

 .. Verify the conversion process: 
+
[source,cli]
----
volume conversion start -vserver <src_svm_name> -volume <src_vol> -check-only true
----
+
Example:
+
----
volume conversion start -vserver vs1 -volume src_vol -check-only true
----
+
You must rectify all errors before converting the volume.
. Convert the destination FlexVol volume to FlexGroup volume.
 .. Quiesce the FlexVol SnapMirror relationship: 
+
[source,cli]
----
snapmirror quiesce -destination-path <dest_svm:dest_volume>
----
+
Example:
+
----
cluster2::> snapmirror quiesce -destination-path vs2:dst_xdp
----

 .. Start the conversion: 
+
[source,cli]
----
volume conversion start -vserver <dest_svm> -volume <dest_volume>
----
+
Example:
+
----
cluster-1::> volume conversion start -vserver vs2 -volume dst_xdp

Warning: After the volume is converted to a FlexGroup, it will not be possible
to change it back to a flexible volume.
Do you want to continue? {y|n}: y

[Job 510] Job succeeded: SnapMirror destination volume "dst_xdp" has been successfully converted to a FlexGroup volume.
You must now convert the relationship's source volume, "vs0:src_xdp", to a FlexGroup.
Then, re-establish the SnapMirror relationship using the "snapmirror resync" command.
----
. Convert the source FlexVol volume to FlexGroup volume: ` 
+
[source,cli]
----
volume conversion start -vserver <src_svm_name> -volume <src_vol_name>
----
+
Example:
+
----
cluster-1::> volume conversion start -vserver vs0 -volume src_xdp

Warning: Converting flexible volume "src_xdp" in Vserver "vs0" to a FlexGroup
         will cause the state of all Snapshot copies from the volume to be set
         to "pre-conversion". Pre-conversion Snapshot copies cannot be
         restored.
Do you want to continue? {y|n}: y
[Job 57] Job succeeded: success
----

. Resync the relationship: 
+
[source,cli]
----
snapmirror resync -destination-path dest_svm_name:dest_volume
----
+
Example:
+
----
cluster2::> snapmirror resync -destination-path vs2:dst_xdp
----

.After you finish

You must ensure that when the source FlexGroup volume is expanded to include more constituents, the destination volume is also expanded.

// 2024-Aug-30, ONTAPDOC-2346
// 2024-April-12, GitHub issue# 1319
// 2023-Jan-30, GitHub issue# 789