---
permalink: flexgroup/create-qtrees-task.html
sidebar: sidebar
keywords: create, qtrees, flexgroup, volume, flex group, segment, smb oplock,
summary: "Beginning with ONTAP 9.3, you can create qtrees with FlexGroup volumes. Qtrees enable you to partition your FlexGroup volumes into smaller segments that you can manage individually."
---
= Create qtrees with FlexGroup volumes
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.3, you can create qtrees with FlexGroup volumes. Qtrees enable you to partition your FlexGroup volumes into smaller segments that you can manage individually.

.About this task

* If you want to revert to ONTAP 9.2 or earlier and if you have created one or more qtrees in the FlexGroup volume or modified the attributes (security style and SMB oplocks) of the default qtree, you must delete all of the non-default qtrees and then disable the qtree functionality on each FlexGroup volume before reverting to ONTAP 9.2 or earlier.
+
link:../revert/task_disabling_qtrees_in_flexgroup_volumes_before_reverting.html[Disable qtree functionality in FlexGroup volumes before reverting].

* If the source FlexGroup volume has qtrees in a SnapMirror relationship, the destination cluster must be running ONTAP 9.3 or later (a version of ONTAP software that supports qtrees).
* Beginning with ONTAP 9.5, qtree statistics are supported for FlexGroup volumes.

.Steps

. Create a qtree in the FlexGroup volume: `volume qtree create -vserver vserver_name -volume volume_name -qtree qtree name`
+
You can optionally specify the security style, SMB oplocks, UNIX permissions, and export policy for the qtree.
+
----
cluster1::> volume qtree create -vserver vs0 -volume fg1 -qtree qtree1 -security-style mixed
----

.Related information

link:../volumes/index.html[Logical storage management]

// 08 DEC 2021, BURT 1430515
