---
permalink: flexgroup/enable-storage-efficiency-task.html
sidebar: sidebar
keywords: enable, storage, efficiency, flexgroup, volume
summary: "You can run deduplication and data compression together or independently on a FlexGroup volume to achieve optimal space savings."
---
= Enable storage efficiency on an ONTAP FlexGroup volume
:icons: font
:imagesdir: ../media/

[.lead]
You can run deduplication and data compression together or independently on a FlexGroup volume to achieve optimal space savings.

.Before you begin

The FlexGroup volume must be online.

.Steps

. Enable storage efficiency on the FlexGroup volume: `volume efficiency on -vserver svm_name -volume volume_name`
+
Storage efficiency operations are enabled on all the constituents of the FlexGroup volume.
+
If a FlexGroup volume is expanded after storage efficiency is enabled on the volume, storage efficiency is automatically enabled on the new constituents.

. Enable the required storage efficiency operation on the FlexGroup volume by using the `volume efficiency modify` command.
+
You can enable inline deduplication, postprocess deduplication, inline compression, and postprocess compression on FlexGroup volumes. You can also set the type of compression (secondary or adaptive) and specify a schedule or efficiency policy for the FlexGroup volume.

. If you are not using schedules or efficiency policies for running the storage efficiency operations, start the efficiency operation: `volume efficiency start -vserver svm_name -volume volume_name`
+
If deduplication and data compression are enabled on a volume, data compression is run initially followed by deduplication. This command fails if any efficiency operation is already active on the FlexGroup volume.

. Verify the efficiency operations that are enabled on the FlexGroup volume: `volume efficiency show -vserver svm_name -volume volume_name`
+
----
cluster1::> volume efficiency show -vserver vs1 -volume fg1
             Vserver Name: vs1
              Volume Name: fg1
              Volume Path: /vol/fg1
                    State: Enabled
                   Status: Idle
                 Progress: Idle for 17:07:25
                     Type: Regular
                 Schedule: sun-sat@0

...

             Compression: true
      Inline Compression: true
Incompressible Data Detection: false
      Constituent Volume: false
Compression Quick Check File Size: 524288000
           Inline Dedupe: true
         Data Compaction: false
----


// 2-APR-2025 ONTAPDOC-2919