---
permalink: flexgroup/enable-client-async-dir-delete-task.html
sidebar: sidebar
keywords: perform, directory, enable, delete, files, asynchronous, client, SMB, NFS, share, flexvol, flex vol, flexgroup, flex group
summary: "Beginning with ONTAP 9.11.1, storage administrators can grant rights on a volume to allow NFS and SMB clients to perform asynchronous delete operations. When async delete is enabled, NFS clients can use the `move` command and SMB clients can use the `rename` command to delete a directory on the specified volume and move it to a hidden .ontaptrashbin directory."
---
= Enable client asynchronous directory delete on a volume
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.11.1, storage administrators can grant rights on a volume to allow NFS and SMB clients to perform asynchronous delete operations. When async delete is enabled, NFS clients can use the `move` command and SMB clients can use the `rename` command to delete a directory on the specified volume and move it to a hidden .ontaptrashbin directory.

.Before you begin

You must be at the cluster CLI.

You must be in advanced privilege mode.

.Steps

. From the cluster CLI, enable client asynchronhous delete:
+
`volume file async-delete client enable volume _volname_ vserver _vserverName_ trashbinname _name_`
+
Example:
+
----
cluster-cli::*> volume file async-delete client enable -volume test -trashbin ntaptrash -vserver vs1

Success: Async delete is enabled on volume client successfully
----
. Verify client asynchronous delete is enabled:
+
`volume file async-delete client show`
+
Example:
+
----
cluster-cli::*> volume file async-delete client show

Vserver Volume      async-delete client TrashBinName
------------ ------------ ----------------------- -------------
vs1          vol1         Enabled          .ntaptrash


vs2          vol2         Disabled          -



2 entries were displayed.
----

// 2022-3-22, IE-494
