---
permalink: flexgroup/expand-snapmirror-relationship-task.html
sidebar: sidebar
keywords: expand, flexgroup, volume, snapmirror, relationship, snap mirror, flex group, manual, automatic, automatically, disaster
summary: "Beginning with ONTAP 9.3, you can expand the source FlexGroup volume and destination FlexGroup volume that are in a SnapMirror relationship by adding new constituents to the volumes. You can expand the destination volumes either manually or automatically."
---
= Expand ONTAP FlexGroup volumes in a SnapMirror relationship
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.3, you can expand the source FlexGroup volume and destination FlexGroup volume that are in a SnapMirror relationship by adding new constituents to the volumes. You can expand the destination volumes either manually or automatically.

.About this task

* After expansion, the number of constituents in the source FlexGroup volume and destination FlexGroup volume of a SnapMirror relationship must match.
+
If the number of constituents in the volumes does not match, the SnapMirror transfers fail.

* You should not perform any SnapMirror operation when the expansion process is in progress.
* If a disaster strikes before the expansion process is complete, you must break the SnapMirror relationship and wait until the operation succeeds.
+
[NOTE]
====
You should break the SnapMirror relationship when the expansion process is in progress only in the case of a disaster. In the case of a disaster, the break operation can take some time to complete. You should wait for the break operation to get completed successfully before performing a resync operation. If the break operation fails, you must retry the break operation. If the break operation fails, some of the new constituents might remain in the destination FlexGroup volume after the break operation. It is best to delete these constituents manually before proceeding further.
====

// 2-APR-2025 ONTAPDOC-2919
// 08 DEC 2021, BURT 1430515
