---
permalink: flexgroup/increase-capacity-task.html
sidebar: sidebar
keywords: increase, size, flexgroup, volume, flex group
summary: "You can increase the size of a FlexGroup volume either by adding more capacity to the existing constituents of the FlexGroup volume or by expanding the FlexGroup volume with new member volumes."
---
= Increase the size of a FlexGroup volume
:icons: font
:imagesdir: ../media/

[.lead]
You can increase the size of a FlexGroup volume either by adding more capacity to the existing member volumes (constituents) of the FlexGroup volume or by expanding the FlexGroup volume with new member volumes. A FlexGroup volume cannot have more than 200 member volumes.

.What you'll need

Sufficient space must be available in the aggregates.

.About this task

If you want to add more space, you can increase the collective size of the FlexGroup volume. Increasing the size of a FlexGroup volume resizes the existing member volumes of the FlexGroup volume.

If you want to improve performance, you can expand the FlexGroup volume. You might want to expand a FlexGroup volume and add new member volumes in the following situations:

* New nodes have been added to the cluster.
* New aggregates have been created on the existing nodes.
* The existing member volumes of the FlexGroup volume have reached the maximum FlexVol size for the hardware (100TB or 300TB if link:../volumes/enable-large-vol-file-support-task.html[large volume support] has been enabled), and therefore the FlexGroup volume cannot be resized without adding additional member volumes.

In releases earlier than ONTAP 9.3, you must not expand FlexGroup volumes after a SnapMirror relationship is established. If you expand the source FlexGroup volume after breaking the SnapMirror relationship in releases earlier than ONTAP 9.3, you must perform a baseline transfer to the destination FlexGroup volume once again. Beginning with ONTAP 9.3, you can expand FlexGroup volumes that are in a SnapMirror relationship.

.Step

. Increase the size of the FlexGroup volume by increasing the capacity or performance of the FlexGroup volume, as required:
+

|===

h| If you want to increase the... h| Then do this...

a|
Capacity of the FlexGroup volume
a|
Resize the member volumes of the FlexGroup volume:

`volume modify -vserver vserver_name -volume fg_name -size new_size`
a|
Performance to the FlexGroup volume
a|
Expand the FlexGroup volume by adding new member volumes (constituents):

`+volume expand -vserver vserver_name -volume fg_name -aggr-list aggregate name,... [-aggr-list-multiplier constituents_per_aggr]+`

The default value of the `-aggr-list-multiplier` parameter is 1.

To expand a FlexGroup volume for FabricPool in ONTAP 9.5, any new aggregates used must be FabricPool.
|===

Whenever possible, you should increase the capacity of a FlexGroup volume. If you must expand a FlexGroup volume, you should add member volumes in the same multiples as the member volumes of the existing FlexGroup volume to ensure consistent performance. For example, if the existing FlexGroup volume has 16 member volumes with eight member volumes per node, you can expand the existing FlexGroup volume by 8 or 16 member volumes.

.Examples

*Example of increasing the capacity of the existing member volumes*

The following example shows how to add 20 TB space to a FlexGroup volume volX:

----
cluster1::> volume modify -vserver svm1 -volume volX -size +20TB
----

If the FlexGroup volume has 16 member volumes, the space of each member volumes is increased by 1.25 TB.

*Example of improving performance by adding new member volumes*

The following example shows how to add two more member volumes to the FlexGroup volume volX:

----
cluster1::> volume expand -vserver vs1 -volume volX -aggr-list aggr1,aggr2
----

The size of the new member volumes is the same as that of the existing member volumes.

// 2024 Dec 18, FG max is 60PB with large volumes (ONTAP 9.12.1 P2)
// 08 DEC 2021, BURT 1430515
