---
permalink: flexgroup/index.html
sidebar: sidebar
keywords: decide, scalability, performance, flexgroup, volumes, scalability, performance
summary: "You can set up, manage, and protect FlexGroup volumes for scalability and performance. A FlexGroup volume is a scale-out volume that provides high performance along with automatic load distribution."
---
= FlexGroup volumes management overview with the CLI
:icons: font
:imagesdir: ../media/

[.lead]
You can set up, manage, and protect FlexGroup volumes for scalability and performance. A FlexGroup volume is a scale-out volume that provides high performance along with automatic load distribution.

You can configure FlexGroup volumes if the following are true:

* You are running ONTAP 9.1 or later.
* You want to use NFSv4.x, NFSv3, SMB 2.0, or SMB 2.1.
* You want to use the ONTAP command-line interface (CLI), not System Manager or an automated scripting tool.
+
Details about command syntax are available from the CLI help and the ONTAP man pages.
+
An important subset of FlexGroup functionality is available in System Manager.

* You want to use best practices, not explore every available option.
* You have cluster administrator privileges, not SVM administrator privileges.

NOTE: Beginning with ONTAP 9.5, FlexGroups replace Infinite Volumes, which are not supported in ONTAP 9.5 or later releases.

// The Infinite Volumes Management information has been moved to the documentation archive.

.Related information

Conceptual information about FlexVol volumes is applicable to FlexGroup volumes. Information about FlexVol volumes and ONTAP technology is available in the ONTAP Reference Library and in Technical Reports (TRs).

// 2023 DEC 14, ontap-issues-1184
// BURT 1448684, 10 JAN 2022
