---
permalink: flexgroup/index.html
sidebar: sidebar
keywords: decide, scalability, performance, flexgroup, volumes, scalability, performance
summary: "This content describes how to set up, manage, and protect FlexGroup volumes for scalability and performance. A FlexGroup volume is a scale-out volume that provides high performance along with automatic load distribution."
---
= Scalability and performance using FlexGroup volumes overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to set up, manage, and protect FlexGroup volumes for scalability and performance. A FlexGroup volume is a scale-out volume that provides high performance along with automatic load distribution.

You should use this content if you want to configure FlexGroup volumes in the following way:

* You are running ONTAP 9.1 or later.
* You want to use NFSv4.x, NFSv3, SMB 2.0, or SMB 2.1.
* You want to use the ONTAP command-line interface (CLI), not ONTAP System Manager or an automated scripting tool.
+
An important subset of FlexGroup functionality is available in ONTAP System Manager.

* You want to use best practices, not explore every available option.
+
Details about command syntax are available from the CLI help and the ONTAP man pages.

* You do not want to read a lot of conceptual background.
+
Most of the conceptual information about FlexVol volumes is applicable to FlexGroup volumes. Information about FlexVol volumes and ONTAP technology is available in the ONTAP Reference Library and in Technical Reports (TRs).

* You have cluster administrator privileges, not SVM administrator privileges.

If this content is not suitable for your situation, you should see the following documentation instead:

* http://www.netapp.com/us/media/tr-4571.pdf[NetApp Technical Report 4571: NetApp FlexGroup Best Practices and Implementation]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands]

FlexGroups replace Infinite Volumes, which are not supported in newer versions of ONTAP. The Infinite Volumes Management content has been moved to the documentation archive.
