---
permalink: flexgroup/monitor-volume-usage-file-system-analytics-task.html
sidebar: sidebar
keywords: monitor, volume, ontap, file, system, analytics
summary: "File System Analytics is a framework for collecting and displaying data about the contents of a FlexGroup or FlexVol volume."
---
= Monitor volume usage with ONTAP File System Analytics
:icons: font
:imagesdir: ../media/

[.lead]
File System Analytics is a framework for collecting and displaying data about the contents of a FlexGroup or FlexVol volume. File System Analytics present detailed information at each level of the volume's file system hierarchy, allowing you to:

* assess capacity usage and trends
* monitor file and directory counts
* evaluate file activity and history

When enabled in ONTAP 9.8 and later releases, File System Analytics can be displayed using ONTAP System Manager. You can also use ONTAP REST APIs to access the data programmatically.

Enabling File System Analytics is expected to have a performance impact. You might choose not to enable analytics if maximal performance is required in your environment. You can also disable analytics if your testing shows that the performance impact is unacceptable. When you disable analytics, previously collected data is no longer displayed for that volume.

Beginning with ONTAP 9.9.1, File System Analytics is available for volumes transitioned from 7-mode systems. Nonetheless, because file system analytics can consume storage space, it should not be run on transitioned volumes that are close to maximum capacity. ONTAP 9.9.1 also introduces the ability to set custom inactivity periods for data monitoring.

Beginning with ONTAP 9.10.1, the File System Analytics framework enables you to monitor the highest traffic and throughputs with Activity Tracking. Activity Tracking displays Read IOPs, Write IOPs, Read Throughputs, and Write Throughputs in four areas: files, clients, users, and directories.

File System Analytics is not currently available for the following volume types:

* FlexCache destination volumes
* SnapMirror destination volumes
+
[NOTE]
====
If you have enabled file system analytics on volumes whose containing SVM is in a protection relationship, the analytics data is not replicated to the destination SVM. If the source SVM must be resynchronized in a recovery operation, you must manually reenable analytics on desired volumes after recovery.
====

* SnapLock volumes
* volumes containing LUNs
* volumes used only to hold SMB audit logs (MDV volumes)
* node root volumes (/mroot)

*Feature availability by release*
[%headers, cols="3,1,1,1"]
|===
| | ONTAP 9.8 | ONTAP 9.9.1 | ONTAP 9.10.1
| Visualization in System Manager
| X
| X
| X
| Capacity analytics
| X
| X
| X
| Inactive Data information
| X
| X
| X
| Availability for volumes transitioned from 7-mode systems
| 
| X
| X
| Option to change Inactive period in System Manager
|
| X
| X
| Activity Tracking
|
| 
| X
| Download to CSV (Acitivity Tracking)
| 
| 
| X
|===



//29 October 2021, IE-422