---
permalink: flexgroup/provision-automatically-task.html
sidebar: sidebar
keywords: provision, flexgroup, volume, automatic, create, flex group, aggregate, space
summary: "When you create a FlexGroup volume, you can choose to have ONTAP provision the FlexGroup volume by automatically selecting the aggregates. Aggregates are selected based on the best practices for optimum performance."
---
= Provision a FlexGroup volume automatically
:icons: font
:imagesdir: ../media/

[.lead]
When you create a FlexGroup volume, you can choose to have ONTAP automatically provision the FlexGroup volume by selecting the aggregates. Aggregates are selected based on the best practices for optimum performance and capacity.

.Before you begin

Each node in the cluster must have at least one aggregate.

[NOTE]
====
For creating a FlexGroup volume for FabricPool in ONTAP 9.5, each node must have at least one aggregate that is FabricPool.
====

.About this task

ONTAP selects two aggregates with the largest amount of usable space on each node to create the FlexGroup volume. If two aggregates are not available, ONTAP selects one aggregate per node to create the FlexGroup volume.

Beginning with ONTAP 9.15.1, when you automatically provision a FlexGroup volume, ONTAP uses balanced placement (BP) to choose the aggregates and FlexGroup constituent layout.  One aspect of BP is how it limits over-provisioning aggregates when creating 'none' guaranteed FlexGroup volumes.  The size of the overall FlexGroup volume is limited by the amount of free space on the aggregates, although the limit is higher than it is for 'volume' guaranteed FlexGroup volumes. When you create a FlexGroup volume using REST APIs or `auto-provision-as` with the ONTAP CLI, provisioning might fail because of insufficient space due to this limit. You can avoid this by creating smaller FlexGroup volumes, or by link:create-task.html[creating a FlexGroup volume and selecting the aggregates manually] using the `aggr-list` parameter.

.Steps

. Provision the FlexGroup volume:
+

|===

h| If you are using... h| Use this command...

a|
ONTAP 9.2 or later
a|
`volume create -vserver svm_name -volume fg_vol_name –auto-provision-as flexgroup -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name] [-support-tiering true]`


Beginning with ONTAP 9.5, you can create FlexGroup volumes for FabricPool. To automatically provision a FlexGroup volume on FabricPool, you must set the `-support-tiering` parameter to `true`. The volume guarantee must be always set to `none` for FabricPool. You can also specify the tiering policy and tiering minimum cooling period for the FlexGroup volume.

link:../disks-aggregates/index.html[Disk and aggregate management]

Beginning with ONTAP 9.3, you can specify a throughput ceiling (QoS Max) for FlexGroup volumes, which limits the performance resources that the FlexGroup volume can consume. Beginning with ONTAP 9.4, you can specify throughput floors (QoS Min) and adaptive QoS for FlexGroup volumes.

link:../performance-admin/index.html[Performance management]

Beginning with ONTAP 9.2, you can set the `-encrypt` parameter to `true` if you want to enable encryption on the FlexGroup volume. For creating an encrypted volume, you must have installed the volume encryption license and the key manager.

NOTE: You must enable encryption on FlexGroup volumes at the time of creation. You cannot enable encryption on existing FlexGroup volumes.

link:../encryption-at-rest/index.html[Encryption of data at rest]
a|
ONTAP 9.1
a|
`volume flexgroup deploy -vserver svm_name -size fg_size`

|===
+
The `size` parameter specifies the size of the FlexGroup volume in KB, MB, GB, TB, or PB.
+
The following example shows how to provision a FlexGroup volume of size 400 TB in ONTAP 9.2:
+
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
The following example shows how to create a QoS policy group for throughput ceiling and how to apply it to a FlexGroup volume:
+
----
cluster1::> qos policy-group create -policy group pg-vs1 -vserver vs1 -max-throughput 5000iops
----
+
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -qos-policy-group pg-vs1
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
The following example shows how to provision a FlexGroup volume of size 400 TB on aggregates in FabricPool in ONTAP 9.5:
+
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -support-tiering true -tiering-policy auto
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
The FlexGroup volume is created with eight constituents on each node in the cluster. The constituents are distributed equally between the two largest aggregates on each node.
+
By default, the FlexGroup volume is created with the `volume` space guarantee setting except on AFF systems. For AFF systems, by default the FlexGroup volume is created with the `none` space guarantee.

. Mount the FlexGroup volume with a junction path: `volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`
+
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg2
----

.After you finish

You should mount the FlexGroup volume from the client.

If you are running ONTAP 9.6 or earlier and if the storage virtual machine (SVM) has both NFSv3 and NFSv4 configured, mounting the FlexGroup volume from the client might fail. In such cases, you must explicitly specify the NFS version when mounting the FlexGroup volume from the client.

----
# mount -t nfs -o vers=3 192.53.19.64:/fg2 /mnt/fg2
# ls /mnt/fg2
file1  file2
----

// 2024-June-21, CONTAP-248246
// 2022-7-19, issue #582
// 08 DEC 2021,BURT 1430515
