---
permalink: flexgroup/restore-snapvault-backup-task.html
sidebar: sidebar
keywords: restore, flexgroup, volume, snapvault, backup
summary: "You can perform a full-volume restore operation of FlexGroup volumes from a snapshot in the SnapVault secondary volume. You can restore the FlexGroup volume either to the original source volume or to a new FlexGroup volume."
---
= Restore a FlexGroup volume from a SnapVault backup
:icons: font
:imagesdir: ../media/
:hardbreaks-option:

[.lead]
You can perform a full-volume restore operation of FlexGroup volumes from a snapshot in the SnapVault secondary volume. You can restore the FlexGroup volume either to the original source volume or to a new FlexGroup volume.

.Before you begin

You must be aware of certain considerations when you restore from SnapVault backups for FlexGroup volumes.

* Only baseline restore is supported with partial snapshots from a SnapVault backup.
The number of constituents in the destination volume must match the number of constituents in the source volume when the snapshot was taken.

* If a restore operation fails, no other operations are allowed until the restore operation is complete.
You can either retry the restore operation or run the restore operation with the `cleanup` parameter.

* A FlexGroup volume can be the source volume of only one backup relationship or restore relationship.
A FlexGroup volume cannot be the source of two SnapVault relationships, two restore relationships, or a SnapVault relationship and a restore relationship.

* SnapVault backup and restore operations cannot run in parallel.
When either a baseline restore operation or an incremental restore operation is in progress, you should quiesce the backup operations.

* You must abort a restore operation of a partial snapshot from the destination FlexGroup volume.
You cannot abort the restore operation of a partial snapshot from the source volume.

* If you abort a restore operation, you must restart the restore operation with the same snapshot that was used for the previous restore operation.

.About this task

Any active quota rules on the destination FlexGroup volume are deactivated before the restore is performed.

You can use the `volume quota modify` command to reactivate quota rules after the restore operation is complete.

.Steps

. Restore the FlexGroup volume: `snapmirror restore -source-path _src_svm:src_flexgroup_ -destination-path _dest_svm:dest_flexgroup_ -snapshot _snapshot_name_`
`snapshot_name` is the snapshot that is to be restored from the source volume to the destination volume. If the snapshot is not specified, the destination volume is restored from the latest snapshot.
+
----
vserverA::> snapmirror restore -source-path vserverB:dstFG -destination-path vserverA:newFG -snapshot daily.2016-07-15_0010
Warning: This is a disruptive operation and the volume vserverA:newFG will be read-only until the operation completes
Do you want to continue? {y|n}: y
----
