---
permalink: flexgroup/supported-unsupported-config-concept.html
sidebar: sidebar
keywords: support, unsupported, configuration, flexgroup, volumes
summary: "You should be aware of the ONTAP features that are supported and not supported with FlexGroup volumes in ONTAP 9."
---
= Supported and unsupported configurations for FlexGroup volumes
:icons: font
:imagesdir: ../media/

[.lead]
You should be aware of the ONTAP features that are supported and not supported with FlexGroup volumes in ONTAP 9.

== Features supported beginning with ONTAP 9.13.1

* Autonomous Ransomware protection (ARP) for FlexGroup volumes, including the following supported functionality:
** FlexGroup expand operations: A new constituent inherits Autonomous Ransomware Protection attributes.
** FlexVol to FlexGroup conversions: Conversions of FlexVols with active Autonomous Ransomware Protection is possible.
** FlexGroup rebalancing: Autonomous Ransomware Protection is copied between inodes during disruptive and non-disruptive rebalancing operations.
* Schedule a single FlexGroup rebalancing operation.
* SnapMirror fanout relationships with SVM DR on FlexGroup volumes. Supports fanout to eight sites.

== Features supported beginning with ONTAP 9.12.1

* FlexGroup rebalancing
* SnapLock for SnapVault
* SVM migrate 
* FabricPool, FlexGroup, and SVM DR working in conjunction. (In releases earlier than ONTAP 9.12.1, any two of these features worked together, but not all three in conjunction.)
* FlexGroup volume constituent size up to a maximum of 300 TB on AFF and FAS platforms when using ONTAP 9.12.1 P2 and later.

== Features supported beginning with ONTAP 9.11.1

* SnapLock volumes
+
SnapLock does not support the following features with FlexGroup volumes:

** Legal-hold
** Event-based retention
** SnapLock for SnapVault

You configure SnapLock at the FlexGroup level. You cannot configure SnapLock at the constituent level.

xref:../snaplock/snaplock-concept.adoc[What SnapLock is]

* Client asynchronous directory delete
+
xref:manage-client-async-dir-delete-task.adoc[Manage client rights to delete directories rapidly]

== Features supported beginning with ONTAP 9.10.1

* Convert FlexVol volumes to FlexGroup volumes in an SVM-DR source
+
xref:convert-flexvol-svm-dr-relationship-task.adoc[Convert a FlexVol volume to a FlexGroup volume within an SVM-DR relationship]

* SVM DR FlexClone support for FlexGroup volumes
+
xref:../volumes/create-flexclone-task.adoc[Learn more about creating FlexClone volumes.]

== Features supported beginning with ONTAP 9.9.1

* SVM disaster recovery
+
Cloning a FlexGroup volume that is part of an SVM-DR relationship is not supported.

* SnapMirror fanout relationships of 2 or more (A to B, A to C), with a maximum of 8 fanout legs.
+
xref:create-snapmirror-cascade-fanout-reference.adoc[Considerations for creating SnapMirror cascade and fanout relationships for FlexGroups]

* SnapMirror cascading relationships up to two levels (A to B to C)
+
xref:create-snapmirror-cascade-fanout-reference.adoc[Considerations for creating SnapMirror cascade and fanout relationships for FlexGroups]

== Features supported beginning with ONTAP 9.8

* Restoring a single file from a FlexGroup SnapMirror vault or from a UDP destination
 ** Restore can be from a FlexGroup volume of any geometry to FlexGroup volume of any geometry
 ** Only one file per restore operation is supported
* Converting volumes transitioned from 7-mode systems to FlexGroup volumes
+
For more information, see Knowledge Base article link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_To_Convert_a_Transitioned_FlexVol_to_FlexGroup[How To Convert a Transitioned FlexVol to FlexGroup].

* NFSv4.2
* Asynchronous delete of files and directories
* Files System Analytics (FSA)
* FlexGroup as a VMware vSphere datastore
* Additional support for tape backup and restore using NDMP, including the following features:
 ** NDMP restartable backup extension (RBE) and Snapshot Management Extension (SSME)
 ** Environment variables EXCLUDE and MULTI_SUBTREE_NAMES support FlexGroup backups
 ** Introduction of IGNORE_CTIME_MTIME environment variable for FlexGroup backups
 ** Individual file recovery in a FlexGroup using the NDMP_SNAP_RECOVER message, which is part of extension 0x2050
Dump and restore sessions are aborted during an upgrade or revert.

== Features supported beginning with ONTAP 9.7

* FlexClone volume
* NFSv4 and NFSv4.1
* pNFS
* Tape backup and restore by using NDMP
+
You must be aware of the following points for NDMP support on FlexGroup volumes:

 ** The NDMP_SNAP_RECOVER message in the extension class 0x2050 can be used only for recovering an entire FlexGroup volume.
+
Individual files in a FlexGroup volume cannot be recovered.

 ** NDMP restartable backup extension (RBE) is not supported for FlexGroup volumes.
 ** Environment variables EXCLUDE and MULTI_SUBTREE_NAMES are not supported for FlexGroup volumes.
 ** The `ndmpcopy` command is supported for data transfer between FlexVol and FlexGroup volumes.
+
If you revert from Data ONTAP 9.7 to an earlier version, the incremental transfer information of the previous transfers is not retained and therefore, you must perform a baseline copy after reverting.

* VMware vStorage APIs for Array Integration (VAAI)
* Conversion of a FlexVol volume to a FlexGroup volume
* FlexGroup volumes as FlexCache origin volumes

== Features supported beginning with ONTAP 9.6

* Continuously available SMB shares
* MetroCluster configurations
* Renaming a FlexGroup volume (`volume rename` command)
* Shrinking or reducing the size of a FlexGroup volume (`volume size` command)
* Elastic sizing
* NetApp aggregate encryption (NAE)
* Cloud Volumes ONTAP

== Features supported beginning with ONTAP 9.5

* ODX copy offload
* Storage-Level Access Guard
* Enhancements to change notifications for SMB shares
+
Change notifications are sent for changes to the parent directory on which the `changenotify` property is set and for changes to all of the subdirectories in that parent directory.

* FabricPool
* Quota enforcement
* Qtree statistics
* Adaptive QoS for files in FlexGroup volumes
* FlexCache (cache only; FlexGroup as origin supported in ONTAP 9.7)

== Features supported beginning with ONTAP 9.4

* FPolicy
* File auditing
* Throughput floor (QoS Min) and adaptive QoS for FlexGroup volumes
* Throughput ceiling (QoS Max) and throughput floor (QoS Min) for files in FlexGroup volumes
+
You use the `volume file modify` command to manage the QoS policy group that is associated with a file.

* Relaxed SnapMirror limits
* SMB 3.x multichannel

== Features supported beginning with ONTAP 9.3

* Antivirus configuration
* Change notifications for SMB shares
+
Notifications are sent only for changes to the parent directory on which the `changenotify` property is set. Change notifications are not sent for changes to subdirectories in the parent directory.

* Qtrees
* Throughput ceiling (QoS Max)
* Expand the source FlexGroup volume and destination FlexGroup volume in a SnapMirror relationship
* SnapVault backup and restore
* Unified data protection relationships
* Autogrow option and autoshrink option
* Inode count factored to ingest

== Feature supported beginning with ONTAP 9.2

* Volume encryption
* Aggregate inline deduplication (cross-volume deduplication)
* NetApp volume encryption (NVE)

== Features supported beginning with ONTAP 9.1

FlexGroup volumes were introduced in ONTAP 9.1, with support for several ONTAP features.

* SnapMirror technology
* Snapshot copies
* Active IQ
* Inline adaptive compression
* Inline deduplication
* Inline data compaction
* AFF
* Quota reporting
* NetApp Snapshot technology
* SnapRestore software (FlexGroup level)
* Hybrid aggregates
* Constituent or member volume move
* Postprocess deduplication
* NetApp RAID-TEC technology
* Per-aggregate consistency point
* Sharing FlexGroup with FlexVol volume in the same SVM

== Unsupported configurations in ONTAP 9


|===

h| Unsupported protocols h| Unsupported data protection features h| Other unsupported ONTAP features

a|
* pNFS (ONTAP 9.0 to 9.6)
* SMB 1.0
* SMB transparent failover (ONTAP 9.0 to 9.5)
* SAN

a|
* SnapLock volumes (ONTAP 9.10.1 and earlier)
* SMTape
* Synchronous SnapMirror 
* SVM DR with FlexGroup volumes containing FabricPools

a|
Remote Volume Shadow Copy Service (VSS)
|===

.Related information

https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center]


// 2023-Apr-20, IDR-212
// 2023-Apr-6, ONTAPDOC-873 and ONTAPDOC-901
// 2023-Feb-2, issue# 794
// 2023-Jan-30, issue# 786
// 2023-Jan-9, Jira ONTAPDOC-786
// 2022-Oct-7, IE-532, ONTAPDOC-662
// 2021-10-29, Jira IE-429
// 2021-11-9, BURT 1431501
// 2021-11-11, NetApp doc issue #239
// 2022-3-22, fix issue #422
// 2022-3-24, Jira IE-521, IE-494
// 2022-5-9, issue 490
// 2022-6-16, KDA-1534
