---
permalink: flexcache-writeback/faq-flexcache-write-back.html
sidebar: sidebar
keywords: tr-4743, flexcache writeback, flexcache write-back, flexcache, write-back, write back, faq
summary: "Frequently asked questions about FlexCache write-back"
---

= Frequently asked questions about FlexCache write-back

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
    
[.lead]
This FAQ can help if you are looking for a quick answer to a question

.I want to use write-back. What version of ONTAP do I need to run?
Both the cache and the origin must be running ONTAP 9.15.1 or later. It is *_strongly_* recommended that you run the latest P release. Engineering is constantly improving the performance and functionality of write-back-enabled caches.

.Can clients accessing the origin have an effect on clients accessing the write-back-enabled cache?
Yes. The origin has equal right to the data as any of the caches. If an operation is executed on a file the requires the file to be evicted from the cache, or a lock/data delegation to be revoked, the client at the cache may see a delay accessing the file.

.Can I apply QoS to write-back-enabled FlexCaches?
Yes. Every cache and the origin can have independent QoS policies applied. This will no have a direct effect on any write-back initiated intercluster traffic. Indirectly, you can slow down intercluster write-back traffic by QoS limiting the front-end traffic at the write-back-enabled cache.

.Is multi-protocol NAS supported at write-back-enabled FlexCaches?
Yes. Multi-protocol is fully supported at write-back-enabled FlexCaches. Currently, NFSv4.2 and S3 are not supported by FlexCache operating in write-around or write-back mode.

.Are SMB alternate data streams supported at write-back-enabled FlexCaches?
SMB alternate data streams (ADS) are supported, but not accelerated by write-back. The write to the ADS will be forwarded to the origin, incurring the penalty of the WAN latency. The write will also evict the main file the ADS is apart of from the cache.

.Can I switch a cache between write-around and write-back mode after it is created?
Yes. All you have to do is toggle the `is-writeback-enabled` flag in the link:../flexcache-writeback/flexcache-writeback-enable-task.adoc[`flexcache modify` command].
