---
permalink: flexcache-writeback/flexcache-write-back-prerequisites.html
sidebar: sidebar
keywords: tr-4743, flexcache writeback, flexcache write-back, prerequisites, technical report, netapp tr, ontap tr
summary: "Before you deploy FlexCache in write-back mode, ensure you have met these software, licensing and system configuration requirements."
---
= FlexCache write-back prerequisites

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
    
[.lead]
Before you deploy FlexCache in write-back mode, ensure you have met these software, licensing, and system configuration requirements.

== ONTAP version

* The origin *_must_* be running ONTAP 9.15.1 or later.
* Any caching cluster that needs to operate in write-back mode *_must_* be running ONTAP 9.15.1 or later.
* Any caching cluster that does not need to operate in write-back mode can run any supported ONTAP version.
//what is a supported ontap version?

== Licensing

FlexCache, including the write-back mode of operation, is included with your ONTAP purchase. No extra license is required.

== Peering

* The origin and cache clusters must be link:../flexcache-writeback/flexcache-writeback-enable-task.html[cluster peered]
* The server virtual machines (SVMs) on the origin and cache cluster must be link:../flexcache-writeback/flexcache-writeback-enable-task.html[vserver peered] with the FlexCache option. 

NOTE: You do not need to peer a cache cluster to another cache cluster. There is also no need to peer a cache SVM to another cache SVM.

// 2024-Aug-6, ONTAPDOC-2272