---
permalink: flexcache-writeback/flexcache-write-back-prerequisites.html
sidebar: sidebar
keywords: tr-4743, flexcache writeback, flexcache write-back, prerequisites, technical report, netapp tr, ontap tr
summary: "Before you deploy FlexCache in write-back mode, ensure you have met these software, licensing and system configuration requirements."
---
= ONTAP FlexCache write-back prerequisites

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
    
[.lead]
Before you deploy FlexCache in write-back mode, ensure you have met these performance, software, licensing, and system configuration requirements.

== CPU and Memory

It is __**strongly recommended**__ that each origin cluster node have at least 128GB of RAM and 20 CPUs to absorb the write-back messages initiated by write-back enabled caches. This is the equivalent of an A400 or greater. If the origin cluster serves as the origin to multiple write-back enabled FlexCaches, it will require more CPU and RAM.

CAUTION: Using an undersized origin for your workload can have profound impacts on performance at the write-back-enabled cache or the origin.

== ONTAP version

* The origin *_must_* be running ONTAP 9.15.1 or later; however, ONTAP 9.15.1 does not have all the necessary fixes and improvements for FlexCache write-back, and is not recommended for production workloads. Significant enhancements for FlexCache write-back were introduced in ONTAP 9.17.1P1. It is *_strongly_* advised you run the current recommended release after 9.17.1P1 at both the origin and cache clusters. If you are unable to run ONTAP 9.17.1, the latest P release of 9.16.1 is the next suggested release. 
[NOTE]
It is *_strongly_* recommended that you review the link:flexcache-write-back-guidelines.html[FlexCache write-back guidelines] before implementing FlexCache write-back in your environment.
* Any caching cluster that needs to operate in write-back mode *_must_* be running ONTAP 9.15.1 or later.
* Any caching cluster that does not need to operate in write-back mode can run any generally ONTAP version that supports FlexCache volumes.
//what is a supported ontap version?

== Licensing

FlexCache, including the write-back mode of operation, is included with your ONTAP purchase. No extra license is required.

== Peering

* The origin and cache clusters must be link:../flexcache-writeback/flexcache-writeback-enable-task.html[cluster peered]
* The server virtual machines (SVMs) on the origin and cache cluster must be link:../flexcache-writeback/flexcache-writeback-enable-task.html[vserver peered] with the FlexCache option. 

NOTE: You do not need to peer a cache cluster to another cache cluster. There is also no need to peer a cache SVM to another cache SVM.

// 2026-Sept-14, ONTAPDOC-4318
// 2024-12-20,PR-2195
// 2024-Aug-6, ONTAPDOC-2272