---
permalink: flexcache-writeback/flexcache-write-back-interoperability.html
sidebar: sidebar
keywords: tr-4743, flexcache writeback, flexcache write-back, interoperability, client, technical report, netapp tr, ontap tr
summary: "Understand these interoperability considerations when deploying FlexCache in write-back mode"
---
= FlexCache Writeback interoperability

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
    
[.lead]
Understand these interoperability considerations when deploying FlexCache in write-back mode.

== ONTAP version

To use the write-back mode of operation, both the cache and origin *must* be running ONTAP 9.15.1 or later. 

NOTE: Clusters where a write-back-enabled cache is unnecessary can run earlier versions of ONTAP, but that cluster can only operate in write-around mode.

You can have a mix of ONTAP versions in your environment. 

[[example1-table]]
.Mixed cluster versions example 1
[%header,cols="1*,1*,1*",options="header"]
|===
| Cluster    | ONTAP version | Write-back supported?
|*Origin*    | ONTAP 9.15.1 | N/A
|*Cluster 1* | ONTAP 9.15.1 | Yes
|*Cluster 2* | ONTAP 9.14.1 | No
|===

[[example2-table]]
.Mixed cluster versions example 2
[%header,cols="1*,1*,1*",options="header"]
|===
| Cluster    | ONTAP version | Write-back supported?
|*Origin*    | ONTAP 9.14.1 | N/A
|*Cluster 1* | ONTAP 9.15.1 | No
|*Cluster 2* | ONTAP 9.15.1 | No
|===

NOTE: In <<example2-table>>, neither cluster can enable write-back mode because the origin is not running ONTAP 9.15.1 or later, which is a strict requirement.

== Client interoperability

Any client generally supported by ONTAP can access a FlexCache volume regardless of whether it is operating in write-around or write-back mode. For an up-to-date list of supported clients, refer to NetApp's https://imt.netapp.com/matrix/#welcome[interoperability matrix^].

Although the client version doesn't matter specifically, the client must be new enough to support NFSv3, NFSv4.0, NFSv4.1, SMB2.x, or SMB3.x. SMB1 and NFSv2 are deprecated protocols and are not supported. 

== Write-back and write-around

As seen in <<example1-table>>, FlexCache operating in write-back mode can co-exist with caches operating in write-around mode. It is advised to compare write-around against write-back with your specific workload.

TIP: If the performance for a workload is the same between write-back and write-around, use write-around.

== ONTAP feature interoperability

For the most up-to-date list of FlexCache feature interoperability, refer to link:../flexcache/supported-unsupported-features-concept.html[the supported and unsupported features for FlexCache volumes].

// 2024-Aug-6, ONTAPDOC-2272