---
sidebar: sidebar
permalink: smbc/considerations-limits.html
keywords: SM-BC, SMBC, restrictions, consistency group, endpoint limits, solaris, aix, hp-ux, fanout, snampmirror active sync
summary: There are several additional restrictions and limitations when using the SnapMirror Business Continuity solution.
---
= Object limits for SnapMirror Business Continuity
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
When preparing to use and managing SnapMirror Business Continuity, be aware of the following limitations. 

== Consistency groups in a cluster

Consistency group limits for a cluster with SM-BC are calculated based on relationships and depend on the version of ONTAP used. Limits are platform-independent. 

[options="header"]
|===
| ONTAP version | Maximum number of relationships
| ONTAP 9.8-9.9.1 | 5
| ONTAP 9.10.1 | 20
| ONTAP 9.11.1 and later | 50
|===

== Volumes per consistency group

The maximum number of volumes per consistency group with SM-BC is platform independent. 

[options="header"]
|===
| ONTAP version | Maximum number of volumes supported in a consistency group relationship
| ONTAP 9.8-9.9.1 | 12 
| ONTAP 9.10.1 and later | 16 
|===

== Volumes

Volume limits in SM-BC are calculated based on the number of endpoints, not the number of relationships. A consistency group with 12 volumes contributes 12 endpoints on both the primary and secondary cluster. Both SM-BC and SnapMirror Synchronous relationships contribute to the total number of endpoints.

The maximum endpoints per platform are included in the following table.

[options="header"]
|===
| S. No |Platform 3+| Endpoints per HA for SM-BC 3+| Overall sync and SM-BC endpoints per HA
|
|
|ONTAP 9.8-9.9.1 |ONTAP 9.10.1 |ONTAP 9.11.1 and later |ONTAP 9.8-9.9.1 |ONTAP 9.10.1 |ONTAP 9.11.1 and later
|1
|AFF
|60
|200
|400
|80
|200
|400
|2
|ASA
|60
|200
|400
|80
|200
|400
|===

== SAN object limits

SAN object limits are included in the following table. The limits apply regardless of the platform.

|===
|Object in an SM-BC relationship |Count

|LUNs per volume
|256
|LUN maps per node
|4096
|LUN maps per cluster
|8192
|LIFs per SVM (with at least one volume in an SM-BC relationship)
|256
|Inter-cluster LIFs per node
|4
|Inter-cluster LIFs per cluster
|8
|===

.Related information 
* link:https://hwu.netapp.com/[Hardware Universe^]
* link:../consistency-groups/limits.html[Consistency group limits^]

// 2023 Nov 22, Git Issue 1173
// ontapdoc-915, 16 april 2023
// ontapdoc-804, 1 april 2023
// BURT 1451494, 2022-02-11
// BURT 1387138
// BURT 1431859, 1 dec 2021
// issue #326, 19 dec 2022
// BURT 1449057, 27 JAN 2022
// BURT 1459617 and 1451134, 10 March 2022
// ontap-issues-#604, 31 august 2022
// ONTAPDOC-883, 6 march 2023