---
permalink: smbc/resume-protection-fan-out-configuration.html
sidebar: sidebar
keywords: fan out, asynchronous, restore, third site, MirrorAllSnapshots, MirrorAndVault
summary: "SM-BC supports fan-out configurations. Following a failover on the SM-BC endpoint, you must resume connection with the asynchronous fan-out endpoint."
---
= Resume protection in a fan-out configuration with SM-BC
:icons: font
:imagesdir: ../media/
:hardbreaks-option:

[.lead]
SM-BC supports xref:../data-protection/supported-deployment-config-concept.html[fan-out configurations]. Your source volume can be mirrored to an SM-BC destination endpoint and to one or more asynchronous SnapMirror relationships.

Fan-out configurations are supported with the `MirrorAllSnapshots` policy, and, beginning with ONTAP 9.11.1, the `MirrorAndVault` policy. Beginning in ONTAP 9.11.1, fan-out configurations in SM-BC are not supported with the `XDPDefault` policy.

If you experience a failover on the SM-BC destination, the asynchronous SnapMirror destination will become unhealthy, and you must manually restore protection by deleting and recreating the relationship with the asynchronous SnapMirror endpoint.  

.Resume protection in a fan-out configuration after failover
. Verify the failover has completed successfully:
`snapmirror failover show`
. On the asynchronous Snapmirror endpoint, delete the fan-out endpoint: 
`snapmirror delete -destination-path _destination_path_`
. On the third site, create an asynchronous SnapMirror relationships between the new SM-BC primary volume and the async fan-out destination volume: 
`snapmirror create -source-path _source_path_ -destination-path _destination_path_ -policy MirrorAllSnapshots -schedule _schedule_`
. Resynchronize the relationship: 
`snapmirror resync -destination-path _destination_path_`
. Verify the relationship status and heath: 
`snapmirror show`

// BURT 1459339, 22 feb 2022
// BURT 1459617, 10 march 2022
// BURT 1451134, 7 april 2022