---
sidebar: sidebar
permalink: smbc/smbc_plan_summary_of_deployment_best_practices.html
keywords: SM-BC, SMBC, best practices, planning, SAN, Mediator, SnapMirror
summary: There are several best practices that you should consider as part of planning an SnapMirror Business Continuity deployment.
---

= Summary of deployment best practices
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-04 10:10:11.777965
//

[.lead]
There are several best practices that you should consider as part of planning an SnapMirror Business Continuity deployment.

=== SAN

The SnapMirror Business Continuity solution supports only SAN workloads. You should follow the SAN best practices in all cases.

In addition:

* Replicated LUNs in the secondary cluster must be mapped to the host and the I/O paths to the LUNs from both the primary and secondary cluster must be discovered at the time of host configuration.
* After an out of sync (OOS) event exceeds 80 seconds, or after an automatic unplanned failover, it is important to rescan the host LUN I/O path to ensure that there is no I/O path loss.  For more information, see the respective host OS vendor's documentation on rescan of LUN I/O paths.

=== Mediator

To be fully functional and to enable automatic unplanned failover, the external ONTAP mediator should be provisioned and configured with ONTAP clusters.

When installing the mediator, you should replace the self-signed certificate with a valid certificate signed by a mainstream reliable CA.

=== SnapMirror

You should terminate an SnapMirror relationship in the following order:

. Perform `snapmirror delete` at the destination cluster
. Perform `snapmirror release` at the source cluster
