---
sidebar: sidebar
permalink: smbc/smbc_plan_additional_restrictions_and_limitations.html
keywords: SM-BC, SMBC, restrictions, limitations, consistency group, volume
summary: There are several additional restrictions and limitations when using the SnapMirror Business Continuity solution.
---

= Additional restrictions and limitations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-04 10:10:11.686088
//

[.lead]
There are several additional restrictions and limitations when using the SnapMirror Business Continuity solution.

=== Consistency groups

From ONTAP 9.8 to 9.9.1, the maximum number of SnapMirror Synchronous consistency group relationships in a cluster is five, a limit which is platform-independent. Beginning in ONTAP 9.10.1, the maximum number of SnapMirror Synchronous consistency group relationships in a cluster is 20. If you reach or attempt to exceed this limit, an error message will display.

=== Volumes per consistency group

From ONTAP 9.8 to 9.9.1, the maximum number of volumes supported per SnapMirror Synchronous consistency group relationship is twelve, a limit which is platform-independent. Beginning in ONTAP 9.10.1, the maximum number of volumes supported per SnapMirror Synchronous relationship is sixteen. If you reach or attempt to exceed this limit, an error message will display.

=== Volumes

[NOTE]
The limit is on the number of endpoints and not the number of relationships. A consistency group with 12 volumes contributes 12 endpoints on both the source and destination.A SnapMirror Synchronous relationship with both source and destination volumes on the same HA pair contributes 2 endpoints.

The maximum endpoints per platform are included in the following table.

[%header, hrows=4]
|===
|S. No |Platform 2+|Endpoints per HA for SM-BC 2+|Overall sync and SM-BC endpoints per HA 
|
|
|ONTAP 9.8-9.9 |ONTAP 9.10.1 |ONTAP 9.8-9.9 |ONTAP 9.10.1
|1
|AFF
|60
|200
|80
|200
|2
|ASA
|60
|200
|80
|200
|===

=== SAN object limits

The following SAN object limits are included in the following table and apply regardless of the platform.

|===
|Limits of objects in an SM-BC relationship |Count

|LUNs per volume
|256
|LUN maps per node
|2048
|LUN maps per cluster
|4096
|LIFs per VServer (with at least one volume in an SM-BC relationship)
|256
|Inter-cluster LIFs per node
|4
|Inter-cluster LIFs per cluster
|8
|===

=== NTFS security style

NTFS security style is not supported on SM-BC volumes.

=== Solaris

Beginning in ONTAP 9.10.1, SM-BC supports Solaris 11.4. You can configure the Solaris operating system with SM-BC consistency groups and avail the data protection offered by SM-BC. 

To use Solaris 11.4 with SM-BC in ONTAP 9.10.1, you will need to modify the parameters in the Solaris MPIO stack.

.Steps
. Create the configuration file `/etc/driver/drv/scsi_vhci.conf` with an entry similar to the following for the NetApp storage type connected to the host:
+
`scsi-vhci-failover-override = "NETAPP  LUN","f_tpgs";`
. Use the `devprop` and `mdb` commands to verify the override has been successfully implemented.
----
root@host-A:~# devprop -v -n /scsi_vhci scsi-vhci-failover-override
      scsi-vhci-failover-override=NETAPP  LUN + f_tpgs
root@host-A:~# echo "*scsi_vhci_dip::print -x struct dev_info devi_child | ::list struct dev_info devi_sibling | ::print struct dev_info devi_mdi_client | ::print mdi_client_t ct_vprivate | ::print struct scsi_vhci_lun svl_lun_wwn svl_fops_name" | mdb -k
      svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
      svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----

NOTE: `conf` will be added to the `svl_fops_name` when a `scsi-vhci-failover-override` has been applied.


//BURT 1387138
//BURT 1431859, 29 nov 2021