---
sidebar: sidebar
permalink: smbc/smbc_install_creating_a_consistency_group_relationship.html
keywords: SM-BC, SMBC, consistency group, create, constituent
summary: You must create a SnapMirror consistency group which also establishes the synchronous consistency group relationship.
---

= Create a consistency group relationship
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You must create a SM-BC consistency group which also establishes the synchronous consistency group relationship.

[NOTE]
This workflow applies to users in ONTAP 9.8 and 9.9.1. Beginning with ONTAP 9.10.1, these ONTAP CLI commands still can be used to create a consistency group; however, it is recommended that you manage consistency groups with System Manager or the ONTAP REST API.

.Before you begin

The following prerequisites and restrictions apply:

* You must be a cluster or storage VM administrator
* You must have a SnapMirror Synchronous license
* The destination volumes must be type DP
* The primary and the secondary storage VM must be in a peered relationship
* All constituent volumes in a consistency group must be in a single Storage VM
* You cannot establish SM-BC consistency group relationships across ASA clusters and non-ASA clusters
* The name of the consistency group must be unique

.About this task

You must create the consistency group relationship from the destination cluster.  You can map up to 12 constituents using the `cg-item-mappings` parameter on the `snapmirror create` command.

.Steps

. Create a consistency group and constituent relationship. This example creates two consistency groups: cg_src with constituent volumes vol1 and vol2, and cg_dist with constituent volumes vol1_dr and vol2_dr.
+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOver`

// 03 AUG 2021, ontap-issues-204
// 27 OCT 2021, BURT 1404382
// 24 JAN 2022, BURT 1449057
