---
sidebar: smbc_sidebar
permalink: smbc/smbc_plan_additional_restrictions_and_limitations.html
keywords:
summary:
---

= Additional restrictions and limitations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-04 10:10:11.686088
//

[.lead]
There are several additional restrictions and limitations when using the SnapMirror Business Continuity solution.

=== Consistency groups

The maximum number of SnapMirror Synchronous Consistency Group relationships in a cluster is five, a limit which is platform-independent. If you reach or attempt to exceed this limit, the following message is displayed:

....
The number of SnapMirror Synchronous Consistency Group relationships in a cluster cannot exceed 5
....

=== Volumes per consistency group

The maximum number of volumes supported per SnapMirror Synchronous Consistency Group relationship is twelve, a limit which is platform-independent. If you reach or attempt to exceed this limit, the following message is displayed:

....
The number of volumes in a SnapMirror Synchronous Consistency Group cannot exceed 12
....

=== Volumes

[NOTE]
The limit is on the number of endpoints and not the number of relationships. A consistency group with 12 volumes contributes 12 endpoints on both the source and destination.A SnapMirror Synchronous relationship with both source and destination volumes on the same HA pair contributes 2 endpoints.

The maximum endpoints per platform are included in the following table.

|===
|S. No |Platform |Endpoints per HA for SM-BC |Overall sync and SM-BC endpoints per HA

|1
|AFF
|60
|80
|2
|ASA
|60
|80
|===

=== SAN object limits

The following SAN object limits are included in the following table and apply regardless of the platform.

|===
|Limits of objects in an SM-BC relationship |Count

|LUNs per volume
|256
|LUN maps per node
|2048
|LUN maps per cluster
|4096
|LIFs per VServer (with at least one volume in an SM-BC relationship)
|256
|Inter-cluster LIFs per node
|4
|Inter-cluster LIFs per cluster
|8
|===
