---
sidebar: smbc_sidebar
permalink: smbc/smbc_plan_preparing_to_use_the_ontap_mediator.html
keywords:
summary:
---

= Preparing to use the ONTAP Mediator
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-04 10:10:11.762519
//

[.lead]
The ONTAP Mediator establishes a quorum for the ONTAP clusters in an SM-BC relationship. It coordinates automated failover when a failure is detected and helps to avoids split-brain scenarios when each cluster simultaneously tries to establish control as the primary cluster.

=== Prerequisites for the ONTAP Mediator

The ONTAP Mediator includes its own set of prerequisites. You must meet these prerequisites before installing the mediator. For more information, see http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-8551894A-DA64-4F16-9CFF-C3DF5AF9B105.html?cp=11_1_4_0_2[Installing or upgrading the ONTAP Mediator service^].

=== Network configuration

By default, the ONTAP Mediator provides service through TCP port 31784. You should make sure that port 31784 is open and available between the ONTAP clusters and the mediator.
