---
sidebar: sidebar
permalink: smbc/smbc_install_installing_the_ontap_mediator.html
keywords: SM-BC, SMBC, Mediator, license, install, Linux, host
summary: You must install the ONTAP Mediator, which includes accepting the licensing agreement, before you can configure and use the SnapMirror Business Continuity solution.
---

= Installing the ONTAP Mediator
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-04 10:10:29.101393
//

[.lead]
You must install the ONTAP Mediator, which includes accepting the licensing agreement, before you can configure and use the SnapMirror Business Continuity solution.

.Before you begin

The following software is required:

* ONTAP Mediator 1.2 or later
* One of the following Linux distributions:
** RHEL 7.6 or 7.7
** CentOS 8.0 or 8.1

.About this task

You should install the ONTAP Mediator at an external site that is physically separated from the two ONTAP clusters.

For complete installation instructions, see http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-8551894A-DA64-4F16-9CFF-C3DF5AF9B105.html?cp=11_1_4_0_2[Installing or upgrading the ONTAP Mediator service^]

.Steps

. Sign into the Linux system that will host the ONTAP Mediator.

. Download the mediator installation package from the ONTAP Mediator page.
+
https://mysupport.netapp.com/products/p/ontap_mediator.html[NetApp Downloads: ONTAP Mediator^].

. Install the ONTAP Mediator and respond to all prompts as required:
+
`./ontap-mediator_1.2`

. Optionally replace the self-signed SSL and certificate authority (CA) with the third party validated SSL Certificate and CA. The certificate you install must not be expired. Copy the contents of the ca.crt file from the ONTAP Mediator directory:
+
`/opt/netapp/lib/ontap_mediator/ontap_mediator/server_config`

. At the ONTAP CLI, install the certificate on both the local and peer cluster:
+
`security certificate install -type server-ca -vserver cserverName`
