---
sidebar: sidebar
permalink: smbc/smbc_admin_add_and_remove_volumes_in_consistency_groups.html
keywords: SM-BC, SMBC, volume, consistency group, remove volume, add volume
summary: If you want to change the composition of the consistency group by adding or removing a volume, you must first delete the original relationship and then create the consistency group again with the new composition.
---
= Add and remove volumes in a consistency group
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
If you want to change the composition of the consistency group by adding or removing a volume, you must first delete the original relationship and then create the consistency group again with the new composition.

[NOTE]
This workflow applies to ONTAP 9.8 and 9.9.1. Beginning with ONTAP 9.10.1, it is recommended that you manage link:../consistency-groups/index.html[consistency groups] through System Manager or with the ONTAP REST API.
Beginning in ONTAP 9.12.1, you can add or remove volumes to a consistency group using System Manager or the ONTAP REST API. You will have to break the SM-BC relationship before you can modify the consistency group and then restore SM-BC protection. For more information about this process, refer to xref:../consistency-groups/modify-task.html[Modify a consistency group].

.About this task

* The composition change is not allowed when the consistency group is in the “InSync” state.
* The destination volume should be of type DP.

NOTE: The new volume you add to expand the consistency group must have a pair of common Snapshot copies between the source and destination volumes.

.Steps

This procedure assumes that there are two volume mappings: vol_src1 <--> vol_dst1 and vol_src2 <--> vol_dst2, in a consistency group relationship between the end points vs1_src:/cg/cg_src and vs1_dst:/cg/cg_dst.

. Verify that a common Snapshot copy exists between the source and destination volumes on both the source and destination cluster:
+
`source::>snapshot show -vserver vs1_src -volume vol_src3 -snapshot snapmirror*`
+
`destination::>snapshot show -vserver vs1_dst -volume vol_dst3 -snapshot snapmirror*`

. If no common Snapshot copy exists, create and initialize a FlexVol SnapMirror relationship:
+
`destination::>snapmirror initialize -source-path vs1_src:vol_src3 -destination-path vs1_dst:vol_dst3`

. Delete the zero RTO consistency group relationship:
+
`destination::>snapmirror delete -destination-path vs1_dst:vol_dst3`

. Release the source SnapMirror relationship and retain the common Snapshot copies:
+
`source::>snapmirror release -relationship-info-only true -destination-path vs1_dst:vol_dst3`

. Unmap the LUNs and delete the existing consistency group relationship:
+
`destination::>lun mapping delete -vserver vs1_dst -path <lun_path> -igroup <igroup_name>`
+
NOTE: The destination LUNs are unmapped, while the LUNs on the primary copy continue to serve the host I/O.
+
`destination::>snapmirror delete -destination-path vs1_dst:/cg/cg_dst`
+
`source::>snapmirror release -destination-path vs1_dst:/cg/cg_dst -relationship-info-only true`

. **If you are using ONTAP 9.10.1 or later,** delete and recreate and the consistency group on the source with the correct composition. Follow the steps in xref:../consistency-groups/delete-task.html[Delete a consistency group] and then xref:../consistency-groups/configure-task.html[Configure a single consistency group]. In ONTAP 9.10.1 and later, you must perform the delete and create operations in System Manager or with the ONTAP REST API; there is no CLI procedure.
+
**If you are using ONTAP 9.8, 9.0, or 9.9.1, skip to the next step.**

. Create the new consistency group on the destination with the new composition:
+
`destination::>snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1, vol_src2:@vol_dst2, vol_src3:@vol_dst3`

. Resynchronize the zero RTO consistency group relationship to ensure it is in sync:
+
`destination::>snapmirror resync -destination-path vs1_dst:/cg/cg_dst`

. Remap the LUNs that you unmapped in Step 5:
+
`destination::> lun map -vserver vs1_dst -path <lun_path> -igroup <igroup_name>`

. Rescan host LUN I/O paths to restore all paths to the LUNs.

// BURT 1449057, 27 JAN 2022
// BURT 1506684, 11 OCT 2022