---
sidebar: sidebar
permalink: smbc/smbc_plan_additional_restrictions_and_limitations.html
keywords: SM-BC, SMBC, restrictions, consistency group, endpoint limits, solaris, aix
summary: There are several additional restrictions and limitations when using the SnapMirror Business Continuity solution.
---
= Additional restrictions and limitations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-04 10:10:11.686088
//

[.lead]
There are several additional restrictions and limitations when using the SnapMirror Business Continuity solution.

== Consistency groups in a cluster
Consistency group limits for a cluster with SM-BC are calculated based on relationships and depend on the version of ONTAP used. Limits are platform-independent. 

[options="header"]
|===
| ONTAP version | Maximum number of relationships
| ONTAP 9.8-9.9.1 | 5
| ONTAP 9.10.1 | 20
| ONTAP 9.11.1 | 50
|===

== Volumes per consistency group

From ONTAP 9.8 to 9.9.1, the maximum number of volumes supported per SM-BC consistency group relationship is twelve, a limit which is platform-independent. Beginning with ONTAP 9.10.1, the maximum number of volumes supported per SM-BC relationship is sixteen.

== Volumes

Limits in SM-BC are calculated based on the number of endpoints, not the number of relationships. A consistency group with 12 volumes contributes 12 endpoints on both the source and destination. Both SM-BC and SnapMirror Synchronous relationships contribute to the total number of endpoints.

The maximum endpoints per platform are included in the following table.

[options="header"]
|===
| S. No |Platform 3+| Endpoints per HA for SM-BC 3+| Overall sync and SM-BC endpoints per HA
|
|
|ONTAP 9.8-9.9.1 |ONTAP 9.10.1 |ONTAP 9.11.1 |ONTAP 9.8-9.9.1 |ONTAP 9.10.1 |ONTAP 9.11.1
|1
|AFF
|60
|200
|400
|80
|200
|400
|2
|ASA
|60
|200
|400
|80
|200
|400
|===

== SAN object limits

The following SAN object limits are included in the following table and apply regardless of the platform.

|===
|Limits of objects in an SM-BC relationship |Count

|LUNs per volume
|256
|LUN maps per node
|2048
|LUN maps per cluster
|4096
|LIFs per VServer (with at least one volume in an SM-BC relationship)
|256
|Inter-cluster LIFs per node
|4
|Inter-cluster LIFs per cluster
|8
|===

== NTFS Security Style

NTFS security style is not supported on SM-BC volumes.

== Fan-out configurations

SM-BC supports xref:../data-protection/supported-deployment-config-concept.html[fan-out configurations] with the `MirrorAllSnapshots` policy and, beginning in ONTAP 9.11.1, the the `MirrorAndVault` policy. Fan-out configurations are not supported with `XDPDefault` policy. 

If you experience a failover on the SM-BC destination in a fan-out configuration, you will have to manually xref:resume-protection-fan-out-configuration.html[resume protection in the fan-out configuration].

== AIX

Beginning with ONTAP 9.11.1, AIX is supported with SM-BC. 

With an AIX configuration, the primary cluster is the "active" cluster.
The LUN mapping will appear hidden, but the data will still be replicated to the destination. 
//What is RTPG? 

Secondary hidden paths will not show up during the initial LUN mapping procedure. Once a failover occurs, the secondary path is exposed to the host, and the primary path becomes hidden. Once this occurs, you must remove the primary path using the `rmpath` procedure. Until the paths are removed, the host will continue to send

In an AIX configuration, failovers are disruptive. With each failover, you will need to perform a rescan on the host for I/o operations to resume. 

See xref:smbc_install_mapping_luns_to_the_application_hosts.html[Mapping LUNS to the application host] for further details about this process

=== ONTAP configuration

See KB 

=== AIX configuration

The AIX host configured with SMBC luns will discover the paths only from the primary cluster after the lun map. The lun paths from secondary cluster will return LU_NOT_SUPPORTED SCSI response during lun discovery. Hence the secondary cluster lun paths will not be visible to the host. This target side response will also result in the following behavioural changes on the host

Automatic and planned failovers will cause a LUN to lose all its paths, prompting the application to experience I/O failure. To restore protection, you must perform a manual AIX host rescan to rediscover the paths. 

During concurrent storage failover operations on primary and secondary clusters, applications may experience higher I/O outage. You can perform a manual host rescan to recover from this. 


== Solaris Host setting recommendation for SM-BC configuration

Beginning with ONTAP 9.10.1, SM-BC supports Solaris 11.4. To ensure the Solaris client applications are nondisruptive when an unplanned site failover switchover occurs in an SM-BC environment, the following setting must be configured on Solaris 11.4 Host. This setting overrides failover module – `f_tpgs` to prevent the code path that detects the contradiction from being executed.

Follow these steps to configure the override parameter:

. Create configuration file `/etc/driver/drv/scsi_vhci.conf` with an entry similar to the following for the NetApp storage type connected to the host:
+
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
. Use `devprop` and `mdb` commands to verify the override has been successfully applied:
+
----
root@host-A:~# devprop -v -n /scsi_vhci scsi-vhci-failover-override scsi-vhci-failover-override=NETAPP  LUN + f_tpgs
root@host-A:~# echo "*scsi_vhci_dip::print -x struct dev_info devi_child | ::list struct dev_info devi_sibling| ::print struct dev_info devi_mdi_client| ::print mdi_client_t ct_vprivate| ::print struct scsi_vhci_lun svl_lun_wwn svl_fops_name"| mdb -k`
----
+
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----

NOTE: `conf` will be added to the `svl_fops_name` when a `scsi-vhci-failover-override` has been applied.
For additional information and recommended changes to default settings, refer to NetApp KB article https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration[Solaris Host support recommended settings in SnapMirror Business Continuity (SM-BC) configuration].

== HP-UX Known issues and limitations for SM-BC configuration

Beginning in ONTAP 9.10.1, SM-BC for HP-UX is supported. If an automatic unplanned failover (AUFO) event occurs on the isolated master cluster in the SM-BC configuration, it might take more than 120 seconds for I/O to resume on the HP-UX host. Depending on the applications that are running, this might not lead to any I/O disruption or error messages. If an AUFO event on the isolated master cluster occurs, you must restart applications on the HP-UX host that have a disruption tolerance of less than 120 seconds.

An AUFO event on the isolated master cluster might cause dual event failure when the connection between the primary and the secondary cluster is lost and the connection between the primary cluster and the mediator is also lost. This is considered a rare event, unlike other AUFO events.

// BURT 1451494, 2022-02-11
// BURT 1387138
// BURT 1431859, 1 dec 2021
// issue #326, 19 dec 2022
// BURT 1449057, 27 JAN 2022
// BURT 1459617 and 1451134, 10 March 2022