---
sidebar: sidebar
permalink: smbc/smbc_troubleshoot_aufo_not_triggered_on_site_b.html
keywords: SM-BC, SMBC, troubleshooting, automatic unplanned failover, aufo, failover, Mediator, quorum, snapmirror active sync
summary: A failure on Site A does not trigger an unplanned failover on Site B.
---

= Automatic unplanned failover not triggered on Site B
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]

.Issue:

A failure on Site A does not trigger an unplanned failover on Site B.

.Possible cause #1:

The ONTAP Mediator is not configured. To determine if this is the cause, issue the `snapmirror mediator show` command on the Site B cluster.

.Example:
....
Cluster2::*> snapmirror mediator show
This table is currently empty.
....

This example indicates that ONTAP Mediator is not configured on Site B.


.Solution:

Ensure that ONTAP Mediator is configured on both clusters, that the status is connected, and quorum is set to True.

.Possible cause #2:

SnapMirror consistency group is out of sync. To determine if this is the cause, view the event log to view if the consistency group was in sync during the time at which the Site A failure occurred.

.Example:
....
cluster::*> event log show -event *out.of.sync*

Time                Node             Severity      Event
------------------- ---------------- ------------- ---------------------------
10/1/2020 23:26:12  sti42-vsim-ucs511w ERROR       sms.status.out.of.sync: Source volume "vs0:zrto_cg_556844_511u_RW1" and destination volume "vs1:zrto_cg_556881_511w_DP1" with relationship UUID "55ab7942-03e5-11eb-ba5a-005056a7dc14" is in "out-of-sync" status due to the following reason: "Transfer failed."
....

.Solution:

Complete the following steps to perform a forced failover on Site B.

. Unmap all LUNs belonging to the consistency group from Site B.

. Delete the SnapMirror consistency group relationship using the `force` option.

. Enter the `snapmirror break` command on the consistency group constituent volumes to convert volumes from DP to R/W, to enable I/O from Site B.

. Boot up the Site A nodes to create a zero RTO relationship from Site B to Site A.

. Release the consistency group with `relationship-info-only` on Site A to retain common Snapshot copy and unmap the LUNs belonging to the consistency group.

. Convert volumes on Site A from R/W to DP by setting up a volume level relationship using either the Sync policy or Async policy.

. Issue the `snapmirror resync` to synchronize the relationships.

. Delete the SnapMirror relationships with the Sync policy on Site A.

. Release the SnapMirror relationships with Sync policy using `relationship-info-only true` on Site B.

. Create a consistency group relationship from Site B to Site A.

. Perform a consistency group resync from Site A, and then verify that the consistency group is in sync.

. Rescan host LUN I/O paths to restore all paths to the LUNs.
