---
sidebar: smbc_sidebar
permalink: smbc/smbc_admin_performing_a_planned_failover.html
keywords:
summary:
---

= Performing a planned failover
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-04 11:20:04.564654
//

[.lead]
You can perform a planned failover to test your disaster recovery configuration or to perform maintenance on the primary cluster.

.Before you begin

* The relationship must be in sync
* Nondisruptive operations must not be running
* Mediator must be configured, connected,  and in quorum*About this task*

A planned failover is initiated by the administrator of the secondary cluster. The operation requires switching the master and slave roles so that the secondary cluster takes over from the primary. The secondary cluster can then begin processing input and output requests locally without disrupting client operations.

.Steps

. Start the failover operation:
+
`destination::>snapmirror failover start -destination-path   vs1_dst:/cg/cg_dst`

. Monitor the progress of the failover:
+
`destination::>snapmirror failover show`
