---
sidebar: sidebar
permalink: smbc/smbc_install_initialize_the_ontap_mediator.html
keywords: SM-BC, SMBC, Mediator, initialize, ONTAP
summary: You must initialize Mediator on one of your cluster peers before SM-BC can perform planned and automatic unplanned failover operations.
---

= Initialize the ONTAP Mediator
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You must initialize Mediator on one of your cluster peers before SM-BC can perform planned and automatic unplanned failover operations.

== Before you begin 

Confirm that you have link:../mediator/index.html[installed and upgraded the ONTAP Mediator service].

== Initialize the ONTAP mediator for SM-BC

You can configure the ONTAP mediator using System Manager or the ONTAP CLI. 

[role="tabbed-block"]
====
.System Manager
--
With System Manager, you can configure the Mediator server for automated failover. You can also replace the self-signed SSL and CA with the third party validated SSL Certificate and CA if you have not already done so.

.Steps
.	Navigate to *Protection > Overview > Mediator > Configure*.
.	Select *Add*, and enter the following Mediator server information:
+
*	IPv4 address
*	Username
*	Password
*	Certificate
--

.CLI
--
You can initialize Mediator from either cluster using the ONTAP CLI. When you issue the `mediator add` command on one cluster, the mediator is automatically added on the other cluster.

.Steps
. Initialize Mediator on one of the clusters:
+
`snapmirror mediator add -mediator-address IP_Address -peer-cluster cluster_name -username user_name`
+
*Example*
+
....
cluster1::> snapmirror mediator add -mediator-address 192.168.10.1 -peer-cluster cluster2 -username mediatoradmin
Notice: Enter the mediator password.

Enter the password: ******
Enter the password again: ******
....
. Check the status of the Mediator configuration:
+
`snapmirror mediator show`
+
....
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
192.168.10.1     cluster-2        connected         true
....
+
`Quorum Status` indicates whether the SnapMirror consistency group relationships are synchronized with the mediator; a status of `true` indicates successful synchronization.
--
====

