---
sidebar: sidebar
permalink: smbc/smbc_install_confirm_the_ontap_cluster_configuration.html
keywords: SM-BC, SMBC, ONTAP, cluster, configure, peering, volume, SVM, SAN, LIFs, map, igroup, discover
summary: You should make sure that your source and destination clusters are configured properly.
---

= Confirm the ONTAP cluster configuration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-04 10:10:29.130581
//

[.lead]
You should make sure that your source and destination clusters are configured properly.

.About this task

Proceed through each of the following steps. For each step, you should confirm that the specific configuration has been performed. Use the link included after each step to get more information as needed.

.Steps

. Confirm that a cluster peering relationship exists between the clusters.
+
NOTE: The default IPspace is required by SM-BC for cluster peer relationships. Custom IPspace is not supported.
+
link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-csp/GUID-5AC8B2CD-9203-4F61-A5FB-C177A22F0C29.html?cp=8_1_3[Configure peer relationships^]

. Confirm that the Storage VMs are created on each cluster.
+
link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-4CF9FEB6-083C-42A0-8B4B-78F51EFCE2F4.html?cp=4_1_5_0_1_4[Creating an SVM^]

. Confirm that a peer relationship exists between the Storage VMs on each cluster.
+
link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/GUID-84C089E7-1A5C-43AF-99B5-9DDB5100B3EA.html?cp=8_2_2_1_2[Creating an SVM peering relationship^]

. Confirm that the volumes exist for your LUNs.
+
link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-cifs-cg/GUID-A8F1A48F-81B8-46B6-AFAC-F4A01B99CFF6.html?cp=13_6_3_0_0[Creating a volume^]

. Confirm that at least one SAN LIF is created on each node in the cluster.
+
link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/GUID-A34528DF-C287-4B1A-9BEF-3EC4CCFA240F.html?cp=13_6_7_4_0_1[Considerations for LIFs in a cluster SAN environment^]
+
link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/GUID-4B666C44-694A-48A3-B0A9-517FA7FD2502.html?cp=13_6_4_0[Creating a LIF^]

. Confirm that the necessary LUNs are created and mapped to igroup, which is used to map LUNs to the initiator on the application host.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/GUID-D4DAC7DB-A6B0-4696-B972-7327EE99FD72.html?cp=13_6_1_0_2_5[Create LUNs and map igroups^]

. Rescan the application host to discover any new LUNs.

// 2021-6-30, BURT 1411387
