---
sidebar: sidebar
permalink: smbc/smbc_admin_upgrade_and_revert_considerations.html
keywords: SM-BC, SMBC, upgrade, revert, ONTAP
summary: You should be aware of the requirements for upgrading and reverting an SM-BC configuration.
---

= SM-BC upgrade and revert considerations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You should be aware of the requirements for upgrading and reverting an SM-BC configuration.

=== Upgrade

Before you can configure and use SM-BC, you must upgrade all nodes on the source and destination clusters to ONTAP 9.8 or later.  See
link:link:../upgrade/index.html[Updating software on ONTAP clusters].

[NOTE]
SM-BC is not supported with mixed ONTAP 9.7 and ONTAP 9.8 clusters.

Upgrading clusters from 9.8 or 9.9.1 to 9.10.1 creates new consistency groups on both source and destination for SM-BC relationships.

=== Reverting to ONTAP 9.9.1 from ONTAP 9.10.1

To revert relationships from 9.10.1 to 9.91, SM-BC relationships must be deleted, followed by the 9.10.1 consistency group instance. Consistency groups cannot be deleted with an active SMBC relationship. Any FlexVol volumes that were upgraded to 9.10.1 previously associated with another Smart Container or Enterprise App in 9.9.1 or earlier will no longer be associated on revert. Deleting consistency groups does not delete the constituent volumes or volume granular snapshots. Refer to link:../consistency-groups/delete-task.html[Delete a consistency group] for more information on this task.

=== Reverting to ONTAP 9.7 from ONTAP 9.8

When you revert from ONTAP 9.8 to ONTAP 9.7, you must be aware of the following:

* If the cluster is hosting an SM-BC destination, reverting to ONTAP 9.7 is not allowed until the relationship is broken and deleted.
* If the cluster is hosting an SM-BC source, reverting to ONTAP 9.7 is not allowed until the relationship is released.
* All user-created custom SM-BC SnapMirror policies must be deleted before reverting to ONTAP 9.7.

.Steps

. Perform a revert check from one of the clusters in the SM-BC relationship:
+
`cluster::*> system node revert-to -version 9.7 -check-only`
+
Example:
+
....
cluster::*> system node revert-to -version 9.7 -check-only
Error: command failed: The revert check phase failed. The following issues must be resolved before revert can be completed. Bring the data LIFs down on running vservers. Command to list the running vservers: vserver show -admin-state running Command to list the data LIFs that are up: network interface show -role data -status-admin up Command to bring all data LIFs down: network interface modify {-role data} -status-admin down
Disable snapshot policies.
    Command to list snapshot policies: "snapshot policy show".
    Command to disable snapshot policies: "snapshot policy modify -vserver
   * -enabled false"

   Break off the initialized online data-protection (DP) volumes and delete
   Uninitialized online data-protection (DP) volumes present on the local
   node.
    Command to list all online data-protection volumes on the local node:
   volume show -type DP -state online -node <local-node-name>
    Before breaking off the initialized online data-protection volumes,
   quiesce and abort transfers on associated SnapMirror relationships and
   wait for the Relationship Status to be Quiesced.
    Command to quiesce a SnapMirror relationship: snapmirror quiesce
    Command to abort transfers on a SnapMirror relationship: snapmirror
   abort
    Command to see if the Relationship Status of a SnapMirror relationship
   is Quiesced: snapmirror show
    Command to break off a data-protection volume: snapmirror break
    Command to break off a data-protection volume which is the destination
   of a SnapMirror relationship with a policy of type "vault": snapmirror
   break -delete-snapshots
    Uninitialized data-protection volumes are reported by the "snapmirror
   break" command when applied on a DP volume.
    Command to delete volume: volume delete

   Delete current version snapshots in advanced privilege level.
    Command to list snapshots: "snapshot show -fs-version 9.8"
    Command to delete snapshots: "snapshot prepare-for-revert -node
   <nodename>"

   Delete all user-created policies of the type active-strict-sync-mirror
   and active-sync-mirror.
   The command to see all active-strict-sync-mirror and active-sync-mirror
   type policies is:
    snapmirror policy show -type
   active-strict-sync-mirror,active-sync-mirror
   The command to delete a policy is :
    snapmirror policy delete -vserver <vserver-name> -policy <policy-name>
....

For information on reverting clusters, see link:../revert/index.html[Revert ONTAP].

// BURT 1449057, 24 JAN 2022
