---
sidebar: networking-app_sidebar
permalink: networking-app/decide_whether_to_use_this_network_management_guide.html
keywords: ONTAP 9.8 and later, CLI, decide, deciding, find, finding
summary: Find the right network management guide
---

= Decide whether to use this network management guide
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-23 12:34:43.138031
//

[.lead]
This guide describes basic storage network administration for ONTAP 9.8 and later. It shows you how to configure physical and virtual network ports (VLANs and interface groups), how to create LIFs using IPv4 and IPv6, how to manage routing and host-resolution services in clusters, how to use load balancing to optimize network traffic, and how to monitor a cluster using SNMP.

You should use this guide under the following circumstances:

* You want to understand the range of ONTAP 9.8 network management capabilities.
* You want to use the CLI, not ONTAP System Manager.
* You are configuring networking on a new system running ONTAP 9.8 or later.
* You are upgrading to ONTAP 9.8 or later from a system running 9.7 or earlier.

If you have an ONTAP release earlier than 9.8, you should use the following documentation:

* https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html[Network Management for ONTAP 9.7 or earlier^]

If you want to use ONTAP System Manager to configure the network, you should choose the following documentation:

* https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help/GUID-DF04A607-30B0-4B98-99C8-CB065C64E670.html[Cluster management using System Manager^]

If you require additional configuration or conceptual information, you should choose among the following documentation:

* Conceptual background for network configuration
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html[ONTAP concepts^]
* NAS file access
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-nfs/home.html[NFS management^]
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html[SMB/CIFS management^]
* SAN host provisioning
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html[SAN administration^]
* Command reference
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands^]
* Technical Reports (TRs), which include additional information about ONTAP technology and interaction with external services
** http://www.netapp.com/us/media/tr-4182.pdf[NetApp Technical Report 4182: Ethernet Storage Design Considerations and Best Practices for Clustered Data ONTAP Configurations^]
