---
permalink: abac/abac-overview.html
sidebar: sidebar
keywords: technical report, tr, abac, attribute, access control, attribute based, nfs, security labels, xattrs, nfs 4.2, nist, abac compliant, data management, role-based access control, rbac, policy enforcement point, pep, policy decision point, pdp
summary: "ONTAP, when configured with NFS 4.2 security labels and Extended Attributes (xattrs), can be integrated with a role-based access control (RBAC) and attribute-based access control (ABAC) identity and access control software that is a NIST ABAC-compliant data management solution."
---
= Attribute-based access control with ONTAP
:icons: font
:imagesdir: ../media/

[.lead]

Beginning with 9.12.1, you can configure ONTAP with NFSv4.2 security labels and extended attributes (xattrs) to support role-based access control (RBAC) with attributes and attribute-based access control (ABAC).

ABAC is an authorization strategy that defines permissions based on user attributes, resource attributes, and environmental conditions. The integration of ONTAP with NFS 4.2 security labels and xattrs complies with NIST standards for ABAC solutions, as set forth in NIST Special Publication 800-162.

You can use NFS 4.2 security labels and xattrs to assign files user-defined attributes and labels. ONTAP can integrate with ABAC-oriented identity and access management software to enforce granular file and folder access control policies based on these attributes and labels.
 
.Related information

* link:../abac/abac-approaches.html[Approaches to ABAC with ONTAP]

* link:https://www.netapp.com/media/10720-tr-4067.pdf[NFS in NetApp ONTAP: Best practice and implementation guide^]

// 2025-1-14 ONTAPDOC-2595
// 2024-11-15 ONTAPDOC-2303