---
sidebar: sidebar
permalink: s3-snapmirror/create-s3-snapshot.html
keywords: s3 snapshots, snapshot verview
summary: You can create a point-in-time backup of your S3 bucket using the S3 Snapshot technology. 
---

= Create S3 snapshots
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can either manually generate S3 snapshots or set up snapshot policies to automatically create S3 snapshots for you. Snapshots serve as static copies of objects that you use for data backup and recovery. For determining the tenure of snapshot retention, you can create snapshot policies that facilitate automatic snapshot creation at specified intervals.

S3 snapshots help you protect your object data in S3 buckets with or without object versioning enabled. 

[TIP]
Snapshots can be especially useful in establishing data protection when object versioning is not enabled in an S3 bucket, because they act as point-in-time records that you can use to restore a bucket even when a previous version of the bucket is not available.

.About this task
* The following naming rules apply to snapshot (for both manual and automatic snapshots):

** S3 snapshot names can be up to 30 characters
** S3 snapshot names can consist only of lowercase letters, numbers, dots (.), and hyphens (-)
** S3 snapshot names must end with a letter or number
** S3 snapshot names cannot contain substring `s3snap`
* In the context of the S3 protocol, the bucket naming restrictions limit a bucket name to 63 characters. Because ONTAP S3 snapshots are presented as buckets through the S3 protocol, similar restrictions apply to the synthetic snapshot bucket names. By default, the original bucket name is used as the base bucket name.
* To make it easier to identify which snapshot belongs to which bucket, the synthetic snapshot bucket name consists of the base bucket name, along with a special string, `-s3snap-`, that's prefixed to the snapshot name. The synthetic bucket names are formatted as `<base-bucket-name>-s3snap-<snapshot-name>`.
+
For example, running the following command to create `snap1` on `bucketA` creates a synthetic snapshot bucket with name `bucketA-s3snap-snap1`.
+
----
vserver object-store-server bucket snapshot create -bucket bucketA -snapshot snap1
----
* You cannot create a snapshot that results in synthetic snapshot bucket name with more than 63 characters.
* The automatic snapshot name contains the policy schedule name and the timestamp, which is similar to the naming convention for the traditional volume snapshots. For example, the scheduled snapshot names can be `daily-2024-01-01-0015` and `hourly-2024-05-22-1105`.


== Manually create S3 snapshots
You can manually create an S3 snapshot by using the ONTAP CLI. The procedure creates a snapshot on the local cluster only.

.Steps
. Create an S3 snapshot:

----
vserver object-store-server bucket snapshot create -vserver <vserner-name> -bucket <bucket-name> -snapshot <snapshot-name>
----

The following example creates a snapshot named `pre-update` on the `vs0` storage VM and `website-data` bucket:

----
vserver object-store-server bucket snapshot create -vserver vs0 -bucket website-data -snapshot pre-update
----

== Assign an S3 snapshot policy to a bucket
When you configure snapshot policies at the S3 bucket level, ONTAP creates scheduled S3 snapshots for you automatically. You can also use S3 snapshot policies to actively delete old snapshots. Like traditional snapshot policies, up to five schedules can be configured for S3 snapshots.

A Snapshot policy typically specifies the time to create snapshots, the number of copies to retain, and their naming convention. For example, a policy can create one S3 snapshot every day at 12:10 AM, retain the two most recent copies, and name them `daily.timestamp`.

.Before you begin
A snapshot policy must have been created before assigning it to the S3 bucket. Policies for S3 snapshots follow the same rules as other ONTAP snapshot policies. For more information about creating snapshot policies for autogenerating snapshots, refer to https://docs.netapp.com/us-en/ontap/data-protection/create-snapshot-policy-task.html[Create a snapshot policy^].

.Steps

. Assign the snapshot policy on your bucket:

----
vserver object-store-server bucket modify/create -snapshot-policy <policy_name>
----

[NOTE]
If you need to revert a cluster to an ONTAP version earlier than ONTAP 9.16.1, ensure that the value for `snapshot-policy` for all the buckets is set to `none` (or `-`).


.Related information

* For information about S3 snapshots, refer to link:../s3-snapshot-overview.html[S3 Snapshot overview].
* For information about ONTAP volume snapshots, refer to https://docs.netapp.com/us-en/ontap/concepts/snapshot-copies-concept.html[Snapshot copies^].
