---
sidebar: sidebar
permalink: s3-snapmirror/create-s3-snapshot.html
keywords: s3 snapshots, snapshot verview
summary: You can create a point-in-time backup of your S3 bucket using the S3 Snapshot technology. 
---

= Create S3 Snapshot copies
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
With the S3 Snapshot feature, you have the option to manually generate snapshots or set up snapshot policies to automatically create them. Snapshots serve as static copies of objects that you use for data backup and recovery. For determining the tenure of snapshot retention, you can create snapshot policies that facilitate automatic snapshot creation at specified intervals.

S3 Snapshot copies help you in protecting your object data in buckets with or without versioning enabled. 

[TIP]
Snapshots can be especially useful in establishing data protection when versioning is not enabled in a bucket.

.About this task



== Manually create Snapshot copies
You can manually create a Snapshot copy by using the ONTAP CLI. The procedure creates a Snapshot copy on the local cluster only.

. Create a snapshot:

----
vserver object-store-server bucket snapshot create -vserver <vserner-name> -bucket <bucket-name> -snapshot <snapshot-name>
----

The following example creates a Snapshot copy named `pre-update` on the `vs0` storage VM and `website-data` bucket:

----
vserver object-store-server bucket snapshot create -vserver vs0 -bucket website-data -snapshot pre-update
----

== Assign a Snapshot policy on a bucket to generate snapshots

Assigning a Snapshot policy on a versioned or non-versioned bucket enables you to protect your data by automatically generating Snapshot copies of your S3 objects. 
A Snapshot policy specifies the time to create Snapshot copies, number of copies to retain, and their naming convention. For example, a system might create one Snapshot copy every day at 12:10 AM, retain two most recent copies, and name them `daily.timestamp`.

.Before you begin
A Snapshot policy must have been created before assigning it to the S3 bucket. 
For information about creating Snapshot policies for autogenerating Snapshot copies, refer to https://docs.netapp.com/us-en/ontap/data-protection/create-snapshot-policy-task.html[Create a Snapshot policy^].

.Steps

. Assign the Snapshot policy on your bucket:

----
vserver object-store-server bucket modify/create -snapshot-policy <POLICY>
----

[NOTE]
If you need to revert a cluster, all buckets should have snapshot policy set to `none` or `-`.


.Related information

* For information about S3 Snapshot, refer to link:../s3-snapshot-overview.html[S3 Snapshot overview].
* For information about volume snapshots in ONTAP, refer to https://docs.netapp.com/us-en/ontap/concepts/snapshot-copies-concept.html[Snapshot copies^].
