---
sidebar: sidebar
permalink: s3-snapmirror/s3-snapshot-overview.html
keywords: s3 snapshots, S3 Snapshot copy creation
summary: You can create a point-in-time backup of your S3 bucket using the S3 Snapshot technology. Point-in-time Snapshots provide a comprehensive backup solution, eliminating the need for full and continuous bucket replication.
---

= S3 Snapshot overview
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.16.1, you can use ONTAP snapshot technology to generate point-in-time backups of your ONTAP S3 buckets. By creating snapshots of your S3 buckets, you can eliminate the need for full and continuous bucket replication. 

S3 snapshots feature leverages bucket versioning to track the objects captured in a bucket snapshot. In ONTAP 9.16.1, snapshots of S3 buckets do not offer object versioning history and point-in-time tags. As a result, S3 snapshots should be governed by snapshot policies to manage the retention tenure of snapshots. 

Using the S3 snapshots feature, you can manually create snapshots or automatically generate them through snapshot policies. The default snapshot policy preserves: 

* Six hourly snapshots
* Two daily snapshots
* Two weekly snapshots

Additionally, you can browse snapshots to determine errors, restore a bucket by using the snapshot at the source volume, and delete snapshots to free up space.

.Quota and space usage
Quotas track the number of objects and logical size used in an S3 bucket. When S3 snapshots are created, the objects captured in the S3 snapshots are counted towards the bucket object count and size used, until the objects are deleted from the file system.

You can calculate the total S3 snapshot size information by link:../s3-snapmirror/manage-s3-snapshot.html#browse-s3-snapshots[browsing] the list of S3 snapshots created.

.Multipart objects
When creating S3 snapshots from multipart object uploads, only the final multipart objects are captured. Partial uploads of multipart objects are not captured in snapshots.

== Snapshots on versioned and non-versioned buckets
You can create snapshots on both versioned and non-versioned buckets, but the snapshot contains only the current object versions at a time when the snapshot is captured. 

.Versioned buckets and snapshots
In buckets with object versioning enabled, a snapshot retains the content of the most recent version after which the snapshot was taken. It excludes content of a previous version of the bucket.

Consider this example: In a bucket where object versioning is enabled, object `obj1` has versions v1, v2, v3, v4, v5. You created a snapshot `snap1` from `obj1` v3 (the most recent version at the point of capture). When browsing `snap1`, `obj1` will appear as an object with content created at v3. Content of the previous versions will not be returned.

.Non-versioned buckets and snapshots
In non-versioned buckets, the S3 snapshot preserves the content of the latest commit prior to snapshot creation.

Consider this example: In a bucket where object versioning is unavailable, object `obj1` has been overwritten several times at (t1, t2, t3, t4, t5). You created an S3 snapshot `snap1` sometime between t3 and t4. When browsing `snap1`, `obj1` will appear with the content created at t3.

== Object expiration and snapshots

ONTAP S3 object expiration and S3 snapshots feature function independently of each other. ONTAP object expiration feature expires object versions according to the lifecycle management rules defined for the S3 bucket. S3 snapshots are static copies of the bucket objects at a point in time when the snapshot is created.

If object versioning is enabled in a bucket, when a specific version (non-current version) of an object is deleted due to an expiration rule defined for that bucket, the content of the expired object continues to remain in an S3 snapshot if it was created from the non-current version of the S3 bucket. That object version will cease to exist on the file system only when that snapshot is deleted.

Similarly, in a non-versioned bucket or a bucket in which versioning is disabled, if an object is deleted based on an expiration rule, the content of the expired object is still retained in any S3 snapshot that was previously created from the object. The object will be permanently removed from the file system when the snapshots capturing it are deleted.

For information about S3 object expiration and lifecycle management, refer to https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-lifecycle-rule-task.html[Create a bucket lifecycle management rule].

.Related information

* For information about ONTAP volume snapshots, refer to https://docs.netapp.com/us-en/ontap/concepts/snapshot-copies-concept.html[Snapshot copies^]. 
