---
permalink: nvme/disable-secure-authentication-nvme-tcp-task.html
sidebar: sidebar
keywords: manage, nvme, secure, authentication, tcp, dh-hmac-hcap, chap, disable
summary: "Beginning with ONTAP 9.12.1 secure, bidirectional authentication between an NVMe host and controller is supported over NVME-TCP using the DH-HMAC-CHAP authentication protocol.   "
---
= Disable secure authentication over NVMe/TCP
:icons: font
:imagesdir: ../media/

[.lead]

If you are running the NVMe/TCP protocol and you have established secure authentication using DH-HMAC-CHAP, you can choose to disable it at any time.  

However, if you are reverting from ONTAP 9.12.1 or later to ONTAP 9.12.0 or earlier you must disable secure authentication before you revert.  If secure authentication using DH-HMAC-CHAP is not disabled, revert will fail. 

.Steps

. Remove the host from the subsystem to disable DH-HMAC-CHAP authentication:
+

`vserver nvme subsystem host remove –vserver _svm_name_ -subsystem _subsystem_ -host-nqn _host_nqn_`

. Verify that the DH-HMAC-CHAP authentication protocol is removed from the host:
+
`vserver nvme subsystem host show`

. Add the host back to the subsystem without authentication:
+

`vserver nvme subsystem host add –vserver _svm_name_ -subsystem _subsystem_ -host-nqn _host_nqn_`

// 2022 oct 07, IE-615
