---
permalink: nvme/manage-automated-discovery.html
sidebar: sidebar
keywords: nvme, tcp, nvme/tcp, disable, automated, discovery, controllers
summary: 'Beginning with ONTAP 9.13.1, host discovery of controllers using the NVMe/TCP protocol is automated by default in IP-based fabrics. '
---
= Manage automated host discovery of NVMe/TCP controllers in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]

Beginning with ONTAP 9.14.1, host discovery of controllers using the NVMe/TCP protocol is automated by default in IP-based fabrics.  

== Enable automated host discovery of NVMe/TCP controllers 

If you previously disabled automated host discovery, but your needs have changed, you can re-enable it.

.Steps 

. Enter advanced privilege mode: 
+
[source,cli]
----
set -privilege advanced 
----
 
. Enable automated discovery: 
+
[source,cli]
----
vserver nvme modify -vserver <vserver_name> -mdns-service-discovery-enabled true 
---- 

. Verify automated discovery of NVMe/TCP controllers is enabled. 
+
[source,cli]
----
vserver nvme show 
----

== Disable automated host discovery of NVMe/TCP controllers 

If you do not need NVMe/TCP controllers to be automatically discovered by your host and you detect unwanted multicast traffic on your network, you should disable this functionality. 

.Steps 

. Enter advanced privilege mode:
+
[source,cli]
----
set -privilege advanced 
----

. Disable automated discovery:   
+
[source,cli]
----
vserver nvme modify -vserver <vserver_name> -mdns-service-discovery-enabled false 
----

. Verify automated discovery of NVMe/TCP controllers is disabled. 
+
[source,cli]
----
vserver nvme show 
----


// 2025 Jan 22, ONTAPDOC-1070
// 2023 Nov 02, Jira 763