---
permalink: nvme/set-up-tls-secure-channel-nvme-task.html
sidebar: sidebar
keywords: manage, nvme, secure, encryption, in-flight, tcp, secure, channel, tcp, tls, encrypt, enable, set up 
summary: "Beginning with ONTAP 9.16.1, you can enable and disable TLS secure channel for NVMe/TCP connections."
---
= Set up TLS secure channel for NVMe/TCP
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.16.1, you can configure TLS secure channel for NVMe/TCP connections. You can use System Manager or the ONTAP CLI to either add a new NVMe subsystem with TLS enabled, or enable TLS for an existing NVMe subsystem.

== 

// start tabbed area

[role="tabbed-block"]
====

.System Manager
--

Beginning with ONTAP 9.16.1, you can use System Manager to configure TLS for NVMe/TCP connections while creating or updating an NVMe subsystem, creating or cloning NVMe namespaces, or adding consistency groups with new NVMe namespaces.

.Steps

. In System Manager, click *Hosts > NVMe Subsystem* and then click *Add*.

. Add the NVMe subsystem name, and select the storage VM and host operating system.

. Enter the Host NQN.

. Select *Require Transport Layer Security (TLS)* next to the Host NQN.

. Provide the pre-shared key (PSK).

. Click *Save*.

. To verify that TLS secure channel is enabled, select *System Manager > Hosts > NVMe Subsystem > Grid > Peek view*.
//+
// A transparent key icon next to the host name indicates that unidirectional mode is enabled. An opaque key next to the host name indicates bidirectional mode is enabled.


--

.CLI
--

.Steps

. Add DH-HMAC-CHAP authentication to your NVMe subsystem:
+
[source,cli]
----

----


--
====
// end tabbed area