---
permalink: nvme/support-limitations.html
sidebar: sidebar
keywords: nvme, namespaces, considerations, provisioning
summary: "NVMe support varies based on your version of ONTAP, your platform and your configuration."
---
= NVMe support and limitations
:icons: font
:imagesdir: ../media/

[.lead]

NVMe support and limitations varies based on your version of ONTAP, your platform and your configuration. 

== Protocol support

[cols=3*]
|===

h| Protocol h| Beginning with ... h| Allowed by...

| TCP
| ONTAP 9.10.1
| Default

| FC
| ONTAP 9.4
| Default
|===

== Platform and configuration support and limitations

Support for NVMe-oF protocol varies by platform and configuration.  For details on your specific configuration, see the link:https://imt.netapp.com/matrix/[NetApp Interoperability Matrix Tool].

NOTE: Beginning with ONTAP 9.12.1, 4-node MetroCluster IP configurations are supported on NVMe/FC.  MetroCluster configurations are not supported for NVMe prior to 9.12.1.

[cols=3*]
|===

h| Beginning with ONTAP... h| Platforms h| Max nodes per cluster

| 9.12.1
a| * FAS
* All Flash FAS (AFF)
* All SAN Array (ASA) platforms
|12

| 9.11.1
a| * AFF
* ASA
|12

| 9.9.1
a| * AFF
* ASA
| 4

| 9.4
| AFF platforms only
| 4
|===

== Namespace support and limitations

NVMe namespace support varies based on your version on ONTAP. 

[cols=2*]
|===

h| Beginning with ONTAP... h| NVMe namespaces support...

| 9.10.1 
|xref:../nvme/resize-namespace-task.html[Resizing]. 

Resizing a namespace is not supported in releases prior to ONTAP 9.10.1.

|9.6
a| * 512 byte blocks and 4096 byte blocks
+
4096 is the default value. 512 should only be used if the host operating system does not support 4096 byte blocks.

* Volume move with mapped namespaces

|===

Also, when working with NVMe namespaces, you should be aware of the following:

* If you lose data in a LUN, it cannot be restored from a namespace, or vice versa.
* The space guarantee for namespaces is the same as the space guarantee of the containing volume.
* You cannot create a namespace on a volume transition from Data ONTAP operating in 7-mode.
* Namespaces do not support the following:
** Renaming
+
You cannot rename a namespace.

** Inter-volume move
** Inter-volume copy
** Copy on Demand

== Multipath HA pair failover/giveback

Beginning with ONTAP 9.5, NVMe supports multipath HA pair failover/giveback.

== Additional limitations

The following ONTAP features are not supported by NVMe configurations:

* Sync
* Virtual Storage Console

See the https://hwu.netapp.com[NetApp Hardware Universe^] for a complete list of NVMe limits.

// 2023 June 21, ONTAPDOC 1109
// 2023 May 02, IDR-217
// 2022 Nov 18, Issue 705
// 2022 oct 7, IE-631
// 25 april 2022, issue #466