. Use the `system license show` command to verify that you have a license for FC or iSCSI. Learn more about `system license show` in the link:https://docs.netapp.com/us-en/ontap-cli/system-license-show.html[ONTAP command reference^].
+
`system license show`
+
----

Package           Type    Description           Expiration
 ----------------- ------- --------------------- --------------------
 Base              site    Cluster Base License  -
 NFS               site    NFS License           -
 CIFS              site    CIFS License          -
 iSCSI             site    iSCSI License         -
 FCP               site    FCP License           -
----

. If you do not have a license for FC or iSCSI, use the `license add` command. Learn more about `license add` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=license+add[ONTAP command reference^].
+
`license add -license-code _your_license_code_`

. Enable your protocol service on the SVM:
+
*For iSCSI:* `vserver iscsi create -vserver _vserver_name_ -target-alias _vserver_name_`
+
Learn more about `vserver iscsi create` in the link:https://docs.netapp.com/us-en/ontap-cli/vserver-iscsi-create.html[ONTAP command reference^].
+
*For FC:* `vserver fcp create -vserver _vserver_name_ -status-admin up`
+
Learn more about `vserver fcp create` in the link:https://docs.netapp.com/us-en/ontap-cli/vserver-fcp-create.html[ONTAP command reference^].

. Create two LIFs for the SVMs on each node:
+
`network interface create -vserver _vserver_name_ -lif _lif_name_ -role data -data-protocol iscsi|fc -home-node _node_name_ -home-port _port_name_ -address _ip_address_ -netmask netmask`
+
NetApp supports a minimum of one iSCSI or FC LIF per node for each SVM serving data. However, two LIFS per node are required for redundancy. Learn more about `network interface create` in the link:https://docs.netapp.com/us-en/ontap-cli/network-interface-create.html[ONTAP command reference^].

. Verify that your LIFs have been created and that their operational status is `online`:
+
`network interface show -vserver _vserver_name_ _lif_name_`
+
Learn more about `network interface show` in the link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html[ONTAP command reference^].

. Create your LUNs:
+
`lun create -vserver vserver_name -volume _volume_name_ -lun _lun_name_ -size _lun_size_ -ostype linux -space-reserve enabled|disabled`
+
Your LUN name cannot exceed 255 characters and cannot contain spaces. Learn more about `lun create` in the link:https://docs.netapp.com/us-en/ontap-cli/lun-create.html[ONTAP command reference^].
+
[NOTE]
The NVFAIL option is automatically enabled when a LUN is created in a volume.

. Create your igroups:
+
`igroup create -vserver _vserver_name_ -igroup _igroup_name_ -protocol fcp|iscsi|mixed -ostype linux -initiator _initiator_name_`
+
Learn more about `igroup create` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=igroup+create[ONTAP command reference^].
. Map your LUNs to igroups:
+
`lun mapping create -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -igroup _igroup_name_`
+
Learn more about `lun mapping create` in the link:https://docs.netapp.com/us-en/ontap-cli/lun-mapping-create.html[ONTAP command reference^].
. Verify that your LUNs are configured correctly:
+
`lun show -vserver _vserver_name_`
+
Learn more about `lun show` in the link:https://docs.netapp.com/us-en/ontap-cli/lun-show.html[ONTAP command reference^].

. link:san-admin/create-port-sets-binding-igroups-task.html[Create a port set and bind to an igroup] (optional).

. Follow steps in your host documentation for enabling block access on your specific hosts.
. Use the Host Utilities to complete the FC or iSCSI mapping and to discover your LUNs on the host.


// 2025 Mar 10, ONTAPDOC-2758