. Use the `system license show` command to verify that you have a license for FC or iSCSI.
+
`system license show`
+
----

Package           Type    Description           Expiration
 ----------------- ------- --------------------- --------------------
 Base              site    Cluster Base License  -
 NFS               site    NFS License           -
 CIFS              site    CIFS License          -
 iSCSI             site    iSCSI License         -
 FCP               site    FCP License           -
----

. If you do not have a license for FC or iSCSI, use the `license add` command.
+
`license add -license-code _your_license_code_`

. Enable your protocol service on the SVM:
+
*For iSCSI:* `vserver iscsi create -vserver _vserver_name_ -target-alias _vserver_name_`
+
*For FC:* `vserver fcp create -vserver _vserver_name_ -status-admin up`

. Create two LIFs for the SVMs on each node:
+
`network interface create -vserver _vserver_name_ -lif _lif_name_ -role data -data-protocol iscsi|fc -home-node _node_name_ -home-port _port_name_ -address _ip_address_ -netmask netmask`
+
NetApp supports a minimum of one iSCSI or FC LIF per node for each SVM serving data. However, two LIFS per node are required for redundancy.

. Verify that your LIFs have been created and that their operational status is `online`:
+
`network interface show -vserver _vserver_name_ _lif_name_`

. Create your LUNs:
+
`lun create -vserver vserver_name -volume _volume_name_ -lun _lun_name_ -size _lun_size_ -ostype linux -space-reserve enabled|disabled`
+
Your LUN name cannot exceed 255 characters and cannot contain spaces.
+
[NOTE]
The NVFAIL option is automatically enabled when a LUN is created in a volume.

. Create your igroups:
+
`igroup create -vserver _vserver_name_ -igroup _igroup_name_ -protocol fcp|iscsi|mixed -ostype linux -initiator _initiator_name_`

. Map your LUNs to igroups:
+
`lun mapping create -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -igroup _igroup_name_`
. Verify that your LUNs are configured correctly:
+
`lun show -vserver _vserver_name_`

. link:san-admin/create-port-sets-binding-igroups-task.html[Create a port set and bind to an igroup] (optional).

. Follow steps in your host documentation for enabling block access on your specific hosts.
. Use the Host Utilities to complete the FC or iSCSI mapping and to discover your LUNs on the host.

