---
sidebar: sidebar
permalink: networking/commands_for_managing_snmp.html
keywords: snmp, traps, traphosts, trap, traphost, manage, managing, users, user, configure, configuring, modify, modifying, set, setting, event, command, system snmp, security, options -option-name snmp.enable -option-value on, options -option-name snmp.enable -option-value off, commands for managing snmp, commands for managing snmp v1, v2c, and v3 users, commands for providing contact and location information, commands for managing SNMP communities, command for displaying snmp option values, commands for managing snmp traps and traphosts, commands for managing events related to snmp traps, system snmp, security login create, security snmpusers and security login show -application snmp, security login create, security login delete, security snmpusers and security login show -application snmp, security login modify, system snmp contact, system snmp location, system snmp community add, system snmp community delete, system snmp community show, system snmp show
summary: Manage SNMP, SNMP users, traps, trap events, and traphosts
---

= Commands for managing SNMP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
//

[.lead]
You can use the `system snmp` commands to manage SNMP, traps, and traphosts. You can use the `security` commands to manage SNMP users per SVM. You can use the `event` commands to manage events related to SNMP traps.

== Commands for configuring SNMP

[cols=2*,options="header"]
|===
|If you want to... |Use this command...

|Enable SNMP on the cluster
|options -option-name snmp.enable -option-value on
The SNMP service must be allowed under the management (mgmt) firewall policy. You can verify whether SNMP is allowed by using the system services firewall policy show command.
|Disable SNMP on the cluster
|options -option-name snmp.enable -option-value off
|===

== Commands for managing SNMP v1, v2c, and v3 users

[cols=2*,options="header"]
|===
|If you want to... |Use this command...

|Configure SNMP users
|security login create
|Display SNMP users
|security snmpusers and security login show -application snmp
|Delete SNMP users
|security login delete
|Modify the access-control role name of a login method for SNMP users
|security login modify
|===

== Commands for providing contact and location information

[cols=2*,options="header"]
|===
|If you want to... |Use this command...

|Display or modify the contact details of the cluster
|system snmp contact
|Display or modify the location details of the cluster
|system snmp location
|===

== Commands for managing SNMP communities

[cols=2*,options="header"]
|===
|If you want to... |Use this command...

|Add a read-only (ro) community for an SVM or for all SVMs in the cluster
|system snmp community add
|Delete a community or all communities
|system snmp community delete
|Display the list of all communities
|system snmp community show
|===

Because SVMs are not part of the SNMP standard, queries on data LIFs must include the NetApp root OID (1.3.6.1.4.1.789), for example, `snmpwalk -v 2c -c snmpNFS 10.238.19.14 1.3.6.1.4.1.789`.

== Command for displaying SNMP option values

[cols=2*,options="header"]
|===
|If you want to... |Use this command...

|Display the current values of all SNMP options, including cluster contact, contact location, whether the cluster is configured to send traps, the list of traphosts, and list of communities and access control type
|system snmp show
|===

== Commands for managing SNMP traps and traphosts

[cols=2*,options="header"]
|===
|If you want to... |Use this command...

|Enable SNMP traps sent from the cluster
|system snmp init -init 1
|Disable SNMP traps sent from the cluster
|system snmp init -init 0
|Add a traphost that receives SNMP notifications for specific events in the cluster
|system snmp traphost add
|Delete a traphost
|system snmp traphost delete
|Display the list of traphosts
|system snmp traphost show
|===

== Commands for managing events related to SNMP traps

[cols=2*,options="header"]
|===
|If you want to... |Use this command...

a|Display the events for which SNMP traps (built-in) are generated
a|event route show

Use the -snmp-support true parameter to view only SNMP-related events.

Use the instance -messagename <message> parameter to view a detailed description why an event might have occurred, and any corrective action.

Routing of individual SNMP trap events to specific traphost destinations is not supported. All SNMP trap events are sent to all traphost destinations.
a|Display a list of SNMP trap history records, which are event notifications that have been sent to SNMP traps
a|event snmphistory show
a|Delete an SNMP trap history record
a|event snmphistory delete
|===

For more information about the `system snmp`, `security`, and `event` commands, see the man pages: http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands^]
