---
sidebar: sidebar
permalink: networking/commands_for_managing_firewall_service_and_policies.html
keywords: manage, managing, firewall, fire, wall, service, policy, policies, commands for managing firewall service and policies, system services firewall, system services firewall policy, network interface modify, system services firewall modify, system services firewall show, system services firewall policy create, network interface modify -lif lifname -firewall-policy, system services firewall policy modify, system services firewall policy show, system services firewall policy clone, system services firewall policy delete
summary: Manage the firewall service
---

= ONTAP commands to manage firewall service and policies
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
You can use the `system services firewall` commands to manage firewall service, the `system services firewall policy` commands to manage firewall policies, and the `network interface modify` command to manage firewall settings for LIFs.

Beginning with ONTAP 9.10.1:

* Firewall policies are deprecated and are replaced by LIF service policies. Previously, the onboard firewall was managed using firewall policies. This functionality is now accomplished using a LIF service policy.
* All firewall policies are empty and do not open any ports in the underlying firewall. Instead, all ports must be opened using a LIF service policy.
* No action is required after an upgrade to 9.10.1 or later to transition from firewall policies to LIF service policies. The system automatically constructs LIF service policies consistent with the firewall policies in use in the previous ONTAP release. If you use scripts or other tools that create and manage custom firewall policies, you might need to upgrade those scripts to create custom service policies instead.

To learn more, see link:lifs_and_service_policies96.html[LIFs and service policies in ONTAP 9.6 and later].


|===

h| If you want to... h| Use this command...

a|Enable or disable firewall service
a|`system services firewall modify`

a|Display the current configuration for firewall service
a|`system services firewall show`

a|Create a firewall policy or add a service to an existing firewall policy
a|`system services firewall policy create`

a|Apply a firewall policy to a LIF
a|`network interface modify -lif lifname -firewall-policy`

a|Modify the IP addresses and netmasks associated with a firewall policy
a|`system services firewall policy modify`

a|Display information about firewall policies
a|`system services firewall policy show`

a|Create a new firewall policy that is an exact copy of an existing policy
a|`system services firewall policy clone`

a|Delete a firewall policy that is not used by a LIF
a|`system services firewall policy delete`
|===

.Related information
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+services+firewall[system services firewall^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html[network interface modify^]

// 2025 Apr 28, ONTAPDOC-2960
// 27-MAR-2025 ONTAPDOC-2909
// 2025 Jan 15, ONTAPDOC-2569
// 16 may 2024, ontapdoc-1986
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
