---
sidebar: sidebar
permalink: networking/commands_for_managing_firewall_service_and_policies.html
keywords: manage, managing, firewall, fire, wall, service, policy, policies, commands for managing firewall service and policies, system services firewall, system services firewall policy, network interface modify, system services firewall modify, system services firewall show, system services firewall policy create, network interface modify -lif lifname -firewall-policy, system services firewall policy modify, system services firewall policy show, system services firewall policy clone, system services firewall policy delete
summary: Manage the firewall service
---

= Commands for managing firewall service and policies
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
//

[.lead]
You can use the `system services firewall` commands to manage firewall service, the `system services firewall policy` commands to manage firewall policies, and the `network interface modify` command to manage firewall settings for LIFs.

[cols=2*,options="header"]
|===
|If you want to... |Use this command...

|Enable or disable firewall service
|system services firewall modify
|Display the current configuration for firewall service
|system services firewall show
|Create a firewall policy or add a service to an existing firewall policy
|system services firewall policy create
|Apply a firewall policy to a LIF
|network interface modify -lif lifname -firewall-policy
|Modify the IP addresses and netmasks associated with a firewall policy
|system services firewall policy modify
|Display information about firewall policies
|system services firewall policy show
|Create a new firewall policy that is an exact copy of an existing policy
|system services firewall policy clone
|Delete a firewall policy that is not used by a LIF
|system services firewall policy delete
|===

For more information, see the man pages for the `system services firewall`, `system services firewall policy`, and `network interface modify` commands in link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands^].
