---
sidebar: sidebar
permalink: networking/commands_for_managing_failover_groups_and_policies.html
keywords: manage, managing, failover, fail, over, group, policy, policies, groups, commands for managing failover groups and policies, network interface failover-groups, network interface modify, network interface failover-groups add-targets, network interface failover-groups remove-targets, network interface failover-groups modify, network interface modify -failover-group -failover-policy, network interface failover-groups show, rename, delete
summary: Manage failover groups
---

= Commands for managing failover groups and policies
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
//

[.lead]
You can use the `network interface failover-groups` commands to manage failover groups. You use the `network interface modify` command to manage the failover groups and failover policies that are applied to a LIF.

[cols=2*,options="header"]
|===
|If you want to... |Use this command...

|Add network ports to a failover group
|network interface failover-groups add-targets
|Remove network ports from a failover group
|network interface failover-groups remove-targets
|Modify network ports in a failover group
|network interface failover-groups modify
|Display the current failover groups
|network interface failover-groups show
|Configure failover on a LIF
|network interface modify -failover-group -failover-policy
|Display the failover group and failover policy that is being used by each LIF
|network interface show -fields failover-group, failover-policy
|Rename a failover group
|network interface failover-groups rename
|Delete a failover group
|network interface failover-groups delete
|===

[NOTE]
Modifying a failover group such that it does not provide a valid failover target for any LIF in the cluster can result in an outage when a LIF attempts to fail over.

For more information, see the man pages for the `network interface failover-groups` and `network interface modify` commands.
