---
sidebar: sidebar
permalink: networking/configure_dns_services_manual.html
keywords: dns, service, services, configuration, configure, configuring, set, up, setup, nfs, smb, cifs, active, directory, statistics, configure dns services, files, dns, hosts, , vserver services name-service dns create, configure dynamic dns on the svm, vserver-fqdn 
summary: Configure DNS services for the SVM before creating an NFS or SMB server
---

= Configure DNS services (ONTAP 9.7 and earlier)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
// 28-FEB-2024 add version to title

[.lead]
You must configure DNS services for the SVM before creating an NFS or SMB server. Generally, the DNS name servers are the Active Directory-integrated DNS servers for the domain that the NFS or SMB server will join.

.About this task

Active Directory-integrated DNS servers contain the service location records (SRV) for the domain LDAP and domain controller servers. If the SVM cannot find the Active Directory LDAP servers and domain controllers, NFS or SMB server setup fails.

SVMs use the hosts name services ns-switch database to determine which name services to use and in which order when looking up information about hosts. The two supported name services for the hosts database are `files` and `dns`.

You must ensure that `dns` is one of the sources before you create the SMB server.

NOTE: To view the statistics for DNS name services for the mgwd process and SecD process, use the Statistics UI.

.Steps

. Determine what the current configuration is for the `hosts` name services database.
+
In this example, the hosts name service database uses the default settings.
+
`vserver services name-service _ns-switch_ show -vserver _vs1_ -database _hosts_`
+
....
                     Vserver: vs1
Name Service Switch Database: hosts
   Name Service Source Order: files, dns
....

. Perform the following actions, if required.
.. Add the DNS name service to the hosts name service database in the desired order, or reorder the sources.
+
In this example, the hosts database is configured to use DNS and local files in that order.
+
`vserver services name-service _ns-switch_ modify -vserver _vs1_ -database _hosts_ -sources _dns,files_`

.. Verify that the name services configuration is correct.
+
`vserver services name-service _ns-switch_ show -vserver _vs1_ -database _hosts_`

. Configure DNS services.
+
`vserver services name-service dns create -vserver _vs1_ -domains _example.com,example2.com_ -name-servers _10.0.0.50,10.0.0.51_`
+
[NOTE]
The vserver services `name-service dns create` command performs an automatic configuration validation and reports an error message if ONTAP is unable to contact the name server.

. Verify that the DNS configuration is correct and that the service is enabled.
+
....
           Vserver: vs1
           Domains: example.com, example2.com Name
           Servers: 10.0.0.50, 10.0.0.51
Enable/Disable DNS: enabled Timeout (secs): 2
  Maximum Attempts: 1
....

. Validate the status of the name servers.
+
`vserver services name-service dns check -vserver _vs1_`
+
....
Vserver  Name Server  Status  Status Details
-------  -----------  ------  -----------------------
vs1      10.0.0.50    up      Response time (msec): 2
vs1      10.0.0.51    up      Response time (msec): 2
....

== Configure dynamic DNS on the SVM

If you want the Active Directory-integrated DNS server to dynamically register the DNS records of an NFS or SMB server in DNS, you must configure dynamic DNS (DDNS) on the SVM.

.Before you begin

DNS name services must be configured on the SVM. If you are using secure DDNS, you must use Active Directory-integrated DNS name servers and you must have created either an NFS or SMB server or an Active Directory account for the SVM.

.About this task

The specified fully qualified domain name (FQDN) must be unique:

* For NFS, the value specified in `-vserver-fqdn` as part of the `vserver services name-service dns dynamic-update` command becomes the registered FQDN for the LIFs.
* For SMB, the values specified as the CIFS server NetBIOS name and the CIFS server fully qualified domain name become the registered FQDN for the LIFs. This is not configurable in ONTAP. In the following scenario, the LIF FQDN is "CIFS_VS1.EXAMPLE.COM":
+
....
cluster1::> cifs server show -vserver vs1

                                          Vserver: vs1
                         CIFS Server NetBIOS Name: CIFS_VS1
                    NetBIOS Domain/Workgroup Name: EXAMPLE
                      Fully Qualified Domain Name: EXAMPLE.COM
                              Organizational Unit: CN=Computers
Default Site Used by LIFs Without Site Membership:
                                   Workgroup Name: -
                                   Kerberos Realm: -
                             Authentication Style: domain
                CIFS Server Administrative Status: up
                          CIFS Server Description:
                          List of NetBIOS Aliases: -
....

[NOTE]
To avoid a configuration failure of an SVM FQDN that is not compliant to RFC rules for DDNS updates, use an FQDN name that is RFC compliant. For more information, see link:https://tools.ietf.org/html/rfc1123[RFC 1123].

.Steps

. Configure DDNS on the SVM:
+
`vserver services name-service dns dynamic-update modify -vserver _vserver_name_ -is- enabled _true_ [-use-secure {true|false} -vserver-fqdn _FQDN_used_for_DNS_updates_`
+
`vserver services name-service dns dynamic-update modify -vserver _vs1_ -is-enabled _true_ - use-secure _true_ -vserver-fqdn _vs1.example.com_`
+
Asterisks cannot be used as part of the customized FQDN. For example, `{asterisk}.netapp.com` is not valid.

. Verify that the DDNS configuration is correct:
+
`vserver services name-service dns dynamic-update show`
+
....
Vserver  Is-Enabled Use-Secure Vserver FQDN      TTL
-------- ---------- ---------- ----------------- -------
vs1      true       true       vs1.example.com   24h
....


// 4 Feb 2022, BURT 1451789 