---
permalink: networking/configure-ports-uta-x1143a-r6.html
sidebar: sidebar
keywords: configure, ports
summary: "To configure the unified target adapter (X1143A-R6), you must configure the two adjacent ports on the same chip in the same personality mode."
---
= Configure UTA X1143A-R6 ports for your ONTAP system
:icons: font
:imagesdir: ../media/

[.lead]

By default the X1143A-R6 unified target adapter is configured in FC target mode, but you can configure its ports as either 10 Gb Ethernet and FCoE (CNA) ports or as 16 Gb FC initiator or target ports.  This requires different SFP+ adapters.

When configured for Ethernet and FCoE, X1143A-R6 adapters support concurrent NIC and FCoE target traffic on the same 10-GBE port. When configured for FC, each two-port pair that shares the same ASIC can be individually configured for FC target or FC initiator mode. This means that a single X1143A-R6 adapter can support FC target mode on one two-port pair and FC initiator mode on another two-port pair.  Port pairs connected to the same ASIC must be configured in the same mode.

In FC mode, the X1143A-R6 adapter behaves just like any existing FC device with speeds up to 16 Gbps. In CNA mode, you can use the X1143A-R6 adapter for concurrent NIC and FCoE traffic sharing the same 10 GbE port. CNA mode only supports FC target mode for the FCoE function.

To configure the unified target adapter (X1143A-R6), you must configure the two adjacent ports on the same chip in the same personality mode.

.Steps

. View the port configuration:
+
[source,cli]
----
system hardware unified-connect show
----
. Configure the ports as needed for Fibre Channel (FC) or Converged Network Adapter (CNA):
+
[source,cli]
----
system node hardware unified-connect modify -node <node_name> -adapter <adapter_name> -mode {fcp|cna}
----

. Attach the appropriate cables for FC or 10 Gb Ethernet.

. Verify that you have the correct SFP+ installed:
+
[source,cli]
----
network fcp adapter show -instance -node -adapter
----
+
For CNA, you should use a 10Gb Ethernet SFP. For FC, you should either use an 8 Gb SFP or a 16 Gb SFP, based on the FC fabric being connected to.
