---
sidebar: sidebar
permalink: networking/configure_network_ports_@cluster_administrators_only@_overview.html
keywords: introducing, introduction, overview, network, port, port type, type, physical, interface group, vlan, vip, virtual, naming, convention, configure network ports overview, introducing physical and virtual network ports
summary: Introducing physical and virtual network ports
---

= Configure network ports overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
// 28-FEB-2024 add context to overview title
//

[.lead]
Ports are either physical ports (NICs) or virtualized ports, such as interface groups or VLANs.

Virtual local area networks (VLANs) and interface groups constitute the virtual ports. Interface groups treat several physical ports as a single port, while VLANs subdivide a physical port into multiple separate logical ports.

* Physical ports: LIFs can be configured directly on physical ports.

* Interface group: A port aggregate containing two or more physical ports that act as a single trunk port. An interface group can be single-mode, multimode, or dynamic multimode.

* VLAN: A logical port that receives and sends VLAN-tagged (IEEE 802.1Q standard) traffic. VLAN port characteristics include the VLAN ID for the port. The underlying physical port or interface group ports are considered VLAN trunk ports, and the connected switch ports must be configured to trunk the VLAN IDs.
+
The underlying physical port or interface group ports for a VLAN port can continue to host LIFs, which transmit and receive untagged traffic.

* Virtual IP (VIP) port: A logical port that is used as the home port for a VIP LIF. VIP ports are created automatically by the system and support only a limited number of operations. VIP ports are supported beginning with ONTAP 9.5.

The port naming convention is _enumberletter_:

* The first character describes the port type.
"e" represents Ethernet.
* The second character indicates the numbered slot in which the port adapter is located.
* The third character indicates the port's position on a multiport adapter.
"a" indicates the first port, "b" indicates the second port, and so on.

For example, `e0b` indicates that an Ethernet port is the second port on the node's motherboard.

VLANs must be named by using the syntax `port_name-vlan-id`.

`port_name` specifies the physical port or interface group.

`vlan-id` specifies the VLAN identification on the network. For example, `e1c-80` is a valid VLAN name.

// 08 DEC 2021, BURT 1430515
