---
sidebar: sidebar
permalink: networking/configure_network_security_using_federal_information_processing_standards_fips.html
keywords: fips 140-2, compliant, ssl, connections, tlsv1.2, tlsv1.1, tlsv1, enable fips, disable fips, compliance status, SSL
summary:  Federal Information Processing Standards (FIPS) 140-2 compliant for all SSL connections
---
= Configure ONTAP network security using FIPS for all SSL connections
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
ONTAP is compliant in the Federal Information Processing Standards (FIPS) 140-2 for all SSL connections. You can turn on and off SSL FIPS mode, set SSL protocols globally, and turn off any weak ciphers such as RC4 within ONTAP.

By default, SSL on ONTAP is set with FIPS compliance disabled and with the following TLS protocols enabled:

* TLSv1.3 (beginning with ONTAP 9.11.1)
* TLSv1.2

Previous ONTAP releases had the following TLS protocols enabled by default:

* TLSv1.1 (disabled by default beginning with ONTAP 9.12.1)
* TLSv1 (disabled by default beginning with ONTAP 9.8)

When SSL FIPS mode is enabled, SSL communication from ONTAP to external client or server components outside of ONTAP will use FIPS compliant crypto for SSL.

If you want administrator accounts to access SVMs with an SSH public key, you must ensure that the host key algorithm is supported before enabling SSL FIPS mode.

*Note:* Host key algorithm support has changed in ONTAP 9.11.1 and later releases.

[cols="30,30,30"]
|===

h| ONTAP release h| Supported key types h| Unsupported key types

a| 9.11.1 and later
a| ecdsa-sha2-nistp256
a| rsa-sha2-512 +
rsa-sha2-256 +
ssh-ed25519 +
ssh-dss +
ssh-rsa

a| 9.10.1 and earlier
a| ecdsa-sha2-nistp256 +
ssh-ed25519
a| ssh-dss +
ssh-rsa

|===

Existing SSH public key accounts without the supported key algorithms must be reconfigured with a supported key type before enabling FIPS, or the administrator authentication will fail.

For more information, see link:../authentication/enable-ssh-public-key-accounts-task.html[Enable SSH public key accounts].

ONTAP 9.18.1 introduces support for postquantum computing cryptographic algorithms for SSL, providing an additional layer of security against potential future quantum computer attacks. These algorithms are only available when <<Disable FIPS,FIPS is disabled>>.

== Enable FIPS

It is recommended that all secure users adjust their security configuration immediately after system installation or upgrade. When SSL FIPS mode is enabled, SSL communication from ONTAP to external client or server components outside of ONTAP will use FIPS compliant crypto for SSL.

[NOTE]
When FIPS is enabled, you cannot install or create a certificate with an RSA key length of 4096.

.Steps

. Change to advanced privilege level:
+
`set -privilege advanced`

. Enable FIPS:
+
`security config modify -is-fips-enabled true`

. When prompted to continue, enter `y`
. Beginning with ONTAP 9.9.1, rebooting is not required. If you are running ONTAP 9.8 or earlier, manually reboot each node in the cluster one by one. 

.Example
If you are running ONTAP 9.9.1 or later, you will not see the warning message.
....
security config modify -is-fips-enabled true

Warning: This command will enable FIPS compliance and can potentially cause some non-compliant components to fail. MetroCluster and Vserver DR require FIPS to be enabled on both sites in order to be compatible.
Do you want to continue? {y|n}: y

Warning: When this command completes, reboot all nodes in the cluster. This is necessary to prevent components from failing due to an inconsistent security configuration state in the cluster. To avoid a service outage, reboot one node at a time and wait for it to completely initialize before rebooting the next node. Run "security config status show" command to monitor the reboot status.
Do you want to continue? {y|n}: y
....

Learn more about `security config modify` and SSL FIPS mode configuration in the link:https://docs.netapp.com/us-en/ontap-cli/security-config-modify.html[ONTAP command reference^].

== Disable FIPS

Beginning with ONTAP 9.18.1, SSL in ONTAP supports postquantum computing cryptographic algorithms. These algorithms are only available when FIPS is disabled. Postquantum computing algorithms are used automatically when FIPS is disabled and the client supports them.

.Steps

. Change to advanced privilege level:
+
`set -privilege advanced`

. Disable FIPS by typing:
+
`security config modify -is-fips-enabled false`

. When prompted to continue, enter `y`.

. Beginning with ONTAP 9.9.1, rebooting is not required. If you are running ONTAP 9.8 or earlier, manually reboot each node in the cluster.

If you need to use the SSLv3 protocol, you must disable FIPS with the above procedure. SSLv3 can only be enabled when FIPS is disabled.

You can enable SSLv3 with the following command. If you are running ONTAP 9.9.1 or later, you will not see the warning message.
....
security config modify -supported-protocols SSLv3

Warning: Enabling the SSLv3 protocol may reduce the security of the interface, and is not recommended.
Do you want to continue? {y|n}: y

Warning: When this command completes, reboot all nodes in the cluster. This is necessary to prevent components from failing due to an inconsistent security configuration state in the cluster. To avoid a service outage, reboot one node at a time and wait for it to completely initialize before rebooting the next node. Run "security config status show" command to monitor the reboot status.
Do you want to continue? {y|n}: y
....

== View FIPS compliance status

You can see whether the entire cluster is running the current security configuration settings.

.Steps

. One by one, reboot each node in the cluster.
+
Do not reboot all cluster nodes simultaneously. A reboot is required to make sure that all applications in the cluster are running the new security configuration, and for all changes to FIPS on/off mode, protocols, and ciphers.

. View the current compliance status:
+
`security config show`
+
.Example

....
security config show

          Cluster                                              Cluster Security
Interface FIPS Mode  Supported Protocols     Supported Ciphers Config Ready
--------- ---------- ----------------------- ----------------- ----------------
SSL       false      TLSv1_2, TLSv1_1, TLSv1 ALL:!LOW:!aNULL:  yes
                                             !EXP:!eNULL
....
+
Learn more about `security config show` in the link:https://docs.netapp.com/us-en/ontap-cli/security-config-show.html[ONTAP command reference^].

// 2025 Sep 26, ONTAPDOC-3240
// 2025 Aug 19, ONTAPDOC-1127
// 2025 June 05, ONTAPDOC-2960
// 27-MAR-2025 ONTAPDOC-2909
// 2-24-25 GH-1486
// 2025 Feb 14, ONTAPDOC-2758
// 2025 Jan 22, ONTAPDOC-1070
// 2022 june 14, BURT 1483070
// 2022 april 24, ontap-issue #516 (reverted 2022 august 26 issue #641)
// 2022 april 28, ontap-issue #475
// 2022 April 11, IE-511
// 2022 Apr 01, BURT 1448836
// 2022 Feb 04, BURT 1453350
// 2022 Jan 17, BURT 1448836
