---
sidebar: sidebar
permalink: networking/create_ipspaces_01.html
keywords: create, creation, creating, add, adding, ipspace, create ipspaces, ipspace create, broadcast-domain move
summary: IPspaces are distinct IP address spaces in which SVMs reside
---

= Create IPspaces
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
//

[.lead]
IPspaces are distinct IP address spaces in which storage virtual machines (SVMs) reside. You can create IPspaces when you need your SVMs to have their own secure storage, administration, and routing.

.About this task

There is a cluster-wide limit of 512 IPspaces. The cluster-wide limit is reduced to 256 IPspaces for clusters that contain nodes with 6 GB of RAM or less for some platforms. See the Hardware Universe to determine whether additional limits apply to your platform.

https://hwu.netapp.com/[NetApp Hardware Universe^]

[NOTE]
An IPspace name cannot be "all" because "all" is a system-reserved name.

.Step

Create an IPspace:

....
network ipspace create -ipspace ipspace_name
....

`ipspace_name` is the name of the IPspace that you want to create. The following command creates the IPspace ipspace1 on a cluster:

....
network ipspace create -ipspace ipspace1
....

.After you finish

If you create an IPspace in a cluster with a MetroCluster configuration, IPspace objects must be manually replicated to the partner clusters. Any SVMs that are created and assigned to an IPspace before the IPspace is replicated will not be replicated to the partner clusters.

Broadcast domains are created automatically in the "Default" IPspace and can be moved between IPspaces using the following command:

....
network port broadcast-domain move
....

For example, if you want to move a broadcast domain from "Default" to "ips1", using the following command:

....
network port broadcast-domain move -ipspace Default -broadcast-domain Default -to-ipspace ips1
....

// 2023-12-07, ONTAPDOC-1007