---
sidebar: sidebar
permalink: networking/create_a_broadcast_domain97.html
keywords: create, creation, creating, add, adding, broadcast, domain, create a broadcast domain, broadcast domains group network ports in the cluster that belong to the same layer 2 network
summary: Broadcast domains group network ports in the cluster that belong to the same layer 2 network
---

= Create a broadcast domain (ONTAP 9.7 and earlier)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
// 08 DEC 2021, BURT 1430515
// 16-FEB-2024 merge other create a broadcast domain topic


[.lead]
In ONTAP 9.7 and earlier, you create a broadcast domain to group network ports in the cluster that belong to the same layer 2 network. The ports can then be used by SVMs. You must create a broadcast domain for a custom IPspace. The SVMs created in the IPspace use the ports in the broadcast domain.

NOTE: This task is relevant for ONTAP 9.0 - 9.7, not ONTAP 9.8.

.Before you begin

You must be a cluster administrator to perform this task.

Beginning with ONTAP 9.8, broadcast domains are automatically created during the cluster create or join operation. If you are running ONTAP 9.8 or later, these steps are not needed.

In ONTAP 9.7 and earlier, the ports you plan to add to the broadcast domain must not belong to another broadcast domain.

.About this task

The port to which a LIF fails over must be a member of the failover group for the LIF. When you create a broadcast domain, ONTAP automatically creates a failover group with the same name. The failover group contains all the ports assigned to the broadcast domain.

* All broadcast domain names must be unique within an IPspace.
* The ports added to a broadcast domain can be physical network ports, VLANs, or interface groups (ifgrps).
* If the ports you want to use belong to another broadcast domain, but are unused, you use the `network port broadcast-domain remove-ports` command to remove the ports from the existing broadcast domain.
* The MTU of the ports added to a broadcast domain are updated to the MTU value set in the broadcast domain.
* The MTU value must match all of the devices connected to that layer 2 network except for the e0M port handling management traffic.
* If you do not specify an IPspace name, the broadcast domain is created in the "Default" IPspace.

To make system configuration easier, a failover group of the same name is created automatically that contains the same ports.

.Steps

. View the ports that are not currently assigned to a broadcast domain:
+
`network port show`
+
If the display is large, use the `network port show -broadcast-domain` command to view only unassigned ports.

. Create a broadcast domain:
+
`network port broadcast-domain create -broadcast-domain broadcast_domain_name -mtu mtu_value [-ipspace ipspace_name] [-ports ports_list]`
+
* `_broadcast_domain_name_` is the name of the broadcast domain you want to create.
* `_mtu_value_` is the MTU size for IP packets; 1500 and 9000 are typical values.
+
This value is applied to all ports that are added to this broadcast domain.
* `_ipspace_name_` is the name of the IPspace to which this broadcast domain will be added.
+
The "Default" IPspace is used unless you specify a value for this parameter.
* `_ports_list_` is the list of ports that will be added to the broadcast domain.
+
The ports are added in the format `_node_name:port_number_`, for example, `node1:e0c`.

. Verify that the broadcast domain was created as desired:
`network port show -instance -broadcast-domain _new_domain_`

.Example

The following command creates broadcast domain bcast1 in the Default IPspace, sets the MTU to 1500, and adds four ports:

`network port broadcast-domain create -broadcast-domain _bcast1_ -mtu _1500_ -ports _cluster1-01:e0e,cluster1-01:e0f,cluster1-02:e0e,cluster1-02:e0f_`

.After you finish

You can define the pool of IP addresses that will be available in the broadcast domain by creating a subnet, or you can assign SVMs and interfaces to the IPspace at this time. For more information, see link:https://docs.netapp.com/us-en/ontap-system-manager-classic/peering/index.html[Cluster and SVM peering^].

If you need to change the name of an existing broadcast domain, you use the `network port broadcast-domain rename` command.
