---
sidebar: sidebar
permalink: networking/create_a_dns_load_balancing_zone.html
keywords: create, creation, creating, add, adding, dns, naming, name, service, load, balancing, balance, zone, lif, create a dns load balancing zone, improve lif performance
summary: Create a DNS load balancing zone to improve LIF performance
---

= Create a DNS load balancing zone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
//

[.lead]
You can create a DNS load balancing zone to facilitate the dynamic selection of a LIF based on the load, that is, the number of clients mounted on a LIF. You can create a load balancing zone while creating a data LIF.

.Before you begin

The DNS forwarder on the site-wide DNS server must be configured to forward all requests for the load balancing zone to the configured LIFs.

The Knowledgebase article link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_set_up_DNS_load_balancing_in_clustered_Data_ONTAP[How to set up DNS load balancing in Cluster-Mode^] on the NetApp Support Site contains more information about configuring DNS load balancing using conditional forwarding.

.About this task

* Any data LIF can respond to DNS queries for a DNS load balancing zone name.
* A DNS load balancing zone must have a unique name in the cluster, and the zone name must meet the following requirements:
** It should not exceed 256 characters.
** It should include at least one period.
** The first and the last character should not be a period or any other special character.
** It cannot include any spaces between characters.
** Each label in the DNS name should not exceed 63 characters.
+
A label is the text appearing before or after the period. For example, the DNS zone named storage.company.com has three labels.

.Step

Use the `network interface create` command with the `dns-zone` option to create a DNS load balancing zone.

If the load balancing zone already exists, the LIF is added to it. For more information about the command, see http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands^].

The following example demonstrates how to create a DNS load balancing zone named storage.company.com while creating the LIF `lif1`:

....
network interface create -vserver vs0 -lif lif1 -home-node node1
-home-port e0c -address 192.0.2.129 -netmask 255.255.255.128 -dns-zone storage.company.com
....

// 2023 Apr 10, Git Issue 870