---
sidebar: sidebar
permalink: networking/create_lifs.html
keywords: create, creation, creating, add, adding, lifs, logical, interface, create lifs
summary: Create LIFs to serve SVM data to clients
---

= Create LIFs
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
//

[.lead]
An SVM serves data to clients through one or more network logical interfaces (LIFs). You must create LIFs on the ports you want to use to access data.

.Best practice

Switch ports connected to ONTAP should be configured as spanning-tree edge ports to reduce delays during LIF migration.

.Before you begin

You must be a cluster administrator to perform this task.

.About this task

Beginning with ONTAP 9.7, ONTAP automatically chooses the home port of a LIF, as long as at least one LIF already exists in the same subnet in that IPspace. ONTAP chooses a home-port in the same broadcast domain as other LIFs in that subnet. You can still specify a home port, but it is no longer required (unless no LIFs yet exist in that subnet in the specified IPspace).

You should not configure LIFs that carry SMB traffic to automatically revert to their home nodes. This recommendation is mandatory if the SMB server is to host a solution for nondisruptive operations with Hyper-V or SQL Server over SMB.

.Steps

. Determine which broadcast domain ports you want to use for the LIF.
+
`network port broadcast-domain show -ipspace _ipspace1_`
+
....
IPspace     Broadcast                       Update
Name        Domain name   MTU   Port List   Status Details
ipspace1
            default       1500
                                node1:e0d   complete
                                node1:e0e   complete
                                node2:e0d   complete
                                node2:e0e   complete
....

. Verify that the subnet you want to use for the LIFs contains sufficient unused IP addresses.
+
`network subnet show -ipspace _ipspace1_`

. Create one or more LIFs on the ports you want to use to access data.
+
`network interface create -vserver _vs1_ -lif _lif1_ -home-node _node1_ -home-port _e0d_ -service-policy _default-data-files_ -subnet-name _ipspace1_`

. Verify that the LIF interface configuration is correct.
+
`network interface show -vserver vs1`
+
....
          Logical    Status     Network         Current   Current Is
Vserver   Interface  Admin/Oper Address/Mask    Node      Port    Home
--------- ---------- ---------- --------------- --------- ------- ----
vs1
           lif1       up/up      10.0.0.128/24   node1     e0d     true
....

. Verify that the failover group configuration is as desired.
+
`network interface show -failover -vserver _vs1_`
+
....
         Logical    Home       Failover        Failover
Vserver  interface  Node:Port  Policy          Group
-------- ---------- ---------  ---------       --------
vs1
         lif1       node1:e0d  system-defined  ipspace1
Failover Targets: node1:e0d, node1:e0e, node2:e0d, node2:e0e
....

// 14 Sep 20232, ONTAPDOC-1343 
// 4 Feb 2022, BURT 1451789 
// 08 DEC 2021, BURT 1430515
