---
sidebar: sidebar
permalink: networking/create_a_subnet.html
keywords: move, moving, broadcast, domain, ipspace
summary: Create a subnet
---

= Create a subnet
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// restructured: March 2021
//

[.lead]
After you create the broadcast domain, you can create a subnet to allocate specific blocks of IPv4 or IPv6 addresses to be used later when you create LIFs for the SVM.

This enables you to create LIFs more easily by specifying a subnet name instead of having to specify IP address and network mask values for each LIF.

.Before you begin

You must be a cluster administrator to perform this task.

.Steps

. Create a subnet.
+
----
network subnet create -broadcast-domain ipspace1 -ipspace ipspace1 -subnet-name ipspace1 -subnet 10.0.0.0/24 -gateway 10.0.0.1 -ip-ranges "10.0.0.128-10.0.0.130,10.0.0.132"
----
+
The subnet name can be either a subnet IP value such as `192.0.2.0/24` or a string such as `ipspace1` like the one used in this example.

. Verify that the subnet configuration is correct.
+
The output from this example shows information about the subnet named ipspace1 in the ipspace1 IPspace. The subnet belongs to the broadcast domain name ipspace1. You can assign the IP addresses in this subnet to data LIFs for SVMs created in the ipspace1 IPspace.
+
`network subnet show -ipspace ipspace1`
