---
sidebar: sidebar
permalink: networking/determine_which_ports_can_be_used_for_a_broadcast_domains.html
keywords: move, moving, broadcast, domain, ipspace, determining which ports can be used for a broadcast domain, before you can configure a broadcast domain to add to the new ipspace, you must determine what ports are available for the broadcast domain
summary: Before you can configure a broadcast domain to add to the new IPspace, you must determine what ports are available for the broadcast domain
---

= Determining which ports can be used for a broadcast domain (ONTAP 9.7 and earlier)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// restructured: March 2021
// enhanced keywords May 2021
// 28-FEB-2024 add version to title


[.lead]
Before you can configure a broadcast domain to add to the new IPspace, you must determine what ports are available for the broadcast domain.

NOTE: This task is relevant for ONTAP 9.0 - 9.7, not ONTAP 9.8.

.Before you begin

You must be a cluster administrator to perform this task.

.About this task

* Ports can be physical ports, VLANs, or interface groups (ifgroups).
* The ports that you want to add to the new broadcast domain cannot be assigned to an existing broadcast domain.
* If the ports that you want to add to the broadcast domain are already in another broadcast domain (for example, the Default broadcast domain in the Default IPspace), you must remove the ports from that broadcast domain before assigning them to the new broadcast domain.
* Ports that have LIFs assigned to them cannot be removed from a broadcast domain.
* Because the cluster management and node management LIFs are assigned to the Default broadcast domain in the Default IPspace, the ports assigned to these LIFs cannot be removed from the Default broadcast domain.

.Steps

. Determine the current port assignments.
+
`network port show`
+
----
Node   Port IPspace  Broadcast Domain Link   MTU  Admin/Oper
------ ---- -------  ---------------- ----- ----  ------------
node1
       e0a  Cluster  Cluster          up    9000  auto/1000
       e0b  Cluster  Cluster          up    9000  auto/1000
       e0c  Default  Default          up    1500  auto/1000
       e0d  Default  Default          up    1500  auto/1000
       e0e  Default  Default          up    1500  auto/1000
       e0f  Default  Default          up    1500  auto/1000
       e0g  Default  Default          up    1500  auto/1000
node2
       e0a  Cluster  Cluster          up    9000  auto/1000
       e0b  Cluster  Cluster          up    9000  auto/1000
       e0c  Default  Default          up    1500  auto/1000
       e0d  Default  Default          up    1500  auto/1000
       e0e  Default  Default          up    1500  auto/1000
       e0f  Default  Default          up    1500  auto/1000
       e0g  Default  Default          up    1500  auto/1000
----
+
In this example, the output from the command provides the following information:
+
* Ports `e0c`, `e0d`, `e0e`, `e0f`, and `e0g` on each node are assigned to the Default broadcast domain.
* These ports are potentially available to use in the broadcast domain of the IPspace that you want to create.

. Determine which ports in the Default broadcast domain are assigned to LIF interfaces, and therefore cannot be moved to a new broadcast domain.
+
`network interface show`
+
----
         Logical      Status     Network         Current   Current Is
Vserver  Interface    Admin/Oper Address/Mask    Node      Port    Home
-------  ----------   ---------- ------------   --------- -------  ----
Cluster
         node1_clus1  up/up       10.0.2.40/24   node1     e0a     true
         node1_clus2  up/up       10.0.2.41/24   node1     e0b     true
         node2_clus1  up/up       10.0.2.42/24   node2     e0a     true
         node2_clus2  up/up       10.0.2.43/24   node2     e0b     true

cluster1
         cluster_mgmt up/up       10.0.1.41/24   node1     e0c     true
         node1_mgmt   up/up       10.0.1.42/24   node1     e0c     true
         node2_mgmt   up/up       10.0.1.43/24   node2     e0c     true
----
+
In the following example, the output from the command provides the following information:
+
* The node ports are assigned to port `e0c` on each node and the cluster administrative LIF's home node is on `e0c` on `node1`.
* Ports `e0d`, `e0e`, `e0f`, and `e0g` on each node are not hosting LIFs and can be removed from the Default broadcast domain and then added to a new broadcast domain for the new IPspace.
