---
sidebar: sidebar
permalink: networking/display_lifs_in_a_load_balancing_zone.html
keywords: display, view, show, lif, logical, interface, load, balancing, zone, balance, performance, display lifs in a load balancing zone, verify whether a load balancing zone is configured correctly by displaying all of the lifs that belong to it, examples of displaying load balancing zones for lifs
summary: Verify whether a load balancing zone is configured correctly by displaying all of the LIFs that belong to it
---

= Display LIFs in a load balancing zone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
//

[.lead]
You can verify whether a load balancing zone is configured correctly by displaying all of the LIFs that belong to it. You can also view the load balancing zone of a particular LIF, or the load balancing zones for all LIFs.

.Step

Display the LIFs and load balancing details that you want by using one of the following commands

[cols="30,70"]
|===

h|To display... h|Enter...

a|LIFs in a particular load balancing zone
a|`network interface show -dns-zone zone_name`

`zone_name` specifies the name of the load balancing zone.
a|The load balancing zone of a particular LIF
a|`network interface show -lif lif_name -fields dns-zone`
a|The load balancing zones of all LIFs
a|`network interface show -fields dns-zone`
|===

== Examples of displaying load balancing zones for LIFs

The following command displays the details of all LIFs in the load balancing zone storage.company.com for SVM vs0:

....
net int show -vserver vs0 -dns-zone storage.company.com

         Logical    Status     Network           Current   Current Is
Vserver  Interface  Admin/Oper Address/Mask      Node      Port    Home
-------- ---------- ---------- ----------------- --------- ------- ----
vs0
         lif3         up/up    10.98.226.225/20  ndeux-11  e0c     true
         lif4         up/up    10.98.224.23/20   ndeux-21  e0c     true
         lif5         up/up    10.98.239.65/20   ndeux-11  e0c     true
         lif6         up/up    10.98.239.66/20   ndeux-11  e0c     true
         lif7         up/up    10.98.239.63/20   ndeux-21  e0c     true
         lif8         up/up    10.98.239.64/20   ndeux-21  e0c     true
....

The following command displays the DNS zone details of the LIF data3:

....
network interface show -lif data3 -fields dns-zone
Vserver  lif    dns-zone
-------  -----  --------
vs0      data3  storage.company.com
....

The following command displays the list of all LIFs in the cluster and their corresponding DNS zones:

....
network interface show -fields dns-zone
Vserver   lif          dns-zone
-------   ------------ --------
cluster   cluster_mgmt none
ndeux-21  clus1        none
ndeux-21  clus2        none
ndeux-21  mgmt1        none
vs0       data1        storage.company.com
vs0       data2        storage.company.com
....
