---
sidebar: sidebar
permalink: networking/display_lif_information.html
keywords: display, view, show, lif, logical, interface, display lif information, view detailed information about a lif to determine its configuration
summary: View detailed information about a LIF to determine its configuration
---

= Display LIF information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
//

[.lead]
You can view detailed information about a LIF to determine its configuration.

You might also want to view this information to diagnose basic LIF problems, such as checking for duplicate IP addresses or verifying whether the network port belongs to the correct subnet. storage virtual machine (SVM) administrators can view only the information about the LIFs associated with the SVM.

.About this task

The following information is displayed:

* IP address associated with the LIF
* Administrative status of the LIF
* Operational status of the LIF
+
The operational status of data LIFs is determined by the status of the SVM with which the data LIFs are associated. When the SVM is stopped, the operational status of the LIF changes to down. When the SVM is started again, the operational status changes to up

* Node and the port on which the LIF resides

If data for a field is not available (for example, if there is no extended status information), the field value is listed as `-`.

.Step

Display LIF information by using the network interface show command.

You can view detailed information for each LIF by specifying the -instance parameter, or get specific information by specifying field names using the -fields parameter.

The following command displays general information about all LIFs in a cluster:

....
network interface show
           Logical    Status     Network          Current      Current Is
Vserver    Interface  Admin/Oper Address/Mask     Node         Port    Home
---------- ---------- ---------- ---------------- ------------ ------- ----
example
           lif1         up/up    192.0.2.129/22   node-01
                                                               e0d     false
node
           cluster_mgmt up/up    192.0.2.3/20     node-02
                                                               e0c     false
node-01
           clus1        up/up    192.0.2.65/18    node-01
                                                               e0a     true
           clus2        up/up    192.0.2.66/18    node-01
                                                               e0b     true
           mgmt1        up/up    192.0.2.1/20     node-01
                                                               e0c     true
node-02
           clus1        up/up    192.0.2.67/18    node-02
                                                               e0a     true
           clus2        up/up    192.0.2.68/18    node-02
                                                               e0b     true
           mgmt2        up/up    192.0.2.2/20     node-02
                                                               e0d     true
vs1
           d1           up/up    192.0.2.130/21   node-01
                                                               e0d     false
           d2           up/up    192.0.2.131/21   node-01
                                                               e0d     true
           data3        up/up    192.0.2.132/20   node-02
                                                               e0c     true
....

The following command shows detailed information about a single LIF:

....
network interface show -lif data1 -instance

                    Vserver Name: vs1
          Logical Interface Name: data1
                            Role: data
                   Data Protocol: nfs,cifs
                       Home Node: node-01
                       Home Port: e0c
                    Current Node: node-03
                    Current Port: e0c
              Operational Status: up
                 Extended Status: -
                         Is Home: false
                 Network Address: 192.0.2.128
                         Netmask: 255.255.192.0
             Bits in the Netmask: 18
                 IPv4 Link Local: -
                     Subnet Name: -
           Administrative Status: up
                 Failover Policy: local-only
                 Firewall Policy: data
                     Auto Revert: false
   Fully Qualified DNS Zone Name: xxx.example.com
         DNS Query Listen Enable: false
             Failover Group Name: Default
                        FCP WWPN: -
                  Address family: ipv4
                         Comment: -
                  IPspace of LIF: Default
....
