---
sidebar: sidebar
permalink: networking/index.html
keywords: ontap, 9, network, management, documentation, guide, ontap 9 network management documentation, welcome to the ontap 9 network management documentation portal
summary: Welcome to the ONTAP 9 Network Management documentation portal
---

= ONTAP 9 Network Management Documentation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// restructured: March 2021
// enhanced keywords May 2021
//

[.lead]
System Manager enables rich networking visualization and the ability to download consolidated data about your network. You can learn more in the following topics:

*	link:https://docs.netapp.com/us-en/ontap/concept_admin_viewing_managing_network.html[View and manage your network]
*	link:https://docs.netapp.com/us-en/ontap/concept_admin_downloading_data_report.html[Download network data for reporting]

You can also set up and manage your network with the ONTAP CLI. The ONTAP 9 CLI network management documentation consists of three main areas:

xref:set_up_nas_path_failover_98_and_later_cli.html[Set up NAS path failover for ONTAP 9.8 and later]

Learn how to set up NAS path failover using established best practices in ONTAP 9.8 and later

xref:set_up_nas_path_failover_9_to_97_cli.html[Set up NAS path failover for ONTAP 9.7 and earlier]

Learn how to set up NAS path failover using established best practices in ONTAP 9.7 and earlier.

xref:networking_reference.html[Networking reference]

The networking reference documentation describes how to configure and manage physical and virtual network ports (VLANs and interface groups), LIFs using IPv4 and IPv6, routing, and host-resolution services in clusters; optimize network traffic by load balancing; and monitor the cluster by using SNMP. Unless otherwise stated, this content applies to all versions of ONTAP 9.
