---
sidebar: sidebar
permalink: networking/manage_the_hosts_table_@cluster_administrators_only@.html
keywords: manage, managing, snmp, monitor, monitoring, troubleshooting, error detection, traps, hosts, host, table, add, modify, change, create, delete, remove, view, show, display, manage the hosts table (cluster administrators only, manage the host name entries in the hosts table of the admin svm, commands for managing local host-name entries, vserver services name-service dns hosts
summary: Manage the host name entries in the hosts table of the admin SVM
---

= Manage the hosts table (cluster administrators only)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
//

[.lead]
A cluster administrator can add, modify, delete, and view the host name entries in the hosts table of the admin storage virtual machine (SVM). An SVM administrator can configure the host name entries only for the assigned SVM.

== Commands for managing local host-name entries

You can use the `vserver services name-service dns hosts` command to create, modify, or delete DNS host table entries.

When you are creating or modifying the DNS host-name entries, you can specify multiple alias addresses separated by commas.

[cols="30,70"]
|===

h| If you want to... h| Use this command...

a|Create a DNS host-name entry
a|`vserver services name-service dns hosts create`
a|Modify a DNS host-name entry
a|`vserver services name-service dns hosts modify`
a|Delete a DNS host-name entry
a|`vserver services name-service dns hosts delete`
|===

For more information, see the http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands^] for the `vserver services name-service dns hosts` commands.
