---
sidebar: sidebar
permalink: networking/manage_routing_in_an_svm_overview.html
keywords: introducing, introduction, overview, route, routing, svm, storage, virtual, machine, network, path, overview, introducing routing tables and network paths
summary: Introducing routing tables and network paths
---

= SVM routing overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
// 28-FEB-2024 describe title

[.lead]
The routing table for an SVM determines the network path the SVM uses to communicate with a destination. It’s important to understand how routing tables work so that you can prevent network problems before they occur.

Routing rules are as follows:

* ONTAP routes traffic over the most specific available route.
* ONTAP routes traffic over a default gateway route (having 0 bits of netmask) as a last resort, when more specific routes are not available.

In the case of routes with the same destination, netmask, and metric, there is no guarantee that the system will use the same route after a reboot or after an upgrade. This is especially an issue if you have configured multiple default routes.

It is a best practice to configure one default route only for an SVM. To avoid disruption, you should ensure that the default route is able to reach any network address that is not reachable by a more specific route. For more information, see the Knowledgebase article https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU134[SU134: Network access might be disrupted by incorrect routing configuration in clustered ONTAP^]
