---
sidebar: sidebar
permalink: networking/merge_broadcast_domains.html
keywords: merge, combine, broadcast, domain, reachability, merge broadcast domains, merge the ports from one broadcast domain into an existing broadcast domain
summary: Merge the ports from one broadcast domain into an existing broadcast domain
---

= Merge ONTAP broadcast domains
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
If network port reachability has changed, either through physical network connectivity or switch configuration, and two group of network ports previously configured in multiple broadcast domains now all share reachability, then merging two broadcast domains can be used to synchronize the ONTAP configuration with the physical network topology.

[NOTE]
The procedure for merging broadcast domains is different in ONTAP 9.7 and earlier versions. If you need to merge broadcast domains on a network running ONTAP 9.7 and earlier, refer to link:https://docs.netapp.com/us-en/ontap-system-manager-classic/networking-bd/merge_broadcast_domains97.html[Merge broadcast domains (ONTAP 9.7 or earlier)^].

To determine if multiple broadcast domains belong to one reachability set, use the "network port reachability show -details" command and pay attention to which ports that are configured in another broadcast domain actually have connectivity to one another ("Unexpected ports"). Typically, the list of unexpected ports defines the set of ports that should be merged into the broadcast domain after you have verified that the physical and switch configuration is accurate.

.Step

Merge the ports from one broadcast domain into an existing broadcast domain:

....
network port broadcast-domain merge -ipspace <ipspace_name> -broadcast-domain <broadcast_domain_name> -into-broadcast-domain <broadcast_domain_name>
....

* `ipspace_name` is the name of the ipspace where the broadcast domains reside.
* `-broadcast-domain` is the name of the broadcast domain that will be merged.
* `-into-broadcast-domain` is the name of the broadcast domain that will receive additional ports.

.Related information
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-broadcast-domain merge[network port broadcast-domain merge^]

// 26-MAR-2025 ONTAPDOC-2882
// 28-FEB-2024 add version to title
// enhanced keywords May 2021
// restructured: March 2021
// Created with NDAC Version 2.0 (August 17, 2020)
