---
sidebar: sidebar
permalink: networking/modify_network_port_attributes.html
keywords: change, changing, modify, modifying, network, port, attributes, modify network port attributes, change the autonegotiation, duplex, flow control, speed, and health settings of a physical network port
summary: Change the autonegotiation, duplex, flow control, speed, and health settings of a physical network port
---

= Modify network port attributes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can modify the autonegotiation, duplex, flow control, speed, and health settings of a physical network port.

.Before you begin

The port that you want to modify must not be hosting any LIFs.

.About this task

* It is not recommended to modify the administrative settings of the 100 GbE, 40 GbE, 10 GbE or 1 GbE network interfaces.
+
The values that you set for duplex mode and port speed are referred to as administrative settings. Depending on network limitations, the administrative settings can differ from the operational settings (that is, the duplex mode and speed that the port actually uses).

* It is not recommended to modify the administrative settings of the underlying physical ports in an interface group.
+
The `-up-admin` parameter (available at the advanced privilege level) modifies the administrative settings of the port.

* It is not recommended to set the `-up-admin` administrative setting to false for all ports on a node, or for the port that hosts the last operational cluster LIF on a node.
* It is not recommended to modify the MTU size of the management port, `e0M`.
* The MTU size of a port in a broadcast domain cannot be changed from the MTU value that is set for the broadcast domain.
* The MTU size of a VLAN cannot exceed the value of the MTU size of its base port.

.Steps

. Modify the attributes of a network port:
+
`network port modify`

. You can set the `-ignore-health-status` field to true for specifying that the system can ignore the network port health status of a specified port.
+
The network port health status is automatically changed from degraded to healthy, and this port can now be used for hosting LIFs. You should set the flow control of cluster ports to `none`. By default, the flow control is set to `full`.

The following command disables the flow control on port e0b by setting the flow control to none:

....
network port modify -node cluster-1-01 -port e0b -flowcontrol-admin none
....

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
// update for GH 400 April 2022
//
