---
sidebar: networking-reference_sidebar
permalink: networking/networking_reference.html
summary: Welcome to the ONTAP 9 Networking Reference Documentation Portal
---

= ONTAP 9 Networking Reference
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// restructured: March 2021
//

[.lead]
This networking reference documentation describes how to configure and manage physical and virtual network ports (VLANs and interface groups), LIFs using IPv4 and IPv6, routing, and host-resolution services in clusters; optimize network traffic by load balancing; and monitor the cluster by using SNMP.

Unless otherwise stated, this content applies to all versions of ONTAP 9.

This content describes basic storage network administration. It shows you how to configure physical and virtual network ports (VLANs and interface groups), how to create LIFs using IPv4 and IPv6, how to manage routing and host-resolution services in clusters, how to use load balancing to optimize network traffic, and how to monitor a cluster using SNMP.

You should use this content under the following circumstances:

* You want to understand the range of ONTAP network management capabilities.
* You want to use the CLI, not ONTAP System Manager.
* You are configuring networking on a new or upgraded system running ONTAP 9.

If you want to follow NAS path failover best practices and are running an ONTAP 9.8 or later release, you should use the following documentation:

* link:https://docs.netapp.com/us-en/ontap/networking-auto-config/index.html[ONTAP 9.8 and later NAS Path Failover Workflow^]

If you want to follow NAS path failover best practices and are running an ONTAP 9.0 - 9.7 release, you should use the following documentation:

* link:https://docs.netapp.com/us-en/ontap/networking-manual-config/index.html[ONTAP 9.0 - 9.7 NAS Path Failover Workflow^]

If you want to use ONTAP System Manager to configure the network for ONTAP 9.7 and later, you should choose the following documentation:

*	link:https://docs.netapp.com/us-en/ontap/[ONTAP System Manager docs^]

If you want to use OnCommand System Manager to configure the network for ONTAP 9.7 and earlier, you should choose the following documentation:

* https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help/GUID-DF04A607-30B0-4B98-99C8-CB065C64E670.html[Cluster management using System Manager^]

If you require additional configuration or conceptual information, you should choose among the following documentation:

* Conceptual background for network configuration
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html[ONTAP concepts^]
* NAS file access
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-nfs/home.html[NFS management^]
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html[SMB/CIFS management^]
* SAN host provisioning
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html[SAN administration^]
* Command reference
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands^]
* Technical Reports (TRs), which include additional information about ONTAP technology and interaction with external services
** http://www.netapp.com/us/media/tr-4182.pdf[NetApp Technical Report 4182: Ethernet Storage Design Considerations and Best Practices for Clustered Data ONTAP Configurations^]
