---
sidebar: sidebar
permalink: networking/recover_from_an_incorrectly_configured_cluster_lif.html
keywords: misconfigured, misconfigurations, incorrect, incorrectly, switch, switches, switched, cable, physical, wiring, wired, reachability, port, cluster, ontap 9.8 and later, recover from an incorrectly configured cluster lif, how to identify and correct a cluster that has been misconfigured, cluster create, network port, reachability show -detail, reset the home port
summary: How to identify and correct a cluster that has been misconfigured
---

= Recover an incorrectly configured ONTAP LIF
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
A cluster cannot be created when the cluster network is cabled to a switch but not all of the ports configured in the Cluster IPspace can reach the other ports configured in the Cluster IPspace.

.About this task

In a switched cluster, if a cluster network interface (LIF) is configured on the wrong port, or if a cluster port is wired into the wrong network, the `cluster create` command can fail with the following error:

....
Not all local cluster ports have reachability to one another.
Use the "network port reachability show -detail" command for more details.
....

Learn more about `cluster create` in the link:https://docs.netapp.com/us-en/ontap-cli/cluster-create.html[ONTAP command reference^].

The results of the `network port show` command might show that several ports are added to the Cluster IPspace because they are connected to a port that is configured with a cluster LIF. However, the results of the `network port` `reachability show -detail` command reveal which ports do not have connectivity to one another.

Learn more about `network port show` in the link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html[ONTAP command reference^].

To recover from a cluster LIF configured on a port that is not reachable to the other ports configured with cluster LIFs, perform the following steps:

.Steps

. Reset the home port of the cluster LIF to the correct port:
+
....
network port modify -home-port
....
Learn more about `network port modify` in the link:https://docs.netapp.com/us-en/ontap-cli/network-port-modify.html[ONTAP command reference^].
. Remove the ports that do not have cluster LIFs configured on them from the cluster broadcast domain:
+
....
network port broadcast-domain remove-ports
....
+
Learn more about `network port broadcast-domain remove-ports` in the link:https://docs.netapp.com/us-en/ontap-cli/network-port-broadcast-domain-remove-ports.html[ONTAP command reference^].

. Create the cluster:
+
....
cluster create
....

.Result

When you complete the cluster creation, the system detects the correct configuration and places the ports into the correct broadcast domains.

// 2025 May 21, ONTAPDOC-2960
// 27-MAR-2025 ONTAPDOC-2909
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021