---
sidebar: sidebar
permalink: networking/removing_a_nic_from_the_node.html
keywords: delete, deleting, remove, removing, nic, network, interface, card, slot, maintenance, faulty, error, bad, failed, fail, node, remove a faulty NIC from its slot or move the NIC to another slot for maintenance purposes, removing a nic from the node on ontap 9.8 or later, controller-replacement, network displaced-vlans, displaced-vlans show, displaced-vlans restore,
summary: ONTAP 9.8 and later, remove a faulty NIC from its slot or move the NIC to another slot for maintenance purposes
---

= Removing a NIC from the node (ONTAP 9.8 and later)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
// 29-FEB-2024 make titles consistent

[.lead]
This topic applies to ONTAP 9.8 and later. You might have to remove a faulty NIC from its slot or move the NIC to another slot for maintenance purposes.

.Steps

. Power down the node.
. Physically remove the NIC from its slot.
. Power on the node.
. Verify that the port has been deleted:
+
....
network port show
....
+
[NOTE]
ONTAP automatically removes the port from any interface groups. If the port was the only member of an interface group, the interface group is deleted.

. If the port had any VLANs configured on it, they are displaced. You can view displaced VLANs using the following command:
+
....
cluster controller-replacement network displaced-vlans show
....
+
[NOTE]
The `displaced-interface show`, `displaced-vlans show`, and `displaced-vlans restore` commands are unique and do not require the fully qualified command name, which starts with `cluster controller-replacement network`.

. These VLANs are deleted, but can be restored using the following command:
+
....
displaced-vlans restore
....

. If the port had any LIFs configured on it, ONTAP automatically chooses new home ports for those LIFs on another port in the same broadcast domain. If no suitable home port is found on the same filer, those LIFs are considered displaced. You can view displaced LIFs using the following command:
+
`displaced-interface show`

. When a new port is added to the broadcast domain on the same node, the home ports for the LIFs are automatically restored. Alternatively, you can either set the home port using `network interface modify -home-port -home-node or use the displaced- interface restore` command.
