---
sidebar: sidebar
permalink: networking/set_up_nas_path_failover_98_and_later_cli.html
keywords: learn about NAS failover on the ONTAP network, setup nas path failover, nas path failover, nas path failover workflow
summary: Welcome to the ONTAP 9.8+ NAS path failover workflow
---
= Learn about NAS failover on the ONTAP network
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This workflow guides you through the networking configuration steps to set up NAS path failover. This workflow assumes the following:

* You want to use NAS path failover best practices in a workflow that simplifies network configuration.
* You want to use the CLI, not System Manager.

[NOTE]
The information for NAS failover on the ONTAP network is different in ONTAP 9.7 and earlier versions. If you need to configure NAS failover on a network running ONTAP 9.7 and earlier, refer to link:https://docs.netapp.com/us-en/ontap-system-manager-classic/networking-failover/set_up_nas_path_failover_9_to_97_cli.html[Set up NAS path failover (ONTAP 9.7 and earlier)^].

If you want network management details, you should use the network management reference material:

* xref:networking_reference.adoc[Network management overview]

// 26-MAR-2025 ONTAPDOC-2882
// 29-FEB-2024 make titles consistent
// enhanced keywords May 2021
// restructured: March 2021
