---
sidebar: sidebar
permalink: networking/set_up_nas_path_failover_9_to_97_cli.html
keywords: set up nas path failover (ontap 9.0 - 9.7 cli), setup nas path failover, nas path failover, nas path failover workflow
summary: Welcome to the ONTAP 9.0 - 9.7 NAS path failover workflow
---

= Set up NAS path failover (ONTAP 9.7 and earlier)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This workflow guides you through the networking configuration steps to set up NAS path failover for ONTAP 9.0 - 9.7. This workflow assumes the following:

* You want to use NAS path failover best practices that simplify network configuration.
* You want to use the CLI, not System Manager.
* You are configuring networking on a new system running ONTAP 9.0 to 9.7.

If you are running an ONTAP release later than 9.7, you should use the NAS path failover procedure for ONTAP 9.8 or later:

* xref:set_up_nas_path_failover_98_and_later_cli.adoc[ONTAP 9.8 and later NAS path failover workflow]

If you want details about network components and management, you should use the network management reference material:

* xref:networking_reference.adoc[Network management overview]


// restructured: March 2021
// enhanced keywords May 2021
// 29-FEB-2024 make titles consistent