---
sidebar: sidebar
permalink: networking/split_broadcast_domains97.html
keywords: split, broadcast, domain, separate, splitting, separating, reachability, port, split a broadcast domain to synchronize the ontap configuration with the physical network topology, unreachable ports, broadcast-domain split, split broadcast domains
summary:  Split a broadcast domain to synchronize the ONTAP 9.0 to 9.7 configuration with the physical network topology
---

= Split broadcast domains (ONTAP 9.7 or earlier)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
// 28-FEB-2024 add version to title
//

[.lead]
You can modify an existing broadcast domain by splitting it into two different broadcast domains, with each broadcast domain containing some of the original ports assigned to the original broadcast domain.

.About this task

* If the ports are in a failover group, all of the ports in a failover group must be split.
* If the ports have LIFs associated with them, the LIFs cannot be part of a subnet's ranges.

.Step

Split a broadcast domain into two broadcast domains:

....
network port broadcast-domain split -ipspace <ipspace_name> -broadcast-domain <broadcast_domain_name> -new-broadcast-domain <broadcast_domain_name> -ports <node:port,node:port>
....

* `ipspace_name` is the name of the IPspace where the broadcast domain resides.
* `-broadcast-domain` is the name of the broadcast domain that will be split.
* `-new-broadcast-domain` is the name of the new broadcast domain that will be created.
* `-ports` is the node name and port to be added to the new broadcast domain.
