---
sidebar: sidebar
permalink: networking/split_broadcast_domains.html
keywords: split, broadcast, domain, separate, splitting, separating, reachability, port, split a broadcast domain to synchronize the ontap configuration with the physical network topology, unreachable ports, broadcast-domain split, split broadcast domains
summary:  Split a broadcast domain to synchronize the ONTAP 9.8 and later configuration with the physical network topology
---

= Split broadcast domains (ONTAP 9.8 or later)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
// 28-FEB-2024 add version to title


[.lead]
If network port reachability has changed, either through physical network connectivity or switch configuration, and a group of network ports previously configured in a single broadcast domain has become partitioned into two different reachability sets, you can split a broadcast domain to synchronize the ONTAP configuration with the physical network topology.

To determine if a network port broadcast domain is partitioned into more than one reachability set, use the `network port reachability show -details` command and pay attention to which ports do not have connectivity to one another ("Unreachable ports"). Typically,  the list of unreachable ports defines the set of ports that should be split into another broadcast domain, after you have verified that the physical and switch configuration is accurate.

.Step

Split a broadcast domain into two broadcast domains:

....
network port broadcast-domain split -ipspace <ipspace_name> -broadcast-domain <broadcast_domain_name> -new-broadcast-domain <broadcast_domain_name> -ports <node:port,node:port>
....

* `ipspace_name` is the name of the ipspace where the broadcast domain resides.
* -`broadcast-domain` is the name of the broadcast domain that will be split.
* -`new-broadcast-domain` is the name of the new broadcast domain that will be created.
* -`ports` is the node name and port to be added to the new broadcast domain.
