---
sidebar: sidebar
permalink: networking/view_network_information_overview.html
keywords: overview, introduction, introducing, view, show, display, network, information, ports, LIFs, routes, failover rules, failover groups, firewall rules, DNS, NIS, connections, view network information overview, network information
summary: View information related to ports, LIFs, routes, failover rules, failover groups, firewall rules, DNS, NIS, and connections
---

= View network information overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
Using the CLI, you can view information related to ports, LIFs, routes, failover rules, failover groups, firewall rules, DNS, NIS, and connections. Beginning with ONTAP 9.8, you can also download the data that is displayed in System Manager about your network.

This information can be useful in situations such as reconfiguring networking settings, or when troubleshooting the cluster.

If you are a cluster administrator, you can view all the available networking information. If you are an SVM administrator, you can view only the information related to your assigned SVMs.

In System Manager, when you display information in a _List View_, you can click *Download*, and the list of objects displayed is downloaded.

 * The list is downloaded in comma-separated values (CSV) format.

 * Only the data in the visible columns is downloaded.

 * The CSV filename is formatted with the object name and a time stamp.


// Merge SM topic concept_admin_downloading_data_report 15-FEB-2024
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021