---
sidebar: sidebar
permalink: networking/what_dns_load_balancing_is.html
keywords: dns, load, balance, balancing, performance, svm, what dns load balancing is, dns load balancing, load balancing supports nfsv3, nfsv4, nfsv4.1, cifs, smb 2.0, smb 2.1, smb 3.0
summary: Associate LIFs with the load balancing zone of an SVM
---

= What DNS load balancing is
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// Created with NDAC Version 2.0 (August 17, 2020)
// restructured: March 2021
// enhanced keywords May 2021
//

[.lead]
DNS load balancing helps in selecting an appropriately loaded data LIF and balancing user network traffic across all available ports (physical, interface groups, and VLANs).

With DNS load balancing, LIFs are associated with the load balancing zone of an SVM. A site-wide DNS server is configured to forward all DNS requests and return the least-loaded LIF based on the network traffic and the availability of the port resources (CPU usage, throughput, open connections, and so on). DNS load balancing provides the following benefits:

* New client connections balanced across available resources.
* No manual intervention required for deciding which LIFs to use when mounting a particular SVM.
* DNS load balancing supports NFSv3, NFSv4, NFSv4.1, CIFS, SMB 2.0, SMB 2.1, and SMB 3.0.
