---
settings:
  name: Training
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Overview
      url: /flexcache-hotspot-remediation-overview.html
    - title: HDFA examples
      url: /flexcache-hotspot-remediation-hdfa-examples.html
    - title: Inter or intra-SVM HDFAs
      url: /flexcache-hotspot-remediation-intra-inter-svm-hdfa.html
    - title: ONTAP configuration
      url: /flexcache-hotspot-remediation-ontap-config.html
    - title: Client configuration
      url: /flexcache-hotspot-remediation-client-config.html
    - title: Legal notices
      url: /legal-notices.html
