---
sidebar: networking-auto-config_sidebar
permalink: networking-auto-config/decide_whether_to_use_this_network_management_guide.html
keywords: ONTAP 9.8 and later, CLI, decide, deciding, find, finding
summary: Find the right network management guide
---

= Decide whether to use this network management guide
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// restructured: March 2021
//

[.lead]
This guide describes the NAS path failover workflow for ONTAP 9.8 and later releases.

You should use this guide under the following circumstances:

* You want to use NAS path failover best practices in a workflow that simplifies network configuration.
* You want to use the CLI, not ONTAP System Manager.
* You are configuring networking on a new system running ONTAP 9.8 or later.

If you are running an ONTAP release earlier than 9.8, you should use the following NAS path failover documentation:

* link:https://docs.netapp.com/us-en/ontap/networking-manual-config/index.html[ONTAP 9.0 - 9.7 NAS Path Failover Workflow^]

If you want network management details, you should use the following ONTAP 9 Network Management Reference:

* link:https://docs.netapp.com/us-en/ontap/networking-reference/index.html[ONTAP 9 Network Management Reference^]

If you want to use ONTAP System Manager to configure the network for ONTAP 9.7 and later, you should choose the following documentation:

*	link:https://docs.netapp.com/us-en/ontap/[ONTAP System Manager docs^]

If you want to use OnCommand System Manager to configure the network for ONTAP 9.7 and earlier, you should choose the following documentation:

* https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help/GUID-DF04A607-30B0-4B98-99C8-CB065C64E670.html[Cluster management using System Manager^]

If you require additional configuration or conceptual information, you should choose among the following documentation:

* Conceptual background for network configuration
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html[ONTAP concepts^]
* NAS file access
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-nfs/home.html[NFS management^]
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html[SMB/CIFS management^]
* SAN host provisioning
** https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html[SAN administration^]
* Command reference
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands^]
* Technical Reports (TRs), which include additional information about ONTAP technology and interaction with external services
** http://www.netapp.com/us/media/tr-4182.pdf[NetApp Technical Report 4182: Ethernet Storage Design Considerations and Best Practices for Clustered Data ONTAP Configurations^]
