---
permalink: concepts/builtin-storage-efficiency-concept.html
sidebar: sidebar
keywords: storage efficiency, built-in, platform, controller, offload, aff a1k, aff a90, aff a70, fas90, fas70, aff a50, aff a30
summary: "Dedicated offload processor storage efficiency is enabled by default on certain AFF and FAS platforms.  These platforms do not use temperature-sensitive storage efficiency.  Compression begins without waiting for data to become cold and is performed using a dedicated offload processor."
---
= Learn about ONTAP dedicated offload processor storage efficiency
:icons: font
:imagesdir: ../media/

[.lead]
Dedicated offload processor storage efficiency performs sequential packing of contiguous physical blocks and uses a dedicated offload processor for 32k data compression.  With 32k compression, space savings is realized at the aggregate level, unlike platforms using 8k adaptive compression, where space savings is realized at the volume level. Platforms that use dedicated offload processor storage efficiency do not use temperature-sensitive storage efficiency (TSSE), meaning compression is not based on hot or cold data. This results in immediate space savings without any performance impact.

Dedicated offload processor storage efficiency is enabled by default on the following platforms and ONTAP versions.

[NOTE]
Data that’s migrated using SnapMirror technology is converted automatically to 32k inline compression on AFF A20 platforms.  However the AFF A20 platform does not support dedicated offload processor storage efficiency. The AFF A20 uses the main CPU for compression.

include::_include/dedicated-offload-processor-supported-platforms.adoc[]

For the following platforms, storage efficiency is enabled automatically and requires no configuration. This applies to all newly created thin-provisioned volumes and existing data, including volumes moved from other platforms.  Deduplication is enabled regardless of the space guarantee setting. Compression and data compaction both require that the space guarantee be set to none. Data that’s migrated using volume move or SnapMirror technology is converted automatically to 32k inline compression.

* AFF A1K
* AFF A90
* AFF A70
* AFF A50
* AFF A30

For the following platforms, storage efficiency is enabled by default only on existing thin-provisioned volumes that had storage efficiency enabled before upgrading to ONTAP 9.15.1 or later. You can enable storage efficiency on newly created volumes using the CLI or REST API method. Data that is migrated using volume move or SnapMirror technology is converted to 32k inline compression only if compression was enabled on the original platform.

* FAS90
* FAS70

For information about upgrading a controller to one of the supported platforms, see the https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html[ONTAP Hardware Upgrade Documentation^].

// 2025 Sept 26, Git Issue 1843
// 2025 Sept 11, ONTAPDOC-3173
// 2025 April 01, GitHub issue 1691
// 2024-Oct-9, ONTAPDOC-2488
// 2024-June-21, IDR-370
// 2024-June-10, ONTAPDOC-1757 and ONTAPDOC-1851
