---
permalink: concepts/fabricpool-concept.html
sidebar: sidebar
keywords: storagegrid, storage grid, fabricpool
summary: "Many NetApp customers have significant amounts of stored data that is rarely accessed. We call that cold data. Customers also have data that is frequently accessed, which we call hot data. Ideally, you want to keep your hot data on your fastest storage for best performance. Cold data can move to slower storage as long as it is immediately available if needed. But how do you know which parts of your data are hot and which are cold?"
---
= FabricPool
:icons: font
:imagesdir: ../media/

[.lead]
Many NetApp customers have significant amounts of stored data that is rarely accessed. We call that _cold_ data. Customers also have data that is frequently accessed, which we call _hot_ data. Ideally, you want to keep your hot data on your fastest storage for best performance. Cold data can move to slower storage as long as it is immediately available if needed. But how do you know which parts of your data are hot and which are cold?

FabricPool is an ONTAP feature that automatically moves data between a high-performance local tier (aggregate) and a cloud tier based on access patterns. Tiering frees up expensive local storage for hot data while keeping cold data readily available from low-cost object storage in the cloud. FabricPool constantly monitors data access and moves data between tiers for best performance and maximum savings.

Using FabricPool to tier cold data to the cloud is one of the easiest ways to gain cloud efficiency and create a hybrid cloud configuration. FabricPool works at the storage block level, so it works with both file and LUN data.

But FabricPool is not just for tiering on-premises data to the cloud. Many customers use FabricPool in Cloud Volumes ONTAP to tier cold data from more-expensive cloud storage to lower-cost object storage within the cloud provider. Beginning with ONTAP 9.8, you can capture analytics on FabricPool-enabled volumes with link:../concept_nas_file_system_analytics_overview.html[File System Analytics] or link:../volumes/enable-temperature-sensitive-efficiency-concept.html[temperature-sensitive storage efficiency].

The applications using the data are not aware that data is tiered, so no changes to your applications are needed. Tiering is fully automatic, so there is no ongoing administration needed.

You can store cold data in object storage from one of the major cloud providers. Or choose NetApp StorageGRID to keep your cold data in your own private cloud for highest performance and complete control over your data.

.Related information

https://docs.netapp.com/us-en/ontap/concept_cloud_overview.html[FabricPool System Manager doc^]

https://docs.netapp.com/us-en/bluexp-tiering/index.html[BlueXP tiering^]

https://www.youtube.com/playlist?list=PLdXI3bZJEw7mcD3RnEcdqZckqKkttoUpS[FabricPool playlist on NetApp TechComm TV^]

// 2023-07-25, ONTAPDOC-821
//github issue 251