---
permalink: concepts/index.html
sidebar: sidebar
keywords: decide, concepts, ontap, overview, data, management, cluster storage, high-availability, virtualization, protection, storage, efficiency, security
summary: "This guide describes the concepts that inform ONTAP data management software, including cluster storage, high-availability, virtualization, data protection, storage efficiency, and security."
---

= Concepts overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes the concepts that inform ONTAP data management software, including cluster storage, high-availability, virtualization, data protection, storage efficiency, and security. You should use this content if you want to understand the full range of ONTAP features and benefits before you configure your storage solution.

*_If you need reference and configuration information_* about the ONTAP capabilities described in this content, you should choose among the following documentation:

* High availability (HA) configuration
+
link:/high-availability/index.html[High Availability]

* Cluster and SVM administration
+
link:/system-admin/index.html[System administration]

* Network and LIF management
+
link:/networking/index.html[Network management]

* Disks and aggregates
+
link:/disks-aggregates/index.html[Disk and aggregate management]

* FlexVol volumes, FlexClone technology, and storage efficiency features
+
link:/volumes/index.html[Logical storage management]

* SAN host provisioning
+
link:/san-admin/index.html[SAN administration]

* NAS file access
 ** link:/nfs-admin/index.html[NFS management]
 ** link:/smb-admin/index.html[SMB management]
* Disaster recovery and archiving
+
link:/data-protection/index.html[Data protection]
