---
permalink: concepts/introducing-ontap-interfaces-concept.html
sidebar: sidebar
keywords: ontap interfaces, storage manager, bluexp, cli, rest api
summary: "ONTAP data management software offers many interfaces you can use to manage your ONTAP protected data."
---
= ONTAP user interfaces
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP data management software offers many interfaces you can use to manage your ONTAP protected data. These interface options provide different levels of access and functionality and give you the flexibility to manage your ONTAP cluster as you'd prefer.

In ONTAP, you can use any of these interfaces to manage a cluster and perform data operations:

== ONTAP System Manager 
ONTAP System Manager is a web-based user interface that provides a simplified and intuitive way to manage your cluster. You can administer common operations such as storage configuration, volume creation, data protection, and network setup and management. System Manager also provides risk and cluster performance monitoring and insights to help you react to and get ahead of cluster issues before they occur. link:../ontap/concept_administration_overview.html[Learn more].

== BlueXP
With BlueXP web-based user interface, you can manage your hybrid multicloud infrastructure from a single control plane while retaining the familiar System Manager dashboard. BlueXP enables you to create and administer cloud storage (for example, Cloud Volumes ONTAP), use NetApp's data services (for example, Cloud Backup), and control many on-premise and edge storage devices. Adding on-premises ONTAP systems to BlueXP enables you to manage all of your storage and data assets from a single interface. https://docs.netapp.com/us-en/bluexp-family/[Learn more^].

== ONTAP Command Line Interface (CLI)

The link:../system-admin/command-line-interface-concept.html[ONTAP CLI] is a text-based interface that allows you to interact with a cluster using link:../concepts/manual-pages.html[commands]. 

These link:../system-admin/different-shells-cli-commands-concept-cluster-admin.html[CLI types] are available based on role and permission level:

*clustershell*: Provides a comprehensive set of commands for cluster management and configuration.
*nodeshell*: Provides a node-level specific set of commands.
*systemshell*: Provides low-level cluster diagnostic and troubleshooting access.

You can access the ONTAP CLI through SSH or a console connection to a node in the cluster.

=== RESTful API 
ONTAP provides a RESTful API that allows you to programmatically manage and automate cluster operations. Use HTTP requests to interact with the API and perform tasks, such as creating and managing volumes, snapshots, and aggregates, as well as monitoring cluster performance. You can access the ONTAP REST API directly using any programming language that supports a REST client and use languages such as Python, PowerShell, and Java. https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html[Learn More^].

== NetApp PowerShell Toolkit
If you use PowerShell for automation and management, NetApp PowerShell Toolkit provides you a set of cmdlets to manage and configure your ONTAP cluster using PowerShell scripts. https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html#client-software-toolkits[Learn More^].

In addition to these native interfaces, there are various ways to https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html[script ONTAP actions^].

// 2024-2-13, Jira 1328
