---
permalink: concepts/introducing-ontap-interfaces-concept.html
sidebar: sidebar
keywords: ontap interfaces, storage manager, bluexp, cli, rest api
summary: "ONTAP data management software offers many interfaces you can use to manage your ONTAP protected data."
---
= ONTAP user interfaces
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP data management software offers many interfaces you can use to manage your ONTAP protected data. These interface options provide different levels of access and functionality and give you the flexibility to manage your ONTAP cluster as you'd prefer.

In ONTAP, you can use any of these interfaces to manage a cluster and perform data operations:

== ONTAP System Manager 
ONTAP System Manager is a web-based graphical user interface (GUI) that provides a simplified and intuitive way to manage your cluster. You can management tasks such as configuring storage, creating and managing volumes, setting up data protection, and monitoring cluster performance. Learn More.

== BlueXP 
Does xxxx. Learn More.

== ONTAP Command Line Interface (CLI)

The ONTAP CLI is a text-based interface that allows you to interact with the cluster using commands. The CLI provides a comprehensive set of commands for cluster management, configuration, and monitoring. You can access the CLI through SSH or a console connection to a node in the cluster. Learn More.

== RESTful API 
ONTAP provides a RESTful API that allows you to programmatically manage and automate cluster operations. Use HTTP requests to interact with the API and perform tasks, such as creating and managing volumes, snapshots, and aggregates, as well as monitoring cluster performance. Learn More.

== NetApp PowerShell Toolkit
If you use PowerShell for automation and management, NetApp PowerShell Toolkit provides you a set of cmdlets to manage and configure your ONTAP cluster using PowerShell scripts. Learn More.


In addition to these native interfaces, there are various ways to https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html. [script ONTAP actions^].

// 2024-2-13, Jira 1328
