---
permalink: concepts/introducing-ontap-interfaces-concept.html
sidebar: sidebar
keywords: ontap interfaces, interfaces, system manager, bluexp, cli, rest api, ontapi
summary: "ONTAP data management software offers many interfaces you can use to manage your ONTAP protected data."
---
= ONTAP user interfaces
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP data management software offers multiple interfaces you can use to manage your ONTAP clusters. These interface options provide different levels of access and functionality and give you the flexibility to manage your ONTAP clusters as appropriate based on your environment.

You can use any of these interfaces to administer your ONTAP clusters and perform data management operations

== ONTAP System Manager 
ONTAP System Manager is a web-based user interface that provides a simplified and intuitive way to manage your cluster. You can administer common operations such as storage configuration, data protection, and network setup and management. System Manager also provides risk and cluster performance monitoring and insights to help you react to cluster issues and get ahead of issues before they occur. link:../concept_administration_overview.html[Learn more].

ONTAP 9.7 marked a critical juncture for ONTAP System Manager. In that release, NetApp delivered two versions of ONTAP System Manager, introducing a redesigned, more streamlined and  intuitive version along with the version that preceded 9.7. After 9.7, the redesigned version carried forward as ONTAP System Manager and its predecessor was renamed System Manager Classic. System Manager Classic was last available in ONTAP 9.7. Its documentation is available https://docs.netapp.com/us-en/ontap-system-manager-classic/index.html[separately^].

== BlueXP
Beginning with ONTAP 9.12.1, you can use the BlueXP web-based interface to manage your hybrid multicloud infrastructure from a single control plane while retaining the familiar System Manager dashboard. BlueXP enables you to create and administer cloud storage (for example, Cloud Volumes ONTAP), use NetApp's data services (for example, Cloud Backup), and control many on-premise and edge storage devices. Adding on-premises ONTAP systems to BlueXP enables you to manage all your storage and data assets from a single interface. https://docs.netapp.com/us-en/bluexp-family/[Learn more^].

== ONTAP command line interface

The link:../system-admin/index.html[ONTAP command line interface (CLI)] is a text-based interface that allows you to interact with a cluster, node, SVM, and more using link:../concepts/manual-pages.html[commands]. CLI commands are available based on link:../system-admin/cluster-svm-administrators-concept.html[role type]. You can access the ONTAP CLI through SSH or a console connection to a node in the cluster.

== ONTAP REST API 
Beginning with ONTAP 9.6, you can access a RESTful API that allows you to programmatically manage and automate cluster operations. Use the API to perform various ONTAP administrative tasks, such as such as creating and managing volumes, snapshots, and aggregates, as well as monitoring cluster performance. You can access the ONTAP REST API directly using a utility such as curl or with any programming language that supports a REST client, such as Python, PowerShell, and Java. https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html[Learn more^].

NOTE: ONTAPI is a proprietary ONTAP API that precedes the ONTAP REST API. The ONTAPI interface will be disabled in future versions of ONTAP. If you are using ONTAPI, you should plan your https://docs.netapp.com/us-en/ontap-automation/migrate/ontapi_disablement.html[migration to the ONTAP REST API^].


== NetApp toolkits and frameworks
NetApp provides client toolkits for specific development languages and environments that abstract the ONTAP REST API and make it easier to create automation code.
https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html#client-software-toolkits[Learn more^].

In addition to these toolkits, you can create and deploy automation code using frameworks. https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html#automation-frameworks[Learn more^].

// 2024 Feb to June, Jira 1328
