---
permalink: concepts/licensing-concept.html
sidebar: sidebar
keywords: licensing, ONTAP, enable features
summary: "A license is a record of one or more software entitlements. Beginning in May 2023, all new AFF systems (both A-series and C-series) and FAS systems are sold with either the ONTAP One software suite or the ONTAP Base software suite."
---
= ONTAP licensing
:icons: font
:imagesdir: ../media/

[.lead]
A license is a record of one or more software entitlements. Beginning in May 2023, all new AFF systems (both A-series and C-series) and FAS systems are sold with either the ONTAP One software suite or the ONTAP Base software suite.  Beginning in June 2023, ONTAP systems using 28-character license keys (LICKEY) can request an upgrade to the ONTAP One or ONTAP Base compatibility bundle. 

== Licenses included with ONTAP One
ONTAP One contains all available licensed functionality. It contains a combination of the contents of the former Core bundle, Data Protection bundle, Security and Compliance bundle, Hybrid Cloud bundle, and Encryption bundle, as shown in the table. Encryption is not available in restricted countries. 

|===

h| Former bundle name h| ONTAP One keys included
.5+| Core bundle
| FlexClone
| SnapRestore
| NFS, SMB, S3
| FC, iSCSI
| NVME-oF

.3+| Security and Compliance bundle
| Autonomous Ransomware Protection
| MTKM
| SnapLock
.3+| Data Protection bundle
| SnapMirror (asynchronous, synchronous, Business Continuity)
| SnapCenter
| S3 SnapMirror for NetApp targets
.2+| Hybrid Cloud bundle
| SnapMirror Cloud
| S3 SnapMirror for non-NetApp targets
.3+| Encryption bundle
| NetApp Volume Encryption
| Trusted Platform module
| Data at Rest Encryption
|===

== Licenses not included with ONTAP One
ONTAP One does not include any of NetApp’s cloud-delivered services, including the following:

* BlueXP tiering
* Cloud Insights
* BlueXP backup
* Data governance

== ONTAP One for existing systems

If you have existing systems that are currently under NetApp support but have not been upgraded to ONTAP One, the existing licenses on those systems are still valid and continue to work as expected. For example, if the SnapMirror license is already installed on existing systems, it is not necessary to upgrade to ONTAP One to get a new SnapMirror license. However, if you do not have a SnapMirror license installed on an existing system, the only way to get that license is to upgrade to ONTAP One for an additional fee.


// 2023-Jan-17, ONTAPDOC-1366