---
permalink: concepts/support-industry-standard-technologies-concept.html
sidebar: sidebar
keywords: support, industry-standard, network, technologies
summary: "ONTAP supports all major industry-standard network technologies. Key technologies include IPspaces, DNS load balancing, and SNMP traps."
---
= Support for industry-standard network technologies
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP supports all major industry-standard network technologies. Key technologies include IPspaces, DNS load balancing, and SNMP traps.

Broadcast domains, failover groups, and subnets are described in xref:nas-path-failover-concept.adoc[NAS path failover].

== IPspaces

You can use an _IPspace_ to create a distinct IP address space for each virtual data server in a cluster. Doing so enables clients in administratively separate network domains to access cluster data while using overlapping IP addresses from the same IP address subnet range.

A service provider, for example, could configure different IPspaces for tenants using the same IP addresses to access a cluster.

== DNS load balancing

You can use _DNS load balancing_ to distribute user network traffic across available ports. A DNS server dynamically selects a network interface for traffic based on the number of clients that are mounted on the interface.

== SNMP traps

You can use _SNMP traps_ to check periodically for operational thresholds or failures. SNMP traps capture system monitoring information sent asynchronously from an SNMP agent to an SNMP manager.

== FIPS compliance 

ONTAP is compliant with the Federal Information Processing Standards (FIPS) 140-2 for all SSL connections. You can turn on and off SSL FIPS mode, set SSL protocols globally, and turn off any weak ciphers such as RC4.
