---
sidebar: sidebar
permalink: concepts/sysmgr-integration-console-concept.html
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, netapp console, console, hybrid, cloud, dashboard, multicloud
summary: You can manage ONTAP 9.10.1 and later releases using System Manager in the NetApp Console. This integration allows you to efficiently oversee your hybrid multicloud infrastructure using a unified control plane, all while retaining the familiar System Manager user interface.
---
= Integrate ONTAP System Manager with NetApp Console
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can manage ONTAP 9.10.1 and later releases using System Manager in the NetApp Console. This integration allows you to efficiently oversee your hybrid multicloud infrastructure using a unified control plane, all while retaining the familiar System Manager user interface.

The Console enables you to create and administer cloud storage (for example, Cloud Volumes ONTAP), use NetApp data services (for example, Cloud Backup), and control many on-premise and edge storage devices.

The Console provides two ways to discover and manage your clusters:

* Direct discovery for management through System Manager (ONTAP 9.12.1 and later)
* Discovery through a Console agent.

The Console agent is software installed in your environment. This allows you to access management functions through System Manager and access NetApp cloud services that provide features such as data replication, backup and recovery, data classification, data tiering, and more.

Learn more about link:https://docs.netapp.com/us-en/console-ontap-onprem/index.html[On-premises ONTAP cluster management using NetApp Console^].

.Steps

. Log into the NetApp Console.
.. If you have a Console login, use it.
.. If this is your first time, select Log in with your NetApp Support Site Credentials and enter your credentials on the Console login page.
. Discover your on-premise cluster in the Console using a Console agent or direct discovery. Learn more about link: https://docs.netapp.com/us-en/console-ontap-onprem/task-discovering-ontap.html[discovering on-premises ONTAP clusters^].
.. Learn how to link:https://docs.netapp.com/us-en/console-ontap-onprem/task-manage-ontap-direct.html[manage clusters that were discovered directly^].
.. Learn how to link:https://docs.netapp.com/us-en/console-ontap-onprem/task-manage-ontap-connector.html[manage clusters that were discovered with a Console agent^].
. Manage your on-premise cluster using System Manager. On My working environments Systems page, select the cluster, and click System Manager from the Services list.
.. Learn more about link:https://docs.netapp.com/us-en/console-ontap-onprem/task-manage-ontap-direct.html[managing clusters that were discovered directly^].
.. Learn how to link:https://docs.netapp.com/us-en/console-ontap-onprem/task-manage-ontap-connector.html[manage clusters that were discovered with a Console agent^].

== NetApp Console and ONTAP 9.12.1

Note: If you are using ONTAP 9.12.1, a message appears to prompt you to try out the NetApp Console.
+
If the cluster has connectivity to the NetApp Console, a login prompt displays.

. Click *Continue to NetApp Console* to follow the link to the Console.
+
[NOTE] 
If your system settings have blocked external networks, you will not be able to access the Console.  To access System Manager using the Console, you must ensure that the address "`cloudmanager.cloud.netapp.com`" can be accessed by your system.  Otherwise, at the prompt, you can choose to use the version of System Manager that is installed with your ONTAP system.

. On the Console login page, select *Log in with your NetApp Support Site Credentials* and enter your credentials.
+
If you've already used the Console and have a login using an email and password, then you'll need to continue using that login option instead.
+
https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html[Learn more about logging in to the NetApp Console^].

. If you're prompted, enter a name for your new NetApp Console account.
+
In most cases, the Console automatically creates an account for you based on data from your cluster.

. Enter the cluster administrator credentials for the cluster.

.Result

System Manager displays and you can now manage the cluster from the Console.

== Learn more about NetApp Console

* https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html[NetApp Console overview^]

* https://docs.netapp.com/us-en/console-ontap-onprem/index.html[Manage your NetApp AFF and FAS systems through NetApp Console^]


// 2025-Sept-9, BLUEXPDOC-872
// 2025 June 24, GH-1349
// 2025 June 23, GH-1349
// ONTAPDOC-724, 2022 Dec 06
// ONTAPDOC-1413 2023 Nov 29
