---
permalink: concepts/thin-provisioning-concept.html
sidebar: sidebar
keywords: thin provision
summary: "A thin-provisioned volume or LUN is one for which storage is not reserved in advance. Instead, storage is allocated dynamically, as it is needed. Free space is released back to the storage system when data in the volume or LUN is deleted."
---
= Thin provisioning
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP offers a wide range of storage efficiency technologies in addition to snapshots. Key technologies include thin provisioning, deduplication, compression, and FlexClone volumes, files, and LUNs. Like snapshots, all are built on ONTAP's Write Anywhere File Layout (WAFL).

A _thin-provisioned_ volume or LUN is one for which storage is not reserved in advance. Instead, storage is allocated dynamically, as it is needed. Free space is released back to the storage system when data in the volume or LUN is deleted.

Suppose that your organization needs to supply 5,000 users with storage for home directories. You estimate that the largest home directories will consume 1 GB of space.

In this situation, you could purchase 5 TB of physical storage. For each volume that stores a home directory, you would reserve enough space to satisfy the needs of the largest consumers.

As a practical matter, however, you also know that home directory capacity requirements vary greatly across your community. For every large user of storage, there are ten who consume little or no space.

Thin provisioning allows you to satisfy the needs of the large storage consumers without having to purchase storage you might never use. Since storage space is not allocated until it is consumed, you can "`overcommit`" an aggregate of 2 TB by nominally assigning a size of 1 GB to each of the 5,000 volumes the aggregate contains.

As long as you are correct that there is a 10:1 ratio of light to heavy users, and as long as you take an active role in monitoring free space on the aggregate, you can be confident that volume writes won't fail due to lack of space.
