---
permalink: pnfs/pnfs-overview.html
sidebar: sidebar
keywords: tr-4063, pnfs, parallel nfs, nfsv4.1, nfsv4.2, performance, metadata, data path, technical report
summary: "Parallel NFS (pNFS) improves performance by allowing NFS clients to perform read/write operations on storage devices directly and in parallel, bypassing the NFS server as a potential bottleneck."
---
= Learn about parallel NFS (pNFS) in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
Parallel NFS was introduced as an RFC standard in January 2010 under RFC-5661 as a way to allow clients to directly access file data on NFSv4.1 servers by separating the metadata and data paths, which offers performance benefits by way of data localization, CPU efficiency, and parallelization of operations. A later RFC was authored in 2018 covering pNFS layout types (RFC-8434), which defines standards for file, block and object layouts. _ONTAP leverages the file layout type for pNFS operations_ and has supported it since ONTAP 8.1 (~2013).

NOTE: Beginning in July 2024, content from technical reports previously published as PDFs has been integrated with ONTAP product documentation. The ONTAP NFS storage management documentation now includes content from _TR-4063: Parallel Network File System (pNFS) in NetApp ONTAP_.

For years, NFSv3 was the standard version of the NFS protocol that was used for nearly all use cases. However, there were a number of limitations with the protocol, such as lack of statefulness, rudimentary permission model, and basic locking capabilities. NFSv4.0 (RFC 7530) introduced a series of improvements over NFSv3 and was further improved with the subsequent NFSv4.1 (RFC 5661) and NFSv4.2 (RFC 7862) versions, which added features such as parallel NFS (pNFS).

== Benefits of NFSv4.x

NFSv4.x provides the following benefits over NFSv3:

* Firewall-friendly because NFSv4 uses only a single port (2049) for its operations
* Advanced and aggressive cache management, like delegations in NFSv4.x
* Strong RPC security choices that employ cryptography
* Internationalization of characters
* Compound operations
* Works only with TCP
* Stateful protocol (not stateless like NFSv3)
* Full Kerberos integration for efficient authentication mechanisms
* NFS referrals
* Support of access control that is compatible with UNIX and Windows
* String-based user and group identifiers
* pNFS (NFSv4.1)
* Extended attributes (NFSv4.2)
* Security labels (NFSv4.2)
* FALLOCATE (NFSv4.2)

For more information about general NFSv4.x, including best practices and details about features, see https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf[NetApp Technical Report 4067: NFS Best Practice and Implementation Guide^].

.Related information

* link:../nfs-config/index.html[NFS configuration overview]
* link:../nfs-admin/index.html[NFS management overview]
* link:../flexgroup/index.html[FlexGroup volumes management]
* link:../nfs-trunking/index.html[NFS trunking overview]
* link:https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf[NetApp Technical Report 4067: NFS Best Practice and Implementation Guide^]
* link:https://www.netapp.com/pdf.html?item=/media/19384-tr-4523.pdf[NetApp Technical Report 4523: DNS Load Balancing in ONTAP^]
* link:https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf[NetApp Technical Report 4616: NFS Kerberos in ONTAP with Microsoft Active Directory^]

// 2025-10-21, ONTAPDOC-2826
