---
permalink: error-messages/index.html
sidebar: sidebar
keywords: ems, configuration, event, management, system, events, notifications
summary: "You can quickly configure ONTAP to send important EMS (Event Management System) event notifications directly to an email address, a syslog server, or a Simple Management Network Protocol (SNMP) traphost so that you are immediately notified of system issues that require prompt attention."
---
= EMS configuration overview
:icons: font
:imagesdir: ../media/

[.lead]
You can configure ONTAP 9 to send important EMS (Event Management System) event notifications directly to an email address, syslog server, Simple Management Network Protocol (SNMP) traphost, or webhook application so that you are immediately notified of system issues that require prompt attention.

Because important event notifications are not enabled by default, you need to configure the EMS to send notifications to either an email address, a syslog server, an SNMP traphost, or webhook application.

Review release-specific versions of the link:https://docs.netapp.com/us-en/ontap-ems-9131/[ONTAP 9 EMS Reference^]. 

If your EMS event mapping uses deprecated ONTAP command sets (such as event destination, event route), it’s recommended that you update your mapping.  link:https://docs.netapp.com/us-en/ontap/error-messages/convert-ems-routing-to-notifications-task.html[Learn how to update your EMS mapping from deprecated ONTAP commands^]. 


// 2023 Mar 30, Jira 973
// 2022 Jan 10 , BURT 1448684
// 2022 Aug 11, issue #622