---
permalink: nfs-admin/commands-manage-local-unix-groups-reference.html
sidebar: sidebar
keywords: command, manage, local, unix, group
summary: "There are specific ONTAP commands for managing local UNIX groups."
---
= Commands for managing local UNIX groups in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
There are specific ONTAP commands for managing local UNIX groups.

[cols="35,65"]
|===

h| If you want to... h| Use this command...

a|
Create a local UNIX group
a|
`vserver services name-service unix-group create`
a|
Add a user to a local UNIX group
a|
`vserver services name-service unix-group adduser`
a|
Load local UNIX groups from a URI
a|
`vserver services name-service unix-group load-from-uri`
a|
Display local UNIX groups
a|
`vserver services name-service unix-group show`
a|
Modify a local UNIX group
a|
`vserver services name-service unix-group modify`
a|
Delete a user from a local UNIX group
a|
`vserver services name-service unix-group deluser`
a|
Delete a local UNIX group
a|
`vserver services name-service unix-group delete`
|===

Learn more about `vserver services name-service unix-group` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+unix-group[ONTAP command reference^].

// 2025 Jan 16, ONTAPDOC-2569 
