---
permalink: nfs-admin/commands-manage-nis-domain-config-reference.html
sidebar: sidebar
keywords: command, manage, nis, domain, configuration
summary: "There are specific ONTAP commands for managing NIS domain configurations."
---
= Commands for managing NIS domain configurations in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
There are specific ONTAP commands for managing NIS domain configurations.

[cols="35,65"]
|===

h| If you want to... h| Use this command...

a|
Create a NIS domain configuration
a|
`vserver services name-service nis-domain create`
a|
Display NIS domain configurations
a|
`vserver services name-service nis-domain show`
a|
Display binding status of a NIS domain configuration
a|
`vserver services name-service nis-domain show-bound`
a|
Display NIS statistics
a|
`vserver services name-service nis-domain show-statistics` Available at the advanced privilege level and higher.

a|
Clear NIS statistics
a|
`vserver services name-service nis-domain clear-statistics` Available at the advanced privilege level and higher.

a|
Modify a NIS domain configuration
a|
`vserver services name-service nis-domain modify`
a|
Delete a NIS domain configuration
a|
`vserver services name-service nis-domain delete`
a|
Enable caching for netgroup-by-host searches
a|
`vserver services name-service nis-domain netgroup-database config modify` Available at the advanced privilege level and higher.

|===

Learn more about `vserver services name-service nis-domain` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+nis-domain[ONTAP command reference^].

// 2025 Jan 16, ONTAPDOC-2569 
