---
permalink: nfs-admin/control-root-user-access-ntfs-security-data-task.html
sidebar: sidebar
keywords: control, root, user, access, ntfs, security, style, data
summary: "You can configure ONTAP to allow NFS clients access to NTFS security-style data and NTFS clients to access NFS security-style data. When using NTFS security style on an NFS data store, you must decide how to treat access by the root user and configure the storage virtual machine (SVM) accordingly."
---
= Control root user access to NTFS security-style data for ONTAP SVMs
:icons: font
:imagesdir: ../media/

[.lead]
You can configure ONTAP to allow NFS clients access to NTFS security-style data and NTFS clients to access NFS security-style data. When using NTFS security style on an NFS data store, you must decide how to treat access by the root user and configure the storage virtual machine (SVM) accordingly.

.About this task

When a root user accesses NTFS security-style data, you have two options:

* Map the root user to a Windows user like any other NFS user and manage access according to NTFS ACLs.
* Ignore NTFS ACLs and provide full access to root.

.Steps

. Set the privilege level to advanced:
+
`set -privilege advanced`
. Perform the desired action:
+
[cols="35,65"]
|===

h| If you want the root user to... h| Enter the command...

a|
Be mapped to a Windows user
a|
`vserver nfs modify -vserver vserver_name -ignore-nt-acl-for-root disabled`
a|
Bypass the NT ACL check
a|
`vserver nfs modify -vserver vserver_name -ignore-nt-acl-for-root enabled`
|===
+
By default, this parameter is disabled.
+
If this parameter is enabled but there is no name mapping for the root user, ONTAP uses a default SMB administrator credential for auditing.

. Return to the admin privilege level:
+
`set -privilege admin`

// 2025 May 28, ONTAPDOC-2982