---
permalink: nfs-admin/control-nfs-access-over-tcp-udp-task.html
sidebar: sidebar
keywords: control, nfs, access, tcp, udp
summary: "You can enable or disable NFS access to storage virtual machines (SVMs) over TCP and UDP by modifying the -tcp and -udp parameters, respectively. This enables you to control whether NFS clients can access data over TCP or UDP in your environment."
---
= Control NFS access over TCP and UDP for ONTAP SVMs
:icons: font
:imagesdir: ../media/

[.lead]
You can enable or disable NFS access to storage virtual machines (SVMs) over TCP and UDP by modifying the `-tcp` and `-udp` parameters, respectively. This enables you to control whether NFS clients can access data over TCP or UDP in your environment.

.About this task

These parameters only apply to NFS. They do not affect auxiliary protocols. For example, if NFS over TCP is disabled, mount operations over TCP still succeed. To completely block TCP or UDP traffic, you can use export policy rules.

[NOTE]
====
You must turn off the SnapDiff RPC Server before you disable TCP for NFS to avoid a command failed error. You can disable TCP by using the command `vserver snapdiff-rpc-server off -vserver vserver name`.
====

.Step

. Perform one of the following actions:
+
[cols="30,70"]
|===

h| If you want NFS access to be... h| Enter the command...

a|
Enabled over TCP
a|
`vserver nfs modify -vserver vserver_name -tcp enabled`
a|
Disabled over TCP
a|
`vserver nfs modify -vserver vserver_name -tcp disabled`
a|
Enabled over UDP
a|
`vserver nfs modify -vserver vserver_name -udp enabled`
a|
Disabled over UDP
a|
`vserver nfs modify -vserver vserver_name -udp disabled`
|===

// 2025 May 23, ONTAPDOC-2982