---
permalink: nfs-admin/decide-security-style-svm-flexvol-concept.html
sidebar: sidebar
keywords: decide, security, style, svm
summary: "To help you decide which security style to use on a volume, you should consider two factors. The primary factor is the type of administrator that manages the file system. The secondary factor is the type of user or service that accesses the data on the volume."
---
= Decide which security style to use on ONTAP NAS SVMs
:icons: font
:imagesdir: ../media/

[.lead]
To help you decide which security style to use on a volume, you should consider two factors. The primary factor is the type of administrator that manages the file system. The secondary factor is the type of user or service that accesses the data on the volume.

When you configure the security style on a volume, you should consider the needs of your environment to ensure that you select the best security style and avoid issues with managing permissions. The following considerations can help you decide:

[cols="20,80"]
|===

h| Security style h| Choose if...

a|
UNIX
a|

* The file system is managed by a UNIX administrator.
* The majority of users are NFS clients.
* An application accessing the data uses a UNIX user as the service account.

a|
NTFS
a|

* The file system is managed by a Windows administrator.
* The majority of users are SMB clients.
* An application accessing the data uses a Windows user as the service account.

a|
Mixed
a|
* The file system is managed by both UNIX and Windows administrators and users consist of both NFS and SMB clients.
|===

// 2025 May 27, ONTAPDOC-2982