---
permalink: nfs-admin/enable-nfsv42-security-labels-task.html
sidebar: sidebar
keywords: enable, nfs, v4.2, security, label
summary: "Beginning with ONTAP 9.9.1, NFS security labels can be enabled. They are disabled by default."
---
= Enable NFS v4.2 security labels
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.9.1, NFS security labels can be enabled. They are disabled by default.

.About this task

With NFS v4.2 security labels, ONTAP NFS servers are Mandatory Access Control (MAC) aware, storing and retrieving sec_label attributes sent by clients.

For more information, see https://tools.ietf.org/html/rfc7204[RFC7240]

[NOTE]
====
NFS v4.2 security labels are not currently supported for NDMP dump operations. If security labels are encountered on files or directories, the dump fails.
====

.Steps

. Change the privilege setting to advanced:
+
``set -privilege advanced``
+
Learn more about `set` in the link:https://docs.netapp.com/us-en/ontap-cli/set.html[ONTAP command reference^].
. Enable security labels:
+
``vserver nfs modify -vserver svm_name -v4.2-seclabel enabled``
+
Learn more about `vserver nfs modify` in the link:https://docs.netapp.com/us-en/ontap-cli/vserver-nfs-modify.html[ONTAP command reference^].

// 2025 Mar 10, ONTAPDOC-2758