---
permalink: nfs-admin/enable-nfs-over-tls-cli.html
sidebar: sidebar
keywords: enable, tls, data, lif
summary: "You can use the ONTAP CLI to enable TLS on a data LIF for NFS clients. This enables the SVM to use TLS security services for NFS."
---
= Enable TLS for NFS clients
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `vserver nfs tls interface enable` command to enable TLS on a data LIF for NFS clients. This enables the SVM to use TLS security services for NFS.

.Before you begin

Refer to the link:tls-nfs-strong-security-concept.html[requirements^] for NFS over TLS before you begin.

.Steps

. Choose a storage VM and a logical interface (LIF) on which to enable TLS.
. Enable TLS for NFS connections on that storage VM and interface. Replace values in brackets <> with information from your environment:
+
[source,console]
----
vs1::> vserver nfs tls interface enable -vserver <STORAGE_VM> -lif <LIF_NAME> -certificate-name <CERTIFICATE_NAME>
----
. Use the `vserver nfs tls interface show` command to view the results:
+
[source,console]
----
vs1::> vserver nfs tls interface show
----

.Example

The following command enables TLS for NFS connections on the `data1` LIF of the `vs1` storage VM: 
[source,console]
----
vs1::> vserver nfs tls interface enable -vserver vs1 -lif data1 -certificate-name cert_vs1
----

[source,console]
----
vs1::> vserver nfs tls interface show
----
               Logical
Vserver        Interface     Address         TLS Status TLS Certificate Name
-------------- ------------- --------------- ---------- -----------------------
vs1           data1         10.0.1.1     enabled    cert_vs1
vs2           data2         10.0.1.2     disabled   -
2 entries were displayed.

// 2023-03-20, ONTAPDOC-1747