---
permalink: nfs-admin/enable-disable-modification-nfsv4-acls-task.html
sidebar: sidebar
keywords: enable, disable, modification, nfsv4, acl
summary: "When ONTAP receives a chmod command for a file or directory with an ACL, by default the ACL is retained and modified to reflect the mode bit change. You can disable the -v4-acl-preserve parameter to change the behavior if you want the ACL to be dropped instead."
---
= Enable or disable NFSv4 ACL modification for ONTAP SVMs
:icons: font
:imagesdir: ../media/

[.lead]
When ONTAP receives a `chmod` command for a file or directory with an ACL, by default the ACL is retained and modified to reflect the mode bit change. You can disable the `-v4-acl-preserve` parameter to change the behavior if you want the ACL to be dropped instead.

.About this task

When using unified security style, this parameter also specifies whether NTFS file permissions are preserved or dropped when a client sends a chmod, chgroup, or chown command for a file or directory.

The default for this parameter is enabled.

.Steps

. Set the privilege level to advanced:
+
`set -privilege advanced`
. Perform one of the following actions:
+
[cols="35,65"]
|===

h| If you want to... h| Enter the following command...

a|
Enable retention and modification of existing NFSv4 ACLs (default)
a|
`vserver nfs modify -vserver vserver_name -v4-acl-preserve enabled`
a|
Disable retention and drop NFSv4 ACLs when changing mode bits
a|
`vserver nfs modify -vserver vserver_name -v4-acl-preserve disabled`
|===

. Return to the admin privilege level:
+
`set -privilege admin`

// 2025 May 28, ONTAPDOC-2982