---
permalink: nfs-admin/enable-disable-nfsv4-write-file-delegations-task.html
sidebar: sidebar
keywords: enable, disable, nfsv4, write, file, delegation
summary: "To enable or disable write file delegations, you can modify the -v4.0-write-delegation or -v4.1-write-delegation option. By enabling write file delegations, you can eliminate much of the message overhead associated with file and record locking in addition to opening and closing of files."
---
= Enable or disable NFSv4 write file delegations for ONTAP SVMs
:icons: font
:imagesdir: ../media/

[.lead]
To enable or disable write file delegations, you can modify the ``-v4.0-write-delegation``or `-v4.1-write-delegation` option. By enabling write file delegations, you can eliminate much of the message overhead associated with file and record locking in addition to opening and closing of files.

.About this task

By default, write file delegations are disabled.

The disadvantage of enabling write file delegations is that the server and its clients must perform additional tasks to recover delegations after the server reboots or restarts, a client reboots or restarts, or a network partition occurs.

.Step

. Perform one of the following actions:
+
[cols="2*",options="header"]
|===
| If you want to...| Then...
a|
Enable NFSv4 write file delegations
a|
Enter the following command: `vserver nfs modify -vserver vserver_name -v4.0-write-delegation enabled`
a|
Enable NFSv4.1 write file delegations
a|
Enter the following command: `vserver nfs modify -vserver vserver_name -v4.1-write-delegation enabled`
a|
Disable NFSv4 write file delegations
a|
Enter the following command: `vserver nfs modify -vserver vserver_name -v4.0-write-delegation disabled`
a|
Disable NFSv4.1 write file delegations
a|
Enter the following command: `vserver nfs modify -vserver vserver_name -v4.1-write-delegation disabled`
|===

.Result

The file delegation options take effect as soon as they are changed. There is no need to reboot or restart NFS.

// 2025 May 28, ONTAPDOC-2982