---
permalink: nfs-admin/enable-disable-pnfs-task.html
sidebar: sidebar
keywords: enable, disable, pnfs
summary: "pNFS improves performance by allowing NFS clients to perform read/write operations on storage devices directly and in parallel, bypassing the NFS server as a potential bottleneck. To enable or disable pNFS (parallel NFS), you can modify the -v4.1-pnfs option."
---
= Enable or disable pNFS
:icons: font
:imagesdir: ../media/

[.lead]
pNFS improves performance by allowing NFS clients to perform read/write operations on storage devices directly and in parallel, bypassing the NFS server as a potential bottleneck. To enable or disable pNFS (parallel NFS), you can modify the `-v4.1-pnfs` option.

[cols=2*,options="header",cols="50,50"]
|===
| If the ONTAP release is...
| The pNFS default is...
| 9.8 or later | disabled
| 9.7 or earlier | enabled
|===

.What you'll need

NFSv4.1 support is required to be able to use pNFS.

If you want to enable pNFS, you must first disable NFS referrals. They cannot both be enabled at the same time.

If you use pNFS with Kerberos on SVMs, you must enable Kerberos on every LIF on the SVM.

.Step

. Perform one of the following actions:
+
[cols="2*",options="header"]
|===
| If you want to...| Enter the command...
a|
Enable pNFS
a|
`vserver nfs modify -vserver vserver_name -v4.1-pnfs enabled`
a|
Disable pNFS
a|
`vserver nfs modify -vserver vserver_name -v4.1-pnfs disabled`
|===


.Related information 
* xref:../nfs-trunking/index.html[NFS trunking overview]

// 2021-12-20, BURT 1437743
