---
permalink: nfs-admin/enable-disable-nfsv4-acls-task.html
sidebar: sidebar
keywords: enable, disable, nfsv4, acls
summary: "To enable or disable NFSv4 ACLs, you can modify the -v4.0-acl and -v4.1-acl options. These options are disabled by default."
---
= Enable or disable NFSv4 ACLs for ONTAP SVMs
:icons: font
:imagesdir: ../media/

[.lead]
To enable or disable NFSv4 ACLs, you can modify the `-v4.0-acl` and `-v4.1-acl` options. These options are disabled by default.

.About this task

The `-v4.0-acl` or `-v4.1-acl` option controls the setting and viewing of NFSv4 ACLs; it does not control enforcement of these ACLs for access checking.

.Step

. Perform one of the following actions:
+
[cols="30,70"]
|===

h| If you want to... h| Then...

a|
Enable NFSv4.0 ACLs
a|
Enter the following command:

`vserver nfs modify -vserver vserver_name -v4.0-acl enabled`
a|
Disable NFSv4.0 ACLs
a|
Enter the following command:

`vserver nfs modify -vserver vserver_name -v4.0-acl disabled`
a|
Enable NFSv4.1 ACLs
a|
Enter the following command:

`vserver nfs modify -vserver vserver_name -v4.1-acl enabled`
a|
Disable NFSv4.1 ACLs
a|
Enter the following command:

`vserver nfs modify -vserver vserver_name -v4.1-acl disabled`
|===

// 2025 May 28, ONTAPDOC-2982