---
permalink: nfs-admin/enable-disable-nfsv4-referrals-task.html
sidebar: sidebar
keywords:
summary: 'You can enable NFSv4 referrals on storage virtual machines \(SVMs\) by enabling the options -v4-fsid-change and -v4.0-referrals or -v4.1-referrals. Enabling NFSV4 referrals can result in faster data access for NFSv4 clients that support this feature.'
---
= Enable or disable NFSv4 referrals for ONTAP SVMs
:icons: font
:imagesdir: ../media/

[.lead]
You can enable NFSv4 referrals on storage virtual machines (SVMs) by enabling the options `-v4-fsid-change` and ``-v4.0-referrals``or `-v4.1-referrals`. Enabling NFSV4 referrals can result in faster data access for NFSv4 clients that support this feature.

.Before you begin

If you want to enable NFS referrals, you must first disable parallel NFS. You cannot enable both at the same time.

.Steps

. Set the privilege level to advanced:
+
`set -privilege advanced`
. Perform one of the following actions:
+
[cols="35,65"]
|===

h| If you want to... h| Enter the command...

a|
Enable NFSv4 referrals
a|
`vserver nfs modify -vserver vserver_name -v4-fsid-change enabled` `vserver nfs modify -vserver vserver_name -v4.0-referrals enabled`
a|
Disable NFSv4 referrals
a|
`vserver nfs modify -vserver vserver_name -v4.0-referrals disabled`
a|
Enable NFSv4.1 referrals
a|
`vserver nfs modify -vserver vserver_name -v4-fsid-change enabled` `vserver nfs modify -vserver vserver_name -v4.1-referrals enabled`
a|
Disable NFSv4.1 referrals
a|
`vserver nfs modify -vserver vserver_name -v4.1-referrals disabled`
|===

. Return to the admin privilege level:
+
`set -privilege admin`

// 2025 May 28, ONTAPDOC-2982