---
permalink: nfs-admin/how-name-mappings-used-concept.html
sidebar: sidebar
keywords: configure, name, mapping
summary: "ONTAP uses name mapping to map SMB identities to UNIX identities, Kerberos identities to UNIX identities, and UNIX identities to SMB identities. It needs this information to obtain user credentials and provide proper file access regardless of whether they are connecting from an NFS client or a SMB client."
---
= Learn about name mapping configuration for ONTAP NAS SVMs
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP uses name mapping to map SMB identities to UNIX identities, Kerberos identities to UNIX identities, and UNIX identities to SMB identities. It needs this information to obtain user credentials and provide proper file access regardless of whether they are connecting from an NFS client or a SMB client.

There are two exceptions where you do not have to use name mapping:

* You configure a pure UNIX environment and do not plan to use SMB access or NTFS security style on volumes.
* You configure the default user to be used instead.
+
In this scenario, name mapping is not required because instead of mapping every individual client credential all client credentials are mapped to the same default user.

Note that you can use name mapping only for users, not for groups.

However, you can map a group of individual users to a specific user. For example, you can map all AD users that start or end with the word SALES to a specific UNIX user and to the user's UID.

// 2025 May 27, ONTAPDOC-2982
// 4 Feb 2022, BURT 1451789 