---
permalink: nfs-admin/modify-nfs-over-tls-cli.html
sidebar: sidebar
keywords: enable, tls, data, lif
summary: "You can use the ONTAP CLI to change an existing TLS configuration on a data LIF for NFS clients."
---
= Modify an NFS over TLS configuration
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `vserver nfs tls interface modify` command to make changes to an existing TLS configuration on a data LIF for NFS clients. 

.Before you begin

Refer to the link:tls-nfs-strong-security-concept.html[requirements^] for NFS over TLS before you begin.

.Steps

. Choose a storage VM and a logical interface (LIF) on which to modify the TLS configuration.
. Modify the TLS configuration for NFS connections on that storage VM and interface. Replace values in brackets <> with information from your environment:
+
[source,console]
----
vs1::> vserver nfs tls interface modify -vserver <STORAGE_VM> -lif <LIF_NAME> -status <TLS_STATUS> -certificate-name <CERTIFICATE_NAME>
----
. Use the `vserver nfs tls interface show` command to view the results:
+
[source,console]
----
vs1::> vserver nfs tls interface show
----

.Example

The following command modifies the TLS configuration for NFS connections on the `data2` LIF of the `vs2` storage VM: 
[source,console]
----
vs1::> vserver nfs tls interface modify -vserver vs2 -lif data2 -status enabled -certificate-name cert_vs2
----

[source,console]
----
vs1::> vserver nfs tls interface show
----
               Logical
Vserver        Interface     Address         TLS Status TLS Certificate Name
-------------- ------------- --------------- ---------- -----------------------
vs1           data1         10.0.1.1     enabled    cert_vs1
vs2           data2         10.0.1.2     enabled   cert_vs2
2 entries were displayed.

// 2023-03-20, ONTAPDOC-1747