---
permalink: nfs-admin/nconnect-concept.html
sidebar: sidebar
keywords: nconnect, nfs, performance, tcp connections, nfsv3, nfsv4.2 nfsv4.1
summary: "nconnect improves NFS performance by enabling multiple TCP connections for a single mount point."
---
= Learn about nconnect for NFS performance
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.8, nconnect functionality is available by default when NFSv4.1 is enabled. nconnect improves NFS client performance by allowing multiple TCP connections for a single mount.

== How nconnect works

Earlier NFS client implementations use only a single TCP connection with a mount. In ONTAP, a single TCP connection can become a bottleneck with increasing IOPS.

An nconnect-enabled client can have multiple TCP connections (up to 16) associated with a single NFS mount. nconnect uses only one IP address and establishes multiple TCP connections over that single IP to mount the NFS export. The NFS client distributes file operations onto multiple TCP connections in a round-robin fashion, obtaining higher throughput from the available network bandwidth.

== Supported NFS versions

* nconnect is recommended for NFSv3, NFSv4.2, and NFSv4.1 mounts.

* nconnect is _not_ recommended for NFSv4.0 mounts.
+
NOTE: For optimal performance, NetApp recommends using NFSv4.1 with nconnect instead of NFSv4.0. While NFSv4.0 supports multiple connections, NFSv4.1 with nconnect provides better load distribution and improved throughput.

== Client support

See your NFS client documentation to confirm whether nconnect is supported in your client version.

== Related information

* link:ontap-support-nfsv41-concept.html[Learn about ONTAP support for NFSv4.1]
* link:ontap-support-nfsv42-concept.html[Learn about ONTAP support for NFSv4.2]

// 2025 Nov 12, GH-1788