---
permalink: nfs-admin/ontap-export-policy-caches-concept.html
sidebar: sidebar
keywords: ontap, use, export, policy, cache
summary: "To improve system performance, ONTAP uses local caches to store information such as host names and netgroups. This enables ONTAP to process export policy rules more quickly than retrieving the information from external sources. Understanding what the caches are and what they do can help you troubleshoot client access issues."
---
= Learn about ONTAP NFS export policy caches
:icons: font
:imagesdir: ../media/

[.lead]
To improve system performance, ONTAP uses local caches to store information such as host names and netgroups. This enables ONTAP to process export policy rules more quickly than retrieving the information from external sources. Understanding what the caches are and what they do can help you troubleshoot client access issues.

You configure export policies to control client access to NFS exports. Each export policy contains rules, and each rule contains parameters to match the rule to clients requesting access. Some of these parameters require ONTAP to contact an external source, such as DNS or NIS servers, to resolve objects such as domain names, host names, or netgroups.

These communications with external sources take a small amount of time. To increase performance, ONTAP reduces the amount of time it takes to resolve export policy rule objects by storing information locally on each node in several caches.
[cols="2*",options="header"]
|===
| Cache name| Type of information stored
a|
Access
a|
Mappings of clients to corresponding export policies
a|
Name
a|
Mappings of UNIX user names to corresponding UNIX user IDs
a|
ID
a|
Mappings of UNIX user IDs to corresponding UNIX user IDs and extended UNIX group IDs
a|
Host
a|
Mappings of host names to corresponding IP addresses
a|
Netgroup
a|
Mappings of netgroups to corresponding IP addresses of members
a|
Showmount
a|
List of exported directories from SVM namespace
|===
If you change information on the external name servers in your environment after ONTAP retrieved and stored it locally, the caches might now contain outdated information. Although ONTAP refreshes caches automatically after certain time periods, different caches have different expiration and refresh times and algorithms.

Another possible reason for caches to contain outdated information is when ONTAP attempts to refresh cached information but encounters a failure when attempting to communicate with name servers. If this happens, ONTAP continues to use the information currently stored in the local caches to prevent client disruption.

As a result, client access requests that are supposed to succeed might fail, and client access requests that are supposed to fail might succeed. You can view and manually flush some of the export policy caches when troubleshooting such client access issues.

// 2025 May 23, ONTAPDOC-2982