---
permalink: nfs-admin/ontap-preserves-unix-permissions-concept.html
sidebar: sidebar
keywords: ontap, preserve, unix, permission
summary: "When files in a FlexVol volume that currently have UNIX permissions are edited and saved by Windows applications, ONTAP can preserve the UNIX permissions."
---
= Learn about ONTAP NFS UNIX permission preservation
:icons: font
:imagesdir: ../media/

[.lead]
When files in a FlexVol volume that currently have UNIX permissions are edited and saved by Windows applications, ONTAP can preserve the UNIX permissions.

When applications on Windows clients edit and save files, they read the security properties of the file, create a new temporary file, apply those properties to the temporary file, and then give the temporary file the original file name.

When Windows clients perform a query for the security properties, they receive a constructed ACL that exactly represents the UNIX permissions. The sole purpose of this constructed ACL is to preserve the file's UNIX permissions as files are updated by Windows applications to ensure that the resulting files have the same UNIX permissions. ONTAP does not set any NTFS ACLs using the constructed ACL.

// 2025 May 23, ONTAPDOC-2982