---
permalink: nfs-admin/specify-nfsv4-locking-lease-period-task.html
sidebar: sidebar
keywords: specify, nfsv4, lock, lease, period
summary: "To specify the NFSv4 locking lease period (that is, the time period in which ONTAP irrevocably grants a lock to a client), you can modify the -v4-lease-seconds option. Shorter lease periods speed up server recovery while longer lease periods are beneficial for servers handling a very large amount of clients."
---
= Specify the NFSv4 locking lease period for ONTAP SVMs
:icons: font
:imagesdir: ../media/

[.lead]
To specify the NFSv4 locking lease period (that is, the time period in which ONTAP irrevocably grants a lock to a client), you can modify the `-v4-lease-seconds` option. Shorter lease periods speed up server recovery while longer lease periods are beneficial for servers handling a very large amount of clients.

.About this task

By default, this option is set to `30`. The minimum value for this option is `10`. The maximum value for this option is the locking grace period, which you can set with the `locking.lease_seconds` option.

.Steps

. Set the privilege level to advanced:
+
`set -privilege advanced`
. Enter the following command:
+
`vserver nfs modify -vserver vserver_name -v4-lease-seconds number_of_seconds`
. Return to the admin privilege level:
+
`set -privilege admin`

// 2025 May 28, ONTAPDOC-2982