---
permalink: nfs-admin/support-vmware-vstorage-over-nfs-concept.html
sidebar: sidebar
keywords: support, vmware, vStorage, nfs
summary: "ONTAP supports certain VMware vStorage APIs for Array Integration (VAAI) features in an NFS environment."
---
= Learn about support for VMware vStorage over ONTAP NFS
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP supports certain VMware vStorage APIs for Array Integration (VAAI) features in an NFS environment.

== Supported features

The following features are supported:

* Copy offload
+
Enables an ESXi host to copy virtual machines or virtual machine disks (VMDKs) directly between the source and destination data store location without involving the host. This conserves ESXi host CPU cycles and network bandwidth. Copy offload preserves space efficiency if the source volume is sparse.

* Space reservation
+
Guarantees storage space for a VMDK file by reserving space for it.

== Limitations

VMware vStorage over NFS has the following limitations:

* Copy offload operations can fail in the following scenarios:
 ** While running wafliron on the source or destination volume because it temporarily takes the volume offline
 ** While moving either the source or destination volume
 ** While moving either the source or destination LIF
 ** While performing takeover or giveback operations
 ** While performing switchover or switchback operations
* Server-side copy can fail due to file handle format differences in the following scenario:
+
You attempt to copy data from SVMs that have currently or had previously exported qtrees to SVMs that have never had exported qtrees. To work around this limitation, you can export at least one qtree on the destination SVM.

.Related information

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_VAAI_offloaded_operations_are_supported_by_Data_ONTAP%3F[What VAAI offloaded operations are supported by Data ONTAP?]

// 2025 May 28, ONTAPDOC-2982