---
sidebar: sidebar
permalink: anti-ransomware/arp-ai-automatic-updates.html
keywords: ransomware, arp, automatic, ai, update, upgrade, autonomous ransomware protection
summary: Keep up-to-date ARP/AI protection against ransomware threats by automatically or manually updating security bundles.
---

= Update Automatic Ransomware Protection with AI (ARP/AI)
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To keep up-to-date protection against the latest ransomware threats, ARP/AI (available beginning with ONTAP 9.16.1) offers automatic updates that occur outside of regular ONTAP release cadences. If you have enabled automatic system and firmware updates then you will also be able to start receiving automatic updates to ARP/AI. If you have not enabled this setting, you can do so using this procedure or elect to install ARP/AI update security bundles manually.

.About this task

The default method of updating ARP/AI is link:../update/enable-automatic-updates-task.html[automatic updates]. Beginning with ONTAP 9.16.1, security downloads are available in System Manager in addition to system and firmware bundles.

Manual updates are also available from the NetApp Support Site. These can also be downloaded and installed from System Manager.

.Before you begin

For manual updates:

* Access to the NetApp Support Site downloads.
* Subscription to NetApp Support Site download monitoring to be informed of new updates.
* You have turned off automatic downloads in the cluster settings for security.

== Manually update ARP/AI with the latest security bundle

You can only update ARP/AI with security bundles using System Manager. 

.Steps

. 

.Related information

* link:enable-arp-ai-with-au.html[Enable ARP/AI]

// 2024-9-17, ontapdoc-2204
