---
sidebar: sidebar
permalink: anti-ransomware/enable-arp-ai-with-au.html
keywords: ransomware, arp, enable, ai, automatic, update, upgrade, autonomous ransomware protection
summary: "Beginning with ONTAP 9.16.1, either automatically enable ARP/AI for FlexVol installations with ARP enabled or manually enable it after meeting prerequisites."
---

= Enable ARP/AI with automatic updating
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP 9.16.1, ARP has adopted Autonomous Ransomware Protection with Artificial Intelligence (ARP/AI) to improve threat detection and response. After upgrading your cluster to ONTAP 9.16.1, ARP/AI will be automatically enabled for existing and new FlexVol volumes if ARP is already enabled for those volumes. If you have not enabled ARP or have not enabled automatic updates your cluster, you can do so using this procedure.

IMPORTANT: Before upgrading to ONTAP 9.16.1, link:respond-abnormal-task.html[close out any existing ARP detections].

//Change this to upgrade warning

.Before you begin

* You must have FlexVol volumes to use ARP/AI. If you have FlexGroup, the pre-AI ARP model continues to operate after upgrading to ONTAP 9.16.1.

NOTE: When you upgrade to ONTAP 9.16.1, ARP is enabled automatically in active mode for any existing ARP instances. Because AI is trained on an extensive machine learning model, a learning period is no longer required. Any learning periods that have not been completed prior to upgrade will be automatically be ended and the volumes transitioned to active mode.

.Steps

. Follow the scenario that is specific to your configuration:

* *For new clusters running ONTAP 9.16.1*: Enable ARP. ARP is not enabled by default. After you enable ARP, ARP/AI functionality is automatically enabled in active mode on the volumes you choose to protect. 
* *For existing clusters recently upgraded to ONTAP 9.16.1 that have ARP enabled*: No action needed. ARP/AI will automatically become the new ARP method of threat protection on the volumes you've chosen to protect. 
* *For existing clusters recently upgraded to ONTAP 9.16.1 that do not have ARP enabled*: Enable ARP. ARP/AI will automatically become the new ARP method of threat protection after you enable ARP.

. After ARP/AI is enabled, decide whether you want ARP/AI protection updates to be delivered and installed link:arp-ai-automatic-updates.html[automatically or manually] installed. 

.Related information

* link:arp-ai-automatic-updates.html[Update ARP/AI]

// 2024-9-17, ontapdoc-2204