---
sidebar: sidebar
permalink: anti-ransomware/index.html
keywords: anti-ransomware overview, ransomware, security, introduce, autonomous, protection, arp, detect, detection, threat, attack, suspect, what ontap anti-ransomware detects, entropy, abnormal volume activity, ransomware, antiransomware, extension conformity, recover data after a ransomware attack, ransomware protection strategy
summary: Beginning with ONTAP 9.10.1, the Autonomous Ransomware Protection (ARP) feature uses workload analysis in NAS (NFS and SMB) environments to proactively detect and warn about abnormal activity that might indicate a ransomware attack.
---

= Autonomous Ransomware Protection overview
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning with ONTAP 9.10.1, the Autonomous Ransomware Protection (ARP) feature uses workload analysis in NAS (NFS and SMB) environments to proactively detect and warn about abnormal activity that might indicate a ransomware attack.

When an attack is suspected, ARP also creates new Snapshot copies, in addition to existing protection from scheduled Snapshot copies.

The ARP feature is enabled with the following licenses.
[cols="2*",options="header"]
|===
| ONTAP releases| License
a| ONTAP 9.11.1 and later
a| Anti_ransomware
a| ONTAP 9.10.1
a| MT_EK_MGMT (Multi-Tenant Key Management)
|===

* If you are upgrading to ONTAP 9.11.1 or later and ARP is already configured on your system, you do not need to purchase the new Anti-ransomware license. For new ARP configurations, the new license is required.
* If you are reverting from ONTAP 9.11.1 or later to ONTAP 9.10.1, and you have enabled ARP with the Anti-ransomware license, you will see a warning message and might need to reconfigure ARP. link:../revert/anti-ransomware-license-task.html[Learn about reverting ARP].

You can configure ARP on a per-volume basis using either ONTAP System Manager or the ONTAP command line interface (CLI).

== ONTAP ransomware protection strategy

An effective ransomware detection strategy should include more than a single layer of protection.

An analogy would be the safety features of a vehicle. You wouldn’t want to rely on a single feature, such as a seatbelt, to completely protect you in an accident. Air bags, anti-lock brakes, and forward-collision warning are all additional safety features that will lead to a much better outcome. Ransomware protection should be viewed in the same way.

While ONTAP includes features like FPolicy, Snapshot copies, SnapLock, and Active IQ Digital Advisor to help protect from ransomware, the following information focuses on the ONTAP ARP on-box feature with machine-learning capabilities.

To learn more about ONTAP's other anti-ransomware features, see: https://www.netapp.com/media/7334-tr4572.pdf[TR-4572: NetApp Solution for Ransomware.^]

== What ONTAP ARP detects
There are two types of ransomware attacks:

.  Denial of service to files by encrypting data.
The attacker withholds access to this data unless a ransom is paid.
.  Theft of sensitive proprietary data.
The attacker threatens to release this data to the public domain unless a ransom is paid.

ONTAP ARP addresses the first type, with an anti-ransomware detection mechanism that is based on:

. Identification of the incoming data as encrypted or plaintext.
. Analytics, which detects
+
** High data _entropy_ (an evaluation of the randomness of data in a file)
** A surge in abnormal volume activity with data encryption
** An extension that does not conform to the normal extension type

[NOTE]
No ransomware detection or prevention system can completely guarantee safety from a ransomware attack. While it's possible an attack might go undetected, NetApp ARP acts as an important additional layer of defense if anti-virus software has failed to detect an intrusion. ARP can detect the spread of most ransomware attacks after only a small number of files are encrypted, take action automatically to protect data, and alert you that a suspected attack is happening.

== How to recover data in ONTAP after a ransomware attack

When an attack is suspected, the system takes a volume Snapshot copy at that point in time and locks that copy. If the attack is confirmed later, the volume can be restored to this proactively taken snapshot, minimizing the data loss.

Locked Snapshot copies cannot be deleted by normal means. However, if you decide later to mark the attack as a false positive, the locked copy will be deleted.

With the knowledge of the affected files and the time of attack, it is possible to selectively recover the affected files from various Snapshot copies, rather than simply reverting the whole volume to one of the snapshots.

ARP thus builds on proven ONTAP data protection and disaster recovery technology to respond to ransomware attacks. See the following topics for more information on recovering data.

**  link:../task_dp_recover_snapshot.html[Recover from Snapshot copies (System Manager)]

** link:../data-protection/restore-contents-volume-snapshot-task.html[Restoring files from Snapshot copies (CLI)]

** link:https://www.netapp.com/blog/smart-ransomware-recovery[Smart ransomware recovery^]

// 2022-08-25, BURT 1499112
// 2022 June 2, BURT 1466313
// Jira IE-517, 2022 Mar 30
// BURT 1459708, 2022 Feb 24
// BURT 1448684, 10 JAN 2022
// Jira IE-353,  29 OCT 2021
