---
sidebar: sidebar
permalink: anti-ransomware/index.html
keywords: ransomware, arp, autonomous protection, ai, arp ai, security, detect, detection, threat, attack, suspect, anti-ransomware, entropy, abnormal volume activity, antiransomware, extension conformity, ransomware protection strategy
summary: Autonomous Ransomware Protection uses workload analysis in NAS or SAN environments to detect and warn about abnormal activity that might be a ransomware attack.
---

= Learn about ONTAP Autonomous Ransomware Protection
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.10.1, ONTAP administrators can enable Autonomous Ransomware Protection (ARP) to perform workload analysis in NAS (NFS and SMB) environments to proactively detect and warn about abnormal activity that might indicate a ransomware attack. Beginning with ONTAP 9.17.1, ARP also supports block-device volumes, including SAN volumes containing LUNs or NVMe namespaces, or NAS volumes containing virtual disks from hypervisors such as VMware, Hyper-V, and KVM. 

ARP is built directly into ONTAP, ensuring integrated control and coordination with ONTAP's other features. ARP operates in real-time, processing data as it's written to or read from the file system, and detecting and responding to potential ransomware attacks quickly. 

ARP creates locked snapshots at regular intervals alongside scheduled ones for added protection. It smartly manages how long snapshots are kept. If no unusual activity is detected, snapshots are quickly recycled. However, if an attack is detected, a snapshot created before the start of an attack is kept for an extended period.

== Licenses and enablement

You'll need a license to be able to use ARP. You'll also need to consider if you want to enable ARP at the volume or SVM level and if you want ARP enabled by default in new and existing volumes.

=== License options for ARP

ARP support is included with the link:https://kb.netapp.com/onprem/ontap/os/ONTAP_9.10.1_and_later_licensing_overview[ONTAP One license^]. If you do not have the ONTAP One license, other licenses are available for ARP use that differ depending on your version of ONTAP. 

[cols="2*",options="header"]
|===
| ONTAP releases| License
a| ONTAP 9.11.1 and later a| `Anti_ransomware`
a| ONTAP 9.10.1 a| `MT_EK_MGMT` (Multi-Tenant Key Management)
|===

* If you are upgrading from ONTAP 9.10.1 to ONTAP 9.11.1 or later and ARP is already configured on your system, you do not need to install the new `Anti-ransomware` license. For new ARP configurations, the new license is required.
* If you are reverting from ONTAP 9.11.1 or later to ONTAP 9.10.1, and you have enabled ARP with the Anti_ransomware license, you will see a warning message and might need to reconfigure ARP. link:../revert/anti-ransomware-license-task.html[Learn about reverting ARP].

=== Enablement options for ARP
// ONTAP 9.18.1+ ARP default enablement
.Default enablement on all supported volumes

Beginning with ONTAP 9.18.1, ARP is enabled by default on all supported volumes after a 12-hour grace period following an upgrade or new installation, provided that an ARP license is installed. 

This default enablement does not apply to SnapLock, DP, LS, SMBC/SSM/SnapMirror active sync, or ONTAP S3 volumes.

During the grace period, you can opt out of default enablement for existing and new volumes using System Manager or the ONTAP CLI. If you do not opt out, ARP is automatically enabled on all supported volumes at the end of the grace period. This enablement occurs automatically for existing volumes that have not yet enabled ARP. Any new volumes created after the grace period are also enabled by default. 

For more information, refer to link:default-enable-change.html[ARP default enablement on all supported volumes] documentation.

.Default enablement on new volumes
Prior to ONTAP 9.18.1, ARP is not enabled by default. If your system is running an earlier version of ONTAP and you'd like to link:enable-default-task.html[enable ARP by default in all new volumes], you can change this setting at the SVM level.

.ARP enablement on select volumes
If you'd prefer to limit ARP enablement to a specific volume and not change the SVM settings, you can link:enable-task.html[enable ARP on a per-volume basis].

== ONTAP ransomware protection strategy

An effective ransomware detection strategy should include more than a single layer of protection. Consider the safety features of a vehicle as an analogy. You don't rely on a single feature, such as a seatbelt, to completely protect you in an accident. Air bags, anti-lock brakes, and forward-collision warning are safety features that collectively lead to a better outcome. Ransomware protection should be viewed in the same way.

While ONTAP includes features like FPolicy, snapshots, SnapLock, and Active IQ Digital Advisor (also known as Digital Advisor) to help protect from ransomware, the following information focuses on the ARP feature with machine learning capabilities.

To learn more about other features in the NetApp portfolio that safeguard against ransomware, see link:https://docs.netapp.com/us-en/ontap-technical-reports/ransomware-solutions/ransomware-active-iq.html[Ransomware and NetApp's protection portfolio^].

== What ARP detects

ONTAP ARP is designed to protect against denial-of-service attacks where the attacker withholds data until a ransom is paid. ARP offers real-time ransomware detection based on the following: 

* Identification of incoming data as either encrypted or plain text.
* Analytics that detect:
** *Entropy*: (Used in NAS and SAN) An evaluation of the randomness of data in a file
** *File extension types*: (Used in NAS only) A file extension that does not conform to expected extension types
** *File IOPS*: (Used in NAS only beginning with ONTAP 9.11.1) A surge in abnormal volume activity with data encryption

ARP detects the spread of most ransomware attacks after only a small number of files are encrypted, responds automatically to protect data, and alerts you that a suspected attack is happening.

[NOTE]
No ransomware detection system can guarantee complete safety. ARP provides an extra layer of defense if anti-virus software fails to detect an intrusion.

== Learn about ARP modes

After ARP is enabled for a volume, it enters a learning period to establish a baseline. ARP analyzes system metrics to develop an alert profile before transitioning to active detection mode. In active mode, ARP monitors abnormal activity, taking protective actions and generating alerts if it detects abnormal behavior.

For ARP, the learning mode and active mode behaviors differ by ONTAP version, volume type, and protocol (NAS or SAN).

=== NAS environments and mode types

The following table summarizes the differences between ONTAP 9.10.1 and later versions for NAS environments. 

In versions with the earlier ARP model, a learning period is recommended before active monitoring begins. For NAS environments that support <<arp-ai,ARP/AI>>, there is no learning period and active monitoring begins immediately.

[cols="1,5,1", options="header"]
|===
| Mode | Description | Volume types and versions
| Learning 
a| For certain versions of ONTAP and certain volume types, ARP is automatically set to learning mode when you enable ARP. In learning mode, the ONTAP system develops an alert profile based on the analytic areas: entropy, file extension types, and file IOPS.

It's recommended that you leave ARP in learning mode for 30 days. Beginning with ONTAP 9.13.1, ARP automatically determines the optimal learning interval and automates the switch, which might occur before 30 days. For versions earlier than ONTAP 9.13.1, you can make the switch manually.

Beginning with ONTAP 9.16.1 for FlexVol volumes, only active mode exists and learning mode is transitioned automatically to active mode for any FlexVol volumes upgraded to this version or later. 

For ONTAP 9.16.1 to 9.17.1, FlexGroup volumes are not yet supported by ARP/AI and continue to run the older ARP model. Because of this, a learning period is still recommended for these versions with FlexGroup volumes.

Beginning with ONTAP 9.18.1, only active mode exists for both FlexVol and FlexGroup volumes. Any upgraded volumes are transitioned to active mode automatically.

link:switch-learning-to-active-mode.html[Learn more about switching from learning to active mode].

TIP: The command `security anti-ransomware volume workload-behavior show` shows file extensions that have been detected in the volume. If you run this command early in learning mode and it shows an accurate representation of file types, you should not use that data as a basis to move to active mode, as ONTAP is still collecting other metrics. Learn more about `security anti-ransomware volume workload-behavior show` in the link:https://docs.netapp.com/us-en/ontap-cli/security-anti-ransomware-volume-workload-behavior-show.html[ONTAP command reference^].
a| * FlexVol volumes with ONTAP 9.10.1 to 9.15.1
* FlexGroup volumes with ONTAP 9.13.1 to ONTAP 9.17.1

| Active 
a| 
In active mode, if a file extension is flagged as abnormal, you should evaluate the alert. You can act on the alert to protect your data, or you can mark the alert as a false positive. Marking an alert as a false positive updates the alert profile. For example, if the alert is triggered by a new file extension and you mark the alert as a false positive, you will not receive an alert the next time that the file extension is observed.

a| All supported ONTAP versions and FlexVol and FlexGroup volumes

|===

=== SAN environments and mode types

SAN environments use _evaluation_ periods (similar to learning modes in NAS environments) before transitioning to active detection automatically. The following table summarizes evaluation and active modes.

[cols="1,5,1", options="header"]
|===
| Mode | Description | Volume types and versions
| Evaluation
a| A two- to four-week evaluation period is performed to determine baseline encryption behavior while ARP/AI provides immediate active protection for SAN volumes during the evaluation period. Detection and alerts can occur while baseline thresholds are being established. You can determine if the evaluation period is complete by running the `security anti-ransomware volume show` command and checking `Block device detection status`.

link:respond-san-entropy-eval-period.html[Learn more about SAN volumes and the entropy evaluation period].

a| * FlexVol volumes with ONTAP 9.17.1 and later

| Active
a| After the evaluation period, you can determine if the ARP SAN protection is active by running the `security anti-ransomware volume show` command and checking `Block device detection status`. A status of `Active_suitable_workload` indicates that the evaluated amount of entropy can be successfully monitored. ARP automatically adjusts the adaptive threshold according to data reviewed during the evaluation.

a| * FlexVol volumes with ONTAP 9.17.1 and later

|===

== Threat assessment and ARP snapshots

ARP assesses threat probability based on incoming data measured against learned analytics. When ARP detects an abnormality, a measurement is assigned. A snapshot might be assigned at the time of detection or at regular intervals.

=== ARP thresholds

* *Low*: The earliest detection of an abnormality in the volume (for example, a new file extension is observed in the volume). This level of detection is only available in versions prior to ONTAP 9.16.1 that do not have ARP/AI.

** Beginning with ONTAP 9.11.1, you can link:manage-parameters-task.html[customize the detection parameters for ARP].
** In ONTAP 9.10.1, the threshold for escalation to moderate is 100 or more files.

* *Moderate*: High entropy is detected or multiple files with the same never-seen-before file extension are observed. This is the baseline detection level in ONTAP 9.16.1 and later with ARP/AI.

The threat escalates to moderate after ONTAP runs an analytics report determining if the abnormality matches a ransomware profile. When the attack probability is moderate, ONTAP generates an EMS notification prompting you to assess the threat. ONTAP does not send alerts about low threats; however, beginning with ONTAP 9.14.1, you can link:manage-parameters-task.html#modify-alerts[modify default alert settings]. For more information, see link:respond-abnormal-task.html[Respond to abnormal activity].

You can view information about moderate threats in System Manager's *Events* section or with the `security anti-ransomware volume show` command. Low threat events can also be viewed using the `security anti-ransomware volume show` command in versions prior to ONTAP 9.16.1 that do not have ARP/AI. Learn more about `security anti-ransomware volume show` in the link:https://docs.netapp.com/us-en/ontap-cli/security-anti-ransomware-volume-show.html[ONTAP command reference^].

=== ARP snapshots

ARP creates a snapshot when early signs of an attack are detected. A detailed analysis is then conducted to confirm or dismiss the potential attack. Because ARP snapshots are created proactively even before an attack is fully confirmed, they might also be generated at regular intervals for certain legitimate applications. The presence of these snapshots should not be regarded as an anomaly. If an attack is confirmed, the attack probability is escalated to `Moderate` and an attack notification is generated.

Beginning with ONTAP 9.17.1, ARP snapshots are generated at regular intervals for both NAS and SAN volumes as well as in response to detected anomalies. ONTAP prepends a name to the ARP snapshot to make it easily identifiable.

Beginning with ONTAP 9.11.1, you can modify the retention settings. For more information, see link:modify-automatic-shapshot-options-task.html[Modify options for snapshots].

//Similar information repeated in respond-abnormal-task.adoc

The following table summarizes ARP snapshot differences by version.

[cols="1,3,3", options="header"]
|===
| Feature  | ONTAP 9.17.1 and later  | ONTAP 9.16.1 and earlier

| Creation trigger

a| * Snapshots are created at fixed 4-hour intervals, regardless of any specific trigger
* Confirmation of an attack

A "periodic" or "attack" snapshot is created based on trigger type.

a| * High entropy is detected
* A new file extension is detected (9.15.1 and earlier)
* A surge of file operations is detected (9.15.1 and earlier)

Snapshot creation interval is based on trigger type.

| Prepended name convention
| "Anti_ransomware_periodic_backup"
"Anti_ransomware_attack_backup"
| "Anti_ransomware_backup"

| Deletion behavior
| ARP snapshot is locked and cannot be deleted by the administrator
| ARP snapshot is locked and cannot be deleted by the administrator

| Maximum snapshot count
| link:modify-automatic-snapshot-options-task.html[Six snapshot configurable limit]
| link:modify-automatic-snapshot-options-task.html[Six snapshot configurable limit]

| Retention period
a| Snapshots are normally retained for 12 hours. 

* NAS volumes: If an attack is confirmed by file-analysis, snapshots created before the attack are retained until the administrator marks the attack as true or a false positive (clear-suspect).

* SAN volume or VM datastores: If an attack is confirmed by block-entropy analysis, snapshots created before the attack are retained for 10 days (configurable).

a| * Determined based on trigger conditions (not fixed)
* Snapshots created before the attack are retained until administrator marks the attack as true or a false positive (clear-suspect).

| Clear-suspect action
a| Administrators can perform a clear-suspect action which sets retention based on confirmation:

* 24 hours for false-positive retention
* 7 days for true-positive retention

a| Administrators can perform a clear-suspect action which sets retention based on confirmation:

* 24 hours for false-positive retention
* 7 days for true-positive retention

This precautionary retention behavior doesn't exist earlier than ONTAP 9.16.1

| Expiration time
| An expiration time is set for all snapshots
| None
|===

== How to recover data in ONTAP after a ransomware attack

ARP builds on proven ONTAP data protection and disaster recovery technology to respond to ransomware attacks. ARP creates locked snapshots when early signs of an attack are detected. You'll need to first confirm whether the attack is real or a false positive. If you confirm the attack, the volume can be restored using the ARP snapshot.

Locked snapshots cannot be deleted by normal means. However, if you decide later to mark the attack as a false positive, ONTAP deletes the locked copy. 

You can recover affected files from select snapshots instead of reverting the entire volume.

See the following topics for more information on responding to an attack and recovering data:

* link:respond-abnormal-task.html[Respond to abnormal activity]

* link:recover-data-task.html[Recover data from ARP snapshots]

* link:../data-protection/restore-contents-volume-snapshot-task.html[Recover from ONTAP snapshots]

* link:https://www.netapp.com/blog/smart-ransomware-recovery[Smart ransomware recovery^]

== Multi-admin verification protection for ARP

Beginning with ONTAP 9.13.1, it's recommended that you enable multi-admin verification (MAV) so that two or more authenticated user admins are required for Autonomous Ransomware Protection (ARP) configuration. For more information, see link:../multi-admin-verify/enable-disable-task.html[Enable multi-admin verification].

[[arp-ai]]
== Autonomous Ransomware Protection with Artificial Intelligence (ARP/AI) 

Beginning with ONTAP 9.16.1, ARP improves cyber resiliency by adopting a machine-learning model for anti-ransomware analytics that detects constantly evolving forms of ransomware with 99% accuracy in NAS environments. ARP's machine-learning model is pre-trained on a large dataset of files both before and after a simulated ransomware attack. This resource-intensive training is done outside ONTAP using open-source forensic research datasets to train the model. Customer data is not used throughout the entire modelling pipeline and privacy issues do not exist. The pre-trained model that results from this training is included on-box with ONTAP. This model is not accessible or modifiable through the ONTAP CLI or ONTAP API.

.Immediate transition to active protection for ARP/AI

With ARP/AI, there is no <<Learn about ARP modes,learning period>>. ARP/AI is active immediately after installation or upgrade for the following supported volume types:

* NAS FlexVol volumes with ONTAP 9.16.1 and later
* NAS FlexGroup volumes with ONTAP 9.18.1 and later
* SAN volumes with ONTAP 9.17.1 and later (active immediately, even during the link:respond-san-entropy-eval-period.html[evaluation period])

For existing and new volumes with ARP functionality already enabled, ARP/AI protection will be active automatically after you upgrade your cluster to an ARP/AI supported ONTAP version.

.ARP/AI automatic updates

To keep up-to-date protection against the latest ransomware threats, ARP/AI offers frequent automatic updates that occur outside of regular ONTAP upgrade and release cadences. If you have link:../update/enable-automatic-updates-task.html[enabled automatic updates] then you will also be able to start receiving automatic security updates to ARP/AI after you select automatic updates for security files. You can also choose to link:arp-ai-automatic-updates.html#manually-update-arpai-with-the-latest-security-package[make these updates manually] and control when the updates occur.

Beginning with ONTAP 9.16.1, security updates for ARP/AI are available using System Manager in addition to system and firmware updates.

link:arp-ai-automatic-updates.html[Learn more about ARP/AI updates]

.Related information
* link:https://docs.netapp.com/us-en/ontap-cli/[ONTAP command reference^]

// 2025-10-6, ONTAPDOC-3376
// 2025 9-9, ONTAPDOC-3321
// 2025 Aug 15, ONTAPDOC-1127
// 2025, Jul 7, ontapdoc-2689
// 2025, Jun 4, ontapdoc-3048
// 2025 May 20, ONTAPDOC-2998
// 2025 Mar 31, ONTAPDOC-2758
// 2025 Jan 22, ONTAPDOC-1070
// 2024-9-17, ontapdoc-2204
// 2025-1-22, ontapdoc-2663
// 2025-1-16, ontapdoc-2645
// 2023-02-27, #1259
// 21 dec 2023, ontapdoc-1550
// 22 august 2023, ONTAPDOC-1303
// 6 august 2023, ontapdoc-840
// 18 may 2023, ontapdoc-1046
// 2022-08-25, BURT 1499112
// 2022 June 2, BURT 1466313
// Jira IE-517, 2022 Mar 30
// BURT 1459708, 2022 Feb 24
// BURT 1448684, 10 JAN 2022
// Jira IE-353,  29 OCT 2021
