---
sidebar: sidebar
permalink: anti-ransomware/manage-parameters-task.html
keywords: anti-ransomware overview, ransomware, security, modify, security anti-ransomware attack, parameters
summary: Beginning in ONTAP 9.11.1, Autonomous Ransomware Protection detection parameters can be modified depending on the workload.
---
= Manage ARP attack detection parameters
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Beginning in ONTAP 9.11.1, you can modify the parameters for ransomware detection on a specific Autonomous Ransomware Protection-enabled volume and report a known surge as normal file activity. Adjusting detection parameters helps improve the accuracy of reporting based on your specific volume workload. 

== How attack detection works

When Autonomous Ransomware Protection (ARP) is in learning mode, it develops baseline values for volume behaviors. These are entropy, file extensions, and, beginning in ONTAP 9.11.1, IOPS. These baselines are used to evaluate ransomware threats. For more information about these criteria, see xref:index.html#what-arp-detects[What ARP detects].

In ONTAP 9.10.1, ARP issues a warning if it detects both of the following conditions:

* more than 20 files with file extensions not previously been observed in the volume
* high entropy data

Beginning in ONTAP 9.11.1, ARP issues a threat warning if _only_ one condition is met. For example, if more than 20 files with file extensions that have not previously been observed in the volume are observed within a 24 hour period, ARP will categorize this as a threat _regardless_ of observed entropy. (The 24 hour and 20 file values are defaults, which can be modified.) 

Certain volumes and workloads require different detection parameters. For example, your ARP-enabled volume may host numerous types of file extensions, in which case you may want to modify the threshold count for never-before-seen file extensions to a number greater than the default of 20 or disable warnings based on never-before-seen file extensions. Beginning with ONTAP 9.11.1, you can modify the attack detection parameters so they better fit your specific workloads. 

== Modify attack detection parameters

Depending on the expected behaviors of your ARP-enabled volume, you may want to modify the attack detection parameters.

.Steps
. View the existing attack detection parameters:
+
`security anti-ransomware volume attack-detection-parameters show -vserver _svm_name_ -volume _volume_name_`
+
....
security anti-ransomware volume attack-detection-parameters show -vserver vs1 -volume vol1
                                             Vserver Name : vs1
                                              Volume Name : vol1
            Is Detection Based on High Entropy Data Rate? : true
  Is Detection Based on Never Seen before File Extension? : true
                  Is Detection Based on File Create Rate? : true
                  Is Detection Based on File Rename Rate? : true
                  Is Detection Based on File Delete Rate? : true
           Is Detection Relaxing Popular File Extensions? : true
                High Entropy Data Surge Notify Percentage : 100
                 File Create Rate Surge Notify Percentage : 100
                 File Rename Rate Surge Notify Percentage : 100
                 File Delete Rate Surge Notify Percentage : 100
 Never Seen before File Extensions Count Notify Threshold : 20
       Never Seen before File Extensions Duration in Hour : 24
....
. All of the fields shown are modifiable with boolean or integer values. To modify a field, use the `security anti-ransomware volume attack-detection-parameters modify` command. 
+
For a full list of parameters, see link:https://docs.netapp.com/us-en/ontap-cli-9131/security-anti-ransomware-volume-attack-detection-parameters-modify.html[ONTAP command reference^].

== Report known surges

ARP continues to modify baseline values for detection parameters even in active mode. If you know of surges in your volume activity--either one-time surges or a surge that is characteristic of a new normal--you should report it as safe. Manually reporting these surges as safe helps to improve the accuracy of ARP's threat assessments. 

.One-time surges 
. If a one-time surge is occurring under known circumstances and you want ARP to report a similar surge in future circumstances, clear the surge from the workload behavior:  
+
`security anti-ransomware volume workload-behavior clear-surge -vserver _svm_name_ -volume _volume_name_`

.Modify baseline surge 
. If a reported surge should be considered normal application behavior, report the surge as such to modify the baseline surge value.
+
`security anti-ransomware volume workload-behavior update-baseline-from-surge -vserver _svm_name_ -volume _volume_name_`

.More information 
* link:https://kb.netapp.com/onprem/ontap/da/NAS/Understanding_Autonomous_Ransomware_Protection_attacks_and_the_Autonomous_Ransomware_Protection_snapshot[Understand Autonomous Ransomware Protection attacks and the Autonomous Ransomware Protection snapshot^]

// 8 august 2023, ontapdoc-840
