---
sidebar: sidebar
permalink: anti-ransomware/pause-task.html
keywords: anti-ransomware, ransomware, pause, autonomous, protection, arp
summary: If you are expecting unusual workload events, you can temporarily suspend and resume Autonomous Ransomware Protection (ARP) analysis at any time.
---

= Pause Autonomous Ransomware Protection to exclude workload events from analysis
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you are expecting unusual workload events, you can temporarily suspend and resume Autonomous Ransomware Protection (ARP) analysis at any time.

Beginning in ONTAP 9.13.1, you can enable multi-admin verification (MAV) so that two or more authenticated user admins are required to pause the APR. link:../multi-admin-verify/enable-disable-task.html[Learn more].

.What you'll need

*	ARP is running in learning or active mode.

.About this task

During an ARP pause, no events are logged nor are any actions for new writes. However, the analytics operation continues for earlier logs in the background.

[NOTE]
Do not use the anti-ransomware disable function to pause analytics. Doing so disables ARP on the volume and all the existing information around learned workload behavior is lost. This would require a restart of the learning period.

.Steps

[role="tabbed-block"]
====
.System Manager
--
.	Click *Storage > Volumes* and then select the volume where you want to pause ARP.
.	In the Security tab of the Volumes overview, click *Pause anti-ransomware* in the *Anti-ransomware* box.
--

.CLI
--
. Pause ARP on a volume:
+
`security anti-ransomware volume pause -vserver _svm_name_ -volume _vol_name_`
+
If you are using MAV, the operation fails and prompts you to request the verification of a second admin. 

. If you are using MAV, the second administrator does the following:

.. Show the request:
+
`security multi-admin-verify request show`

.. Approve the request:
+
`security multi-admin-verify request approve -index2`
+
The response indicates that the volume has been modified and the state of ARP is paused.

. To resume processing, use the `resume` parameter.

`security anti-ransomware volume resume -vserver _svm_name_ -volume _vol_name_`
--
====

// 2023-04-06, ontapdoc-931
// 2022-08-25, BURT 1499112
// 2021-10-29, Jira IE-353
