---
sidebar: sidebar
permalink: /anti-ransomware/pause-task.html
keywords: anti-ransomware, ransomware, pause anti-ransomware, pause anti-ransomware to exclude workload events
summary: If you are expecting unusual workload events, you can temporarily suspend and resume anti-ransomware analysis at any time.
---

= Pause anti-ransomware to exclude workload events from analysis
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

// new for ONTAP 9.10.1

[.lead]
If you are expecting unusual workload events, you can temporarily suspend and resume anti-ransomware analysis at any time.

.What you’ll need

*	Anti-ransomware is running in learning or active mode.

.About this task

During an anti-ransomware pause, no events are logged nor are any actions for new writes. However, the analytics operation continues for earlier logs in the background.

[NOTE]
]Do not use the anti-ransomware disable function to pause analytics. Doing so disables anti-ransomware on the volume and all the existing information around learned workload behavior is lost. This would require a restart of the learning period.

== System Manager procedure

.	Click *Storage > Volumes* and then select the volume where you want to pause anti-ransomware.
.	In the Security tab of the Volumes overview, click *Pause anti-ransomware* in the Anti-ransomware box.

== CLI procedure

Pause ransomware protection on a volume:

`security anti-ransomware volume pause -vserver svm_name -volume vol_name`

To resume processing, use the resume parameter.

`security anti-ransomware volume resume -vserver svm_name -volume vol_name`
