---
sidebar: sidebar
permalink: anti-ransomware/recover-data-task.html
keywords: Restore data after an attack, anti-ransomware backup, restore data from snapshot copies, potential ransomware attack, ransomware attack, recovery snapshot copies are deleted, recover deleted snapshot copies, autonomous, ransomware, protection, arp
summary: Snapshot copies named Anti_ransomware_backup are created when anti-ransomware detects a potential attack. You can restore data from these anti-ransomware copies or other Snapshot copies.
---

= Restore data after a ransomware attack
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Snapshot copies named “Anti_ransomware_backup” are created when Autonomous Ransomware Protection (ARP) detects a potential attack. You can restore data from these ARP copies or other Snapshot copies.

[NOTE]
If a ransomware attack occurs, see the Knowledge Base article link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Ransomware_prevention_and_recovery_in_ONTAP[Ransomware prevention and recovery in ONTAP^] for additional information on recovery and future mitigation.

.What you’ll need

*	ARP enabled
*	Reports from potential ransomware attacks


.Steps

[role="tabbed-block"]
====
.System Manager
--
.	Display the Snapshot copies in volumes identified in a potential attack:
Click *Storage > Volumes*, select the volume, then click the Snapshot Copies tab.

.	Restore the desired copies according to these instructions:
link:../task_dp_recover_snapshot.html[Recover from Snapshot copies]
--

.CLI
--
.	Display the Snapshot copies in volumes identified in a potential attack:
`volume snapshot show -vserver _svm_name_ -volume _vol_name_`

.	Restore the desired copies according to these instructions:
link:../data-protection/restore-contents-volume-snapshot-task.html[Restoring files from Snapshot copies]
--
====

// 2022-08-25, BURT 1499112
// 2022-06-10, jira-kda-1532
// 2021-12-08, BURT 1444760
// 2021-10-29, Jira IE-353
