---
sidebar: sidebar
permalink: anti-ransomware/respond-abnormal-task.html
keywords: abnormal activity, data entropy, unusual file extensions, potential ransomware attack, false positive, ransomware attack, abnormal activity notification, ransomware alert, detected abnormal volume, suspected file types, attack report, anti-ransomware attack, ransomware ems
summary: Learn about ARP notifications in ONTAP and determine if a ransomware attack is occurring and how to respond.
---
= Respond to abnormal activity detected by ONTAP ARP
:icons: font
:imagesdir: ../media/

[.lead]
When Autonomous Ransomware Protection (ARP) detects abnormal activity in a protected volume, it issues a warning. You should evaluate the notification to determine whether the activity is acceptable (false positive) or whether an attack seems malicious. After you categorize the attack, you can clear the warning and notices about suspected files.

When you categorize an attack, ARP snapshots are either deleted instantly (ONTAP 9.15.1 and earlier) or retained for an abbreviated period initiated by the categorization operation (ONTAP 9.16.1 and later).

NOTE: Beginning with ONTAP 9.11.1, you can modify the xref:modify-automatic-snapshot-options-task.html[retention settings] for ARP snapshots.

//Nearly identical content to threat assessment and arp snapshots in link
.About this task

ARP displays a list of suspected files when it detects any combination of high data entropy, abnormal volume activity with data encryption, and unusual file extensions. Beginning with ONTAP 9.17.1 for both NAS and SAN environments, details of entropy spikes are also reported on the Anti-ransomware page in System Manager.

When an ARP warning notification is issued, respond by designating the activity in one of two ways:

* *False positive*
+
The identified file type or entropy spike is expected in your workload and can be ignored.

* *Potential ransomware attack*
+
The identified file type or entropy spike is unexpected in your workload and should be treated as a potential attack.

Normal monitoring resumes after you update with your decision and clear the ARP notifications. ARP records your evaluation to the threat assessment profile, using your choice to monitor subsequent file activities. 

In the case of a suspected attack, you must determine whether it is an attack, respond to it if it is, and restore protected data before clearing the notices. link:index.html#how-to-recover-data-in-ontap-after-a-ransomware-attack[Learn more about how to recover from a ransomware attack].

[NOTE]
If you restore an entire volume, there are no notices to clear.

.Before you begin 

ARP must be actively protecting a volume and not in a learning or evaluation mode.

.Steps

You can use System Manager or the ONTAP CLI to respond to abnormal activity. 

[role="tabbed-block"]
====
.System Manager
--
. When you receive an "abnormal activity" notification, follow the link. Alternatively, navigate to the *Security* tab of the *Volumes* overview.
+
Warnings are displayed in the *Overview* pane of the *Events* menu.

. In the *Security* tab, review the suspected file types or entropy spikes report.
** For suspected files, examine each file type in the *Suspected File Types* dialog box and mark each individually.
** For entropy spikes, examine the entropy report.

. Record your response:
+
[cols="25,75"]
|===

h| If you select this value... h| Take this action...

a| False Positive a| . Do one of the following:
** For file type warnings, select *Update and Clear Suspect File Types*.
** For entropy spikes, select *Mark as false positive*.
+
These actions clear warning notices about suspected files or activity. ARP then resumes normal monitoring of the volume. For ONTAP 9.15.1 and earlier, related ARP snapshots are automatically deleted after you clear suspected file types. For ARP/AI in ONTAP 9.16.1 and later, ARP snapshots are automatically deleted after an abbreviated retention period triggered by the categorization operation.
+
NOTE: Beginning with ONTAP 9.13.1, if you are using MAV to protect your ARP settings, the clear-suspect operation prompts you to obtain the approval of one or more additional administrators. link:../multi-admin-verify/request-operation-task.html[Approval must be received from all administrators] associated with the MAV approval group or the operation will fail.

a| Potential Ransomware Attack a| . Respond to the attack:
** For file type warnings, mark selected files as *Potential ransomware attack* and link:recover-data-task.html[restore protected data].
** For entropy spikes that indicate an attack, select *Mark as potential ransomware attack* and link:recover-data-task.html[restore protected data].
. After data restoration is complete, record your decision and resume normal ARP monitoring:
** For file type warnings, select *Update and Clear Suspect File Types*.
** For entropy spikes, select *Mark as potential ransomware attack* and select *Save and dismiss*.

NOTE: There are no suspected file type notices to clear if you've restored an entire volume.

Recording your decision clears the attack report. For ONTAP 9.15.1 and earlier, after you restore a volume the ARP snapshots are automatically deleted. For ARP/AI in ONTAP 9.16.1 and later, ARP snapshots are automatically deleted after an abbreviated retention period triggered by the categorization operation.
|===
--

.CLI
--
. When you receive a notification of a suspected ransomware attack, verify the time and severity of the attack:
+
[source,cli]
----
security anti-ransomware volume show -vserver <svm_name> -volume <vol_name>
----
+
Sample output:
+
....
Vserver Name: vs0
Volume Name: vol1
State: enabled
Attack Probability: moderate
Attack Timeline: 5/12/2025 01:03:23
Number of Attacks: 1
Attack Detected By: encryption_percentage_analysis
....
+
You can also check EMS messages:
+
[source,cli]
----
event log show -message-name callhome.arw.activity.seen
----

. Generate an attack report and note the output location:
+
[source,cli]
----
security anti-ransomware volume attack generate-report -vserver <svm_name> -volume <vol_name> -dest-path <[svm_name]:[junction_path/sub_dir_name]>
----
+
Sample command:
+
----
security anti-ransomware volume attack generate-report -vserver vs0 -volume vol1 -dest-path vs0:vol1
----
+
Sample output:
+
----
Report "report_file_vs0_vol1_14-09-2021_01-21-08" available at path "vs0:vol1/"
----

. View the report on an admin client system. For example:
+
----
cat report_file_vs0_vol1_14-09-2021_01-21-08
----

. Take one of the following actions based on your evaluation of the file extensions or entropy spikes:

** False positive
+
Run one of the following commands to record your decision and resume normal Autonomous Ransomware Protection monitoring:

*** For file extensions:
+
[source,cli]
----
anti-ransomware volume attack clear-suspect -vserver <svm_name> -volume <vol_name> [<extension_identifiers>] -false-positive true
----
+
Use the following optional parameter to identify only specific extensions as false positives:
+
* `[-extension <text>, … ]`: File extensions

*** For entropy spikes:
+
[source,cli]
----
security anti-ransomware volume attack clear-suspect -vserver <svm_name> -volume <vol_name> -start-time <MM/DD/YYYY HH:MM:SS> -end-time <MM/DD/YYYY HH:MM:SS> -false-positive true
----

** Potential ransomware attack
+
Respond to the attack and link:../anti-ransomware/recover-data-task.html[recover data from the ARP-created backup snapshot]. After the data is recovered, run one of the following commands to record your decision and resume normal ARP monitoring:

*** For file extensions:
+
[source,cli]
----
anti-ransomware volume attack clear-suspect -vserver <svm_name> -volume <vol_name> [<extension identifiers>] -false-positive false
----
+
Use the following optional parameter to identify only specific extensions as potential ransomware:
+
* `[-extension <text>, … ]`: File extension

*** For entropy spikes:
+
[source,cli]
----
security anti-ransomware volume attack clear-suspect -vserver <svm_name> -volume <vol_name> -start-time <MM/DD/YYYY HH:MM:SS> -end-time <MM/DD/YYYY HH:MM:SS> -false-positive false
----

+
This `clear-suspect` operation clears the attack report. There are no suspected file type notices to clear if you restored an entire volume. For ONTAP 9.15.1 and earlier, ARP snapshots are automatically deleted after you restore a volume or clear a suspected event. For ARP/AI in ONTAP 9.16.1 and later, ARP snapshots are automatically deleted after an abbreviated retention period triggered by the categorization operation.

. If you are using MAV and an expected `clear-suspect` operation needs additional approvals, each MAV group approver must:
.. Show the request:
+
[source,cli]
----
security multi-admin-verify request show
----

.. Approve the request to resume normal anti-ransomware monitoring:
+
[source,cli]
----
security multi-admin-verify request approve -index[<number returned from show request>]
----
+
The response for the last group approver indicates that the volume has been modified and a false positive is recorded.

. If you are using MAV and you are a MAV group approver, you can also reject a clear-suspect request:
+
[source,cli]
----
security multi-admin-verify request veto -index[<number returned from show request>]
----

--
====

.Related information

* link:https://kb.netapp.com/onprem%2Fontap%2Fda%2FNAS%2FUnderstanding_Autonomous_Ransomware_Protection_attacks_and_the_Autonomous_Ransomware_Protection_snapshot#[KB: Understanding Autonomous Ransomware Protection attacks and the Autonomous Ransomware Protection snapshot^]
* link:modify-automatic-snapshot-options-task.html[Modify automatic snapshots options]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+anti-ransomware+volume[security anti-ransomware volume^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+multi-admin-verify+request[security multi-admin-verify request^]


// 2025 June 20, ONTAPDOC-2960
// 2025-1-16, ontapdoc-2645
// 2024-12-17, ontapdoc-2557
// 2024-02-26, #1267
// 2023-04-21, ONTAPDOC-931
// 2022-08-25, BURT 1499112
// 2022-06-02, ontap-issues-436
// 2021-10-29, Jira IE-353