---
sidebar: sidebar
permalink: anti-ransomware/use-cases-restrictions-concept.html
keywords: anti-ransomware use cases and restrictions, anti-ransomware performance and frequency considerations, anti-ransomware workloads, anti-ransomware volume requirements, anti-ransomware performance, volumes, anti-ransomware encryption, anti-ransomware system configurations, autonomous ransomware protection, arp
summary: In the current release, ransomware protection is most suitable in NAS environments. Support for other environments will be available in future releases.
---

= Autonomous Ransomware Protection use cases and considerations
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

ONTAP platform support:

* The Autonomous Ransomware Protection (ARP) feature is available for all on-premises ONTAP systems beginning with ONTAP 9.10.1.
* ARP is not currently available for ONTAP Select.
* ARP is not currently available for Amazon FSx or the following Cloud Volumes ONTAP environments:
** AWS
** Azure 
** Google Cloud

Suitable workloads:

* Databases on NFS storage
* Windows or Linux home directories
+
Because users could create files with extensions that weren’t detected in the learning period, there is greater possibility of false positives in this workload.
* Images and video
+
For example, health care records and Electronic Design Automation (EDA) data.

Beginning with ONTAP 9.12.1, ARP is available for these configurations:

* Volumes protected with SnapMirror
* SVMs protected with SnapMirror
* SVMs enabled for migration (SVM data mobility)

Unsuitable workloads:

* Workloads with a high frequency of file create or delete (hundreds of thousands of files in few seconds; for example, test/dev workloads)
* ARP depends on the ability to recognize an unusual surge in file create or delete activity. If the application itself is the source of the file activity, it cannot be effectively distinguished from ransomware activity
* Workloads where the application or the host encrypts data
ARP depends on distinguishing incoming data as encrypted or unencrypted. If the application itself is encrypting the data, then the effectiveness of the feature is reduced. However, the feature can still work based on file activity (create, delete, and overwrite) and file type.

Unsupported system configurations:

* SAN environments
* ONTAP S3 environments
* VMDKs on NFS

Volume requirements:

* Less than 100% full
* Junction path must be active

Unsupported volume types:

* Offline volumes
* Restricted volumes
* SnapLock volumes
* FlexGroup volumes
* FlexCache volumes (the anti-ransomware feature is supported on origin FlexVol volumes but not on cache volumes)
* SAN-only volumes
* Volumes of stopped storage VMs
* Root volumes of storage VMs

== SnapMirror and ARP interoperability
Beginning with ONTAP 9.12.1, ARP is supported on SnapMirror destination volumes. If a SnapMirror source volume is ARP-enabled, the SnapMirror destination volume automatically acquires the ARP configuration state (learning, enabled, etc), ARP training data, and ARP-created Snapshot of the source volume. No explicit enablement is required.

While the destination volume consists of read-only (RO) Snapshot copies, no ARP processing is done on its data. However, when the SnapMirror destination volume is converted to read-write (RW), ARP is automatically enabled on the RW-converted destination volume. The destination volume does not require any additional learning procedure besides what is already recorded on the source volume.

In ONTAP 9.10.1 and 9.11.1, SnapMirror does not transfer the ARP configuration state, training data, and Snapshot copies from source to destination volumes. Hence when the SnapMirror destination volume is converted to RW, ARP on the destination volume must be explicitly enabled in learning mode after conversion. 

== ARP performance and frequency considerations

The ARP feature can have a minimal impact on system performance as measured in throughput and peak IOPS. The impact of the anti-ransomware feature is highly dependent on volume workloads. For most typical or common workloads, the following configuration limits are recommended:


[cols="30,20,30",options="header"]
|===
| Workload characteristics
| Recommended volume limit per node
| Performance degradation when per-node volume limit is exceeded pass:[*]

| Read-intensive or the data can be compressed.
| 150
| 4% of maximum IOPS

| Write-intensive and the data cannot be compressed.
| 60
| 10% of maximum IOPS
|===

pass:[*] System performance is not degraded beyond these percentages regardless of the number of volumes added in excess of the recommended limits.

Because ARP analytics are run in a prioritized sequence, as the number of protected volumes increases, analytics are run on each volume less frequently.

== How automatic Snapshot copies work when ransomware is detected

In order to obtain the best possible recovery point, ARP creates an automatic Snapshot copy as soon as it detects abnormal file activity. However, ARP does not immediately flag an alert; rather, analytics need to run and confirm that the suspicious activity matches a ransomware profile before generating an alert. This process could take up to 60 minutes. If the analytics determines the activity is not suspicious, then an alert is not generated, but the automatically created Snapshot copy remains present on the file system for a minimum of two days.

Beginning with ONTAP 9.11.1, you can control the number and retention period for ARP Snapshot copies that are automatically generated in response to suspected ransomware attacks. Learn how to link:modify-automatic-shapshot-options-task.html[modify options for automatic Snapshot copies].

// 2023 Jan 19, ontap-issues-774
// 2023 Jan 11, Jira ONTAPDOC-806
// 2023 Jan 10, ontap-issues-753
// 2022 Nov 06, Jira ONTAPDOC-646
// 2022-08-25, BURT 1499112
// 2022-08-01, BURT 1494233
// 2022-06-07, BURT 1482782
// 2022-05-04, Jira IE-517
// 2022-03-30, Jira IE-517
// 2022-03-22, ontap-issues-419
// 2022-02-18, ontap-issues-371
// 2021-11-29, ontap-issues 255 & 257
// 2021-10-29, Jira IE-353
