---
sidebar: sidebar
permalink: anti-ransomware/use-cases-restrictions-concept.html
keywords: anti-ransomware use cases and restrictions, anti-ransomware performance and frequency considerations, anti-ransomware workloads, anti-ransomware volume requirements, anti-ransomware performance, volumes, anti-ransomware encryption, anti-ransomware system configurations
summary: In the current release, ransomware protection is most suitable in NAS environments. Support for other environments will be available in future releases.
---

= Anti-ransomware use cases and considerations
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
In the current release, ransomware protection is most suitable in NAS environments. Support for other environments will be available in future releases.

Suitable workloads:

* Databases on NFS storage
* Windows or Linux home directories
+
Because users could create files with extensions that weren’t detected in the learning period, there is greater possibility of false positives in this workload.
* Images and video
+
For example, health care records and Electronic Design Automation (EDA) data.

Unsuitable workloads:

* Workloads with a high frequency of file create or delete (hundreds of thousands of files in few seconds; for example, test/dev workloads)
* The anti-ransomware feature depends on the ability to recognize an unusual surge in file create or delete activity. If the application itself is the source of the file activity, it cannot be effectively distinguished from ransomware activity
* Workloads where the application or the host encrypts data
The anti-ransomware feature depends on distinguishing incoming data as encrypted or unencrypted. If the application itself is encrypting the data, then the effectiveness of the feature is reduced. However, the feature can still work based on file activity (create, delete, and overwrite) and file type.

Unsupported system configurations:

* SAN environments
* ONTAP S3 environments
* VMDKs on NFS
* Cloud Volumes ONTAP
* Cloud Volume Services for AWS and Google Cloud
* Azure NetApp Files
* Amazon FSx for ONTAP
* ONTAP Select

Volume requirements:

* Less than 100% full
* Junction path must be active

Unsupported volume types:

* offline volumes
* restricted volumes
* Snaplock volumes
* SnapLock volumes
* FlexGroup volumes
* FlexCache volumes
* SAN-only volumes
*	volumes of stopped storage VMs
*	root volumes of storage VMs
*	data protection volumes

== Anti-ransomware performance and frequency considerations

The anti-ransomware feature can have a minimal impact on system performance as measured in throughput and peak IOPS. The impact of the anti-ransomware feature is highly dependent on volume workloads. For most typical or common workloads, the following configuration limits are recommended:

* No more than 50 volumes per node if the workload is either read-intensive or the data can be compressed.
* No more than 20 volumes per node if the workload is write-intensive and the data cannot be compressed.

Because anti-ransomware analytics are run in a prioritized sequence, as the number of protected volumes increases, analytics are run on each volume less frequently.

== How automatic Snapshot copies work when ransomware is Detected

In order to obtain the best possible recovery point, the anti-ransomware feature creates a Snapshot copy as soon as it detects that suspicious file contents are being written. However, the anti-ransomware feature does not immediately flag an alert; rather, analytics need to run and confirm that the activity is suspected ransomware before generating an alert. This process could take up to 60 minutes. If the analytics determines the activity is not suspicious, then an alert is not generated, but the automatically created Snapshot copy remains present on the file system for a minimum of two days.

// 2022102-18, ontap-issues-371
// 2021-11-29, ontap-issues 255 & 257
// 2021-10-29, Jira IE-353
