---
sidebar: sidebar
permalink: snapmirror-active-sync/cloud-mediator-slow-troubleshoot-task.html
keywords: troubleshooting, SM-BC, SMBC, Cloud Mediator, network, latency, snapmirror active sync
summary: Adding the ONTAP Cloud Meditor fails with an error that says the ping latency is higher than the recommended latency.
---

= ONTAP Cloud Mediator is reachable but responding slowly
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Use the following information if the ONTAP Cloud Meditor fails with an error that says the ping latency is higher than the recommended latency.

.Issue:

System Manager:
The Cloud Mediator service is reachable but it's responding slowly. 

CLI:
The `mediator add` command fails with the error: 
`Error: command failed: The ping latency of the BlueXP cloud server is <x> ms which is higher than twice the recommended latency of 200 ms.`

.Cause:

The clusters might not be located in proximity to the NetApp Console cloud or there are network path bottlenecks.

.Solution:

* Check the geographical location and proximity to the NetApp Console cloud (US East).
* Optimize network path or address bottlenecks.
* Measure round trip time (RTT) using network tools, and reduce latency to within recommended limits.
* Use an HTTP proxy to improve performance.

See link:cloud-mediator-config-task.html[Configure the ONTAP Cloud Mediator and clusters for SnapMirror active sync].

// 2025-Sept-10, BLUEXPDOC-872
// 2025-June-30, ONTAPDOC-2763