---
sidebar: sidebar
permalink: snapmirror-active-sync/convert-relationships-tasks.html 
keywords: SM-BC, SMBC, convert, Synchronous SnapMirror, zero RPO, zero recovery time objective, zero RTO, existing, snapmirror active sync
summary: You can convert an existing zero recovery point protection (zero RPO) Synchronous SnapMirror relationship to an SM-BC zero RTO Synchronous SnapMirror consistency group relationship.
---
= Convert existing relationships to SM-BC relationships
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
If you have an existing Synchronous SnapMirror relationship between a source and destination cluster, you can convert it to an SM-BC relationship. This allows you to associate the mirrored volumes with a consistency group, ensuring zero RPO across a multi-volume workload. Additionally, you can retain existing SnapMirror snapshots if you need to revert to a point in time prior to establishing the SM-BC relationship. 

.Before you begin

* A zero RPO Synchronous SnapMirror relationship must exist between the primary and secondary cluster.
* All LUNs on the destination volume must be unmapped before the zero RTO SnapMirror relationship can be created.
* SM-BC only supports SAN protocols (not NFS/CIFS). Ensure no constituent of the consistency group is mounted for NAS access.

.About this task

* You must be a cluster and SVM administrator on the primary and secondary clusters.
* You cannot convert zero RPO to zero RTO sync by changing the SnapMirror policy.
* You must ensure the LUNs are unmapped before issuing the `snapmirror create` command.
+
If existing LUNs on the secondary volume are mapped and the `AutomatedFailover` policy is configured, the `snapmirror create` will trigger an error. 

.Steps

. From the secondary cluster, perform a SnapMirror update on the existing relationship:
+
`destination::>snapmirror update -destination-path vs1_dst:vol1`

. Verify that the SnapMirror update completed successfully:
+
`destination::>snapmirror show`

. Quiesce each of the zero RPO synchronous relationships:
+
`destination::>snapmirror quiesce -destination-path vs1_dst:vol1`
+
`destination::>snapmirror quiesce -destination-path vs1_dst:vol2`

. Delete each of the zero RPO synchronous relationships:
+
`destination::>snapmirror delete -destination-path vs1_dst:vol1`
+
`destination::>snapmirror delete -destination-path vs1_dst:vol2`

. Release the source SnapMirror relationship but retain the common Snapshot copies:
+
`source::>snapmirror release -relationship-info-only true -destination-path vs1_dst:vol1`
+
`source::>snapmirror release -relationship-info-only true -destination-path vs1_dst:vol2`

. Create a group zero RTO Synchronous Snapmirror relationship:
+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol1:@vol1,vol2:@vol2 -policy AutomatedFailover`

. Resynchronize the consistency group:
+
`destination::> snapmirror resync -destination-path vs1_dst:/cg/cg_dst`

. Rescan host LUN I/O paths to restore all paths to the LUNs.

//BURTs 1443418 & 1443978, 9 Dec 2021