---
sidebar: sidebar
permalink: snapmirror-active-sync/delete-fails-takeover-task.html
keywords: troubleshooting, SM-BC, SMBC, SnapMirror, delete, takeover, consistency group, snapmirror active sync
summary: When ONTAP 9.9.1 is installed on a cluster, executing the `snapmirror delete` command fails when an SnapMirror active sync consistency group relationship is in takeover state.
---

= SnapMirror delete operation fails in takover state
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]

.Issue:

When ONTAP 9.9.1 is installed on a cluster, executing the `snapmirror delete` command fails when an SnapMirror active sync consistency group relationship is in takeover state.

.Example:
....
C2_cluster::> snapmirror delete  vs1:/cg/dd

Error: command failed: RPC: Couldn't make connection
....

.Solution
When the nodes in an SnapMirror active sync relationship are in takeover state, perform the SnapMirror delete and release operation with the "-force" option set to true.

.Example:
....
C2_cluster::> snapmirror delete  vs1:/cg/dd -force true

Warning: The relationship between source "vs0:/cg/ss" and destination
         "vs1:/cg/dd" will be deleted, however the items of the destination
         Consistency Group might not be made writable, deletable, or modifiable
         after the operation. Manual recovery might be required.
Do you want to continue? {y|n}: y
Operation succeeded: snapmirror delete for the relationship with destination "vs1:/cg/dd".
....

//BURT 1386588
