---
sidebar: sidebar
permalink: snapmirror-active-sync/index.html
keywords: SM-BC, SMBC, failover, terms, benefits, snapmirror active sync
summary: Beginning with ONTAP 9.8, you can use SnapMirror active sync (previously known as SnapMirror Business Continuity) to protect applications with LUNs, enabling applications to fail over transparently, ensuring business continuity in case of a disaster.
---
= SnapMirror active sync overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
SnapMirror active sync (previously known as SnapMirror Business Continuity [SM-BC]), enables business services to continue operating even through a complete site failure, supporting applications to fail over transparently using a secondary copy. Manual intervention nor custom scripting are required to trigger a failover with SnapMirror active sync. 

SnapMirror active sync is available beginning with ONTAP 9.8. SnapMirror active sync is supported on AFF clusters or All-Flash SAN Array (ASA) clusters. Primary and secondary clusters must be of the same type: either ASA or AFF. SnapMirror active sync protects applications with iSCSI or FCP LUNs.

== Benefits

SnapMirror active sync provides the following benefits:

* Continuous availability for business-critical applications.
* Ability to host critical applications alternately from primary and secondary site.
* Simplified application management using consistency groups for dependent write-order consistency.
* The ability to test failover for each application.
* Instantaneous creation of mirror clones without impacting application availability.
* LUN identity remains the same, so the application sees them as a shared virtual device.
* The ability to reuse secondary clusters with flexibility to create instantaneous clones for application usage for dev-test, UAT or reporting purposes without impacting application performance or availability. 
* Beginning with ONTAP 9.11.1, SnapMirror active sync supports xref:../data-protection/restore-single-file-snapshot-task.html[single-file SnapRestore]. 
* Beginning with ONTAP 9.14.1, SnapMirror active sync supports Windows Failover Clustering and link:https://kb.netapp.com/onprem/ontap/da/SAN/What_are_SCSI_Reservations_and_SCSI_Persistent_Reservations[SCSI 3 persistent reservations^], improving high availability. 

SM-BC allows you to protect your data LUNs, which enables applications to fail over transparently for the purpose of business continuity in the event of a disaster.  


== Key concepts

SnapMirror Business Continuity (SM-BC) utilizes features such as consistency groups and the ONTAP Mediator to ensure your data is replicated and served even in the event of a disaster scenario. When planning your SM-BC deployment, it is important to understand the essential concepts in SM-BC and its architecture. 

.Consistency group

A consistency group is a collection of FlexVol volumes that provide a consistency guarantee for the application workload that must be protected for business continuity.

The purpose of a consistency group is to take simultaneous snapshot images of multiple volumes, thus ensuring crash-consistent copies of a collection of volumes at a point in time. A consistency group ensures all volumes of a dataset are quiesced and then snapped at precisely the same point in time. This provides a data-consistent restore point across volumes supporting the dataset. A consistency group thereby maintains dependent write-order consistency. If you decide to protect applications for business continuity, the group of volumes corresponding to this application must be added to a consistency so a data protection relationship is established between a source and a destination consistency group. The source and destination consistency must contain the same number and type of volumes.  

To learn more about consistency groups, see link:../consistency-groups/index.html[Consistency groups overview].

.Constituent

An individual volume or LUN that is part of a consistency group, which is protected by the SM-BC relationship. 

.ONTAP Mediator

The ONTAP Mediators receives health information about peered ONTAP clusters and nodes, orchestrating between the two and determining if each node/cluster is healthy and running. ONTAP Mediator provides the health information about: 

* Peer ONTAP clusters
* Peer ONTAP cluster nodes 
* Consistency groups (which is the failover unit); for each consistency group, the following information is provided: 
** Replication state: Uninitialized, In Sync, or Out of Sync 
** Which cluster hosts the primary copy 
** Operation context (used for planned failover) 

With this ONTAP Mediator health information, clusters can differentiate between distinct types of failures and determine whether to perform an automated failover. ONTAP Mediator is one of the three parties in the SM-BC quorum along with both ONTAP clusters (primary and secondary). To reach consensus, at least two parties in the quorum must agree to a certain operation.  

Learn more about the link:../mediator/index.html[ONTAP Mediator^].

.Planned failover

A manual operation to change the roles of copies in a SM-BC relationship. The primary sites becomes the secondary, and the secondary becomes the primary.

.Automatic unplanned failover (AUFO)

An automatic operation to perform a failover to the mirror copy. The operation requires assistance from Mediator to detect that the primary copy is unavailable.

.Out of Sync (OOS)

When the application I/O is not replicating to the secondary storage system, it will be reported as **out of sync**. An out of sync status means the secondary volumes are not synchronized with the primary (source) and that SnapMirror replication is not occurring. 

If the mirror state is `Snapmirrored`, this indicates a transfer failure or failure due to an unsupported operation.

.Zero RPO

RPO stands for recovery point objective, which is the amount of data loss deemed acceptable during a given time period. Zero RPO signifies that no data loss is acceptable.  

.Zero RTO

RTO stands for recovery time objective, which is the amount of time that is deemed acceptable for an application to return to normal operations following an outage, failure, or other data loss event. Zero RTO signifies that no amount of downtime is acceptable. 

// 16 may 2023, ONTAPDOC-1004
// 16 may 2023, ONTAPDOC-883



== Further information 

* link:https://www.netapp.com/pdf.html?item=/media/21888-tr-4878.pdf[TR-4878: SnapMirror Business Continuity^]

// ontapdoc-1219, 2023 oct 12
// ontapdoc-883, 7 march 2023
// 7 april 2022, BURT 1459617