---
sidebar: sidebar
permalink: snapmirror-active-sync/limits-reference.html
keywords: SM-BC, SMBC, restrictions, consistency group, endpoint limits, solaris, aix, hp-ux, fanout, snapmirror active sync
summary: There are several additional restrictions and limitations when using SnapMirror active sync.
---
= Object limits for SnapMirror active sync
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
When preparing to use SnapMirror active sync, be aware of the following object limits. 

== Consistency groups in a cluster

Consistency group limits for a cluster with SnapMirror active sync are calculated based on relationships and depend on the version of ONTAP used. Limits are platform-independent. 

[options="header"]
|===
| ONTAP version | Maximum number of relationships
| ONTAP 9.11.1 and later | 50
| ONTAP 9.10.1 | 20
| ONTAP 9.9.1 | 5
|===

== Volumes per consistency group

The maximum number of volumes per consistency group with SnapMirror active sync is platform independent. 

[options="header"]
|===
| ONTAP version | Maximum number of volumes supported in a consistency group relationship
| ONTAP 9.15.1 and later | 80 
| ONTAP 9.10.1-9.14.1 | 16 
| ONTAP 9.9.1 | 12 
|===

== Volumes

Volume limits in SnapMirror active sync are calculated based on the number of endpoints, not the number of relationships. A consistency group with 12 volumes contributes 12 endpoints on both the primary and secondary cluster. Both SnapMirror active sync and SnapMirror Synchronous relationships contribute to the total number of endpoints.

The maximum endpoints per platform are included in the following table.

[options="header"]
|===
| S. No |Platform 3+| Endpoints per HA for SnapMirror active sync 3+| Overall sync and SnapMirror active sync endpoints per HA
|
|
|ONTAP 9.9.1 |ONTAP 9.10.1 |ONTAP 9.11.1 and later |ONTAP 9.9.1 |ONTAP 9.10.1 |ONTAP 9.11.1 and later
|1
|AFF
|60
|200
|400
|80
|200
|400
|2
|ASA
|60
|200
|400
|80
|200
|400
|===

== SAN object limits

SAN object limits are included in the following table. The limits apply regardless of the platform.

|===
|Object in an SnapMirror active sync relationship |Count

|LUNs per volume
|256
|LUN maps per node
a| * 4096 (ONTAP 9.10 and later)
* 2048 (ONTAP 9.9.1 and earlier)

|LUN maps per cluster
a| * 8192 (ONTAP 9.10 and later)
* 4096 (ONTAP 9.9.1 and earlier)
|LIFs per SVM (with at least one volume in an SnapMirror active sync relationship)
|256
|Inter-cluster LIFs per node
|4
|Inter-cluster LIFs per cluster
|8
|===

.Related information 
* link:https://hwu.netapp.com/[Hardware Universe^]
* link:../consistency-groups/limits.html[Consistency group limits^]

// 6 may 2024, ontapdoc-1478
// 2024 Feb 08, Git Issue 1173
// 2023 Nov 22, Git Issue 1173
// ontapdoc-915, 16 april 2023
// ontapdoc-804, 1 april 2023
// BURT 1451494, 2022-02-11
// BURT 1387138
// BURT 1431859, 1 dec 2021
// issue #326, 19 dec 2022
// BURT 1449057, 27 JAN 2022
// BURT 1459617 and 1451134, 10 March 2022
// ontap-issues-#604, 31 august 2022
// ONTAPDOC-883, 6 march 2023