---
sidebar: sidebar
permalink: snapmirror-active-sync/network-port-requirements.html
keywords: SM-BC, SMBC, SM-AS, restrictions, firewall, network ports, snapmirror active sync
summary: ONTAP SnapMirror active sync network port requirements
---
= Network port requirements
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
SnapMirror active sync replication has several network port requirements.

For example, each node involved in replication needs to monitor the health of its parter nodes, control replication activity, and the data itself must be replicated. Furthermore, the ONTAP Mediator or ONTAP Cloud Mediator needs to communicate with all nodes in order to provide quorum services and assist with failover. All of these functions have differing endpoint and port requirements. 

In most cases, SnapMirror active sync replication will operate on an internal network with no port or destination-based restrictions. If IP traffic is restricted by firewalls, routers, network toplogy, or other mechanisms, the following connectivity requirements should be validated.

== Communication between nodes using intercluster/peer links

[options="header"]
|===
| Port | Source | Direction | Destination | Purpose
| 3260/tcp| intercluster LIFs | both | intercluster LIFs | LUN consensus
a| 11104/tcp +
11105/tcp | intercluster LIFs | both | intercluster LIFs a| Intercluster communication sessions and SnapMirror data transfer
| 443/tcp (https) | intercluster LIFs | both | intercluster LIFs| Intercluster management traffic
| 10000/tcp a| cluster-mgmt LIFs + 
node-mgmt LIFs | both | optional | Communication with Active IQ Unified Manager
|===

== Communication between the mediator and cluster nodes

[options="header"]
|===
| Port | Source | Direction | Destination | Purpose
| 22/tcp (ssh) | Management host | Inbound | ONTAP Mediator | ONTAP Mediator management
| 31784/tcp (https) | cluster-mgmt LIFs| Inbound | ONTAP Mediator | REST API 
| 31784/tcp | node-mgmt LIFs| Inbound | ONTAP Mediator | ONTAP Mediator quorum service 
|===

// ontapdoc-9.19.1. 4/15/2026