---
sidebar: sidebar
permalink: snapmirror-active-sync/prerequisites-reference.html
keywords: SM-BC, SMBC, prerequisites, planning, software, hardware, licensing, protocols, network, snapmirror active sync
summary: There are several prerequisites that you should consider as part of planning a SnapMirror active sync solution deployment.
---
= Prerequisites for SnapMirror active sync in ONTAP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/


[.lead]
When planning your SnapMirror active sync deployment, ensure you have met the various hardware, software, and system configuration requirements. 

== Hardware

The following table outlines the supported NetApp cluster configurations. 

[cols="25,25,25,25"]
|===

h| Cluster type h| Supported models h| Supported features h| Nodes supported

a| AFF
a| A-Series, C-Series
a| Automated Failover Duplex (Symmetric Active/Active), Automated Failover (Asymmetric Active/Active)
a| Two-node or four-node clusters ^1^
a| All San Array (ASA)
a| A-Series, C-Series
a| Automated Failover Duplex (Symmetric AA), Automated Failover (Asymmetric AA)
a| Two-node or four-node clusters ^1^
a| ASA r2 
a| -
a| Automated Failover Duplex (Symmetric AA)
a| Two-node high availability (HA) clusters
|===

// Start snippet: numbered list - 1 entry
// No placeholders
. Support for four-node clusters is available beginning with ONTAP 9.16.1 and requires Symmetric AA.
// End snippet

The table below outlines the capability for replication between cluster types.

[cols="33,33,33"]
|===

h| Cluster type 1 h| Cluster type 2 h| Replication supported?

a| A-Series
a| C-Series
a| Yes 
a| AFF
a| ASA
a| No 
a| ASA (legacy) ^1^
a| ASA r2
a| ASA (legacy)
a| ASAr2
a| No
|===

// Start snippet: numbered list - 1 entry
// No placeholders
. For more information on the cluster types ASA supports, see link:https://docs.netapp.com/us-en/ontap/asa/support-limitations.html[All-Flash SAN Array configuration limits and support^].
// End snippet

== Software
* ONTAP 9.9.1 or later
* ONTAP Mediator 1.2 or later
* A Linux server or virtual machine for the ONTAP Mediator running one of the following:

include::../_include/mediator-linux-support.adoc[]

== Licensing

* SnapMirror synchronous license must be applied on both clusters.
* SnapMirror license must be applied on both clusters.
+
[NOTE]
If your ONTAP storage systems were purchased before June 2019, see link:https://mysupport.netapp.com/site/systems/master-license-keys[NetApp ONTAP Master License Keys^] to get the required SnapMirror synchronous license.

== Networking environment

* Inter-cluster latency round trip time (RTT) must be less than 10 milliseconds.
* Beginning with ONTAP 9.14.1, link:https://kb.netapp.com/onprem/ontap/da/SAN/What_are_SCSI_Reservations_and_SCSI_Persistent_Reservations[SCSI-3 persistent reservations] are supported with SnapMirror active sync.

== Supported protocols

* Only SAN protocols are supported (not NFS/SMB).
* Only Fibre Channel and iSCSI protocols are supported. 
* The default IPspace is required by SnapMirror active sync for cluster peer relationships. Custom IPspace is not supported.

== NTFS Security Style

NTFS security style is *not* supported on SnapMirror active sync volumes.

== ONTAP Mediator
* The ONTAP Mediator must be provisioned externally and attached to ONTAP for transparent application failover.
* To be fully functional and to enable automatic unplanned failover, the external ONTAP mediator should be provisioned and configured with ONTAP clusters.
* The ONTAP Mediator must be installed in a third failure domain, separate from the two ONTAP clusters.
* When installing the ONTAP Mediator, you should replace the self-signed certificate with a valid certificate signed by a mainstream reliable CA.
* For more information about the ONTAP Mediator, see link:../mediator/index.html[Prepare to install the ONTAP Mediator service].

== Other prerequisites 

* SnapMirror active sync relationships are not supported on read-write destination volumes. Before you can use a read-write volume, you must convert it to a DP volume by creating a volume-level SnapMirror relationship and then deleting the relationship. For details, see link:convert-active-sync-task.html[Convert an existing SnapMirror relationships to SnapMirror active sync].
* Storage VMs using SnapMirror active sync cannot be joined to Active Directory as a client computed.  

== Further information 
* link:https://hwu.netapp.com/[Hardware Universe^]
* link:../mediator/mediator-overview-concept.html[ONTAP Mediator overview^]

// 11 Feb 2025, ONTAPDOC-2670
// 20 dec 2024 issue #1506
// 2024 Nov 21, ONTAPDOC-2516
// 2024 october 29, ONTAPDOC-2514/ontap-issues #1509
// 17 Oct 2024, ONTAPDOC-2073
// 8 may 2024, ONTAPDOC-1881/1221
// 2023 july 24, ontap-issues-862
// 2023 9 june, ontap-issues-958
// 2021 Nov 2, BURT 1419781
// 2021 Nov 8, ontap-issues #218
// 16nov2021, BURT 1436974
// 25 april 2022, ontap-issues #469
// 22 june 2022, ontap-issues #540
