---
sidebar: sidebar
permalink: snapmirror-active-sync/protect-active-task.html 
keywords: snapmirror active sync, igroup, vmware vmsc, automatedfailoverduplex 
---
= Create active/active protection 
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

= Establish active/active protection 

Beginning with ONTAP 9.15.1, you can utilize SnapMirror active sync's active/active solution for bidirectional support. 

You can convert an existing SnapMirror active sync relationship to active/active or create a new relationship. 

.Before you begin 

* Both clusters must be running ONTAP 9.15.1 or later. 

// what is a uniform vs non-uniform config 

.Steps 
. Modify the SnapMirror policy from `AutomatedFailover` to `AutomatedFailoverDuplex`:
+
`snapmirror modify -destination-path _destination_path_ -policy AutomatedFailoverDuplex`
. Modifying the policy to `AutomatedFailoverDuplex` takes the relationship out of sync and trigger an resync operation. When the resync operation succeeds, birectional sync replication has been established. Confirm the relationship is `Insync`:
+
`snapmirror show -destination-path _destination_path_`
. If the existing hosts are local to cluster-1, add the host to the second cluster and establish connectivity with respective access to each cluster depending on the configuration. 

. Delete LUN maps on the Igroups associated with remote hosts. This is required to enable replication on the Igroup.

Note: Also ensure the Igroup does not contain maps for non-replicated LUNs (non SMBC)
+
`SiteB::> lun mapping delete -vserver vsB -igroup ig2 -path <>`
. Modify the initiator configuration for existing hosts to set the proximal path for initiators on the local cluster. Initiator replication effectively inverses the host proximity on the remote cluster.
+
`SiteA::> igroup initiator add-proximal-vserver -vserver _Svm_name_ -initiator _host_ -proximal-vserver _server_`

. Add a new Igroup config/Initiators for the new hosts and set the host proximity for host affinity to its local site. For uniform config, enable Igroup replication which will replicate the config and inverse the host locality on the remote cluster. For Non-uniform config, a new Igroup has to be created if one doesn't exist and Map existing LUNs to this Igroup.
+
**For a uniform configuration:**
``
SiteA::> igroup modify -vserver vsA -igroup ig1 -replication-peer vsB
SiteA::> igroup initiator add-proximal-vserver -vserver vsA -initiator host2 -proximal-vserver vsB
``
+
**For a non-uniform configuration:**
``
SiteB::> igroup create -vserver _svm_name_ -igroup _igroup_name_
SiteB::> igroup add -vserver _svm_name_ -igroup  _igroup_name_ -initiator _host_name_
SiteB::> lun mapping create -igroup  _igroup_name_ -path _path_name_
``
. Discover the paths on the hosts and verify the hosts have an Active/Optimized path to the storage LUN from the preferred cluster
. Deploy the VMSC application and distribute the VM workloads across clusters to achieve required Load balancing


//Uniform config - System Manager
Site B : Remove the Igroup so that igroup replicaton can be enabled as part of change to load balancing mode: Hosts → San Initiator Group - > select the Igroup and delete, enable the checkbox to unmap LUNs
Site B : Edit the existing Failover mode SMBC relationship and select the "AutmatedFailoverDuplex" policy . Once this policy is selected user will get the option to edit the host proxmity and igroup replication bits for the igroups/ initiators assciated with the LUNs that are part of the source and destination CG. Modify igroup replication and host poximity settings.

//Non-Uniform Config - System Manager

Site B : Remove destination igroup: Hosts → San Initiator Group - > select the Igroup and delete, enable the checkbox to unmap LUNs and create new igroup by adding new host: Hosts → San Initiator Group → Add
Site B: Map the new igroup to destination LUNs: Storage → LUNs → Select all destination LUNs → More → Map to Initiator Groups
Site B : Edit the existing Failover mode SMBC relationship and select the "AutmatedFailoverDuplex" policy . Once this policy is selected user will get the option to edit the host proximity of the initiators assciated with the LUNs that are part of the source and destination CG. Modify host proximity settings.

=== new configuration 

1. Create a new SMBC relationship grouping all the volumes constituting the application. Specify the "AutomatedFailOverDuplex" policy to setup the relationship with bi-directional sync replication.

::> snapmirror create -source-path vsA:/cg/cg_src -destination-path vsB:/cg/cg1_dst -cg-item-mappings vol1:@vol1_dp,vol2:@vol2_dp -policy AutomatedFailOverDuplex
2. Wait for the relationship to reach the Snapmirrored, Insync state

::> snapmirror show -destination-path vsB:/cg/cg1_dst
                                                                                   Progress
Source            Destination Mirror       Relationship   Total             Last
Path        Type  Path        State        Status         Progress  Healthy Updated
----------- ---- ------------ ------------ -------------- --------- ------- --------
vsA:/cg/scg1 XDP vsB:/cg/dcg1 Snapmirrored Insync -      true   -
3. Setup the host connectivity with respective access to each cluster, depending on Uniform/Non-Uniform access configurations

4. Setup the Igroup configuration. For uniform config, set the preferred paths for Initiators on the local Cluster and specify the option to replicate the config to the peer cluster with inverse affinity.

Uniform Config:

SiteA::> igroup create -vserver vsA -igroup igroup1 -replication-peer vsB -initiators host1 -proximal-vserver local
 
SiteA::> igroup add -vserver vsA -igroup igroup1 -initiators host2 -proximal-vserver peer
Non-Uniform Config:

# primary site
SiteA::> igroup create -vserver vsA -igroup igroup1 -initiators host1
 
# secondary site
SiteB::> igroup create -vserver vsB -igroup igroup2 -initiators host2
5. Map the LUNs to the Igroups on the primary cluster. If the Igroup is setup for replication, the LUN map will be replicated to the secondary cluster automatically. For non-uniform config, the LUNs have to be mapped explicitly on both clusters.

Uniform Config:

SiteA::> lun mapping create -igroup igroup1 -path <>
Non-Uniform Config:

SiteA::> lun mapping create -igroup igroup1 -path <>
 
SiteB::> lun mapping create -igroup igroup2 -path <>
6. Discover the paths on the hosts and verify the hosts have an Active/Optimized path to the storage LUN from the preferred cluster

7. Deploy the VMSC application and distribute the VM workloads across clusters to achieve required Load balancing

6.2.4.1. System Manager UI Workflow Steps
In System Manager this workflow can be done using the following steps

In System Manager LUNs or CG with LUNs cannot be provisioned without specifying Igroups.

So the GUI steps will be.

Uniform config

Site A:

Create CG using new LUNs, Storage → Consistency Groups → Add using New LUNs . All the below details can be specified in single workflow.
Specify CG name, and details for LUNs
Specify Host intiators to create igroup igroup1 by adding hosts host1 and host2
Select "Enable Snapmirror" checkbox and choose "AutomatedFailoverDuplex" policy
Once this policy is selected user will get the option to edit the host proximity and igroup replication
For uniform config Select "Replicate initiator groups" checbox to replicate the igroups.
Set proximal vservers for host1 and host2 by clicking on edit proximal settings
On click of save :
New CG created by provisioning new LUNs
Igroup igroup1 is created with inititators host1 and host2
New LUNs are mapped to igroup1
SMBC relationship is created.
The proximal vservers are set for host1 and host2 and replication enabled for igroup1
Once the LUNs are replicated to the destination, LUNs on the destination is automatically mapped to igroup1 in destination