---
sidebar: sidebar
permalink: snapmirror-active-sync/remove-mediator-task.html
keywords: SM-BC, SMBC, removing, uninstalling, Mediator, Cloud Mediator, snapmirror active sync
summary: If you want to remove an existing ONTAP Mediator or ONTAP Cloud Mediator configuration from your ONTAP clusters, you can do so by using the snapmirror mediator remove command.
---

= Remove ONTAP Mediator or ONTAP Cloud Mediator
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
If you want to remove an existing ONTAP Mediator or ONTAP Cloud Mediator configuration from your ONTAP clusters,  you can do so by using the `snapmirror mediator remove` command. For example, you can use only one type of Mediator at a time, so you must remove one instance before you install the other. 


.Steps
You can remove ONTAP Mediator or ONTAP Cloud Mediator by completing one of the following steps.

[role="tabbed-block"]
====

.ONTAP Mediator
--
. Remove ONTAP Mediator:
+
`snapmirror mediator remove -mediator-address <address> -peer-cluster <peerClusterName>`
+
Example:
+
----
snapmirror mediator remove -mediator-address 12.345.678.90 -peer-cluster cluster_xyz
----
--

.ONTAP Cloud Mediator
--

. Remove ONTAP Cloud Mediator:
+
`snapmirror mediator remove -peer-cluster <peerClusterName> -type cloud`
+
Example:
+
----
snapmirror mediator remove -peer-cluster cluster_xyz -type cloud
----
--
====


.Related information
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-mediator-remove.html[snapmirror mediator remove^]


// 2025-July-1, ONTAPDOC-2763
// 2025 June 21, ONTAPDOC-2960