---
sidebar: sidebar
permalink: snapmirror-active-sync/remove-configuration-task.html
keywords: SM-BC, SMBC, removing, protection relationship, snapmirror active sync
summary: You can remove zero RTO Synchronous SnapMirror protection and delete the SM-BC relationship configuration.
---

= Remove an SnapMirror active sync configuration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
If you no longer require zero RTO Synchronous SnapMirror protection, you can delete your SnapMirror active sync relationship. 

.About this task

* Before you delete the SnapMirror active sync relationship, all LUNs in the destination cluster must be unmapped.
* After the LUNs are unmapped and the host is rescanned, the SCSI target notifies the hosts that the LUN inventory has changed. The existing LUNs on the zero RTO secondary volumes change to reflect a new identity after the zero RTO relationship is deleted. Hosts discover the secondary volume LUNs as new LUNs that have no relationship to the source volume LUNs.
* The secondary volumes remain DP volumes after the relationship is deleted. You can issue the `snapmirror break` command to convert them to read/write.
* Deleting the relationship is not allowed in the failed-over state when the relationship is not reversed.

.Steps

. From the secondary cluster, remove the SnapMirror active sync consistency group relationship between the source endpoint and destination endpoint:
+
`destination::>snapmirror delete -destination-path vs1_dst:/cg/cg_dst`

. From the primary cluster, release the consistency group relationship and the Snapshot copies created for the relationship:
+
`source::>snapmirror release -destination-path vs1_dst:/cg/cg_dst`
+
. Perform a host rescan to update the LUN inventory.
+ 
. Beginning with ONTAP 9.10.1, deleting the SnapMirror relationship does not delete the consistency group. If you want to delete the consistency group, you must use System Manager or the ONTAP REST API. See xref:../consistency-groups/delete-task.adoc[Delete a consistency group] for more information.