---
sidebar: sidebar
permalink: snapmirror-active-sync/troubleshoot-site-a-mediator-task.html
keywords: SM-BC, SMBC, troubleshooting, connectivity, consensus, snapmirror active sync
summary: Troubleshooting link down between Site A and the ONTAP Mediator down and Site B down.
---
= Link between Site A and mediator down and Site B down
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
When using SnapMirror active sync, you may lose connectivity between the ONTAP Mediator or your peered clusters. You can diagnose the issue by checking the connection, availability, and consensus status of the different parts of the SnapMirror active sync relationship then forcefully resuming connection.

.Determining the cause

[cols=3,options="header"]
|===
| What to check | CLI command | Indicator
| Mediator from Site A | `snapmirror mediator show` | The connection status displays as `unreachable` 
| Site B connectivity | `cluster peer show` | Availability displays as `unavailable` 
| Consensus status of the SnapMirror active sync volume | `volume show _volume_name_ -fields smbc-consensus` | The `sm-bc consensus` field displays `Awaiting-consensus`
|===

For additional information about diagnosing and resolving this issue, refer to the Knowledge Base article link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Link_between_Site_A_and_Mediator_down_and_Site_B_down_when_using_SM-BC[Link between Site A and Mediator down and Site B down when using SnapMirror active sync^].

// 1 april 2022, issue #440