---
sidebar: sidebar
permalink: snapmirror-active-sync/use-cases-concept.html
keywords: SM-BC, SMBC, overview, benefits, use cases, architecture, snapmirror active sync
summary: Beginning with ONTAP 9.8, you can use SM-BC to protect applications with LUNs, enabling applications to fail over transparently, ensuring business continuity in case of a disaster.
---
= Use cases for SnapMirror active sync
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The demands of a globally connected business environment demand rapid recovery of business-critical application data with zero data loss in the event of a disruption such as a cyber attack, power outage, or natural disaster. These demands are heightened in arenas such as finance and those adhering to regulatory mandates such as the General Data Protection Regulation (GDPR).  

SnapMirror active sync provides the following use cases: 

.Application deployment for zero recovery time object (RTO)
In a SnapMirror active sync deployment, you will have a primary and secondary cluster. A LUN in the primary cluster (`1LP`) will have a mirror (`L1s`) on the secondary; both LUNs share the same serial ID and are reported as read-write LUNs to the host. Read and write operations, however, are only serviced to the primary LUN, `1LP`. Any writes to the mirror `L1S` are served by proxy. 

.Application deployment for zero RTO or TAF 
TAF is based on host MPIO software-based path failover to achieve non-disruptive access to the storage. Both LUN copies--for example, primary (L1P) and mirror copy (L1S)--have the same identity (serial number) and are reported as read-writable to the host. However, reads and writes are serviced only by the primary volume. I/Os issued to the mirror copy are proxied to the primary copy. The host's preferred path to L1 is VS1:N1 based on asymmetric logical unit access (ALUA) access state Active Optimized (A/O). ONTAP Mediator is required as part of the deployment, primarily to perform failover (planned or unplanned) in the event of a storage outage on the primary. 

SnapMirror active sync uses ALUA, a standard SCSI mechanism that allows an application host multipathing software with paths advertised with priorities and access availability for the application host communication with the storage array. ALUA marks active optimized paths to the controllers owning the LUN and others as active non-optimized paths, used only if the primary path fails.  

.Disaster scenario
Synchronously replicate multiple volumes for an application between sites at geographically dispersed locations. You can automatically failover to the secondary copy in case of disruption of the primary, thus enabling business continuity for tier one applications. When the site hosting the primary cluster experiences a disaster, the host multipathing software marks all paths through the cluster as down and uses paths from the secondary cluster. The result is a non-disruptive failover enabled by ONTAP Mediator to the mirror copy. 

.VMware vMSc deployments 

VMWare vMSc requires simultaneous access so the VMs can be failed over to other site without any performance overhead.

What vMSc requires is a stretched datastore which can provide optimized local read/write access from both sites. To achieve that we need to serve IO locally with bi-directional replication and ALUA access characteristics to be site local aware as shown in the below diagram. Henceforth called Load balancing mode.

SQL Failover Cluster + WSFC allows high availability for a SQL server instance. Key point for SQL with WSFC is that it is a active/standby config where WSFC will failover SQL server instance automatically if the node hosting the instance were to become unavailable. Think of 2 Data Centers (DCs) where first DC has 2 ONTAP controller nodes and second has 2 ONTAP controller nodes. SQL server instance is configured for SQL failover cluster and all 4 ONTAP controller nodes are part of a single WSFC cluster. SM-BC provides underlying storage to both DC1 and DC2 using sync replication.

A SQL server instance can be failed over within the 2 ONTAP controller nodes in a single DC or from DC1 to DC2. SM-BC Symmetric A/A is not particularly helpful because in steady state writes will happen only from 1 site (DC1 or DC2). However, if SQL server instance is failed over to other DC, SM-BC should support local I/O access. DC/Site disaster - both WSFC failover and SM-BC failover will happen, so that should not be an issue.

.Windows failover 
SnapMirror active sync provides flexibility with easy-to-use application-level granularity and automatic failover. SM-BC uses proven SnapMirror Synchronous (SM-S) replication over IP network to replicate data at high speeds over LAN or WAN, to achieve high data availability and fast data replication for your business-critical applications such as Oracle, Microsoft SQL Server, and so on, in both virtual and physical environments. SM-BC enables mission-critical business services to continue operating even through a complete site failure, with TAF to the secondary copy. No manual intervention or no additional scripting are required to trigger this failover. 


