---
sidebar: sidebar
permalink: snapmirror-active-sync/use-cases-concept.html
keywords: SM-BC, SMBC, overview, benefits, use cases, architecture, snapmirror active sync
summary: Beginning with ONTAP 9.8, you can use SnapMirror active sync (previously known as SnapMirror Business Continuity) to protect applications with LUNs, enabling applications to fail over transparently, ensuring business continuity in case of a disaster.
---
= SnapMirror active sync overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]




== Use cases

.Application deployment for zero recovery time object (RTO)
In a SnapMirror active sync deployment, you will have a primary and secondary cluster. A LUN in the primary cluster (`1LP`) will have a mirror (`L1s`) on the secondary; both LUNs share the same serial ID and are reported as read-write LUNs to the host. Read and write operations, however, are only serviced to the primary LUN, `1LP`. Any writes to the mirror `L1S` are served by proxy. 

.Disaster scenario
With SnapMirror active sync, you can synchronously replicate multiple volumes for an application between sites at geographically dispersed locations. You can automatically failover to the secondary copy in case of disruption of the primary, thus enabling business continuity for tier one applications.

Use cases (TME version) 

In today's constantly connected global business environment, organizations want rapid recovery of business-critical application data with zero data loss, following a disruption such as a cyberattack, power outage, equipment failure to natural disaster. Especially, financial organizations have zero tolerance to data loss or application unavailability and must adhere to General Data Protection Regulation (GDPR) and other regulatory mandates.  

 

Organizations can devise an effective business continuity and disaster recovery (BCDR) plan with the following requirements as priority: 

Zero recovery point objective (RPO), to achieve zero data loss enabled by synchronous replication 

Zero recovery time objective (RTO) through Transparent Application Failover (TAF), to prevent disruption of business-critical applications in case of disaster 

 

Windows failover 

SM-BC gives you flexibility with easy-to-use application-level granularity and automatic failover. SM-BC uses proven SnapMirror Synchronous (SM-S) replication over IP network to replicate data at high speeds over LAN or WAN, to achieve high data availability and fast data replication for your business-critical applications such as Oracle, Microsoft SQL Server, and so on, in both virtual and physical environments. SM-BC enables mission-critical business services to continue operating even through a complete site failure, with TAF to the secondary copy. No manual intervention or no additional scripting are required to trigger this failover. 

 

Application deployment for zero RTO or TAF 

TAF is based on host MPIO software-based path failover to achieve nondisruptive access to the storage. Both LUN copies--for example, primary (L1P) and mirror copy (L1S)--have the same identity (serial number) and are reported as read-writable to the host. However, reads and writes are serviced only by the primary volume. I/Os issued to the mirror copy are proxied to the primary copy. The host’s preferred path to L1 is VS1:N1 based on asymmetric logical unit access (ALUA) access state Active Optimized (A/O). ONTAP Mediator is required as part of the deployment, primarily to perform failover (planned or unplanned) in the event of a storage outage on the primary. 

SM-BC uses ALUA, a standard SCSI mechanism that allows an application host multipathing software with paths advertised with priorities and access availability for the application host communication with the storage array. ALUA marks active optimized paths to the controllers owning the LUN and others as active nonoptimized paths, used only if the primary path fails.  


Disaster scenario 

When the site hosting the primary cluster experiences a disaster, the host multipathing software marks all paths through the cluster as down and uses paths from the secondary cluster. The result is a nondisruptive failover enabled by ONTAP Mediator, to the mirror copy for LUN L1 with L1S now converted from a mirror copy to an active copy with the hosts preferred path through VS2:N3. 