---
permalink: smb-hyper-v-sql/create-config-nondisruptive-operations-task.html
sidebar: sidebar
keywords: create, configuration, nondisruptive, operations, hyper, v, sql, server, smb
summary: "There are several ONTAP configuration steps you must perform to prepare for Hyper-V and SQL Server installations that provides nondisruptive operations over SMB."
---
= Create ONTAP configurations for nondisruptive operations with Hyper-V and SQL Server over SMB overview
:icons: font
:imagesdir: ../media/

[.lead]
There are several ONTAP configuration steps you must perform to prepare for Hyper-V and SQL Server installations that provides nondisruptive operations over SMB.

Before you create the ONTAP configuration for nondisruptive operations with Hyper-V and SQL Server over SMB, the following tasks must be completed:

* Time services must be set up on the cluster.
* Networking must be set up for the SVM.
* The SVM must be created.
* Data LIF interfaces must be configured on the SVM.
* DNS must be configured on the SVM.
* Desired names services must be set up for the SVM.
* The SMB server must be created.

.Related information

xref:volume-config-worksheet-reference.html[Plan the Hyper-V or SQL Server over SMB configuration]

xref:licensing-requirements-concept.html[Configuration requirements and considerations]
