---
permalink: smb-hyper-v-sql/enable-disable-vss-shadow-copies-backups-task.html
sidebar: sidebar
keywords: enable, disable, vss, aware, backup, hyper, v, virtual, machine, files, smb, shares, shadow, copy
summary: "If you use a VSS-aware backup application to back up Hyper-V virtual machine files stored on SMB shares, VSS shadow copy must be enabled. You can disable the VSS shadow copy if you do not use VSS-aware backup applications. The default is to enable the VSS shadow copy."
---
= Enable or disable VSS shadow copies for Hyper-V over SMB backups
:icons: font
:imagesdir: ../media/

[.lead]
If you use a VSS-aware backup application to back up Hyper-V virtual machine files stored on SMB shares, VSS shadow copy must be enabled. You can disable the VSS shadow copy if you do not use VSS-aware backup applications. The default is to enable the VSS shadow copy.

.About this task

You can enable or disable VSS shadow copies at any time.

.Steps

. Set the privilege level to advanced:
+
`*set -privilege advanced*`
. Perform one of the following actions:
+
[options="header"]
|===
| If you want VSS shadow copies to be...| Enter the command...
a|
Enabled
a|
`*vserver cifs options modify -vserver _vserver_name_ -shadowcopy-enabled true*`
a|
Disabled
a|
`*vserver cifs options modify -vserver _vserver_name_ -shadowcopy-enabled false*`
|===

. Return to the admin privilege level:
+
`*set -privilege admin*`

.Example

The following commands enable VSS shadow copies on SVM vs1:

----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -shadowcopy-enabled true

cluster1::*> set -privilege admin
----
