---
permalink: smb-hyper-v-sql/index.html
sidebar: sidebar
keywords: smb, cifs, configuration, microsoft, hyper-v, sql, serve
summary: "This content describes ONTAP features that allow you to enable nondisruptive operations for two Microsoft applications over the SMB protocol: Microsoft Hyper-V and Microsoft SQL Server."
---
= SMB configuration for Microsoft Hyper-V and SQL Server overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes ONTAP features that allow you to enable nondisruptive operations for two Microsoft applications over the SMB protocol: Microsoft Hyper-V and Microsoft SQL Server. It includes a conceptual overview, planning guidance, and detailed implementation instructions.

You should use this content if you want to implement SMB nondisruptive operations under the following circumstances:

* Basic CIFS protocol file access has been configured.
* You want to enable SMB 3.0 or later file shares residing in SVMs to store the following objects:
 ** Hyper-V virtual machine files
 ** SQL Server system databases

If you want to create a basic configuration using best practices and ONTAP System Manager, and you do not want a lot of conceptual background, you should choose among the following documentation:

* https://docs.netapp.com/us-en/ontap-sm-classic/smb-config/index.html[SMB configuration]
* https://docs.netapp.com/us-en/ontap-sm-classic/nas-multiprotocol-config/index.html[SMB and NFS multiprotocol configuration]

If you want general information about SMB/CIFS protocol support in ONTAP, you should see the following documentation:

* https://docs.netapp.com/us-en/ontap/smb-admin/index.html[SMB management]

If you require additional configuration or conceptual information, you should choose among the following documentation:

* Networking concepts and detailed implementation procedures
 ** https://docs.netapp.com/us-en/ontap/networking/index.html[Network management]
* Auditing configuration and management using native and external server implementations
 ** https://docs.netapp.com/us-en/ontap/nas-audit/index.html[SMB and NFS auditing and security tracing]
* Technical Reports (TRs), which include additional information about ONTAP technology and interaction with external services
 ** http://www.netapp.com/us/media/tr-4172.pdf[NetApp Technical Report 4172: Microsoft Hyper-V over SMB 3.0 with ONTAP Best Practices]
 ** https://www.netapp.com/us/media/tr-4369.pdf[NetApp Technical Report 4369: Best Practices for Microsoft SQL Server and SnapManager 7.2 for SQL Server with Clustered Data ONTAP]
