---
permalink: smb-hyper-v-sql/nondisruptive-operations-glossary-concept.html
sidebar: sidebar
keywords: key, concepts, nondisruptive, operation, hyper, v, sql, server, smb, configure
summary: "There are certain concepts about nondisruptive operations (NDOs) that you should understand before you configure your Hyper-V or SQL Server over SMB solution."
---
= Key concepts about nondisruptive operations for Hyper-V and SQL Server over SMB
:icons: font
:imagesdir: ../media/

[.lead]
There are certain concepts about nondisruptive operations (NDOs) that you should understand before you configure your Hyper-V or SQL Server over SMB solution.

* *Continuously available share*
+
An SMB 3.0 share that has the continuously available share property set. Clients connecting through continuously available shares can survive disruptive events such as takeover, giveback, and aggregate relocation.

* *Node*
+
A single controller that is a member of a cluster. To distinguish between the two nodes in an SFO pair, one node is sometimes called the _local node_ and the other node is sometimes called the _partner node_ or _remote node_. The primary owner of the storage is the local node. The secondary owner, which takes control of the storage when the primary owner fails, is the partner node. Each node is the primary owner of its storage and secondary owner for its partner's storage.

* *Nondisruptive aggregate relocation*
+
The ability to move an aggregate between partner nodes within an SFO pair in a cluster without interrupting client applications.

* *Nondisruptive failover*
+
See _Takeover_.

* *Nondisruptive LIF migration*
+
The ability to perform a LIF migration without interrupting client applications that are connected to the cluster through that LIF. For SMB connections, this is only possible for clients that connect using SMB 2.0 or later.

* *Nondisruptive operations*
+
The ability to perform major ONTAP management and upgrade operations as well as withstand node failures without interrupting client applications. This term refers to the collection of nondisruptive takeover, nondisruptive upgrade, and nondisruptive migration capabilities as a whole.

* *Nondisruptive upgrade*
+
The ability to upgrade node hardware or software without application interruption.

* *Nondisruptive volume move*
+
The ability to move a volume freely throughout the cluster without interrupting any applications that are using the volume. For SMB connections, all versions of SMB support nondisruptive volume moves.

* *Persistent handles*
+
A property of SMB 3.0 that allows continuously available connections to transparently reconnect to the CIFS server in the event of a disconnection. Similar to durable handles, persistent handles are maintained by the CIFS server for a period of time after communication to the connecting client is lost. However, persistent handles have more resilience than durable handles. In addition to giving the client a chance to reclaim the handle within a 60-second window after reconnecting, the CIFS server denies access to any other clients requesting access to the file during that 60-second window.
+
Information about persistent handles is mirrored on the SFO partner's persistent storage, which allows clients with disconnected persistent handles to reclaim the durable handles after an event where the SFO partner takes ownership of the node's storage. In addition to providing nondisruptive operations in the event of LIF moves (which durable handles support), persistent handles provide nondisruptive operations for takeover, giveback, and aggregate relocation.

* *SFO giveback*
+
Returning aggregates to their home locations when recovering from a takeover event.

* *SFO pair*
+
A pair of nodes whose controllers are configured to serve data for each other if one of the two nodes stops functioning. Depending on the system model, both controllers can be in a single chassis, or the controllers can be in separate chassis. Known as an HA pair in a two-node cluster.

* *Takeover*
+
The process by which the partner takes control of the storage when the primary owner of that storage fails. In the context of SFO, failover and takeover are synonymous.
