---
permalink: smb-hyper-v-sql/recommendations-config-concept.html
sidebar: sidebar
keywords: recommendations, sql, server, hyper, v, smb, configuration
summary: "To be sure that your SQL Server and Hyper-V over SMB configurations are robust and operational, you need to be familiar with recommended best practices when configuring the solutions."
---
= Recommendations for SQL Server and Hyper-V over SMB configurations
:icons: font
:imagesdir: ../media/

[.lead]
To be sure that your SQL Server and Hyper-V over SMB configurations are robust and operational, you need to be familiar with recommended best practices when configuring the solutions.

== General recommendations

* Separate application server files from general user data.
+
If possible, devote an entire storage virtual machine (SVM) and its storage for the application server's data.

* For best performance, do not enable SMB signing on SVMs that are used to store the application server's data.
* For best performance and improved fault tolerance, enable SMB Multichannel to provide multiple connections between ONTAP and clients in a single SMB session.
* Do not create continuously available shares on any shares other than those used in the Hyper-V or SQL Server over SMB configuration.
* Disable change notify on shares used for continuous availability.
* Do not perform a volume move at the same time as aggregate relocation (ARL) because ARL has phases that pause some operations.
* For Hyper-V over SMB solutions, use in-guest iSCSI drives when creating clustered virtual machines. Shared `.VHDX` files are not supported for Hyper-V over SMB in ONTAP SMB shares.
