---
permalink: smb-hyper-v-sql/share-based-backups-remote-vss-concept.html
sidebar: sidebar
keywords: share, based, backups, remote, vss, cif, server, hyper, v, virtual, machine, file
summary: "You can use Remote VSS to perform share-based backups of Hyper-V virtual machine files that are stored on a CIFS server."
---
= Share-based backups with Remote VSS overview 
:icons: font
:imagesdir: ../media/

[.lead]
You can use Remote VSS to perform share-based backups of Hyper-V virtual machine files that are stored on a CIFS server.

Microsoft Remote VSS (Volume Shadow Copy Services) is an extension of the existing Microsoft VSS infrastructure. This limited the use of VSS to applications that store data either on a local disk or on SAN-based storage. With Remote VSS, Microsoft has extended the VSS infrastructure to support the shadow copying of SMB shares. Server applications such as Hyper-V are now storing VHD files on SMB file shares. With these new extensions, it is possible to take application consistent shadow copies for virtual machines that store data and configuration files on shares.

