---
permalink: smb-hyper-v-sql/snapmanager-hyper-v-remote-backups-concept.html
sidebar: sidebar
keywords: snapmanager, hyper, v, remote, manage, vss, backup, smb
summary: "You can use SnapManager for Hyper-V to manage Remote VSS-based backup services. There are benefits to using SnapManager for Hyper-V managed backup service to create space efficient backup sets."
---
= How SnapManager for Hyper-V manages Remote VSS-based backups for Hyper-V over SMB
:icons: font
:imagesdir: ../media/

[.lead]
You can use SnapManager for Hyper-V to manage Remote VSS-based backup services. There are benefits to using SnapManager for Hyper-V managed backup service to create space efficient backup sets.

Optimizations to SnapManager for Hyper-V managed backups include the following:

* SnapDrive integration with ONTAP provides performance optimization when discovering SMB share location.
+
ONTAP provides SnapDrive with the name of the volume where the share resides.

* SnapManager for Hyper-V specifies the list of virtual machine files in the SMB shares that the shadow copy service needs to copy.
+
By providing a targeted list of virtual machine files, the shadow copy service does not need to create shadow copies of all the files in the share.

* The storage virtual machine (SVM) retains the snapshots for SnapManager for Hyper-V to use for restores.
+
There is no backup phase. The backup is the space-efficient snapshot.

SnapManager for Hyper-V provides backup and restore capabilities for HyperV over SMB using the following process:

. Preparing for the shadow copy operation
+
The SnapManager for Hyper-V application's VSS client sets up the shadow copy set. The VSS client gathers information about what shares to include in the shadow copy set and provides this information to ONTAP. A set might contain one or more shadow copies, and one shadow copy corresponds to one share.

. Creating the shadow copy set (if automatic-recovery is used)
+
For every share included in the shadow copy set, ONTAP creates a shadow copy and makes the shadow copy writable.

. Exposing the shadow copy set
+
After ONTAP creates the shadow copies, they are exposed to SnapManager for Hyper-V so that the application's VSS writers can perform automatic recovery.

. Automatically recovering the shadow copy set
+
During the shadow copy set creation, there is a period of time when active changes are occurring to the files included in the backup set. The application's VSS writers must update the shadow copies to make sure that they are in a completely consistent state prior to backup.
+
[NOTE]
====
The way that automatic recovery is done is application specific. Remote VSS is not involved in this phase.
====

. Completing and cleaning up the shadow copy set
+
The VSS client notifies ONTAP after it completes automatic recovery. The shadow copy set is made read-only and then is ready for backup. When using SnapManager for Hyper-V for backup, the files in a snapshot become the backup; therefore, for the backup phase, a snapshot is created for every volume containing shares in the backup set. After the backup is complete, the shadow copy set is removed from the CIFS server.
