---
permalink: smb-hyper-v-sql/verify-security-style-svm-root-volume-ntfs-task.html
sidebar: sidebar
keywords: verify, security, style, svm, root, volume, ntfs, storage, virtual, machine
summary: "To ensure that nondisruptive operations for Hyper-V and SQL Server over SMB are successful, volumes must be created with NTFS security style. Since the root volume’s security style is applied by default to volumes created on the storage virtual machine (SVM), the security style of the root volume should be set to NTFS."
---
= Verify that the security style of the SVM root volume is set to NTFS
:icons: font
:imagesdir: ../media/

[.lead]
To ensure that nondisruptive operations for Hyper-V and SQL Server over SMB are successful, volumes must be created with NTFS security style. Since the root volume's security style is applied by default to volumes created on the storage virtual machine (SVM), the security style of the root volume should be set to NTFS.

.About this task

* You can specify the root volume security style at the time you create the SVM.
* If the SVM is not created with the root volume set to NTFS security style, you can change the security style later by using the `volume modify` command.

.Steps

. Determine the current security style of the SVM root volume:
+
`*volume show -vserver _vserver_name_ -fields vserver,volume,security-style*`
. If the root volume is not an NTFS security-style volume, change the security style to NTFS:
+
`*volume modify -vserver _vserver_name_ -volume root_volume_name -security-style ntfs*`
. Verify that the SVM root volume is set to NTFS security style:
+
`*volume show -vserver _vserver_name_ -fields vserver,volume,security-style*`

.Example

The following commands verify that the root volume security style is NTFS on SVM vs1:

----
cluster1::> volume show -vserver vs1 -fields vserver,volume,security-style
vserver  volume     security-style
-------- ---------- --------------
vs1      vs1_root   unix

cluster1::> volume modify -vserver vs1 -volume vs1_root -security-style ntfs

cluster1::> volume show -vserver vs1 -fields vserver,volume,security-style
vserver  volume     security-style
-------- ---------- --------------
vs1      vs1_root   ntfs
----
