---
permalink: smb-hyper-v-sql/witness-protocol-transparent-failover-concept.html
sidebar: sidebar
keywords: witness, protocol, transparent, failover, lif, ca, share, client, smb, recovery
summary: "The Witness protocol provides enhanced client failover capabilities for SMB 3.0 continuously available shares (CA shares). Witness facilitates faster failover because it bypass the LIF failover recovery period. It notifies applications servers when a node is unavailable without needing to wait for the SMB 3.0 connection to time out."
---
= What the Witness protocol does to enhance transparent failover
:icons: font
:imagesdir: ../media/

[.lead]
The Witness protocol provides enhanced client failover capabilities for SMB 3.0 continuously available shares (CA shares). Witness facilitates faster failover because it bypass the LIF failover recovery period. It notifies applications servers when a node is unavailable without needing to wait for the SMB 3.0 connection to time out.

The failover is seamless, with applications running on the client not being aware that a failover occurred. If Witness is not available, failover operations still occur successfully, but failover without Witness is less efficient.

Witness enhanced failover is possible when the following requirements are met:

* It can only be used with SMB 3.0-capable CIFS servers that have SMB 3.0 enabled.
* The shares must use SMB 3.0 with the continuous availability share property set.
* The SFO partner of the node to which the application servers are connected must have at least one operational data LIF assigned to the storage virtual machine (SVM) hosting data for the application servers.
+
[NOTE]
====
The Witness protocol operates between SFO pairs. Because LIFs can migrate to any node within the cluster, any node might need to be the witness for its SFO partner.     The Witness protocol cannot provide rapid failover of SMB connections on a given node if the SVM hosting data for the application servers does not have an active data LIF on the partner node. Therefore, every node in the cluster must have at least one data LIF for each SVM hosting one of these configurations.
====

* The application servers must connect to the CIFS server by using the CIFS server name that is stored in DNS instead of by using individual LIF IP addresses.

