---
permalink: file-system-analytics/activity-tracking-task.html
sidebar: sidebar
keywords: monitor, volume, ontap, FSA, File System Analytics, 
summary: "Activity Tracking to view hot files, directories, clients, and users in a specified volume for real-time performance troubleshooting with"
---
= Enable Activity Tracking
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.10.1, File System Analytics includes an Activity Tracking feature that allows you to identify hot objects with Activity Tracking and download them as CSV file.

Activity Tracking enables monitoring in four categories:

*	Directories
*	Files
*	Clients
*	Users

For each category monitored, Activity Tracking will display Read IOPs, Write IOPs, Read Throughputs, and Write Throughputs. Queries on Activity Tracking refresh every 10 to 15 seconds pertaining to hot spots seen in the system over the previous five-second interval.

NOTE: Activity tracking information is approximate, and the accuracy of the data depends on the distribution of the incoming I/O traffic. 

When viewing Activity Tracking in System Manager, only the menu of the expanded volume will actively refresh. If the view of any volumes are collapsed, they will not refresh until the volume display is expanded. You can stop the refreshes with the *Pause Refresh* button. Activity data can be downloaded in a CSV format that will display all the point-in-time data captured for the selected volume. 

*Enable Activity Tracking*
[role="tabbed block"]
====
.System Manager
--
. Select *Storage > Volumes*. Select the desired volume. From the individual volume menu, select File System and then select the Activity tab. 
. Ensure *Activity Tracking* is turned on to view individual reports on top directories, files, clients, and users.
. To analyze data in greater depth without refreshes, select *Pause Refresh*. You can download the data to have a CSV record of the report as well. 
--

.CLI
--
. Enable Activity Tracking:
+
`volume activity-tracking on -vsverver _svm_name_ -volume _volume_name_`
+
You can check if the Activity Tracking state for a volume is on or off with the command: 
+
`volume activity-tracking show -vsverver _svm_name_ -volume _volume_name_ -state`
. Once enabled, use ONTAP System Manager or the ONTAP REST API to display Activity Tracking data.
--
====
//2021-10-29, IE-422