---
permalink: file-system-analytics/activity-tracking-task.html
sidebar: sidebar
keywords: monitor, volume, ontap, FSA, File System Analytics, 
summary: "Activity Tracking to view hot files, directories, clients, and users in a specified volume for real-time performance troubleshooting with"
---
= Enable Activity Tracking
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.10.1, File System Analytics includes an Activity Tracking feature that allows you to identify hot objects and download them as a CSV file. Beginning with ONTAP 9.11.1, Activity Tracking is expanded to the SVM scope. Also beginning in ONTAP 9.11.1, System Manager features a timeline for Activity Tracking, allowing you to look through up to five minutes of Activity Tracking data. 

Activity Tracking enables monitoring in four categories:

* Directories
* Files
* Clients
* Users

For each category monitored, Activity Tracking will display read IOPs, write IOPs, read throughputs, and write throughputs. Queries on Activity Tracking refresh every 10 to 15 seconds pertaining to hot spots seen in the system over the previous five-second interval.

Activity tracking information is approximate, and the accuracy of the data depends on the distribution of the incoming I/O traffic. 

When viewing Activity Tracking in System Manager at the volume level, only the menu of the expanded volume will actively refresh. If the view of any volumes are collapsed, they will not refresh until the volume display is expanded. You can stop the refreshes with the *Pause Refresh* button. Activity data can be downloaded in a CSV format that will display all the point-in-time data captured for the selected volume. 

With the timeline feature available beginning in ONTAP 9.11.1, you can keep a record of hotspot activity on a volume or SVM, continuously updating approximately every five seconds and retaining the previous five minutes of data. Timeline data is only retained for fields that are visible area of the page. If you collapse a tracking category or scroll so the timeline is out of view, the timeline will stop collecting data. By default, timelines are disabled and will automatically be disabled when you navigate away from the Activity tab.

== Enable Activity Tracking for a single volume

You can enable Activity Tracking with ONTAP System Manager or the ONTAP CLI.

.About this task
If you use RBAC with the ONTAP REST API or System Manager, you will need to create custom roles to manage access to Activity Tracking. See <<Role-based access control (RBAC) and Activity Tracking>> for this process. 

.Steps

[role="tabbed-block"]
====

.System Manager
--

. Select *Storage > Volumes*. Select the desired volume. From the individual volume menu, select File System and then select the Activity tab. 
. Ensure *Activity Tracking* is turned on to view individual reports on top directories, files, clients, and users.
. To analyze data in greater depth without refreshes, select *Pause Refresh*. You can download the data to have a CSV record of the report as well. 
--

.CLI
--

. Enable Activity Tracking: 
+
`volume activity-tracking on -vsverver _svm_name_ -volume _volume_name_`

. You can check if the Activity Tracking state for a volume is on or off with the command: 
+
`volume activity-tracking show -vsverver _svm_name_ -volume _volume_name_ -state`

. Once enabled, use ONTAP System Manager or the ONTAP REST API to display Activity Tracking data.
--
====

== Enable Activity Tracking for multiple volumes

You can enable Activity Tracking for multiple volumes at once with System Manager. 

.About this task
If you use RBAC with the ONTAP REST API or System Manager, you will need to create custom roles to manage access to Activity Tracking. See <<Role-based access control (RBAC) and Activity Tracking>> for this process. 

.Steps

[role="tabbed-block"]
====

.For specific volumes
--
. Select *Storage > Volumes*. Select the desired volume. From the individual volume menu, select File System and then select the Activity tab. 

. Select the volumes that you want to enable Activity Tracking on. At the top of the volume list, select the *More Options* button. Select *Enable Activity Tracking*.

. To view Activity Tracking at the SVM level, select the specific SVM you would like to view from *Storage > Volumes*. Navigate to the File System tab then Activity and you will see data for the volumes that have Activity Tracking enabled.
--

.For all volumes in an SVM
--
. Select *Storage > Volumes*. Select an SVM from the menu. 

.	Navigate to the *File System* tab, choose the *More* tab to enable Activity Tracking on all volumes in the SVM. 
--
====

== Role-based access control (RBAC) and Activity Tracking

If you use xref:../concepts/administrator-authentication-rbac-concept.html[role-based access control] (RBAC) in System Manager or the ONTAP REST API, you will need to create a dedicated role to moderate access to Activity Tracking in File System Analytics. 

.Control access to Activity Tracking

.Steps

. Create a default role to have access to all features. 
+
This needs to be done before creating the restrictive role to ensure the role is only restrictive on the Activity Tracking:
+
`security login role create -cmddirname DEFAULT -access all -role storageAdmin`
. Create the restrictive role:
+
`security login role create -cmddirname "volume file show-disk-usage" -access none -role storageAdmin`
. Authorize roles to access the SVM's web services:
    * `rest` for REST API calls
    * `security` for password protection
    * `sysmgr` for System Manager access
+
`vserver services web access create -vserver _svm-name_ -name_ -name rest -role storageAdmin`
+
`vserver services web access create -vserver _svm-name_ -name security -role storageAdmin`
+
`vserver services web access create -vserver _svm-name_ -name sysmgr -role storageAdmin`

. Create a user. 
+
You must issue a distinct create command for each application you would like to apply to the user. Calling create multiple times on the same user simply applies all the applications to that one user and does not create a new user each time. The `http` parameter for application type applies for the ONTAP REST API and System Manager.
+
`security login create -user-or-group-name storageUser -authentication-method password -application http -role storageAdmin`
. With the new user credentials, you can now log in to System Manager or use the ONTAP REST API to access File Systems Analytics data. 

link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_overview.html[Learn more about RBAC roles and the ONTAP REST API^]


//2021-10-29, IE-422
//2022-03-22, IE-509