---
sidebar: sidebar
permalink: fsa/fsa-considerations-concept.html
keywords: file system analytics, performance, 7-mode
summary: File System Analytics is designed to provide visibility on volumes with active NAS data. There are restrictions and limitations to its use. 
---

= Considerations for File System Analytics
:icons: font
:imagesdir: ../media/

[.lead]
File System Analytics is designed to provide visibility on volumes with active NAS data. Enabling File System Analytics can incur a performance impact. Do not enable analytics on the systems that are at a maximum CPU utilization.

System Manager provides xref:../concept_cluster_performance_overview.adoc[performance monitoring tools] to manage cluster health and metrics. If you identify impacts to the performance of your monitored volumes, you can disable analytics if your testing shows that the performance impact is unacceptable.

If you have enabled File System Analytics on volumes whose containing SVM is in a protection relationship, the analytics data is not replicated to the destination SVM. If the source SVM must be resynchronized in a recovery operation, you must manually reenable analytics on desired volumes after recovery.

// created 7 December from FSA overview