---
permalink: antivirus/apply-scanner-policy-pool-task.html
sidebar: sidebar
keywords: apply, scanner policy, single, cluster
summary: "A scanner policy determines whether a scanner pool is active. You must activate a scanner pool before the Vscan servers that it defines can connect to an SVM."
---
= Apply a scanner policy on a single cluster
:icons: font
:imagesdir: ../media/

[.lead]
A scanner policy determines whether a scanner pool is active. You must activate a scanner pool before the Vscan servers that it defines can connect to an SVM.

.About this task

* You can apply only one scanner policy to a scanner pool.
* If you created a scanner pool for all the SVMs in a cluster, you must apply a scanner policy on each SVM individually.

.Steps

. Apply a scanner policy:
+
`vserver vscan scanner-pool apply-policy -vserver data_SVM -scanner-pool scanner_pool -scanner-policy primary|secondary|idle -cluster cluster_to_apply_policy_on`
+
A scanner policy can have one of the following values:
+
 ** `Primary` specifies that the scanner pool is active.
 ** `Secondary` specifies that the scanner pool is active only if none of the Vscan servers in the primary scanner pool are connected.
 ** `Idle` specifies that the scanner pool is inactive.
+
The following example shows that the scanner pool named `SP` on the `vs1` SVM is active:
+
----
cluster1::> vserver vscan scanner-pool apply-policy -vserver vs1 -scanner-pool SP  -scanner-policy primary
----

. Verify that the scanner pool is active:
+
`vserver vscan scanner-pool show -vserver data_SVM|cluster_admin_SVM -scanner-pool scanner_pool`
+
Learn more about the commands described in this procedure in the link:https://docs.netapp.com/us-en/ontap-cli/[ONTAP command reference^].
+
The following command displays the details for the `SP` scanner pool:
+
----
cluster1::> vserver vscan scanner-pool show -vserver vs1 -scanner-pool SP

                                    Vserver: vs1
                               Scanner Pool: SP
                             Applied Policy: primary
                             Current Status: on
         Cluster on Which Policy Is Applied: cluster1
                  Scanner Pool Config Owner: vserver
       List of IPs of Allowed Vscan Servers: 1.1.1.1, 10.72.204.27
List of Host Names of Allowed Vscan Servers: 1.1.1.1, vmwin204-27.fsct.nb
                   List of Privileged Users: cifs\u1, cifs\u2
----
+
You can use the `vserver vscan scanner-pool show-active` command to view the active scanner pools on an SVM. Learn more about `vserver vscan scanner-pool show-active` in the link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-scanner-pool-show-active.html[ONTAP command reference^].

// 2025 Jan 10, ONTAPDOC-2569
// 2023 May 09, vscan-overview-update