---
permalink: antivirus/best-practices-configure-off-box-antivirus-functionality-concept.html
sidebar: sidebar
keywords: off-box, clustered ONTAP, antivirus, 
summary: "Consider the following recommendations to configure the off-box antivirus functionality in clustered 
ONTAP."
---
= Best practices for configuring the off-box antivirus functionality in clustered ONTAP 
:icons: font
:imagesdir: ../media/


[.lead. ]

Consider the following recommendations for configuring the off-box functionality in clustered ONTAP.

* Restrict privileged users to virus-scanning operations. Normal users should be discouraged from 
using privileged user credentials. This restriction can be achieved by turning off login rights for 
privileged users on Active Directory.
* Privileged users are not required to be part of any user group that has a large number of rights in the 
domain, such as the administrators group or the backup operators group. Privileged users must be 
validated only by the storage system so that they are allowed to create Vscan server connections and 
access files for virus scanning.
* Use the computers running Vscan servers only for virus-scanning purposes. To discourage general 
use, disable the Windows terminal services and other remote access provisions on these machines 
and grant the right to install new software on these machines only to administrators.
* Dedicate Vscan servers to virus scanning and do not use them for other operations, such as backups. 
You might decide to run the Vscan server as a virtual machine (VM). If this is the case, ensure that 
the resources allocated to the VM are not shared and are enough to perform virus scanning. Consult 
link:http://www.symantec.com/business/support/index?page=home[Symantec^] for guidance on antivirus engine requirements.
* Provide adequate CPU, memory, and disk capacity to the Vscan server to avoid resource 
bottlenecks. Most Vscan servers are designed to use multiple CPU core servers and to distribute the 
load across the CPUs. Consult link:http://www.symantec.com/business/support/index?page=home[Symantec^] for guidance on antivirus engine requirements.
* NetApp recommends using a dedicated network with a private VLAN for the connection from the SVM 
to the Vscan server so that the scan traffic is not affected by other client network traffic. Create a 
separate NIC that is dedicated to the antivirus VLAN on the Vscan server and to the data LIF on the 
SVM. This step simplifies administration and troubleshooting if network issues arise.
The AV traffic should be segregated using a private network. The AV server should be configured to 
communicate with domain controller (DC) and clustered ONTAP in one of the following ways:
** The DC should communicate to the AV servers through the private network that is used to segregate the traffic.
** The DC and AV server should communicate through a different network (not the private network mentioned previously), which is not the same as the CIFS client network. 

For Kerberos authentication to work for the AV communication, create a DNS entry for the private 
LIFs and a service principal name on the DC corresponding to the DNS entry created for the private 
LIF. Use this name when adding a LIF to the AV Connector. The DNS should be able to return a 
unique name for each private LIF connected to the AV Connector.


