---
permalink: antivirus/commands-manage-on-access-policies-reference.html
sidebar: sidebar
keywords: commands, manage, on-access, policies
summary: "You can modify, disable, or delete an on-access policy. You can view a summary and details for the policy."
---
= Commands for managing on-access policies
:icons: font
:imagesdir: ../media/

[.lead]
You can modify, disable, or delete an on-access policy. You can view a summary and details for the policy.

|===

h| If you want to... h| Enter the following command...
a|
Create an on-access policy
a|
`vserver vscan on-access-policy create`
a|
Modify an on-access policy
a|
`vserver vscan on-access-policy modify`
a|
Enable an on-access policy
a|
`vserver vscan on-access-policy enable`
a|
Disable an on-access policy
a|
`vserver vscan on-access-policy disable`
a|
Delete an on-access policy
a|
`vserver vscan on-access-policy delete`
a|
View summary and details for an on-access policy
a|
`vserver vscan on-access-policy show`
a|
Add to the list of paths to exclude
a|
`vserver vscan on-access-policy paths-to-exclude add`
a|
Delete from the list of paths to exclude
a|
`vserver vscan on-access-policy paths-to-exclude remove`
a|
View the list of paths to exclude
a|
`vserver vscan on-access-policy paths-to-exclude show`
a|
Add to the list of file extensions to exclude
a|
`vserver vscan on-access-policy file-ext-to-exclude add`
a|
Delete from the list of file extensions to exclude
a|
`vserver vscan on-access-policy file-ext-to-exclude remove`
a|
View the list of file extensions to exclude
a|
`vserver vscan on-access-policy file-ext-to-exclude show`
a|
Add to the list of file extensions to include
a|
`vserver vscan on-access-policy file-ext-to-include add`
a|
Delete from the list of file extensions to include
a|
`vserver vscan on-access-policy file-ext-to-include remove`
a|
View the list of file extensions to include
a|
`vserver vscan on-access-policy file-ext-to-include show`
|===
For more information about these commands, see the man pages.

// 2023 May 09, vscan-overview-update