---
permalink: antivirus/commands-view-vscan-server-reference.html
sidebar: sidebar
keywords: commands, view, vscan, server, connection, status
summary: "You can use the vserver vscan connection-status show commands to view summary and detailed information about Vscan server connection status."
---
= Commands for viewing Vscan server connection status
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `vserver vscan connection-status show` commands to view summary and detailed information about Vscan server connection status.

[options="header"]
|===
| If you want to... | Enter the following command...
a|
View a summary of Vscan server connections
a|
`vserver vscan connection-status show`
a|
View details for Vscan server connections
a|
`vserver vscan connection-status show-all`
a|
View details for connected Vscan servers
a|
`vserver vscan connection-status show-connected`
a|
View details for available Vscan servers that are not connected
a|
`vserver vscan connection-status show-not-connected`
|===

Learn more about `vserver vscan connection-status show` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+vscan+connection-status+show[ONTAP command reference^].

// 2025 Feb 14, ONTAPDOC-2758
// 2023 sep 19, ONTAPDOC-1052
