---
permalink: antivirus/commands-manage-scanner-pools-reference.html
sidebar: sidebar
keywords: commands, manage, scanner pools
summary: "You can modify and delete scanner pools, and manage privileged users and Vscan servers for a scanner pool. You can also view summary information about the scanner pool."
---
= Commands for managing scanner pools
:icons: font
:imagesdir: ../media/

[.lead]
You can modify and delete scanner pools, and manage privileged users and Vscan servers for a scanner pool. You can also view summary information about the scanner pool.

|===

h| If you want to... h| Enter the following command...

a|
Modify a scanner pool
a|
`vserver vscan scanner-pool modify`
a|
Delete a scanner pool
a|
`vserver vscan scanner-pool delete`
a|
Add privileged users to a scanner pool
a|
`vserver vscan scanner-pool privileged-users add`
a|
Delete privileged users from a scanner pool
a|
`vserver vscan scanner-pool privileged-users remove`
a|
Add Vscan servers to a scanner pool
a|
`vserver vscan scanner-pool servers add`
a|
Delete Vscan servers from a scanner pool
a|
`vserver vscan scanner-pool servers remove`
a|
View summary and details for a scanner pool
a|
`vserver vscan scanner-pool show`
a|
View privileged users for a scanner pool
a|
`vserver vscan scanner-pool privileged-users show`
a|
View Vscan servers for all scanner pools
a|
`vserver vscan scanner-pool servers show`
|===
For more information about these commands, see the man pages.

// 2023 May 09, vscan-overview-update