---
permalink: antivirus/create-on-demand-task-task.html
sidebar: sidebar
keywords: create, on-demand, task, vserver vscan
summary: "An on-demand task defines the scope of an on-demand scan. You can specify the maximum size of the files to be scanned, the extensions and paths of the files to be included in the scan, and the extensions and paths of the files to be excluded from the scan."
---
= Create an on-demand task with ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
An on-demand task defines the scope of the on-demand virus scan. You can specify the maximum size of the files to be scanned, the extensions and paths of the files to be included in the scan, and the extensions and paths of the files to be excluded from the scan. Files in subdirectories are scanned by default.

.About this task

* A maximum of ten (10) on-demand tasks can exist for each SVM, but only one can be active.
* An on-demand task creates a report, which has information regarding the statistics related to the scans. This report is accessible with a command or by downloading the report file created by the task at the location defined.

.Before you begin

* You must have xref:create-on-access-policy-task.html[created an on-access policy]. The policy can be a default or user-created one. Without the on-access policy, you cannot enable the scan. 

.Steps

. Create an on-demand task:
+
`vserver vscan on-demand-task create -vserver _data_SVM_ -task-name _task_name_ -scan-paths _paths_of_files_to_scan_ -report-directory _report_directory_path_ -report-expiry-time _expiration_time_for_report_ -schedule cron_schedule -max-file-size _max_size_of_files_to_scan_ -paths-to-exclude _paths_ -file-ext-to-exclude _file_extensions_ -file-ext-to-include _file_extensions_ -scan-files-with-no-ext true|false -directory-recursion true|false`
+
 ** The `-file-ext-to-exclude` setting overrides the `-file-ext-to-include` setting.
 ** Set `-scan-files-with-no-ext` to true to scan files without extensions.
+
Learn more about `vserver vscan on-demand-task create` in the link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-create.html[ONTAP command reference^].

+
The following command creates an on-demand task named `Task1` on the `vs1`SVM:
+
----
cluster1::> vserver vscan on-demand-task create -vserver vs1 -task-name Task1 -scan-paths "/vol1/","/vol2/cifs/" -report-directory "/report" -schedule daily -max-file-size 5GB -paths-to-exclude "/vol1/cold-files/" -file-ext-to-include "vmdk?","mp*" -file-ext-to-exclude "mp3","mp4" -scan-files-with-no-ext false
[Job 126]: Vscan On-Demand job is queued. Use the "job show -id 126" command to view the status.
----
+
[NOTE]
You can use the `job show` command to view the status of the job. You can use the `job pause` and `job resume` commands to pause and restart the job, or the `job stop` command to end the job.

. Verify that the on-demand task has been created:
+
`vserver vscan on-demand-task show -instance data_SVM -task-name task_name`
+
Learn more about `vserver vscan on-demand-task show` in the link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-show.html[ONTAP command reference^].
+
The following command displays the details for the `Task1` task:
+
----
cluster1::> vserver vscan on-demand-task show -instance vs1 -task-name Task1

                           Vserver: vs1
                         Task Name: Task1
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk?, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
        Expiration Time for Report: -
----

.After you finish

You must enable scanning on the SVM before the task is scheduled to run.

// 2025 Jan 10, ONTAPDOC-2569
// 2024 Dec 17, ONTAPDOC-2569
// 2024 may 16, ontapdoc-1986
// 05 July 2023, ONTAPDOC-790
