---
permalink: antivirus/enable-on-access-policy-task.html
sidebar: sidebar
keywords: enable, on-access, policy
summary: "An on-access policy defines the scope of an on-access scan. You must enable an on-access policy on an SVM before its files can be scanned."
---
= Enable an on-access policy with ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
An on-access policy defines the scope of an on-access scan. You must enable an on-access policy on an SVM before its files can be scanned.

If you created an on-access policy for all the SVMs in a cluster, you must enable the policy on each SVM individually. You can enable only one on-access policy on an SVM at a time.

.Steps

. Enable an on-access policy:
+
`vserver vscan on-access-policy enable -vserver data_SVM -policy-name policy_name`
+
The following command enables an on-access policy named `Policy1` on the `vs1` SVM:
+
----
cluster1::> vserver vscan on-access-policy enable -vserver vs1 -policy-name Policy1
----

. Verify that the on-access policy is enabled: 
+
`vserver vscan on-access-policy show -instance _data_SVM_ -policy-name _policy_name_`
+
Learn more about `vserver vscan on-access-policy show` in the link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-access-policy-show.html[ONTAP command reference^].
+
The following command displays the details for the `Policy1` on-access policy:
+
----
cluster1::> vserver vscan on-access-policy show -instance vs1 -policy-name Policy1

                           Vserver: vs1
                            Policy: Policy1
                     Policy Status: on
               Policy Config Owner: vserver
              File-Access Protocol: CIFS
                           Filters: scan-ro-volume
                    Mandatory Scan: on
Max File Size Allowed for Scanning: 3GB
            File Paths Not to Scan: \vol\a b\, \vol\a,b\
       File Extensions Not to Scan: mp3, txt
           File Extensions to Scan: mp*, tx*
      Scan Files with No Extension: false
----

// 2025 Jan 13, ONTAPDOC-2569 
// 2023 May 09, vscan-overview-update