---
permalink: antivirus/index.html
sidebar: sidebar
keywords: overview, antivirus, virus, viruses, configuration, overview, deciding, malicious code, scan, scanning, vscan, protect, data, on-access, on-demand
summary: "Vscan is an antivirus scanning solution developed by NetApp that allows customers to protect their data from being compromised by viruses or other malicious code."
---
= Antivirus configuration overview
:icons: font
:imagesdir: ../media/

[.lead]
Vscan is an antivirus scanning solution developed by NetApp that allows customers to protect their data from being compromised by viruses or other malicious code.  

Vscan performs virus scans when clients access files over SMB. You can configure Vscan to scan on-demand or on a schedule. You can interact with Vscan using the ONTAP command-line interface (CLI) or ONTAP application programming interfaces (APIs).

.Related information

https://docs.trellix.com/bundle?labelkey=prod-endpoint-security-storage-protection&labelkey=prod-endpoint-security-storage-protection-v2-3-x&labelkey=prod-endpoint-security-storage-protection-v2-2-x&labelkey=prod-endpoint-security-storage-protection-v2-1-x&labelkey=prod-endpoint-security-storage-protection-v2-0-x[Trellix (formerly McAfee) Endpoint Security Storage Protection^]

http://www.netapp.com/us/media/tr-4304.pdf[NetApp Technical Report 4304: Antivirus Solution for Clustered Data ONTAP Symantec^]

http://www.netapp.com/us/media/tr-4312.pdf[NetApp Technical Report 4312: Antivirus Solution for Clustered Data ONTAP Trend Micro^]

// 2023 Mar 10, Git Issue 840
// BURT 1338684, 10 JAN 2021
// issue #354, 1 FEB 2022
// 4 FEB 2022, BURT 1451789
// 2023 May 09, vscan-overview-update 