---
permalink: antivirus/index.html
sidebar: sidebar
keywords: overview, antivirus, virus, viruses, configuration, overview, deciding, malicious code, scan, scanning, vscan, protect, data, on-access, on-demand
summary: "You can use NetApp virus scanning, called Vscan, to protect data from being compromised by viruses or other malicious code."
---
= Antivirus configuration overview
:icons: font
:imagesdir: ../media/

[.lead]
You can use NetApp virus scanning, called _Vscan_, to protect data from being compromised by viruses or other malicious code. It shows you how to use on-access scanning to check for viruses when clients access files over SMB, and how to use on-demand scanning to check for viruses immediately or on a schedule.

You can work with Vscan by using the ONTAP command-line interface (CLI), not System Manager or an automated scripting tool. Vscan is not supported by System Manager.

.Related information

https://docs.trellix.com/bundle?labelkey=prod-endpoint-security-storage-protection&labelkey=prod-endpoint-security-storage-protection-v2-3-x&labelkey=prod-endpoint-security-storage-protection-v2-2-x&labelkey=prod-endpoint-security-storage-protection-v2-1-x&labelkey=prod-endpoint-security-storage-protection-v2-0-x[Trellix (formerly McAfee) Endpoint Security Storage Protection^]

https://techdocs.broadcom.com/us/en/symantec-security-software/endpoint-security-and-management/symantec-protection-engine/9-0-0.html[Symantec Protection Engine^]

http://www.netapp.com/us/media/tr-4312.pdf[NetApp Technical Report 4312: Antivirus Solution for Clustered Data ONTAP Trend Micro^]

// 2023 May 22, Git Issue 929
// 2023 Mar 10, Git Issue 840
// BURT 1338684, 10 JAN 2021
// issue #354, 1 FEB 2022
// 4 FEB 2022, BURT 1451789 