---
permalink: antivirus/install-ontap-antivirus-connector-task.html
sidebar: sidebar
keywords: install, ontap, task, antivirus connector
summary: "Install the ONTAP Antivirus Connector on the Vscan server to provide communication between the system running ONTAP and the Vscan server."
---
= Install ONTAP Antivirus Connector
:icons: font
:imagesdir: ../media/

[.lead]
Install the ONTAP Antivirus Connector on the Vscan server to provide communication between the system running ONTAP and the Vscan server. When the ONTAP Antivirus Connector is installed, antivirus software is able to communicate with one or more storage virtual machines (SVMs).

.About this task

* View the link:https://docs.netapp.com/us-en/ontap/antivirus/vscan-partner-solutions.html[Vscan partner solutions] page for information about the supported protocols, antivirus vendor software versions, ONTAP versions, interoperability requirements and Windows servers.
* .NET 4.5.1 or later.
* The ONTAP Antivirus Connector can run on a virtual machine. However, for best performance, NetApp recommends using a dedicated machine for antivirus scanning.
* SMB 2.0 must be enabled on the Windows server on which you are installing and running the ONTAP Antivirus Connector.

.Before you begin

* Verify that you have downloaded the ONTAP Antivirus Connector setup file from the Support Site and saved it to a directory on your hard drive.
* Verify that you meet the requirements to install the Antivirus Connector.
* Verify that you have administrator privileges to install the Antivirus Connector.

.Steps

. Start the Antivirus Connector installation wizard by running the appropriate setup file.
+
. Click *Next*. The Destination Folder dialog box opens.
+
. Click *Next* to install the Antivirus Connector to the folder that is listed or click *Change* to install to a different folder.
+
. The ONTAP AV Connector Windows Service Credentials dialog box opens.
+
. Enter your Windows service credentials or click *Add* to select a user. For an ONTAP system, this user must be a valid domain user and must exist in the scanner pool configuration for the SVM.
+
. Click *Next*. The Ready to Install the Program dialog box opens.
+
. Click *Install* to begin the installation or click *Back* if you want to make any changes to the settings.
A status box opens and charts the progress of the installation, followed by the InstallShield Wizard Completed dialog box.
+
. Select the Configure ONTAP LIFs check box if you want to continue with the configuration of ONTAP Management or Data LIFs.
You must configure at least one ONTAP Management or Data LIF before this Vscan server can be used.
+
. Select the Show the Windows Installer log check box if you want to view the installation logs.
+
. Click *Finish* to end the installation and to close the InstallShield wizard.
The Configure ONTAP LIFs icon is saved on the desktop to configure the ONTAP LIFs.
+
. link:https://docs.netapp.com/us-en/ontap/antivirus/configure-ontap-antivirus-connector-task.html[Configure the ONTAP Antivirus Connector].
// 2023 sep 19, ONTAPDOC-1052