---
permalink: antivirus/modify-vscan-file-profile-smb-share-task.html
sidebar: sidebar
keywords: modify, vscan, file-operations, profile, cifs share
summary: "The _Vscan file-operations profile_ for an SMB share defines the operations on the share that can trigger scanning. By default, the parameter is set to `standard`. You can adjust the parameter as necessary when you create or modify an SMB share."
---
= Modify the Vscan file-operations profile for an SMB share
:icons: font
:imagesdir: ../media/

[.lead]
The _Vscan file-operations profile_ for an SMB share defines the operations on the share that can trigger scanning. By default, the parameter is set to `standard`. You can adjust the parameter as necessary when you create or modify an SMB share.

See the link:architecture-concept.html[Antivirus architecture] section for details about the _Vscan file-operations profile_.

[NOTE]
====
Virus scanning is not performed on an SMB share that has the `continuously-available` parameter set to `Yes`.
====

.Step

. Modify the value of the Vscan file-operations profile for an SMB share:
+
`vserver cifs share modify -vserver _data_SVM_ -share-name _share_ -path _share_path_ -vscan-fileop-profile no-scan|standard|strict|writes-only`
+
For a complete list of options, see the man page for the command.
+
The following command changes the Vscan file operations profile for an SMB share to `strict`:
+
----
cluster1::> vserver cifs share modify -vserver vs1 -share-name SALES_SHARE -path /sales -vscan-fileop-profile strict
----

// 4 FEB 2022, BURT 1451789 
// 2023 May 09, vscan-overview-update