---
permalink: revert/anti-ransomware-license-task.html
sidebar: sidebar
keywords: revert, reverting, reversion, anti-ransomware, protection, license, licensing
summary: "If you have configured anti-ransomware protection and you revert from ONTAP 9.11.1 or later to ONTAP 9.10.1, you might experience warning messages and limited anti-ransomware functionality."
---
= Check anti-ransomware licensing before reverting from ONTAP 9.11.1 or later

:icons: font
:imagesdir: ../media/

[.lead]
If you have configured anti-ransomware protection and you revert from ONTAP 9.11.1 or later to ONTAP 9.10.1 or earlier, you might experience warning messages and limited anti-ransomware functionality.

In ONTAP 9.11.1, the Anti-ransomware license replaced the Multi-Tenant Key Management (MTKM) license. If your system has the Anti_ransomware license but no MT_EK_MGMT license, you will see a warning during revert that anti-ransomware cannot be enabled on new volumes upon revert.

The volumes with existing anti-ransomware protection will continue to work normally after revert, and anti-ransomware status can be displayed using the ONTAP CLI.  However, System Manager cannot show anti-ransomware status without the MTKM license.

Therefore, if you want anti-ransomware protection to continue after reverting to ONTAP 9.10.1, be sure the MTKM license is installed before reverting. link:../anti-ransomware/index.html[Learn about anti-ransomware licensing.]

// 2022-03-20, Jira IE-517
