---
permalink: revert/concept_reversion_requirements_for_snapmirror_and_snapvault_relationships.html
sidebar: sidebar
keywords: ontap, revert, reverting, reversion, requirements, snapmirror, snapvault, relationships
summary: 'The system node revert-to command notifies you of any SnapMirror and SnapVault relationships that need to be deleted or reconfigured for the revert process to be completed. However, you should be aware of these requirements before you begin the reversion.'
---
= ONTAP revert requirements for SnapMirror and SnapVault relationships
:icons: font
:imagesdir: ../media/

[.lead]
The `system node revert-to` command notifies you of any SnapMirror and SnapVault relationships that need to be deleted or reconfigured for the revert process to be completed. However, you should be aware of these requirements before you begin the reversion.

* All SnapVault and data protection mirror relationships must be quiesced and then broken.
+
After the reversion is completed, you can resynchronize and resume these relationships if a common snapshot exists.

* SnapVault relationships must not contain the following SnapMirror policy types:
 ** async-mirror
+
You must delete any relationship that uses this policy type.

 ** MirrorAndVault
+
If any of these relationships exist, you should change the SnapMirror policy to mirror-vault.
* All load-sharing mirror relationships and destination volumes must be deleted.
* SnapMirror relationships with FlexClone destination volumes must be deleted.
* Network compression must be disabled for each SnapMirror policy.
* The all_source_snapshot rule must be removed from any async-mirror type SnapMirror policies.
+
NOTE: The Single File Snapshot Restore (SFSR) and Partial File Snapshot Restore (PFSR) operations are deprecated on the root volume.

* Any currently running single file and snapshot restore operations must be completed before the reversion can proceed.
+
You can either wait for the restore operation to finish, or you can abort it.

* Any incomplete single file and snapshot restore operations must be removed by using the `snapmirror restore` command.

// 2024 Dec 05, Jira 2563