---
permalink: revert/concept_revert_paths.html
sidebar: sidebar
keywords: ontap, downgrade, revert, paths
summary: 'The version of ONTAP that you can revert to varies based on the version of ONTAP currently running on your nodes.'
---
= Supported ONTAP revert paths
:icons: font
:imagesdir: ../media/

[.lead]

The version of ONTAP that you can revert to varies based on the version of ONTAP currently running on your nodes. You can use the `system image show` command to  determine the version of ONTAP running on each node.

These guidelines refer only to on-premises ONTAP releases. For information about reverting ONTAP in the cloud, see https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html#reverting-or-downgrading[Reverting or downgrading Cloud Volumes ONTAP^].

[cols=2*,options="header"]
|===
| You can revert from...| To...
a| ONTAP 9.16.1 | ONTAP 9.15.1
a| ONTAP 9.15.1 | ONTAP 9.14.1
a| ONTAP 9.14.1 | ONTAP 9.13.1
a| ONTAP 9.13.1 | ONTAP 9.12.1
a| ONTAP 9.12.1 | ONTAP 9.11.1
a| ONTAP 9.11.1 | ONTAP 9.10.1
a| ONTAP 9.10.1 | ONTAP 9.9.1
a| ONTAP 9.9.1 | ONTAP 9.8
a| ONTAP 9.8 
a|
ONTAP 9.7
a|
ONTAP 9.7
a|
ONTAP 9.6
a|
ONTAP 9.6
a|
ONTAP 9.5
a|
ONTAP 9.5
a|
ONTAP 9.4
a|
ONTAP 9.4
a|
ONTAP 9.3
a|
ONTAP 9.3
a|
ONTAP 9.2
a|
ONTAP 9.2
a|
ONTAP 9.1
a|
ONTAP 9.1 or ONTAP 9
a|
Data ONTAP 8.3.x
|===

NOTE: If you need to change from ONTAP 9.1 to 9.0, you should follow the link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2876873[downgrade process^] documented here.


// 2024 Apr 15, Jira 1701
// 2023 Jun 20, Git Issue 968
// 2022-05-03, BURT 1454366
