---
permalink: revert/concept_revert_paths.html
sidebar: sidebar
keywords: ontap, downgrade, revert, paths
summary: 'You can directly revert your ONTAP software to just one release earlier than your current ONTAP version. You should not revert to unsupported ONTAP versions.'
---
= Supported ONTAP revert paths
:icons: font
:imagesdir: ../media/

[.lead]
You can directly revert your ONTAP software to only one release earlier than your current ONTAP version.  For example, if you are running 9.15.1, you cannot revert directly to 9.13.1. You must revert to 9.14.1; then perform a separate revert from 9.14.1 to 9.13.1.  

Reverting to ONTAP 9.4 or earlier is not supported.  You should not revert to unsupported ONTAP versions.  

You can use the `system image show` command to  determine the version of ONTAP running on each node.

The following supported revert paths refer only to on-premises ONTAP releases. For information about reverting ONTAP in the cloud, see https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html#reverting-or-downgrading[Reverting or downgrading Cloud Volumes ONTAP^].

[cols=2*,options="header"]
|===
| You can revert from...| To...
a| ONTAP 9.16.1 | ONTAP 9.15.1
a| ONTAP 9.15.1 | ONTAP 9.14.1
a| ONTAP 9.14.1 | ONTAP 9.13.1
a| ONTAP 9.13.1 | ONTAP 9.12.1
a| ONTAP 9.12.1 | ONTAP 9.11.1
a| ONTAP 9.11.1 | ONTAP 9.10.1
a| ONTAP 9.10.1 | ONTAP 9.9.1
a| ONTAP 9.9.1 | ONTAP 9.8
a| ONTAP 9.8 | ONTAP 9.7
a| ONTAP 9.7 | ONTAP 9.6
a| ONTAP 9.6 | ONTAP 9.5
|===

// 2024 Dec 05, Jira 2563
// 2024 Apr 15, Jira 1701
// 2023 Jun 20, Git Issue 968
// 2022-05-03, BURT 1454366
