---
permalink: revert/concept_when_to_call_technical_support.html
sidebar: sidebar
keywords: ontap, downgrade, revert, paths
summary: 'You can revert without assistance on new or test clusters.  You should call technical support to revert production clusters.'
---
= Do I need technical support to revert an ONTAP cluster?

:icons: font
:imagesdir: ../media/

[.lead]

You should call technical support to revert production clusters.  You should also call technical support if you experience any of the following:

* You are in a production environment and revert fails or you encounter any problems before or after the revert such as:
** The revert process fails and cannot finish.
** The revert process finishes, but the cluster is unusable in a production environment.
** The revert process finishes and the cluster goes into production, but you are not satisfied with its behavior.
* You created volumes in ONTAP 9.5 or later and you need to revert to an earlier version. Volumes using adaptive compression must be uncompressed before reverting.

You can revert without assistance on new or test clusters.  
