---
permalink: revert/concept_downgrade_or_revert.html
sidebar: revert_sidebar
keywords: ontap, downgrade, revert, paths
summary: 'Whether you should downgrade or revert to depends on the version of ONTAP currently running on your nodes and the version you want to move to.'
---
= Should I downgrade or revert?
:icons: font
:imagesdir: ../media/

[.lead]

Whether you should downgrade or revert to depends on the version of ONTAP currently running on your nodes and the version you want to move to.

* *Downgrade*: You should follow the link:task_downgrade_a_cluster.html[downgrade process] if you want to move to an earlier version of ONTAP within the same major release, for example, you want to move from ONTAP 9.2.3 to ONTAP 9.2.2. A downgrade can be performed nondisruptively.
* *Revert*: You should follow the link:task_reverting_an_ontap_cluster.html[revert process] if you want to move from a major release of ONTAP to an earlier major release, for example, to move from ONTAP 9.8 to ONTAP 9.7. Moving from ONTAP 9.1 to ONTAP 9 is the only exception to this rule. Changing from ONTAP 9.1 to ONTAP 9 follows the downgrade process. Reverting is always disruptive.
+
IMPORTANT: Do not attempt to revert ONTAP by simply downloading and booting (or netbooting) in an earlier release. If you do, you cannot boot the earlier target release. You must use the clustershell system node revert-to and nodeshell revert_to commands for the reversion process.

== Do I need technical support to downgrade or revert?
You can downgrade or revert without assistance when downgrading or reverting new or test clusters.

You should call technical support if you experience the any of the following:

* You are in a production environment and your upgrade fails or you encounter any problems before or after the upgrade such as:
** The upgrade process fails and cannot finish.
** The upgrade process finishes, but the cluster is unusable in a production environment.
** The upgrade process finishes and the cluster goes into production, but you are not satisfied with its behavior.
** The upgrade process finishes for some but not all of the nodes, and you decide that you want to revert.
* You created volumes in ONTAP 9.5 or later and you need to revert to an earlier version. Volumes using adaptive compression must be uncompressed before reverting.
