---
permalink: revert/concept_downgrade_or_revert.html
sidebar: revert_sidebar
keywords: ontap, downgrade, revert, paths
summary: 'The version of ONTAP that you can downgrade or revert to varies based on the version of ONTAP currently running on your nodes.'
---
= Should you downgrade or revert?
:icons: font
:imagesdir: ../media/

[.lead]

Your current version of ONTAP determines whether you should perform a downgrade or revert. You can use the `system image show` command to determine the current version of ONTAP running on each or your nodes.

* *Downgrade*: To downgrade means to move to an earlier version of ONTAP within the same major release, for example, to move from ONTAP 9.2.3 to ONTAP 9.2.2. A downgrade can be performed nondisruptively.
* *Revert*: To revert means to move from a major release of ONTAP to an earlier major release, for example, to move from ONTAP 9.8 to ONTAP 9.7. Moving from ONTAP 9.1 to ONTAP 9 is the only exception to this rule. Changing from ONTAP 9.1 to ONTAP 9 follows the downgrade process. Reverting is always disruptive.
+
IMPORTANT: Do not attempt to revert ONTAP by simply downloading and booting (or netbooting) in an earlier release. If you do, you cannot boot the earlier target release. You must use the clustershell system node revert-to and nodeshell revert_to commands for the reversion process.

== Do I need technical support to downgrade or revert?
You can downgrade or revert without assistance when downgrading or reverting new or test clusters.

You should call technical support if you experience the any of the following:

* You are in a production environment and your upgrade fails or you encounter any problems before or after the upgrade such as:
** The upgrade process fails and cannot finish.
** The upgrade process finishes, but the cluster is unusable in a production environment.
** The upgrade process finishes and the cluster goes into production, but you are not satisfied with its behavior.
** The upgrade process finishes for some but not all of the nodes, and you decide that you want to revert.
* You created volumes in ONTAP 9.5 or later and you need to revert to an earlier version. Volumes using adaptive compression must be uncompressed before reverting.

== Downgrade/Revert paths for Non-MCC and MCC configurations

[cols=2*,options="header"]
|===
| You can link:task_downgrade_a_cluster.html[downgrade] from...| To...
a|
ONTAP 9.1
a|
ONTAP 9**Note:** Downgrade of a two-node MetroCluster configuration from ONTAP 9.1 to 9 is disruptive.
|===

[cols=2*,options="header"]
|===
| You must link:task_reverting_an_ontap_cluster.html[perform a revert] from...| To...
a|
ONTAP 9.8
a|
ONTAP 9.7
a|
ONTAP 9.7
a|
ONTAP 9.6
a|
ONTAP 9.6
a|
ONTAP 9.5
a|
ONTAP 9.5
a|
ONTAP 9.4
a|
ONTAP 9.4
a|
ONTAP 9.3
a|
ONTAP 9.3
a|
ONTAP 9.2
a|
ONTAP 9.2
a|
ONTAP 9.1
a|
ONTAP 9.1 or ONTAP 9
a|
Data ONTAP 8.3.x
|===
