---
permalink: revert/concept_when_to_call_technical_support.html
sidebar: revert_sidebar
keywords: ontap, downgrade, revert, paths
summary: 'You can revert without assistance on new or test clusters.  You should call technical support to revert production clusters.'
---
== Do I need technical support to revert?

:icons: font
:imagesdir: ../media/

[.lead]

You can revert without assistance on new or test clusters.  You should call technical support to revert production clusters.  You should also call technical support if you experience any of the following:

* You are in a production environment and your upgrade fails or you encounter any problems before or after the upgrade such as:
** The upgrade process fails and cannot finish.
** The upgrade process finishes, but the cluster is unusable in a production environment.
** The upgrade process finishes and the cluster goes into production, but you are not satisfied with its behavior.
** The upgrade process finishes for some but not all of the nodes, and you decide that you want to revert.
* You created volumes in ONTAP 9.5 or later and you need to revert to an earlier version. Volumes using adaptive compression must be uncompressed before reverting.
