---
permalink: revert/concept_consideration_for_reverting_systems_with_snapmirror_synchronous_relationships.html
sidebar: sidebar
keywords: ontap, revert, reverting, reversion, considerations, snapmirror, synchronous, relationships
summary: 'You must be aware of the considerations for SnapMirror Synchronous relationships before reverting from ONTAP 9.6 to ONTAP 9.5.'
---
= Considerations for reverting systems with SnapMirror Synchronous relationships
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of the considerations for SnapMirror Synchronous relationships before reverting from ONTAP 9.6 to ONTAP 9.5.

Before reverting, you must take the following steps if you have SnapMirror Synchronous relationships:

* You must delete any SnapMirror Synchronous relationship in which the source volume is serving data using NFSv4 or SMB.
+
ONTAP 9.5 does not support NFSv4 and SMB.

* You must delete any SnapMirror Synchronous relationships in a mirror-mirror cascade deployment.
+
A mirror-mirror cascade deployment is not supported for SnapMirror Synchronous relationships in ONTAP 9.5.

* If the common Snapshot copies in ONTAP 9.5 are not available during revert, you must initialize the SnapMirror Synchronous relationship after reverting.
+
After two hours of upgrade to ONTAP 9.6, the common Snapshot copies from ONTAP 9.5 are automatically replaced by the common Snapshot copies in ONTAP 9.6. Therefore, you cannot resynchronize the SnapMirror Synchronous relationship after reverting if the common Snapshot copies from ONTAP 9.5 are not available.
