---
permalink: revert/disable-extended-qtree-performance-monitoring.html
sidebar: sidebar
keywords: ontap, revert, reversion, reverting, downgrade, downgrading, preparation
summary: 'Various configuration settings can impact cluster upgrade readiness.'
---
= Disable extended Qtree performance monitoring before reverting from ONTAP 9.16.1
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.16.1, you can use the ONTAP REST API to access the extended qtree monitoring capabilities which includes latency metrics and historical statistics. If extended qtree monitoring is enabled on any qtrees, before you revert from 9.16.1, you must set `ext_performance_monitoring.enabled` to false.

You can work with the `ext_performance_monitoring.enabled` setting by using the `/api/storage/qtrees` endpoint. Use GET to retrieve the current value, POST to set it when creating a new qtree, and PATCH to change it on an existing qtree.

Learn more about link:../volumes/qtrees-partition-your-volumes-concept.html#upgrading-and-reverting[reverting clusters with extended qtree performance monitoring].

// 2024 Dec 05, Jira 2563
// 2024 Mar 03, ONTAPDOC-3712