---
permalink: revert/task_identifying_current_cluster_activity.html
sidebar: sidebar
keywords: ontap, downgrade, dowgrading, cluster, activity, running, jobs, stop, shutdown, active, SMB, sessions
summary: 'Before performing a nondisruptive downgrade, you should identify and gracefully terminate any CIFS sessions that are not continuously available.'
---

= Verify current cluster activity before downgrading
:icons: font
:imagesdir: ../media/

[.lead]
Before downgrading, no jobs should be running and any SMB sessions that are not continuously available should be terminated.

== Verify that no jobs are running

Before downgrading the ONTAP software, you must verify the status of cluster jobs. If any aggregate, volume, NDMP (dump or restore), or Snapshot jobs (such as create, delete, move, modify, replicate, and mount jobs) are running or queued, you must allow the jobs to finish successfully or stop the queued entries.

. Review the list of any running or queued aggregate, volume, or Snapshot jobs: `job show`
+
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
8629   Vol Reaper           cluster1   -              Queued
       Description: Vol Reaper Job
8630   Certificate Expiry Check
                            cluster1   -              Queued
       Description: Certificate Expiry Check
.
.
.
----

. Delete any running or queued aggregate, volume, or Snapshot copy jobs: `job delete -id job_id`
+
----
cluster1::> job delete -id 8629
----

. Verify that no aggregate, volume, or Snapshot jobs are running or queued: `job show`
+
In this example, all running and queued jobs have been deleted:
+
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
9944   SnapMirrorDaemon_7_2147484678
                            cluster1   node1          Dormant
       Description: Snapmirror Daemon for 7_2147484678
18377  SnapMirror Service Job
                            cluster1   node0          Dormant
       Description: SnapMirror Service Job
2 entries were displayed
----


== Identify active SMB sessions that should be terminated

Before performing a nondisruptive downgrade, you should identify and gracefully terminate any SMB sessions that are not continuously available.

Continuously available SMB shares, which are accessed by Hyper-V or Microsoft SQL Server clients using the SMB 3.0 protocol, do not need to be terminated before upgrading or downgrading.

. Identify any established SMB sessions that are not continuously available: `vserver cifs session show -continuously-available Yes -instance`
+
This command displays detailed information about any SMB sessions that have no continuous availability. You should terminate them before proceeding with the ONTAP downgrade.
+
----
cluster1::> vserver cifs session show -continuously-available Yes -instance

                        Node: node1
                     Vserver: vs1
                  Session ID: 1
               Connection ID: 4160072788
Incoming Data LIF IP Address: 198.51.100.5
      Workstation IP address: 203.0.113.20
    Authentication Mechanism: NTLMv2
                Windows User: CIFSLAB\user1
                   UNIX User: nobody
                 Open Shares: 1
                  Open Files: 2
                  Open Other: 0
              Connected Time: 8m 39s
                   Idle Time: 7m 45s
            Protocol Version: SMB2_1
      Continuously Available: No
1 entry was displayed.
----

. If necessary, identify the files that are open for each SMB session that you identified: `vserver cifs session file show -session-id _session_ID_`
+
----
cluster1::> vserver cifs session file show -session-id 1

Node:       node1
Vserver:    vs1
Connection: 4160072788
Session:    1
File    File      Open Hosting                               Continuously
ID      Type      Mode Volume          Share                 Available
------- --------- ---- --------------- --------------------- ------------
1       Regular   rw   vol10           homedirshare          No
Path: \TestDocument.docx
2       Regular   rw   vol10           homedirshare          No
Path: \file1.txt
2 entries were displayed.
----

// 4 Feb 2022, BURT 1451789 