---
permalink: revert/task_reviewing_pre_reversion_resources.html
sidebar: sidebar
keywords: ontap, downgrade, downgrading, revert, reverting, reversion, resources, pre-reversion, pre-downgrading, before
summary: 'Before you revert ONTAP, you should confirm hardware support and review resources to understand issues you might encounter or need to resolve.'
---
= Resources to review before you revert and ONTAP cluster
:icons: font
:imagesdir: ../media/

[.lead]
Before you revert ONTAP, you should confirm hardware support and review resources to understand issues you might encounter or need to resolve.

. Review the link:https://library.netapp.com/ecmdocs/ECMLP2492508/html/frameset.html[ONTAP 9 Release Notes] for the target release.
+
The "`Important cautions`" section describes potential issues that you should be aware of before downgrading or reverting.

. Confirm that your hardware platform is supported in the target release.
+
https://hwu.netapp.com[NetApp Hardware Universe^]

. Confirm that your cluster and management switches are supported in the target release.
+
You must verify that the NX-OS (cluster network switches), IOS (management network switches), and reference configuration file (RCF) software versions are compatible with the version of ONTAP to which you are reverting.
+
https://mysupport.netapp.com/site/downloads[NetApp Downloads: Cisco Ethernet Switch^]

. If your cluster is configured for SAN, confirm that the SAN configuration is fully supported.
+
All SAN components--including target ONTAP software version, host OS and patches, required Host Utilities software, and adapter drivers and firmware--should be supported.
+
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]
