---
permalink: smb-admin/additional-information-concept.html
sidebar: sidebar
keywords: additional, resource, configure, dynamic, access, control, central, policies, policy, where to find additional information about configuring and using dynamic access control and central policies
summary: "Additional resources are available to help you configure and use Dynamic Access Control and central access policies."
---
= Where to find additional information about configuring and using Dynamic Access Control and central access policies
:icons: font
:imagesdir: ../media/

[.lead]
Additional resources are available to help you configure and use Dynamic Access Control and central access policies.

You can find information about how to configure Dynamic Access Control and central access policies on Active Directory in the Microsoft TechNet Library.

http://technet.microsoft.com/library/hh831717.aspx[Microsoft TechNet: Dynamic Access Control Scenario Overview]

http://technet.microsoft.com/library/hh831425.aspx[Microsoft TechNet: Central Access Policy Scenario]

The following references can help you configure the SMB server to use and support Dynamic Access Control and central access policies:

* *Using GPOs on the SMB server*
+
xref:applying-group-policy-objects-concept.adoc[Applying Group Policy Objects to SMB servers]

* *Configuring NAS auditing on the SMB server*
+
link:../nas-audit/index.html[SMB and NFS auditing and security tracing]

// 4 Feb 2022, BURT 1451789 