---
permalink: smb-admin/branchcache-when-reverting-concept.html
sidebar: sidebar
keywords: revert, ontap, release, support, branchcache, what happens to branchcache when reverting
summary: "It is important to understand what happens when you revert ONTAP to a release that does not support BranchCache."
---
= What happens to BranchCache when reverting
:icons: font
:imagesdir: ../media/

[.lead]
It is important to understand what happens when you revert ONTAP to a release that does not support BranchCache.

* When you revert to a version of ONTAP that does not support BranchCache, the SMB shares do not advertise BranchCache capabilities to BranchCache-enabled clients; therefore, the clients do not request hash information.
+
Instead, they request the actual content using normal SMB read requests. In response to the request for content, the CIFS server sends the actual content that is stored on the storage virtual machine (SVM).

* When a node hosting a hash store is reverted to a release that does not support BranchCache, the storage administrator needs to manually revert the BranchCache configuration using a command that is printed out during the revert.
+
This command deletes the BranchCache configuration and hashes.
+
After the revert completes, the storage administrator can manually delete the directory that contained the hash store if desired.

.Related information

xref:delete-branchcache-config-svms-concept.adoc[Deleting the BranchCache configuration on SVMs]
