---
permalink: smb-admin/builtin-groups-default-privileges-reference.html
sidebar: sidebar
keywords: assign, membership, local, user, domain, predefined, builtin, ontap, predefined builtin groups and default privileges
summary: "You can assign membership of a local user or domain user to a predefined set of BUILTIN groups provided by ONTAP. Predefined groups have predefined privileges assigned."
---
= Predefined BUILTIN groups and default ONTAP SMB privileges
:icons: font
:imagesdir: ../media/

[.lead]
You can assign membership of a local user or domain user to a predefined set of BUILTIN groups provided by ONTAP. Predefined groups have predefined privileges assigned.

The following table describes the predefined groups:

[options="header"]
|===
| Predefined BUILTIN group| Default privileges
a|
``BUILTIN\Administrators``RID 544

When first created, the local `Administrator` account, with a RID of 500, is automatically made a member of this group. When the storage virtual machine (SVM) is joined to a domain, the `domain\Domain Admins` group is added to the group. If the SVM leaves the domain, the `domain\Domain Admins` group is removed from the group.

a|

* `SeBackupPrivilege`
* `SeRestorePrivilege`
* `SeSecurityPrivilege`
* `SeTakeOwnershipPrivilege`
* `SeChangeNotifyPrivilege`

a|
``BUILTIN\Power Users``RID 547

When first created, this group does not have any members. Members of this group have the following characteristics:

* Can create and manage local users and groups.
* Cannot add themselves or any other object to the `BUILTIN\Administrators` group.

a|
`SeChangeNotifyPrivilege`
a|
``BUILTIN\Backup Operators``RID 551

When first created, this group does not have any members. Members of this group can override read and write permissions on files or folders if they are opened with backup intent.

a|

* `SeBackupPrivilege`
* `SeRestorePrivilege`
* `SeChangeNotifyPrivilege`

a|
``BUILTIN\Users``RID 545

When first created, this group does not have any members (besides the implied `Authenticated Users` special group). When the SVM is joined to a domain, the `domain\Domain Users` group is added to this group. If the SVM leaves the domain, the `domain\Domain Users` group is removed from this group.

a|
`SeChangeNotifyPrivilege`
a|
``Everyone``SID S-1-1-0

This group includes all users, including guests (but not anonymous users). This is an implied group with an implied membership.

a|
`SeChangeNotifyPrivilege`
|===
.Related information

xref:builtin-groups-local-administrator-account-concept.adoc[Guidelines for using BUILTIN groups and the local administrator account]

xref:list-supported-privileges-reference.adoc[List of supported privileges]

xref:configure-bypass-traverse-checking-concept.adoc[Configuring bypass traverse checking]

// 2025 May 20, ONTAPDOC-2981