---
permalink: smb-admin/choosing-hash-store-location-concept.html
sidebar: sidebar
keywords: configuring, configure, branchcache, store, hash, size, guideline, cids-enabled, svm, guidelines for choosing the hash store location
summary: "When configuring BranchCache, you choose where to store hashes and what size the hash store should be. Understanding the guidelines when choosing the hash store location and size can help you plan your BranchCache configuration on a CIFS-enabled SVM."
---
= Learn about choosing the ONTAP SMB hash store location
:icons: font
:imagesdir: ../media/

[.lead]
When configuring BranchCache, you choose where to store hashes and what size the hash store should be. Understanding the guidelines when choosing the hash store location and size can help you plan your BranchCache configuration on a CIFS-enabled SVM.

* You should locate the hash store on a volume where atime updates are permitted.
+
The access time on a hash file is used to keep frequently accessed files in the hash store. If atime updates are disabled, the creation time is used for this purpose. It is preferable to use atime to track frequently used files.

* You cannot store hashes on read-only file systems such as SnapMirror destinations and SnapLock volumes.
* If the maximum size of the hash store is reached, older hashes are flushed to make room for new hashes.
+
You can increase the maximum size of the hash store to reduce the amount of hashes that are flushed from the cache.

* If the volume on which you store hashes is unavailable or full, or if there is an issue with intra-cluster communication where the BranchCache service cannot retrieve hash information, BranchCache services are not available.
+
The volume might be unavailable because it is offline or because the storage administrator specified a new location for the hash store.
+
This does not cause issues with file access. If access to the hash store is impeded, ONTAP returns a Microsoft-defined error to the client, which causes the client to request the file using the normal SMB read request.

.Related information

xref:configure-branchcache-task.adoc[Configure BranchCache on the SMB server]

xref:modify-branchcache-config-task.html[Modify the BranchCache configuration]


// 2025 June 05, ONTAPDOC-2981