---
permalink: smb-admin/commands-manage-name-mappings-reference.html
sidebar: sidebar
keywords: ontap, command, managing, manage, name, mapping
summary: "There are specific ONTAP commands for managing name mappings."
---
= Commands for managing name mappings
:icons: font
:imagesdir: ../media/

[.lead]
There are specific ONTAP commands for managing name mappings.

[options="header"]
|===
| If you want to...| Use this command...
a|
Create a name mapping
a|
`vserver name-mapping create`
a|
Insert a name mapping at a specific position
a|
`vserver name-mapping insert`
a|
Display name mappings
a|
`vserver name-mapping show`
a|
Exchange the position of two name mappings
[NOTE]
====
A swap is not allowed when name-mapping is configured with an ip-qualifier entry.
====

a|
`vserver name-mapping swap`
a|
Modify a name mapping
a|
`vserver name-mapping modify`
a|
Delete a name mapping
a|
`vserver name-mapping delete`
a|
Validate the correct name mapping
a|
`vserver security file-directory show-effective-permissions -vserver vs1 -win-user-name user1 -path / -share-name sh1`
|===
See the man page for each command for more information.
