---
permalink: smb-admin/commands-manage-character-mappings-file-name-reference.html
sidebar: sidebar
keywords: manage, character, mapping, creating, create, modify, information, deleting, delete, file, smb, translation, flexvol, volume, commands for managing character mappings for smb file name translation
summary: "You can manage character mapping by creating, modifying, displaying information about, or deleting file character mappings used for SMB file name translation on FlexVol volumes."
---
= Commands for managing character mappings for SMB file name translation in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
You can manage character mapping by creating, modifying, displaying information about, or deleting file character mappings used for SMB file name translation on FlexVol volumes.

[options="header"]
|===
| If you want to...| Use this command...
a|
Create new file character mappings
a|
`vserver cifs character-mapping create`
a|
Display information about file character mappings
a|
`vserver cifs character-mapping show`
a|
Modify existing file character mappings
a|
`vserver cifs character-mapping modify`
a|
Delete file character mappings
a|
`vserver cifs character-mapping delete`
|===
Learn more about `vserver cifs character-mapping` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+character-mapping[ONTAP command reference^].

.Related information

xref:configure-character-mappings-file-name-translation-task.adoc[Configuring character mapping for SMB file name translation on volumes]


// 2025 Jan 16, ONTAPDOC-2569