---
permalink: smb-admin/commands-manage-computer-account-passwords-concept.html
sidebar: sidebar
keywords: command, changing, change, reset, disable, disabling, password, configuring, configure, automatic, update, schedule, cifs, server, commands for managing cifs servers computer account passwords
summary: "You need to know the commands for changing, resetting, and disabling passwords, and for configuring automatic update schedules. You can also configure a schedule on the CIFS server to update it automatically."
---
= Commands for managing CIFS servers computer account passwords
:icons: font
:imagesdir: ../media/

[.lead]
You need to know the commands for changing, resetting, and disabling passwords, and for configuring automatic update schedules. You can also configure a schedule on the CIFS server to update it automatically.

[options="header"]
|===
| If you want to...| Use this command...
a|
Change or reset the domain account password and you know the password
a|
`vserver cifs domain password change`
a|
Reset the domain account password and you do not know the password
a|
`vserver cifs domain password reset`
a|
Configure CIFS servers for automatic computer account password changes
a|
`vserver cifs domain password schedule modify -vserver vserver_name -is-schedule-enabled true`
a|
Disable automatic computer account password changes on CIFS servers
a|
`vserver cifs domain password schedule modify -vserver vs1 -is-schedule-enabled false`
|===
See the man page for each command for more information.
