---
permalink: smb-admin/commands-manage-ntfs-dacl-reference.html
sidebar: sidebar
keywords: ontap, command, managing, manage, dacl, access, control, entries, aces, ntfs, modify, deleting, delete, display, information, commands for managing ntfs dacl access control entries
summary: "There are specific ONTAP commands for managing DACL access control entries (ACEs). You can add ACEs to NTFS DACLs at any time. You can also manage existing NTFS DACLs by modifying, deleting, and displaying information about ACEs in DACLs."
---
= Commands for managing NTFS DACL access control entries in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
There are specific ONTAP commands for managing DACL access control entries (ACEs). You can add ACEs to NTFS DACLs at any time. You can also manage existing NTFS DACLs by modifying, deleting, and displaying information about ACEs in DACLs.

[options="header"]
|===
| If you want to...| Use this command...
a|
Create ACEs and add them to NTFS DACLs
a|
`vserver security file-directory ntfs dacl add`
a|
Modify existing ACEs in NTFS DACLs
a|
`vserver security file-directory ntfs dacl modify`
a|
Display information about existing ACEs in NTFS DACLs
a|
`vserver security file-directory ntfs dacl show`
a|
Remove existing ACEs from NTFS DACLs
a|
`vserver security file-directory ntfs dacl remove`
|===
Learn more about `vserver security file-directory ntfs dacl` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs+dacl[ONTAP command reference^].


// 2025 Jan 16, ONTAPDOC-2569