---
permalink: smb-admin/commands-manage-ntfs-smb.html
sidebar: sidebar
keywords: ontap, command, managing, manage, security, descriptor, create, modify, delete, display, information, commands for managing ntfs security descriptors
summary: "Use ONTAP commands to create, modify, delete, and display information about NTFS security descriptors and access control entries (ACEs) in DACLs and SACLs. You can also use ONTAP commands to manage SMB security policies, policy tasks, and policy jobs."
---
= ONTAP commands for managing NTFS and SMB security policies and access control entries
:icons: font
:imagesdir: ../media/

[.lead]
Use ONTAP commands to create, modify, delete, and display information about NTFS security descriptors and access control entries (ACEs) in DACLs and SACLs. You can also use ONTAP commands to manage SMB security policies, policy tasks, and policy jobs.

== ONTAP commands for managing NTFS security descriptors on SMB servers

There are specific ONTAP commands for managing security descriptors. You can create, modify, delete, and display information about security descriptors.

[options="header"]
|===
| If you want to...| Use this command...
a|
Create NTFS security descriptors
a|
`vserver security file-directory ntfs create`
a|
Modify existing NTFS security descriptors
a|
`vserver security file-directory ntfs modify`
a|
Display information about existing NTFS security descriptors
a|
`vserver security file-directory ntfs show`
a|
Delete NTFS security descriptors
a|
`vserver security file-directory ntfs delete`
|===
Learn more about `vserver security file-directory ntfs` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs[ONTAP command reference^].

== ONTAP commands for managing NTFS DACL access control entries on SMB servers

There are specific ONTAP commands for managing DACL access control entries (ACEs). You can add ACEs to NTFS DACLs at any time. You can also manage existing NTFS DACLs by modifying, deleting, and displaying information about ACEs in DACLs.

[options="header"]
|===
| If you want to...| Use this command...
a|
Create ACEs and add them to NTFS DACLs
a|
`vserver security file-directory ntfs dacl add`
a|
Modify existing ACEs in NTFS DACLs
a|
`vserver security file-directory ntfs dacl modify`
a|
Display information about existing ACEs in NTFS DACLs
a|
`vserver security file-directory ntfs dacl show`
a|
Remove existing ACEs from NTFS DACLs
a|
`vserver security file-directory ntfs dacl remove`
|===
Learn more about `vserver security file-directory ntfs dacl` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs+dacl[ONTAP command reference^].

== ONTAP commands for managing NTFS SACL access control entries on SMB servers

There are specific ONTAP commands for managing SACL access control entries (ACEs). You can add ACEs to NTFS SACLs at any time. You can also manage existing NTFS SACLs by modifying, deleting, and displaying information about ACEs in SACLs.

[options="header"]
|===
| If you want to...| Use this command...
a|
Create ACEs and add them to NTFS SACLs
a|
`vserver security file-directory ntfs sacl add`
a|
Modify existing ACEs in NTFS SACLs
a|
`vserver security file-directory ntfs sacl modify`
a|
Display information about existing ACEs in NTFS SACLs
a|
`vserver security file-directory ntfs sacl show`
a|
Remove existing ACEs from NTFS SACLs
a|
`vserver security file-directory ntfs sacl remove`
|===
Learn more about `vserver security file-directory ntfs sacl` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs+sacl[ONTAP command reference^].

== ONTAP commands for managing SMB security policies

There are specific ONTAP commands for managing security policies. You can display information about policies and you can delete policies. You cannot modify a security policy.

[options="header"]
|===
| If you want to...| Use this command...
a|
Create security policies
a|
`vserver security file-directory policy create`
a|
Display information about security policies
a|
`vserver security file-directory policy show`
a|
Delete security policies
a|
`vserver security file-directory policy delete`
|===
Learn more about `vserver security file-directory policy` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+policy[ONTAP command reference^].

== ONTAP commands for managing SMB security policy tasks

There are ONTAP commands for adding, modifying, removing, and displaying information about security policy tasks.

[options="header"]
|===
| If you want to...| Use this command...
a|
Add security policy tasks
a|
`vserver security file-directory policy task add`
a|
Modify security policy tasks
a|
`vserver security file-directory policy task modify`
a|
Display information about security policy tasks
a|
`vserver security file-directory policy task show`
a|
Remove security policy tasks
a|
`vserver security file-directory policy task remove`
|===
Learn more about `vserver security file-directory policy task` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+policy+task[ONTAP command reference^].

== ONTAP commands for managing SMB security policy jobs

There are ONTAP commands for pausing, resuming, stopping, and displaying information about security policy jobs.

[options="header"]
|===
| If you want to...| Use this command...
a|
Pause security policy jobs
a|
`vserver security file-directory job pause ‑vserver vserver_name -id integer`
a|
Resume security policy jobs
a|
`vserver security file-directory job resume ‑vserver vserver_name -id integer`
a|
Display information about security policy jobs
a|
`vserver security file-directory job show ‑vserver vserver_name` You can determine the job ID of a job using this command.

a|
Stop security policy jobs
a|
`vserver security file-directory job stop ‑vserver vserver_name -id integer`
|===
Learn more about `vserver security file-directory job` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+job[ONTAP command reference^].

// 2026 May 26, ONTAPDOC-3910
// 2025 May 29, ONTAPDOC-2981
// 2025 Jan 16, ONTAPDOC-2569