---
permalink: smb-admin/commands-manage-servers-reference.html
sidebar: sidebar
keywords: command, creating, create, display, modify, stop, start, deleting, delete
summary: "You need to know the commands for creating, displaying, modifying, stopping, starting, and deleting SMB servers. There are also commands to reset and rediscover servers, change or reset machine account passwords, schedule changes for machine account passwords, and add or remove NetBIOS aliases."
---
= Commands for managing SMB servers in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
You need to know the commands for creating, displaying, modifying, stopping, starting, and deleting SMB servers. There are also commands to reset and rediscover servers, change or reset machine account passwords, schedule changes for machine account passwords, and add or remove NetBIOS aliases.

|===

h| If you want to... h| Use this command...
a|
Create an SMB server
a|
`vserver cifs create`
a|
Display information about an SMB server
a|
`vserver cifs show`
a|
Modify an SMB server
a|
`vserver cifs modify`
a|
Move an SMB server to another domain
a|
`vserver cifs modify`
a|
Stop an SMB server
a|
`vserver cifs stop`
a|
Start an SMB server
a|
`vserver cifs start`
a|
Delete an SMB server
a|
`vserver cifs delete`
a|
Reset and rediscover servers for the SMB server
a|
`vserver cifs domain discovered-servers reset-servers`
a|
Change the SMB server's machine account password
a|
`vserver cifs domain password change`
a|
Reset the SMB server's machine account password
a|
`vserver cifs domain password change`
a|
Schedule automatic password changes for the SMB server's machine account
a|
`vserver cifs domain password schedule modify`
a|
Add NetBIOS aliases for the SMB server
a|
`vserver cifs add-netbios-aliases`
a|
Remove NetBIOS aliases for the SMB server
a|
`vserver cifs remove-netbios-aliases`
|===
Learn more about `vserver cifs` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs[ONTAP command reference^].

.Related information

link:local-users-groups-when-deleting-servers-concept.html[What happens to local users and groups when deleting SMB servers]


// 2025 Jan 16, ONTAPDOC-2569
// 08 DEC 2021, BURT 1430515
// 4 Feb 2022, BURT 1451789 
