---
permalink: smb-admin/command-options-limit-client-resource-concept.html
sidebar: sidebar
keywords: option, vserver, cifs, modify, command, enable, control, resource, consumption, windows, client, bound, notify, request, command options to limit excessive windows client resource consumption
summary: "Options to the vserver cifs options modify command enable you to control resource consumption for Windows clients. This can be helpful if any clients are outside normal bounds of resource consumption, for example, if there are unusually high numbers of files open, sessions open, or change notify requests."
---
= Command options to limit excessive Windows client resource consumption in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
Options to the `vserver cifs options modify` command enable you to control resource consumption for Windows clients. This can be helpful if any clients are outside normal bounds of resource consumption, for example, if there are unusually high numbers of files open, sessions open, or change notify requests.

The following options to the `vserver cifs options modify` command have been added to control Windows client resource consumption. If the maximum value for any of these options is exceeded, the request is denied and an EMS message is sent. An EMS warning message is also sent when 80 percent of the configured limit for these options is reached.

* `-max-opens-same-file-per-tree`
+
Maximum number of opens on the same file per CIFS tree

* `-max-same-user-sessions-per-connection`
+
Maximum number of sessions opened by the same user per connection

* `-max-same-tree-connect-per-session`
+
Maximum number of tree connects on the same share per session

* `-max-watches-set-per-tree`
+
Maximum number of watches (also known as _change notifies_) established per tree

Learn more about `vserver cifs options modify` in the link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-options-modify.html[ONTAP command reference^].

Beginning with ONTAP 9.4, servers running SMB version 2 or later can limit the number of outstanding requests (_SMB credits_) that the client can send to the server on a SMB connection. The management of SMB credits is initiated by the client and controlled by the server.

The maximum number of outstanding requests that can be granted on an SMB connection is controlled by the `-max-credits` option. The default value for this option is 128.


// 2025 Jan 16, ONTAPDOC-2569