---
permalink: smb-admin/configure-security-styles-qtrees-task.html
sidebar: sidebar
keywords: configure, qtree, volume, security, style, permission, data, configure security styles on qtrees
summary: "You configure the qtree volume security style to determine the type of permissions used for data on qtrees."
---
= Configure SMB security styles on ONTAP qtrees
:icons: font
:imagesdir: ../media/

[.lead]
You configure the qtree volume security style to determine the type of permissions used for data on qtrees.

.Steps

. Perform one of the following actions:
+
[options="header"]
|===
| If the qtree...| Use the command...
a|
Does not exist yet
a|
`volume qtree create` and include the `-security-style` parameter to specify the security style.
a|
Already exists
a|
`volume qtree modify` and include the `-security-style` parameter to specify the security style.
|===
The possible options for the qtree security style are `unix`, `ntfs`, or `mixed`.
+
If you do not specify a security style when creating a qtree, the default security style is `mixed`.
+
For more information about the `volume qtree create` or `volume qtree modify` commands, see link:../volumes/index.html[Logical storage management].

. To display the configuration, including the security style of the qtree you created, enter the following command: `volume qtree show -qtree qtree_name -instance`

// 2025 May 15, ONTAPDOC-2981