---
permalink: smb-admin/configure-default-unix-user-task.html
sidebar: sidebar
keywords: configure, unix, user, map, fail, individual, windows, authentication, non-mapped, configure the default unix user
summary: "You can configure the default UNIX user to use if all other mapping attempts fail for a user, or if you do not want to map individual users between UNIX and Windows. Alternatively, if you want authentication of non-mapped users to fail, you should not configure the default UNIX user."
---
= Configure the default ONTAP SMB UNIX user
:icons: font
:imagesdir: ../media/

[.lead]
You can configure the default UNIX user to use if all other mapping attempts fail for a user, or if you do not want to map individual users between UNIX and Windows. Alternatively, if you want authentication of non-mapped users to fail, you should not configure the default UNIX user.

.About this task

By default, the name of the default UNIX user is "`pcuser`", which means that, by default, user mapping to the default UNIX user is enabled. You can specify another name to use as the default UNIX user. The name that you specify must exist in the name service databases configured for the storage virtual machine (SVM). If this option is set to a null string, no one can access the CIFS server as a UNIX default user. That is, each user must have an account in the password database before they can access the CIFS server.

For a user to connect to the CIFS server using the default UNIX user account, the user must meet the following prerequisites:

* The user is authenticated.
* The user is in the CIFS server's local Windows user database, in the CIFS server's home domain, or in a trusted domain (if multidomain name mapping searches is enabled on the CIFS server).
* The user name is not explicitly mapped to a null string.

.Steps

. Configure the default UNIX user:
+
[options="header"]
|===
| If you want to ...| Enter ...
a|
Use the default UNIX user "`pcuser`"
a|
`vserver cifs options modify -default-unix-user pcuser`
a|
Use another UNIX user account as the default user
a|
`vserver cifs options modify -default-unix-user _user_name_`
a|
Disable the default UNIX user
a|
`vserver cifs options modify -default-unix-user ""`
|===
`vserver cifs options modify -default-unix-user pcuser`

. Verify that the default UNIX user is configured correctly: `vserver cifs options show -vserver _vserver_name_`
+
In the following example, both the default UNIX user and the guest UNIX user on SVM vs1 are configured to use UNIX user "`pcuser`":
+
`vserver cifs options show -vserver vs1`
+
----

Vserver: vs1

  Client Session Timeout : 900
  Default Unix Group     : -
  Default Unix User      : pcuser
  Guest Unix User        : pcuser
  Read Grants Exec       : disabled
  Read Only Delete       : disabled
  WINS Servers           : -
----

// 2025 May 09, ONTAPDOC-2981