---
permalink: smb-admin/configure-folder-redirection-task.html
sidebar: sidebar
keywords: configure, folder, redirection, windows, properties, method, assistance, svm, administrator, configure folder redirection
summary: "You can configure folder redirection using the Windows Properties window. The advantage to using this method is that the Windows user can configure folder redirection without assistance from the SVM administrator."
---
= Configure ONTAP SMB folder redirection using Windows Properties
:icons: font
:imagesdir: ../media/

[.lead]
You can configure folder redirection using the Windows Properties window. The advantage to using this method is that the Windows user can configure folder redirection without assistance from the SVM administrator.

.Steps

. In Windows Explorer, right-click the folder that you want to redirect to a network share.
. Click *Properties*.
+
Properties for the share you selected are displayed.

. In the *Shortcut* tab, click *Target* and specify the path to the network location where you want to redirect the selected folder.
+
For example, if you want to redirect a folder to the `data` folder in a home directory that is mapped to `Q:\`, specify `Q:\data` as the target.

. Click *OK*.
+
For more information about configuring offline folders, consult the Microsoft TechNet Library.

.Related information

http://technet.microsoft.com/en-us/library/[Microsoft TechNet Library: technet.microsoft.com/en-us/library/]


// 2025 June 04, ONTAPDOC-2981