---
permalink: smb-admin/configure-roaming-profiles-task.html
sidebar: sidebar
keywords: automatic, user, profile, available, log, computer, network, configure, roam, active, directory, mmc, snap-in, configuring, roam, windows, server, administration, center, configure roam profile
summary: "If you want to automatically make a user’s profile available when that user logs on to any computer on the network, you can configure roaming profiles through the Active Directory Users and Computers MMC snap-in. If you are configuring roaming profiles on Windows Server, you can use the Active Directory Administration Center."
---
= Configure roaming profiles
:icons: font
:imagesdir: ../media/

[.lead]
If you want to automatically make a user's profile available when that user logs on to any computer on the network, you can configure roaming profiles through the Active Directory Users and Computers MMC snap-in. If you are configuring roaming profiles on Windows Server, you can use the Active Directory Administration Center.

.Steps

. On the Windows server, open the Active Directory Users and Computers MMC (or the Active Directory Administration Center on Windows servers).
. Locate the user for which you want to configure a roaming profile.
. Right-click the user and click *Properties*.
. On the *Profile* tab, enter the profile path to the share where you want to store the user's roaming profile, followed by `%username%`.
+
For example, a profile path might be the following: `\\vs1.example.com\profiles\%username%`. The first time a user logs in, `%username%` is replaced with the user's name.
+
[NOTE]
====
In the path `\\vs1.example.com\profiles\%username%`, `profiles` is the share name of a share on storage virtual machine (SVM) vs1 that has Full Control rights for Everyone.
====

. Click *OK*.

// 2023 Nov 15 Jira 1446