---
permalink: smb-admin/configure-apply-audit-policies-ntfs-files-folders-task.html
sidebar: sidebar
keywords: perform, apply, policies, policy, ntfs, file, folder, ontap, cli, security, descriptor, sacl, descriptor, create, storage, virtual, machine, svm, configure and apply audit policies to ntfs files and folders using the cli
summary: "There are several steps you must perform to apply audit policies to NTFS files and folders when using the ONTAP CLI. First, you create an NTFS security descriptor and add SACLs to the security descriptor. Next you create a security policy and add policy tasks. You then apply the security policy to a storage virtual machine (SVM)."
---
= ONTAP commands to configure and apply SMB audit policies to NTFS files and folders
:icons: font
:imagesdir: ../media/

[.lead]
There are several steps you must perform to apply audit policies to NTFS files and folders when using the ONTAP CLI. First, you create an NTFS security descriptor and add SACLs to the security descriptor. Next you create a security policy and add policy tasks. You then apply the security policy to a storage virtual machine (SVM).

.About this task

After applying the security policy, you can monitor the security policy job and then verify the settings for the applied audit policy.

NOTE: When an audit policy and associated SACLs are applied, any existing DACLs are overwritten. You should review existing security policies before creating and applying new ones.

.Related information

xref:secure-file-access-storage-level-access-guard-concept.adoc[Securing file access by using Storage-Level Access Guard]

xref:limits-when-cli-set-file-folder-security-concept.adoc[Limits when using the CLI to set file and folder security]

xref:security-descriptors-apply-file-folder-security-concept.adoc[How security descriptors are used to apply file and folder security]

link:../nas-audit/index.html[SMB and NFS auditing and security tracing]

xref:create-ntfs-security-descriptor-file-task.adoc[Configure and apply file security on NTFS files and folders using the CLI]

// 2025 May 28, ONTAPDOC-2981