---
permalink: smb-admin/configure-default-user-task.html
sidebar: sidebar
keywords: configure, default, user, map, fail, authentication, non-mapped, fail, alternative, configure the default user
summary: "You can configure a default user to use if all other mapping attempts fail for a user, or if you do not want to map individual users between UNIX and Windows. Alternatively, if you want authentication of non-mapped users to fail, you should not configure a default user."
---
= Configure the default ONTAP SMB user
:icons: font
:imagesdir: ../media/

[.lead]
You can configure a default user to use if all other mapping attempts fail for a user, or if you do not want to map individual users between UNIX and Windows. Alternatively, if you want authentication of non-mapped users to fail, you should not configure a default user.

.About this task

For CIFS authentication, if you do not want to map each Windows user to an individual UNIX user, you can instead specify a default UNIX user.

For NFS authentication, if you do not want to map each UNIX user to an individual Windows user, you can instead specify a default Windows user.

.Steps

. Perform one of the following actions:
+
[options="header"]
|===
| If you want to...| Enter the following command...
a|
Configure the default UNIX user
a|
`vserver cifs options modify -default-unix-user _user_name_`
a|
Configure the default Windows user
a|
`vserver nfs modify -default-win-user _user_name_`
|===

// 2025 May 15, ONTAPDOC-2981