---
permalink: smb-admin/configure-branchcache-enabled-shares-concept.html
sidebar: sidebar
keywords: configure, branchcache, smb server, office, enable, smb, share, content, client, configure branchache-enabled smb shares
summary: "After you configure BranchCache on the SMB server and at the branch office, you can enable BranchCache on SMB shares that contain content that you want to allow clients at branch offices to cache."
---
= Learn about configuring BranchCache-enabled ONTAP SMB shares
:icons: font
:imagesdir: ../media/

[.lead]
After you configure BranchCache on the SMB server and at the branch office, you can enable BranchCache on SMB shares that contain content that you want to allow clients at branch offices to cache.

BranchCache caching can be enabled on all SMB shares on the SMB server or on a share-by-share basis.

* If you enable BranchCache on a share-by-share basis, you can enable BranchCache as you create the share or by modifying existing shares.
+
If you enable caching on an existing SMB share, ONTAP begins computing hashes and sending metadata to clients requesting content as soon as you enable BranchCache on that share.

* Any clients that have an existing SMB connection to a share do not get BranchCache support if BranchCache is subsequently enabled on that share.
+
ONTAP advertises BranchCache support for a share at the time the SMB session is set up. Clients that already have established sessions when BranchCache is enabled need to disconnect and reconnect to use cached content for this share.

[NOTE]
====
If BranchCache on a SMB share is subsequently disabled, ONTAP stops sending metadata to the requesting client. A client that needs data retrieves it directly from the content server (SMB server).
====


// 2025 June 09, ONTAPDOC-2981