---
permalink: smb-admin/configure-access-restrictions-anonymous-users-task.html
sidebar: sidebar
keywords: anonymous, unauthenticated, user, information, network, cifs, server, option, configure, access, restriction, user, configure access restrictions for anonymous users
summary: "By default, an anonymous, unauthenticated user (also known as the null user) can access certain information on the network. You can use a SMB server option to configure access restrictions for the anonymous user."
---
= Configure ONTAP SMB access restrictions for anonymous users
:icons: font
:imagesdir: ../media/

[.lead]
By default, an anonymous, unauthenticated user (also known as the _null user_) can access certain information on the network. You can use a SMB server option to configure access restrictions for the anonymous user.

.About this task

The `-restrict-anonymous` SMB server option corresponds to the `RestrictAnonymous` registry entry in Windows.

Anonymous users can list or enumerate certain types of system information from Windows hosts on the network, including user names and details, account policies, and share names. You can control access for the anonymous user by specifying one of three access restriction settings:

[options="header"]
|===
| Value| Description
a|
`no-restriction` (default)
a|
Specifies no access restrictions for anonymous users.
a|
`no-enumeration`
a|
Specifies that only enumeration is restricted for anonymous users.
a|
`no-access`
a|
Specifies that access is restricted for anonymous users.
|===

.Steps

. Set the privilege level to advanced: `set -privilege advanced`
. Configure the restrict anonymous setting: `vserver cifs options modify -vserver _vserver_name_ -restrict-anonymous {no-restriction|no-enumeration|no-access}`
. Verify that the option is set to the desired value: `vserver cifs options show -vserver _vserver_name_`
. Return to the admin privilege level: `set -privilege admin`

.Related information

xref:server-options-reference.adoc[Available SMB server options]

// 2025 Apr 30, ONTAPDOC-2981
// 4 Feb 2022, BURT 1451789 