---
permalink: smb-admin/control-domain-controller-discovery-task.html
sidebar: sidebar
keywords: ontap, modify, default, process, domain, controller, dc, enable, limit, site, pool, performance, improvement, environment, manage, manage domain controller discovery
summary: "Beginning with ONTAP 9.3, you can modify the default process by which domain controllers (DCs) are discovered. This enables you to limit discovery to your site or to a pool of preferred DCs, which can lead to performance improvements depending on the environment."
---
= Manage domain controller discovery
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.3, you can modify the default process by which domain controllers (DCs) are discovered. This enables you to limit discovery to your site or to a pool of preferred DCs, which can lead to performance improvements depending on the environment.

.About this task

By default, the dynamic discovery process discovers all available DCs, including any preferred DCs, all DCs in the local site, and all remote DCs. This configuration can lead to latency in authentication and accessing shares in certain environments. If you have already determined the pool of DCs that you want to use, or if the remote DCs are inadequate or inaccessible, you can change the discovery method.

In ONTAP 9.3 and later releases, the `discovery-mode` parameter of the `cifs domain discovered-servers` command enables you to select one of the following discovery options:

* All DCs in the domain are discovered.
* Only DCs in the local site are discovered.
+
The `default-site` parameter for the SMB server can be defined to use this mode with LIFs that are not assigned to a site in sites-and-services.

* Server discovery is not performed, the SMB server configuration depends only on preferred DCs.
+
To use this mode, you must first define the preferred DCs for the SMB server.

.Step

. Specify the desired discovery option: `vserver cifs domain discovered-servers discovery-mode modify -vserver _vserver_name_ -mode {all|site|none}`
+
Options for the `mode` parameter:

 ** `all`
+
Discover all available DCs (default).

 ** `site`
+
Limit DC discovery to your site.

 ** `none`
+
Use only preferred DCs and not perform discovery.

// Public PR 1190
