---
permalink: smb-admin/create-snapshot-config-previous-versions-access-task.html
sidebar: sidebar
keywords: previous, version, functionality, available, client, access, snapshot, copies, copy, enable, snapshot, exist, configuration, requirement, create a snapshot configuration to enable previous versions access
summary: "The Previous Versions functionality is always available, provided that client access to Snapshot copies is enabled and provided that Snapshot copies exist. If your Snapshot copy configuration does not meet these requirements, you can create a Snapshot copy configuration that does."
---
= Create a Snapshot configuration to enable Previous Versions access in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
The Previous Versions functionality is always available, provided that client access to Snapshot copies is enabled and provided that Snapshot copies exist. If your Snapshot copy configuration does not meet these requirements, you can create a Snapshot copy configuration that does.

.Steps

. If the volume containing the share to which you want to allow Previous Versions access does not have an associated Snapshot policy, associate a Snapshot policy to the volume and enable it by using the `volume modify` command.
+
Learn more about `volume modify` in the link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html[ONTAP command reference^].

. Enable access to the Snapshot copies by using the `volume modify` command to set the `-snap-dir` option to `true`.
+
Learn more about `volume modify` in the link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html[ONTAP command reference^].

. Verify that Snapshot policies are enabled and that access to Snapshot directories is enabled by using the `volume show` and `volume snapshot policy show` commands.
+
Learn more about `volume show` and `volume snapshot policy show` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+show[ONTAP command reference^].
+
For more information about configuring and managing Snapshot policies and Snapshot schedules, see link:../data-protection/index.html[Data Protection].

.Related information

link:../data-protection/index.html[Data protection]


// 2025 Jan 17, ONTAPDOC-2569