---
permalink: smb-admin/create-branchcache-enabled-share-task.html
sidebar: sidebar
keywords: enable, branchcache, smb, create, share, setting, property, create a bracnhcache-enabled smb share
summary: "You can enable BranchCache on an SMB share when you create the share by setting the branchcache share property."
---
= Create a BranchCache-enabled SMB share in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
You can enable BranchCache on an SMB share when you create the share by setting the `branchcache` share property.

.About this task

* If BranchCache is enabled on the SMB share, the share must have the offline files configuration set to manual caching.
+
This is the default setting when you create a share.

* You can also specify additional optional share parameters when you create the BranchCache-enabled share.
* You can set the `branchcache` property on a share even if BranchCache is not configured and enabled on the storage virtual machine (SVM).
+
However, if you want the share to offer cached content, you must configure and enable BranchCache on the SVM.

* Since there are no default share properties applied to the share when you use the `-share-properties` parameter, you must specify all other share properties that you want applied to the share in addition to the `branchcache` share property by using a comma-delimited list.
* Learn more about `vserver cifs share create` in the link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html[ONTAP command reference^].

.Step

. Create a BranchCache-enabled SMB share: +
`vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -share-properties branchcache[,...]`
+
. Verify that the BranchCache share property is set on the SMB share by using the `vserver cifs share show` command.

.Example

The following command creates a BranchCache-enabled SMB share named "`data`" with a path of `/data` on SVM vs1. By default, the offline files setting is set to `manual`:

----
cluster1::> vserver cifs share create -vserver vs1 -share-name data -path /data -share-properties branchcache,oplocks,browsable,changenotify

cluster1::> vserver cifs share show -vserver vs1 -share-name data
                      Vserver: vs1
                        Share: data
     CIFS Server NetBIOS Name: VS1
                         Path: /data
             Share Properties: branchcache
                               oplocks
                               browsable
                               changenotify
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: data
                Offline Files: manual
Vscan File-Operations Profile: standard
----

.Related information

xref:disable-branchcache-single-share-task.adoc[Disabling BranchCache on a single SMB share]


// 2025 Jan 16, ONTAPDOC-2569