---
permalink: smb-admin/create-security-policies-audit-task.html
sidebar: sidebar
keywords: creating, create, audit, policy, storage, virtual, machine, svm, configuring, configure, apply, acl, file, folder, act, container, task, entry, applied, apply, security, create security policies
summary: "Creating an audit policy for storage virtual machines (SVMs) is the third step in configuring and applying ACLs to a file or folder. A policy acts as a container for various tasks, where each task is a single entry that can be applied to files or folders. You can add tasks to the security policy later."
---
= Create ONTAP SMB security policies
:icons: font
:imagesdir: ../media/

[.lead]
Creating an audit policy for storage virtual machines (SVMs) is the third step in configuring and applying ACLs to a file or folder. A policy acts as a container for various tasks, where each task is a single entry that can be applied to files or folders. You can add tasks to the security policy later.

.About this task

The tasks that you add to a security policy contain associations between the NTFS security descriptor and the file or folder paths. Therefore, you should associate the security policy with each storage virtual machine (SVM) (containing NTFS security-style volumes or mixed security-style volumes).

.Steps

. Create a security policy: `vserver security file-directory policy create -vserver vserver_name -policy-name policy_name`
+
`vserver security file-directory policy create -policy-name policy1 -vserver vs1`

. Verify the security policy: `vserver security file-directory policy show`
+
----

            vserver security file-directory policy show
               Vserver          Policy Name
             ------------     --------------
                 vs1              policy1
----

// 2025 May 29, ONTAPDOC-2981