---
permalink: smb-admin/create-ntfs-security-descriptor-file-task.html
sidebar: sidebar
keywords: create, creating, ntfs, security, descriptor, file, policy, configuring, configure, apply, access, control, acl, file, folder, residing, reside, storage, virtual, machine, svm, associate, task
summary: "Creating an NTFS security descriptor (file security policy) is the first step in configuring and applying NTFS access control lists (ACLs) to files and folders residing within storage virtual machines (SVMs). You can associate the security descriptor to the file or folder path in a policy task."
---
= Create an NTFS security descriptor in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
Creating an NTFS security descriptor (file security policy) is the first step in configuring and applying NTFS access control lists (ACLs) to files and folders residing within storage virtual machines (SVMs). You can associate the security descriptor to the file or folder path in a policy task.

.About this task

You can create NTFS security descriptors for files and folders residing within NTFS security-style volumes, or for files and folders residing on mixed security-style volumes.

By default, when a security descriptor is created, four discretionary access control list (DACL) access control entries (ACEs) are added to that security descriptor. The four default ACEs are as follows:

[options="header"]
|===
| Object| Access type| Access rights| Where to apply the permissions
a|
BUILTIN\Administrators
a|
Allow
a|
Full Control
a|
this-folder, sub-folders, files
a|
BUILTIN\Users
a|
Allow
a|
Full Control
a|
this-folder, sub-folders, files
a|
CREATOR OWNER
a|
Allow
a|
Full Control
a|
this-folder, sub-folders, files
a|
NT AUTHORITY\SYSTEM
a|
Allow
a|
Full Control
a|
this-folder, sub-folders, files
|===
You can customize the security descriptor configuration by using the following optional parameters:

* Owner of the security descriptor
* Primary group of the owner
* Raw control flags

The value for any optional parameter is ignored for Storage-Level Access Guard. 
Learn more in the link:https://docs.netapp.com/us-en/ontap-cli/[ONTAP command reference^].


// 2025 Jan 16, ONTAPDOC-2569