---
permalink: smb-admin/delete-branchcache-config-task.html
sidebar: sidebar
keywords: command, deleting, delete, branchcache, service, storage, virtual, machine, svm, exist, hash, delete the branchcache configuration
summary: "The command you use for deleting the BranchCache service on your storage virtual machine differs depending on whether you want to delete or keep existing hashes."
---
= Delete the BranchCache configuration on ONTAP SMB shares
:icons: font
:imagesdir: ../media/

[.lead]
= Learn what happens when you delete the BranchCache configuration on ONTAP SMB shares
:icons: font
:imagesdir: ../media/

[.lead]
If you previously configured BranchCache but do not want the storage virtual machine (SVM) to continue providing cached content, you can delete the BranchCache configuration on the CIFS server. You must be aware of what happens when you delete the configuration.

When you delete the configuration, ONTAP removes the configuration information for that SVM from the cluster and stops the BranchCache service. You can choose whether ONTAP should delete the hash store on the SVM.

Deleting the BranchCache configuration does not disrupt access by BranchCache-enabled clients. Thereafter, when BranchCache-enabled clients request metadata information on existing SMB connections for content that is already cached, ONTAP responds with a Microsoft defined error, which causes the client to send a second request, requesting the actual content. In response to the request for content, the CIFS server sends the actual content that is stored on the SVM

After the BranchCache configuration is deleted, SMB shares do not advertise BranchCache capabilities. To access content that has not previously been cached using new SMB connections, clients make normal read SMB requests.

The command you use for deleting the BranchCache service on your storage virtual machine (SVM) differs depending on whether you want to delete or keep existing hashes.

.Step

. Run the appropriate command:
+
[options="header"]
|===
| If you want to...| Then enter the following...
a|
Delete the BranchCache configuration and delete existing hashes
a|
`vserver cifs branchcache delete -vserver _vserver_name_ -flush-hashes true`
a|
Delete the BranchCache configuration but keep existing hashes
a|
`vserver cifs branchcache delete -vserver _vserver_name_ -flush-hashes false`
|===

.Example

The following example deletes the BranchCache configuration on SVM vs1 and deletes all existing hashes:

----
cluster1::> vserver cifs branchcache delete -vserver vs1 -flush-hashes true
----


// 2025 June 10, ONTAPDOC-2981