---
permalink: smb-admin/deploy-offline-files-concept.html
sidebar: sidebar
keywords: important, guideline, understand, deploy, offline, file, home, directory, share, showsnapshot, property, set, home, directories, directory, guidelines for deploying offline files
summary: "There are some important guidelines you need to understand when you deploy offline files on home directory shares that have the showsnapshot share property set on home directories."
---
= Guidelines for deploying offline files
:icons: font
:imagesdir: ../media/

[.lead]
There are some important guidelines you need to understand when you deploy offline files on home directory shares that have the `showsnapshot` share property set on home directories.

If the `showsnapshot` share property is set on a home directory share that has offline files configured, Windows clients cache all of the Snapshot copies under the `~snapshot` folder in the user's home directory.

Windows clients cache all of the Snapshot copies under the home directory if one of more of the following is true:

* The user makes the home directory available offline from the client.
+
The contents of the `~snapshot` folder in the home directory is included and made available offline.

* The user configures folder redirection to redirect a folder such as `My Documents` to the root of a home directory residing on the CIFS server share.
+
Some Windows clients might automatically make the redirected folder available offline. If the folder is redirected to the root of the home directory, the `~snapshot` folder is included in the cached offline content.

[NOTE]
====
Offline file deployments where the `~snapshot` folder is included in offline files should be avoided. The Snapshot copies in the `~snapshot` folder contain all data on the volume at the point at which ONTAP created the snapshot. Therefore, creating an offline copy of the `~snapshot` folder consumes significant local storage on the client, consumes network bandwidth during offline files synchronization, and increases the time it takes to synchronize offline files.
====
