---
permalink: smb-admin/directory-case-sensitivity-share-multiprotocol-concept.html
sidebar: sidebar
keywords: create, share, svm, naming, name, scheme, distinguish, directory, difference, share, path, ensure, client, connect, desire, directory, path, directory case-sensitivity requirements when creating shares in a multiprotocol environment
summary: "If you create shares in an SVM where the 8.3 naming scheme is used to distinguish between directory names where there are only case differences between the names, you must use the 8.3 name in the share path to ensure that the client connects to the desired directory path."
---
= Learn about ONTAP SMB directory case-sensitivity requirements when creating shares in a multiprotocol environment
:icons: font
:imagesdir: ../media/

[.lead]
If you create shares in an SVM where the 8.3 naming scheme is used to distinguish between directory names where there are only case differences between the names, you must use the 8.3 name in the share path to ensure that the client connects to the desired directory path.

In the following example, two directories named "`testdir`" and "`TESTDIR`" were created on a Linux client. The junction path of the volume containing the directories is `/home`. The first output is from a Linux client and the second output is from an SMB client.

----
 ls -l
drwxrwxr-x 2 user1 group1   4096 Apr 17 11:23 testdir
drwxrwxr-x 2 user1 group1   4096 Apr 17 11:24 TESTDIR
----

----
dir

 Directory of Z:\

04/17/2015  11:23 AM    <DIR>          testdir
04/17/2015  11:24 AM    <DIR>          TESTDI~1
----

When you create a share to the second directory, you must use the 8.3 name in the share path. In this example, the share path to the first directory is `/home/testdir` and the share path to the second directory is `/home/TESTDI~1`.

// 2025 May 15, ONTAPDOC-2981