---
permalink: smb-admin/display-preferred-trusted-domain-list-task.html
sidebar: sidebar
keywords: display, information, trust, domain, perfer, list, order, multidomain, name, map, search, enable, configure, alternative, display information about the preferred trusted domain list
summary: "You can display information about which trusted domains are in the preferred trusted domain list and the order in which they are searched if multidomain name mapping searches are enabled. You can configure a preferred trusted domain list as an alternative to using the automatically discovered trusted domain list."
---
= Display information about the preferred trusted ONTAP SMB domain list
:icons: font
:imagesdir: ../media/

[.lead]
You can display information about which trusted domains are in the preferred trusted domain list and the order in which they are searched if multidomain name mapping searches are enabled. You can configure a preferred trusted domain list as an alternative to using the automatically discovered trusted domain list.

.Steps

. Perform one of the following actions:
+
[options="header"]
|===
| If you want to display information about the following...| Use the command...
a|
All preferred trusted domains in the cluster grouped by storage virtual machine (SVM)
a|
`vserver cifs domain name-mapping-search show`
a|
All preferred trusted domains for a specified SVM
a|
`vserver cifs domain name-mapping-search show -vserver _vserver_name_`
|===
The following command displays information about all preferred trusted domains on the cluster:
+
----
cluster1::> vserver cifs domain name-mapping-search show
Vserver         Trusted Domains
--------------  ----------------------------------
vs1             CIFS1.EXAMPLE.COM
----

.Related information

xref:add-remove-replace-trusted-domains-preferred-lists-task.adoc[Add, remove, or replace trusted domains in preferred lists]


// 2025 June 18, ONTAPDOC-2981