---
permalink: smb-admin/display-central-access-policy-rules-task.html
sidebar: sidebar
keywords: display, detail, information, central, access, policy, rule, policies, define, active, directory, group, object, display information about central access policy rules
summary: "You can display detailed information about central access policy rules that are associated with central access policies defined in Active Directory. You can also display information about central access policies rules that are applied to the CIFS server through central access policy GPOs (group policy objects)."
---
= Display information about ONTAP SMB central access policy rules
:icons: font
:imagesdir: ../media/

[.lead]
You can display detailed information about central access policy rules that are associated with central access policies defined in Active Directory. You can also display information about central access policies rules that are applied to the CIFS server through central access policy GPOs (group policy objects).

.About this task

You can display detailed information about defined and applied central access policy rules. By default, the following information is displayed:

* Vserver name
* Name of the central access rule
* Description
* Creation time
* Modification time
* Current permissions
* Proposed permissions
* Target resources

.Step

[options="header"]
|===
| If you want to display information about all central access policy rules associated with central access policies...| Enter the command...
a|
Defined in Active Directory
a|
`vserver cifs group-policy central-access-rule show-defined -vserver vserver_name`
a|
Applied to a CIFS server
a|
`vserver cifs group-policy central-access-rule show-applied -vserver vserver_name`
|===

.Example

The following example displays information for all central access policy rules associated with central access policies defined in Active Directory:

----
cluster1::> vserver cifs group-policy central-access-rule show-defined

Vserver    Name
---------- --------------------
vs1        r1
           Description: rule #1
         Creation Time: Tue Oct 22 09:33:48 2013
     Modification Time: Tue Oct 22 09:33:48 2013
   Current Permissions: O:SYG:SYD:AR(A;;FA;;;WD)
  Proposed Permissions: O:SYG:SYD:(A;;FA;;;OW)(A;;FA;;;BA)(A;;FA;;;SY)

vs1        r2
           Description: rule #2
         Creation Time: Tue Oct 22 10:27:57 2013
     Modification Time: Tue Oct 22 10:27:57 2013
   Current Permissions: O:SYG:SYD:AR(A;;FA;;;WD)
  Proposed Permissions: O:SYG:SYD:(A;;FA;;;OW)(A;;FA;;;BA)(A;;FA;;;SY)
----

The following example displays information for all central access policy rules associated with central access policies applied to storage virtual machines (SVMs) on the cluster:

----
cluster1::> vserver cifs group-policy central-access-rule show-applied

Vserver    Name
---------- --------------------
vs1        r1
           Description: rule #1
         Creation Time: Tue Oct 22 09:33:48 2013
     Modification Time: Tue Oct 22 09:33:48 2013
   Current Permissions: O:SYG:SYD:AR(A;;FA;;;WD)
  Proposed Permissions: O:SYG:SYD:(A;;FA;;;OW)(A;;FA;;;BA)(A;;FA;;;SY)

vs1        r2
           Description: rule #2
         Creation Time: Tue Oct 22 10:27:57 2013
     Modification Time: Tue Oct 22 10:27:57 2013
   Current Permissions: O:SYG:SYD:AR(A;;FA;;;WD)
  Proposed Permissions: O:SYG:SYD:(A;;FA;;;OW)(A;;FA;;;BA)(A;;FA;;;SY)
----

.Related information

xref:secure-file-access-dynamic-access-control-concept.adoc[Securing file access by using Dynamic Access Control (DAC)]

xref:display-gpo-config-task.adoc[Display information about GPO configurations]

xref:display-central-access-policies-task.adoc[Display information about central access policies]


// 2025 June 17, ONTAPDOC-2981