---
permalink: smb-admin/display-members-local-groups-task.html
sidebar: sidebar
keywords: display, list, member, local, group, configure, cluster, storage, virtual, machine, svm, information, troubleshoot, file-access, issue, user-rights, privilege, display information about members of local groups
summary: "You can display a list of all members of local groups configured on the cluster or on a specified storage virtual machine (SVM). This information can be useful when troubleshooting file-access issues or user-rights (privilege) issues."
---
= Display ONTAP SMB information about members of local groups
:icons: font
:imagesdir: ../media/

[.lead]
You can display a list of all members of local groups configured on the cluster or on a specified storage virtual machine (SVM). This information can be useful when troubleshooting file-access issues or user-rights (privilege) issues.

.Step

. Perform one of the following actions:
+
[options="header"]
|===
| If you want to display information about...| Enter the command...
a|
Members of all local groups on the cluster
a|
`vserver cifs users-and-groups local-group show-members`
a|
Members of all local groups on the SVM
a|
`vserver cifs users-and-groups local-group show-members -vserver _vserver_name_`
|===

.Example

The following example displays information about members of all local groups on SVM vs1:

----
cluster1::> vserver cifs users-and-groups local-group show-members -vserver vs1
Vserver   Group Name                   Members
--------- ---------------------------- ------------------------
vs1       BUILTIN\Administrators       CIFS_SERVER\Administrator
                                       AD_DOMAIN\Domain Admins
                                       AD_DOMAIN\dom_grp1
          BUILTIN\Users                AD_DOMAIN\Domain Users
                                       AD_DOMAIN\dom_usr1
          CIFS_SERVER\engineering      CIFS_SERVER\james
----

// 2025 May 21, ONTAPDOC-2981