---
permalink: smb-admin/display-local-users-task.html
sidebar: sidebar
keywords: display, list, local, user, summary, form, determine, account, setting, configure, specific, user, detail, troubleshoot, authentication, file, access, issue, display information about local users
summary: "You can display a list of all local users in a summary form. If you want to determine which account settings are configured for a specific user, you can display detailed account information for that user as well as the account information for multiple users. This information can help you determine if you need to modify a user’s settings, and also to troubleshoot authentication or file access issues."
---
= Display information about local users in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
You can display a list of all local users in a summary form. If you want to determine which account settings are configured for a specific user, you can display detailed account information for that user as well as the account information for multiple users. This information can help you determine if you need to modify a user's settings, and also to troubleshoot authentication or file access issues.

.About this task

Information about a user's password is never displayed.

.Step

. Perform one of the following actions:
+
[options="header"]
|===
| If you want to...| Enter the command...
a|
Display information about all users on the storage virtual machine (SVM)
a|
`vserver cifs users-and-groups local-user show -vserver _vserver_name_`
a|
Display detailed account information for a user
a|
`vserver cifs users-and-groups local-user show -instance -vserver _vserver_name_ -user-name _user_name_`
|===
There are other optional parameters that you can choose when you run the command. 
Learn more about `vserver cifs` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs[ONTAP command reference^].

.Example

The following example displays information about all local users on SVM vs1:

----
cluster1::> vserver cifs users-and-groups local-user show -vserver vs1
Vserver  User Name                   Full Name     Description
-------- --------------------------- ------------- -------------
vs1      CIFS_SERVER\Administrator   James Smith   Built-in administrator account
vs1      CIFS_SERVER\sue             Sue   Jones
----


// 2025 Jan 16, ONTAPDOC-2569