---
permalink: smb-admin/enable-disable-dynamic-access-control-task.html
sidebar: sidebar
keywords: option, enable, dynamic, access, control, dac, secure, object, cifs, server, disable, default, enable or disable dynamic access control
summary: "The option that enables you to use Dynamic Access Control (DAC) to secure objects on your CIFS server is disabled by default. You must enable the option if you want to use Dynamic Access Control on your CIFS server. If you later decide that you do not want to use Dynamic Access Control to secure objects stored on the CIFS server, you can disable the option."
---
= Enable or disable Dynamic Access Control overview 
:icons: font
:imagesdir: ../media/

[.lead]
The option that enables you to use Dynamic Access Control (DAC) to secure objects on your CIFS server is disabled by default. You must enable the option if you want to use Dynamic Access Control on your CIFS server. If you later decide that you do not want to use Dynamic Access Control to secure objects stored on the CIFS server, you can disable the option.

You can find information about how to configure Dynamic Access Control on Active Directory in the Microsoft TechNet Library.

http://technet.microsoft.com/library/hh831717.aspx[Microsoft TechNet: Dynamic Access Control Scenario Overview^]

.About this task

Once Dynamic Access Control is enabled, the file system can contain ACLs with Dynamic Access Control-related entries. If Dynamic Access Control is disabled, the current Dynamic Access Control entries will be ignored, and new ones will not be allowed.

This option is available only at the advanced privilege level.

.Step

. Set the privilege level to advanced: `set -privilege advanced`
. Perform one of the following actions:
+
|===
| If you want Dynamic Access Control to be...| Enter the command...
a|
Enabled
a|
`vserver cifs options modify -vserver _vserver_name_ -is-dac-enabled true`
a|
Disabled
a|
`vserver cifs options modify -vserver _vserver_name_ -is-dac-enabled false`
|===

. Return to the administrator privilege level: `set -privilege admin`

.Related information

xref:configure-central-access-policies-secure-data-task.adoc[Configuring central access policies to secure data on CIFS servers]

//1-29-25 ONTAPDOC-1506