---
permalink: smb-admin/enable-metadata-cache-task.html
sidebar: sidebar
keywords: smb, performance, client, enabling, enable, metadata, cache, disable, enable the smb metadata cache
summary: "You can improve SMB performance for SMB 1.0 clients by enabling the SMB metadata cache. By default, SMB metadata caching is disabled."
---
= Enable the SMB metadata cache
:icons: font
:imagesdir: ../media/

[.lead]
You can improve SMB performance for SMB 1.0 clients by enabling the SMB metadata cache. By default, SMB metadata caching is disabled.

.Step

. Perform the desired action:
+
[options="header"]
|===
| If you want to...| Enter the command...
a|
Enable SMB metadata caching when you create a share
a|
`vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -share-properties attributecache`
a|
Enable SMB metadata caching on an existing share
a|
`vserver cifs share properties add -vserver _vserver_name_ -share-name _share_name_ -share-properties attributecache`
|===

.Related information

xref:configure-lifetime-metadata-cache-entries-task.adoc[Configuring the lifetime of SMB metadata cache entries]

xref:add-remove-share-properties-existing-share-task.adoc[Adding or removing share properties on an existing SMB share]
