---
permalink: smb-admin/enable-disable-local-users-groups-task.html
sidebar: sidebar
keywords: smb, access, storage, virtual, machine, svm, functionality, default
summary: "You can enable or disable local users and groups for SMB access on storage virtual machines (SVMs). Local users and groups functionality is enabled by default."
---
= Enable or disable local users and groups on ONTAP SMB servers
:icons: font
:imagesdir: ../media/

[.lead]
You can enable or disable local users and groups for SMB access on storage virtual machines (SVMs). Local users and groups functionality is enabled by default.

.About this task

You can use local users and groups when configuring SMB share and NTFS file permissions and can optionally use local users for authentication when creating an SMB connection. To use local users for authentication, you must also enable the local users and groups authentication option.

.Steps

. Set the privilege level to advanced: `set -privilege advanced`
. Perform one of the following actions:
+
[options="header"]
|===
| If you want local users and groups to be...| Enter the command...
a|
Enabled
a|
`vserver cifs options modify -vserver _vserver_name_ -is-local-users-and-groups-enabled true`
a|
Disabled
a|
`vserver cifs options modify -vserver _vserver_name_ -is-local-users-and-groups-enabled false`
|===

. Return to the admin privilege level: `set -privilege admin`

.Example

The following example enables local users and groups functionality on SVM vs1:

----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-local-users-and-groups-enabled true

cluster1::*> set -privilege admin
----

.Related information

xref:enable-disable-local-user-authentication-task.adoc[Enable or disable local user authentication]

xref:enable-disable-local-user-accounts-task.adoc[Enable or disable local user accounts]

// 2025 May 20, ONTAPDOC-2981