---
permalink: smb-admin/enable-netbios-name-service-task.html
sidebar: sidebar
keywords: ontap, netbios, name, service, nbns, windows, internet, name, service, wins, disable, default, cifs-enable, storage, virtual, machine, svm, registration, broadcast, network, server, wnable the netbios name service
summary: "Beginning with ONTAP 9, the NetBios name service (NBNS, sometimes called Windows Internet Name Service or WINS) is disabled by default. Previously, CIFS-enabled storage virtual machines (SVMs) sent name registration broadcasts regardless of whether WINS was enabled on a network. To limit such broadcasts to configurations where NBNS is required, you must enable NBNS explicitly for new CIFS servers."
---
= Enable the ONTAP SMB NetBios name service
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9, the NetBios name service (NBNS, sometimes called Windows Internet Name Service or WINS) is disabled by default. Previously, CIFS-enabled storage virtual machines (SVMs) sent name registration broadcasts regardless of whether WINS was enabled on a network. To limit such broadcasts to configurations where NBNS is required, you must enable NBNS explicitly for new CIFS servers.

.Before you begin

* If you are already using NBNS and you upgrade to ONTAP 9, it is not necessary to complete this task. NBNS will continue to work as before.
* NBNS is enabled over UDP (port 137).
* NBNS over IPv6 is not supported.

.Steps

. Set the privilege level to advanced.
+
----
set -privilege advanced
----

. Enable NBNS on a CIFS server.
+
----
vserver cifs options  modify -vserver <vserver name> -is-nbns-enabled true
----

. Return to the admin privilege level.
+
----
set -privilege admin
----

// 2025 May 15, ONTAPDOC-2981