---
permalink: smb-admin/enable-disable-ntfs-acls-unix-security-task.html
sidebar: sidebar
keywords: enable, disable, presentation, ntfs, acl, smb, client, unix, security-style, data, volume, enable or disable the presentation of ntfs acls for unix security-style data
summary: "You can enable or disable the presentation of NTFS ACLs to SMB clients for UNIX security-style data (UNIX security-style volumes and mixed security-style volumes with UNIX effective security)."
---
= Configure the presentation of NTFS ACLs to ONTAP SMB clients for UNIX security-style data 
:icons: font
:imagesdir: ../media/

[.lead]
You can enable or disable the presentation of NTFS ACLs to SMB clients for UNIX security-style data (UNIX security-style volumes and mixed security-style volumes with UNIX effective security).

.About this task

If you enable this option, ONTAP presents files and folders on volumes with effective UNIX security style to SMB clients as having NTFS ACLs. If you disable this option, the volumes are presented as FAT volumes to SMB clients. The default is to present NTFS ACLs to SMB clients.

.Steps

. Set the privilege level to advanced: `set -privilege advanced`
. Configure the UNIX NTFS ACL option setting: `vserver cifs options modify -vserver _vserver_name_ -is-unix-nt-acl-enabled {true|false}`
. Verify that the option is set to the desired value: `vserver cifs options show -vserver _vserver_name_`
. Return to the admin privilege level: `set -privilege admin`

// 2025 Apr 30, ONTAPDOC-2981