---
permalink: smb-admin/enable-ldap-over-ssl-tls-task.html
sidebar: sidebar
keywords: cifs, smb, server, tls, secure, communication, active, directory, ldap, security, enable ldap over tls on the cifs server
summary: "Before your SMB server can use TLS for secure communication with an Active Directory LDAP server, you must modify the SMB server security settings to enable LDAP over TLS."
---
= Enable LDAP over TLS on the  server
:icons: font
:imagesdir: ../media/

[.lead]
Before your SMB server can use TLS for secure communication with an Active Directory LDAP server, you must modify the SMB server security settings to enable LDAP over TLS.

Beginning with ONTAP 9.10.1, LDAP channel binding is supported by default for both Active Directory (AD) and name services LDAP connections. ONTAP will try channel binding with LDAP connections only if Start-TLS or LDAPS is enabled along with session security set to either sign or seal. To disable or reenable LDAP channel binding with AD servers, use the `-try-channel-binding-for-ad-ldap` parameter with the `vserver cifs security modify` command.

To learn more, see:

* link:../nfs-admin/using-ldap-concept.html[LDAP overview]
* link:https://support.microsoft.com/en-us/topic/2020-ldap-channel-binding-and-ldap-signing-requirements-for-windows-ef185fb8-00f7-167d-744c-f299a66fc00a[2020 LDAP channel binding and LDAP signing requirements for Windows^].

.Steps

. Configure the SMB server security setting that allows secure LDAP communication with Active Directory LDAP servers: `vserver cifs security modify -vserver _vserver_name_ -use-start-tls-for-ad-ldap true`
. Verify that the LDAP over TLS security setting is set to `true`: `vserver cifs security show -vserver _vserver_name_`
+
[NOTE]
====
If the SVM uses the same LDAP server for querying name-mapping or other UNIX information (such as users, groups, and netgroups), then you must also modify the `-use-start-tls` option by using the `vserver services name-service ldap client modify` command.
====

// 2022 Dec 01, Jira ONTAPDOC-722 
// 2021-11-15, BURT 1402470
