---
permalink: smb-admin/enable-disable-gpo-support-task.html
sidebar: sidebar
keywords: enable, disable, group, policy, object, gpo, support, cifs, server, applicable, define, policy, organizational, unit, ou, enable or disable gpo support on a cifs server
summary: "You can enable or disable Group Policy Object (GPO) support on a CIFS server. If you enable GPO support on a CIFS server, the applicable GPOs that are defined on the group policy—the policy that is applied to the organizational unit (OU) that contains the CIFS server computer object—are applied to the CIFS server."
---
= Enable or disable GPO support on ONTAP SMB servers
:icons: font
:imagesdir: ../media/

[.lead]
You can enable or disable Group Policy Object (GPO) support on a CIFS server. If you enable GPO support on a CIFS server, the applicable GPOs that are defined on the group policy--the policy that is applied to the organizational unit (OU) that contains the CIFS server computer object--are applied to the CIFS server.

.About this task

[NOTE]
====
GPOs cannot be enabled on CIFS servers in workgroup mode.
====

.Steps

. Perform one of the following actions:
+
[options="header"]
|===
| If you want to...| Enter the command...
a|
Enable GPOs
a|
`vserver cifs group-policy modify -vserver _vserver_name_ -status enabled`
a|
Disable GPOs
a|
`vserver cifs group-policy modify -vserver _vserver_name_ -status disabled`
|===

. Verify that GPO support is in the desired state: `vserver cifs group-policy show -vserver +vserver_name_`
+
Group Policy Status for CIFS servers in workgroup mode is displayed as "`disabled`".

.Example

The following example enables GPO support on storage virtual machine (SVM) vs1:

----
cluster1::> vserver cifs group-policy modify -vserver vs1 -status enabled

cluster1::> vserver cifs group-policy show -vserver vs1

            Vserver: vs1
Group Policy Status: enabled
----

.Related information

xref:supported-gpos-concept.adoc[Learn about supported GPOs]

xref:requirements-gpos-concept.adoc[Server requirements for GPOs]

xref:gpos-updated-server-concept.adoc[Learn about updating GPOs on SMB servers]

xref:manual-update-gpo-settings-task.adoc[Manually update GPO settings on SMB servers]

xref:display-gpo-config-task.adoc[Display information about GPO configurations]


// 2025 June 17, ONTAPDOC-2981