---
permalink: smb-admin/enable-disable-local-user-authentication-task.html
sidebar: sidebar
keywords: enable, disable, local, user, authentication, smb, access, storage, virtual, machine, svm, domain, controller, domain-level, level, enable or disable local user authentication
summary: "You can enable or disable local user authentication for SMB access on storage virtual machines (SVMs). The default is to allow local user authentication, which is useful when the SVM cannot contact a domain controller or if you choose not to use domain-level access controls."
---
= Enable or disable local user authentication on ONTAP SMB servers
:icons: font
:imagesdir: ../media/

[.lead]
You can enable or disable local user authentication for SMB access on storage virtual machines (SVMs). The default is to allow local user authentication, which is useful when the SVM cannot contact a domain controller or if you choose not to use domain-level access controls.

.Before you begin

Local users and groups functionality must be enabled on the CIFS server.

.About this task

You can enable or disable local user authentication at any time. If you want to use local users for authentication when creating an SMB connection, you must also enable the CIFS server's local users and groups option.

.Steps

. Set the privilege level to advanced: `set -privilege advanced`
. Perform one of the following actions:
+
[options="header"]
|===
| If you want local authentication to be...| Enter the command...
a|
Enabled
a|
`vserver cifs options modify -vserver _vserver_name_ -is-local-auth-enabled true`
a|
Disabled
a|
`vserver cifs options modify -vserver _vserver_name_ -is-local-auth-enabled false`
|===

. Return to the admin privilege level: `set -privilege admin`

.Example

The following example enables local user authentication on SVM vs1:

----
cluster1::>set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-local-auth-enabled true

cluster1::*> set -privilege admin
----

.Related information

* xref:local-user-authentication-concept.adoc[Learn about local user authentication]

* xref:enable-disable-local-users-groups-task.adoc[Enable or disable local users and groups on servers]


// 2025 June 18, ONTAPDOC-2981