---
permalink: smb-admin/enable-disable-automatic-node-referrals-task.html
sidebar: sidebar
keywords: enable, smb, automatic, node, referral, client, access, performance, disable, ontap, enable or disable smb automatic node referrals
summary: "You can enable SMB automatic node referrals to increase SMB client access performance. You can disable automatic node referrals if you do not want ONTAP to make referrals to SMB clients."
---
= Enable or disable SMB automatic node referrals
:icons: font
:imagesdir: ../media/

[.lead]
You can enable SMB automatic node referrals to increase SMB client access performance. You can disable automatic node referrals if you do not want ONTAP to make referrals to SMB clients.

.Before you begin

A CIFS server must be configured and running on the storage virtual machine (SVM).

.About this task

The SMB automatic node referrals functionality is disabled by default. You can enable or disable this functionality on each SVM as required.

This option is available at the advanced privilege level.

.Steps

. Set the privilege level to advanced: `set -privilege advanced`
. Enable or disable SMB automatic node referrals as required:
+
[options="header"]
|===
| If you want SMB automatic node referrals to be...| Enter the following command...
a|
Enabled
a|
`vserver cifs options modify -vserver vserver_name -is-referral-enabled true`
a|
Disabled
a|
`vserver cifs options modify -vserver vserver_name -is-referral-enabled false`
|===
The option setting takes effect for new SMB sessions. Clients with existing connection can use node referral only when their existing cache timeout expires.

. Switch to the admin privilege level: `set -privilege admin`

.Related information

xref:server-options-reference.adoc[Available SMB server options]
