---
permalink: smb-admin/enable-disable-multidomain-name-mapping-searches-task.html
sidebar: sidebar
keywords: multidomain, name, mapping, search, wild, card, domain, portion, windows, configure, configuring, unix, user, bidirectional, enable, disable, enable or disable multidomain name mapping searches
summary: "With multidomain name mapping searches, you can use a wild card (*) in the domain portion of a Windows name when configuring UNIX user to Windows user name mapping. Using a wild card (*) in the domain portion of the name enables ONTAP to search all domains that have a bidirectional trust with the domain that contains the CIFS server’s computer account."
---
= Enable or disable ONTAP SMB multidomain name mapping searches
:icons: font
:imagesdir: ../media/

[.lead]
With multidomain name mapping searches, you can use a wild card (\*) in the domain portion of a Windows name when configuring UNIX user to Windows user name mapping. Using a wild card (*) in the domain portion of the name enables ONTAP to search all domains that have a bidirectional trust with the domain that contains the CIFS server's computer account.

.About this task

As an alternative to searching all bidirectionally trusted domains, you can configure a list of preferred trusted domains. When a list of preferred trusted domains is configured, ONTAP uses the preferred trusted domain list instead of the discovered bidirectionally trusted domains to perform multidomain name mapping searches.

* Multidomain name mapping searches are enabled by default.
* This option is available at the advanced privilege level.

.Steps

. Set the privilege level to advanced: `set -privilege advanced`
. Perform one of the following actions:
+
[options="header"]
|===
| If you want multidomain name mapping searches to be...| Enter the command...
a|
Enabled
a|
`vserver cifs options modify -vserver _vserver_name_ -is-trusted-domain-enum-search-enabled true`
a|
Disabled
a|
`vserver cifs options modify -vserver _vserver_name_ -is-trusted-domain-enum-search-enabled false`
|===

. Return to the admin privilege level: `set -privilege admin`

.Related information

xref:server-options-reference.adoc[Available SMB server options]

// 2025 May 15, ONTAPDOC-2981