---
permalink: smb-admin/guidelines-reverting-local-users-groups-concept.html
sidebar: sidebar
keywords: plan, revert, cluster, ontap, release, support, local, user, group, manage, consideration, guidelines for reverting
summary: "If you plan to revert the cluster to an ONTAP release that does not support local users and groups and local users and groups are being used to manage file access or user rights, you must be aware of certain considerations."
---
= Learn about reverting ONTAP SMB clusters
:icons: font
:imagesdir: ../media/

[.lead]
If you plan to revert the cluster to an ONTAP release that does not support local users and groups and local users and groups are being used to manage file access or user rights, you must be aware of certain considerations.

* Due to security reasons, information about configured local users, groups, and privileges are not deleted when ONTAP is reverted to a version that does not support local users and groups functionality.
* Upon a revert to a prior major version of ONTAP, ONTAP does not use local users and groups during authentication and credential creation.
* Local users and groups are not removed from file and folder ACLs.
* File access requests that depend on access being granted because of permissions granted to local users or groups are denied.
+
To allow access, you must reconfigure file permissions to allow access based on domain objects instead of local user and group objects.

// 2025 May 20, ONTAPDOC-2981