---
permalink: smb-admin/home-directory-config-concept.html
sidebar: sidebar
keywords: create, additional, home, directory, configuration, variable, enable, customize, additional home directory configurations
summary: "You can create additional home directory configurations using the %w, %d, and %u variables, which enables you to customize the home directory configuration to meet your needs."
---
= Learn about additional ONTAP SMB home directory configurations
:icons: font
:imagesdir: ../media/

[.lead]
You can create additional home directory configurations using the `%w`, `%d`, and `%u` variables, which enables you to customize the home directory configuration to meet your needs.

You can create a number of home directory configurations using a combination of variables and static strings in the share names and search paths. The following table provides some examples illustrating how to create different home directory configurations:

[options="header"]
|===
| Paths created when `/vol1/user` contains home directories...| Share command...
a|
To create a share path `\\vs1\~win_username` that directs the user to `/vol1/user/win_username`
a|
`vserver cifs share create -share-name ~%w -path %w -share-properties oplocks,browsable,changenotify,homedirectory`
a|
To create a share path `\\vs1\win_username` that directs the user to `/vol1/user/domain/win_username`
a|
`vserver cifs share create -share-name %w -path %d/%w -share-properties oplocks,browsable,changenotify,homedirectory`
a|
To create a share path `\\vs1\win_username` that directs the user to `/vol1/user/unix_username`
a|
`vserver cifs share create -share-name %w -path %u -share-properties oplocks,browsable,changenotify,homedirectory`
a|
To create a share path `\\vs1\unix_username` that directs the user to `/vol1/user/unix_username`
a|
`vserver cifs share create -share-name %u -path %u -share-properties oplocks,browsable,changenotify,homedirectory`
|===


// 2025 June 04, ONTAPDOC-2981