---
permalink: smb-admin/ipv6-connect-external-servers-concept.html
sidebar: sidebar
keywords: create, configuration, requirement, aware, cifs, server, ipv6, connection, external, server, how cifs servers use ipv6 to connect to external servers
summary: "To create a configuration that meets your requirements, you must be aware of how CIFS servers use IPv6 when making connections to external servers."
---
= Learn how ONTAP SMB servers use IPv6 to connect to external servers
:icons: font
:imagesdir: ../media/

[.lead]
To create a configuration that meets your requirements, you must be aware of how CIFS servers use IPv6 when making connections to external servers.

* Source address selection
+
If an attempt is made to connect to an external server, the source address selected must be of the same type as the destination address. For example, if connecting to an IPv6 address, the storage virtual machine (SVM) hosting the CIFS server must have a data LIF or management LIF that has an IPv6 address to use as the source address. Similarly, if connecting to an IPv4 address, the SVM must have a data LIF or management LIF that has an IPv4 address to use as the source address.

* For servers dynamically discovered using DNS, server discovery is performed as follows:
 ** If IPv6 is disabled on the cluster, only IPv4 servers addresses are discovered.
 ** If IPv6 is enabled on the cluster, both IPv4 and IPv6 server addresses are discovered. Either type might be used depending upon the suitability of the server to which the address belongs and the availability of IPv6 or IPv4 data or management LIFs.
Dynamic server discovery is used for discovering Domain Controllers and their associated services, such as LSA, NETLOGON, Kerberos, and LDAP.
* DNS server connectivity
+
Whether the SVM uses IPv6 when connecting to a DNS server depends on the DNS name services configuration. If DNS services are configured to use IPv6 addresses, connections are made by using IPv6. If desired, the DNS name services configuration can use IPv4 addresses so that connections to DNS servers continue to use IPv4 addresses. Combinations of IPv4 and IPv6 addresses can be specified when configuring DNS name services.

* LDAP server connectivity
+
Whether the SVM uses IPv6 when connecting to an LDAP server depends on the LDAP client configuration. If the LDAP client is configured to use IPv6 addresses, connections are made by using IPv6. If desired, the LDAP client configuration can use IPv4 addresses so that connections to LDAP servers continue to use IPv4 addresses. Combinations of IPv4 and IPv6 addresses can be specified when configuring the LDAP client configuration.
+
[NOTE]
====
The LDAP client configuration is used when configuring LDAP for UNIX user, group, and netgroup name services.
====

* NIS server connectivity
+
Whether the SVM uses IPv6 when connecting to a NIS server depends on the NIS name services configuration. If NIS services are configured to use IPv6 addresses, connections are made by using IPv6. If desired, the NIS name services configuration can use IPv4 addresses so that connections to NIS servers continue to use IPv4 addresses. Combinations of IPv4 and IPv6 addresses can be specified when configuring NIS name services.
+
[NOTE]
====
NIS name services are used for storing and managing UNIX user, group, netgroup, and host name objects.
====

.Related information

* xref:enable-ipv6-task.adoc[Enable IPv6 for servers]

* xref:monitor-display-ipv6-sessions-task.adoc[Monitor and display information about IPv6 sessions]


// 2025 June 18, ONTAPDOC-2981