---
permalink: smb-admin/manage-smb-level-acls-concept.html
sidebar: sidebar
keywords: change, share-level, acl, user, access, right, share, configure, windows, unix, group, guidelines for managing smb share-level acls
summary: "You can change share-level ACLs to give users more or less access rights to the share. You can configure share-level ACLs by using either Windows users and groups or UNIX users and groups."
---
= Guidelines for managing SMB share-level ACLs
:icons: font
:imagesdir: ../media/

[.lead]
You can change share-level ACLs to give users more or less access rights to the share. You can configure share-level ACLs by using either Windows users and groups or UNIX users and groups.

By default, the share-level ACL gives full control to the standard group named Everyone. Full control in the ACL means that all users in the domain and all trusted domains have full access to the share. You can control the level of access for a share-level ACL by using the link:../smb-admin/create-share-access-control-lists-task.html[Microsoft Management Console (MMC) on a Windows client or the ONTAP command line]. 

The following guidelines apply when you use the MMC:

* The user and group names specified must be Windows names.
* You can specify only Windows permissions.

The following guidelines apply when you use the ONTAP command line:

* The user and group names specified can be Windows names or UNIX names.
+
If a user and group type is not specified when creating or modifying ACLs, the default type is Windows users and groups.

* You can specify only Windows permissions.

// 2024 Sep 17, gh-1474, gh-1473