---
permalink: smb-admin/manage-acls-dynamic-access-control-aces-task.html
sidebar: sidebar
keywords: resource, acl, applied, apply, dynamic, access, control, ace, disable, dynamic, storage, virtual, machine, svm, remove, non-dynamic, manage acls that contain dynamic access control aces when dynamic access control is disabled
summary: "If you have resources that have ACLs applied with Dynamic Access Control ACEs and you disable Dynamic Access Control on the storage virtual machine (SVM), you must remove the Dynamic Access Control ACEs before you can manage the non-Dynamic Access Control ACEs on that resource."
---
= Manage ACLs containing DAC ACEs when Dynamic Access Control is disabled on ONTAP SMB servers
:icons: font
:imagesdir: ../media/

[.lead]
If you have resources that have ACLs applied with Dynamic Access Control ACEs and you disable Dynamic Access Control on the storage virtual machine (SVM), you must remove the Dynamic Access Control ACEs before you can manage the non-Dynamic Access Control ACEs on that resource.

.About this task

After Dynamic Access Control is disabled, you cannot remove existing non-Dynamic Access Control ACEs or add new non-Dynamic Access Control ACEs until you have removed the existing Dynamic Access Control ACEs.

You can use whichever tool you normally use to manage ACLs to perform these steps.

.Steps

. Determine what Dynamic Access Control ACEs are applied to the resource.
. Remove the Dynamic Access Control ACEs from the resource.
. Add or remove non-Dynamic Access Control ACEs as desired from the resource.


// 2025 May 19, ONTAPDOC-2981