---
permalink: smb-admin/manage-file-security-clients-unix-style-concept.html
sidebar: sidebar
keywords: present, file, security, smb, client, unix, security-style, data, disabling, disable, presentation, ntfs, acl, client, advantage, setting, business, requirement, manage how file security is presented to smb clients for unix security-style data
summary: "You can choose how you want to present file security to SMB clients for UNIX security-style data by enabling or disabling the presentation of NTFS ACLs to SMB clients. There are advantages with each setting, which you should understand to choose the setting best suited for your business requirements."
---
= Learn about presenting ONTAP file security to SMB clients for UNIX security-style data
:icons: font
:imagesdir: ../media/

[.lead]
You can choose how you want to present file security to SMB clients for UNIX security-style data by enabling or disabling the presentation of NTFS ACLs to SMB clients. There are advantages with each setting, which you should understand to choose the setting best suited for your business requirements.

By default, ONTAP presents UNIX permissions on UNIX security-style volumes to SMB clients as NTFS ACLs. There are scenarios where this is desirable, including the following:

* You want to view and edit UNIX permissions by using the *Security* tab in the Windows Properties box.
+
You cannot modify permissions from a Windows client if the operation is not permitted by the UNIX system. For example, you cannot change the ownership of a file you do not own, because the UNIX system does not permit this operation. This restriction prevents SMB clients from bypassing UNIX permissions set on the files and folders.

* Users are editing and saving files on the UNIX security-style volume by using certain Windows applications, for example Microsoft Office, where ONTAP must preserve UNIX permissions during save operations.
* There are certain Windows applications in your environment that expect to read NTFS ACLs on files they use.

Under certain circumstances, you might want to disable the presentation of UNIX permissions as NTFS ACLs. If this functionality is disabled, ONTAP presents UNIX security-style volumes as FAT volumes to SMB clients. There are specific reasons why you might want to present UNIX security-style volumes as FAT volumes to SMB clients:

* You only change UNIX permissions by using mounts on UNIX clients.
+
The Security tab is not available when a UNIX security-style volume is mapped on an SMB client. The mapped drive appears to be formatted with the FAT file system, which has no file permissions.

* You are using applications over SMB that set NTFS ACLs on accessed files and folders, which can fail if the data resides on UNIX security-style volumes.
+
If ONTAP reports the volume as FAT, the application does not try to change an ACL.

.Related information

xref:configure-security-styles-task.adoc[Configure security styles on ONTAP NFS FlexVol volumes]

xref:configure-security-styles-qtrees-task.adoc[Configure security styles on ONTAP NFS qtrees]

// 2025 May 29, ONTAPDOC-2982
// 2025 Apr 30, ONTAPDOC-2981