---
permalink: smb-admin/modify-local-user-accounts-reference.html
sidebar: sidebar
keywords: modify, local, user, account, change, exist, name, description, enable, disable, rename, compromise, administrative, modify local user accounts
summary: "You can modify a local user account if you want to change an existing user’s full name or description, and if you want to enable or disable the user account. You can also rename a local user account if the user’s name is compromised or if a name change is needed for administrative purposes."
---
= Modify local user accounts
:icons: font
:imagesdir: ../media/

[.lead]
You can modify a local user account if you want to change an existing user's full name or description, and if you want to enable or disable the user account. You can also rename a local user account if the user's name is compromised or if a name change is needed for administrative purposes.

[options="header"]
|===
| If you want to...| Enter the command...
a|
Modify the local user's full name
a|
`vserver cifs users-and-groups local-user modify -vserver vserver_name -user-name user_name ‑full-name text` If the full name contains a space, then it must be enclosed within double quotation marks.

a|
Modify the local user's description
a|
`vserver cifs users-and-groups local-user modify -vserver vserver_name -user-name user_name ‑description text` If the description contains a space, then it must be enclosed within double quotation marks.

a|
Enable or disable the local user account
a|
`vserver cifs users-and-groups local-user modify -vserver vserver_name -user-name user_name -is-account-disabled {true\|false}`
a|
Rename the local user account
a|
`vserver cifs users-and-groups local-user rename -vserver vserver_name -user-name user_name -new-user-name new_user_name` When renaming a local user, the new user name must remain associated with the same CIFS server as the old user name.

|===

.Example

The following example renames the local user "`CIFS_SERVER\sue`" to "`CIFS_SERVER\sue_new`" on storage virtual machine (SVM, formerly known as Vserver) vs1:

----
cluster1::> vserver cifs users-and-groups local-user rename -user-name CIFS_SERVER\sue -new-user-name CIFS_SERVER\sue_new -vserver vs1
----
