---
permalink: smb-admin/modify-dynamic-dns-domain-before-moving-server-task.html
sidebar: sidebar
keywords: active, directory-integrated, dns, server, dynamic, register, smb, server, record, modify, ddns, storage, virtual, machine, svm, modify the dynamic dns domain on the svm before moving the smb server
summary: "If you want the Active Directory-integrated DNS server to dynamically register the SMB server’s DNS records in DNS when you move the SMB server to another domain, you must modify dynamic DNS (DDNS) on the storage virtual machine (SVM) before moving the SMB server."
---
= Modify the dynamic DNS domain on the SVM before moving the SMB server
:icons: font
:imagesdir: ../media/

[.lead]
If you want the Active Directory-integrated DNS server to dynamically register the SMB server's DNS records in DNS when you move the SMB server to another domain, you must modify dynamic DNS (DDNS) on the storage virtual machine (SVM) before moving the SMB server.

.Before you begin

DNS name services must be modified on the SVM to use the DNS domain that contains the service location records for the new domain that will contain the SMB server computer account. If you are using secure DDNS, you must use Active Directory-integrated DNS name servers.

.About this task

Although DDNS (if configured on the SVM) automatically adds the DNS records for data LIFs to the new domain, the DNS records for the original domain are not automatically deleted from the original DNS server. You must delete them manually.

To complete your DDNS modifications before moving the SMB server, see the following topic:

link:../networking/configure_dynamic_dns_services.html[Configure dynamic DNS services]
