---
permalink: smb-admin/name-mapping-concept.html
sidebar: sidebar
keywords: ontap, map, credential, user, local, name, map, database, ldap, server, exist, service, configuration, svm, how name mapping works
summary: "When ONTAP has to map credentials for a user, it first checks the local name mapping database and LDAP server for an existing mapping. Whether it checks one or both and in which order is determined by the name service configuration of the SVM."
---
= Learn about ONTAP SMB name mapping
:icons: font
:imagesdir: ../media/

[.lead]
When ONTAP has to map credentials for a user, it first checks the local name mapping database and LDAP server for an existing mapping. Whether it checks one or both and in which order is determined by the name service configuration of the SVM.

* For Windows to UNIX mapping
+
If no mapping is found, ONTAP checks whether the lowercase Windows user name is a valid user name in the UNIX domain. If this does not work, it uses the default UNIX user provided that it is configured. If the default UNIX user is not configured and ONTAP cannot obtain a mapping this way either, mapping fails and an error is returned.

* For UNIX to Windows mapping
+
If no mapping is found, ONTAP tries to find a Windows account that matches the UNIX name in the SMB domain. If this does not work, it uses the default SMB user, provided that it is configured. If the default CIFS user is not configured and ONTAP cannot obtain a mapping this way either, mapping fails and an error is returned.

Machine accounts are mapped to the specified default UNIX user by default. If no default UNIX user is specified, machine account mappings fail.

* Beginning with ONTAP 9.5, you can map machine accounts to users other than the default UNIX user.
* In ONTAP 9.4 and earlier, you cannot map machine accounts to other users.
+
Even if name mappings for machine accounts are defined, the mappings are ignored.

// 2025 May 15, ONTAPDOC-2981