---
permalink: smb-admin/previous-versions-view-manage-snapshot-data-task.html
sidebar: sidebar
keywords: windows, client, machine, previous, version, tab, properties, restore, data, store, snapshot, copies, copy, storage, virtual, machine, svm, administrator, use the previous versions tab to view and manage snapshot copy data
summary: "Users on Windows client machines can use the Previous Versions tab on the Windows Properties window to restore data stored in snapshots without needing to involve the storage virtual machine (SVM) administrator."
---
= Use the Previous Versions tab to view and manage snapshot data
:icons: font
:imagesdir: ../media/

[.lead]
Users on Windows client machines can use the Previous Versions tab on the Windows Properties window to restore data stored in snapshots without needing to involve the storage virtual machine (SVM) administrator.

.About this task

You can only use the Previous Versions tab to view and manage data in snapshots of data stored on the SVM if the administrator has enabled snapshots on the volume containing the share, and if the administrator configures the share to show snapshots.

.Steps

. In Windows Explorer, display the contents of the mapped drive of the data stored on the CIFS server.
. Right-click the file or folder in the mapped network drive whose snapshots you want to view or manage.
. Click *Properties*.
+
Properties for the file or folder you selected are displayed.

. Click the *Previous Versions* tab.
+
A list of available snapshots of the selected file or folder is displayed in the Folder versions: box. The listed snapshots are identified by the snapshot name prefix and the creation timestamp.

. In the *Folder versions:* box, right-click the copy of the file or folder that you want to manage.
. Perform the appropriate action:
+
[options="header"]
|===
| If you want to...| Do the following...
a|
View data from that snapshot
a|
Click *Open*.
a|
Create a copy of data from that snapshot
a|
Click *Copy*.
|===
Data in snapshots is read-only. If you want to make modifications to files and folders listed in the Previous Versions tab, you must save a copy of the files and folders that you want to modify to a writable location and make modifications to the copies.

. After you finish managing snapshot data, close the *Properties* dialog box by clicking *OK*.
+
For more information about using the Previous Versions tab to view and manage snapshot data, consult the Microsoft TechNet Library.

.Related information

http://technet.microsoft.com/en-us/library/[Microsoft TechNet Library: technet.microsoft.com/en-us/library/]
