---
permalink: smb-admin/remove-netbios-aliases-from-list-task.html
sidebar: sidebar
keywords: netbios, alias, cifs, server, remove, list, remove netbios aliases from the netbios alias list
summary: "If you do not need specific NetBIOS aliases for a CIFS server, you can remove those NetBIOS aliases from the list. You can also remove all NetBIOS aliases from the list."
---
= Remove NetBIOS aliases from the list for ONTAP CIFS servers
:icons: font
:imagesdir: ../media/

[.lead]
If you do not need specific NetBIOS aliases for a CIFS server, you can remove those NetBIOS aliases from the list. You can also remove all NetBIOS aliases from the list.

.About this task

You can remove more than one NetBIOS alias by using a comma-delimited list. You can remove all of the NetBIOS aliases on a CIFS server by specifying `-` as the value for the `-netbios-aliases` parameter.

.Steps

. Perform one of the following actions:
+
[options="header"]
|===
| If you want to remove...| Enter...
a|
Specific NetBIOS aliases from the list
a|
`+vserver cifs remove-netbios-aliases -vserver _vserver_name_ -netbios-aliases _NetBIOS_alias_,...+`
a|
All NetBIOS aliases from the list
a|
`vserver cifs remove-netbios-aliases -vserver _vserver_name_ -netbios-aliases -`
|===
`vserver cifs remove-netbios-aliases -vserver vs1 -netbios-aliases alias_1`

. Verify that the specified NetBIOS aliases were removed: `vserver cifs show -vserver _vserver_name_ -display-netbios-aliases`
+
`vserver cifs show -vserver vs1 -display-netbios-aliases`
+
----
Vserver: vs1

         Server Name: CIFS_SERVER
         NetBIOS Aliases: ALIAS_2, ALIAS_3
----

// 2025 May 13, ONTAPDOC-2981