---
permalink: smb-admin/requirements-configuring-branchcache-concept.html
sidebar: sidebar
keywords: meet, prerequisite, branchcache, requirement, requirements for configuring branchcache, configure, configuring
summary: "After meeting some prerequisites, you can set up BranchCache."
---
= Requirements for configuring BranchCache
:icons: font
:imagesdir: ../media/

[.lead]
After meeting some prerequisites, you can set up BranchCache.

The following requirements must be met before configuring BranchCache on the CIFS server for your SVM:

* ONTAP must be installed on all nodes in the cluster.
* CIFS must be licensed and a SMB server must be configured. The SMB license is included with link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one[ONTAP One]. If you don't have ONTAP One and the license is not installed, contact your sales representative. 
* IPv4 or IPv6 network connectivity must be configured.
* For BranchCache 1, SMB 2.1 or later must be enabled.
* For BranchCache 2, SMB 3.0 must be enabled and the remote Windows clients must support BranchCache 2.

// 2024-Mar-28, ONTAPDOC-1366