---
permalink: smb-admin/requirements-microsoft-previous-versions-concept.html
sidebar: sidebar
keywords: version, cifs, server, ontap, smb, windows, client, support, snapshot, setting, requirement
summary: "Before you can use Previous Versions with your CIFS server, you need to know which versions of ONTAP and SMB, and which Windows clients, support it. You also need to know about the snapshot setting requirement."
---
= Requirements for using Microsoft Previous Versions
:icons: font
:imagesdir: ../media/

[.lead]
Before you can use Previous Versions with your CIFS server, you need to know which versions of ONTAP and SMB, and which Windows clients, support it. You also need to know about the snapshot setting requirement.

== ONTAP version requirements

Supports Previous Versions.

== SMB protocol version requirements

For storage virtual machine (SVM), ONTAP supports Previous Versions on all versions of SMB.

== Windows client requirements

Before a user can use Previous Versions to access data in snapshots, the Windows client must support the feature.

For the latest information about which Windows clients support Previous Versions, see the Interoperability Matrix.

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^]

== Requirements for snapshot settings

To use Previous Versions to access data in snapshots, an enabled snapshot policy must be associated to the volume containing the data, clients must be able to access to the Snapshot data, and snapshots must exist.
