---
permalink: smb-admin/set-server-minimum-authentication-security-level-task.html
sidebar: sidebar
keywords: cifs, server, minimum, security, level, lmcompatibilitylevel, smb, token, set the cifs server minimum authentication security level
summary: "You can set the SMB server minimum security level, also known as the LMCompatibilityLevel, on your SMB server to meet your business security requirements for SMB access. The minimum security level is the minimum level of the security tokens that the SMB server accepts from SMB clients."
---
= Set the ONTAP SMB server minimum authentication security level
:icons: font
:imagesdir: ../media/

[.lead]
You can set the SMB server minimum security level, also known as the _LMCompatibilityLevel_, on your SMB server to meet your business security requirements for SMB client access. The minimum security level is the minimum level of the security tokens that the SMB server accepts from SMB clients.

.About this task

[NOTE]
====
* SMB servers in workgroup mode support only NTLM authentication. Kerberos authentication is not supported.
* LMCompatibilityLevel applies only to SMB client authentication, not admin authentication.
====

You can set the minimum authentication security level to one of four supported security levels.

[options="header"]
|===
| Value| Description
a|
`lm-ntlm-ntlmv2-krb` (default)
a|
The storage virtual machine (SVM) accepts LM, NTLM, NTLMv2, and Kerberos authentication security.
a|
`ntlm-ntlmv2-krb`
a|
The SVM accepts NTLM, NTLMv2, and Kerberos authentication security. The SVM denies LM authentication.
a|
`ntlmv2-krb`
a|
The SVM accepts NTLMv2 and Kerberos authentication security. The SVM denies LM and NTLM authentication.
a|
`krb`
a|
The SVM accepts Kerberos authentication security only. The SVM denies LM, NTLM, and NTLMv2 authentication.
|===

.Steps

. Set the minimum authentication security level: `vserver cifs security modify -vserver _vserver_name_ -lm-compatibility-level {lm-ntlm-ntlmv2-krb|ntlm-ntlmv2-krb|ntlmv2-krb|krb}`
. Verify that the authentication security level is set to the desired level: `vserver cifs security show -vserver _vserver_name_`

.Related information

xref:enable-disable-aes-encryption-kerberos-task.adoc[Enabling or disabling AES encryption for Kerberos-based communication]

// 2025 May 07, ONTAPDOC-2981
// 2021-12-02, BURT 1351274
