---
permalink: smb-admin/share-properties-concept.html
sidebar: sidebar
keywords: customize, properties, property, smb, share, how to use smb share properties
summary: 'You can customize the properties of SMB shares.'
---
= Use SMB share properties overview
:icons: font
:imagesdir: ../media/

[.lead]
You can customize the properties of SMB shares.

The available share properties are as follows:

[options="header"]
|===
| Share properties| Description
a|
`oplocks`
a|
This property specifies that the share uses opportunistic locks, also known as client-side caching.
a|
`browsable`
a|
This property allows Windows clients to browse the share.
a|
`showsnapshot`
a|
This property specifies that snapshots can be viewed and traversed by clients.
a|
`changenotify`
a|
This property specifies that the share supports Change Notify requests. For shares on an SVM, this is a default initial property.
a|
`attributecache`
a|
This property enables the file attribute caching on the SMB share to provide faster access of attributes. The default is to disable attribute caching. This property should be enabled only if there are clients connecting to shares over SMB 1.0. This share property is not applicable if clients are connecting to shares over SMB 2.x or SMB 3.0.
a|
`continuously-available`
a|
This property permits SMB clients that support it to open files in a persistent manner. Files opened this way are protected from disruptive events, such as failover and giveback.
a|
`branchcache`
a|
This property specifies that the share allows clients to request BranchCache hashes on the files within this share. This option is useful only if you specify "`per-share`" as the operating mode in the CIFS BranchCache configuration.
a|
`access-based-enumeration`
a|
This property specifies that _Access Based Enumeration_ (ABE) is enabled on this share. ABE-filtered shared folders are visible to a user based on that individual user's access rights, preventing the display of folders or other shared resources that the user does not have rights to access.
a|
`namespace-caching`
a|
This property specifies that the SMB clients connecting to this share can cache the directory enumeration results returned by the CIFS servers, which can provide better performance. By default, SMB 1 clients do not cache directory enumeration results. Because SMB 2 and SMB 3 clients cache directory enumeration results by default, specifying this share property provides performance benefits only to SMB 1 client connections.
a|
`encrypt-data`
a|
This property specifies that SMB encryption must be used when accessing this share. SMB clients that do not support encryption when accessing SMB data will not be able to access this share.
|===
