---
permalink: smb-admin/static-home-directory-share-names-upgrading-concept.html
sidebar: sidebar
keywords: static, home, directory, share, names, upgrading, upgrade
summary: "Home directory share names must contain either the %w or the %u dynamic variable. You should be aware of what happens to existing static home directory share names after upgrading to a version of ONTAP with the new requirement."
---
= Learn about what happens to static ONTAP SMB home directory share names after upgrading
:icons: font
:imagesdir: ../media/

[.lead]
Home directory share names must contain either the `%w` or the `%u` dynamic variable. You should be aware of what happens to existing static home directory share names after upgrading to a version of ONTAP with the new requirement.

If your home directory configuration contains static share names and you upgrade to ONTAP, the static home directory share names are not changed and are still valid. However, you cannot create any new home directory shares that do not contain either the `%w` or `%u` variable.

Requiring that one of these variables is included in the user's home directory share name ensures that every share name is unique across the home directory configuration. If desired, you can change the static home directory share names to names that contain either the `%w` or `%u` variable.


// 2025 June 04, ONTAPDOC-2981