---
permalink: smb-admin/stop-start-server-task.html
sidebar: sidebar
keywords: stop, cifs, server, svm, perform, task, user, access, data, smb, share, restart, protocol, storage, virtual, machine, stop or start the cifs server
summary: "You can stop the CIFS server on a SVM, which can be useful when performing tasks while users are not accessing data over SMB shares. You can restart SMB access by starting the CIFS server. By stopping the CIFS server, you can also modify the protocols allowed on the storage virtual machine (SVM)."
---
= Stop or start the CIFS server
:icons: font
:imagesdir: ../media/

[.lead]
You can stop the CIFS server on a SVM, which can be useful when performing tasks while users are not accessing data over SMB shares. You can restart SMB access by starting the CIFS server. By stopping the CIFS server, you can also modify the protocols allowed on the storage virtual machine (SVM).

.Steps

. Perform one of the following actions:
+
[options="header"]
|===
| If you want to...| Enter the command...
a|
Stop the CIFS server
a|
`vserver cifs stop -vserver _vserver_name_ [-foreground {true\|false}]`
a|
Start the CIFS server
a|
`vserver cifs start -vserver _vserver_name_ [-foreground {true\|false}]`
|===
`-foreground` specifies whether the command should execute in the foreground or background. If you do not enter this parameter, it is set to `true`, and the command is executed in the foreground.

. Verify that the CIFS server administrative status is correct by using the `vserver cifs show` command.

.Example

The following commands start the CIFS server on SVM vs1:

----
cluster1::> vserver cifs start -vserver vs1

cluster1::> vserver cifs show -vserver vs1

                                          Vserver: vs1
                         CIFS Server NetBIOS Name: VS1
                    NetBIOS Domain/Workgroup Name: DOMAIN
                      Fully Qualified Domain Name: DOMAIN.LOCAL
Default Site Used by LIFs Without Site Membership:
                             Authentication Style: domain
                CIFS Server Administrative Status: up
----

.Related information

xref:display-discovered-servers-task.adoc[Displaying information about discovered servers]

xref:reset-rediscovering-servers-task.adoc[Resetting and rediscovering servers]

// 2023 Apr 10, Issue 864
