---
permalink: smb-admin/support-ipv6-concept.html
sidebar: sidebar
keywords: ipv6, cifs, server, ontap, smb, network, communication, service, support for ipv6 with smb access and cifs services
summary: "If you want to use IPv6 on your CIFS server, you need to be aware of how ONTAP supports IPv6 for SMB access and network communication for CIFS services."
---
= Support for IPv6 with SMB access and CIFS services
:icons: font
:imagesdir: ../media/

[.lead]
If you want to use IPv6 on your CIFS server, you need to be aware of how ONTAP supports IPv6 for SMB access and network communication for CIFS services.

== Windows client and server support

ONTAP provides support for Windows servers and clients that support IPv6. The following describes Microsoft Windows client and server IPv6 support:


* Windows 7, Windows 8, Windows Server 2008, Windows Server 2012 and later support IPv6 for both SMB file sharing and Active Directory services, including DNS, LDAP, CLDAP, and Kerberos services.
+
If IPv6 addresses are configured, Windows 7 and Windows Server 2008 and later releases use IPv6 by default for Active Directory services. Both NTLM and Kerberos authentication over IPv6 connections are supported.
+
All Windows clients supported by ONTAP can connect to SMB shares by using IPv6 addresses.

For the latest information about which Windows clients ONTAP supports, see the link:https://mysupport.netapp.com/matrix[Interoperability Matrix].

[NOTE]
====
NT domains are not supported for IPv6.
====

== Additional CIFS services support

In addition to IPv6 support for SMB file shares and Active Directory services, ONTAP provides IPv6 support for the following:

* Client-side services, including offline folders, roaming profiles, folder redirection, and Previous Versions
* Server-side services, including Dynamic home directories (Home Directory feature), symlinks and Widelinks, BranchCache, ODX copy offload, automatic node referrals, and Previous Versions
* File access management services, including the use of Windows local users and groups for access control and rights management, setting file permissions and audit policies using the CLI, security tracing, file locks management, and monitoring SMB activity
* NAS multiprotocol auditing
* FPolicy
* Continuously available shares, Witness protocol, and Remote VSS (used with Hyper-V over SMB configurations)

== Name service and authentication service support

Communication with the following name services are supported with IPv6:

* Domain controllers
* DNS servers
* LDAP servers
* KDC servers
* NIS servers

// 2023 Dec 18, Jira 1446