---
permalink: smb-admin/supported-versions-functionality-concept.html
sidebar: sidebar
keywords: server, message, block, smb, remote, file-sharing, protocol, microsoft, windows, client, server, ontap, functionality, environment, supported smb versions and functionality
summary: "Server Message Block (SMB) is a remote file-sharing protocol used by Microsoft Windows clients and servers. In ONTAP 9, all SMB versions are supported; however, default SMB 1.0 support depends on your ONTAP version. You should verify that the ONTAP SMB server supports the clients and functionality required in your environment."
---
= Supported SMB versions and functionality
:icons: font
:imagesdir: ../media/

[.lead]
Server Message Block (SMB) is a remote file-sharing protocol used by Microsoft Windows clients and servers. In ONTAP 9, all SMB versions are supported; however, default SMB 1.0 support depends on your ONTAP version. You should verify that the ONTAP SMB server supports the clients and functionality required in your environment.

The latest information about which SMB clients and domain controllers ONTAP supports is available in the _Interoperability Matrix Tool_.

SMB 2.0 and later versions are enabled by default for ONTAP 9 SMB servers, and can be enabled or disabled as needed. The following table shows SMB 1.0 support and default configuration.

[options="header"]
|===
| SMB 1.0 functionality: 4+| In these ONTAP 9 releases:
a|

a|
9.0
a|
9.1
a|
9.2
a|
9.3 and later
a|
Is enabled by default
a|
Yes
a|
Yes
a|
Yes
a|
No
a|
Can be enabled or disabled
a|
No
a|
Yes*9.1 P8 or later required.

a|
Yes
a|
Yes
|===

[NOTE]
====
Default settings for SMB 1.0 and 2.0 connections to domain controllers also depend on the ONTAP version. More information is available in the `vserver cifs security modify` man page. For environments with existing CIFS servers running SMB 1.0, you should migrate to a later SMB version as soon as possible to prepare for security and compliance enhancements. Contact your NetApp representative for details.

====

The following table shows which SMB features are supported in each SMB version. Some SMB features are enabled by default and some require additional configuration.
[options="header"]
|===
| *This functionality:*| *Requires enablement:* 5+| *Is supported in ONTAP 9 for these SMB versions:*
a|

a|

a|
1.0
a|
2.0
a|
2.1
a|
3.0
a|
3.1.1
a|
Legacy SMB 1.0 functionality
a|

a|
X
a|
X
a|
X
a|
X
a|
X
a|
Durable handles
a|

a|

a|
X
a|
X
a|
X
a|
X
a|
Compounded operations
a|

a|

a|
X
a|
X
a|
X
a|
X
a|
Asynchronous operations
a|

a|

a|
X
a|
X
a|
X
a|
X
a|
Increased read and write buffer sizes
a|

a|

a|
X
a|
X
a|
X
a|
X
a|
Increased scalability
a|

a|

a|
X
a|
X
a|
X
a|
X
a|
SMB signing
a|
X
a|
X
a|
X
a|
X
a|
X
a|
X
a|
Alternate Data Stream (ADS) file format
a|
X
a|
X
a|
X
a|
X
a|
X
a|
X
a|
Large MTU (enabled by default beginning with ONTAP 9.7)
a|
X
a|

a|

a|
X
a|
X
a|
X
a|
Lease oplocks
a|

a|

a|

a|
X
a|
X
a|
X
a|
Continuously available shares
a|
X
a|

a|

a|

a|
X
a|
X
a|
Persistent handles
a|

a|

a|

a|

a|
X
a|
X
a|
Witness
a|

a|

a|

a|

a|
X
a|
X
a|
SMB encryption: AES-128-CCM
a|
X
a|

a|

a|

a|
X
a|
X
a|
Scale out (required by CA shares)
a|

a|

a|

a|

a|
X
a|
X
a|
Transparent failover
a|

a|

a|

a|

a|
X
a|
X
a|
SMB Multichannel (beginning with ONTAP 9.4)
a|
X
a|

a|

a|

a|
X
a|
X
a|
Preauthentication integrity
a|

a|

a|

a|

a|

a|
X
a|
Cluster client failover v.2 (CCFv2)
a|

a|

a|

a|

a|

a|
X
a|
SMB encryption: AES-128-GCM (beginning with ONTAP 9.1)
a|
X
a|

a|

a|

a|

a|
X
|===
.Related information

xref:signing-enhance-network-security-concept.adoc[Using SMB signing to enhance network security]

xref:set-server-minimum-authentication-security-level-task.adoc[Setting the SMB server minimum authentication security level]

xref:configure-required-encryption-concept.adoc[Configuring required SMB encryption on SMB servers for data transfers over SMB]

https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability^]

// 2024-06-21, ontapdoc-2116
// 2022-01-07, BURT 1394663
