---
permalink: svm-migrate/cancel-task.html
sidebar: sidebar
keywords: svm, migrate, cancel, abort
summary: "If you need to cancel an SVM migration before it completes, you can use the `vserver migrate abort` command. You can cancel an SVM migration only when the operation is in the paused or failed state. You cannot cancel an SVM migration when the status is “cutover-started” or after cutover is complete. You cannot use the `abort` option when an SVM migration is in progress."
---
= Cancel an SVM migration
:icons: font
:imagesdir: ../media/


[.lead]
If you need to cancel an SVM migration before it completes, you can use the `vserver migrate abort` command. You can cancel an SVM migration only when the operation is in the paused or failed state. You cannot cancel an SVM migration when the status is “cutover-started” or after cutover is complete. You cannot use the `abort` option when an SVM migration is in progress.

.Steps

. Check the migration status:
+
`dest_cluster> vserver migrate show -vserver <vserver name>`
. Cancel the migration:
+
`dest_cluster> vserver migrate abort -vserver <vserver name>`
. Check the progress of the cancel operation:
+
`dest_cluster> vserver migrate show`
+
The migration status shows migrate-aborting while the cancel operation is in progress. When the cancel operation completes, the migration status shows nothing.


// 2021-11-2, Jira IE-330
