---
permalink: svm-migrate/migrate-svm-task.html
sidebar: sidebar
keywords: svm, migrate, defaults, cutover, cleanup
summary: "After an SVM migration has completed, clients are cut over to the destination cluster automatically and the unnecessary SVM is removed from the source cluster. Automatic cutover and automatic source cleanup are enabled by default. If necessary, you can disable client auto-cutover to suspend the migration before cutover occurs and you can also disable automatic source SVM cleanup."
---
= Migrate an ONTAP SVM
:icons: font
:imagesdir: ../media/


[.lead]
After an SVM migration has completed, clients are cut over to the destination cluster automatically and the unnecessary SVM is removed from the source cluster. Automatic cutover and automatic source cleanup are enabled by default. If necessary, you can disable client auto-cutover to suspend the migration before cutover occurs and you can also disable automatic source SVM cleanup.

.About this task

This procedure applies to FAS, AFF, and ASA systems. If you have an ASA r2 system (ASA A1K, ASA A90, ASA A70, ASA A50, ASA A30, ASA A20, or ASA C30), follow link:https://docs.netapp.com/us-en/asa-r2/manage-data/migrate-svm.html[these steps^] to migrate an SVM. ASA r2 systems provide a simplified ONTAP experience specific to SAN-only customers.

* You can use the `-auto-cutover false` option to suspend the migration when automatic client cutover normally occurs and then manually perform the cutover later.
+
xref:manual-client-cutover-task.adoc[Manually cutover clients after SVM migration]
* You can use the advance privilege `-auto-source-cleanup false` option to disable the removal of the source SVM after cutover and then trigger source cleanup manually later, after cutover.
+
xref:manual-source-removal-task.adoc[Manually remove source SVM after cutover] 

== Migrate an ONTAP SVM with automatic cutover enabled

By default, clients are cut over to the destination cluster automatically when the migration is complete, and the unnecessary SVM is removed from the source cluster.

.Steps

. From the destination cluster, run the migration prechecks:
+
[source,cli]
----
vserver migrate start -vserver <SVM_name> -source-cluster <cluster_name> -check-only true`
----

. From the destination cluster, start the SVM migration:
+
[source,cli]
----
vserver migrate start -vserver <SVM_name> -source-cluster <cluster_name>
----

. Check the migration status:
+
[source,cli]
----
vserver migrate show
----
+
The status displays migrate-complete when the SVM migration is finished.

== Migrate an ONTAP SVM with automatic client cutover disabled

You can use the -auto-cutover false option to suspend the migration when automatic client cutover normally occurs and then manually perform the cutover later. See xref:manual-client-cutover-task.adoc[Manually cutover clients after SVM migration].

.Steps

.	From the destination cluster, run the migration prechecks:
+
[source,cli]
----
vserver migrate start -vserver <SVM_name> -source-cluster <cluster_name> -check-only true`
----

.	From the destination cluster, start the SVM migration:
+
[source,cli]
----
vserver migrate start -vserver <SVM_name> -source-cluster <cluster_name> -auto-cutover false`
----

.	Check the migration status:
+
[source,cli]
----
vserver migrate show
----

The status displays ready-for-cutover when SVM migration completes the asynchronous data transfers, and it is ready for cutover operation.


== Migrate an ONTAP SVM with source cleanup disabled

You can use the advance privilege -auto-source-cleanup false option to disable the removal of the source SVM after cutover and then trigger source cleanup manually later, after cutover. See xref:manual-source-removal-task.adoc[Manually remove source SVM].

.Steps

. From the destination cluster, run the migration prechecks:
+
[source,cli]
----
vserver migrate start -vserver <SVM_name> -source-cluster <cluster_name> -check-only true`
----

.	From the destination cluster, start the SVM migration:
+
[source,cli]
----
vserver migrate start -vserver <SVM_name> -source-cluster <cluster_name> -auto-source-cleanup false`
----

.	Check the migration status:
+
[source,cli]
----
vserver migrate show
----
+
The status displays ready-for-source-cleanup when SVM migration cutover is complete, and it is ready to remove the SVM on the source cluster.

// 2025 Nov 06, ONTAPDOC-3345
// 2021-11-1, Jira IE-330