---
permalink: svm-migrate/pause-task.html
sidebar: sidebar
keywords: svm, migrate, pause, resume, restart
summary: "You might want to pause an SVM migration before the migration cutover begins. You can pause an SVM migration using the `vserver migrate pause` command."
---
= Pause and resume SVM migration
:icons: font
:imagesdir: ../media/


[.lead]
You might want to pause an SVM migration before the migration cutover begins. You can pause an SVM migration using the `vserver migrate pause` command.

== Pause migration

You can pause an SVM migration before client cutover starts by using the `vserver migrate pause` command.

Some configuration changes are restricted when a migration operation is in progress; however, beginning with ONTAP 9.12.1, you can pause a migration to fix some restricted configurations and for some failed states so that you can fix configuration issues that might have caused the failure. Some of the failed states that you can fix when you pause SVM migration include the following:

* `setup-configuration-failed`
* `migrate-failed`


.Steps

. From the destination cluster, pause the migration:
+
[source,cli]
----
vserver migrate pause -vserver <vserver name>
----

== Resume migrations

When you're ready to resume a paused SVM migration or when an SVM migration has failed, you can use the `vserver migrate resume` command.

.Steps

. Do the following from the destination cluster:
.. Resume SVM migration:
+
[source,cli]
----
vserver migrate resume
----

.. Verify that the SVM migration has resumed, and monitor the progress:
+
[source,cli]
----
vserver migrate show
----

// 2024-12-9, ONTAPDOC-2590
// 2022-Oct-6, BURT 1482882
// 2021-11-2, Jira IE-330
