---
permalink: mediator/download-install-pkg-task.html
sidebar: sidebar
keywords: mediator, new, release, update, install, download, package
summary: "Download the Mediator installation package as part of the installation process."
---

= Download the Mediator installation package
:icons: font
:imagesdir: ../media/

[.lead]
Download the Mediator installation package as part of the installation process.

.Steps

. Download the Mediator installation package from the ONTAP Mediator page.
+
https://mysupport.netapp.com/site/products/all/details/ontap-mediator/downloads-tab[ONTAP Mediator download page^]

. Confirm that the Mediator installation package is in the current working directory:
+
`ls`
+
----
[root@mediator-host ~]#ls
ontap-mediator-1.6.0.tgz
----
+
NOTE: For ONTAP Mediator versions 1.4 and earlier, the installer is named `ontap-mediator`.
+
If you are at a location without access to the internet, you must ensure that the installer has access to the required packages.

. If necessary, move the Mediator installation package from the download directory to the installation directory on the Linux Mediator host.

. Unzip the installer package: 
+
`tar xvfz ontap-mediator-1.6.0.tgz`
+
----
[root@scs000099753 ~]# tar xvfz ontap-mediator-1.6.0.tgz
ontap-mediator-1.6.0/
ontap-mediator-1.6.0/ONTAP-Mediator-production.pub
ontap-mediator-1.6.0/tsa-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.6.0/tsa-prod-ONTAP-Mediator.pem
ontap-mediator-1.6.0/csc-prod-ONTAP-Mediator.pem
ontap-mediator-1.6.0/csc-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.6.0/ontap-mediator-1.6.0
ontap-mediator-1.6.0/ontap-mediator-1.6.0.sig.tsr
ontap-mediator-1.6.0/ontap-mediator-1.6.0.tsr
ontap-mediator-1.6.0/ontap-mediator-1.6.0.sig

----

// 2021-04-21 ONTAPEX-133437
// 2021-05-05 review comment in IDR-67
// ontap-metrocluster issue #146, 7 march 2022
// 2022-04-28, BURT 1470656
// january 2022 ontap-metrocluster/issues/35
// 19 july 2022, ontap-issues-564
// ONTAPDOC-955, 2023 May 05
