---
permalink: mediator/host-maintenance-task.html
sidebar: sidebar
keywords: mediator, maintain, host, maintenance, package update, kernal upgrade, change hostname, change IP, self-signed certificate, self signed certificate
summary: "For optimal performance, you should maintain the host OD for ONTAP Mediator on a regular basis."
---

= Maintain OS host for ONTAP Mediator
:icons: font
:imagesdir: ../media/

[.lead]
For optimal performance, you should maintain the host OS for ONTAP Mediator on a regular basis.

== Reboot the host

Reboot the host when the clusters are healthy.  While the ONTAP Mediator is offline, the clusters are at risk of not being able to react properly to failures. A service window is recommended if a reboot is required.

ONTAP Mediator will automatically resume during a reboot and will re-enter the relationships that were previously configured with ONTAP clusters.

== Host package updates

Any library or yum packages (except the kernel) can be safely updated but might require a reboot to take effect.   A service window is recommended if a reboot is required.

If you install the `yum-utils` package, use the `needs-restarting` command to detect if any package changes require a reboot.

You should reboot if any of the ONTAP Mediator dependencies are updated because they will not take immediate effect on running processes.

== Host OS minor kernel upgrades

SCST must be compiled for the kernel that is being used.  To update the OS, a maintenance window is required.  

.Steps
Perform the following steps to upgrade the host OS kernel.

. Stop the ONTAP Mediator
. Uninstall the SCST package.  (SCST doesn't provide an upgrade mechanism.)
. Upgrade the OS, and reboot.
. Re-install the SCST package.
. Re-enable the ONTAP Mediator services.

== Host changes to the hostname or IP

.About this task

* You perform this task on the Linux host on which the ONTAP Mediator service is installed.
* You can perform this task only if the generated self-signed certificates have become obsolete due to changes to the hostname or IP address of the host after installing the ONTAP Mediator.
* After the temporary self-signed certificate has been replaced by a trusted third-party certificate, you do _not_ use this task to regenerate a certificate.  The absence of a self-signed certificate will cause this procedure to fail.

.Step

To regenerate a new temporary self-signed certificate for the current host, perform the following step:

. Restart the ONTAP Mediator:
+
`./make_self_signed_certs.sh overwrite`
+
----
[root@xyz000123456 ~]# cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config
[root@xyz000123456 server_config]# ./make_self_signed_certs.sh overwrite

Adding Subject Alternative Names to the self-signed server certificate
#
# OpenSSL example configuration file.
Generating self-signed certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
..................................................................................................................................................................++++
........................................................++++
e is 65537 (0x010001)
Generating a RSA private key
................................................++++
.............................................................................................................................................++++
writing new private key to 'ontap_mediator_server.key'
-----
Signature ok
subject=C = US, ST = California, L = San Jose, O = "NetApp, Inc.", OU = ONTAP Core Software, CN = ONTAP Mediator, emailAddress = support@netapp.com
Getting CA Private Key

[root@xyz000123456 server_config]# systemctl restart ontap_mediator
----

// ONTAPDOC-955, 2023 May 05
// ONTAPDOC-1314, 2023 Nov 01
