---
permalink: mediator/index.html
sidebar: sidebar
keywords: ontap mediator service, install requirements, mediator requirements
summary: To install the ONTAP Mediator service, you must ensure all prerequisites are met, get the installation package and run the installer on the host.
---
= Prepare to install or upgrade the ONTAP Mediator service
:icons: font
:imagesdir: ../media/

[.lead]
To install the ONTAP Mediator service, you must ensure all prerequisites are met, fetch the installation package and run the installer on the host. This procedure is used for an installation or an upgrade of an existing installation.

* Beginning with ONTAP 9.7, you can use any version of ONTAP Mediator to monitor a MetroCluster IP configuration.
* Beginning with ONTAP 9.8, you can use any version of ONTAP Mediator to monitor an SnapMirror active sync relationship.

== Installation and upgrade considerations

Review the following considerations before you upgrade or install the ONTAP Mediator. 

CAUTION: ONTAP Mediator 1.8 and earlier is not compatible with Red Hat Enterprise Linux FIPS mode and will prevent it from installing successfully. You can check if FIPS mode is enabled using the `fips-mode-setup --check` command. You can disable FIPS mode using the `fips-modesetup --disable` command. Reboot after disabling FIPS mode to successfully install ONTAP Mediator 1.8 or earlier.

* You should upgrade the ONTAP Mediator to the latest version that is available. Previous versions of ONTAP Mediator remain backwards compatible with all ONTAP versions but recent versions include security patches for all third-party elements.

* When you upgrade to a new ONTAP Mediator version, the installer automatically upgrades to the recommended SCST version unless a higher version is available. For instructions on manually installing a higher SCST version, see link:manage-task.html[Manage the Mediator service]. For supported versions, see the link:whats-new-concept.html#scst-support-matrix[SCST support matrix].
+
CAUTION: If an installation failure occurs, you might need to upgrade to a later version of ONTAP Mediator. 

* If you install the `yum-utils` package, you can use the `needs-restarting` command.

=== Host requirements 
// BURT 1392725

Follow these requirements when installing Red Hat Enterprise Linux (RHEL) or Rocky Linux and configuring the associated repositories. 

[NOTE] 
====
If you modify the installation or configuration process, you might need to perform additional steps.
====

.Linux distribution requirements
* Install RHEL or Rocky Linux according to Red Hat's best practices. Since CentOS 8.x has reached end-of-life, compatible versions of CentOS 8.x are not recommended.
* When installing the ONTAP Mediator service, ensure the system has access to the required repository so the installation program can retrieve and install all required software dependencies.
* To enable the yum installer to find dependent software in the RHEL repositories, register the system during installation or afterwards using a valid Red Hat subscription.
+
[NOTE] 
====
See the Red Hat Subscription Manager documentation for further information.
====

.Networking requirements
* Ensure the following ports are available and unused for ONTAP Mediator.
 ** 31784: Configure this port for inbound requests, as it is an HTTPS port and only accepts incoming traffic.
 ** 3260: This port is bidirectional because the iSCSI protocol requires two-way connection. 
* If using a third-party firewall, refer to link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html#firewall-requirements-for-ontap-mediator[Firewall requirements for ONTAP Mediator^].
* For Linux hosts without internet access, make sure the required packages are available in a local repository.
+
If you are using Link Aggregation Control Protocol (LACP) in a Linux environment, configure the kernel and set the `sysctl net.ipv4.conf.all.arp_ignore` to `2`.

.OS requirements

Your OS must meet the following requirements:

* 64-bit physical installation or virtual machine
* 8 GB RAM
* 1 GB disk space (used for applications installation, server logs, and the database)
* User: Root access

The following table shows the supported OSs for each version of ONTAP Mediator.
include::../_include/mediator-linux-support.adoc[]

.OS required packages

The following packages are required by the ONTAP Mediator service:

[NOTE] 
The packages are either pre-installed or automatically installed by the ONTAP Mediator installer.

[cols="34,33,33"]
|===

h| All RHEL/CentOS versions h| Additional packages for RHEL 8.x / Rocky Linux 8 h| Additional packages for RHEL 9.x / Rocky Linux 9

a|
 * openssl
 * openssl-devel
 * kernel-devel-$ (uname -r)
 * gcc
 * make
 * libselinux-utils
 * patch
 * bzip2
 * perl-Data-Dumper
 * perl-ExtUtils-MakeMaker
 * efibootmgr
 * mokutil

a|
 * python3-pip
 * elfutils-libelf-devel
 * policycoreutils-python-utils
 * redhat-lsb-core
 * python39
 * python39-devel

a|
 * python3-pip
 * elfutils-libelf-devel
 * policycoreutils-python-utils
 * python3
 * python3-devel

|===

The Mediator installation package is a self-extracting compressed tar file that includes:

* An RPM file containing all dependencies that cannot be obtained from the supported release's repository.
* An install script.

A valid SSL certification is recommended.

=== OS upgrade considerations and kernel compatibility
* All library packages, except the kernel, can safely be updated but might require a reboot to apply the changes within the ONTAP Mediator application. A service window is recommended when a reboot is required.
* You should keep the OS kernel up to date. The kernel core can be upgraded to a version listed as supported in the link:whats-new-concept.html#scst-support-matrix[ONTAP Mediator version matrix]. A reboot is mandatory, so you should plan a maintenance window for the outage.
** You must uninstall the SCST kernel module before rebooting and then re-install it after.
** You must have a supported version of the SCST ready to reinstall before starting the kernel OS upgrade. 


[NOTE] 
====
* The kernel version must match the operating system version.
* Upgrading to a kernel beyond the supported OS release for the specific ONTAP Mediator release is not supported. (This likely indicates that the tested SCST module won't compile).
====

== Install ONTAP Mediator when UEFI Secure Boot is enabled

ONTAP Mediator can be installed on a system with or without UEFI Secure Boot enabled.

.About this task

You can choose to disable UEFI Secure Boot before installing ONTAP Mediator if it is not needed or if you are troubleshooting ONTAP Mediator installation issues. Disable the UEFI Secure Boot option from your machine settings. 

[NOTE] 
====
For detailed instructions on disabling UEFI Secure Boot, refer to the documentation for your host OS.
====

To install the ONTAP Mediator with UEFI Secure Boot enabled, you must register a security key before the service can start. The key is generated during the SCST installation's compile step and saved as a private-public key pair on your machine. Use the `mokutil` utility to add the public key as a Machine Owner Key (MOK) to your UEFI firmware, enabling the system to trust and load the signed module. Save the `mokutil` passphrase in a secure location as this is required when rebooting your system to activate the MOK.

.Steps

. [[step_1_uefi]]Check if UEFI Secure Boot is enabled on your system:
+
`mokutil --sb-state`
+
The results indicate whether UEFI Secure Boot is enabled on this system. 
+
[cols="40,60"]
|===

h| If... h| Go to...

a| UEFI secure boot is enabled
a| <<step_2_uefi,The step where you run the `mokutil` utility>>

a| UEFI secure boot is disabled
a| link:upgrade-host-os-mediator-task.html[Upgrade the host operating system and then the ONTAP Mediator]

|===
+
[NOTE] 
====
* You are prompted to create a passphrase that you must store in a secure location. You'll need this passphrase to enable the key in the UEFI Boot Manager.
* ONTAP Mediator 1.2.0 and earlier versions do not support this mode.
====

. [[step_2_uefi]]If the `mokutil` utility is not installed, run the following command: 
+
`yum install mokutil`
. Add the public key to the MOK list:
+
`mokutil --import /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der`
+
NOTE: You can leave the private key in its default location or move it to a secure location. However, the public key must be maintained in its existing location for use by the Boot Manager. For further information, see the following README.module-signing file:
+
`[root@hostname ~]# ls /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/
README.module-signing  scst_module_key.der  scst_module_key.priv`
. Reboot the host and use your device's UEFI Boot Manager to approve the new MOK. You'll need the passphrase provided for the `mokutil` utility in <<step_1_uefi,the step where you check if UEFI Secure Boot is enabled on your system>>. 

// 2021 Apr 21, ONTAPEX-133437
// 2021 May 05, review comment in IDR-67
// 2022 Mar 07, ontap-metrocluster issue #146
// 2022 Apr 28, BURT 1470656
// 2022 Jan 18, ontap-metrocluster/issues/35
// 2022 Jul 19, ontap-issues-564
// 2023 May 05, ONTAPDOC-955 
// 2023 Jul 20, ONTAPDOC-1163 
// 2023 Oct 24, ONTAPDOC-1428
// 2024 Feb 24, ONTAPDOC-1165
// 27-JULY-2024 GH-1314
// 11-OCT-2024, ONTAPDOC-1689
// 19-NOV-2024, ONTAPDOC-2414
// 21-NOV-2024, ONTAPDOC-2516
// 24-JAN-2025, ONTAPDOC-2625
// 5-FEB-2025, ONTAPDOC-2631