---
permalink: mediator/index.html
sidebar: sidebar
keywords: ontap mediator service, install requirements, mediator requirements
summary: To install the ONTAP Mediator service, you must ensure all prerequisites are met, get the installation package and run the installer on the host.
---
= Prepare to install or upgrade the ONTAP Mediator service
:icons: font
:imagesdir: ../media/

[.lead]

To install the ONTAP Mediator service, you must ensure all prerequisites are met, fetch the installation package and run the installer on the host. This procedure is used for an installation or an upgrade of an existing installation.

.About this task

* Beginning with ONTAP 9.7, you can use any version of ONTAP Mediator to monitor a MetroCluster IP configuration.
* Beginning with ONTAP 9.8, you can use any version of ONTAP Mediator to monitor an SM-BC relationship.

.Before you begin

You must meet the following prerequisites.

include::../_include/mediator-linux-support.adoc[]

NOTE: The kernel version must match the operating system version.

// BURT 1392725
* 64-bit physical installation or virtual machine
* 8 GB RAM
* 1 GB disk space (used for applications installation, server logs, and the database)
* User: Root access

Any library packages except the kernel can safely be updated but might require a reboot to take affect within the ONTAP Mediator application.  A service window is recommended when a reboot is required.

If you install the `yum-utils` package, you can use the `needs-restarting` command.

The kernel core can be updated if it is being updated to a version that is still supported by the ONTAP Mediator version matrix. A reboot will be mandatory, so a service window is required.

The SCST kernel module must be uninstalled prior to the reboot, then re-installed after the reboot.

NOTE: Upgrading to a kernel beyond the supported OS release for the specific ONTAP Mediator release is not support.  (This likely indicates that the tested SCST module won’t compile).

== Register a security key when UEFI Secure Boot is enabled

If UEFI Secure Boot is enabled, to install ONTAP Mediator, you will have to register a security key before the ONTAP Mediator service can start. To determine if the system is UEFI-enabled and Secure Boot is turned on, perform the following steps:

.Steps

. If mokutil is not installed, run the following command: 
+
`yum install mokutil`

. To determine if UEFI Secure Boot is enabled on your system, run the following command:
+
`mokutil --sb-state`
+
The results show whether UEFI Secure Boot is enabled on this system.
+
NOTE: ONTAP Mediator 1.2.0 and previous versions do not support this mode.

 

== Disable UEFI Secure Boot

You can also choose to disable UEFI Secure Boot before installing ONTAP Mediator.

.Steps

. In the physical machine BIOS settings, disable the "UEFI Secure Boot" option.

. In the VMware settings for the VM, disable the "Safe Start" option for vSphere 6.x or the "Secure Boot" option for vSphere 7.x.

// 2021 Apr 21, ONTAPEX-133437
// 2021 May 05, review comment in IDR-67
// 2022 Mar 07, ontap-metrocluster issue #146
// 2022 Apr 28, BURT 1470656
// 2022 Jan 18, ontap-metrocluster/issues/35
// 2022 Jul 19, ontap-issues-564
// 2023 May 05, ONTAPDOC-955 
// 2023 Jul 20, ONTAPDOC-1163 
// 2023 Oct 24, ONTAPDOC-1428
// 2024 Feb 24, ONTAPDOC-1165
