---
permalink: mediator/index.html
sidebar: sidebar
keywords: ontap mediator service, install requirements, mediator requirements
summary: To install the ONTAP Mediator service, you must ensure all prerequisites are met, get the installation package and run the installer on the host.
---
= Prepare to install or upgrade the ONTAP Mediator service
:icons: font
:imagesdir: ../media/

[.lead]

To install the ONTAP Mediator service, you must ensure all prerequisites are met, get the installation package and run the installer on the host. This procedure is used for an installation or an upgrade of an existing installation.

.About this task

** Beginning with ONTAP 9.7, you can use any version of ONTAP Mediator to monitor a MetroCluster IP configuration.
** Beginning with ONTAP 9.8, you can use any version of ONTAP Mediator to monitor an SM-BC relationship.

.Before you begin

You must meet the following prerequisites.

include::../_include/mediator-linux-support.adoc[]

NOTE: The kernel version must match the operating system version.

// BURT 1392725
* 64-bit physical installation or virtual machine
* 8 GB RAM
* User: Root access

// 2021-04-21 ONTAPEX-133437
// 2021-05-05 review comment in IDR-67
// ontap-metrocluster issue #146, 7 march 2022
// 2022-04-28, BURT 1470656
// january 2022 ontap-metrocluster/issues/35
// 19 july 2022, ontap-issues-564
// ONTAPDOC-955, 2023 May 05
