---
permalink: mediator/install-mediator-pkg-task.html
sidebar: sidebar
keywords: mediator, new, release, update, install, package
summary: "To install the ONTAP Mediator service, you must  get the installation package and run the installer on the host."
---

= Install the ONTAP Mediator installation package
:icons: font
:imagesdir: ../media/

[.lead]
To install the ONTAP Mediator service, you must  get the installation package and run the installer on the host.

.Steps

. Run the installer and respond to the prompts as required: 
+
`./ontap-mediator-1.8.0/ontap-mediator-1.8.0 -y` 
+
----
[root@scs000099753 ~]# ./ontap-mediator-1.8.0/ontap-mediator-1.8.0 -y
----

+
The installation process proceeds to create the required accounts and install required packages. If you have a previous version of Mediator installed on the host, you will be prompted to confirm that you want to upgrade.


. Beginning with ONTAP Mediator 1.4, the Secure Boot mechanism is enabled on UEFI systems. When Secure Boot is enabled, you must take additional steps to register the security key after installation:

** Follow instructions in the README file to sign the SCST kernel module.:
+
`/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/README.module-signing`

** Locate the required keys: 
+
`/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys`

+
NOTE: After installation, the README files and key location are also provided in the system output.

.Example of ONTAP Mediator installation (console output)
[%collapsible]

====
----
[root@mediator_host ~]# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.4 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.4 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
[root@mediator_host ~]#

[root@mediator_host ~]# tar -zxvf ontap-mediator-1.9.0.tgz
ontap-mediator-1.9.0/
ontap-mediator-1.9.0/csc-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.9.0/csc-prod-ONTAP-Mediator.pem
ontap-mediator-1.9.0/tsa-prod-ONTAP-Mediator.pem
ontap-mediator-1.9.0/tsa-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.9.0/ONTAP-Mediator-production.pub
ontap-mediator-1.9.0/ontap-mediator-1.9.0
ontap-mediator-1.9.0/ontap-mediator-1.9.0.sig.tsr
ontap-mediator-1.9.0/ontap-mediator-1.9.0.tsr
ontap-mediator-1.9.0/ontap-mediator-1.9.0.sig
[root@mediator_host ~]# ontap-mediator-1.9.0/ontap-mediator-1.9.0

ONTAP Mediator: Self Extracting Installer

+ Extracting the ONTAP Mediator installation/upgrade archive
+ Performing the ONTAP Mediator run-time code signature check
   Using openssl from the path: /usr/bin/openssl configured for CApath:/etc/pki/tls
Error querying OCSP responder
80BBA032607F0000:error:1E800080:HTTP routines:OSSL_HTTP_REQ_CTX_nbio:failed reading data:crypto/http/http_client.c:549:
80BBA032607F0000:error:1E800067:HTTP routines:OSSL_HTTP_REQ_CTX_exchange:error receiving:crypto/http/http_client.c:901:server=http://ocsp.entrust.net:80
   WARNING: The OCSP check failed while attempting to test the Code-Signature-Check certificate
   Continue without code signature checking (only recommended if integrity has been established manually)? y(es)/N(o): yes
 SKIPPING: Code signature check, manual override due to lack of OCSP response
+ Unpacking the ONTAP Mediator installer
ONTAP Mediator requires two user accounts. One for the service (netapp), and one for use by ONTAP to the mediator API (mediatoradmin).
Using default account names: netapp + mediatoradmin



Enter ONTAP Mediator user account (mediatoradmin) password:

Re-Enter ONTAP Mediator user account (mediatoradmin) password:

+ Checking if SELinux is in enforcing mode


+ Checking for default Linux firewall


###############################################################
Preparing for installation of ONTAP Mediator packages.


+ Installing required packages.


Last metadata expiration check: 0:15:55 ago on Thu 17 Oct 2024 09:06:29 AM EDT.
Package openssl-1:3.0.7-27.el9.x86_64 is already installed.
Package openssl-devel-1:3.0.7-27.el9.x86_64 is already installed.
Package kernel-devel-5.14.0-427.22.1.el9_4.x86_64 is already installed.
Package gcc-11.4.1-3.el9.x86_64 is already installed.
Package make-1:4.3-8.el9.x86_64 is already installed.
Package libselinux-utils-3.6-1.el9.x86_64 is already installed.
Package perl-Data-Dumper-2.174-462.el9.x86_64 is already installed.
Package bzip2-1.0.8-8.el9.x86_64 is already installed.
Package elfutils-libelf-devel-0.190-2.el9.x86_64 is already installed.
Package policycoreutils-python-utils-3.6-2.1.el9.noarch is already installed.
Package python3-3.9.18-3.el9.x86_64 is already installed.
Dependencies resolved.
================================================================================================================================================================================================================================
 Package                                                     Architecture                           Version                                              Repository                                                        Size
================================================================================================================================================================================================================================
Installing:
 efibootmgr                                                  x86_64                                 16-12.el9                                            rhel-9-for-x86_64-baseos-rpms                                     48 k
 mokutil                                                     x86_64                                 2:0.6.0-4.el9                                        rhel-9-for-x86_64-baseos-rpms                                     50 k
 patch                                                       x86_64                                 2.7.6-16.el9                                         rhel-9-for-x86_64-appstream-rpms                                 130 k
 perl-ExtUtils-MakeMaker                                     noarch                                 2:7.60-3.el9                                         rhel-9-for-x86_64-appstream-rpms                                 304 k
 python3-devel                                               x86_64                                 3.9.18-3.el9_4.5                                     rhel-9-for-x86_64-appstream-rpms                                 248 k
 python3-pip                                                 noarch                                 21.2.3-8.el9                                         rhel-9-for-x86_64-appstream-rpms                                 2.0 M
Upgrading:
 openssl                                                     x86_64                                 1:3.0.7-28.el9_4                                     rhel-9-for-x86_64-baseos-rpms                                    1.2 M
 openssl-devel                                               x86_64                                 1:3.0.7-28.el9_4                                     rhel-9-for-x86_64-appstream-rpms                                 4.1 M
 openssl-libs                                                i686                                   1:3.0.7-28.el9_4                                     rhel-9-for-x86_64-baseos-rpms                                    1.9 M
 openssl-libs                                                x86_64                                 1:3.0.7-28.el9_4                                     rhel-9-for-x86_64-baseos-rpms                                    1.9 M
 python-unversioned-command                                  noarch                                 3.9.18-3.el9_4.5                                     rhel-9-for-x86_64-appstream-rpms                                  10 k
 python3                                                     x86_64                                 3.9.18-3.el9_4.5                                     rhel-9-for-x86_64-baseos-rpms                                     30 k
 python3-libs                                                x86_64                                 3.9.18-3.el9_4.5                                     rhel-9-for-x86_64-baseos-rpms                                    7.9 M
Installing dependencies:
 efi-filesystem                                              noarch                                 6-2.el9_0                                            rhel-9-for-x86_64-baseos-rpms                                    9.5 k
 efivar-libs                                                 x86_64                                 38-3.el9                                             rhel-9-for-x86_64-baseos-rpms                                    124 k
 perl-AutoSplit                                              noarch                                 5.74-481.el9                                         rhel-9-for-x86_64-appstream-rpms                                  22 k
 perl-Benchmark                                              noarch                                 1.23-481.el9                                         rhel-9-for-x86_64-appstream-rpms                                  27 k
 perl-CPAN-Meta-YAML                                         noarch                                 0.018-461.el9                                        rhel-9-for-x86_64-appstream-rpms                                  29 k
 perl-Devel-PPPort                                           x86_64                                 3.62-4.el9                                           rhel-9-for-x86_64-appstream-rpms                                 216 k
 perl-ExtUtils-Command                                       noarch                                 2:7.60-3.el9                                         rhel-9-for-x86_64-appstream-rpms                                  16 k
 perl-ExtUtils-Constant                                      noarch                                 0.25-481.el9                                         rhel-9-for-x86_64-appstream-rpms                                  49 k
 perl-ExtUtils-Install                                       noarch                                 2.20-4.el9                                           rhel-9-for-x86_64-appstream-rpms                                  47 k
 perl-ExtUtils-Manifest                                      noarch                                 1:1.73-4.el9                                         rhel-9-for-x86_64-appstream-rpms                                  37 k
 perl-ExtUtils-ParseXS                                       noarch                                 1:3.40-460.el9                                       rhel-9-for-x86_64-appstream-rpms                                 190 k
 perl-File-Compare                                           noarch                                 1.100.600-481.el9                                    rhel-9-for-x86_64-appstream-rpms                                  14 k
 perl-JSON-PP                                                noarch                                 1:4.06-4.el9                                         rhel-9-for-x86_64-appstream-rpms                                  69 k
 perl-Test-Harness                                           noarch                                 1:3.42-461.el9                                       rhel-9-for-x86_64-appstream-rpms                                 299 k
 perl-lib                                                    x86_64                                 0.65-481.el9                                         rhel-9-for-x86_64-appstream-rpms                                  15 k
 perl-version                                                x86_64                                 7:0.99.28-4.el9                                      rhel-9-for-x86_64-appstream-rpms                                  67 k
 systemtap-sdt-devel                                         x86_64                                 5.0-4.el9                                            rhel-9-for-x86_64-appstream-rpms                                  77 k
Installing weak dependencies:
 perl-CPAN-Meta                                              noarch                                 2.150010-460.el9                                     rhel-9-for-x86_64-appstream-rpms                                 206 k
 perl-CPAN-Meta-Requirements                                 noarch                                 2.140-461.el9                                        rhel-9-for-x86_64-appstream-rpms                                  34 k
 perl-devel                                                  x86_64                                 4:5.32.1-481.el9                                     rhel-9-for-x86_64-appstream-rpms                                 680 k
 perl-doc                                                    noarch                                 5.32.1-481.el9                                       rhel-9-for-x86_64-appstream-rpms                                 4.6 M

Transaction Summary
================================================================================================================================================================================================================================
Install  27 Packages
Upgrade   7 Packages

Total download size: 27 M
Is this ok [y/N]: y
Downloading Packages:
(1/34): perl-CPAN-Meta-YAML-0.018-461.el9.noarch.rpm                                                                                                                                            220 kB/s |  29 kB     00:00
(2/34): perl-CPAN-Meta-Requirements-2.140-461.el9.noarch.rpm                                                                                                                                    249 kB/s |  34 kB     00:00
(3/34): perl-ExtUtils-Install-2.20-4.el9.noarch.rpm                                                                                                                                             4.2 MB/s |  47 kB     00:00
(4/34): perl-CPAN-Meta-2.150010-460.el9.noarch.rpm                                                                                                                                              1.3 MB/s | 206 kB     00:00
(5/34): perl-version-0.99.28-4.el9.x86_64.rpm                                                                                                                                                   5.5 MB/s |  67 kB     00:00
(6/34): perl-ExtUtils-Manifest-1.73-4.el9.noarch.rpm                                                                                                                                            3.9 MB/s |  37 kB     00:00
(7/34): perl-ExtUtils-MakeMaker-7.60-3.el9.noarch.rpm                                                                                                                                            16 MB/s | 304 kB     00:00
(8/34): perl-ExtUtils-ParseXS-3.40-460.el9.noarch.rpm                                                                                                                                            11 MB/s | 190 kB     00:00
(9/34): patch-2.7.6-16.el9.x86_64.rpm                                                                                                                                                            15 MB/s | 130 kB     00:00
(10/34): perl-Test-Harness-3.42-461.el9.noarch.rpm                                                                                                                                               15 MB/s | 299 kB     00:00
(11/34): perl-Devel-PPPort-3.62-4.el9.x86_64.rpm                                                                                                                                                 14 MB/s | 216 kB     00:00
(12/34): perl-ExtUtils-Command-7.60-3.el9.noarch.rpm                                                                                                                                            1.4 MB/s |  16 kB     00:00
(13/34): perl-JSON-PP-4.06-4.el9.noarch.rpm                                                                                                                                                     6.9 MB/s |  69 kB     00:00
(14/34): perl-Benchmark-1.23-481.el9.noarch.rpm                                                                                                                                                 3.9 MB/s |  27 kB     00:00
(15/34): systemtap-sdt-devel-5.0-4.el9.x86_64.rpm                                                                                                                                               9.4 MB/s |  77 kB     00:00
(16/34): perl-AutoSplit-5.74-481.el9.noarch.rpm                                                                                                                                                 2.8 MB/s |  22 kB     00:00
(17/34): perl-ExtUtils-Constant-0.25-481.el9.noarch.rpm                                                                                                                                         5.9 MB/s |  49 kB     00:00
(18/34): perl-File-Compare-1.100.600-481.el9.noarch.rpm                                                                                                                                         1.7 MB/s |  14 kB     00:00
(19/34): perl-devel-5.32.1-481.el9.x86_64.rpm                                                                                                                                                    21 MB/s | 680 kB     00:00
(20/34): perl-lib-0.65-481.el9.x86_64.rpm                                                                                                                                                       2.1 MB/s |  15 kB     00:00
(21/34): python3-pip-21.2.3-8.el9.noarch.rpm                                                                                                                                                     26 MB/s | 2.0 MB     00:00
(22/34): efi-filesystem-6-2.el9_0.noarch.rpm                                                                                                                                                    1.8 MB/s | 9.5 kB     00:00
(23/34): python3-devel-3.9.18-3.el9_4.5.x86_64.rpm                                                                                                                                              8.6 MB/s | 248 kB     00:00
(24/34): efibootmgr-16-12.el9.x86_64.rpm                                                                                                                                                        5.0 MB/s |  48 kB     00:00
(25/34): efivar-libs-38-3.el9.x86_64.rpm                                                                                                                                                         15 MB/s | 124 kB     00:00
(26/34): mokutil-0.6.0-4.el9.x86_64.rpm                                                                                                                                                         5.2 MB/s |  50 kB     00:00
(27/34): python-unversioned-command-3.9.18-3.el9_4.5.noarch.rpm                                                                                                                                 2.2 MB/s |  10 kB     00:00
(28/34): python3-3.9.18-3.el9_4.5.x86_64.rpm                                                                                                                                                    6.9 MB/s |  30 kB     00:00
(29/34): perl-doc-5.32.1-481.el9.noarch.rpm                                                                                                                                                      27 MB/s | 4.6 MB     00:00
(30/34): openssl-3.0.7-28.el9_4.x86_64.rpm                                                                                                                                                       30 MB/s | 1.2 MB     00:00
(31/34): openssl-devel-3.0.7-28.el9_4.x86_64.rpm                                                                                                                                                 25 MB/s | 4.1 MB     00:00
(32/34): openssl-libs-3.0.7-28.el9_4.x86_64.rpm                                                                                                                                                  22 MB/s | 1.9 MB     00:00
(33/34): openssl-libs-3.0.7-28.el9_4.i686.rpm                                                                                                                                                    29 MB/s | 1.9 MB     00:00
(34/34): python3-libs-3.9.18-3.el9_4.5.x86_64.rpm                                                                                                                                                27 MB/s | 7.9 MB     00:00
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                            44 MB/s |  27 MB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                                        1/1
  Upgrading        : openssl-libs-1:3.0.7-28.el9_4.x86_64                                                                                                                                                                  1/41
  Installing       : perl-version-7:0.99.28-4.el9.x86_64                                                                                                                                                                   2/41
  Installing       : perl-CPAN-Meta-Requirements-2.140-461.el9.noarch                                                                                                                                                      3/41
  Upgrading        : python3-libs-3.9.18-3.el9_4.5.x86_64                                                                                                                                                                  4/41
  Upgrading        : python3-3.9.18-3.el9_4.5.x86_64                                                                                                                                                                       5/41
  Upgrading        : python-unversioned-command-3.9.18-3.el9_4.5.noarch                                                                                                                                                    6/41
  Installing       : efivar-libs-38-3.el9.x86_64                                                                                                                                                                           7/41
  Installing       : perl-File-Compare-1.100.600-481.el9.noarch                                                                                                                                                            8/41
  Installing       : perl-JSON-PP-1:4.06-4.el9.noarch                                                                                                                                                                      9/41
  Installing       : perl-ExtUtils-ParseXS-1:3.40-460.el9.noarch                                                                                                                                                          10/41
  Installing       : python3-pip-21.2.3-8.el9.noarch                                                                                                                                                                      11/41
  Installing       : systemtap-sdt-devel-5.0-4.el9.x86_64                                                                                                                                                                 12/41
  Installing       : efi-filesystem-6-2.el9_0.noarch                                                                                                                                                                      13/41
  Installing       : perl-lib-0.65-481.el9.x86_64                                                                                                                                                                         14/41
  Installing       : perl-doc-5.32.1-481.el9.noarch                                                                                                                                                                       15/41
  Installing       : perl-ExtUtils-Constant-0.25-481.el9.noarch                                                                                                                                                           16/41
  Installing       : perl-AutoSplit-5.74-481.el9.noarch                                                                                                                                                                   17/41
  Installing       : perl-Benchmark-1.23-481.el9.noarch                                                                                                                                                                   18/41
  Installing       : perl-Test-Harness-1:3.42-461.el9.noarch                                                                                                                                                              19/41
  Installing       : perl-ExtUtils-Command-2:7.60-3.el9.noarch                                                                                                                                                            20/41
  Installing       : perl-Devel-PPPort-3.62-4.el9.x86_64                                                                                                                                                                  21/41
  Installing       : perl-ExtUtils-Manifest-1:1.73-4.el9.noarch                                                                                                                                                           22/41
  Installing       : perl-CPAN-Meta-YAML-0.018-461.el9.noarch                                                                                                                                                             23/41
  Installing       : perl-CPAN-Meta-2.150010-460.el9.noarch                                                                                                                                                               24/41
  Installing       : perl-devel-4:5.32.1-481.el9.x86_64                                                                                                                                                                   25/41
  Installing       : perl-ExtUtils-Install-2.20-4.el9.noarch                                                                                                                                                              26/41
  Installing       : perl-ExtUtils-MakeMaker-2:7.60-3.el9.noarch                                                                                                                                                          27/41
  Installing       : efibootmgr-16-12.el9.x86_64                                                                                                                                                                          28/41
  Installing       : python3-devel-3.9.18-3.el9_4.5.x86_64                                                                                                                                                                29/41
  Installing       : mokutil-2:0.6.0-4.el9.x86_64                                                                                                                                                                         30/41
  Upgrading        : openssl-devel-1:3.0.7-28.el9_4.x86_64                                                                                                                                                                31/41
  Upgrading        : openssl-1:3.0.7-28.el9_4.x86_64                                                                                                                                                                      32/41
  Installing       : patch-2.7.6-16.el9.x86_64                                                                                                                                                                            33/41
  Upgrading        : openssl-libs-1:3.0.7-28.el9_4.i686                                                                                                                                                                   34/41
  Cleanup          : openssl-devel-1:3.0.7-27.el9.x86_64                                                                                                                                                                  35/41
  Cleanup          : python-unversioned-command-3.9.18-3.el9.noarch                                                                                                                                                       36/41
  Cleanup          : openssl-1:3.0.7-27.el9.x86_64                                                                                                                                                                        37/41
  Cleanup          : openssl-libs-1:3.0.7-27.el9.i686                                                                                                                                                                     38/41
  Cleanup          : python3-3.9.18-3.el9.x86_64                                                                                                                                                                          39/41
  Cleanup          : python3-libs-3.9.18-3.el9.x86_64                                                                                                                                                                     40/41
  Cleanup          : openssl-libs-1:3.0.7-27.el9.x86_64                                                                                                                                                                   41/41
  Running scriptlet: openssl-libs-1:3.0.7-27.el9.x86_64                                                                                                                                                                   41/41
  Verifying        : perl-CPAN-Meta-2.150010-460.el9.noarch                                                                                                                                                                1/41
  Verifying        : perl-CPAN-Meta-Requirements-2.140-461.el9.noarch                                                                                                                                                      2/41
  Verifying        : perl-CPAN-Meta-YAML-0.018-461.el9.noarch                                                                                                                                                              3/41
  Verifying        : perl-ExtUtils-Install-2.20-4.el9.noarch                                                                                                                                                               4/41
  Verifying        : perl-version-7:0.99.28-4.el9.x86_64                                                                                                                                                                   5/41
  Verifying        : perl-ExtUtils-MakeMaker-2:7.60-3.el9.noarch                                                                                                                                                           6/41
  Verifying        : perl-ExtUtils-Manifest-1:1.73-4.el9.noarch                                                                                                                                                            7/41
  Verifying        : perl-ExtUtils-ParseXS-1:3.40-460.el9.noarch                                                                                                                                                           8/41
  Verifying        : perl-Test-Harness-1:3.42-461.el9.noarch                                                                                                                                                               9/41
  Verifying        : patch-2.7.6-16.el9.x86_64                                                                                                                                                                            10/41
  Verifying        : perl-Devel-PPPort-3.62-4.el9.x86_64                                                                                                                                                                  11/41
  Verifying        : perl-ExtUtils-Command-2:7.60-3.el9.noarch                                                                                                                                                            12/41
  Verifying        : perl-JSON-PP-1:4.06-4.el9.noarch                                                                                                                                                                     13/41
  Verifying        : perl-Benchmark-1.23-481.el9.noarch                                                                                                                                                                   14/41
  Verifying        : python3-pip-21.2.3-8.el9.noarch                                                                                                                                                                      15/41
  Verifying        : systemtap-sdt-devel-5.0-4.el9.x86_64                                                                                                                                                                 16/41
  Verifying        : perl-AutoSplit-5.74-481.el9.noarch                                                                                                                                                                   17/41
  Verifying        : perl-ExtUtils-Constant-0.25-481.el9.noarch                                                                                                                                                           18/41
  Verifying        : perl-File-Compare-1.100.600-481.el9.noarch                                                                                                                                                           19/41
  Verifying        : perl-devel-4:5.32.1-481.el9.x86_64                                                                                                                                                                   20/41
  Verifying        : perl-doc-5.32.1-481.el9.noarch                                                                                                                                                                       21/41
  Verifying        : perl-lib-0.65-481.el9.x86_64                                                                                                                                                                         22/41
  Verifying        : python3-devel-3.9.18-3.el9_4.5.x86_64                                                                                                                                                                23/41
  Verifying        : efi-filesystem-6-2.el9_0.noarch                                                                                                                                                                      24/41
  Verifying        : efibootmgr-16-12.el9.x86_64                                                                                                                                                                          25/41
  Verifying        : efivar-libs-38-3.el9.x86_64                                                                                                                                                                          26/41
  Verifying        : mokutil-2:0.6.0-4.el9.x86_64                                                                                                                                                                         27/41
  Verifying        : python-unversioned-command-3.9.18-3.el9_4.5.noarch                                                                                                                                                   28/41
  Verifying        : python-unversioned-command-3.9.18-3.el9.noarch                                                                                                                                                       29/41
  Verifying        : openssl-devel-1:3.0.7-28.el9_4.x86_64                                                                                                                                                                30/41
  Verifying        : openssl-devel-1:3.0.7-27.el9.x86_64                                                                                                                                                                  31/41
  Verifying        : python3-3.9.18-3.el9_4.5.x86_64                                                                                                                                                                      32/41
  Verifying        : python3-3.9.18-3.el9.x86_64                                                                                                                                                                          33/41
  Verifying        : python3-libs-3.9.18-3.el9_4.5.x86_64                                                                                                                                                                 34/41
  Verifying        : python3-libs-3.9.18-3.el9.x86_64                                                                                                                                                                     35/41
  Verifying        : openssl-1:3.0.7-28.el9_4.x86_64                                                                                                                                                                      36/41
  Verifying        : openssl-1:3.0.7-27.el9.x86_64                                                                                                                                                                        37/41
  Verifying        : openssl-libs-1:3.0.7-28.el9_4.x86_64                                                                                                                                                                 38/41
  Verifying        : openssl-libs-1:3.0.7-27.el9.x86_64                                                                                                                                                                   39/41
  Verifying        : openssl-libs-1:3.0.7-28.el9_4.i686                                                                                                                                                                   40/41
  Verifying        : openssl-libs-1:3.0.7-27.el9.i686                                                                                                                                                                     41/41
Installed products updated.

Upgraded:
  openssl-1:3.0.7-28.el9_4.x86_64       openssl-devel-1:3.0.7-28.el9_4.x86_64       openssl-libs-1:3.0.7-28.el9_4.i686       openssl-libs-1:3.0.7-28.el9_4.x86_64       python-unversioned-command-3.9.18-3.el9_4.5.noarch
  python3-3.9.18-3.el9_4.5.x86_64       python3-libs-3.9.18-3.el9_4.5.x86_64
Installed:
  efi-filesystem-6-2.el9_0.noarch                             efibootmgr-16-12.el9.x86_64                           efivar-libs-38-3.el9.x86_64                            mokutil-2:0.6.0-4.el9.x86_64
  patch-2.7.6-16.el9.x86_64                                   perl-AutoSplit-5.74-481.el9.noarch                    perl-Benchmark-1.23-481.el9.noarch                     perl-CPAN-Meta-2.150010-460.el9.noarch
  perl-CPAN-Meta-Requirements-2.140-461.el9.noarch            perl-CPAN-Meta-YAML-0.018-461.el9.noarch              perl-Devel-PPPort-3.62-4.el9.x86_64                    perl-ExtUtils-Command-2:7.60-3.el9.noarch
  perl-ExtUtils-Constant-0.25-481.el9.noarch                  perl-ExtUtils-Install-2.20-4.el9.noarch               perl-ExtUtils-MakeMaker-2:7.60-3.el9.noarch            perl-ExtUtils-Manifest-1:1.73-4.el9.noarch
  perl-ExtUtils-ParseXS-1:3.40-460.el9.noarch                 perl-File-Compare-1.100.600-481.el9.noarch            perl-JSON-PP-1:4.06-4.el9.noarch                       perl-Test-Harness-1:3.42-461.el9.noarch
  perl-devel-4:5.32.1-481.el9.x86_64                          perl-doc-5.32.1-481.el9.noarch                        perl-lib-0.65-481.el9.x86_64                           perl-version-7:0.99.28-4.el9.x86_64
  python3-devel-3.9.18-3.el9_4.5.x86_64                       python3-pip-21.2.3-8.el9.noarch                       systemtap-sdt-devel-5.0-4.el9.x86_64

Complete!
OS package installations finished
+ Installing ONTAP Mediator. (Log: /root/ontap_mediator.T7uce6/ontap-mediator-1.9.0/ontap-mediator-1.9.0/install_20241017092214.log)
    This step will take several minutes. Use the log file to view progress.
    Sudoer config verified
    ONTAP Mediator rsyslog and logging rotation enabled
+ Install successful. (Moving log to /opt/netapp/lib/ontap_mediator/log/install_20241017092214.log)

+ Note: ONTAP Mediator generated a self-signed server certificate for temporary use on
    this host. If the DNS name or IP address for the host is changed, the certificate
    will no longer be valid. The default certificates should be replaced with secure
    trusted certificates signed by a known certificate authority prior to use for production.
    For more information, see /opt/netapp/lib/ontap_mediator/README

+ Note: ONTAP Mediator uses a kernel module compiled specifically for the current
        OS. Using 'yum update' to upgrade the kernel might cause service interruption.
    For more information, see /opt/netapp/lib/ontap_mediator/README

[root@mediator_host ~]# systemctl status ontap_mediator
● ontap_mediator.service - ONTAP Mediator
     Loaded: loaded (/etc/systemd/system/ontap_mediator.service; enabled; preset: disabled)
     Active: active (running) since Thu 2024-10-17 09:27:14 EDT; 1min 12s ago
    Process: 54470 ExecStartPre=/opt/netapp/lib/ontap_mediator/tools/otm_logs_fs.sh (code=exited, status=0/SUCCESS)
   Main PID: 54489 (uwsgi)
     Status: "uWSGI is ready"
      Tasks: 3 (limit: 11104)
     Memory: 77.1M
        CPU: 2.507s
     CGroup: /system.slice/ontap_mediator.service
             ├─54489 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
             ├─54504 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
             └─54507 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini

Oct 17 09:27:10 mediator_host ontap_mediator[54476]: Creating filesystem with 192000 4k blocks and 48000 inodes
Oct 17 09:27:10 mediator_host ontap_mediator[54476]: Filesystem UUID: b1fa0a40-0e7d-4c67-bbff-33421f3ec61b
Oct 17 09:27:10 mediator_host ontap_mediator[54476]: Superblock backups stored on blocks:
Oct 17 09:27:10 mediator_host ontap_mediator[54476]:         32768, 98304, 163840
Oct 17 09:27:10 mediator_host ontap_mediator[54476]: [41B blob data]
Oct 17 09:27:10 mediator_host ontap_mediator[54476]: [38B blob data]
Oct 17 09:27:10 mediator_host ontap_mediator[54476]: Creating journal (4096 blocks): done
Oct 17 09:27:10 mediator_host ontap_mediator[54476]: [75B blob data]
Oct 17 09:27:10 mediator_host ontap_mediator[54489]: [uWSGI] getting INI configuration from /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
Oct 17 09:27:14 mediator_host systemd[1]: Started ONTAP Mediator.

[root@mediator_host ~]# systemctl status mediator-scst
● mediator-scst.service
     Loaded: loaded (/etc/systemd/system/mediator-scst.service; enabled; preset: disabled)
     Active: active (running) since Thu 2024-10-17 09:27:08 EDT; 1min 32s ago
    Process: 54384 ExecStart=/etc/init.d/scst start (code=exited, status=0/SUCCESS)
    Process: 54467 ExecStartPost=/usr/sbin/modprobe scst_vdisk (code=exited, status=0/SUCCESS)
   Main PID: 54425 (iscsi-scstd)
      Tasks: 1 (limit: 11104)
     Memory: 1.2M
        CPU: 494ms
     CGroup: /system.slice/mediator-scst.service
             └─54425 /usr/local/sbin/iscsi-scstd

Oct 17 09:27:07 mediator_host systemd[1]: Starting mediator-scst.service...
Oct 17 09:27:08 mediator_host iscsi-scstd[54423]: max_data_seg_len 1048576, max_queued_cmds 2048
Oct 17 09:27:08 mediator_host scst[54384]: Loading and configuring SCST
Oct 17 09:27:08 mediator_host systemd[1]: Started mediator-scst.service.
[root@mediator_host ~]#
[vm2] 0:root@mediator_host:~*                                                                                                                                                             "cycrh7rtp04.rtp.eng.n" 09:29 17-Oct-24
----
====

// 2023 July 24, Public PR 1012
// 2021-04-21 ONTAPEX-133437
// 2021-05-05 review comment in IDR-67
// ontap-metrocluster issue #146, 7 march 2022
// 2022-04-28, BURT 1470656
// january 2022 ontap-metrocluster/issues/35
// 19 july 2022, ontap-issues-564
// April 22 2022, BURT 1470656
// ONTAPDOC-955, 2023 May 05
// ONTAPDOC-1689, 24 Feb 2024
//ontapdoc 1906, 06 june 2024
