---
permalink: mediator/manage-task.html
sidebar: sidebar
keywords: mediator, username, password, change, uninstall
summary: After you have installed ONTAP Mediator service, you might want to change the user name or password. You may also uninstall the ONTAP Mediator Service.
---

= Manage the ONTAP mediator service
:icons: font
:imagesdir: ../media/

[.lead]
After you have installed ONTAP Mediator service, you may change the user name or password. You may also uninstall the ONTAP Mediator Service.

== Change the user name

.About these tasks

These task is performed on the Linux host on which the ONTAP Mediator service is installed.

If you are unable to reach this command, you might need to run the command using the full path as shown in the following example:

`/usr/local/bin/mediator_username`

.Procedure

Change the username by choosing one of the following options:

* Run the command mediator_change_user and respond to the prompts as shown in the following example:
+
....
 [root@mediator-host ~]# mediator_change_user
 Modify the Mediator API username by entering the following values:
     Mediator API User Name: mediatoradmin
                   Password:
 New Mediator API User Name: mediator
 The account username has been modified successfully.
 [root@mediator-host ~]#
....

* Run the following command:
+
`MEDIATOR_USERNAME=mediator MEDIATOR_PASSWORD=mediator2 MEDIATOR_NEW_USERNAME=mediatoradmin mediator_change_user`
+
....
 [root@mediator-host ~]# MEDIATOR_USERNAME= mediator MEDIATOR_PASSWORD='mediator2' MEDIATOR_NEW_USERNAME= mediatoradmin mediator_change_user
 The account username has been modified successfully.
 [root@mediator-host ~]#
....

== Change the password

.About this task

This task is performed on the Linux host on which the ONTAP Mediator service is installed.

If you are unable to reach this command, you might need to run the command using the full path as shown in the following example:

`/usr/local/bin/mediator_change_password`

.Procedure

Change the password by choosing one of the following options:

* Run the `mediator_change_password` command and respond to the prompts as shown in the following example:
+
....
 [root@mediator-host ~]# mediator_change_password
 Change the Mediator API password by entering the following values:
    Mediator API User Name: mediatoradmin
              Old Password:
              New Password:
          Confirm Password:
 The password has been updated successfully.
 [root@mediator-host ~]#
....

* Run the following command:
+
`MEDIATOR_USERNAME= mediatoradmin MEDIATOR_PASSWORD=mediator1 MEDIATOR_NEW_PASSWORD=mediator2 mediator_change_password`
+
The example shows the password is changed from "mediator1" to "mediator2".
+
....
 [root@mediator-host ~]# MEDIATOR_USERNAME=mediatoradmin MEDIATOR_PASSWORD=mediator1 MEDIATOR_NEW_PASSWORD=mediator2 mediator_change_password
 The password has been updated successfully.
 [root@mediator-host ~]#
....

== Stop the ONTAP Mediator service
To stop the ONTAP Mediator service, perform the following steps:

.Steps
. Stop the ONTAP Mediator.
+
`systemctl stop ontap_mediator`

. Stop SCST.
+
`systemctl stop mediator-scst`

. Disable the ONTAP Mediator and SCST.
+
`systemctl diable ontap_mediator mediator-scst`

== Re-enable the ONTAP Mediator service
To re-enable the ONTAP Mediator service, perform the following steps:

.Steps
. Enable the ONTAP Mediator and SCST.
+
`systemctl enable ontap_mediator mediator-scst`

. Start SCST.
+
`systemctl start mediator-scst`

. Start ONTAP Mediator.
+
`systemctl start ontap_mediator`

== Verify the ONTAP Mediator is healthy
After the ONTAP Mediator has been installed, you should verify that the ONTAP Mediator services are running.

.Steps

. View the status of the ONTAP Mediator services:

.. `systemctl status ontap_mediator`
+
----
[root@scspr1915530002 ~]# systemctl status ontap_mediator

 ontap_mediator.service - ONTAP Mediator
Loaded: loaded (/etc/systemd/system/ontap_mediator.service; enabled; vendor preset: disabled)
Active: active (running) since Mon 2022-04-18 10:41:49 EDT; 1 weeks 0 days ago
Process: 286710 ExecStop=/bin/kill -s INT $MAINPID (code=exited, status=0/SUCCESS)
Main PID: 286712 (uwsgi)
Status: "uWSGI is ready"
Tasks: 3 (limit: 49473)
Memory: 139.2M
CGroup: /system.slice/ontap_mediator.service
      ├─286712 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
      ├─286716 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
      └─286717 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini

[root@scspr1915530002 ~]#
----

+
.. `systemctl status mediator-scst`
+
----
[root@scspr1915530002 ~]# systemctl status mediator-scst
   Loaded: loaded (/etc/systemd/system/mediator-scst.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2022-04-18 10:41:47 EDT; 1 weeks 0 days ago
  Process: 286595 ExecStart=/etc/init.d/scst start (code=exited, status=0/SUCCESS)
 Main PID: 286662 (iscsi-scstd)
    Tasks: 1 (limit: 49473)
   Memory: 1.2M
   CGroup: /system.slice/mediator-scst.service
           └─286662 /usr/local/sbin/iscsi-scstd

[root@scspr1915530002 ~]#
----

. Confirm the ports that are used by the ONTAP Mediator service: 
+
`netstat`
+
----
[root@scspr1905507001 ~]# netstat -anlt | grep -E '3260|31784'

         tcp   0   0 0.0.0.0:31784   0.0.0.0:*      LISTEN

         tcp   0   0 0.0.0.0:3260    0.0.0.0:*      LISTEN

         tcp6  0   0 :::3260         :::*           LISTEN
----


== Uninstall SCST to perform host maintenance

== Manually install SCST to perform host maintenance

== Uninstall the ONTAP Mediator service

.Before you begin

If necessary, you can remove the ONTAP Mediator service. The Mediator must be disconnected from ONTAP before you remove the Mediator service.

.About this task

This task is performed on the Linux host on which the ONTAP Mediator service is installed.

If you are unable to reach this command, you might need to run the command using the full path as shown in the following example:

`/usr/local/bin/uninstall_ontap_mediator`

.Step

. Uninstall the ONTAP Mediator service:
+
`uninstall_ontap_mediator`
+
....
 [root@mediator-host ~]# uninstall_ontap_mediator

 ONTAP Mediator: Self Extracting Uninstaller

 + Removing ONTAP Mediator. (Log: /tmp/ontap_mediator.GmRGdA/uninstall_ontap_mediator/remove.log)
 + Remove successful.
 [root@mediator-host ~]#
....



// ontap-metrocluster issue #146, 7 march 2022
