---
permalink: mediator/upgrade-host-os-mediator-task.html
sidebar: sidebar
keywords: mediator, new, release, update, install,
summary: "As part of the installation process, you upgrade the host operating system and then the ONTAP Mediator."
---

= Upgrade the host operating system and then the ONTAP Mediator
:icons: font
:imagesdir: ../media/

[.lead]
As part of the installation process, you upgrade the host operating system and then the ONTAP Mediator.

The following table provides the upgrade guidelines if you are upgrading from RHEL/CentOS 7.6 to a later RHEL/CentOS release in addition to upgrading the ONTAP Mediator version.

[cols="20,20,60"]
|===

h| Target Linux version h| Target Mediator version h| Upgrade notes

a|
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 8.1
* CentOS: 7.6, 7.7, 7.8
a|
1.2
a|

* The upgrade must be performed in the following order:
 .. Upgrade the operating system from RHEL/CentOS version.
 .. Reboot the host to apply the kernel module changes.
 .. Upgrade the Mediator from the immediately prior version to the current version.
* For MetroCluster:
. The storage iscsi-initiator show command will report that the connection to the Mediator service is down during the upgrade.
. The ONTAP operating system will generate the following EMS events:
 .. cf.mccip.med.auso.stDisabled during the upgrade
 .. cf.mccip.med.auso.stEnabled when automatic unplanned switchover is re-enabled

a|
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3
* CentOS: 7.6, 7.7, 7.8, 7.9
a|
1.3
a|
.. Upgrade the operating system from RHEL/CentOS version.
.. Reboot the host to apply the kernel module changes.
.. Upgrade the Mediator from the immediately prior version to the current version.


a|
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9
a|
1.4
a|
.. Upgrade the operating system from RHEL/CentOS version.
.. Reboot the host to apply the kernel module changes.
.. Upgrade the Mediator from the immediately prior version to the current version.
a|
* Red Hat Enterprise Linux: 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9
a|
1.5
a|
.. Upgrade the operating system from RHEL/CentOS version.
.. Reboot the host to apply the kernel module changes.
If you do not reboot the host, an error message appears prompting you to perform a reboot.
.. Upgrade the Mediator from the immediately prior version to the current version.
a|


|===

== Best practices

The best practices for installing Red Hat Enterprise Linux or CentOS and the associated repositories on your system are listed below. Systems installed or configured differently might require additional steps.

* You must install Red Hat Enterprise Linux or CentOS according to Red Hat best practices. Due to end-of-life support for CentOS 8.x versions, compatible versions of CentOS 8.x are not recommended.
* While installing the ONTAP Mediator service on Red Hat Enterprise Linux or CentOS, the system must have access to the appropriate repository so that the installation program can access and install all the required software dependencies.
* For the yum installer to find dependent software in the Red Hat Enterprise Linux repositories, you must have registered the system during the Red Hat Enterprise Linux installation or afterwards by using a valid Red Hat subscription.
+
See the Red Hat documentation for information about the Red Hat Subscription Manager.
* The following ports must be unused and available for the Mediator:
 ** 31784
 ** 3260
* If using a third-party firewall: refer to link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html#firewall-requirements-for-ontap-mediator[Firewall requirements for ONTAP Mediator^]
* If the Linux host is in a location without access to the internet, you must ensure that the required packages are available in a local repository.
+
If you are using Link Aggregation Control Protocol (LACP) in a Linux environment, you must correctly configure the kernel and make sure the `sysctl net.ipv4.conf.all.arp_ignore` is set to "2".

== Required packages
The following packages are required by the ONTAP Mediator service:

[cols="25,35,40"]
|===

h| All RHEL/CentOS versions h| Additional packages for RHEL/CentOS 7.x h| Additional packages for RHEL 8.x

a|

 ** openssl
 ** openssl-devel
 ** kernel-devel
 ** gcc
 ** libselinux-utils
 ** make
 ** redhat-lsb-core
 ** patch
 ** bzip2
 ** python36
 ** python36-devel
 ** perl-Data-Dumper
 ** perl-ExtUtils-MakeMaker
 ** python3-pip

a|

 ** policycoreutils-python
 ** python36-pip

a|

 ** elfutils-libelf-devel
 ** policycoreutils-python-utils

+
|===

The Mediator installation package is a self-extracting compressed tar file that includes:

* An RPM file containing all dependencies that cannot be obtained from the supported release's repository.
* An install script.

A valid SSL certification is recommended.

// 2021-04-21 ONTAPEX-133437
// 2021-05-05 review comment in IDR-67
// ontap-metrocluster issue #146, 7 march 2022
// 2022-04-28, BURT 1470656
// january 2022 ontap-metrocluster/issues/35
// 19 july 2022, ontap-issues-564
// ONTAPDOC-955, 2023 May 05
