---
permalink: mediator/verify-code-signature-task.html
sidebar: sidebar
keywords: mediator, new, release, update, install, verify, code, signature
summary: "You should verify the ONTAP Mediator code signature before installing the Mediator installation package."
---
= Verify the ONTAP Mediator code signature
:icons: font
:imagesdir: ../media/

[.lead]
NetApp recommends verifying the ONTAP Mediator code signature before installation. This step is optional.

.Before you begin

Make sure your system meets these needs before verifying the ONTAP Mediator code signature.

[NOTE]
====
* From June 15th, 2025, you can't install or upgrade to ONTAP Mediator 1.9 and 1.8 because the code signature verification certificates have expired. Instead, install or upgrade to ONTAP Mediator 1.11 or 1.10.
* If the system doesn't meet the below requirements, the verification process isn't required and you can go directly to link:install-mediator-pkg-task.html[Install the ONTAP Mediator installation package].
====

** openssl versions 1.0.2 to 3.0 for basic verification
** openssl version 1.1.0 or later for Time Stamping Authority (TSA) operations
** Public internet access for OCSP verification

The download package includes the following files:

[cols="50,50"]
|===

h| File  h| Description

a| `ONTAP-Mediator-production.pub`      a| The public key used to verify the signature
a| `csc-prod-chain-ONTAP-Mediator.pem`  a| The public certification CA chain of trust
a| `csc-prod-ONTAP-Mediator.pem`        a| The certificate used to generate the key
a| `ontap-mediator-1.11.0`               a| The product installation executable for version 1.11
a| `ontap-mediator-1.11.0.sig`           a| The SHA-256 hashed, then RSA-signed using the csc-prod key, signature for the installer
a| `ontap-mediator-1.11.0.sig.tsr`       a| The revocation request for use by OCSCP for the installer’s signature
a|`ontap-mediator-1.11.0.tsr`            a| The timestamp signing request file
a| `tsa-prod-ONTAP-Mediator.pem`        a| The public certificate for the TSR
a| `tsa-prod-chain-ONTAP-Mediator.pem`  a| The public certificate CA Chain for the TSR

|===

.Steps

. Perform the revocation check on `csc-prod-ONTAP-Mediator.pem` by using Online Certificate Status Protocol (OCSP).

.. Find the OCSP URL for the certificate. Developer certificates might not provide a URI:
+
----
openssl x509 -noout -ocsp_uri -in csc-prod-chain-ONTAP-Mediator.pem
----
.. Generate an OCSP request for the certificate. 
+
----
openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem  -reqout req.der
----
	
.. Connect to the OCSP Manager to send the OCSP request: 
+
----
openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem  -url ${ocsp_uri} -resp_text -respout resp.der -verify_other csc-prod-chain-ONTAP-Mediator.pem
----


. Verify the trust chain of the CSC and expiration dates against the local host: 
+
`openssl verify`
+
NOTE: The `openssl` version from the PATH must have a valid `cert.pem` (not self-signed).
+
----
openssl verify -untrusted csc-prod-chain-ONTAP-Mediator.pem -CApath ${OPENSSLDIR} csc-prod-ONTAP-Mediator.pem  # Failure action: The Code-Signature-Check certificate has expired or is invalid. Download a newer version of the ONTAP Mediator.
openssl verify -untrusted tsa-prod-chain-ONTAP-Mediator.pem -CApath ${OPENSSLDIR} tsa-prod-ONTAP-Mediator.pem  # Failure action: The Time-Stamp certificate has expired or is invalid. Download a newer version of the ONTAP Mediator.
----
    
. Verify the `ontap-mediator-1.11.0.sig.tsr` and `ontap-mediator-1.11.0.tsr` files using the associated certificates: 
+

[role="tabbed-block"]
====
.OpenSSL 3.x
--
`openssl ts -verify -data ontap-mediator-1.11.0.sig -in ontap-mediator-1.11.0.sig.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -untrusted tsa-prod-ONTAP-Mediator.pem`
--
.OpenSSL 1.x
--
`openssl ts -verify -data ontap-mediator-1.11.0 -in ontap-mediator-1.11.0.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -partial_chain`
--
====
+
NOTE: `.tsr` files contain the time stamp response associated with the installer and the code signature. Processing confirms that the time stamp has a valid signature from TSA and that your input file has not changed.
Your machine performs the verification locally. You do not need to access TSA servers.

. Verify signatures against the key:  
+
`openssl -dgst -verify`
+
----
openssl dgst -sha256 -verify ONTAP-Mediator-production.pub -signature ontap-mediator-1.11.0.sig ontap-mediator-1.11.0
----


// 2021 Apr 21, ONTAPEX-133437
// 2021 May 05, review comment in IDR-67
// 2022 Mar 07, ontap-metrocluster issue #146
// 2022 Apr 28, BURT 1470656
// 2022 Jan 15, ontap-metrocluster/issues/35
// 2022 Jul 19, ontap-issues-564
// 2023 May 05, ONTAPDOC-955
// 2023 Jun 02, ONTAPDOC-1064
// 2023 Dec 06, ONTAPDOC-1427
// ontapdoc-1906, 12 june 2024
// ONTAPDOC-728, 12 Feb 2025
// ONTAPDOC-3053, 9 Jun 2025
// ONTAPDOC-3089, 2 Jul 2025
// ONTAPDOC-3276, 19 Aug 2025
// ONTAPDOC-3217, 2 Oct 2025