---
sidebar: sidebar
permalink: flexcache-hot-spot/flexcache-hotspot-remediation-hdfa-examples.html
keywords: key, words, here
summary: "Let's look at a few examples of how high-density FlexCache arrays can help remediate hot-spotting."
---
= Auto-provisioned FlexCache vs high-density FlexCache array (HDFA)

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
Design decision one is to figure out how dense of FlexCaches you want to make. Let’s look at a few examples. The examples will be four-node clusters. We will assume that the file count is evenly distributed amongst all the constituents in each HDF. We will also assume an even distribution of frontend NAS connections across all nodes.

NOTE: HDFAs will be represented using the following syntax: `HDFs per HDFA x nodes per HDF x constituents per node per HDF`

== Example 1: 2x2x2 HDFA
<<Figure 2>> below is a 2x2x2 HDFA configuration—two HDFs, each spanning two nodes, and each node containing two constituent volumes. In this example, each client has a 50% chance of having direct access to the hot file. Two of the four client will still have east-west traffic. The biggest thing here is there are now two HDFs, which means two distinct caches of the hot file. There are now two CPUs/volume affinities servicing access to the hot file.

image::FlexCache-Hotspot-HDFA-2x2x2.svg[Figure 2: 2x2x2 HDFA]

== Example 2: 4x1x4 HDFA
Figure 3 is our ultimate goal. It is a 4x1x4 HDFA configuration—four HDFs, each contained to a single node, and each node containing four constituents. In this example, each client is guaranteed to have direct access to a cache of the hot file. Since there are four cached files on four different nodes, we have four different CPUs/volume affinities to help service access to the hot file. Additionally, there is zero east-west traffic generated.

image::FlexCache-Hotspot-HDFA-4x1x4.svg[Figure 3: 4x1x4 HDFA]

These examples aren't the only configurations you can use. The guiding design principle is to make as many HDFs as your space requirements and available resources allow. Once you have decided how dense you want to make your HDFs, you have to make another design decision if you will be accessing the HDFs with NFS. Inter-SVM HDFAs or intra-SVM HDFAs are described in the next section.