---
sidebar: sidebar
permalink: ontap-deploy-secure/ldap-signing-sealing.html
keywords: ontap hardening guide, none, sign, seal, security on queries to an LDAP server
summary: "Lightweight Directory Access Protocol signing and sealing enable session security on queries to an LDAP server."
---
= Lightweight Directory Access Protocol signing and sealing
:hardbreaks:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
Signing and sealing are supported to enable session security on queries to an LDAP server. This approach provides an alternative to LDAP-over-TLS session security.

Signing confirms the integrity of LDAP payload data using secret key technology. Sealing encrypts the LDAP payload data to avoid transmitting sensitive information in clear text. The session security settings on an SVM correspond to those available on the LDAP server. By default, LDAP signing and sealing are disabled. To enable this function, run the `vserver cifs security modify` command with the `session-security-for-ad-ldap` parameter. See the following list of options for LDAP security functions:

* None (default, no signing or sealing)
* Sign (sign LDAP traffic)
* Seal (sign and encrypt LDAP traffic)

NOTE: The sign and seal parameters are cumulative, meaning that if the sign option is used, the outcome is LDAP with signing. However, if the seal option is used, the outcome is both sign and seal. In addition, if a parameter is not specified for this command, the default is none.

The following text provides an example configuration:
----
cluster1::> vserver cifs security modify -vserver vs1 -kerberos-clock-skew 3 -kerberos-ticket-age 8 -session-security-for-ad-ldap seal
----
