---
permalink: upgrade/concept_how_firmware_is_updated_during_the_data_ontap_upgrade.html
sidebar: sidebar
keywords: 
summary: 'Because upgrading ONTAP includes upgrading your firmware, you do not need to update firmware manually. When you perform an ONTAP upgrade, the firmware for your cluster included with the ONTAP upgrade package is copied to each node’s boot device, and the new firmware is installed automatically.'
---
= How firmware is updated during the ONTAP upgrade
:icons: font
:imagesdir: ../media/

[.lead]
Because upgrading ONTAP includes upgrading your firmware, you do not need to update firmware manually. When you perform an ONTAP upgrade, the firmware for your cluster included with the ONTAP upgrade package is copied to each node's boot device, and the new firmware is installed automatically.

Firmware for the following components is updated automatically if the version in your cluster is older than the firmware that is bundled with the ONTAP upgrade package:

* System and diagnostics:
 ** BIOS
 ** Flash Cache
 ** Service Processor (SP)
* Disk
* Disk shelf

If desired, you can also update firmware manually in between ONTAP upgrades.

*Related information*

https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics[NetApp Downloads: System Firmware and Diagnostics]

https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware[NetApp Downloads: Disk Drive Firmware]

https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware[NetApp Downloads: Disk Shelf Firmware]
