---
permalink: upgrade/concept_considerations_for_services_and_protocols_during_upgrades.html
sidebar: sidebar
keywords: 
summary: 'In general, services based on stateless protocols—such as NFSv3, FC, and iSCSI—are less susceptible to service interruptions during upgrades than session-oriented protocols—such as CIFS and NDMP.'
---
= Considerations for services and protocols during upgrades
:icons: font
:imagesdir: ../media/

[.lead]
In general, services based on stateless protocols--such as NFSv3, FC, and iSCSI--are less susceptible to service interruptions during upgrades than session-oriented protocols--such as CIFS and NDMP.

During an upgrade, each node in the cluster must be rebooted (by initiating an HA configuration takeover and giveback) to load the new software. Services based on stateless protocols usually remain available during the nondisruptive upgrade.

Stateless protocols usually include a timeout procedure. For example, if a message is sent and receipt is not acknowledged within a timeout period, a transmission error is assumed to have occurred. In a cluster, if the client's timeout period is greater than the disruption period on the cluster (for example, the amount of time a reboot or HA configuration giveback takes), the client does not perceive a disruption of cluster services.

In session-oriented protocols, there is no concept of timeout to protect the service from disruption. If session-oriented cluster services are disrupted, state information about any operation in progress is lost and the user must restart the operation.
