---
permalink: upgrade/task_verifying_storage_health_completing_post_upgrade_or_downgrade_tasks_for_the_cluster.html
sidebar: sidebar
keywords: 
summary: 'Before and after you upgrade, revert, or downgrade a cluster, you should verify the status of your disks, aggregates, and volumes.'
---
= Verifying storage health (completing post-upgrade or downgrade tasks)
:icons: font
:imagesdir: ../media/

[.lead]
Before and after you upgrade, revert, or downgrade a cluster, you should verify the status of your disks, aggregates, and volumes.

. If you are preparing to upgrade, revert, or downgrade, verify disk status:
+
|===
| To check for...| Do this...
a|
Broken disks
a|

 .. Display any broken disks: `storage disk show -state broken`
 .. Remove or replace any broken disks.

a|
Disks undergoing maintenance or reconstruction
a|

 .. Display any disks in maintenance, pending, or reconstructing states: `storage disk show -state maintenance|pending|reconstructing`
 .. Wait for the maintenance or reconstruction operation to finish before proceeding.

+
|===

. Verify that all aggregates are online by displaying the state of physical and logical storage, including storage aggregates: `storage aggregate show -state !online`
+
This command displays the aggregates that are _not_ online. All aggregates must be online before and after performing a major upgrade or reversion.
+
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----

. Verify that all volumes are online by displaying any volumes that are _not_ online: `volume show -state !online`
+
All volumes must be online before and after performing a major upgrade or reversion.
+
----
cluster1::> volume show -state !online
There are no entries matching your query.
----

. Verify that there are no inconsistent volumes: `volume show -is-inconsistent true`
+
If any inconsistent volumes are returned, you must contact NetApp Support before you precede with the upgrade.

*Related information*

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html[Disk and aggregate management]
