---
permalink: update/enable-automatic-updates-task.html
sidebar: sidebar
keywords: ontap, enable, upgrade, update, automatic, automated, firmware, bmc, sp, system, timezone database, timezone
summary: 'Enabling automatic updates allows ONTAP to download and install firmware and Time Zone Database updates without your intervention.'
---
= Enable automatic updates
:icons: font
:imagesdir: ../media/

[.lead]
Enabling automatic updates allows ONTAP to download and install firmware and Time Zone Database updates without your intervention. 

Automatic firmware updates are available beginning in ONTAP 9.10.1.  Automatic Time Zone Database updates are available beginning in ONTAP 9.13.1.

.About this task
To enable automatic updates, you must first enable AutoSupport with HTTPs.  If AutoSupport is not enabled on your cluster, or if your cluster is enabled with another transport protocol, you will be given the option to enable it with HTTPs during this procedure.

.Before you begin

You must have one of the following entitlements:

* AIQEXPERT
* AIQADVISOR
* AIQUPGRADE

.Steps

. In System Manager, click *Events*.
. In the *Overview* section, next to *Enable automatic update*, click *Actions>Enable*.
. If you do not have AutoSupport with HTTPs enabled, select to enable it.
. Accept the terms and conditions and *Save*.

// 2023 May 03, Jira 750