---
sidebar: sidebar
permalink: ontap-deploy-secure/oauth20-token-based-auth-for-rest-api.html
keywords: ontap hardening guide, security, access, oauth, oauth 2.0, token based authentication, rest api, tokens
summary: "OAuth 2.0 tokens replace passwords for user account authentication."
---
= ONTAP OAuth 2.0 token-based authentication for REST API
:hardbreaks:
:icons: font
:linkattrs:
:imagesdir: ../media

[.lead]
Rather than use of certificate-based authentication, you can use OAuth 2.0 token-based authentication for REST API.

Beginning with ONTAP 9.14.1, you have the option to control access to your ONTAP clusters using the Open Authorization (OAuth 2.0) framework. You can configure this feature using any of the ONTAP administrative interfaces, including the ONTAP CLI, System Manager, and REST API. However, the OAuth 2.0 authorization and access control decisions can only be applied when a client accesses ONTAP using the REST API.

OAuth 2.0 tokens replace passwords for user account authentication.

For more information about using OAuth 2.0, see the link:https://docs.netapp.com/us-en/ontap/authentication/overview-oauth2.html[ONTAP documentation on authentication and authorization using OAuth 2.0].

//6-24-24 ontapdoc-1938