---
permalink: data-protection/configure-destination-volume-data-access-concept.html
sidebar: sidebar
keywords: configure, destination, volume, data, access
summary: "After making the destination volume writeable, you must configure the volume for data access. NAS clients, NVMe subsystem, and SAN hosts can access the data from the destination volume until the source volume is reactivated."
---
= Configure the destination volume for data access
:icons: font
:imagesdir: ../media/

[.lead]
After making the destination volume writeable, you must configure the volume for data access. NAS clients, NVMe subsystem, and SAN hosts can access the data from the destination volume until the source volume is reactivated.

NAS environment:

. Mount the NAS volume to the namespace using the same junction path that the source volume was mounted to in the source SVM.
. Apply the appropriate ACLs to the SMB shares at the destination volume.
. Assign the NFS export policies to the destination volume.
. Apply the quota rules to the destination volume.
. Redirect clients to the destination volume.
. Remount the NFS and SMB shares on the clients.

SAN environment:

. Map the LUNs in the volume to the appropriate initiator group.
. For iSCSI, create iSCSI sessions from the SAN host initiators to the SAN LIFs.
. On the SAN client, perform a storage re-scan to detect the connected LUNs.

For information about NVMe environment, see link:../san-admin/index.html[SAN administration].

// 2022, Nov 11, Public PR 712