---
permalink: data-protection/convert-type-snapmirror-task.html
sidebar: sidebar
keywords: convert, snapmirror, relationship, asynchronous, synchronous, baseline, convert
summary: "Beginning with ONTAP 9.5, SnapMirror Synchronous is supported. You can convert an asynchronous SnapMirror relationship to a SnapMirror Synchronous relationship or vice versa without performing a baseline transfer."
---
= Convert the type of a SnapMirror relationship
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.5, SnapMirror Synchronous is supported. You can convert an asynchronous SnapMirror relationship to a SnapMirror Synchronous relationship or vice versa without performing a baseline transfer.

.About this task

You cannot convert an asynchronous SnapMirror relationship to a SnapMirror Synchronous relationship or vice versa by changing the SnapMirror policy

.Steps

* *Converting an asynchronous SnapMirror relationship to a SnapMirror Synchronous relationship*
 .. From the destination cluster, delete the asynchronous SnapMirror relationship:
+
`snapmirror delete -destination-path <SVM:volume>`
+
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----

 .. From the source cluster, release the SnapMirror relationship without deleting the common Snapshot copies:
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM>:<destination_volume>`
+
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----

 .. From the destination cluster, create a SnapMirror Synchronous relationship:
+
`snapmirror create -source-path _src_SVM:src_volume_ -destination-path <destination_SVM>:<destination_volume> -policy sync-mirror`
+
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----

 .. Resynchronize the SnapMirror Synchronous relationship:
+
`snapmirror resync -destination-path <destination_SVM:destination_volume>`
+
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----
* *Converting a SnapMirror Synchronous relationship to an asynchronous SnapMirror relationship*
 .. From the destination cluster, quiesce the existing SnapMirror Synchronous relationship:
+
`snapmirror quiesce -destination-path <destination_SVM>:<destination_volume>`
+
----
cluster2::> snapmirror quiesce -destination-path vs1_dr:vol1
----

 .. From the destination cluster, delete the asynchronous SnapMirror relationship:
+
`snapmirror delete -destination-path <SVM:volume>`
+
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----

 .. From the source cluster, release the SnapMirror relationship without deleting the common Snapshot copies:
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM:destination_volume>`
+
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----

 .. From the destination cluster, create an asynchronous SnapMirror relationship:
+
`snapmirror create -source-path _src_SVM:src_volume_ -destination-path <destination_SVM:destination_volume> -policy MirrorAllSnapshots`
+
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----

 .. Resynchronize the SnapMirror Synchronous relationship:
+
`snapmirror resync -destination-path <destination_SVM:destination_volume>`
+
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----

// 2024-7-10 ontapdoc-2192
// 07 DEC 2021, BURT 1430515
