---
permalink: data-protection/create-load-sharing-mirror-task.html
sidebar: sidebar
keywords: create, initialize, load-sharing, mirror, relationship
summary: "You should create a load-sharing mirror (LSM) for each root volume in the cluster. You can create the LSM on any node other than the one containing the root volume, such as the partner node in an HA pair, or preferably in a different HA pair. For a two-node cluster, you should create the LSM on the partner of the node with the root volume."
---
= Create and initializing load-sharing mirror relationships with ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
You should create a load-sharing mirror (LSM) for each SVM root volume that serves NAS data in the cluster. For clusters consisting of two or more HA pairs, you should consider load-sharing mirrors of SVM root volumes to ensure the namespace remains accessible to clients in the event that
both nodes of an HA pair fail. Load-sharing mirrors are not suitable for clusters consisting of a single HA pair.

.About this task

If you create an LSM on the same node, and the node is unavailable, you have a single point of failure, and you do not have a second copy to ensure the data remains accessible to clients. But when you create the LSM on a node other than the one containing the root volume, or on a different HA pair, your data is still accessible in the event of an outage.

For example, in a four-node cluster with a root volume on three nodes:

* For the root volume on HA 1 node 1, create the LSM on HA 2 node 1 or HA 2 node 2.
* For the root volume on HA 1 node 2, create the LSM on HA 2 node 1 or HA 2 node 2.
* For the root volume on HA 2 node 1, create the LSM on HA 1 node 1 or HA 1 node 2.

.Steps

. Create a destination volume for the LSM:
+
[source, cli]
----
volume create -vserver <SVM> -volume <volume> -aggregate <aggregate> -type DP -size <size>
----
+
The destination volume should be the same or greater in size than the root volume.
+
It is a best practice to name the root and destination volume with suffixes, such as `_root` and `_m1`.
+
Learn more about `volume create` in the link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html[ONTAP command reference^].
+
The following example creates a load-sharing mirror volume for the root volume `svm1_root` in `cluster_src`:
+
----
cluster_src:> volume create -vserver svm1 -volume svm1_m1 -aggregate aggr_1 -size 1gb -state online -type DP
----

. link:create-replication-job-schedule-task.html[Create a replications job schedule].
. Create a load-sharing mirror relationship between the SVM root volume and the destination volume for the LSM:
+
[source, cli]
----
snapmirror create -source-path <SVM:volume> -destination-path <SVM:volume> -type LS -schedule <schedule>
----
+
Learn more about `snapmirror create` in the link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html[ONTAP command reference^].
+
The following example creates a load-sharing mirror relationship between the root volume `svm1_root` and the load-sharing mirror volume `svm1_m1`:
+
----
cluster_src::> snapmirror create -source-path svm1:svm1_root -destination-path svm1:svm1_m1 -type LS -schedule hourly
----
+
The type attribute of the load-sharing mirror changes from `DP` to `LS`.

. Initialize the load-sharing mirror:
+
[source, cli]
----
snapmirror initialize-ls-set -source-path <SVM:volume>
----
+
Learn more about `snapmirror initialize` in the link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html[ONTAP command reference^].
+
The following example initializes the load-sharing mirror for the root volume `svm1_root`:
+
----
cluster_src::> snapmirror initialize-ls-set -source-path svm1:svm1_root
----

// 2024 Jan 14, ONTAPDOC-2569
// 2024-May-1, GitHub issue# 1336
// 2023-Nov-30, ONTAPDOC-1512
// 2023-Oct-27, issue# 1156
// 2023-Sept-20, issue# 1108
// 2023-Sept-6, issue# 993
// 2021-12-21, BURT 1446961
