---
permalink: data-protection/define-rule-policy-task.html
sidebar: sidebar
keywords: define, rule, policy
summary: "For custom policies with the “vault” or “mirror-vault” policy type, you must define at least one rule that determines which Snapshot copies are transferred during initialization and update. You can also define rules for default policies with the “vault” or “mirror-vault” policy type."
---
= Define a rule for a policy
:icons: font
:imagesdir: ../media/

[.lead]
For custom policies with the "`vault`" or "`mirror-vault`" policy type, you must define at least one rule that determines which Snapshot copies are transferred during initialization and update. You can also define rules for default policies with the "`vault`" or"`mirror-vault`" policy type.

.About this task

Every policy with the "`vault`" or "`mirror-vault`" policy type must have a rule that specifies which Snapshot copies to replicate. The rule "`bi-monthly`", for example, indicates that only Snapshot copies assigned the SnapMirror label "`bi-monthly`" should be replicated. You specify the SnapMirror label when you configure the Snapshot policy on the source.

Each policy type is associated with one or more system-defined rules. These rules are automatically assigned to a policy when you specify its policy type. The table below shows the system-defined rules.

[cols="3*"]
|===

h| System-defined rule h| Used in policy types h| Result

a|
sm_created
a|
async-mirror, mirror-vault, Sync, StrictSync
a|
A snapshot created by SnapMirror is transferred on initialization and update.
a|
all_source_snapshots
a|
async-mirror
a|
New Snapshot copies on the source are transferred on initialization and update.
a|
daily
a|
vault,mirror-vault
a|
New Snapshot copies on the source with the SnapMirror label "`daily`" are transferred on initialization and update.
a|
weekly
a|
vault,mirror-vault
a|
New Snapshot copies on the source with the SnapMirror label "`weekly`" are transferred on initialization and update.
a|
monthly
a|
mirror-vault
a|
New Snapshot copies on the source with the SnapMirror label "`monthly`" are transferred on initialization and update.
a|
app_consistent
a|
Sync, StrictSync
a|
Snapshot copies with the SnapMirror label "`app_consistent`" on source are synchronously replicated to the destination. Supported Beginning with ONTAP 9.7.

|===
Except for the "`async-mirror`" policy type, you can specify additional rules as needed, for default or custom policies. For example:

* For the default `MirrorAndVault` policy, you might create a rule called "`bi-monthly`" to match Snapshot copies on the source with the "`bi-monthly`" SnapMirror label.
* For a custom policy with the "`mirror-vault`" policy type, you might create a rule called "`bi-weekly`" to match Snapshot copies on the source with the "`bi-weekly`" SnapMirror label.

.Step

. Define a rule for a policy:
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -keep _retention_count_`
+
For complete command syntax, see the man page.
+
The following example adds a rule with the SnapMirror label `bi-monthly` to the default `MirrorAndVault` policy:
+
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label bi-monthly -keep 6
----
+
The following example adds a rule with the SnapMirror label `bi-weekly` to the custom `my_snapvault` policy:
+
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_snapvault -snapmirror-label bi-weekly -keep 26
----
+
The following example adds a rule with the SnapMirror label `app_consistent` to the custom `Sync` policy:
+
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy Sync -snapmirror-label app_consistent -keep 1
----
+
You can then replicate Snapshot copies from the source cluster that match this SnapMirror label:
+
----
cluster_src::> snapshot create -vserver vs1 -volume vol1 -snapshot snapshot1 -snapmirror-label app_consistent
----
