---
permalink: data-protection/define-schedule-create-local-copy-destination-task.html
sidebar: sidebar
keywords: define, schedule, create, local copy, destination
summary: "For SnapVault and unified replication relationships, you can protect against the possibility that an updated snapshot is corrupted by creating a copy of the last transferred snapshot on the destination. This “local copy” is retained regardless of the retention rules on the source, so that even if the Snapshot originally transferred by SnapMirror is no longer available on the source, a copy of it will be available on the destination."
---
= Define a schedule for creating a local copy on the destination
:icons: font
:imagesdir: ../media/

[.lead]
For SnapVault and unified replication relationships, you can protect against the possibility that an updated snapshot is corrupted by creating a copy of the last transferred snapshot on the destination. This "`local copy`" is retained regardless of the retention rules on the source, so that even if the snapshot originally transferred by SnapMirror is no longer available on the source, a copy of it will be available on the destination.

.About this task

You specify the schedule for creating a local copy in the `-schedule` option of the `snapmirror policy add-rule` command.

.Step

. Define a schedule for creating a local copy on the destination:
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -schedule _schedule_`
+
For complete command syntax, see the man page. For an example of how to create a job schedule, see link:create-replication-job-schedule-task.html[Creating a replication job schedule].
+
The following example adds a schedule for creating a local copy to the default `MirrorAndVault` policy:
+
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label my_monthly -schedule my_monthly
----
+
The following example adds a schedule for creating a local copy to the custom `my_unified` policy:
+
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_unified -snapmirror-label my_monthly -schedule my_monthly
----
