---
permalink: data-protection/delete-volume-replication-relationship-task.html
sidebar: sidebar
keywords: delete, volume, replication, relationship, replicate, synchronous, snapmirror, quiese, pause
summary: "You can use the snapmirror delete and snapmirror release commands to delete a volume replication relationship. You can then delete unneeded destination volumes manually."
---
= Delete a volume replication relationship with ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `snapmirror delete` and `snapmirror release` commands to delete a volume replication relationship. You can then delete unneeded destination volumes manually.

.About this task

The `snapmirror release` command deletes any SnapMirror-created snapshots from the source. You can use the `-relationship-info-only` option to preserve the snapshots.

.Steps

. Quiesce the replication relationship:
+
`snapmirror quiesce -destination-path <SVM:volume>|<cluster://SVM/volume>`
+
----
cluster_dst::> snapmirror quiesce -destination-path svm_backup:volA_dst
----

. (Optional) Break the replication relationship if you require the destination volume to be a read/write volume. You can skip this step if you plan to delete the destination volume or if you don't need the volume to be read/write:
+
`snapmirror break -source-path <SVM:volume>|<cluster://SVM/volume>, …​ -destination-path <SVM:volume>|<cluster://SVM/volume>, …​`
+
----
cluster_dst::> snapmirror break -source-path svm1:volA -destination-path svm_backup:volA_dst
----

. Delete the replication relationship:
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`
+
Learn more about `snapmirror delete` in the link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html[ONTAP command reference^].
+
[NOTE]
====
You must run this command from the destination cluster or destination SVM.
====
+
The following example deletes the relationship between the source volume `volA` on `svm1` and the destination volume `volA_dst` on `svm_backup`:
+
----
cluster_dst::> snapmirror delete -source-path svm1:volA -destination-path svm_backup:volA_dst
----

. Release replication relationship information from the source SVM:
+
`snapmirror release -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`
+
Learn more about `snapmirror release` in the link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html[ONTAP command reference^].
+
[NOTE]
====
You must run this command from the source cluster or source SVM.
====
+
The following example releases information for the specified replication relationship from the source SVM `svm1`:
+
----
cluster_src::> snapmirror release -source-path svm1:volA -destination-path svm_backup:volA_dst
----

// 2025 Jan 14, ONTAPDOC-2569
// 2024-7-10 ontapdoc-2192
// 2023-Mar-6, issue# 835
// 08 DEC 2021, BURT 1430515
// 2022-1-11, issue 263
// 2022-2-28, BURT 1460185
// 2022-3-1, add an example to step 2
