---
permalink: data-protection/install-snapmirror-cloud-license-task.html
sidebar: sidebar
keywords: install, snapmirror, cloud, license, asynchronous, replicate, replication, snapshot
summary: "Beginning with ONTAP 9.8, SnapMirror Cloud provides asynchronous Snapshot copy replication from ONTAP to object storage endpoints. SnapMirror Cloud relationships can only be configured using pre-qualified third-party backup applications. To configure ONTAP to object storage replication, both SnapMirror and SnapMirror Cloud licenses are required on the ONTAP source cluster configured for replication to the object store endpoint."
---
= Install a SnapMirror Cloud license
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.8, SnapMirror Cloud provides asynchronous snapshot replication from ONTAP to object storage endpoints. SnapMirror Cloud relationships can only be configured using pre-qualified third-party backup applications. To configure ONTAP to object storage replication, both SnapMirror and SnapMirror Cloud licenses are required on the ONTAP source cluster configured for replication to the object store endpoint.

.About this task

The SnapMirror Cloud license is a single-instance cluster-wide license, which means it does not need to be installed on every node in the cluster. In addition to this end user license, SnapMirror Cloud requires an authorized and approved backup application to configure and invoke ONTAP APIs for replication. Both SnapMirror Cloud end user license and an authorized app are necessary to utilize SnapMirror Cloud replication.

Clusters that have the ONTAP One software suite are entitled to the SnapMirror Cloud license; however, because the license is a cluster-wide license, not node-based like other feature licenses, it must be acquired separately. It's available at no cost, along with the S3 API license key, in the ONTAP One compatibility bundle. You need to provide the cluster UUID on the NetApp Support site to generate the SnapMirror Cloud license and the S3 API license keys. 

You can use System Manager or the ONTAP command line to install a SnapMirror Cloud license on the cluster.

.Steps

. Request and download two NetApp License Files (NLFs) for SnapMirror Cloud from the NetApp Support Site.
+
https://mysupport.netapp.com/site/global/dashboard[NetApp Support]

. Use System Manager to upload the SnapMirror Cloud NLF file to the cluster:
 .. Click *Configuration* > *Licenses*.
 .. In the *Cluster Settings* pane, click *Licenses*.
 .. In the *Packages* window, click *Add*.
 .. In the *Add License Packages* dialog box, click *Choose Files* to select the NLF you downloaded, and then click *Add* to upload the file to the cluster.

.Related information

http://mysupport.netapp.com/licenses[NetApp Software License Search]

// 2024-Jan-5, ONTAPDOC-1366
// 08 DEC 2021, BURT 1430515
// 2022-4-6, remove FabricPool instances 
