---
permalink: data-protection/long-term-retention-snapshots-concept.html
sidebar: sidebar
keywords: local, snapshot, retention, snapmirror, vault
summary: "You can create long-term retention snapshots directly on the secondary volume of a SnapMirror relationship using either the vault or mirror-vault policy type. These snapshots are retained on the destination as backups."
---
= Learn about ONTAP long-term retention snapshots
:icons: font
:imagesdir: ../media/

[.lead]
//IE UPDATE WARNING: SEE ONTAPDOC-3355 BEFORE CHANGING CONTENT.
SnapMirror relationships with a policy type of either "vault" or "mirror-vault" allow snapshot creation directly on the secondary volume of the SnapMirror relationship. These snapshots are retained on the destination as backups. These snapshots are often created for long-term retention and are called long-term retention snapshots. 

You create a long-term retention snapshot by specifying a snapshot creation schedule in the SnapMirror policy rule, the snapshot name prefix, SnapMirror label, and the retention count. This snapshot is retained on the SnapMirror destination volume regardless of the retention rules on the source. 

Long-term retention snapshots are available for FlexVol SnapMirror configurations only. You cannot create long-term retention snapshots for FlexGroup SnapMirror configurations. 

In a SnapMirror cascade relationship, long-term retention snapshots can only be created on the last volume of the cascade. 

== Related information

* link:supported-deployment-config-concept.html#how-cascade-deployments-work[Learn about how cascade deployments work]

* link:define-schedule-create-local-copy-destination-task.html[Define an ONTAP SnapMirror schedule to create a local copy on the destination]

// 2026-Jan-12, ONTAPDOC-3592
// 2025-Oct-8, pr-2760
// 2025-Oct-6, ONTAPDOC-3355