---
permalink: data-protection/manage-snapmirror-root-volume-replication-concept.html
sidebar: sidebar
keywords: manage, snapmirror, root volume , replication
summary: "Every SVM in a NAS environment has a unique namespace. The SVM root volume, containing operating system and related information, is the entry point to the namespace hierarchy. To ensure that data remains accessible to clients in the event of a node outage or failover, you should create a load-sharing mirror copy of the SVM root volume."
---
= Learn about ONTAP SnapMirror root volume replication
:icons: font
:imagesdir: ../media/

[.lead]
Every SVM in a NAS environment has a unique namespace. The SVM _root volume,_ containing operating system and related information, is the entry point to the namespace hierarchy. To ensure that data remains accessible to clients in the event of a node outage or failover, you should create a load-sharing mirror copy of the SVM root volume.

Beginning with ONTAP 9.1, load-sharing mirror relationships on FlexVol data volumes are no longer supported. The main purpose of load-sharing mirrors has changed for SVM root volumes and is no longer for load sharing; instead, their purpose is for disaster recovery.

* If the root volume is temporarily unavailable, the load-sharing mirror automatically provides read-only access to root volume data.
* If the root volume is permanently unavailable, you can promote one of the load-sharing volumes to provide write access to root volume data.

link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/What_are_the_dsadvantages_of_Load-sharing_Mirrors[Learn more about why load-sharing mirrors are no longer used for load-sharing].

// 2025-Mar-16, GitHub issue #1975
// 2025-Apr-21, ONTAPDOC-2803