---
permalink: data-protection/manage-local-snapshot-copies-concept.html
sidebar: sidebar
keywords: manage, local, snapshot, copy, storage, performance overhead, copies, image, restore, flexvol, flexgroup
summary: "A snapshot is a read-only, point-in-time image of a volume. The image consumes minimal storage space and incurs negligible performance overhead because it records only changes to files since the last snapshot."
---
= Learn about managing local ONTAP snapshots 
:icons: font
:imagesdir: ../media/

[.lead]
A _snapshot_ is a read-only, point-in-time image of a volume. The image consumes minimal storage space and incurs negligible performance overhead because it records only changes to files since the last snapshot.

You can use a snapshot to restore the entire contents of a volume, or to recover individual files or LUNs. snapshots are stored in the directory `.snapshot` on the volume.

In ONTAP 9.4 and later, a FlexVol volume can contain up to 1023 snapshots.
In ONTAP 9.3 and earlier, a volume can contain up to 255 snapshots. 

[NOTE]
====
Beginning with ONTAP 9.8, FlexGroup volumes can contain 1023 snapshots. For more information, see link:../flexgroup/protect-snapshot-copies-task.html[Protect FlexGroup volumes using snapshots].
====

There are several common ONTAP snapshot types:

`sched_created`: Snapshots generated automatically by an ONTAP snapshot policy, based on predefined schedules (for example, hourly, daily, weekly, or monthly).

`sm_created`: Snapshots created automatically as a result of SnapMirror replication transfers (either update or initialize operations).

`application_created`: Snapshots generated by host-level or database-level integration software like SnapCenter or SnapDrive.

`user_created`: Snapshots triggered manually by an administrator using either the ONTAP CLI or System Manager.

`sv_created`: Snapshots created automatically during cluster operations, such as Storage Virtual Machine (SVM) DR or specific protection workflows.

`luns_created`: Snapshots created to back up or capture the state of LUN or NVMe namespace clones.

// 2026-May-27, GitHub issue #2038
// 2025 July 30, ONTAPDOC-1127
// 2025-May-8, ONTAPDOC-2803
// 08 DEC 2021, BURT 1430515
// 2022-2-8, fix link
