---
permalink: data-protection/reactivate-original-source-volume-task.html
sidebar: sidebar
keywords: reactivate, original, source, volume
summary: "You can reestablish the original data protection relationship between the source and destination volumes when you no longer need to serve data from the destination."
---
= Reactivate the original source volume
:icons: font
:imagesdir: ../media/

[.lead]
You can reestablish the original data protection relationship between the source and destination volumes when you no longer need to serve data from the destination.

.About this task

* The procedure below assumes that the baseline in the original source volume is intact. If the baseline is not intact, you must create and initialize the relationship between the volume you are serving data from and the original source volume before performing the procedure.
* Background preparation and the data warehousing phase of an XDP SnapMirror relationship can take a long time. It is not uncommon to see the SnapMirror relationship reporting the status "preparing" for an extended time period.

.Steps

. Delete the original data protection relationship:
+
`snapmirror delete -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`
+
For complete command syntax, see the man page.
+
You must run this command from the destination SVM or the destination cluster.
+
The following example deletes the relationship between the original source volume, `volA` on `svm1`, and the volume you are serving data from, `volA_dst` on `svm_backup`:
+
----
cluster_dst::> snapmirror delete -source-path svm1:volA -destination-path svm_backup:volA_dst
----

. Reverse the original data protection relationship:
+
`snapmirror resync -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`
+
For complete command syntax, see the man page.
+
[NOTE]
====
You must run this command from the original source SVM or the original source cluster. Although resync does not require a baseline transfer, it can be time-consuming. You might want to run the resync in off-peak hours. The command fails if a common Snapshot copy does not exist on the source and destination. Use `snapmirror initialize` to re-initialize the relationship.
====
+
The following example reverses the relationship between the original source volume, `volA` on `svm1`, and the volume you are serving data from, `volA_dst` on `svm_backup`:
+
----
cluster_src::> snapmirror resync -source-path svm_backup:volA_dst -destination-path svm1:volA
----

. When you are ready to reestablish data access to the original source, stop access to the original destination volume. One way to do this is to stop the original destination SVM:
+
`vserver stop -vserver _SVM_`
+
For complete command syntax, see the man page.
+
[NOTE]
====
You must run this command from the original destination SVM or the original destination cluster. This command stops user access to the entire original destination SVM. You may want to stop access to the original destination volume using other methods.
====
+
The following example stops the original destination SVM:
+
----
cluster_dst::> vserver stop svm_backup
----

. Update the reversed relationship:
+
`snapmirror update -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`
+
For complete command syntax, see the man page.
+
[NOTE]
====
You must run this command from the original source SVM or the original source cluster.
====
+
The following example updates the relationship between the volume you are serving data from, `volA_dst` on `svm_backup`, and the original source volume, `volA` on `svm1`:
+
----
cluster_src::> snapmirror update -source-path svm_backup:volA_dst -destination-path svm1:volA
----

. From the original source SVM or the original source cluster, stop scheduled transfers for the reversed relationship:
+
`snapmirror quiesce -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`
+
For complete command syntax, see the man page.
+
[NOTE]
====
You must run this command from the original source SVM or the original source cluster.
====
+
The following example stops scheduled transfers between the original destination volume, `volA_dst` on `svm_backup`, and the original source volume, `volA` on `svm1`:
+
----
cluster_src::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path svm1:volA
----

. When the final update is complete and the relationship indicates "Quiesced" for the relationship status, run the following command from the original source SVM or the original source cluster to break the reversed relationship::
+
`snapmirror break -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`
+
For complete command syntax, see the man page.
+
[NOTE]
====
You must run this command from the original source SVM or the source cluster.
====
+
The following example breaks the relationship between the original destination volume, `volA_dst` on `svm_backup`, and the original source volume, `volA` on `svm1`:
+
----
cluster_scr::> snapmirror break -source-path svm_backup:volA_dst -destination-path svm1:volA
----

. From the original source SVM or the original source cluster, delete the reversed data protection relationship:
+
`snapmirror delete -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`
+
For complete command syntax, see the man page.
+
[NOTE]
====
You must run this command from the original source SVM or the original source cluster.
====
+
The following example deletes the reversed relationship between the original source volume, `volA` on `svm1`, and the volume you are serving data from, `volA_dst` on `svm_backup`:
+
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path svm1:volA
----

. Release the reversed relationship from the original destination SVM or the original destination cluster.
+
`snapmirror release -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`
+
[NOTE]
====
You must run this command from the original destination SVM or the original destination cluster.
====
+
The following example releases the reversed relationship between the original destination volume, `volA_dst` on `svm_backup`, and the original source volume, `volA` on `svm1`:
----
cluster_dst::> snapmirror release -source-path svm_backup:volA_dst -destination-path svm1:volA
----

. If needed, start the original destination SVM:
+
`vserver start -vserver _SVM_`
+
For complete command syntax, see the man page.
+
The following example starts the original destination SVM:
+
----
cluster_dst::> vserver start svm_backup
----

. Reestablish the original data protection relationship from the original destination:
+
`snapmirror resync -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`
+
For complete command syntax, see the man page.
+
The following example reestablishes the relationship between the original source volume, `volA` on `svm1`, and the original destination volume, `volA_dst` on `svm_backup`:
+
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----

.After you finish

Use the `snapmirror show` command to verify that the SnapMirror relationship was created. For complete command syntax, see the man page.

// 2023-Jan-10, issue# 737
// 2022-2-2, BURT 1364426
