---
permalink: data-protection/restore-svm-root-volume-promote-mirror-task.html
sidebar: sidebar
keywords: promote, load-sharing, mirror
summary: "If a root volume is permanently unavailable, you can promote the load-sharing mirror (LSM) volume to provide write access to root volume data."
---
= Promote a load-sharing mirror with ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
If a root volume is permanently unavailable, you can promote the load-sharing mirror (LSM) volume to provide write access to root volume data.

.What you'll need

You must use advanced privilege level commands for this task.

.Steps

. Change to advanced privilege level:
+
[source, cli]
----
set -privilege advanced
----
. Promote an LSM volume:
+
You must replace the variables in angle brackets with the required values before running this command.
+
[source, cli]
----
snapmirror promote -destination-path <SVM:volume>
----
+
Learn more about `snapmirror promote` in the link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-promote.html[ONTAP command reference^].
+
The following example promotes the volume `svm1_m2` as the new SVM root volume:
+
----
cluster_src::*> snapmirror promote -destination-path svm1:svm1_m2

Warning: Promote will delete the offline read-write volume
         cluster_src://svm1/svm1_root and replace it with
         cluster_src://svm1/svm1_m2. Because the volume is offline,
         it is not possible to determine whether this promote will
         affect other relationships associated with this source.
Do you want to continue? {y|n}: y
----
+
Enter `y`. ONTAP makes the LSM volume a read/write volume, and deletes the original root volume if it is accessible.
+
[NOTE]
====
The promoted root volume might not have all of the data that was in the original root volume if the last update did not occur recently.
====

. Return to admin privilege level:
+
[source, cli]
----
set -privilege admin
----

. Rename the promoted volume following the naming convention you used for the root volume:
+
You must replace the variables in angle brackets with the required values before running this command.
+
[source, cli]
----
volume rename -vserver <SVM> -volume <volume> -newname <new_name>
----
+
The following example renames the promoted volume `svm1_m2` with the name `svm1_root`:
+
----
cluster_src::> volume rename -vserver svm11 -volume svm1_m2 -newname svm1_root
----

. Protect the renamed root volume, as described in step 3 through step 4 in link:create-load-sharing-mirror-task.html[Creating and initializing load-sharing mirror relationships].

// 2025 Jan 14, ONTAPDOC-2569
// 2023-Sept-21, issue# 1108