---
permalink: data-protection/resynchronize-relationship-task.html
sidebar: sidebar
keywords: resynchronize, replication, relationship
summary: "You need to resynchronize a replication relationship after you make a destination volume writeable, after an update fails because a common Snapshot copy does not exist on the source and destination volumes, or if you want to change the replication policy for the relationship."
---
= Resynchronize a replication relationship
:icons: font
:imagesdir: ../media/

[.lead]
You need to resynchronize a replication relationship after you make a destination volume writeable, after an update fails because a common Snapshot copy does not exist on the source and destination volumes, or if you want to change the replication policy for the relationship.

.About this task

* Although resync does not require a baseline transfer, it can be time-consuming. You might want to run the resync in off-peak hours.
* Volumes that are part of a fan-out or cascade configuration can take longer to resynchronize. It is not uncommon to see the SnapMirror relationship reporting the status "preparing" for an extended time period.

.Step

. Resync the source and destination volumes:
+
`snapmirror resync -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -type DP|XDP -policy _policy_`
+
For complete command syntax, see the man page.
+
[NOTE]
====
You must run this command from the destination SVM or the destination cluster.
====
+
The following example resyncs the relationship between the source volume `volA` on `svm1` and the destination volume `volA_dst` on `svm_backup`:
+
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----

// 2024-7-10 ontapdoc-2192
// 2024-April-10, ONTAPDOC-1873
// 2022-2-2, BURT 1364426
