---
permalink: data-protection/snapmirror-licensing-concept.html
sidebar: sidebar
keywords: snapmirror, licensing, snapvault, vault, mirror, relationship, replication, backup, back up, disaster recovery, dr
summary: "Beginning with ONTAP 9.3, licensing has been simplified for replicating between ONTAP instances. In ONTAP 9 releases, the SnapMirror license supports both vault and mirror relationships. Users can now purchase a SnapMirror license to support ONTAP replication for both backup and disaster recovery use cases."
---
= SnapMirror licensing overview
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.3, licensing has been simplified for replicating between ONTAP instances. In ONTAP 9 releases, the SnapMirror license supports both vault and mirror relationships. You can use a SnapMirror license to support ONTAP replication for both backup and disaster recovery use cases.

Prior to the ONTAP 9.3 release, a separate SnapVault license was needed to configure _vault_ relationships between ONTAP instances, where the DP instance could retain a higher number of Snapshot copies to support backup use cases with longer retention times, and a SnapMirror license was needed to configure _mirror_ relationships between ONTAP instances, where each ONTAP instance would maintain the same number of Snapshot copies (that is, a _mirror_ image) to support disaster recovery use cases to make cluster failovers possible. Both SnapMirror and SnapVault licenses continue to be used and supported for ONTAP 8.x and 9.x releases.

While SnapVault licenses continue to function and are supported for both ONTAP 8.x and 9.x releases, the SnapMirror license can be used in place of a SnapVault license and can be used for both mirror and vault configurations.

For ONTAP asynchronous replication, beginning with ONTAP 9.3 a single unified replication engine is used to configure extended data protection mode (XDP) policies, where the SnapMirror license can be configured for a mirror policy, a vault policy, or a mirror-vault policy. A SnapMirror license is required on both the source and destination clusters. A SnapVault license is not required if a SnapMirror license is already installed. The SnapMirror asynchronous perpetual license is included in the ONTAP One software suite that's installed on new AFF and FAS systems. 

Data protection configuration limits are determined using several factors, including your ONTAP version, hardware platform, and the licenses installed. For more information, see https://hwu.netapp.com/[Hardware Universe^].

== SnapMirror Synchronous license

Beginning with ONTAP 9.5, SnapMirror Synchronous relationships are supported. You require the following licenses for creating a SnapMirror Synchronous relationship:

* The SnapMirror Synchronous license is required on both the source cluster and the destination cluster.
+
The SnapMirror Synchronous license is part of the ONTAP One license suite.
+
If your system was purchased before June 2019 with a Premium or Flash Bundle, you can download a NetApp master key to get the required SnapMirror Synchronous license from the NetApp Support Site: https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/[Master License Keys].

* The SnapMirror license is required on both the source cluster and the destination cluster.

== SnapMirror Cloud license

Beginning with ONTAP 9.8, the SnapMirror Cloud license provides asynchronous replication of Snapshot copies from ONTAP instances to object storage endpoints. Replication targets can be configured using both on-premises object stores as well as S3 and S3-compatible public cloud object storage services. SnapMirror Cloud relationships are supported from ONTAP systems to pre-qualified object storage targets. 

SnapMirror Cloud is not available as a standalone license. Only one license is needed per ONTAP cluster. Capacity is defined as the “used” capacity (not raw capacity) within any volume which is protected by SnapMirror Cloud. In addition to a SnapMirror Cloud license, the asynchronous SnapMirror license is also required.

You require the following licenses for creating a SnapMirror Cloud relationship:

* Both a SnapMirror license and a SnapMirror Cloud API license for replicating directly to the object store endpoint.
* When configuring a multi-policy replication workflow (for example, Disk-to-Disk-to-Cloud), a SnapMirror license is required on all ONTAP instances, while the SnapMirror Cloud license is only required for the source cluster which is replicating directly to the object storage endpoint.

Beginning with ONTAP 9.9.1, you can https://docs.netapp.com/us-en/ontap/task_dp_back_up_to_cloud.html[use System Manager for SnapMirror Cloud replication].

A list of authorized SnapMirror Cloud third-party applications is published on the NetApp web site.

== Data Protection Optimized (DPO) license

Beginning with ONTAP 9.1, the DP_Optimized (DPO) license was introduced to support unique ONTAP features for secondary workloads.

The DPO license was specifically designed for ONTAP clusters being dedicated as secondary targets for SnapMirror replication. In addition to increasing the maximum volumes per node on the DPO controller, the DPO license also modifies controller QoS settings to support greater replication traffic at the expense of application I/O. For this reason, the DPO license should never be installed on a cluster that supports application I/O, as application performance will be impacted. 

Beginning with ONTAP 9.5, a standalone DPO license was introduced. The standalone DPO license is supported on both FAS and AFF platforms. Secondary clusters configured with the a la carte DPO license must also purchase a SnapMirror license, and all primary clusters replicating to the DPO secondary cluster must purchase a SnapMirror license.

For the latest maximum FlexVol volume support for your configuration, see https://hwu.netapp.com/[Hardware Universe^].

== Considerations for all new DPO installations

* After it is enabled, the DPO license feature cannot be disabled or undone.
* Installation of the DPO license requires a reboot of ONTAP or failover to enable it.
* The DPO solution is intended for secondary storage workloads; application workload performance on DPO clusters may be impacted.
* The DPO license is supported only on select NetApp storage platform models.
* DPO features vary by ONTAP release. For details, refer to https://hwu.netapp.com/[Hardware Universe^].

// 2023-12-19, ONTAPDOC-1366
// 2022-8-31, add missing text
// 08 DEC 2021, BURT 1430515
// 2022-9-1, issue #644