---
permalink: data-protection/snapmirror-unified-replication-concept.html
sidebar: sidebar
keywords: snapmirror, unified, replication
summary: "SnapMirror unified replication allows you to configure disaster recovery and archiving on the same destination volume. When unified replication is appropriate, it offers benefits in reducing the amount of secondary storage you need, limiting the number of baseline transfers, and decreasing network traffic."
---
= SnapMirror unified replication basics
:icons: font
:imagesdir: ../media/

[.lead]
SnapMirror _unified replication_ allows you to configure disaster recovery and archiving on the same destination volume. When unified replication is appropriate, it offers benefits in reducing the amount of secondary storage you need, limiting the number of baseline transfers, and decreasing network traffic.

== How unified data protection relationships are initialized

As with SnapMirror, unified data protection performs a baseline transfer the first time you invoke it. The SnapMirror policy for the relationship defines the contents of the baseline and any updates.

A baseline transfer under the default unified data protection policy `MirrorAndVault` makes a snapshot of the source volume, then transfers that copy and the data blocks it references to the destination volume. Like vault archiving, unified data protection does not include older snapshots in the baseline.

== How unified data protection relationships are updated

At each update under the `MirrorAndVault` policy, SnapMirror creates a snapshot of the source volume and transfers that snapshot and any snapshots that have been made since the last update, provided they have labels matching the labels defined in the snapshot policy rules. In the following output from the `snapmirror policy show` command for the `MirrorAndVault` policy, note the following:

* `Create Snapshot` is "`true`", indicating that `MirrorAndVault` creates a snapshot when SnapMirror updates the relationship.
* `MirrorAndVault` has rules "`sm_created`", "`daily`", and "`weekly`", indicating that both the snapshot created by SnapMirror and the snapshots with matching labels on the source are transferred when SnapMirror updates the relationship.

----
cluster_dst::> snapmirror policy show -policy MirrorAndVault -instance

                     Vserver: vs0
      SnapMirror Policy Name: MirrorAndVault
      SnapMirror Policy Type: mirror-vault
                Policy Owner: cluster-admin
                 Tries Limit: 8
           Transfer Priority: normal
   Ignore accesstime Enabled: false
     Transfer Restartability: always
 Network Compression Enabled: false
             Create Snapshot: true
                     Comment: A unified SnapMirror synchronous and SnapVault policy for
                              mirroring the latest file system and daily and weekly snapshots.
       Total Number of Rules: 3
                  Total Keep: 59
                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
----

== Unified7year policy

The preconfigured `Unified7year` policy works exactly the same way as `MirrorAndVault`, except that a fourth rule transfers monthly snapshots and retains them for seven years.

----

                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
                              monthly                84  false       0 -        -
----

== Protect against possible data corruption

Unified replication limits the contents of the baseline transfer to the snapshot created by SnapMirror at initialization. At each update, SnapMirror creates another snapshot of the source and transfers that snapshot and any new snapshots that have labels matching the labels defined in the snapshot policy rules.

You can protect against the possibility that an updated snapshot is corrupted by creating a copy of the last transferred snapshot on the destination. This "`local copy`" is retained regardless of the retention rules on the source, so that even if the snapshot originally transferred by SnapMirror is no longer available on the source, a copy of it will be available on the destination.

== When to use unified data replication

You need to weigh the benefit of maintaining a full mirror against the advantages that unified replication offers in reducing the amount of secondary storage, limiting the number of baseline transfers, and decreasing network traffic.

The key factor in determining the appropriateness of unified replication is the rate of change of the active file system. A traditional mirror might be better suited to a volume holding hourly snapshots of database transaction logs, for example.

// 2024-Aug-30, ONTAPDOC-2346