---
permalink: data-protection/update-load-sharing-mirror-set-task.html
sidebar: sidebar
keywords: update, loaad-sharing, mirror, relationship, LSM, manual update
summary: "Load-sharing mirror (LSM) relationships are updated automatically for SVM root volumes after a volume in the SVM is mounted or unmounted, and during `volume create` operations that include the `junction-path`option. You can manually update a LSM relationship if you want it updated before the next scheduled update."
---
= Update a load-sharing mirror relationship
:icons: font
:imagesdir: ../media/

[.lead]
Load-sharing mirror (LSM) relationships are updated automatically for SVM root volumes after a volume in the SVM is mounted or unmounted, and during `volume create` operations that include the `junction-path` option. You can manually update a LSM relationship if you want it updated before the next scheduled update.

Load-sharing mirror relationships update automatically in the following circumstances:

* It's time for a scheduled update
* A mount or unmount operation is performed on a volume in the SVM root volume
* A `volume create` command is issued that includes the `juntion-path` option

.Step

. Update a load-sharing mirror relationship manually:
+
You must replace the variables in angle brackets with the required values before running this command.
+
[source, cli]
----
snapmirror update-ls-set -source-path <SVM:volume>
----
+
The following example updates the load-sharing mirror relationship for the root volume `svm1_root`:
+
----
cluster_src::> snapmirror update-ls-set -source-path svm1:svm1_root
----

.Related Information
Learn more about `volume create` in the link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html[ONTAP command reference^].

// 2025 Feb 26, ONTAPDOC-2758
// 2023-Sept-21, issue# 1108
// 2022-4-20, issue #461 
