---
permalink: data-protection/workloads-strictsync-sync-policies-concept.html
sidebar: sidebar
keywords: understand, workloads, support, strictsync, policy, strict sync, policies, snapmirror, snap mirror, cifs, vmware, eda, synchronous, fc, iscsi, nvme, nfsv3, nfsv4
summary: "StrictSync and Sync policies support all LUN-based applications with FC, iSCSI, and FC-NVMe protocols, as well as NFSv3 and NFSv4 protocols for enterprise applications such as databases, VMWare, quota, SMB, and so on. Beginning with ONTAP 9.6, SnapMirror synchronous can be used for enterprise file services such as electronic design automation (EDA), home directories, and software build workloads."
---
= About workloads supported by StrictSync and Sync policies
:icons: font
:imagesdir: ../media/

[.lead]
StrictSync and Sync policies support all LUN-based applications with FC, iSCSI, and FC-NVMe protocols, as well as NFSv3 and NFSv4 protocols for enterprise applications such as databases, VMWare, quota, SMB, and so on. Beginning with ONTAP 9.6, SnapMirror synchronous can be used for enterprise file services such as electronic design automation (EDA), home directories, and software build workloads.

In ONTAP 9.5, for a Sync policy, you need to consider a few important aspects while selecting the NFSv3 or NFSv4 workloads. The amount of data read or write operations by workloads is not a consideration, as Sync policy can handle high read or write IO workloads. In ONTAP 9.5, workloads that have excessive file creation, directory creation, file permission changes, or directory permission changes may not be suitable (these are referred to as high-metadata workloads). A typical example of a high-metadata workload is a DevOps workload in which you create multiple test files, run automation, and delete the files. Another example is parallel build workload that generate multiple temporary files during compilation. The impact of a high rate of write metadata activity is that it can cause synchronization between mirrors to temporarily break which stalls the read and write IOs from the client.

Beginning with ONTAP 9.6, these limitations are removed and SnapMirror synchronous can be used for enterprise file services workloads that include multiuser environments, such as home directories and software build workloads.

.Related information

http://www.netapp.com/us/media/tr-4733.pdf[SnapMirror synchronous Configuration and Best Practices^]

// 2024-Aug-30, ONTAPDOC-2346
// 08 DEC 2021, BURT 1430515
// 4 FEB 2022, BURT 1451789
