---
permalink: release-notes/whats-new-9181.html
sidebar: sidebar
keywords: what's new, release notes, 9.18.1
summary: "Learn about the new capabilities available in ONTAP 9.18.1."
---
= What's new in ONTAP 9.18.1
:icons: font
:imagesdir: ../media/

[.lead]
Learn about the new capabilities available in ONTAP 9.17.1.

For details about known issues, limitations, and upgrade cautions in recent ONTAP 9 releases, refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP 9 Release Notes^]. You must sign in with your NetApp account or create an account to access the Release Notes.

* Learn about new and enhanced https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html[ONTAP MetroCluster features^].

* Learn about https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9171.html[new and enhanced ONTAP software features for NetApp AFX storage systems^].

* Learn about https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html[new and enhanced ONTAP software features for NetApp ASA r2 storage systems^].

* Learn about https://docs.netapp.com/us-en/ontap-systems/whats-new.html[new and enhanced support for AFF, ASA, and FAS systems and supported switches^].

* Learn about updates to the https://docs.netapp.com/us-en/ontap-automation/whats_new.html[ONTAP REST API^]. 

To upgrade to the latest version of ONTAP, see link:../upgrade/create-upgrade-plan.html[Prepare to upgrade ONTAP].


== Networking

[cols="30%,70%",options="header"]
|===
| Update | Description 
a| 
xref:../networking/ipsec-prepare.html[IPsec hardware offload IPv6 support] 
a| 
IPsec hardware offload support is extended to IPv6. 
a|
xref:../networking/configure_network_security_using_federal_information_processing_standards_fips.html[OpenSSL PQC algorithms] 
a| 
ONTAP supports postquantum computing cryptographic algorithms for SSL. These algorithms provide additional protection against potential future quantum computing attacks, and are available when SSL FIPS mode is disabled. 
a|
xref:../networking/configure-backend-encryption.html[ONTAP backend cluster network encryption] 
a| 
You can enable TLS encryption for data-in-flight on the ONTAP backend cluster network. 
a|
xref:../high-availability/ha-pair-encryption.html[ONTAP HA traffic network encryption] 
a| 
You can enable encryption for traffic between nodes in high-availability (HA) pairs.  
|===

== SAN 

[cols="30%,70%",options="header"]
|===
| Update | Description 
a|
xref:../san-admin/nvme-copy-offload.html[NVMe copy offload]
a|
NVMe copy offload enables an NVMe host to offload copy operations from its CPU to the CPU of the ONTAP storage controller. The host can copy data from one NVMe namespace to another while reserving its CPU resources for application workloads. 

|===

== S3 object storage 

[cols="30%,70%",options="header"]
|===
| Update | Description
a|
xref:../s3-snapshots/list-restore-s3-snapshot.html[Support for point-in-time S3 snapshot restore]
a|
Provides the ability to restore corrupted objects in an S3 bucket, or restore the entire bucket over an existing bucket. 


//ONTAPDOC-3162

|===

== Security  

[cols="30%,70%",options="header"]
|===
| Update | Description 
a|
xref:../anti-ransomware/use-cases-restrictions-concept.html#supported-configurations[FlexGroup volume support for ARP/AI]
a|
NetApp FlexGroup volumes support ARP/AI, providing advanced, machine-learning-based ransomware detection and protection. In ONTAP 9.17.1 and earlier, only the first generation of ARP was available for FlexGroup volumes. Beginning with ONTAP 9.18.1, FlexGroup volumes have parity with FlexVol volumes on both on-premises ONTAP platforms (AFF and FAS) and virtual ONTAP deployments (including Cloud Volumes ONTAP and ONTAP Select). As a result, ARP/AI becomes the default ARP technology for both FlexVol and FlexGroup volumes. 

//ONTAPDOC-3377
|===

== Storage resource management enhancements  

[cols="30%,70%",options="header"]
|===
| Update | Description 
a|
xref:../performance-admin/adaptive-qos-policy-groups-task.html[Support for two-level nested QoS policy groups on SVMs and volumes]
a|
You can assign a QoS policy to an SVM and to volumes under the SVM at the same time. 

//ONTAPDOC-3272
a| 
xref:../flexcache/create-volume-task.html[Create SVM FlexCache volumes of origin volumes in an SVM-DR relationship] 
a|
You can create SVM FlexCache volumes of origin volumes that are part of an SVM-DR relationship. 

//ONTAPDOC-3349
|===


//2025 Nov - 9.18.1 RC