---
permalink: release-notes/whats-new-9181.html
sidebar: sidebar
keywords: what's new, release notes, 9.18.1
summary: "Learn about the new capabilities available in ONTAP 9.18.1."
---
= What's new in ONTAP 9.18.1
:icons: font
:imagesdir: ../media/

[.lead]
Learn about the new capabilities available in ONTAP 9.18.1.

For details about known issues, limitations, and upgrade cautions in recent ONTAP 9 releases, refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP 9 Release Notes^]. You must sign in with your NetApp account or create an account to access the Release Notes.

* Learn about new and enhanced https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html[ONTAP MetroCluster features^].

* Learn about https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9171.html[new and enhanced ONTAP software features for NetApp AFX storage systems^].

* Learn about https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html[new and enhanced ONTAP software features for NetApp ASA r2 storage systems^].

* Learn about https://docs.netapp.com/us-en/ontap-systems/whats-new.html[new and enhanced support for AFF, ASA, and FAS systems and supported switches^].

* Learn about updates to the https://docs.netapp.com/us-en/ontap-automation/whats_new.html[ONTAP REST API^]. 

To upgrade to the latest version of ONTAP, see link:../upgrade/create-upgrade-plan.html[Prepare to upgrade ONTAP].


== Data protection 

[cols="30%,70%",options="header"]
|===
| Update | Description
a|
xref:../data-protection/cloud-backup-with-snapmirror-task.html[SnapMirror cloud support for MetroCluster FlexGroup volumes]
a|
SnapMirror cloud supports backup and restore operations for FlexGroup volumes in MetroCluster configurations. 

//ONTAPDOC-3327
|===


== Networking

[cols="30%,70%",options="header"]
|===
| Update | Description 
a| 
xref:../networking/ipsec-prepare.html[IPsec hardware offload IPv6 support] 
a| 
IPsec hardware offload support is extended to IPv6. 
a|
xref:../networking/configure_network_security_using_federal_information_processing_standards_fips.html[OpenSSL PQC algorithms] 
a| 
ONTAP supports postquantum computing cryptographic algorithms for SSL. These algorithms provide additional protection against potential future quantum computing attacks, and are available when SSL FIPS mode is disabled. 
a|
xref:../networking/configure-backend-encryption.html[ONTAP backend cluster network encryption] 
a| 
You can enable TLS encryption for data-in-flight on the ONTAP backend cluster network. 
a|
xref:../high-availability/ha-pair-encryption.html[ONTAP HA traffic network encryption] 
a| 
You can enable encryption for traffic between nodes in high-availability (HA) pairs.  
|===

== SAN 

[cols="30%,70%",options="header"]
|===
| Update | Description 
a|
xref:../san-admin/nvme-copy-offload.html[NVMe copy offload]
a|
NVMe copy offload enables an NVMe host to offload copy operations from its CPU to the CPU of the ONTAP storage controller. The host can copy data from one NVMe namespace to another while reserving its CPU resources for application workloads. 

|===

== S3 object storage 

[cols="30%,70%",options="header"]
|===
| Update | Description
a|
xref:../s3-snapshots/list-restore-s3-snapshot.html[Support for point-in-time S3 snapshot restore]
a|
The S3 snapshot bucket is now accessible natively with the ONTAP CLI. In addition, you can restore a single object, a set of objects, or a whole bucket on an S3 client from an S3 snapshot. 

//ONTAPDOC-3162

a|
xref:../s3-multiprotocol/create-nas-bucket-task.html[Support for creating NAS buckets on FlexCache volumes] 
a|
You can create NAS buckets on FlexCache volumes, and applications can access data on FlexCache volumes with the S3 protocol when all nodes in the cluster are using ONTAP 9.18.1 or later. 

//ONTAPDOC-3407

|===

== Security  

[cols="30%,70%",options="header"]
|===
| Update | Description 
a|
xref:../anti-ransomware/use-cases-restrictions-concept.html#supported-configurations[FlexGroup volume support for ARP/AI]
a|
NetApp FlexGroup volumes support ARP/AI, providing advanced, machine-learning-based ransomware detection and protection. In ONTAP 9.17.1 and earlier, only the first generation of ARP was available for FlexGroup volumes. Beginning with ONTAP 9.18.1, FlexGroup volumes have parity with FlexVol volumes on both on-premises ONTAP platforms (AFF and FAS) and virtual ONTAP deployments (including Cloud Volumes ONTAP and ONTAP Select). As a result, ARP/AI becomes the default ARP technology for both FlexVol and FlexGroup volumes. 

//ONTAPDOC-3377

a|
xref:../anti-ransomware/index.html#enablement-options-for-arp[ARP/AI is enabled by default for new volumes on supported systems]
a|
When you create a new cluster or upgrade your cluster to 9.18.1, ARP/AI is automatically enabled by default on all new volumes for AFF A series, AFF C series, ASA, and https://docs.netapp.com/us-en/asa-r2/secure-data/enable-anti-ransomware-protection.html[ASA r2] systems after a 12-hour grace period. During this grace period, you can opt out of default enablement.

//ONTAPDOC-3234
|===

== Storage resource management enhancements  

[cols="30%,70%",options="header"]
|===
| Update | Description 
a|
xref:../performance-admin/adaptive-qos-policy-groups-task.html[Support for two-level nested QoS policy groups on SVMs and volumes]
a|
You can assign a QoS policy to an SVM and to volumes under the SVM at the same time. 

//ONTAPDOC-3272
a| 
xref:../flexcache/create-volume-task.html[Create SVM FlexCache volumes of origin volumes in an SVM-DR relationship] 
a|
You can create SVM FlexCache volumes of origin volumes that are part of an SVM-DR relationship. 

//ONTAPDOC-3349
a| 
xref:../volumes/commands-display-space-usage-reference.html[Commands for displaying space usage information] 
a|
In ONTAP 9.18.1 and later, the 'storage aggregate show-space' command changes how Logical Referenced Capacity and Logical Unreferenced Capacity is reported. Logical Referenced Capacity reports referenced blocks in all objects and unreferenced blocks in fragmented objects. Logical Unreferenced Capacity reports only unreferenced blocks in objects that have crossed the fullness threshold and are eligible for object deletion and defragmentation.

For example, when you use the default aggregate fullness threshold of 40% for ONTAP S3 and StorageGRID, 60% of the blocks in an object must be unreferenced before the blocks are reported as unreferenced capacity.

In releases earlier than ONTAP 9.18.1, Logical Referenced Capacity reports referenced blocks in all objects (both full and fragmented objects). Logical Unreferenced Capacity reports unreferenced blocks in all objects.

//ONTAPDOC-3637 
|===


// 2025-Nov-13, GH issue# 1902
//2025 Nov - 9.18.1 RC