---
sidebar: sidebar
permalink: fabricpool/add-connection-to-cloud-task.html
keywords: netapp, ontap, connection, cloud, cloud insights, cloud agent
summary: Beginning with ONTAP 9.9.0, you can use System Manager to add a connection to the cloud.
---
= Add a connection to the cloud
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.9.0, you can use System Manager to add a connection to the cloud.

You start by using NetApp Cloud Insights to configure a collector. During the configuration process, you copy a pairing code that is generated by Cloud Insights, and then you log on to a cluster using System Manager. There, you add a cloud connection using that pairing code. The rest of the process is completed in Cloud Insights.

.Steps

.	In Cloud Insights, during the process to configure a collector, copy the generated pairing code.

.	Using System Manager with ONTAP 9.9.0 or later, log on to the cluster.

.	Go to *Cluster > Settings*.

.	In the Cloud Connections section, select *Add* to add a connection.

.	Enter a name for the connection, and paste the pairing code in the space provided.

.	Select *Add*.

.	Return to Cloud Insights to complete the configuration of the collector.

For additional information about Cloud Insights, refer to link:https://docs.netapp.com/us-en/cloudinsights/task_dc_na_cloud_connection.html[Cloud Insights documentation^].

// 18 FEB 2021, BURT 1380318
// 31 MAR 2021, JIRA IE-268
// 07 DEC 2021, BURT 1430515
