---
permalink: fabricpool/benefits-storage-tiers-concept.html
sidebar: sidebar
keywords: benefits, storage, tiers, using, fabricpool
summary: "Configuring an aggregate to use FabricPool enables you to use storage tiers. You can efficiently balance the performance and cost of your storage system, monitor and optimize the space utilization, and perform policy-based data movement between storage tiers."
---
= Benefits of storage tiers by using FabricPool
:icons: font
:imagesdir: ../media/

[.lead]
Configuring an aggregate to use FabricPool enables you to use storage tiers. You can efficiently balance the performance and cost of your storage system, monitor and optimize the space utilization, and perform policy-based data movement between storage tiers.

* You can optimize storage performance and reduce storage cost by storing data in a tier based on whether the data is frequently accessed.
 ** Frequently accessed ("`hot`") data is stored in the _performance tier_.
+
The performance tier uses high-performance primary storage, such as an all flash (all SSD) aggregate of the storage system.

 ** Infrequently accessed ("`cold`") data is stored in the _cloud tier_, also known as the _capacity tier_.
+
The cloud tier uses an object store that is less costly and does not require high performance.
* You have the flexibility in specifying the tier in which data should be stored.
+
You can specify one of the supported tiering policy options at the volume level. The options enable you to efficiently move data across tiers as data becomes hot or cold.
+
link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies[Types of FabricPool tiering policies]

* You can choose one of the supported object stores to use as the cloud tier for FabricPool.
* You can monitor the space utilization in a FabricPool-enabled aggregate.
* You can see how much data in a volume is inactive by using inactive data reporting.
* You can reduce the on-premise footprint of the storage system.
+
You save physical space when you use a cloud-based object store for the cloud tier.
