---
permalink: fabricpool/enable-disable-aggressive-read-ahead-task.html
bar: sidebar
keywords: creating, volume, fabricpool, aggressive read ahead, enable, on prem, on premises, disable
summary: "Beginning with ONTAP 9.14.1, you can enable and disable aggressive read-ahead mode on volumes in FabricPools that provide support for media and entertain, such as movie streaming workloads."
---
= Enable and disable aggressive read-ahead mode
:icons: font
:imagesdir: ../media/

[.lead]

Beginning with ONTAP 9.14.1, you can enable and disable aggressive read-ahead mode on volumes in FabricPools that provide support for media and entertainment, such as movie streaming workloads. Aggressive read-ahead mode is available in ONTAP 9.14.1 on all on-premises platforms that support FabricPool. The feature is disabled by default.

.About this task

The `aggressive-readahead-mode` command has two options:

* `none`: read-ahead is disabled.
* `file_prefetch`: the system reads the entire file into memory ahead of the client application.

.Before you begin

* You should be a cluster or SVM administrator.
* You must be at the advanced privilege level.

.Enable aggressive read-ahead mode during volume creation

.Steps 

. Set the privilege level to advanced:
+
[source,cli]
----
set -privilege advanced
----

. Create a volume and enable cloud write mode:
+
[source,cli]
----
volume create -volume <volume name>  -aggressive-readahead-mode <none|file_prefetch>
----
+
The following example creates a volume named vol1 with aggressive read-ahead enabled with the file_prefetch option:
+
----
volume create -volume vol1 -aggressive-readahead-mode file_prefetch 
----

.Disable aggressive read-ahead mode

.Steps 

. Set the privilege level to advanced:
+
[source,cli]
----
set -privilege advanced
----

. Modify a volume to disable aggressive read-ahead mode:
+
[source,cli]
----
volume modify -volume <volume name>  -aggressive-readahead-mode none
----
+
The following example modifies a volume named vol1 to disable aggressive read-ahead mode:
+
----
volume modify -volume vol1 -aggressive-readahead-mode none
----

.View aggressive read-ahead mode on a volume

.Steps 

. Set the privilege level to advanced:
+
[source,cli]
----
set -privilege advanced
----

. Modify a volume to disable aggressive read-ahead mode:
+
[source,cli]
----
volume show -fields aggressive-readahead-mode
----


// 2023-Oct-17, ONTAPDOC-1233