---
permalink: fabricpool/enable-disable-aggressive-read-ahead-task.html
sidebar: sidebar
keywords: creating, volume, fabricpool, aggressive read ahead, enable, on prem, on premises, disable
summary: "Beginning with ONTAP 9.14.1, you can enable and disable aggressive read-ahead mode on volumes in FabricPools that provide support for media and entertain, such as movie streaming workloads."
---
= Enable ONTAP volumes in FabricPool to perform aggressive read-aheads
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.14.1, you can enable and disable aggressive read-ahead mode on volumes in FabricPools. Aggressive read-ahead mode is available in ONTAP 9.14.1 on all on-premises platforms that support FabricPool. The feature is disabled by default.

When aggressive read-ahead is _disabled_, FabricPool only reads the file blocks that a client application needs; it does not need to read the entire file. This can result in reduced network traffic, especially for large GB-sized and TB-sized files. _Enabling_ aggressive read-ahead on a volume turns this functionality off, and FabricPool preemptively reads the entire file sequentially from the object store, increasing GET throughput and reducing the latency of client reads on the file. By default, when tiered data is read sequentially it stays cold and is not written to the local tier.

Aggressive read-ahead trades network efficiency for increased performance of tiered data.

.About this task

The `aggressive-readahead-mode` command has two options:

* `none`: read-ahead is disabled.
* `file_prefetch`: the system reads the entire file into memory ahead of the client application.

.Before you begin

* You should be a cluster or SVM administrator.
* You must be at the advanced privilege level.

== Enable aggressive read-ahead mode during volume creation

.Steps 

. Set the privilege level to advanced:
+
[source,cli]
----
set -privilege advanced
----

. Create a volume and enable aggressive read-ahead mode:
+
[source,cli]
----
volume create -volume <volume name>  -aggressive-readahead-mode <none|file_prefetch>
----
+
The following example creates a volume named vol1 with aggressive read-ahead enabled with the file_prefetch option:
+
----
volume create -volume vol1 -aggressive-readahead-mode file_prefetch 
----

== Disable aggressive read-ahead mode

.Steps 

. Set the privilege level to advanced:
+
[source,cli]
----
set -privilege advanced
----
. Disable aggressive read-ahead mode:
+
[source,cli]
----
volume modify -volume <volume name>  -aggressive-readahead-mode none
----
+
The following example modifies a volume named vol1 to disable aggressive read-ahead mode:
+
----
volume modify -volume vol1 -aggressive-readahead-mode none
----

== View aggressive read-ahead mode on a volume

.Steps 

. Set the privilege level to advanced:
+
[source,cli]
----
set -privilege advanced
----
. View the aggressive read-ahead mode:
+
[source,cli]
----
volume show -fields aggressive-readahead-mode
----

// 2024-12-18 ONTAPDOC-2606
// 2024-Feb-26, ONTAPDOC-1667
// 2023-Oct-17, ONTAPDOC-1233