---
permalink: fabricpool/enable-disable-volume-cloud-write-task.html
sidebar: sidebar
keywords: creating, volume, fabricpool, cloud write, enable, disable
summary: "Beginning with ONTAP 9.14.1, you can enable and disable cloud write mode on a new or existing volume in a FabricPool to allow NFS clients to write data directly to the cloud."
---
= Enable and disable volumes to write directly to the cloud
:icons: font
:imagesdir: ../media/

[.lead]

Beginning with ONTAP 9.14.1, you can enable and disable cloud write mode on a new or existing volume in a FabricPool to allow NFS clients to write data directly to the cloud without waiting for tiering scans. SMB clients still write to the performance tier in a cloud write enabled volume. Cloud write mode is disabled by default.

Cloud write mode is helpful for cases like migrations, for example, where large amounts of data are transferred to a cluster than the cluster can support on the local tier. Without cloud write mode, during a migration, smaller amounts of data are transferred, then tiered, then transferred and tiered again, until the migration is complete. Using cloud write mode, this type of management is no longer required because the data is never transferred to the local tier.


.Before you begin

* You should be a cluster or SVM administrator.
* You must be at the advanced privilege level.
* The volume must be a read-write type volume.
* The volume must have the ALL tiering policy.


== Enable cloud write during volume creation

.Steps

. Set the privilege level to advanced:
+
[source,cli]
----
set -privilege advanced
----
. Create a volume and enable cloud write mode:
+
[source,cli]
----
volume create -volume <volume name> -is-cloud-write-enabled <true|false> -aggregate <local tier name>
----
+
The following example creates a volume named vol1 with cloud write enabled on the FabricPool local tier (aggr1):
+
----
volume create -volume vol1 -is-cloud-write-enabled true -aggregate aggr1
----

== Enable cloud write on an existing volume

.Steps

. Set the privilege level to advanced:
+
[source,cli]
----
set -privilege advanced
----
. Modify a volume to enable cloud write mode:
+
[source,cli]
----
volume modify -volume <volume name> -is-cloud-write-enabled <true|false> -aggregate <local tier name>
----
+
The following example modifies a volume named vol1 with cloud write enabled on the FabricPool local tier (aggr1):
+
----
volume modify -volume vol1 -is-cloud-write-enabled true -aggregate aggr1
----

== Disable cloud write on a volume

.Steps

. Set the privilege level to advanced:
+
[source,cli]
----
set -privilege advanced
----
. Disable cloud write mode:
+
[source,cli]
----
volume modify -volume <volume name> -is-cloud-write-enabled <true|false> -aggregate <aggregate name>
----
+
The following example creates a volume named vol1 with cloud write enabled:
+
----
volume modify -volume vol1 -is-cloud-write-enabled false -aggregate aggr1
----


// 2023-Oct-17, ONTAPDOC-1233