---
permalink: fabricpool/index.html
sidebar: sidebar
keywords: deciding, use, managing, storage tiers, fabricpool
summary: "This content describes how to configure and manage data in storage tiers using FabricPool depending on how frequently you access the data."
---
= Managing storage tiers by using FabricPool overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to configure and manage data in storage tiers using FabricPool depending on how frequently you access the data.


Storing data in tiers can enhance the efficiency of your storage system. Beginning with ONTAP 9.2, you can manage storage tiers by using FabricPool. It enables you to store data in a tier, based on whether the data is frequently accessed.

You should use this content under the following circumstances:

* You want to use the command-line interface (CLI), not ONTAP System Manager or an automated scripting tool.
* You want to use best practices, not explore every available option.

If this content is not suitable for your situation, you should see the following documentation instead:

* https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf[NetApp Technical Report 4598: FabricPool Best Practices]
* https://docs.netapp.com/us-en/occm/concept_cloud_tiering.html[NetApp Documentation: NetApp Cloud Tiering]
