---
permalink: fabricpool/modify-tiering-policy-cooling-period-task.html
sidebar: sidebar
keywords: managing, storage, tiering, modifying, volume, tiering, policy, tiering, minimum, cooling period
summary: "You can change the tiering policy of a volume to control whether data is moved to the cloud tier when it becomes inactive (cold). For a volume with the snapshot-only or auto tiering policy, you can also specify the tiering minimum cooling period that user data must remain inactive before it is moved to the cloud tier."
---
= Modify an ONTAP volume's tiering policy and minimum cooling period
:icons: font
:imagesdir: ../media/

[.lead]
You can change the tiering policy of a volume to control whether data is moved to the cloud tier when it becomes inactive (_cold_). For a volume with the `snapshot-only` or `auto` tiering policy, you can also specify the tiering minimum cooling period that user data must remain inactive before it is moved to the cloud tier.

.What you'll need

Changing a volume to the `auto` tiering policy or modifying the tiering minimum cooling period requires ONTAP 9.4 or later.

.About this task

Changing the tiering policy of a volume changes only the subsequent tiering behavior for the volume. It does not retroactively move data to the cloud tier.

Changing the tiering policy might affect how long it takes for data to become cold and be moved to the cloud tier.

link:tiering-policies-concept.html#what-happens-when-you-modify-the-tiering-policy-of-a-volume-in-fabricpool[What happens when you modify the tiering policy of a volume in FabricPool]

.Steps

. Modify the tiering policy for an existing volume by using the `volume modify` command with the `-tiering-policy` parameter:
+
You can specify one of the following tiering policies:

 ** `snapshot-only` (default)
 ** `auto`
 ** `all`
 ** `none`
+
link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies[Types of FabricPool tiering policies]

. If the volume uses the `snapshot-only` or `auto` tiering policy and you want to modify the tiering minimum cooling period, use the `volume modify` command with the `-tiering-minimum-cooling-days` optional parameter in the advanced privilege level.
+
You can specify a value between 2 and 183 for the tiering minimum cooling days. If you are using a version of ONTAP earlier than 9.8, you can specify a value between 2 and 63 for the tiering minimum cooling days.

.Example of modifying the tiering policy and the tiering minimum cooling period of a volume

The following example changes the tiering policy of the volume "`myvol`" in the SVM "`vs1`" to `auto` and the tiering minimum cooling period to 45 days:

----
cluster1::> volume modify -vserver vs1 -volume myvol
-tiering-policy auto -tiering-minimum-cooling-days 45
----

// 2024-12-18 ONTAPDOC-2606