---
permalink: fabricpool/requirements-concept.html
sidebar: sidebar
keywords: considerations, requirements, using, fabricpool
summary: "To help ensure that you optimize your FabricPool configurations, you should familiarize yourself with a few considerations and requirements about using FabricPool."
---
= Requirements for using ONTAP FabricPool
:icons: font
:imagesdir: ../media/

[.lead]
To help ensure that you optimize your FabricPool configurations, you should familiarize yourself with a few considerations and requirements about using FabricPool.

== General considerations and requirements
=== ONTAP 9.2
You must be running ONTAP 9.2 or later FabricPool. 

=== ONTAP 9.4
* You must be running ONTAP 9.4 or later releases for the following FabricPool functionality:
 ** The `auto` link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies[tiering policy]
 ** Specifying the tiering minimum cooling period
 ** Inactive data reporting (IDR)
 ** Using Microsoft Azure Blob Storage for the cloud as the cloud tier for FabricPool
 ** Using FabricPool with ONTAP Select

=== ONTAP 9.5
* You must be running ONTAP 9.5 or later releases for the following FabricPool functionality:
 ** Specifying the tiering fullness threshold
 ** Using IBM Cloud Object Storage as the cloud tier for FabricPool
 ** NetApp Volume Encryption (NVE) of the cloud tier, enabled by default.

=== ONTAP 9.6
* You must be running ONTAP 9.6 or later releases for the following FabricPool functionality:
 ** The `all` tiering policy
 ** Inactive data reporting enabled manually on HDD aggregates
 ** Inactive data reporting enabled automatically for SSD aggregates when you upgrade to ONTAP 9.6 and at time aggregate is created, except on low end systems with less than 4 CPU, less than 6 GB of RAM, or when WAFL-buffer-cache size is less than 3 GB.
+
ONTAP monitors system load, and if the load remains high for 4 continuous minutes, IDR is disabled, and is not automatically enabled. You can reenable IDR manually, however, manually enabled IDR is not automatically disabled.

 ** Using Alibaba Cloud Object Storage as the cloud tier for FabricPool
 ** Using Google Cloud Platform as the cloud tier for FabricPool
 ** Volume move without cloud tier data copy

=== ONTAP 9.7
* You must be running ONTAP 9.7 or later releases for the following FabricPool functionality:
 ** Non transparent HTTP and HTTPS proxy to provide access to only whitelisted access points, and to provide auditing and reporting capabilities.
 ** FabricPool mirroring to tier cold data to two object stores simultaneously
 ** FabricPool mirrors on MetroCluster configurations
 ** NDMP dump and restore enabled by default on FabricPool attached aggregates.
+
[NOTE]
====
If the backup application uses a protocol other than NDMP, such as NFS or SMB, all data being backed up in the performance tier becomes hot and can affect tiering of that data to the cloud tier. Non-NDMP reads can cause data migration from the cloud tier back to the performance tier.
====
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/NDMP_Backup_and_Restore_supported_for_FabricPool%3F[NDMP Backup and Restore Support for FabricPool]

=== ONTAP 9.8
* You must be running ONTAP 9.8 or later for the following FabricPool functionality:
 ** Cloud retrieval
 ** FabricPool with SnapLock Enterprise. FabricPool with SnapLock Enterprise requires a Feature Product Variance Request (FPVR). To create an FPVR, please contact your sales team.
 ** Minimum cooling period maximum of 183 days
 ** Object tagging using user-created custom tags
 ** HDD FabricPool aggregates
+
HDD FabricPools are supported with SAS, FSAS, BSAS and MSATA disks only on systems with 6 or more CPU cores.
+
Check https://hwu.netapp.com/Home/Index[Hardware Universe^] for the latest supported models.

=== ONTAP 9.10.1
* You must be running ONTAP 9.10.1 or later for the following FabricPool functionality:
 ** PUT throttling
 ** Temperature-sensitive storage efficiency (TSSE).

=== ONTAP 9.12.1
* You must be running ONTAP 9.12.1 or later for the following FabricPool functionality:
 ** SVM Migrate
 ** Support for FabricPool, FlexGroup, and SVM-DR working in conjunction. (Prior to 9.12.1 any two of these features worked together, but not all three in conjunction.)

=== ONTAP 9.14.1
* You must be running ONTAP 9.14.1 or later for the following FabricPool functionality:
 ** Cloud Write
 ** Aggressive Readahead

== Local tiers (aggregates)
FabricPool supports the following aggregate types:

* On AFF systems, you can only use SSD aggregates for FabricPool.
* On FAS systems, you can use either SSD or HDD aggregates for FabricPool.
* On Cloud Volumes ONTAP and ONTAP Select, you can use either SSD or HDD aggregates for FabricPool. Using SSD aggregates is recommended.

[NOTE]
====
Flash Pool aggregates, which contain both SSDs and HDDs, are not supported.
====

== Cloud tiers
FabricPool supports using the following object stores as the cloud tier:

 * Alibaba Cloud Object Storage Service (Standard, Infrequent Access)
 * Amazon S3 (Standard, Standard-IA, One Zone-IA, Intelligent-Tiering, Glacier Instant Retrieval)
 * Amazon Commercial Cloud Services (C2S)
 * Google Cloud Storage (Multi-Regional, Regional, Nearline, Coldline, Archive)
 * IBM Cloud Object Storage (Standard, Vault, Cold Vault, Flex)
 * Microsoft Azure Blob Storage (Hot and Cool)
 * NetApp ONTAP S3 (ONTAP 9.8 and later)
 * NetApp StorageGRID (StorageGRID 10.3 and later)

[NOTE] 
====
Glacier Flexible Retrieval and Glacier Deep Archive are not supported.
====
* The object store "`bucket`" (container) you plan to use must have already been set up, must have at least 10 GB of storage space, and must not be renamed.
* HA pairs that use FabricPool require intercluster LIFs to communicate with the object store.
* You cannot detach a cloud tier from a local tier after it is attached; however, you can use link:create-mirror-task.html[FabricPool mirror] to attach a local tier to a different cloud tier.


== ONTAP storage efficiencies
Storage efficiencies such as compression, deduplication, and compaction are preserved when moving data to the cloud tier, reducing required object storage capacity and transport costs.

[NOTE] 
Beginning in ONTAP 9.15.1, FabricPool supports Intel QuickAssist Technology (QAT4) which provides more aggressive, and more performant, storage efficiency savings. 

Aggregate inline deduplication is supported on the local tier, but associated storage efficiencies are not carried over to objects stored on the cloud tier.

When using the All volume tiering policy, storage efficiencies associated with background deduplication processes might be reduced as data is likely to be tiered before the additional storage efficiencies can be applied.

== BlueXP tiering license
FabricPool requires a capacity-based license when attaching third-party object storage providers (such as
Amazon S3) as cloud tiers for AFF and FAS systems. A BlueXP Tiering license is not required when using
StorageGRID or ONTAP S3 as the cloud tier or when tiering with Cloud Volumes ONTAP, Amazon FSx for NetApp ONTAP, or Azure NetApp files.

BlueXP licenses (including add-on or extensions to preexisting FabricPool licenses) are
activated in the link:https://docs.netapp.com/us-en/bluexp-tiering/concept-cloud-tiering.html[BlueXP digital wallet^].


== StorageGRID consistency controls
StorageGRID’s consistency controls affects how the metadata that StorageGRID uses to track objects is
distributed between nodes and the availability of objects for client requests. NetApp recommends using
the default, read-after-new-write, consistency control for buckets used as FabricPool targets.
[NOTE] 
Do not use the available consistency control for buckets used as FabricPool targets.

== Additional considerations for tiering data accessed by SAN protocols

When tiering data that is accessed by SAN protocols, NetApp recommends using private clouds, like ONTAP S3 or StorageGRID, due to connectivity considerations.

[IMPORTANT]

You should be aware that when using FabricPool in a SAN environment with a Windows host, if the object storage becomes unavailable for an extended period of time when tiering data to the cloud, files on the NetApp LUN on the Windows host might become inaccessible or disappear. See the Knowledge Base article link:https://kb.netapp.com/onprem/ontap/os/During_FabricPool_S3_object_store_unavailable_Windows_SAN_host_reported_filesystem_corruption[During FabricPool S3 object store unavailable Windows SAN host reported filesystem corruption^].

== Quality of Service
* If you use throughput floors (QoS Min), the tiering policy on the volumes must be set to `none` before the aggregate can be attached to FabricPool.
+
Other tiering policies prevent the aggregate from being attached to FabricPool. A QoS policy will not enforce throughput floors when FabricPool is enabled.

== Functionality or features not supported by FabricPool

* Object stores with WORM enabled and object versioning enabled.
* Information lifecycle management (ILM) policies that are applied to object store buckets
+
FabricPool supports StorageGRID’s Information Lifecycle Management policies only for data replication and erasure coding to protect cloud tier data from failure. However, FabricPool does _not_ support advanced ILM rules such as filtering based on user metadata or tags. ILM typically includes various movement and deletion policies. These policies can be disruptive to the data in the cloud tier of FabricPool. Using FabricPool with ILM policies that are configured on object stores can result in data loss.

* 7-Mode data transition using the ONTAP CLI commands or the 7-Mode Transition Tool
* FlexArray Virtualization
* RAID SyncMirror, except in a MetroCluster configuration
* SnapLock volumes when using ONTAP 9.7 and earlier releases
* Tape backup using SMTape for FabricPool-enabled aggregates
* The Auto Balance functionality
* Volumes using a space guarantee other than `none`
+
With the exception of root SVM volumes and CIFS audit staging volumes, FabricPool does not support attaching a cloud tier to an aggregate that contains volumes using a space guarantee other than `none`. For example, a volume using a space guarantee of `volume` (`-space-guarantee` `volume`) is not supported.

* Clusters with link:../data-protection/snapmirror-licensing-concept.html#data-protection-optimized-license[DP_Optimized license]
* Flash Pool aggregates

// 2024-Dec-04, ONTAPDOC-2579
// 2024-July-17, Added additional features/releases, storage efficiency, cloud tiers, and licensing information.
// 2024-April-24, ONTAPDOC-1049
// 2024-April-22, GitHub issue# 1335
// 2024-Mar-28, ONTAPDOC-1366
// 2023-Sept-13, issue# 1097
// 2023-July-24, issue# 1023
// 2023-July-7, BURT 1546161
// 2023-June-7, BURT 1276358
// 2023-May-4, ONTAPDOC-990
// 2023-Jan-18, issue# 765
// 2021-11-9, BURT 1437100
// 4 FEB 2022, BURT 1451789
// 2022-8-12, FabricPool reorg updates
