---
permalink: fabricpool/setup-google-storage-cloud-tier-task.html
sidebar: sidebar
keywords: setting up, google cloud storage, cloud tier
summary: "If you are running ONTAP 9.6 or later, you can set up Google Cloud Storage as the cloud tier for FabricPool."
---
= Set up Google Cloud Storage as the ONTAP FabricPool cloud tier
:icons: font
:imagesdir: ../media/

[.lead]
If you are running ONTAP 9.6 or later, you can set up Google Cloud Storage as the cloud tier for FabricPool.

== Additional considerations for using Google Cloud Storage with FabricPool

* A link:https://bluexp.netapp.com/cloud-tiering[BlueXP tiering license] is required when tiering to Google Cloud Storage.

* It is recommended that the LIF that ONTAP uses to connect with the Google Cloud Storage object server be on a 10 Gbps port.
* On AFF and FAS systems and ONTAP Select, FabricPool supports the following Google Cloud Object storage classes:
 ** Google Cloud Multi-Regional
 ** Google Cloud Regional
 ** Google Cloud Nearline
 ** Google Cloud Coldline
+
https://cloud.google.com/storage/docs/storage-classes[Google Cloud: Storage Classes^]

.Steps

. Specify the Google Cloud Storage configuration information by using the `storage aggregate object-store config create` command with the `-provider-type` `GoogleCloud` parameter.
 ** The `storage aggregate object-store config create` command fails if ONTAP cannot access Google Cloud Storage with the provided information.
 ** You use the `-access-key` parameter to specify the access key for authorizing requests to the Google Cloud Storage object store.
 ** If the Google Cloud Storage password is changed, you should update the corresponding password stored in ONTAP immediately.
+
Doing so enables ONTAP to access the data in Google Cloud Storage without interruption.

+
----
storage aggregate object-store config create my_gcp_store_1 -provider-type GoogleCloud  -container-name my-gcp-bucket1 -access-key GOOGAUZZUV2USCFGHGQ511I8
----
. Display and verify the Google Cloud Storage configuration information by using the `storage aggregate object-store config show` command.
+
The `storage aggregate object-store config modify` command enables you to modify the Google Cloud Storage configuration information for FabricPool.

// 2024-12-18 ONTAPDOC-2606
// 2024-Oct-11, Removed reference to free 10TB capacity; linked to BlueXP/cloud-tiering 
// 2024-Mar-28, ONTAPDOC-1366
// 2023-Feb-21, BURT 1391390
// 2022-8-12, FabricPool reorg updates