---
permalink: fabricpool/setup-azure-blob-storage-cloud-tier-task.html
sidebar: sidebar
keywords: setting up, azure blob storage, cloud, cloud tier
summary: "If you are running ONTAP 9.4 or later, you can set up Azure Blob Storage for the cloud as the cloud tier for FabricPool."
---
= Set up Azure Blob Storage for the cloud as the cloud tier
:icons: font
:imagesdir: ../media/

[.lead]
If you are running ONTAP 9.4 or later, you can set up Azure Blob Storage for the cloud as the cloud tier for FabricPool.

.Considerations for using Microsoft Azure Blob Storage with FabricPool

* You might need a FabricPool license.
+
Newly ordered AFF systems come with 10 TB of free capacity for using FabricPool. If you need additional capacity on an AFF system, if you use Azure Blob Storage on a non-AFF system, or if you upgrade from an existing cluster, you need a https://docs.netapp.com/us-en/ontap/fabricpool/install-license-aws-azure-ibm-task.html[FabricPool license^].
+
If you order FabricPool for the first time for an existing cluster, a FabricPool license with 10 TB of free capacity is available.

* A FabricPool license is not required if you are using Azure Blob Storage with Cloud Volumes ONTAP.
* It is recommended that the LIF that ONTAP uses to connect with the Azure Blob Storage object server be on a 10 Gbps port.
* FabricPool currently does not support Azure Stack, which is on-premises Azure services.
* At the account level in Microsoft Azure Blob Storage, FabricPool supports only hot and cool storage tiers.
+
FabricPool does not support blob-level tiering. It also does not support tiering to Azure's archive storage tier.

.About this task

FabricPool currently does not support Azure Stack, which is on-premises Azure services.

.Steps

. Specify the Azure Blob Storage configuration information by using the `storage aggregate object-store config create` command with the `-provider-type` `Azure_Cloud` parameter.
 ** The `storage aggregate object-store config create` command fails if ONTAP cannot access Azure Blob Storage with the provided information.
 ** You use the `-azure-account` parameter to specify the Azure Blob Storage account.
 ** You use the `-azure-private-key` parameter to specify the access key for authenticating requests to Azure Blob Storage.
 ** If the Azure Blob Storage password is changed, you should update the corresponding password stored in ONTAP immediately.
+
Doing so enables ONTAP to access the data in Azure Blob Storage without interruption.

+
----
cluster1::> storage aggregate object-store config create
-object-store-name MyAzure -provider-type Azure_Cloud
-server blob.core.windows.net -container-name myAzureContainer
-azure-account myAzureAcct -azure-private-key myAzureKey
----
. Display and verify the Azure Blob Storage configuration information by using the `storage aggregate object-store config show` command.
+
The `storage aggregate object-store config modify` command enables you to modify the Azure Blob Storage configuration information for FabricPool.

// 2024-Mar-28, ONTAPDOC-1366
// 2023-Feb-21, BURT 1391390
// 2022-8-12, FabricPool reorg updates