---
permalink: fabricpool/setup-ontap-s3-cloud-tier-task.html
sidebar: sidebar
keywords: tr-4814, fabricpool, setting up, ontap s3, cloud tier, local tier, tiering, storage tiering, storage tier, lif
summary: "If you are running ONTAP 9.8 or later, you can set up ONTAP S3 as the cloud tier for FabricPool."
---
= Set up ONTAP S3 as the FabricPool cloud tier
:icons: font
:imagesdir: ../media/

[.lead]
If you are running ONTAP 9.8 or later, you can set up ONTAP S3 as the cloud tier for FabricPool.

.Before you begin

* You must have the ONTAP S3 server name and the IP address of its associated LIFs on the remote cluster.
+
NOTE: The server name is used as the fully qualified domain name (FQDN) by client applications. Outside of ONTAP, confirm DNS records point to the SVM data LIFs being used.

* There must be <<create-lif,intracluster LIFs>> on the local cluster.
+
When configured for local cluster tiering, a local tier (also known as a storage aggregate in the ONTAP CLI) is attached to a local bucket. FabricPool uses cluster LIFs for intracluster traffic.
+
NOTE: Performance degradation might occur if cluster LIF resources become saturated. To avoid this, NetApp recommends using four-node or greater clusters when tiering to a local bucket along with an HA pair for the local tier and an HA pair for the local bucket. Tiering to local buckets on a single HA pair is not recommended.

* To enable remote FabricPool capacity (cloud) tiering using ONTAP S3, you must link:../s3-config/create-intercluster-lifs-remote-fabricpool-tiering-task.html[configure intercluster LIFs] on the FabricPool client and link:../s3-config/create-data-lifs-task.html[configure data LIFs] on the object store server.

.About this task

Load balancing is enabled for ONTAP S3 servers in ONTAP 9.8 and later. When the server's hostname resolves to more than one IP address, ONTAP establishes client connections with all the IP addresses returned (up to a maximum of 16 IP addresses). The IP addresses are picked up in a round-robin method when connections are established.

.Procedure

You can set up ONTAP S3 as the cloud tier for FabricPool with ONTAP System Manager or the ONTAP CLI. 

[role="tabbed-block"]
====

.System Manager
--

. Click *Storage > Tiers > Add Cloud Tier* and select ONTAP S3 as the object store provider.
. Complete the requested information.
. If you want to create a cloud mirror, click *Add as FabricPool Mirror*.

A FabricPool mirror provides a method for you to seamlessly replace a data store, and it helps to ensure that your data is available in the event of disaster.
--
.CLI
--

. Add entries for the S3 server and LIFs to your DNS server.
+

|===

h| Option h|Description

a|
*If you use an external DNS server*
a|
Give the S3 server name and IP addresses to the DNS server administrator.
a|
*If you use your local system's DNS hosts table*
a|
Enter the following command:

----
dns host create -vserver <svm_name> -address ip_address -hostname <s3_server_name>
----

|===

. Specify the ONTAP S3 configuration information by using the `storage aggregate object-store config create` command with the `-provider-type` `ONTAP_S3` parameter.
 ** The `storage aggregate object-store config create` command fails if the local ONTAP system cannot access the ONTAP S3 server with the information provided.
 ** You use the `-access-key` parameter to specify the access key for authorizing requests to the ONTAP S3 server.
 ** You use the `-secret-password` parameter to specify the password (secret access key) for authenticating requests to the ONTAP S3 server.
 ** If the ONTAP S3 server password is changed, you should immediately update the corresponding password stored in the local ONTAP system.
+
Doing so enables access to the data in the ONTAP S3 object store without interruption.

 ** Setting the `-is-certificate-validation-enabled` parameter to `false` disables certificate checking for ONTAP S3. Using signed certificates (`-is-certificate-validation-enabled true`) from a third-party certificate authority is a recommended best practice.

+
----
cluster1::> storage aggregate object-store config create
-object-store-name myS3 -provider-type ONTAP_S3 -server myS3server
-container-name myS3container -access-key myS3key
-secret-password myS3pass
----
. Display and verify the ONTAP_S3 configuration information by using the `storage aggregate object-store config show` command.
+
The `storage aggregate object-store config modify` command enables you to modify the `ONTAP_S3` configuration information for FabricPool.
--
====

[[create-lif]]
.Related information

* link:../smb-config/create-lif-task.html[Create LIF for SMB]
* link:../nfs-config/create-lif-task.html[Create LIF for NFS]


// 2025-2-25,GH-1657
// 2024-12-18 ONTAPDOC-2606
// 2024-11-6, S3 certs
// 2023 Jan 19, ontap-issues-727
// 2022 Jan 07, BURT 1372360 
