---
permalink: fabricpool/setup-alibaba-object-storage-cloud-tier-task.html
sidebar: sidebar
keywords: setting, up, alibaba cloud object, storage, cloud tier
summary: "If you are running ONTAP 9.6 or later, you can set up Alibaba Cloud Object Storage as the cloud tier for FabricPool."
---
= Set up Alibaba Cloud Object Storage as the cloud tier
:icons: font
:imagesdir: ../media/

[.lead]
If you are running ONTAP 9.6 or later, you can set up Alibaba Cloud Object Storage as the cloud tier for FabricPool.

.Steps

. Specify the Alibaba Cloud Object Storage configuration information by using the `storage aggregate object-store config create` command with the `-provider-type` `AliCloud` parameter.
 ** The `storage aggregate object-store config create` command fails if ONTAP cannot access Alibaba Cloud Object Storage with the provided information.
 ** You use the `-access-key` parameter to specify the access key for authorizing requests to the Alibaba Cloud Object Storage object store.
 ** If the Alibaba Cloud Object Storage password is changed, you should update the corresponding password stored in ONTAP immediately.
+
Doing so enables ONTAP to access the data in Alibaba Cloud Object Storage without interruption.

+
----
storage aggregate object-store config create my_ali_oss_store_1
-provider-type AliCloud -server oss-us-east-1.aliyuncs.com
-container-name my-ali-oss-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. Display and verify the Alibaba Cloud Object Storage configuration information by using the `storage aggregate object-store config show` command.
+
The `storage aggregate object-store config modify` command enables you to modify the Alibaba Cloud Object Storage configuration information for FabricPool.
