---
permalink: fabricpool/setup-ibm-object-storage-cloud-tier-task.html
sidebar: sidebar
keywords: setting up, ibm cloud, object storage, cloud tier
summary: "If you are running ONTAP 9.5 or later, you can set up IBM Cloud Object Storage as the cloud tier for FabricPool."
---
= Set up IBM Cloud Object Storage as the cloud tier
:icons: font
:imagesdir: ../media/

[.lead]
If you are running ONTAP 9.5 or later, you can set up IBM Cloud Object Storage as the cloud tier for FabricPool.

.Steps

. Specify the IBM Cloud Object Storage configuration information by using the `storage aggregate object-store config create` command with the `-provider-type` `IBM_COS` parameter.
 ** The `storage aggregate object-store config create` command fails if ONTAP cannot access IBM Cloud Object Storage with the provided information.
 ** You use the `-access-key` parameter to specify the access key for authorizing requests to the IBM Cloud Object Storage object store.
 ** You use the `-secret-password` parameter to specify the password (secret access key) for authenticating requests to the IBM Cloud Object Storage object store.
 ** If the IBM Cloud Object Storage password is changed, you should update the corresponding password stored in ONTAP immediately.
+
Doing so enables ONTAP to access the data in IBM Cloud Object Storage without interruption.

+
----
storage aggregate object-store config create
-object-store-name MyIBM -provider-type IBM_COS
-server s3.us-east.objectstorage.softlayer.net
-container-name my-ibm-cos-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. Display and verify the IBM Cloud Object Storage configuration information by using the `storage aggregate object-store config show` command.
+
The `storage aggregate object-store config modify` command enables you to modify the IBM Cloud Object Storage configuration information for FabricPool.
