---
permalink: fabricpool/throttle-puts-task.html
sidebar: sidebar
keywords: throttle, fabricpool, fabric pool, tiering
summary: "PUT throttling enables storage administrators to set an upper threshold on the maximum per node put rate."
---
= Throttle FabricPool PUTs
:icons: font
:imagesdir: ../media/

[.lead]
PUT throttling enables storage administrators to set an upper threshold on the maximum per node put rate.

PUT throttling is useful when network resources or the object store endpoint are resource constrained. Although rare, resource constraints can occur with underpowered object stores or during the first days of FabricPool usage when TB or PB of cold data begins to tier out.

PUT throttling is per node. The minimum PUT throttling put-rate-limit is 8MB/s. Setting the put-rate-limit to a value less than 8MB/s will result in 8MB/s throughput on that node. Multiple nodes, tiering concurrently, may consume more bandwidth and potentially saturate a network link with extremely limited capacity.

[NOTE]
====
FabricPool PUT operations do not compete for resources with other applications. FabricPool PUT operations are automatically placed at a lower priority (bullied) by client applications and other ONTAP workloads, such as SnapMirror. PUT throttling using `put-rate-limit`` may be useful for reducing network traffic associated with FabricPool tiering but it is unrelated to concurrent ONTAP traffic.
====

.Before you begin

Advanced privilege level is required.

.Steps

. To throttle FabricPool PUT operations by using the ONTAP CLI, run the following command:
+
[source,cli]
----
storage aggregate object-store put-rate-limit modify -node <name> -default <true|false> -putrate-bytes-limit <integer>[KB|MB|GB|TB|PB]
----

// 2024-Dec-10, PR 2165
// 06 DEC 2024, ONTAPDOC-1819
