---
permalink: upgrade-express/concept_deciding_whether_to_use_this_guide_dot_upgrade_eg.html
sidebar: sidebar
keywords: 
summary: 'This guide describes how to upgrade an ONTAP cluster with the automated upgrade feature using ONTAP System Manager.'
---
= Deciding whether to use the Upgrade Express Guide
:icons: font
:imagesdir: ../media/

[.lead]
This guide describes how to upgrade an ONTAP cluster with the automated upgrade feature using ONTAP System Manager.

You can also perform an automated upgrade using the command line interface (CLI); however, using ONTAP System Manager is preferred.

Beginning with ONTAP 9.3, automated upgrades can be performed for all ONTAP upgrades including MetroCluster configurations. However, automated upgrades for MetroCluster configurations are only supported by ONTAP System Manager for clusters with four nodes. If you need to upgrade a MetroCluster configuration for a cluster with a number of nodes other than four, you should use the CLI procedures in the _ONTAP Upgrade and Revert/Downgrade Guide_.

You should use this guide if you want to use ONTAP System Manager to:

* Perform an automated upgrade from ONTAP 9 or later for all non-MetroCluster configurations with two or more nodes.
+
If you want to perform a manual upgrade and you have less than eight nodes in your cluster, you should use the procedures in the _ONTAP Upgrade and Revert/Downgrade Guide_. Manual upgrades are not recommended for clusters with eight or more nodes.

* Perform an automated upgrade for single-node clusters running ONTAP 9.4 or later.
+
Beginning with ONTAP 9.4, you can perform an automated upgrade on a single-node cluster. If you want to upgrade a single-node cluster running ONTAP 9.3 or earlier, you should use the CLI procedures in the _ONTAP Upgrade and Revert/Downgrade Guide_.

*Related information*

xref:concept_cluster_update_requirements.adoc[Cluster update requirements]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ug-rdg/home.html[Upgrade, revert, or downgrade]
