---
permalink: upgrade-express/task_automatically_updating_a_cluster_using_system_manager.html
sidebar: sidebar
keywords: nondisruptive upgrades,NDU
summary: 'You can use ONTAP System Manager to update a cluster or individual nodes in HA pairs that are running ONTAP 8.3.1 or later to a specific version of ONTAP software without disrupting access to client data. You can also use ONTAP System Manager to automatically perform updates for single-node clusters running ONTAP 9.4 or later. Single-node cluster updates are disruptive.'
---
= Automatically updating a cluster using ONTAP System Manager
:icons: font
:imagesdir: ../media/

[.lead]
You can use ONTAP System Manager to update a cluster or individual nodes in HA pairs that are running ONTAP 8.3.1 or later to a specific version of ONTAP software without disrupting access to client data. You can also use ONTAP System Manager to automatically perform updates for single-node clusters running ONTAP 9.4 or later. Single-node cluster updates are disruptive.

* You should launch Active IQ Digital Advisor.
+
The Upgrade Advisor component of Active IQ Digital Advisor helps you plan for a successful update

* Single-node clusters must be running ONTAP 9.4 and ONTAP System Manager 9.4 or later.
* All of the nodes must be healthy.
+
The status of your nodes is indicated on the System Manager Dashboard under *Alerts and Notification* and under *Nodes*.

* You must have copied the software image from the NetApp Support Site so that the nodes can access the image.
+
xref:task_obtaining_ontap_software_images.adoc[Obtaining ONTAP software images]

If you try to perform other tasks from ONTAP System Manager while updating the node that hosts the cluster management LIF, an error message might be displayed. You must wait for the update to finish before performing any operations.

. Depending on the System Manager version that you are running, perform one of the following steps:
 ** ONTAP 9.4 or earlier: Click *Configuration* > *Cluster Update*.
 ** ONTAP 9.5 , or 9.6: Click *Configuration* > *Cluster* > *Update*.
 ** ONTAP 9.7 or later: Click *Cluster* > *Overview*
+
Then in the right corner of the Overview pane, click the three blue vertical dots, and *ONTAP Update*.
. In the Cluster Update tab, add a new image or select an available image.
+
|===
| If you want to...| Then...
a|
Add a new software image from the local client    *Note:* You should have already downloaded the image to the local client.
+
xref:task_obtaining_ontap_software_images.adoc[Obtaining ONTAP software images]
a|

 .. Under Available Software Images, click *Add from Local*.
 .. Browse to the location you saved the software image, select the image, and then click *Open*.
+
The software image uploads after you click *Open*.

a|
Add a new software image from the NetApp Support Site
a|

 .. Click *Add from Server*.
 .. In the Add a New Software Image dialog box, enter the URL of the HTTP server or FTP server on which you have saved the image that was downloaded from the NetApp Support Site.
+
For anonymous FTP, you must specify the URL in the ftp://anonymous@ftpserver format.

 .. Click *Add*.

a|
Select an available image
a|
Choose one of the listed images.
|===

. Click *Validate* to run the pre-update validation checks to verify whether the cluster is ready for an update.
+
The validation operation checks the cluster components to validate that the update can be completed nondisruptively, and then displays any errors or warnings. It also displays any required remedial action that you must perform before updating the software.
+
IMPORTANT: You must perform all of the required remedial actions for the errors before proceeding with the update. Although you can ignore the remedial actions for the warnings, the best practice is to perform all of the remedial actions before proceeding with the update.

. Click *Next*.
. Click *Update*.
+
Validation is performed again.

 ** When the validation is complete, a table displays any errors and warnings, along with any required remedial actions to be taken before proceeding.
 ** If the validation is completed with warnings, you can choose to select the *Continue update with warnings* checkbox, and then click *Continue*.
When the validation is complete and the update is in progress, the update might be paused because of errors. You can click the error message to view the details, and then perform the remedial actions before resuming the update.

+
After the update is completed successfully, the node reboots, and you are redirected to the ONTAP System Manager login page. If the node takes a long time to reboot, you must refresh your browser.

. Log in to ONTAP System Manager.
. Depending on the System Manager version that you are running, perform one of the following steps to view the details and verify that the cluster is successfully updated to the selected version
 ** ONTAP 9.4 or earlier: Click *Configuration* > *Cluster Update* > *Update History*.
 ** ONTAP 9.5 or 9.6: Click *Configuration* > *Cluster* > *Update* > *Update History*.
 ** ONTAP 9.7 or later: Click *Cluster* > *Overview*
+
Then in the right corner of the Overview pane, click the three blue vertical dots, and *Update History*.

*Related information*

https://aiq.netapp.com/[Launch Active IQ]

https://docs.netapp.com/us-en/active-iq/[Active IQ documentation]
