---
permalink: upgrade-express/task_resuming_an_upgrade_after_an_error_in_the_automated_upgrade_process.html
sidebar: sidebar
keywords: 
summary: 'If an automated upgrade pauses because of an error, you can resolve the error and resume the automated upgrade, or you can cancel the automated upgrade and complete the process manually. If you choose to continue the automated upgrade, do not perform any of the upgrade steps manually.'
---
= Resuming an upgrade after an error in the automated upgrade process
:icons: font
:imagesdir: ../media/

[.lead]
If an automated upgrade pauses because of an error, you can resolve the error and resume the automated upgrade, or you can cancel the automated upgrade and complete the process manually. If you choose to continue the automated upgrade, do not perform any of the upgrade steps manually.

. Depending on the System Manager version that you are running, perform one of the following steps:
 ** ONTAP 9.4 or earlier: Click *Configuration* > *Cluster Update*.
 ** ONTAP 9.5 or 9.6: Click *Configuration* > *Cluster* > *Update*.
 ** ONTAP 9.7 or later: Click *Cluster* > *Overview*
+
Then in the right corner of the Overview pane, click the three blue vertical dots, and *ONTAP Update*.
. Continue the automated update or cancel it and continue manually.
+
|===
| If you want to...| Then...
a|
Resume the automated updated
a|
Click *Resume*.
a|
Cancel the automated updated and continue manually
a|
Click *Cancel*.
|===
