---
permalink: nfs-config/additional-information-reference.html
sidebar: sidebar
keywords: additional, information, nfs, configuration, networking, san protocol, root volume, protection
summary: "After you have successfully tested NFS client access, you can perform additional NFS configuration or add SAN access. When protocol access is complete, you should protect the root volume of storage virtual machine (SVM)."
---
= Where to find additional information
:icons: font
:imagesdir: ../media/

[.lead]
After you have successfully tested NFS client access, you can perform additional NFS configuration or add SAN access. When protocol access is complete, you should protect the root volume of storage virtual machine (SVM).

== NFS configuration

You can further configure NFS access using the following information and technical reports:

* link:../nfs-admin/index.html[NFS management]
+
Describes how to configure and manage file access using NFS.

* https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf[NetApp Technical Report 4067: NFS Best Practice and Implementation Guide^]
+
Serves as an NFSv3 and NFSv4 operational guide, and provides an overview of the ONTAP operating system with a focus on NFSv4.

* https://www.netapp.com/pdf.html?item=/media/19371-tr-4073.pdf[NetApp Technical Report 4073: Secure Unified Authentication^]
+
Explains how to configure ONTAP for use with UNIX-based Kerberos version 5 (krb5) servers for NFS storage authentication and Windows Server Active Directory (AD) as the KDC and Lightweight Directory Access Protocol (LDAP) identity provider.

* http://www.netapp.com/us/media/tr-3580.pdf[NetApp Technical Report 3580: NFSv4 Enhancements and Best Practices Guide Data ONTAP Implementation]
+
Describes the best practices that should be followed while implementing NFSv4 components on AIX, Linux, or Solaris clients attached to systems running ONTAP.

== Networking configuration

You can further configure networking features and name services using the following informati and technical reports:

* link:../nfs-admin/index.html[NFS management]
+
Describes how to configure and manage ONTAP networking.

* https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf[NetApp Technical Report 4182: Ethernet Storage Design Considerations and Best Practices for Clustered Data ONTAP Configurations^]
+
Describes the implementation of ONTAP network configurations, and provides common network deployment scenarios and best practice recommendations.

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf[NetApp Technical Report 4668: Name Services Best Practices Guide^]
+
Explains how to configure LDAP, NIS, DNS, and local file configuration for authentication purposes.

== SAN protocol configuration

If you want to provide or modify SAN access to the new SVM, you can use the FC or iSCSI configuration information, which is available for multiple host operating systems.


== Root volume protection

After configuring protocols on the SVM, you should ensure that its root volume is protected:

* link:../data-protection/index.html[Data protection]
+
Describes how to create a load-sharing mirror to protect the SVM root volume, which is a NetApp best practice for NAS-enabled SVMs. Also describes how to quickly recover from volume failures or losses by promoting the SVM root volume from a load-sharing mirror.

// BURT 1448684, 10 JAN 2022
