---
permalink: nfs-config/comparison-exports-7-mode-concept.html
sidebar: sidebar
keywords: comparison, exports, 7-mode ontap
summary: "Exports in ONTAP are defined and used differently than they are in 7-Mode environments."
---
= Learn about 7-Mode and ONTAP NFS export comparisons
:icons: font
:imagesdir: ../media/

[.lead]
Exports in ONTAP are defined and used differently than they are in 7-Mode environments.

|===

h| Areas of difference h| 7-Mode h| ONTAP

a|
How exports are defined
a|
Exports are defined in the `/etc/exports` file.
a|
Exports are defined by creating an export policy within an SVM. An SVM can include more than one export policy.

a|
Scope of export
a|

* Exports apply to a specified file path or qtree.
* You must create a separate entry in `/etc/exports` for each file path or qtree.
* Exports are persistent only if they are defined in the `/etc/exports` file.

a|

* Export policies apply to an entire volume, including all of the file paths and qtrees contained in the volume.
* Export policies can be applied to more than one volume if you want.
* All export policies are persistent across system restarts.

a|
Fencing (specifying different access for specific clients to the same resources)
a|
To provide specific clients different access to a single exported resource, you have to list each client and its permitted access in the `/etc/exports` file.
a|
Export policies are composed of a number of individual export rules. Each export rule defines specific access permissions for a resource and lists the clients that have those permissions. To specify different access for specific clients, you have to create an export rule for each specific set of access permissions, list the clients that have those permissions, and then add the rules to the export policy.

a|
Name aliasing
a|
When you define an export, you can choose to make the name of the export different from the name of the file path. You should use the `-actual` parameter when defining such an export in the `/etc/exports` file.

a|
You can choose to make the name of the exported volume different from the actual volume name. To do this, you must mount the volume with a custom junction path name within the SVM namespace.

NOTE: By default, volumes are mounted with their volume name. To customize a volume's junction path name you need to unmount it, rename it, and then remount it.

|===

// 2025 May 28, ONTAPDOC-2982