---
permalink: nfs-config/export-policies-concept.html
sidebar: sidebar
keywords: secure, nfs, access, using, export, policies
summary: "You can use export policies to restrict NFS access to volumes or qtrees to clients that match specific parameters. When provisioning new storage, you can use an existing policy and rules, add rules to an existing policy, or create a new policy and rules. You can also check the configuration of export policies"
---
= Learn about securing ONTAP NFS access using export policies
:icons: font
:imagesdir: ../media/

[.lead]
You can use export policies to restrict NFS access to volumes or qtrees to clients that match specific parameters. When provisioning new storage, you can use an existing policy and rules, add rules to an existing policy, or create a new policy and rules. You can also check the configuration of export policies

[NOTE]
====
Beginning with ONTAP 9.3, you can enable export policy configuration checking as a background job that records any rules violations in an error rule list. The `vserver export-policy config-checker` commands invoke the checker and display results, which you can use to verify your configuration and delete erroneous rules from the policy.The commands only validate export configuration for host names, netgroups, and anonymous users.

====

// 2025 May 28, ONTAPDOC-2982