---
permalink: nfs-config/index.html
sidebar: sidebar
keywords: NFS, configuration, overview
summary: "This content describes how to use ONTAP 9 CLI commands to configure NFS client access to files contained in a new volume or qtree in a new or existing storage virtual machine."
---
= NFS configuration overview with the CLI
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to use ONTAP 9 CLI commands to configure NFS client access to files contained in a new volume or qtree in a new or existing storage virtual machine (SVM). It includes examples and advanced configuration options.

You should use this content if you want to configure access to a volume or qtree in the following way:

* You want to use any version of NFS currently supported by ONTAP: NFSv3, NFSv4, NFSv4.1, NFSv4.2, or NFSv4.1 with pNFS.
* You want to use the command-line interface (CLI), not ONTAP System Manager or an automated scripting tool.
* You want to use best practices, not explore every available option.
+
Details about command syntax are available from CLI help and ONTAP man pages.

* You do not want to read a lot of conceptual background.
+
Additional information about ONTAP technology and interaction with external services is available in the ONTAP Reference Library and in Technical Reports (TRs).

* UNIX file permissions will be used to secure the new volume.
* You have cluster administrator privileges, not SVM administrator privileges.

If you want details about the range of ONTAP NFS protocol capabilities, you should use the NFS reference material:

* link:/nfs-admin/index.html[NFS reference overview]
