---
permalink: nfs-config/where-provision-storage-capacity-task.html
sidebar: sidebar
keywords: decide, provision, new, nfs, storage, capacity
summary: "Before you create a new NFS volume or qtree, you must decide whether to place it in a new or existing SVM, and how much configuration the SVM requires. This decision determines your workflow."
---
= Decide where to provision new NFS storage capacity
:icons: font
:imagesdir: ../media/

[.lead]
Before you create a new NFS volume or qtree, you must decide whether to place it in a new or existing SVM, and how much configuration the SVM requires. This decision determines your workflow.

.Choices

* If you want to provision a volume or qtree on a new SVM, or on an existing SVM that has NFS enabled but not configured, complete the steps in both "Configuring NFS access to an SVM" and "Adding NFS storage to an NFS-enabled SVM".
+
xref:../nfs-config/create-svms-data-access-task.html[Configure NFS access to an SVM]
+
xref:add-storage-capacity-nfs-enabled-svm-concept.adoc[Add NFS storage to an NFS-enabled SVM]
+
You might choose to create a new SVM if one of the following is true:

 ** You are enabling NFS on a cluster for the first time.
 ** You have existing SVMs in a cluster in which you do not want to enable NFS support.
 ** You have one or more NFS-enabled SVMs in a cluster, and you want another NFS server in an isolated namespace (multi-tenancy scenario).
You should also choose this option to provision storage on an existing SVM that has NFS enabled but not configured. This might be the case if you created the SVM for SAN access or if no protocols were enabled when the SVM was created.

+
After enabling NFS on the SVM, proceed to provision a volume or qtree.

* If you want to provision a volume or qtree on an existing SVM that is fully configured for NFS access, complete the steps in "Adding NFS storage to an NFS-enabled SVM".
+
xref:add-storage-capacity-nfs-enabled-svm-concept.adoc[Adding NFS storage to an NFS-enabled SVM]

// 2024 Mar 15, ONTAPDOC-1788