---
permalink: system-admin/access-cluster-rsh-task.html
sidebar: sidebar
keywords: access, cluster, rsh, cluster, administrative, task, secure, protocol
summary: "You can issue RSH requests to the cluster to perform administrative tasks. RSH is not a secure protocol and is disabled by default."
---
= Access the cluster by using RSH
:icons: font
:imagesdir: ../media/

[.lead]
You can issue RSH requests to the cluster to perform administrative tasks. RSH is not a secure protocol and is disabled by default.

.What you'll need

The following conditions must be met before you can use RSH to access the cluster:

* You must have a cluster local user account that is configured to use RSH as an access method.
+
The `-application` parameter of the `security login` commands specifies the access method for a user account. For more information, see the `security login` man pages.

.About this task

* RSH is not a secure protocol.
+
You should consider using SSH to access the cluster. SSH provides a secure remote shell and interactive network session.

* ONTAP supports a maximum of 50 concurrent RSH sessions per node.
+
If the cluster management LIF resides on the node, it shares this limit with the node management LIF.
+
If the rate of incoming connections is higher than 10 per second, the service is temporarily disabled for 60 seconds.

* RSH commands require advanced privileges.

.Steps

. Confirm that the RSH security protocol is enabled using the following command:
+
`security protocol show`

.. If the RSH security protocol is enabled, continue to the next step.
.. If the RSH security protocol is not enabled, use the following command to enable it:
+
`security protocol modify -application rsh -enabled true` 

. Confirm that the `management-rsh-server` service exists on the management LIFs using the following command:
+
`network interface show -services management-rsh-server`

.. If the `management-rsh-server` service exists, continue to the next step.
.. If the `management-rsh-server` service does not exist, use the following command to add it:
+ 
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-rsh-server`

.Example of an RSH request

The following example shows how the user named "`joe`", who has been set up with RSH access, can issue an RSH request to run the `cluster show` command:

----

admin_host$ rsh 10.72.137.28 -l joe:password cluster show

Node                  Health  Eligibility
--------------------- ------- ------------
node1                 true    true
node2                 true    true
2 entries were displayed.

admin_host$
----

// 27-JULY-2024 GH-1401
