---
permalink: system-admin/access-system-console-node-task.html
sidebar: sidebar
keywords: access, system, console, node, serial, ssh, sp, boot
summary: "If a node is hanging at the boot menu or the boot environment prompt, you can access it only through the system console (also called the serial console). You can access the system console of a node from an SSH connection to the node’s SP or to the cluster."
---
= Access the system console of a node
:icons: font
:imagesdir: ../media/

[.lead]
If a node is hanging at the boot menu or the boot environment prompt, you can access it only through the system console (also called the _serial console_). You can access the system console of a node from an SSH connection to the node's SP or to the cluster.

.About this task

Both the SP and ONTAP offer commands that enable you to access the system console. However, from the SP, you can access only the system console of its own node. From the cluster, you can access the system console of any other node in the cluster (other than the local node).

.Steps

. Access the system console of a node:
+
[options="header"]
|===
| If you are in the...| Enter this command...
a|
SP CLI of the node
a|
`system console`
a|
ONTAP CLI
a|
`system node run-console`
|===

. Log in to the system console when you are prompted to do so.
. To exit the system console, press Ctrl-D.

.Examples of accessing the system console

The following example shows the result of entering the `system console` command at the "`SP node2`" prompt. The system console indicates that node2 is hanging at the boot environment prompt. The `boot_ontap` command is entered at the console to boot the node to ONTAP. Ctrl-D is then pressed to exit the console and return to the SP.

----
SP node2> system console
Type Ctrl-D to exit.

LOADER>
LOADER> boot_ontap
...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
...
----

(Ctrl-D is pressed to exit the system console.)

----

Connection to 123.12.123.12 closed.
SP node2>
----

The following example shows the result of entering the `system node run-console` command from ONTAP to access the system console of node2, which is hanging at the boot environment prompt. The `boot_ontap` command is entered at the console to boot node2 to ONTAP. Ctrl-D is then pressed to exit the console and return to ONTAP.

----
cluster1::> system node run-console -node node2
Pressing Ctrl-D will end this session and any further sessions you might open on top of this session.
Type Ctrl-D to exit.

LOADER>
LOADER> boot_ontap
...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
...
----

(Ctrl-D is pressed to exit the system console.)

----

Connection to 123.12.123.12 closed.
cluster1::>
----

// 2025 Feb 25, ONTAPDOC 1898