---
permalink: system-admin/accessg-node-log-core-dump-mib-files-task.html
sidebar: sidebar
keywords: service, processor, infrastructure, spi, web, service, node, log, core, dump, mib, file, browser
summary: "The Service Processor Infrastructure (spi) web service is enabled by default to enable a web browser to access the log, core dump, and MIB files of a node in the cluster. The files remain accessible even when the node is down, provided that the node is taken over by its partner."
---
= Access a node's log, core dump, and MIB files by using a web browser
:icons: font
:imagesdir: ../media/

[.lead]
The Service Processor Infrastructure (`spi`) web service is enabled by default to enable a web browser to access the log, core dump, and MIB files of a node in the cluster. The files remain accessible even when the node is down, provided that the node is taken over by its partner.

.What you'll need

* The cluster management LIF must be up.
+
You can use the management LIF of the cluster or a node to access the `spi` web service. However, using the cluster management LIF is recommended.
+
The `network interface show` command displays the status of all LIFs in the cluster.

* You must use a local user account to access the `spi` web service, domain user accounts are not supported.

* If your user account does not have the "`admin`" role (which has access to the `spi` web service by default), your access-control role must be granted access to the `spi` web service.
+
The `vserver services web access show` command shows what roles are granted access to which web services.

* If you are not using the "`admin`" user account (which includes the `http` access method by default), your user account must be set up with the `http` access method.
+
The `security login show` command shows user accounts' access and login methods and their access-control roles.

* If you want to use HTTPS for secure web access, SSL must be enabled and a digital certificate must be installed.
+
The `system services web show` command displays the configuration of the web protocol engine at the cluster level.

.About this task

The `spi` web service is enabled by default, and the service can be disabled manually (`vserver services web modify -vserver * -name spi -enabled false`).

The "`admin`" role is granted access to the `spi` web service by default, and the access can be disabled manually (`services web access delete -vserver _cluster_name_ -name spi -role admin`).

.Steps

. Point the web browser to the `spi` web service URL in one of the following formats:
 ** `http://_cluster-mgmt-LIF_/spi/`
 ** `https://_cluster-mgmt-LIF_/spi/`
+
`cluster-mgmt-LIF` is the IP address of the cluster management LIF.
. When prompted by the browser, enter your user account and password.
+
After your account is authenticated, the browser displays links to the `/mroot/etc/log/`, `/mroot/etc/crash/`, and `/mroot/etc/mib/` directories of each node in the cluster.

// 2022 Dec 06, ontap-issues-725