---
permalink: system-admin/access-cluster-telnet-task.html
sidebar: sidebar
keywords: access, cluster, telnet, administrative, tasks, disbale, default
summary: "You can issue Telnet requests to the cluster to perform administrative tasks. Telnet is disabled by default."
---
= Access the cluster by using Telnet
:icons: font
:imagesdir: ../media/

[.lead]
You can issue Telnet requests to the cluster to perform administrative tasks. Telnet is disabled by default.

.What you'll need

The following conditions must be met before you can use Telnet to access the cluster:

* You must have a cluster local user account that is configured to use Telnet as an access method.
+
The `-application` parameter of the `security login` commands specifies the access method for a user account. For more information, see the `security login` man pages.

.About this task

* Telnet is not a secure protocol.
+
You should consider using SSH to access the cluster. SSH provides a secure remote shell and interactive network session.

* ONTAP supports a maximum of 50 concurrent Telnet sessions per node.
+
If the cluster management LIF resides on the node, it shares this limit with the node management LIF.
+
If the rate of in-coming connections is higher than 10 per second, the service is temporarily disabled for 60 seconds.

* If you want to access the ONTAP CLI from a Windows host, you can use a third-party utility such as PuTTY.

* RSH commands require advanced privileges.

.Steps

. Confirm that the Telnet security protocol is enabled:
+
`security protocol show`

.. If the Telnet security protocol is enabled, continue to the next step.
.. If the Telnet security protocol is not enabled, use the following command to enable it:
+
`security protocol modify -application telnet -enabled true` 

. Confirm that the `management-telnet-server` service exists on the management LIFs:
+
`network interface show -services management-telnet-server`

.. If the `management-telnet-server` service exists, continue to the next step.
.. If the `management-telnet-server` service does not exist, use the following command to add it:
+ 
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-telnet-server`

.Example of a Telnet request

The following example shows how the user named "`joe`", who has been set up with Telnet access, can issue a Telnet request to access a cluster whose cluster management LIF is 10.72.137.28:

----
admin_host$ telnet 10.72.137.28
Data ONTAP
login: joe
Password:
cluster1::>
----

// 1-AUG-2024 GH-1401 and ONTAPDOC-1116