---
permalink: system-admin/access-cluster-telnet-task.html
sidebar: sidebar
keywords: access, cluster, telnet, administrative, tasks, disbale, default
summary: "You can issue Telnet requests to the cluster to perform administrative tasks. Telnet is disabled by default."
---
= Access the cluster by using Telnet
:icons: font
:imagesdir: ../media/

[.lead]
You can issue Telnet requests to the cluster to perform administrative tasks. Telnet is disabled by default.

.What you'll need

The following conditions must be met before you can use Telnet to access the cluster:

* You must have a cluster local user account that is configured to use Telnet as an access method.
+
The `-application` parameter of the `security login` commands specifies the access method for a user account. For more information, see the `security login` man pages.

* Telnet must already be enabled in the management firewall policy that is used by the cluster or node management LIFs so that Telnet requests can go through the firewall.
+
By default, Telnet is disabled. The `system services firewall policy show` command with the `-service telnet` parameter displays whether Telnet has been enabled in a firewall policy. For more information, see the `system services firewall policy` man pages.

* If you use IPv6 connections, IPv6 must already be configured and enabled on the cluster, and firewall policies must already be configured with IPv6 addresses.
+
The `network options ipv6 show` command displays whether IPv6 is enabled. The `system services firewall policy show` command displays firewall policies.

.About this task

* Telnet is not a secure protocol.
+
You should consider using SSH to access the cluster. SSH provides a secure remote shell and interactive network session.

* ONTAP supports a maximum of 50 concurrent Telnet sessions per node.
+
If the cluster management LIF resides on the node, it shares this limit with the node management LIF.
+
If the rate of in-coming connections is higher than 10 per second, the service is temporarily disabled for 60 seconds.

* If you want to access the ONTAP CLI from a Windows host, you can use a third-party utility such as PuTTY.

.Steps

. From an administration host, enter the following command:
+
`*telnet _hostname_or_IP_*`
+
`_hostname_or_IP_` is the host name or the IP address of the cluster management LIF or a node management LIF. Using the cluster management LIF is recommended. You can use an IPv4 or IPv6 address.

.Example of a Telnet request

The following example shows how the user named "`joe`", who has been set up with Telnet access, can issue a Telnet request to access a cluster whose cluster management LIF is 10.72.137.28:

----
admin_host$ telnet 10.72.137.28
Data ONTAP
login: joe
Password:
cluster1::>
----
