---
permalink: system-admin/acces-ssp-bmc-administration-host-task.html
sidebar: sidebar
keywords: access, sp, bmc, administration, host, node, management
summary: "You can log in to the SP of a node from an administration host to perform node management tasks remotely."
---
= Access the ONTAP SP/BMC of a node from an administration host
:icons: font
:imagesdir: ../media/

[.lead]
You can log in to the SP of a node from an administration host to perform node management tasks remotely.

.What you'll need

The following conditions must be met:

* The administration host you use to access the SP must support SSHv2.
* Your user account must already be set up for accessing the SP.
+
To access the SP, your user account must have been created with the `-application` parameter of the `security login create` command set to `service-processor` and the `-authmethod` parameter set to `password`.

[NOTE]
====
This task applies to both the SP and the BMC.
====

If the SP is configured to use an IPv4 or IPv6 address, and if five SSH login attempts from a host fail consecutively within 10 minutes, the SP rejects SSH login requests and suspends the communication with the IP address of the host for 15 minutes. The communication resumes after 15 minutes, and you can try to log in to the SP again.

ONTAP prevents you from creating or using system-reserved names (such as "`root`" and "`naroot`") to access the cluster or the SP.

.Steps

. From the administration host, log in to the SP:
+
`*ssh username@SP_IP_address*`
. When you are prompted, enter the password for `username`.
+
The SP prompt appears, indicating that you have access to the SP CLI.

.Examples of SP access from an administration host

The following example shows how to log in to the SP with a user account `joe`, which has been set up to access the SP.

----
[admin_host]$ ssh joe@192.168.123.98
joe@192.168.123.98's password:
SP>
----

The following examples show how to use the IPv6 global address or IPv6 router-advertised address to log in to the SP on a node that has SSH set up for IPv6 and the SP configured for IPv6.

----
[admin_host]$ ssh joe@fd22:8b1e:b255:202::1234
joe@fd22:8b1e:b255:202::1234's password:
SP>
----

----
[admin_host]$ ssh joe@fd22:8b1e:b255:202:2a0:98ff:fe01:7d5b
joe@fd22:8b1e:b255:202:2a0:98ff:fe01:7d5b's password:
SP>
----
