---
permalink: system-admin/administrative-privilege-levels-concept.html
sidebar: sidebar
keywords: administrative, privilege, levels, parameters, commands, admin, advanced, diagnostic
summary: "ONTAP commands and parameters are defined at three privilege levels: admin, advanced, and diagnostic. The privilege levels reflect the skill levels required in performing the tasks."
---
= Understand the privilege levels for ONTAP CLI commands
// old title: Use of administrative privilege levels
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP commands and parameters are defined at three privilege levels: _admin_, _advanced_, and _diagnostic_. The privilege levels reflect the skill levels required in performing the tasks.

* *admin*
+
Most commands and parameters are available at this level. They are used for common or routine tasks.

* *advanced*
+
Commands and parameters at this level are used infrequently, require advanced knowledge, and can cause problems if used inappropriately.
+
You use advanced commands or parameters only with the advice of support personnel.

* *diagnostic*
+
Diagnostic commands and parameters are potentially disruptive. They are used only by support personnel to diagnose and fix problems.
