---
permalink: system-admin/audit-manage-cross-cluster-requests.html
sidebar: sidebar
keywords: audit, peered, cross cluster, log, cluster, get request
summary: "While SET requests are logged by default, GET requests are not. However, you can use the settings command to control whether get requests sent from ONTAP HTML (-httpget), the ONTAP CLI (-cliget) or from the ONTAP APIs (-ontapiget) are logged in the file."
---
= Manage ONTAP cross-cluster audits
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.16.1 P1, cross-cluster auditing is enabled in ONTAP to log operations initiated from a peered cluster, allowing administrators to track user-driven and internal operations between clusters. This remote auditing is particularly valuable for cloud environments where multiple clusters interact because it provides traceability and accountability of remote actions.









While SET requests are logged by default, GET requests are not. However, you can control whether GET requests sent from ONTAP HTML (`-httpget`), the ONTAP CLI (`-cliget`), or from the ONTAP APIs (`-ontapiget`) are logged in the file.

You can modify audit logging settings from the ONTAP CLI, and beginning with ONTAP 9.11.1, from System Manager.

[role="tabbed-block"]
====

.System Manager
--


--

.CLI
--
* To specify that GET requests from the ONTAP CLI or APIs should be recorded in the audit log (the audit.log file), in addition to default set requests, enter: +
`security audit modify [-cliget {on|off}][-httpget {on|off}][-ontapiget {on|off}]`

* To display the current settings, enter: +
`security audit show`

Learn more about `security audit show` in the link:https://docs.netapp.com/us-en/ontap-cli/security-audit-show.html[ONTAP command reference^].
--
====

// 2025 June 9, ontapdoc-2937
// 2025 Jan 16, ONTAPDOC-2569
// 2022-05-03, jira-481
