---
permalink: system-admin/autosupport-active-iq-digital-advisor-concept.html
sidebar: sidebar
keywords: autosupport, active, iq, digital, advisor, telemetry, artificial, intelligence
summary: "The AutoSupport component of ONTAP collects telemetry and sends it for analysis. Digital Advisor analyzes the data from AutoSupport and provides proactive care and optimization. Using artificial intelligence, Digital Advisor can identify potential problems and help you resolve them before they impact your business."
---
= About Digital Advisor and AutoSupport
:icons: font
:imagesdir: ../media/

[.lead]
The AutoSupport component of ONTAP collects telemetry and sends it for analysis. Digital Advisor analyzes the data from AutoSupport and provides proactive care and optimization. Using artificial intelligence, Digital Advisor can identify potential problems and help you resolve them before they impact your business.

Digital Advisor enables you to optimize your data infrastructure across your global hybrid cloud by delivering actionable predictive analytics and proactive support through a cloud-based portal and mobile app. Data-driven insights and recommendations from Digital Advisor are available to all NetApp customers with an active SupportEdge contract (features vary by product and support tier).

Here are some things you can do with Digital Advisor:

* Plan upgrades. Digital Advisor identifies issues in your environment that can be resolved by upgrading to a newer version of ONTAP and the Upgrade Advisor component helps you plan for a successful upgrade.
* View system wellness. Your Digital Advisor dashboard reports any issues with wellness and helps you correct those issues. Monitor system capacity to make sure you never run out of storage space. View support cases for your system.
* Manage performance. Digital Advisor shows system performance over a longer period than you can see in System Manager. Identify configuration and system issues that are impacting your performance.
* Maximize efficiency. View storage efficiency metrics and identify ways to store more data in less space.
* View inventory and configuration. Digital Advisor displays complete inventory and software and hardware configuration information. See when service contracts are expiring and renew them to ensure you remain supported.

.Related information

https://docs.netapp.com/us-en/active-iq/[NetApp Documentation: Digital Advisor^]

https://aiq.netapp.com/custom-dashboard/search[Launch Digital Advisor^]

https://www.netapp.com/us/services/support-edge.aspx[SupportEdge Services^]
