---
permalink: system-admin/commands-manage-config-backup-files-reference.html
sidebar: sidebar
keywords: command, manage, configuration, backup, file
summary: "You use the system configuration backup commands to manage cluster and node configuration backup files."
---
= Commands for managing configuration backup files
:icons: font
:imagesdir: ../media/

[.lead]
You use the `system configuration backup` commands to manage cluster and node configuration backup files.

These commands are available at the advanced privilege level.

[options="header"]
|===
| If you want to...| Use this command...
a|
Create a new node or cluster configuration backup file
a|
`system configuration backup create`
a|
Copy a configuration backup file from a node to another node in the cluster
a|
`system configuration backup copy`
a|
Upload a configuration backup file from a node in the cluster to a remote URL (FTP, HTTP, HTTPS, TFTP, or FTPS)
a|
`system configuration backup upload`

When you use HTTPS in the remote URL, use the `-validate-certification` option to enable or disable digital certificate validation. Certificate validation is disabled by default.

[NOTE]
====
The web server to which you are uploading the configuration backup file must have PUT operations enabled for HTTP and POST operations enabled for HTTPS. Some web servers might require the installation of an additional module. For more information, see your web server's documentation. Supported URL formats vary by ONTAP release. Learn more about system configuration commands in the https://docs.netapp.com/us-en/ontap-cli/[`ONTAP command reference^].
====

a|
Download a configuration backup file from a remote URL to a node in the cluster, and, if specified, validate the digital certificate
a|
`system configuration backup download`

When you use HTTPS in the remote URL, use the `-validate-certification` option to enable or disable digital certificate validation. Certificate validation is disabled by default.

a|
Rename a configuration backup file on a node in the cluster
a|
`system configuration backup rename`
a|
View the node and cluster configuration backup files for one or more nodes in the cluster
a|
`system configuration backup show`
a|
Delete a configuration backup file on a node
a|
`system configuration backup delete`

[NOTE]
====
This command deletes the configuration backup file on the specified node only. If the configuration backup file also exists on other nodes in the cluster, it remains on those nodes.
====

|===
