---
permalink: system-admin/commands-manage-autosupport-reference.html
sidebar: sidebar
keywords: command, manage, autosupport, node, message, send, resend, cancel, configure, display, information
summary: "You use the system node autosupport commands to change or view AutoSupport configuration, display information about previous AutoSupport messages, and send, resend or cancel an AutoSupport message."
---
= Commands for managing AutoSupport
:icons: font
:imagesdir: ../media/

[.lead]
You use the `system node autosupport` commands to change or view AutoSupport configuration, display information about previous AutoSupport messages, and send, resend or cancel an AutoSupport message.

== Configure AutoSupport

[options="header"]
|===
| If you want to...| Use this command...
a|
Control whether any AutoSupport messages are sent
a|
`system node autosupport modify` with the `-state` parameter
a|
Control whether AutoSupport messages are sent to technical support
a|
`system node autosupport modify` with the `-support` parameter
a|
Set up AutoSupport or modify the configuration of AutoSupport
a|
`system node autosupport modify`
a|
Enable and disable AutoSupport messages to your internal support organization for individual trigger events, and specify additional subsystem reports to include in messages sent in response to individual trigger events
a|
`system node autosupport trigger modify`
|===

== Display information about the AutoSupport configuration

[options="header"]
|===
| If you want to...| Use this command...
a|
Display the AutoSupport configuration
a|
`system node autosupport show` with the `-node` parameter
a|
View a summary of all addresses and URLs that receive AutoSupport messages
a|
`system node autosupport destinations show`
a|
Display which AutoSupport messages are sent to your internal support organization for individual trigger events
a|
`system node autosupport trigger show`
a|
Display status of AutoSupport configuration as well as delivery to various destinations
a|
`system node autosupport check show`
a|
Display detailed status of AutoSupport configuration as well as delivery to various destinations
a|
`system node autosupport check show-details`
|===

== Display information about past AutoSupport messages

[options="header"]
|===
| If you want to...| Use this command...
a|
Display information about one or more of the 50 most recent AutoSupport messages
a|
`system node autosupport history show`
a|
Display information about recent AutoSupport messages generated to upload core dump or performance archive files to the technical support site or a specified URI
a|
`system node autosupport history show-upload-details`
a|
View the information in the AutoSupport messages including the name and size of each file collected for the message along with any errors
a|
`system node autosupport manifest show`
|===

== Send, resend, or cancel AutoSupport messages

[options="header"]
|===
| If you want to...| Use this command...
a|
Retransmit a locally stored AutoSupport message, identified by its AutoSupport sequence number
[NOTE]
====
If you retransmit an AutoSupport message, and if support already received that message, the support system will not create a duplicate case. If, on the other hand, support did not receive that message, then the AutoSupport system will analyze the message and create a case, if necessary.
====

a|
`system node autosupport history retransmit`
a|
Generate and send an AutoSupport message--for example, for testing purposes
a|
`system node autosupport invoke`
[NOTE]
====
Use the `-force` parameter to send a message even if AutoSupport is disabled. Use the `-uri` parameter to send the message to the destination you specify instead of the configured destination.
====

a|
Cancel an AutoSupport message
a|
`system node autosupport history cancel`
|===
.Related information

https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html[ONTAP command reference]
