---
permalink: system-admin/commands-manage-system-time-reference.html
sidebar: sidebar
keywords: command, manage, cluster, time, ntp, server, date, ntp, time, manually
summary: "You use the cluster time-service ntp server commands to manage the NTP servers for the cluster. You use the cluster date commands to manage the cluster time manually."
---
= Commands for managing the cluster time
:icons: font
:imagesdir: ../media/

[.lead]
You use the `cluster time-service ntp server` commands to manage the NTP servers for the cluster. You use the `cluster date` commands to manage the cluster time manually.

Beginning with ONTAP 9.5, you can configure your NTP server with symmetric authentication.

The following commands enable you to manage the NTP servers for the cluster:

[options="header"]
|===
| If you want to...| Use this command...
a|
Associate the cluster with an external NTP server without symmetric authentication
a|
`cluster time-service ntp server create -server server_name`
a|
Associate the cluster with an external NTP server with symmetric authenticationAvailable in ONTAP 9.5 or later

a|
`cluster time-service ntp server create -server server_ip_address -key-id key_id`
[NOTE]
====
The `key_id` must refer to an existing shared key configured with '`cluster time-service ntp key'.
====

a|
Enable symmetric authentication for an existing NTP serverAn existing NTP server can be modified to enable authentication by adding the required key-id.

Available in ONTAP 9.5 or later

a|
`cluster time-service ntp server modify -server server_name -key-id key_id`
a|
Disable symmetric authentication
a|
`cluster time-service ntp server modify -server server_name -is-authentication-enabled false`
a|
Configure a shared NTP key
a|
`cluster time-service ntp key create -id shared_key_id -type shared_key_type -value shared_key_value`
[NOTE]
====
Shared keys are referred to by an ID. The ID, its type, and value must be identical on both the node and the NTP server
====

a|
Display information about the NTP servers that are associated with the cluster
a|
`cluster time-service ntp server show`
a|
Modify the configuration of an external NTP server that is associated with the cluster
a|
`cluster time-service ntp server modify`
a|
Dissociate an NTP server from the cluster
a|
`cluster time-service ntp server delete`
a|
Reset the configuration by clearing all external NTP servers' association with the cluster
a|
`cluster time-service ntp server reset`
[NOTE]
====
This command requires the advanced privilege level.
====

|===
The following commands enable you to manage the cluster time manually:

[options="header"]
|===
| If you want to...| Use this command...
a|
Set or modify the time zone, date, and time
a|
`cluster date modify`
a|
Display the time zone, date, and time settings for the cluster
a|
`cluster date show`
|===
.Related information

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 Commands^]

// BURT 1426046, 2023 Jun 30