---
permalink: system-admin/commands-manage-feature-licenses-reference.html
sidebar: sidebar
keywords: command, manage, license, command, cluster, system, feature, usage, usage
summary: "You use the system license commands to manage feature licenses for the cluster. You use the system feature-usage commands to monitor feature usage."
---
= Commands for managing licenses
:icons: font
:imagesdir: ../media/

[.lead]
You use the `system license` commands to manage feature licenses for the cluster. You use the `system feature-usage` commands to monitor feature usage.

See the man pages for more information about the following system license commands:

* link:https://docs.netapp.com/us-en/ontap-cli-9141/system-license-clean-up.html[system license clean-up]
* link:https://docs.netapp.com/us-en/ontap-cli-9141/system-license-capacity-show.html#description[system license capacity show]
* link:https://docs.netapp.com/us-en/ontap-cli-9141/system-license-show-status.html[system license show-status]


[options="header", cols="2,4"]
|===
| If you want to...| Use this command...
a|
Add one or more licenses
a|
`system license add`

.Examples

The following example adds a list of licenses with the keys AAAAAAAAAAAAAAAAAAAAAAAAAAAA and BBBBBBBBBBBBBBBBBBBBBBBBBBBB to the cluster:

====
cluster1::> system license add -license-code AAAAAAAAAAAAAAAAAAAAAAAAAAAA, BBBBBBBBBBBBBBBBBBBBBBBBBBBB
====

The following example installs the licenses from the local node "/mroot/etc/lic_file":

====
cluster1::> system license add -use-license-file true
====

a|
Display information about installed licenses, for example:

* License package name and description
* License type (`site`, `license`, or `demo`)
* Expiration date, if applicable
* The cluster or nodes that a package is licensed for
* Whether the license was installed prior to Data ONTAP 8.2 (`legacy`)
* Customer ID

a|
`system license show`
[NOTE]
====
Some information is displayed only when you use the `–instance` parameter.
====

a|
Display all packages that require licenses and their current license status, including the following:

* The package name
* The licensed method
* The expiration date, if applicable

a|
`system license show-status`

.Example

The following example displays the license status of the cluster:

====
cluster1::> system license show-status
Status    License              Scope     Detailed Status
--------- -------------------  --------- ----------------------
partially-installed
          CIFS                 node      License missing on: Node2-Cluster1.
          SnapRestore          node      License missing on: Node2-Cluster1.
valid
          FCP                  node      -
          FabricPool           cluster   The system is using 1TB, and can use up to 25TB.
not-installed
          NFS                  -         -
          iSCSI                -         -
          SnapMirror           -         -
          FlexClone            -         -
          SnapVault            -         -
          SnapLock             -         -
          SnapManagerSuite     -         -
          SnapProtectApps      -         -
          V_StorageAttach      -         -
          Insight_Balance      -         -
          OCShift              -         -
          TPM                  -         -
          VE                   -         -
          DP_Optimized         -         -
not-applicable
          Cloud                -         -
          Select               -         -
20 entries were displayed.
====

a|
Delete the license of a package from the cluster or a node whose serial number you specify
a|
`system license delete`

.Examples

The following example deletes a license named CIFS and serial number 1-81-0000000000000000000123456 from the cluster:

====
cluster1::> system license delete -serial-number 1-81-0000000000000000000123456 -package CIFS
====

The following example deletes from the cluster all of the licenses under the installed-license Core Bundle for serial number 123456789:

====
cluster1::> system license delete { -serial-number 123456789 -installed-license "Core Bundle" }
====


a|
Display or remove expired or unused licenses
a|
`system license clean-up`

.Examples

The following example simulates and displays the licenses that can be cleaned up:

====

cluster-1::> system license clean-up -expired -unused

The following licenses were safely deleted:

Serial number: 1-80-000011
Owner: cdancluster-1
Package                   Reason
------------------------- -----------------------------------------------------
CIFS                      License has expired

Serial number: 4067154888
Owner: none
Package                   Reason
------------------------- -----------------------------------------------------
Cloud                     License has expired

Serial number: 1-81-0000000000000004067154999
Owner: none
Package                   Reason
------------------------- -----------------------------------------------------
iSCSI                     License unused by any node in the cluster
The following licenses are either expired or unused but cannot be safely deleted:

Serial number: 4067154778
Owner: node1
Package                   Reason
------------------------- -----------------------------------------------------
Cloud                     Feature would be impaired upon removal

Serial number: 4067154779
Owner: node2
Package                   Reason
------------------------- -----------------------------------------------------
Cloud                     System generated license

====

a|
Display summary of feature usage in the cluster on a per-node basis
a|
`system feature-usage show-summary`

a|
Display feature usage status in the cluster on a per-node and per-week basis
a|
`system feature-usage show-history`

a|
Display the status of license entitlement risk for each license package
a|
`system license entitlement-risk show`
[NOTE]
====
Some information is displayed only when you use the `-detail` and `-instance` parameters.
====

|===
.Related information

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 Commands^]

https://kb.netapp.com/onprem/ontap/os/ONTAP_9.10.1_and_later_licensing_overview[Knowledge Base article: ONTAP 9.10.1 and later licensing overview^]

https://docs.netapp.com/us-en/ontap/task_admin_enable_new_features.html[Use System Manager to install a NetApp license file^]


// 2023-July-19, issue# 1005