---
permalink: system-admin/commands-manage-web-services-reference.html
sidebar: sidebar
keywords: command, manage, web, service, vserver, svm, storage, virtual. machine
summary: "You use the vserver services web commands to manage the availability of web services for the cluster or a storage virtual machine (SVM). You use the vserver services web access commands to control a role’s access to a web service."
---
= Commands for managing web services
:icons: font
:imagesdir: ../media/

[.lead]
You use the `vserver services web` commands to manage the availability of web services for the cluster or a storage virtual machine (SVM). You use the `vserver services web access` commands to control a role's access to a web service.

[options="header"]
|===
| If you want to...| Use this command...
a|
Configure a web service for the cluster or anSVM:

* Enable or disable a web service
* Specify whether only HTTPS can be used for accessing a web service

a|
`vserver services web modify`
a|
Display the configuration and availability of web services for the cluster or anSVM
a|
`vserver services web show`
a|
Authorize a role to access a web service on the cluster or anSVM
a|
`vserver services web access create`
a|
Display the roles that are authorized to access web services on the cluster or anSVM
a|
`vserver services web access show`
a|
Prevent a role from accessing a web service on the cluster or anSVM
a|
`vserver services web access delete`
|===
.Related information

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 Commands^]
