---
permalink: system-admin/commands-monitor-health-system-reference.html
sidebar: sidebar
keywords: command, monitor, health, system, display, status, cli, software, version, switches, alert
summary: "You can use the system health commands to display information about the health of system resources, to respond to alerts, and to configure future alerts. Using the CLI commands enables you to view in-depth information about how health monitoring is configured. The man pages for the commands contain more information."
---
= Commands for monitoring the health of your system
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `system health` commands to display information about the health of system resources, to respond to alerts, and to configure future alerts. Using the CLI commands enables you to view in-depth information about how health monitoring is configured. The man pages for the commands contain more information.

== Display the status of system health

[options="header"]
|===
| If you want to...| Use this command...
a|
Display the health status of the system, which reflects the overall status of individual health monitors
a|
`system health status show`
a|
Display the health status of subsystems for which health monitoring is available
a|
`system health subsystem show`
|===

== Display the status of node connectivity

[options='header']
|===
| If you want to...| Use this command...
a|
Display details about connectivity from the node to the storage shelf, including port information, HBA port speed, I/O throughput, and the rate of I/O operations per second

a|
`storage shelf show -connectivity` Use the `-instance` parameter to display detailed information about each shelf.

a|
Display information about drives and array LUNs, including the usable space, shelf and bay numbers, and owning node name

a|
`storage disk show` Use the `-instance` parameter to display detailed information about each drive.

a|
Display detailed information about storage shelf ports, including port type, speed, and status

a|
`storage port show` Use the `-instance` parameter to display detailed information about each adapter.

|===

== Manage the discovery of cluster and management network switches

[options="header"]
|===
| If you want to...| Use this command...
a|
Display the switches that the cluster monitors
a|
`system cluster-switch show`
a|
Display the switches that the cluster currently monitors, including switches that you deleted (shown in the Reason column in the command output), and configuration information that you need for network access to the cluster and management network switchesThis command is available at the advanced privilege level.

a|
`system cluster-switch show-all`
a|
Configure discovery of an undiscovered switch
a|
`system cluster-switch create`
a|
Modify information about a switch that the cluster monitors (for example, device name, IP address, SNMP version, and community string)

a|
`system cluster-switch modify`
a|
Disable monitoring of a switch
a|
`system cluster-switch modify -disable-monitoring`
a|
Display the interval in which the health monitor polls switches to gather information
a|
`system cluster-switch polling-interval show`
a|
Modify the interval in which the health monitor polls switches to gather informationThis command is available at the advanced privilege level.

a|
`system cluster-switch polling-interval modify`
a|
Disable discovery and monitoring of a switch and delete switch configuration information
a|
`system cluster-switch delete`
a|
Permanently remove the switch configuration information which is stored in the database (doing so reenables automatic discovery of the switch)
a|
`system cluster-switch delete -force`
a|
Enable automatic logging to send with AutoSupport messagesThis command is available at the advanced privilege level.

a|
`system cluster-switch log`
|===

== Respond to generated alerts

[options="header"]
|===
| If you want to...| Use this command...
a|
Display information about generated alerts, such as the resource and node where the alert was triggered, and the alert's severity and probable cause
a|
`system health alert show`
a|
Display information about each generated alert
a|
`system health alert show -instance`
a|
Indicate that someone is working on an alert
a|
`system health alert modify`
a|
Acknowledge an alert
a|
`system health alert modify -acknowledge`
a|
Suppress a subsequent alert so that it does not affect the health status of a subsystem
a|
`system health alert modify -suppress`
a|
Delete an alert that was not automatically cleared
a|
`system health alert delete`
a|
Display information about the AutoSupport messages that alerts triggered within the last week, for example, to determine whether an alert triggered an AutoSupport message

a|
`system health autosupport trigger history show`
|===

== Configure future alerts

[options="header"]
|===
| If you want to...| Use this command...
a|
Enable or disable the policy that controls whether a specific resource state raises a specific alert

a|
`system health policy definition modify`
|===

== Display information about how health monitoring is configured

[options="header"]
|===
| If you want to...| Use this command...
a|
Display information about health monitors, such as their nodes, names, subsystems, and status

a|
`system health config show`
[NOTE]
====
Use the `-instance` parameter to display detailed information about each health monitor.
====

a|
Display information about the alerts that a health monitor can potentially generate

a|
`system health alert definition show`
[NOTE]
====
Use the `-instance` parameter to display detailed information about each alert definition.
====

a|
Display information about health monitor policies, which determine when alerts are raised

a|
`system health policy definition show`
[NOTE]
====
Use the `-instance` parameter to display detailed information about each policy. Use other parameters to filter the list of alerts--for example, by policy status (enabled or not), health monitor, alert, and so on.
====

|===

== Downgrade software versions between minor releases

When downgrading a cluster from Data ONTAP 8.2.1 to Data ONTAP 8.2, ONTAP clears the history of deleted switches. It also sets the `Model` column to `OTHER` if a switch that it automatically discovers is not supported for health monitoring.

[options="header"]
|===
| If you want to...| Use this command...
a|
Downgrade the software version command
a|
`system cluster-switch prepare-to-downgrade`
|===
