---
permalink: system-admin/commands-monitor-health-system-reference.html
sidebar: sidebar
keywords: command, monitor, health, system, display, status, cli, software, version, switches, alert
summary: "You can use the system health commands to display information about the health of system resources, to respond to alerts, and to configure future alerts. Using the CLI commands enables you to view in-depth information about how health monitoring is configured. The man pages for the commands contain more information."
---
= Commands for monitoring the health of your system
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `system health` commands to display information about the health of system resources, to respond to alerts, and to configure future alerts. Using the CLI commands enables you to view in-depth information about how health monitoring is configured. Learn more about `system health` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+health[ONTAP command reference^].

== Display the status of system health

[options="header"]
|===
| If you want to...| Use this command...
a|
Display the health status of the system, which reflects the overall status of individual health monitors
a|
`system health status show`
a|
Display the health status of subsystems for which health monitoring is available
a|
`system health subsystem show`
|===

== Display the status of node connectivity

[options='header']
|===
| If you want to...| Use this command...
a|
Display details about connectivity from the node to the storage shelf, including port information, HBA port speed, I/O throughput, and the rate of I/O operations per second

a|
`storage shelf show -connectivity`

Use the `-instance` parameter to display detailed information about each shelf.

a|
Display information about drives and array LUNs, including the usable space, shelf and bay numbers, and owning node name

a|
`storage disk show`

Use the `-instance` parameter to display detailed information about each drive.

a|
Display detailed information about storage shelf ports, including port type, speed, and status

a|
`storage port show`

Use the `-instance` parameter to display detailed information about each adapter.

|===

== Manage the discovery of cluster, storage, and management network switches

[cols=3*,options="header"]
|===
| If you want to...| Use this command.. (ONTAP 9.8 and later) | Use this command.. (ONTAP 9.7 and earlier)
a| Display the switches that the cluster monitors
a| `system switch ethernet show`
a| `system cluster-switch show`
a|
Display the switches that the cluster currently monitors, including switches that you deleted (shown in the Reason column in the command output), and configuration information that you need for network access to the cluster and management network switches.

This command is available at the advanced privilege level.
a| `system switch ethernet show-all`
a| `system cluster-switch show-all`
a|
Configure discovery of an undiscovered switch
a| `system switch ethernet create`
a| `system cluster-switch create`
a|
Modify information about a switch that the cluster monitors (for example, device name, IP address, SNMP version, and community string)
a| `system switch ethernet modify`
a| `system cluster-switch modify`
a|
Disable monitoring of a switch
a| `system switch ethernet modify -disable-monitoring`
a| `system cluster-switch modify -disable-monitoring`
a|
Disable discovery and monitoring of a switch and delete switch configuration information
a| `system switch ethernet delete`
a| `system cluster-switch delete`
a|
Permanently remove the switch configuration information which is stored in the database (doing so reenables automatic discovery of the switch)
a| `system switch ethernet delete -force`
a| `system cluster-switch delete -force`
a|
Enable automatic logging to send with AutoSupport messages.

a| `system switch ethernet log`
a| `system cluster-switch log`
|===

== Respond to generated alerts

[options="header"]
|===
| If you want to...| Use this command...
a|
Display information about generated alerts, such as the resource and node where the alert was triggered, and the alert's severity and probable cause
a|
`system health alert show`
a|
Display information about each generated alert
a|
`system health alert show -instance`
a|
Indicate that someone is working on an alert
a|
`system health alert modify`
a|
Acknowledge an alert
a|
`system health alert modify -acknowledge`
a|
Suppress a subsequent alert so that it does not affect the health status of a subsystem
a|
`system health alert modify -suppress`
a|
Delete an alert that was not automatically cleared
a|
`system health alert delete`
a|
Display information about the AutoSupport messages that alerts triggered within the last week, for example, to determine whether an alert triggered an AutoSupport message
a|
`system health autosupport trigger history show`
|===

== Configure future alerts

[options="header"]
|===
| If you want to...| Use this command...
a|
Enable or disable the policy that controls whether a specific resource state raises a specific alert

a|
`system health policy definition modify`
|===

== Display information about how health monitoring is configured

[options="header"]
|===
| If you want to...| Use this command...
a|
Display information about health monitors, such as their nodes, names, subsystems, and status

a|
`system health config show`
[NOTE]
====
Use the `-instance` parameter to display detailed information about each health monitor.
====

a|
Display information about the alerts that a health monitor can potentially generate

a|
`system health alert definition show`
[NOTE]
====
Use the `-instance` parameter to display detailed information about each alert definition.
====

a|
Display information about health monitor policies, which determine when alerts are raised

a|
`system health policy definition show`
[NOTE]
====
Use the `-instance` parameter to display detailed information about each policy. Use other parameters to filter the list of alerts--for example, by policy status (enabled or not), health monitor, alert, and so on.
====

|===

// 2025 Feb 17, ONTAPDOC-2758
// 8 August 2022, ontap-issues-567
// 18 july 2022, ontap-issues-579
