---
permalink: system-admin/commands-manage-mount-points-nodes-reference.html
sidebar: sidebar
keywords: command, manage, mount, point, nodes, spi, web, service, root, volume, root
summary: "The spi web service automatically creates a mount point from one node to another node’s root volume upon a request to access the node’s log files or core files. Although you do not need to manually manage mount points, you can do so by using the system node root-mount commands."
---
= Commands for managing mount points on the nodes
:icons: font
:imagesdir: ../media/

[.lead]
The `spi` web service automatically creates a mount point from one node to another node's root volume upon a request to access the node's log files or core files. Although you do not need to manually manage mount points, you can do so by using the `system node root-mount` commands.

[options="header"]
|===
| If you want to...| Use this command...
a|
Manually create a mount point from one node to another node's root volume
a|
`system node root-mount create` Only a single mount point can exist from one node to another.

a|
Display existing mount points on the nodes in the cluster, including the time a mount point was created and its current state
a|
`system node root-mount show`
a|
Delete a mount point from one node to another node's root volume and force connections to the mount point to close
a|
`system node root-mount delete`
|===
.Related information

link:../concepts/manual-pages.html[ONTAP command reference]
