---
permalink: system-admin/commands-manage-feature-licenses-reference.html
sidebar: sidebar
keywords: command, manage, license, command, cluster, system, feature, usage, usage
summary: "You use the system license commands to manage feature licenses for the cluster. You use the system feature-usage commands to monitor feature usage."
---
= Commands for managing licenses
:icons: font
:imagesdir: ../media/

[.lead]
You use the `system license` commands to manage feature licenses for the cluster. You use the `system feature-usage` commands to monitor feature usage.

[options="header"]
|===
| If you want to...| Use this command...
a|
Add one or more licenses
a|
`system license add`
a|
Display information about installed licenses, for example:

* License package name and description
* License type (`site`, `license`, or `demo`)
* Expiration date, if applicable
* The cluster or nodes that a package is licensed for
* Whether the license was installed prior to Data ONTAP 8.2 (`legacy`)
* Customer ID

a|
`system license show`
[NOTE]
====
Some information is displayed only when you use the `–instance` parameter.
====

a|
Display all packages that require licenses and their current license status, including the following:

* The package name
* The licensed method
* The expiration date, if applicable

a|
`system license status show`
a|
Delete the license of a package from the cluster or a node whose serial number you specify
a|
`system license delete`
a|
Display or remove expired or unused licenses
a|
`system license clean-up`
a|
Display summary of feature usage in the cluster on a per-node basis
a|
`system feature-usage show-summary`
a|
Display feature usage status in the cluster on a per-node and per-week basis
a|
`system feature-usage show-history`
a|
Display the status of license entitlement risk for each license package
a|
`system license entitlement-risk show`
[NOTE]
====
Some information is displayed only when you use the `-detail` and `-instance` parameters.
====

|===
.Related information

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands]
