---
permalink: system-admin/different-shells-cli-commands-concept-cluster-admin.html
sidebar: sidebar
keywords: diag, secd, different, shells, cli, commands, cluster, administrators, clustershell, nodeshell, systemshell, display, list, help
summary: "The cluster has three different shells for CLI commands, the clustershell, the nodeshell, and the systemshell. The shells are for different purposes, and they each have a different command set."
---
= About the different shells for CLI commands overview (cluster administrators only)
:icons: font
:imagesdir: ../media/

[.lead]
The cluster has three different shells for CLI commands, the _clustershell_, the _nodeshell_, and the _systemshell_. The shells are for different purposes, and they each have a different command set.
include::../_include/cli-shells.adoc[Different CLI command shells]

== Access of nodeshell commands and options in the clustershell

Nodeshell commands and options are accessible through the nodeshell:

`system node run –node _nodename_`

Many commonly used nodeshell commands and options are tunneled or aliased into the clustershell and can be executed also from the clustershell.

Nodeshell options that are supported in the clustershell can be accessed by using the `vserver options clustershell` command. To see these options, you can do one of the following:

* Query the clustershell CLI with `vserver options -vserver _nodename_or_clustername_ -option-name ?`
* Learn more about `vserver options` in the link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+options[ONTAP command reference^].

If you enter a nodeshell or legacy command or option in the clustershell, and the command or option has an equivalent clustershell command, ONTAP informs you of the clustershell command to use.

If you enter a nodeshell or legacy command or option that is not supported in the clustershell, ONTAP informs you of the "`not supported`" status for the command or option.

== Display available nodeshell commands

You can obtain a list of available nodeshell commands by using the CLI help from the nodeshell.

.Steps

. To access the nodeshell, enter the following command at the clustershell's system prompt:
+
`*system node run -node {_nodename_|local}*`
+
`local` is the node you used to access the cluster.
+
[NOTE]
====
The `system node run` command has an alias command, `run`.
====

. Enter the following command in the nodeshell to see the list of available nodeshell commands:
+
`*[_commandname_] help*`
+
`_commandname_` is the name of the command whose availability you want to display. If you do not include `_commandname_`, the CLI displays all available nodeshell commands.
+
You enter `exit` or type Ctrl-d to return to the clustershell CLI.

.Example of displaying available nodeshell commands

The following example accesses the nodeshell of a node named node2 and displays information for the nodeshell command `environment`:

----
cluster1::> system node run -node node2
Type 'exit' or 'Ctrl-D' to return to the CLI

node2> environment help
Usage: environment status |
     [status] [shelf [<adapter>[.<shelf-number>]]] |
     [status] [shelf_log] |
     [status] [shelf_stats] |
     [status] [shelf_power_status] |
     [status] [chassis [all | list-sensors | Temperature | PSU 1 |
     PSU 2 | Voltage | SYS FAN | NVRAM6-temperature-3 | NVRAM6-battery-3]]
----

// 2025 Feb 17, ONTAPDOC-2758
// 2023 Aug 22, ONTAPDOC-1135
