---
permalink: system-admin/different-shells-cli-commands-concept.html
sidebar: sidebar
keywords: diag, secd, different, shells, cli, commands, cluster, administrators, clustershell, nodeshell, systemshell
summary: "The cluster has three different shells for CLI commands, the clustershell, the nodeshell, and the systemshell. The shells are for different purposes, and they each have a different command set."
---
= About the different shells for CLI commands overview (cluster administrators only)
:icons: font
:imagesdir: ../media/

[.lead]
The cluster has three different shells for CLI commands, the _clustershell_, the _nodeshell_, and the _systemshell_. The shells are for different purposes, and they each have a different command set.

* The clustershell is the native shell that is started automatically when you log in to the cluster.
+
It provides all the commands you need to configure and manage the cluster. The clustershell CLI help (triggered by `?` at the clustershell prompt) displays available clustershell commands. The `man _command_name_` command in the clustershell displays the man page for the specified clustershell command.

* The nodeshell is a special shell for commands that take effect only at the node level.
+
The nodeshell is accessible through the `system node run` command.
+
The nodeshell CLI help (triggered by `?` or `help` at the nodeshell prompt) displays available nodeshell commands. The `man _command_name_` command in the nodeshell displays the man page for the specified nodeshell command.
+
Many commonly used nodeshell commands and options are tunneled or aliased into the clustershell and can be executed also from the clustershell.

* The systemshell is a low-level shell that is used only for diagnostic and troubleshooting purposes.
+
The systemshell and the associated "`diag`" account are intended for low-level diagnostic purposes. Their access requires the diagnostic privilege level and is reserved only for technical support to perform troubleshooting tasks.
