---
permalink: system-admin/index.html
sidebar: sidebar
keywords: system, administration, reference, overview, cluster, access, node, management, manage
summary: "This content describes how to administer ONTAP systems."
---
= System administration reference overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to administer ONTAP systems. It shows you how to use the CLI interface, how to access the cluster, how to manage nodes, and much more.

*You should use this content* under the following circumstances:

* You want to understand the range of ONTAP administrator capabilities.
* You want to use the command-line interface (CLI), not ONTAP System Manager or an automated scripting tool.

*If you want to use ONTAP System Manager* to administer your system, you should choose the following documentation:

* https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help/GUID-DF04A607-30B0-4B98-99C8-CB065C64E670.html[Cluster management using System Manager]

*If you require additional configuration or conceptual information*, you should choose among the following documentation:

* Conceptual background for clusters and SVMs
+
https://docs.netapp.com/us-en/ontap/concepts/index.html[ONTAP concepts]

* Administrator authentication and authorization
+
https://docs.netapp.com/us-en/ontap/authentication/index.html[Administrator authentication and RBAC]

* Network and LIF management
+
https://docs.netapp.com/us-en/ontap/networking/index.html[Network management]

* Command reference
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands]

* Automation of management tasks
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61550[NetApp Documentation: OnCommand Workflow Automation (current releases)]
