---
permalink: system-admin/license-types-licensed-method-concept.html
sidebar: sidebar
keywords: license, types, method, cluster, manage, install, add, nlf
summary: "Understanding license types and the licensed method helps you manage the licenses in a cluster."
---
= License types and licensed method
:icons: font
:imagesdir: ../media/

[.lead]
Understanding license types and the licensed method helps you manage the licenses in a cluster.

== License types

A package can have one or more of the following license types installed in the cluster. The `system license show` command displays the installed license type or types for a package.

* Standard license (`license`)
+
A standard license is a node-locked license. It is issued for a node with a specific system serial number (also known as a _controller serial number_). A standard license is valid only for the node that has the matching serial number.
+
Installing a standard, node-locked license entitles a node to the licensed functionality. For the cluster to use licensed functionality, at least one node must be licensed for the functionality. It might be out of compliance to use licensed functionality on a node that does not have an entitlement for the functionality.

* Site license (`site`)
+
A site license is not tied to a specific system serial number. When you install a site license, all nodes in the cluster are entitled to the licensed functionality. The `system license show` command displays site licenses under the cluster serial number.
+
If your cluster has a site license and you remove a node from the cluster, the node does not carry the site license with it, and it is no longer entitled to the licensed functionality. If you add a node to a cluster that has a site license, the node is automatically entitled to the functionality granted by the site license.

* Evaluation license (`demo`)
+
An evaluation license is a temporary license that expires after a certain period of time (indicated by the `system license show` command). It enables you to try certain software functionality without purchasing an entitlement. It is a cluster-wide license, and it is not tied to a specific serial number of a node.
+
If your cluster has an evaluation license for a package and you remove a node from the cluster, the node does not carry the evaluation license with it.

== Licensed method

It is possible to install both a cluster-wide license (the `site` or `demo` type) and a node-locked license (the `license` type) for a package. Therefore, an installed package can have multiple license types in the cluster. However, to the cluster, there is only one _licensed method_ for a package. The `licensed method` field of the `system license status show` command displays the entitlement that is being used for a package. The command determines the licensed method as follows:

* If a package has only one license type installed in the cluster, the installed license type is the licensed method.
* If a package does not have any licenses installed in the cluster, the licensed method is `none`.
* If a package has multiple license types installed in the cluster, the licensed method is determined in the following priority order of the license type--`site`, `license`, and `demo`.
+
For example:

 ** If you have a site license, a standard license, and an evaluation license for a package, the licensed method for the package in the cluster is `site`.
 ** If you have a standard license and an evaluation license for a package, the licensed method for the package in the cluster is `license`.
 ** If you have only an evaluation license for a package, the licensed method for the package in the cluster is `demo`.

// 2021-11-23, update keywords
