---
permalink: system-admin/manage-banner-reference.html
sidebar: sidebar
keywords: manage, banner, svm, cluster, configure
summary: "You can manage the banner at the cluster or SVM level and change how the banner is displayed"
---
= Manage the banner text displayed at the ONTAP cluster and SVM level
:icons: font
:imagesdir: ../media/

[.lead]
You can manage the banner at the cluster or SVM level. The banner configured for the cluster is also used for all SVMs that do not have a banner message defined. A subsequently created banner for an SVM overrides the cluster banner for that SVM.

.Choices

* Manage the banner at the cluster level:
+
[options="header"]
|===
| If you want to...| Then...
a|
Create a banner to display for all login sessions
a|
Set a cluster-level banner:

`security login banner modify -vserver <cluster_name> { [-message "text"] \| [-uri <ftp_or_http_addr>] }`
a|
Remove the banner for all (cluster and SVM) logins
a|
Set the banner to an empty string (`""`):

`security login banner modify -vserver * -message ""`
a|
Override a banner created by an SVM administrator
a|
Modify the SVM banner message:

`security login banner modify -vserver <svm_name> { [-message "<text>"] \| [-uri <ftp_or_http_addr>] }`
|===

* Manage the banner at the SVM level:
+
Specifying `-vserver <svm_name>` is not required in the SVM context.
+
[options="header"]
|===
| If you want to...| Then...
a|
Override the banner supplied by the cluster administrator with a different banner for the SVM
a|
Create a banner for the SVM:

`security login banner modify -vserver <svm_name> { [-message "text"] \| [-uri <ftp_or_http_addr>] }`
a|
Suppress the banner supplied by the cluster administrator so that no banner is displayed for the SVM
a|
Set the SVM banner to an empty string for the SVM:

`security login banner modify -vserver <svm_name> -message ""`
a|
Use the cluster-level banner when the SVM currently uses an SVM-level banner
a|
Set the SVM banner to `"-"`:

`security login banner modify -vserver <svm_name> -message "-"`
|===


.Related information
link:https://docs.netapp.com/us-en/ontap-cli/security-login-banner-modify.html[security login banner modify^]


// 2025 June 27, ONTAPDOC-2960
// 3-FEB-2025 GH-1618