---
permalink: system-admin/manage-cluster-time-concept.html
sidebar: sidebar
keywords: manage, cluster, time, administrator, ntp, network, time, protocol, zone
summary: "Problems can occur when the cluster time is inaccurate. Although ONTAP enables you to manually set the time zone, date, and time on the cluster, you should configure the Network Time Protocol (NTP) servers to synchronize the cluster time."
---
= Manage the cluster time (cluster administrators only)
:icons: font
:imagesdir: ../media/

[.lead]
Problems can occur when the cluster time is inaccurate. Although ONTAP enables you to manually set the time zone, date, and time on the cluster, you should configure the Network Time Protocol (NTP) servers to synchronize the cluster time.

Beginning with ONTAP 9.5, you can configure your NTP server with symmetric authentication.

NTP is always enabled. However, configuration is still required for the cluster to synchronize with an external time source. ONTAP enables you to manage the cluster's NTP configuration in the following ways:

* You can associate a maximum of 10 external NTP servers with the cluster (`cluster time-service ntp server create`).
 ** For redundancy and quality of time service, you should associate at least three external NTP servers with the cluster.
 ** You can specify an NTP server by using its IPv4 or IPv6 address or fully qualified host name.
 ** You can manually specify the NTP version (v3 or v4) to use.
+
By default, ONTAP automatically selects the NTP version that is supported for a given external NTP server.
+
If the NTP version you specify is not supported for the NTP server, time exchange cannot take place.

 ** At the advanced privilege level, you can specify an external NTP server that is associated with the cluster to be the primary time source for correcting and adjusting the cluster time.
* You can display the NTP servers that are associated with the cluster (`cluster time-service ntp server show`).
* You can modify the cluster's NTP configuration (`cluster time-service ntp server modify`).
* You can disassociate the cluster from an external NTP server (`cluster time-service ntp server delete`).
* At the advanced privilege level, you can reset the configuration by clearing all external NTP servers' association with the cluster (`cluster time-service ntp server reset`).

A node that joins a cluster automatically adopts the NTP configuration of the cluster.

In addition to using NTP, ONTAP also enables you to manually manage the cluster time. This capability is helpful when you need to correct erroneous time (for example, a node's time has become significantly incorrect after a reboot). In that case, you can specify an approximate time for the cluster until NTP can synchronize with an external time server. The time you manually set takes effect across all nodes in the cluster.

You can manually manage the cluster time in the following ways:

* You can set or modify the time zone, date, and time on the cluster (`cluster date modify`).
* You can display the current time zone, date, and time settings of the cluster (`cluster date show`).

[NOTE]
====
Job schedules do not adjust to manual cluster date and time changes. These jobs are scheduled to run based on the current cluster time when the job was created or when the job most recently ran. Therefore, if you manually change the cluster date or time, you must use the `job show` and `job history show` commands to verify that all scheduled jobs are queued and completed according to your requirements.
====

== Commands for managing the cluster time

You use the `cluster time-service ntp server` commands to manage the NTP servers for the cluster. You use the `cluster date` commands to manage the cluster time manually.

Beginning with ONTAP 9.5, you can configure your NTP server with symmetric authentication.

The following commands enable you to manage the NTP servers for the cluster:

[options="header"]
|===
| If you want to...| Use this command...
a|
Associate the cluster with an external NTP server without symmetric authentication
a|
`cluster time-service ntp server create -server server_name`
a|
Associate the cluster with an external NTP server with symmetric authenticationAvailable in ONTAP 9.5 or later

a|
`cluster time-service ntp server create -server server_ip_address -key-id key_id`
[NOTE]
====
The `key_id` must refer to an existing shared key configured with '`cluster time-service ntp key'.
====

a|
Enable symmetric authentication for an existing NTP serverAn existing NTP server can be modified to enable authentication by adding the required key-id.

Available in ONTAP 9.5 or later

a|
`cluster time-service ntp server modify -server server_name -key-id key_id`
a|
Disable symmetric authentication
a|
`cluster time-service ntp server modify -server server_name -is-authentication-enabled false`
a|
Configure a shared NTP key
a|
`cluster time-service ntp key create -id shared_key_id -type shared_key_type -value shared_key_value`
[NOTE]
====
Shared keys are referred to by an ID. The ID, its type, and value must be identical on both the node and the NTP server
====

a|
Display information about the NTP servers that are associated with the cluster
a|
`cluster time-service ntp server show`
a|
Modify the configuration of an external NTP server that is associated with the cluster
a|
`cluster time-service ntp server modify`
a|
Dissociate an NTP server from the cluster
a|
`cluster time-service ntp server delete`
a|
Reset the configuration by clearing all external NTP servers' association with the cluster
a|
`cluster time-service ntp server reset`
[NOTE]
====
This command requires the advanced privilege level.
====

|===
The following commands enable you to manage the cluster time manually:

[options="header"]
|===
| If you want to...| Use this command...
a|
Set or modify the time zone, date, and time
a|
`cluster date modify`
a|
Display the time zone, date, and time settings for the cluster
a|
`cluster date show`
|===
.Related information

https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html[ONTAP command reference]

// 2024 Feb 23, Jira 1790
// BURT 1426046, 2023 Jun 30