---
permalink: system-admin/manage-core-dumps-concept.html
sidebar: sidebar
keywords: manage, core, dump, cluster, administrator, node, panic, configure, attributes, save, display, segment, upload, delete
summary: "When a node panics, a core dump occurs and the system creates a core dump file that technical support can use to troubleshoot the problem. You can configure or display core dump attributes. You can also save, display, segment, upload, or delete a core dump file."
---
= Manage core dumps (cluster administrators only)
:icons: font
:imagesdir: ../media/

[.lead]
When a node panics, a core dump occurs and the system creates a core dump file that technical support can use to troubleshoot the problem. You can configure or display core dump attributes. You can also save, display, segment, upload, or delete a core dump file.

You can manage core dumps in the following ways:

* Configuring core dumps and displaying the configuration settings
* Displaying basic information, the status, and attributes of core dumps
+
Core dump files and reports are stored in the `/mroot/etc/crash/` directory of a node. You can display the directory content by using the `system node coredump` commands or a web browser.

* Saving the core dump content and uploading the saved file to a specified location or to technical support
+
ONTAP prevents you from initiating the saving of a core dump file during a takeover, an aggregate relocation, or a giveback.

* Deleting core dump files that are no longer needed

// 1 may 2023, BURT 132950