---
permalink: system-admin/manage-ssl-concept.html
sidebar: sidebar
keywords: manage, command, ssl, cluster, storage, svm, security, web, access, digital, certificate, encrypted, connection, server, browser
summary: "Use ssl commands to manage SSL protocol to improve web access security using a digital certificate to establish an encrypted connection."
---
= Manage SSL
:icons: font
:imagesdir: ../media/

[.lead]
Use the `security ssl` commands to manage the SSL protocol for the cluster or a storage virtual machine (SVM). SSL protocol improves the security of web access by using a digital certificate to establish an encrypted connection between a web server and a browser.

You can manage SSL for the cluster or a storage virtual machine (SVM) in the following ways:

* Enabling SSL
* Generating and installing a digital certificate and associating it with the cluster or SVM
* Displaying the SSL configuration to see whether SSL has been enabled, and, if available, the SSL certificate name
* Setting up firewall policies for the cluster or SVM, so that web access requests can go through
* Defining which SSL versions can be used
* Restricting access to only HTTPS requests for a web service

== Commands for managing SSL

You use the `security ssl` commands to manage the SSL protocol for the cluster or a storage virtual machine (SVM).

[options="header"]
|===
| If you want to...| Use this command...
a|
Enable SSL for the cluster or an SVM, and associate a digital certificate with it
a|
`security ssl modify`
a|
Display the SSL configuration and certificate name for the cluster or an SVM
a|
`security ssl show`
|===