---
permalink: system-admin/methods-navigating-cli-command-directories-concept.html
sidebar: sidebar
keywords: method, navigating, cli, command, directories, hierarchy, path, structure
summary: "Commands in the CLI are organized into a hierarchy by command directories. You can run commands in the hierarchy either by entering the full command path or by navigating through the directory structure."
---
= How to navigate through ONTAP CLI command directories
:icons: font
:imagesdir: ../media/

[.lead]
Commands in the CLI are organized into a hierarchy by command directories. You can run commands in the hierarchy either by entering the full command path or by navigating through the directory structure.

When using the CLI, you can access a command directory by typing the directory's name at the prompt and then pressing Enter. The directory name is then included in the prompt text to indicate that you are interacting with the appropriate command directory. To move deeper into the command hierarchy, you type the name of a command subdirectory followed by pressing Enter. The subdirectory name is then included in the prompt text and the context shifts to that subdirectory.

You can navigate through several command directories by entering the entire command. For example, you can display information about disk drives by entering the `storage disk show` command at the prompt. You can also run the command by navigating through one command directory at a time, as shown in the following example:

----
cluster1::> storage
cluster1::storage> disk
cluster1::storage disk> show
----

You can abbreviate commands by entering only the minimum number of letters in a command that makes the command unique to the current directory. For example, to abbreviate the command in the previous example, you can enter `st d sh`. You can also use the Tab key to expand abbreviated commands and to display a command's parameters, including default parameter values.

You can use the `top` command to go to the top level of the command hierarchy, and the `up` command or `..` command to go up one level in the command hierarchy.

[NOTE]
====
Commands and command options preceded by an asterisk (*) in the CLI can be executed only at the advanced privilege level or higher.
====
