---
permalink: system-admin/methods-extended-queries-concept.html
sidebar: sidebar
keywords: method, extended, queries, operations, perform, specified, values
summary: "You can use extended queries to match and perform operations on objects that have specified values."
---
= Use extended queries with modify and delete commands in the ONTAP CLI
:icons: font
:imagesdir: ../media/

[.lead]
You can use extended queries to match and perform operations on objects that have specified values.

You specify extended queries by enclosing them within curly brackets ({}). An extended query must be specified as the first argument after the command name, before any other parameters. For example, to set offline all volumes whose names include the string `tmp`, you run the command in the following example:

----
cluster1::> volume modify {-volume *tmp*} -state offline
----

Extended queries are generally useful only with `modify` and `delete` commands. They have no meaning in `create` or `show` commands.

The combination of queries and modify operations is a useful tool. However, it can potentially cause confusion and errors if implemented incorrectly. For example, using the (advanced privilege) `system node image modify` command to set a node's default software image automatically sets the other software image not to be the default. The command in the following example is effectively a null operation:

----
cluster1::*> system node image modify {-isdefault true} -isdefault false
----

This command sets the current default image as the non-default image, then sets the new default image (the previous non-default image) to the non-default image, resulting in the original default settings being retained. To perform the operation correctly, you can use the command as given in the following example:

----
cluster1::*> system node image modify {-iscurrent false} -isdefault true
----
