---
permalink: system-admin/modify-node-attributes-task.html
sidebar: sidebar
keywords: modify, node, attributes, owner, information, location, asset, tag, eligibility, cluster
summary: "You can modify the attributes of a node as required. The attributes that you can modify include the node’s owner information, location information, asset tag, and eligibility to participate in the cluster."
---
= Modify the attributes of a node in an ONTAP cluster
:icons: font
:imagesdir: ../media/

[.lead]
You can modify the attributes of a node as required. The attributes that you can modify include the node's owner information, location information, asset tag, and eligibility to participate in the cluster.

.About this task

A node's eligibility to participate in the cluster can be modified at the advanced privilege level by using the `–eligibility` parameter of the `system node modify` or `cluster modify` command. If you set a node's eligibility to `false`, the node becomes inactive in the cluster.

[NOTE]
====
You cannot modify node eligibility locally. It must be modified from a different node. Node eligiblity also cannot be modified with a cluster HA configuration.
====

[NOTE]
====
You should avoid setting a node's eligibility to `false`, except for situations such as restoring the node configuration or prolonged node maintenance. SAN and NAS data access to the node might be impacted when the node is ineligible.
====

.Steps

. Use the `system node modify` command to modify a node's attributes.

.Example of modifying node attributes

The following command modifies the attributes of the "`node1`" node. The node's owner is set to "`Joe Smith`" and its asset tag is set to "`js1234`":

----
cluster1::> system node modify -node node1 -owner "Joe Smith" -assettag js1234
----
