---
permalink: system-admin/modify-cluster-attributes-task.html
sidebar: sidebar
keywords: modify, cluster, attributes, name, location, contact, information
summary: "You can modify a cluster’s attributes, such as the cluster name, location, and contact information as needed."
---
= Modify cluster attributes
:icons: font
:imagesdir: ../media/

[.lead]
You can modify a cluster's attributes, such as the cluster name, location, and contact information as needed.

.About this task

You cannot change a cluster's UUID, which is set when the cluster is created.

.Steps

. To modify cluster attributes, use the `cluster identity modify` command.
+
The `-name` parameter specifies the name of the cluster. Learn more about `cluster identity modify` and the rules for specifying the cluster's name in the link:https://docs.netapp.com/us-en/ontap-cli/cluster-identity-modify.html[ONTAP command reference^].
+
The `-location` parameter specifies the location for the cluster.
+
The `-contact` parameter specifies the contact information such as a name or e-mail address.

.Example of renaming a cluster

The following command renames the current cluster ("`cluster1`") to "`cluster2`":

----
cluster1::> cluster identity modify -name cluster2
----

// 2025 Feb 17, ONTAPDOC-2758