---
permalink: system-admin/node-cluster-config-backed-up-automatically-concept.html
sidebar: sidebar
keywords: node, cluster, configuration, backup, up, automatically
summary: "Three separate schedules automatically create cluster and node configuration backup files and replicate them among the nodes in the cluster."
---
= How the node and cluster configurations are backed up automatically
:icons: font
:imagesdir: ../media/

[.lead]
Three separate schedules automatically create cluster and node configuration backup files and replicate them among the nodes in the cluster.

The configuration backup files are automatically created according to the following schedules:

* Every 8 hours
* Daily
* Weekly

At each of these times, a node configuration backup file is created on each healthy node in the cluster. All of these node configuration backup files are then collected in a single cluster configuration backup file along with the replicated cluster configuration and saved on one or more nodes in the cluster.

For single-node clusters (including Data ONTAP Edge systems), you can specify the configuration backup destination during software setup. After setup, those settings can be modified using ONTAP commands.
