---
permalink: system-admin/online-help-at-sp-bmc-cli-task.html
sidebar: sidebar
keywords: online, help, sp, bmc, cli, command
summary: "The online help displays the SP/BMC CLI commands and options."
---
= View the help information in the ONTAP SP/BMC CLI
:icons: font
:imagesdir: ../media/

[.lead]
The online help displays the SP/BMC CLI commands and options.

.About this task

This task applies to both the SP and the BMC.

.Steps

. To display help information for the SP/BMC commands, enter the following:
+
[options="header"]
|===
| To access SP help...| To access BMC help...
a|
Type `help` at the SP prompt.
a|
Type `system` at the BMC prompt.
|===
+
The following example shows the SP CLI online help.
+
----
SP> help
date - print date and time
exit - exit from the SP command line interface
events - print system events and event information
help - print command help
priv - show and set user mode
sp - commands to control the SP
system - commands to control the system
version - print SP version
----
+
The following example shows the BMC CLI online help.
+
----
BMC> system
system acp - acp related commands
system battery - battery related commands
system console - connect to the system console
system core - dump the system core and reset
system cpld - cpld commands
system log - print system console logs
system power - commands controlling system power
system reset - reset the system using the selected firmware
system sensors - print environmental sensors status
system service-event - print service-event status
system fru - fru related commands
system watchdog - system watchdog commands

BMC>
----

. To display help information for the option of an SP/BMC command, enter `help` before or after the SP/BMC command.
+
The following example shows the SP CLI online help for the SP `events` command.
+
----
SP> help events
events all - print all system events
events info - print system event log information
events newest - print newest system events
events oldest - print oldest system events
events search - search for and print system events
----
+
The following example shows the BMC CLI online help for the BMC `system power` command.
+
----
BMC> system power help
system power cycle - power the system off, then on
system power off - power the system off
system power on - power the system on
system power status - print system power status

BMC>
----

Learn more about the commands described in this procedure in the link:https://docs.netapp.com/us-en/ontap-cli/[ONTAP command reference^].

.Related information
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=events[events^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+power[system power^]

// 2025 Apr 23, ONTAPDOC-2960
// 2025 Apr 10, ONTAPDOC-2758
// 2022-01-10, BURT 1416674 
