---
permalink: system-admin/ontap-implements-audit-logging-concept.html
sidebar: sidebar
keywords: ontap, implement, audit, logging, management, autosupport, ems, messages, log, cli, web, browser
summary: "Management activities recorded in the audit log are included in standard AutoSupport reports, and certain logging activities are included in EMS messages. You can also forward the audit log to destinations that you specify, and you can display audit log files by using the CLI or a web browser."
---
= How ONTAP implements audit logging
:icons: font
:imagesdir: ../media/

[.lead]
Management activities recorded in the audit log are included in standard AutoSupport reports, and certain logging activities are included in EMS messages. You can also forward the audit log to destinations that you specify, and you can display audit log files by using the CLI or a web browser.

Beginning with ONTAP 9.11.1, you can display audit log contents using System Manager.

Beginning with ONTAP 9.12.1, ONTAP provides tampering alerts for audit logs. ONTAP runs a daily background job to check for tampering of audit.log files and sends an EMS alert if it finds any log files that have been changed or tampered with.

ONTAP logs management activities that are performed on the cluster, for example, what request was issued, the user who triggered the request, the user's access method, and the time of the request.

The management activities can be one of the following types:

* SET requests, which typically apply to non-display commands or operations
 ** These requests are issued when you run a `create`, `modify`, or `delete` command, for instance.
 ** Set requests are logged by default.
* GET requests, which retrieve information and display it in the management interface
 ** These requests are issued when you run a `show` command, for instance.
 ** GET requests are not logged by default, but you can control whether GET requests sent from the ONTAP CLI (`-cliget`), from the ONTAP API (`-ontapiget`), or from the REST API (`-httpget`) are logged in the file.

ONTAP records management activities in the `/mroot/etc/log/mlog/audit.log` file of a node. Commands from the three shells for CLI commands--the clustershell, the nodeshell, and the non-interactive systemshell (interactive systemshell commands are not logged)--as well as API commands are logged here. Audit logs include timestamps to show whether all nodes in a cluster are time synchronized.

The `audit.log` file is sent by the AutoSupport tool to the specified recipients. You can also forward the content securely to external destinations that you specify; for example, a Splunk or a syslog server.

The `audit.log` file is rotated daily. The rotation also occurs when it reaches 100 MB in size, and the previous 48 copies are preserved (with a maximum total of 49 files). When the audit file performs its daily rotation, no EMS message is generated. If the audit file rotates because its file size limit is exceeded, an EMS message is generated.


// 2023-June-5, ONTAPDOC-1054
// 2022 Nov 4, Jira Jira ONTAPDOC-651, ONTAPDOC-653 
// 2022 Apr 11, jira-481
