---
permalink: system-admin/ontap-commands-bmc-management-reference.html
sidebar: sidebar
keywords: ontap, command, bmc, management, baseboard, controller
summary: "These ONTAP commands are supported on the Baseboard Management Controller (BMC)."
---
= ONTAP commands for BMC management
:icons: font
:imagesdir: ../media/

[.lead]
These ONTAP commands are supported on the Baseboard Management Controller (BMC).

The BMC uses some of the same commands as the Service Processor (SP). The following SP commands are supported on the BMC.

[options="header"]
|===
| If you want to...| Use this command
a|
Display the BMC information
a|
`*system service-processor show*`
a|
Display/modify the BMC network configuration
a|
`*system service-processor network show/modify*`
a|
Reset the BMC
a|
`*system service-processor reboot-sp*`
a|
Display/modify the details of the currently installed BMC firmware image
a|
`*system service-processor image show/modify*`
a|
Update BMC firmware
a|
`*system service-processor image update*`
a|
Display the status for the latest BMC firmware update
a|
`*system service-processor image update-progress show*`
a|
Enable the automatic network configuration for the BMC to use an IPv4 or IPv6 address on the specified subnet
a|
`*system service-processor network auto-configuration enable*`
a|
Disable the automatic network configuration for an IPv4 or IPv6 address on the subnet specified for the BMC
a|
`*system service-processor network auto-configuration disable*`
a|
Display the BMC automatic network configuration
a|
`*system service-processor network auto-configuration show*`
|===
For commands that are not supported by the BMC firmware, the following error message is returned.

----
::> Error: Command not supported on this platform.
----

.Related Information
Learn more about the commands described in this procedure in the link:https://docs.netapp.com/us-en/ontap-cli/[ONTAP command reference^].

// 2025 Feb 21, ONTAPDOC-2758