---
permalink: system-admin/receive-system-health-alerts-automatic-task.html
sidebar: sidebar
keywords: receive, system, health, alert, automatically, system, show, command, ems, event, management, monito
summary: "You can manually view system health alerts by using the system health alert show command. However, you should subscribe to specific Event Management System (EMS) messages to automatically receive notifications when a health monitor generates an alert."
---
= Receive system health alerts automatically
:icons: font
:imagesdir: ../media/

[.lead]
You can manually view system health alerts by using the `system health alert show` command. However, you should subscribe to specific Event Management System (EMS) messages to automatically receive notifications when a health monitor generates an alert.

.About this task

The following procedure shows you how to set up notifications for all hm.alert.raised messages and all hm.alert.cleared messages.

All hm.alert.raised messages and all hm.alert.cleared messages include an SNMP trap. The names of the SNMP traps are `HealthMonitorAlertRaised` and `HealthMonitorAlertCleared`. For information about SNMP traps, see the _Network Management Guide_.

.Steps

. Use the `event destination create` command to define the destination to which you want to send the EMS messages.
+
----
cluster1::> event destination create -name health_alerts -mail admin@example.com
----

. Use the `event route add-destinations` command to route the `hm.alert.raised` message and the `hm.alert.cleared` message to a destination.
+
----
cluster1::> event route add-destinations -messagename hm.alert* -destinations health_alerts
----

.Related information

link:../networking/networking_reference.html[Network management]
