---
permalink: system-admin/structure-autosupport-messages-sent-email-concept.html
sidebar: sidebar
keywords: structure, autosupport, messages, sent, email, subject, standard, brief, body, large, attachment, 7z, file, data
summary: "When an AutoSupport message is sent by email, the message has a standard subject, a brief body, and a large attachment in 7z file format that contains the data."
---
= Learn about the structure of ONTAP AutoSupport messages sent by email
:icons: font
:imagesdir: ../media/

[.lead]
When an AutoSupport message is sent by email, the message has a standard subject, a brief body, and a large attachment in 7z file format that contains the data.

[NOTE]
====
If AutoSupport is configured to hide private data, certain information, such as the hostname, is omitted or masked in the header, subject, body, and attachments.
====

== Subject

The subject line of messages sent by the AutoSupport mechanism contains a text string that identifies the reason for the notification. The format of the subject line is as follows:

HA Group Notification from _System_Name_ (_Message_) _Severity_

* _System_Name_ is either the hostname or the system ID, depending on the AutoSupport configuration

== Body

The body of the AutoSupport message contains the following information:

* Date and timestamp of the message
* Version of ONTAP on the node that generated the message
* System ID, serial number, and hostname of the node that generated the message
* AutoSupport sequence number
* SNMP contact name and location, if specified
* System ID and hostname of the HA partnernode

== Attached files

The key information in an AutoSupport message is contained in files that are compressed into a 7z file called `body.7z` and attached to the message.

The files contained in the attachment are specific to the type of AutoSupport message.
