---
permalink: system-admin/system-health-monitoring-concept.html
sidebar: sidebar
keywords: monitor, health, system, cluster, conditions, alert, fault, risk, degraded, status, active
summary: "Health monitors proactively monitor certain critical conditions in your cluster and raise alerts if they detect a fault or risk. If there are active alerts, the system health status reports a degraded status for the cluster. The alerts include the information that you need to respond to degraded system health."
---
= Learn about ONTAP system health monitoring
:icons: font
:imagesdir: ../media/

[.lead]
Health monitors proactively monitor certain critical conditions in your cluster and raise alerts if they detect a fault or risk. If there are active alerts, the system health status reports a degraded status for the cluster. The alerts include the information that you need to respond to degraded system health.

If the status is degraded, you can view details about the problem, including the probable cause and recommended recovery actions. After you resolve the problem, the system health status automatically returns to OK.

The system health status reflects multiple separate health monitors. A degraded status in an individual health monitor causes a degraded status for the overall system health.

For details on how ONTAP supports cluster switches for system health monitoring in your cluster, you can refer to the _Hardware Universe_.

https://hwu.netapp.com/SWITCH/INDEX[Supported switches in the Hardware Universe^]

For details on the causes of Cluster Switch Health Monitor (CSHM) AutoSupport messages, and the necessary actions required to resolve these alerts, you can refer to the Knowledgebase article.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/AutoSupport_Message%3A_Health_Monitor_Process_CSHM[AutoSupport Message: Health Monitor Process CSHM]
