---
permalink: system-admin/troubleshoot-autosupport-messages-not-received-task.html
sidebar: sidebar
keywords: troubleshoot, autosupport, messagem receive, deliver, generate
summary: "If the system does not send the AutoSupport message, you can determine whether that is because AutoSupport cannot generate the message or cannot deliver the message."
---
= Troubleshoot ONTAP AutoSupport when messages are not received
:icons: font
:imagesdir: ../media/

[.lead]
If the system does not send the AutoSupport message, you can determine whether that is because AutoSupport cannot generate the message or cannot deliver the message.

.Steps

. Check delivery status of the messages by using the `system node autosupport history show` command.
. Read the status.
+
[cols="25,75",options="header"]
|===
| This status| Means
a|
initializing
a|
The collection process is starting. If this state is temporary, all is well. However, if this state persists, there is an issue.
a|
collection-failed
a|
AutoSupport cannot create the AutoSupport content in the spool directory. You can view what AutoSupport is trying to collect by entering the `system node autosupport history show -detail` command.
a|
collection-in-progress
a|
AutoSupport is collecting AutoSupport content. You can view what AutoSupport is collecting by entering the `system node autosupport manifest show` command.
a|
queued
a|
AutoSupport messages are queued for delivery, but not yet delivered.
a|
transmitting
a|
AutoSupport is currently delivering messages.
a|
sent-successful
a|
AutoSupport successfully delivered the message. You can find out where AutoSupport delivered the message by entering the `system node autosupport history show -delivery` command.
a|
ignore
a|
AutoSupport has no destinations for the message. You can view the delivery details by entering the `system node autosupport history show -delivery` command.
a|
re-queued
a|
AutoSupport tried to deliver messages, but the attempt failed. As a result, AutoSupport placed the messages back in the delivery queue for another attempt. You can view the error by entering the `system node autosupport history show` command.
a|
transmission-failed
a|
AutoSupport failed to deliver the message the specified number of times and stopped trying to deliver the message. You can view the error by entering the `system node autosupport history show` command.
a|
ondemand-ignore
a|
The AutoSupport message was processed successfully, but the AutoSupport OnDemand service chose to ignore it.
|===

. Perform one of the following actions:
+
[options="header"]
|===
| For this status| Do this
a|
initializing or collection-failed
a|
Contact NetApp Support, because AutoSupport cannot generate the message. Mention the following Knowledge Base article:

link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/AutoSupport_is_failing_to_deliver%3A_status_is_stuck_in_initializing[AutoSupport is failing to deliver: status is stuck in initializing^]
a|
ignore, re-queued, or transmission failed
a|
Check that destinations are correctly configured for SMTP, HTTP, or HTTPS because AutoSupport cannot deliver the message.
|===

// 2022-06-27, BURT 1485042
