---
permalink: system-admin/use-hsts-task.html
sidebar: sidebar
keywords: manage, http, https, hsts, strict transport security, security, web, access, certificate, encrypted, connection, server, browser, web services
summary: "Use HSTS to enforce HTTPS connections for ONTAP web services."
---
= Use HSTS for ONTAP web services
:icons: font
:imagesdir: ../media/

[.lead]
HTTP Strict Transport Security (HSTS) is a web security policy mechanism that helps protect websites against man-in-the-middle attacks such as protocol downgrade attacks and cookie hijacking. By enforcing the use of HTTPS, HSTS ensures that all communications between the user's browser and the server are encrypted. You can enable HSTS and enforce HTTPS connections for ONTAP web services.

NOTE: HSTS is enforced by the web browser only after an initial secure HTTPS connection is established with ONTAP. If the browser does not establish an initial secure connection, HSTS will not be enforced. Reference your browser documentation for information on HSTS management.

.About this task
* HSTS support was introduced in ONTAP 9.17.1.
* For 9.17.1 and above, HSTS is enabled by default for newly installed ONTAP clusters.
//* HSTS is supported for all ONTAP web services.

.Before you begin
* Advanced privileges are required for this task.

== Show HSTS configuration
You can show the current HSTS configuration to check if it is enabled and view the max age setting.

.Steps
. Use the `system services web show` command to show the current web services configuration, including HSTS settings:
+
----
cluster-1::system services web*> show

                   External Web Services: true
                               HTTP Port: 80
                              HTTPS Port: 443
                         Protocol Status: online
                       Per Address Limit: 80
                     Wait Queue Capacity: 192
                            HTTP Enabled: true
                 CSRF Protection Enabled: true
Maximum Number of Concurrent CSRF Tokens: 500
       CSRF Token Idle Timeout (Seconds): 900
   CSRF Token Absolute Timeout (Seconds): 0
          Allow Web Management via Cloud: true
Enforce Network Interface Service-Policy: -
                            HSTS Enabled: true
                  HSTS max age (Seconds): 63072000
----

== Enable HSTS and set the max age
You can enable HSTS and set the max age. You can change the max age at any time if HSTS is enabled.

.Steps
. Use the `system services web modify` command to enable HSTS and/or modify the max age:
+
[source,cli]
----
system services web modify -hsts-enabled true -hsts-max-age <seconds>
----
`-hsts-max-age` specifies the duration in seconds for which the browser will remember to enforce HTTPS. The default value is 63072000 seconds (two years).

== Safely disable HSTS

Follow this procedure to disable HSTS. Browsers save the HSTS max age setting with each connection, and will continue to enforce HSTS for the entire duration even if HSTS is disabled on ONTAP. If a certificate error occurs and secure connection is not possible, the browser will block access to ONTAP until the max age expires regardless of the current ONTAP HSTS setting.

.Steps 
. Check the current HSTS max age setting using the `system services web show` command. Note this duration for later.
. Set the HSTS max age to 0 using the `system services web modify` command:
+
[source,cli]
----
system services web modify -hsts-max-age 0
----
. Wait until the original max age duration, noted in step one, has passed. This may take a while, depending on the original max age setting.
. After the original max age expires, disable HSTS using the `system services web modify` command:
+
[source,cli]
----
system services web modify -hsts-enabled false
----

.Related information
link:https://datatracker.ietf.org/doc/html/rfc6797[RFC 6797 - HTTP Strict Transport Security (HSTS)^]

//4-15-25 ONTAPDOC-2930