---
permalink: system-admin/view-default-certificates-tls-based-applications-task.html
sidebar: sidebar
keywords: view, default, certificates, tls, applications, transport
summary: "ONTAP provides a default set of trusted root certificates for ONTAP applications using Transport Layer Security (TLS)."
---
= View default certificates for TLS-based applications in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP provides a default set of trusted root certificates for ONTAP applications using Transport Layer Security (TLS).

.Before you begin

The default certificates are installed only on the admin SVM during its creation, or during an upgrade.

.About this task

The current applications that act as a client and require certificate validation are AutoSupport, EMS, LDAP, Audit Logging, FabricPool, and KMIP.

When certificates expire, an EMS message is invoked that requests the user to delete the certificates. The default certificates can only be deleted at the advanced privilege level.

[NOTE]
====
Deleting the default certificates may result in some ONTAP applications not functioning as expected (for example, AutoSupport and Audit Logging).
====

.Step

. You can view the default certificates that are installed on the admin SVM by using the security certificate show command:
+
`*security certificate show -vserver –type server-ca*`
+
----
cluster1::> security certificate show

Vserver    Serial Number   Certificate Name                          Type
---------- --------------- ----------------------------------------- ---------
vs0        4F4E4D7B         www.example.com                            server
    Certificate Authority:  www.example.com
          Expiration Date: Thu Feb 28 16:08:28 2013
----
+
Learn more about `security certificate show` in the link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-show.html?q=show[ONTAP command reference^].

// 2025 July 3, ONTAPDOC-2616
// 2025 June 03, ONTAPDOC-2960
// 2024, Dec 04, ONTAPDOC-2579