---
permalink: authentication/configure-jit-elevation-task.html
sidebar: sidebar
keywords: just in time, just-in-time, privilege elevation, password, security, authentication, JIT, elevation
summary: "Configure just-in-time privilege elevation to allow ONTAP users to temporarily elevate their privileges to perform certain tasks."
---
= Configure JIT privilege elevation in ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.17.1, cluster administrators can configure just-in-time (JIT) privilege elevation to allow ONTAP users to temporarily elevate their privileges to perform certain tasks. When JIT is configured for a user, they can temporarily link:elevate-jit-access-task.html[elevate their privilege] to a role that has the necessary permissions to perform a task. After the session duration expires, the user returns to their original role.

Cluster administrators can configure the duration for which a user can access JIT elevation. For example, you can configure user access to JIT elevation with a 30 minute per-session limit for a 30 day period. During the 30 day period, the user can elevate their privilege as many times as needed, but each session is limited to 30 minutes.

Cluster administrators can set up JIT access for ONTAP admin accounts, and configure default JIT session duration and maximum JIT access duration globally and for individual SVMs. When JIT privilege elevation is configured for a user, they can independently access the configured elevated role for the configured session duration. The elevated privilege is only available within the user's current SSH session, but they can elevate privileges within as many concurrent SSH sessions as needed.

.About this task
* JIT privilege elevation is only available to users accessing ONTAP with SSH.
* JIT privilege elevation is only supported for users using password authentication to login.

.Before you begin
* You must be an ONTAP cluster administrator at the `admin` privilege level to perform the following tasks.

== Modify global JIT settings
You can modify the default JIT settings globally or for a specific SVM. These settings determine the default and maximum JIT durations for users who are given JIT access. You can configure the JIT duration for individual users, but it cannot exceed the configured maximum JIT duration.

.About this task
* The default `default-session-validity-period` is one hour. This setting determines the default for which the user can access the elevated role before needing to re-elevate.
* The default `max-jit-validity-period` is 90 days. This setting determines the maximum duration for which a user can access JIT elevation after the configured start date.

.Steps

. Check the current JIT settings:
+
[source, cli]
----
security jit-privilege show -vserver <svm_name>
----
`-versever` is optional. If you don't specify a SVM, the command shows the global JIT settings.

. Modify the JIT settings globally or for an SVM:
+
[source, cli]
----
security jit-privilege modify -vserver <svm_name> -default-session-validity-period <period> -max-jit-validity-period <period>
----
If you don't specify a SVM, the command modifies the global JIT settings. The following example will set the default JIT session duration to 45 minutes and the maximum JIT duration to 30 days for SVM `svm1`: +
`security jit-privilege modify -vserver svm1 -default-session-validity-period 45m -max-jit-validity-period 30d`


== Configure JIT privilege elevation access for a user
You can assign JIT privilege elevation access for ONTAP users. 

.Steps

. Check the current JIT access for a user:
+
[source, cli]
----
security jit-privilege user show -username <username>
----
`-username` is optional. If you don't specify a username, the command shows the JIT access for all users.

. Assign new JIT access for a user:
+
[source, cli]
----
security jit-privilege create -username <username> -vserver <svm_name> -role <rbac_role> -session-validity-period <period> -jit-validity-period <period> -start-time <date>
----
* If `-vserver` is not specified, the JIT access is assigned at the cluster level.
* `-role` is the RBAC role that the user will be elevated to. If not specified, defaults to `admin`.
* `-session-validity-period` is the duration for which the user can access the elevated role before needing to re-elevate. If not specified, the global or SVM `default-session-validity-period` period is used.
* `-jit-validity-period` is the maximum duration for which a user can access JIT elevation after the configured start date. If not specified, the `session-validity-period` is used. This parameter cannot exceed the global or SVM `max-jit-validity-period`.
* `-start-time` is the date and time when the JIT access begins. If not specified, the current date and time is used.
The following example will allow `ontap_user` to access the `admin` role for 1 hour before needing to re-elevate. `ontap_user` will be able to temporarily elevate their privilege for the next 60 days, starting immediately:
`security jit-privilege user create -username ontap_user -role admin -session-validity-period 1h -jit-validity-period 60d`

. If needed, revoke a user's JIT access:
+
[source, cli]
----
security jit-privilege user delete -username <username> -vserver <svm_name>
----
This command will revoke a user's JIT access, even if their access has not expired. If `-vserver` is not specified, the JIT access is revoked at the cluster level.

//4-30-25 ontapdoc-2712