---
permalink: authentication/configure-dynamic-authorization.html
sidebar: sidebar
keywords: dynamic, authorization, framework, security, login, ssh
summary: "Configure the Dynamic Authorization Framework to increase security of SSH logins and execution of certain commands under suspicious circumstances."
---
= Configure Dynamic Authorization
:icons: font
:imagesdir: ../media/

[.lead]
As an administrator, you can configure Dynamic Authorization to increase the security of remote administrator connections to ONTAP.

.Before you begin

.About this task

== Configure Dynamic Authorization global settings
You can configure global settings for Dynamic Authorization such as the storage VM to secure and the suppression interval for authentication challenges.

== Configure Dynamic Authorization trust score global settings
You can configure the trust score maximum score weight to change priority of scoring criteria or to remove certain criteria from risk scoring.

The default raw score weights and percentage weights are the following:
[cols="3*"]
|===
h|Criteria h|Default raw score weight h|Default percentage weight

|Geolocation
|20
|20

|Access time
|20
|20

|Trusted device
|20
|20

|User login authentication history
|20
|20

|History of user authorization failures
|20
|20

|Total score
|100
|100

|===

=== Reset the trust score for a user
If a user is denied access due to system policies and is able to prove their identity, the administrator can use reset the user's trust score. 

=== Display your own trust score
A user can display their own trust score for a login session.

=== Show Dynamic Authorization trust score components
You can display each component of the configured trust score and their weights.

== Configure a custom trust score provider
If you already receive scoring methods from an external trust score provider, you can add the custom provider to the Dynamic Authorization configuration.


=== Add a custom trust score provider
You can add a custom trust score provider.

.Before you begin
* The custom trust score provider must return a JSON response. The following syntax requirements must be met:
** The field that returns the trust score must be a scalar field and not an element of an array.
** The field that returns the trust score can be a nested field, e.g. `trust_score.value`.
** There must be a field within the JSON response that returns a numeric trust score. If this is not natively available, the customer can write a wrapper script to return this value.
* The value can be either a trust score or a risk score. The difference is that the trust score is in ascending order with a higher score denoting a higher trust level, while the risk score is in descending order. For example, a trust score of 90 for a score range of 0 to 100 indicates that the score is very trustworthy and likely to result in an "allow" without additional challenge, while a risk score of 90 for a score range of 0 to 100 indicates high risk and likely to result in a "deny" without an additional challenge.
* The custom trust score provider must be be accessible via the REST API.
* The custom trust score provider must be configurable using one of the supported parameters. Custom trust score providers that require configuration that is not in the supported parameter list are not supported.

=== Use custom trust score provider tags

== Configure restricted commands

=== Add a restricted command

=== Remove a restricted command

== Configure Dynamic Authorization groups

=== Add a Dynamic Authorization group

=== Remove a Dynamic Authorization group


