---
permalink: authentication/create-svm-computer-account-domain-task.html
sidebar: sidebar
keywords: create, svm, computer, account, domain, cifs server
summary: "If you have not configured a SMB server for a data SVM, you can use the vserver active-directory create command to create a computer account for the SVM on the domain."
---
= Create an SVM computer account on the domain
:icons: font
:imagesdir: ../media/

[.lead]
If you have not configured an SMB server for a data SVM, you can use the `vserver active-directory create` command to create a computer account for the SVM on the domain.

.What you'll need

You must be a cluster or SVM administrator to perform this task.

.About this task

After you enter the `vserver active-directory create` command, you are prompted to provide the credentials for an AD user account with sufficient privileges to add computers to the specified organizational unit in the domain. The password of the account cannot be empty.

.Step

. Create a computer account for an SVM on the AD domain:
+
`vserver active-directory create -vserver _SVM_name_ -account-name _NetBIOS_account_name_ -domain _domain_ -ou _organizational_unit_`
+
For complete command syntax, see the link:config-worksheets-reference.html[worksheet].
+
The following command creates a computer account named `ADSERVER1` on the domain `example.com` for the SVM `engData`. You are prompted to enter the AD user account credentials after you enter the command.
+
----
cluster1::>vserver active-directory create -vserver engData -account-name ADSERVER1 -domain example.com

In order to create an Active Directory machine account, you must supply the name and password of a Windows account with sufficient privileges to add computers to the "CN=Computers" container within the "example.com" domain.

Enter the user name: Administrator

Enter the password:
----

// 4 FEB 2022, BURT 1451789 