---
permalink: authentication/enable-ssh-public-key-accounts-task.html
sidebar: sidebar
keywords: enable, ssh, public key, accounts
summary: "You can use the security login create command to enable administrator accounts to access an admin or data SVM with an SSH public key."
---
= Enable SSH public key accounts
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `security login create` command to enable administrator accounts to access an admin or data SVM with an SSH public key.

.About this task

* You must associate the public key with the account before the account can access the SVM.
+
xref:manage-public-key-authentication-concept.adoc[Associating a public key with a user account]
+
You can perform this task before or after you enable account access.

* If you are unsure of the access control role that you want to assign to the login account, you can use the `security login modify` command to add the role later.

If you want to enable FIPS mode on your cluster, existing SSH public key accounts without the supported key algorithms must be reconfigured with a supported key type.  The accounts should be reconfigured before you enable FIPs or the administrator authentication will fail. 

include::../_include/supported-ssh-key-types.adoc[]

.Before you begin

You must be a cluster administrator to perform this task.

.Step

. Enable local administrator accounts to access an SVM using an SSH public key:
+
`security login create -vserver _SVM_name_ -user-or-group-name user_or_group_name -application _application_ -authmethod _authentication_method_ -role _role_ -comment _comment_`
+
For complete command syntax, see the link:config-worksheets-reference.html[worksheet].
+
The following command enables the SVM administrator account `svmadmin1` with the predefined `vsadmin-volume` role to access the SVM``engData1`` using an SSH public key:
+
----
cluster1::>security login create -vserver engData1 -user-or-group-name svmadmin1 -application ssh -authmethod publickey -role vsadmin-volume
----

.After you finish

If you have not associated a public key with the administrator account, you must do so before the account can access the SVM.

xref:manage-public-key-authentication-concept.adoc[Associating a public key with a user account]

// 2023, Mar 17, Jira 953
// 2022-04-01, BURT 1448836
// 2022-01-17, BURT 1448836
// 2022 Feb 04, BURT 1453350
