---
permalink: authentication/enable-password-account-access-task.html
sidebar: sidebar
keywords: enable, password, account, access
summary: "You can use the security login create command to enable administrator accounts to access an admin or data SVM with a password. You are prompted for the password after you enter the command."
---
= Enable password account access
:icons: font
:imagesdir: ../media/

[.lead]
You can use the `security login create` command to enable administrator accounts to access an admin or data SVM with a password. You are prompted for the password after you enter the command.

.About this task

If you are unsure of the access control role that you want to assign to the login account, you can use the `security login modify` command to add the role later.

.Before you begin

You must be a cluster administrator to perform this task.

.Step

. Enable local administrator accounts to access an SVM using a password:
+
`security login create -vserver _SVM_name_ -user-or-group-name _user_or_group_name_ -application _application_ -authmethod _authentication_method_ -role _role_ -comment _comment_`
+
Learn more about `security login create` in the link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html[ONTAP command reference^].
+
The following command enables the cluster administrator account `admin1` with the predefined `backup` role to access the admin SVM``engCluster`` using a password. You are prompted for the password after you enter the command.
+
----
cluster1::>security login create -vserver engCluster -user-or-group-name admin1 -application ssh -authmethod password -role backup
----

// 2025 Feb 20, ONTAPDOC-2758