---
permalink: authentication/index.html
sidebar: sidebar
keywords: decide, overview, administrator, authentication, rbac, role-based, access, control
summary: "This content describes how to enable login accounts for ONTAP cluster administrators and storage virtual machine (SVM) administrators, and how to use role-based access control (RBAC) to define the capabilities of administrators."
---
= Administrator Authentication and RBAC overview
:icons: font
:imagesdir: ../media/

[.lead]
This content describes how to enable login accounts for cluster administrators and storage virtual machine (SVM) administrators, and how to use role-based access control (RBAC) to define the capabilities of administrators.

You should use this content if you want to enable login accounts and RBAC in the following way:

* You want to use the ONTAP command-line interface (CLI), not ONTAP System Manager or an automated scripting tool.
* You want to use best practices, not explore every available option.
* You do not want to read a lot of conceptual background.
* You are not using SNMP to collect information about the cluster.

If this content is not suitable for your situation, you should see the following documentation instead:

* https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands]
* https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help/GUID-DF04A607-30B0-4B98-99C8-CB065C64E670.html[Cluster management using System Manager]
* https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61550[NetApp Documentation: OnCommand Workflow Automation (current releases)]
