---
permalink: authentication/manage-public-key-authentication-concept.html
sidebar: sidebar
keywords: associate, public key, administrator account
summary: "For SSH public key authentication, you must associate the public key with an administrator account before the account can access the SVM. You can use the security login publickey create command to associate a key with an administrator account."
---
= Associate a public key with an administrator account
:icons: font
:imagesdir: ../media/

[.lead]
For SSH public key authentication, you must associate the public key with an administrator account before the account can access the SVM. You can use the `security login publickey create` command to associate a key with an administrator account.

.What you'll need

* You must have generated the SSH key.
* You must be a cluster or SVM administrator to perform this task.

.About this task

If you authenticate an account over SSH with both a password and an SSH public key, the account is authenticated first with the public key.

.Step

. Associate a public key with an administrator account:
+
`security login publickey create -vserver SVM_name -username user_name -index index -publickey certificate -comment comment`
+
For complete command syntax, see the link:config-worksheets-reference.html[worksheet].
+
link:config-worksheets-reference.html[Associating a public key with a user account]
+
The following command associates a public key with the SVM administrator account `svmadmin1` for the SVM ``engData1``. The public key is assigned index number 5.
+
----
cluster1::>security login publickey create -vserver engData1 -username svmadmin1 -index 5 -publickey
"ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAspH64CYbUsDQCdW22JnK6J
/vU9upnKzd2zAk9C1f7YaWRUAFNs2Qe5lUmQ3ldi8AD0Vfbr5T6HZPCixNAIza
FciDy7hgnmdj9eNGedGr/JNrftQbLD1hZybX+72DpQB0tYWBhe6eDJ1oPLob
ZBGfMlPXh8VjeU44i7W4+s0hG0E=tsmith@publickey.example.com"
----
