---
sidebar: sidebar
permalink: authentication/oauth2-groups.html
keywords: oauth 2.0, oauth2, identity mapping, group uuid, group name, group mapping, external roles, role mapping
summary: "ONTAP provides several options for configuring groups based on your authorization server. The groups can then be mapped to roles which are used by ONTAP to determine access."
---

= Working with groups
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
ONTAP provides several options for configuring groups based on your authorization server. The groups can then be mapped to roles which are used by ONTAP to determine access.

== How groups are identified

When you configure a group at an authorization server, it is identified and carried in an OAuth 2.0 access token using either a name or UUID. If multiple groups are included in an access token, ONTAP will attempt to use each one until there is a match. You need to be aware of how your authorization handles groups before configuring ONTAP.

[CAUTION]
The example access tokens are presented for illustration purposes only. You should not attempt to use these tokens in your security environment.

=== Group names

Many authorization servers identify and represent groups using a name. Here is an example of a token generated by Active Directory Federation Service (ADFS) which contains several groups. See <<Manage groups with names>> for more information.

[source,json]
{
  "aud": "microsoft:identityserver:3dcc3b2b-8e47-44ba-7e32-d73c3b76ee33",
  "iss": "http://t01.dev.netapp.com/adfs/services/trust",
  "iat": 1688144115,
  "exp": 1688147715,
  "sub": "User_Test@NICAD5.COM",
  "group": [
    "NICAD5\\Domain Users",
    "NICAD5\\Development Group",
    "NICAD5\\Production Group"
  ],
  "apptype": "Confidential",
  "appid": "3dcc3b2b-8e47-44ba-7e32-d73c3b76ee33",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "auth_time": "2023-08-30T16:55:15.037Z",
  "ver": "1.0"
}

=== Group UUIDs

Some authorization servers identify and represent groups using a UUID. Here is an example of a token generated by Microsoft Entra ID which contains several groups. See <<Manage groups with UUIDs>> for more information.

[source,json]
{
  "aud": "ab158532-2aab-325c-b5f9-fd90f3d32663",
  "iss": "https://sts.windows.net/7db1eb8c-4711-4bf5-dd73-411197e20dc2/",
  "iat": 1689196499,
  "nbf": 1689196499,
  "exp": 1689201253,
  "acr": "1",
  "aio": "SXKAy/8TBBBBMtsASE0oPqLp1qpJN2V5+Rzq27oBXxyvYO1nWkoXKxx1FG8GJI2UIhkJ+CxDGw/y",
  "amr": [
    "pwd"
  ],
  "appid": "ab158532-2aab-325c-b5f9-fd90f3d32663",
  "appidacr": "1",
  "groups": [
    "68c4c5b0-daeb-4e66-8b1c-cd395474a118",
    "a8a58fc2-a7b6-4cb7-a511-59bd831831c1"   ],
  "ipaddr": "10.10.10.10",
  "name": "admin12 with group membership",
  "oid": "8f6de82b-325a-470d-9c1c-8edb05b74139",
  "preferred_username": "admin2@netappsecdev.onmicrosoft.com",
  "rh": "0.Ab0AjOunbFc49Uu6XAMyl-INwjKFRu6rKtVDtfn9kPPTSIG9AH4.",
  "sub": "I_gyDbMsTIO4HUH0uQQWXaP96vGNgt0JR_GbvrmkUug",
  "tid": "6ca7eb8c-3857-4bf5-ba5c-033297e20dc2",
  "unique_name": "admin12@netappsecdev.onmicrosoft.com",
  "upn": "admin2@netappsecdev.onmicrosoft.com",
  "uti": "5xETkFuuAEakdnSsbjgHAA",
  "ver": "1.0"
}

== Manage groups with names

If your authorization server uses names to identify groups, you need to make sure the group is defined to ONTAP. 

Here's an example of a CLI command defining a group to ONTAP. If you're already using Active Directory or LDAP to configure your groups, you might already have the group defined.

.Example
----
security login create -user-or-group-name "NICAD5\\Domain Users" -application http -authentication-method domain -role admin
----

[NOTE]
You can also configure this feature using the ONTAP REST API. See the https://docs.netapp.com/us-en/ontap-automation/[ONTAP Automation^] documentation site for more information.

== Manage groups with UUIDs

If your authorization server represents groups using UUID values, you need to perform a two-step configuration before using the groups. Beginning with ONTAP 9.16.1, two mapping features are available and have been tested with Microsoft Entra ID.

[NOTE]
You can also configure these features using the ONTAP REST API. See the https://docs.netapp.com/us-en/ontap-automation/[ONTAP Automation^] documentation site for more information.

.Related information

* https://docs.netapp.com/us-en/ontap-cli/[ONTAP CLI commands^]

=== Map a group UUID to a group name

If you're using an authorization server that represents groups using UUID values, you need to map the group UUIDs to group names. The primary ONTAP CLI operations are described below. You need to be at the ONTAP *admin* privilege level to issue the commands.

==== Create

You can define a new group mapping configuration with the `security login group create` command. The group name should match the name used at the authorization server.

.Parameters
The parameters used to create a group mapping are described below.

[cols="30,70"*,options="header"]
|===
|Parameter
|Description
|`vserver`
|Optionally specifies the name of the SVM (vserver) the group is associated with. If omitted, the group is associated with the ONTAP cluster.
|`name`
|The unique name of the group that ONTAP will use.
|`type`
|This value indicates the identity provider the group originates from.
|`uuid`
|Specifies the universally unique identifier of the group as provided by the authorization server.
|===

.Example
----
security login group create -vserver ontap-cls-1 -name IAM_Dev -type entra -uuid 68c4c5b0-daeb-4e66-8b1c-cd395474a118
----

After creating the group, a unique read-only integer identifier is generated for the group.

==== Additional CLI operations

The command supports several additional operations, including:

* Show
* Modify
* Delete

You can use the `show` option to retrieve the unique group ID generated for a group. Refer to the ONTAP commands reference documentation or ONTAP CLI man pages for more information.

=== Map a group UUID to a role

If you're using an authorization server that represents groups using UUID values, you can map the group to a role. The primary ONTAP CLI operations are described below. Also, you need to be at the ONTAP *admin* privilege level to issue the commands.

[NOTE]
You need to first <<Map a group UUID to a group name>> and retrieve the unique integer ID generated for the group. You'll need the ID to map the group to a role.

==== Create

You can define a new role mapping with the `security login group role-mapping create` command.

.Parameters
The parameters used to map a group to a role are described below.

[cols="30,70"*,options="header"]
|===
|Parameter
|Description
|`group-id`
|Specifies the unique ID generated for the group using the command `security login group create`.
|`role`
|The name of the ONTAP role the group is mapped to.
|===

.Example
----
security login group role-mapping create -group-id 1 -role admin
----

==== Additional CLI operations

The command supports several additional operations, including:

* Show
* Modify
* Delete

Refer to the ONTAP commands reference documentation or ONTAP CLI man pages for more information.

// DMP - November 5 2024 - ONTAPDOC-2163
