---
permalink: authentication/reset-totp-configuration-task.html
sidebar: sidebar
keywords: enable, ssh, multifactor authentication, mfa, hardware authentication device
summary: "To protect your account security, if your TOTP secret key is compromised or lost, you should disable it and create a new one."
---
= Reset TOTP secret key
:icons: font
:imagesdir: ../media/

[.lead]
To protect your account security, if your TOTP secret key is compromised or lost, you should disable it and create a new one.

== Reset TOTP if your key is compromised

If your TOTP secret key is compromised, but you still have access to it, you can remove the compromised key and create a new one.   

. Log in to your user account with your user password or SSH public key and your compromised TOTP secret key. 

. Remove the compromised TOTP secret key:
+
[source,cli]
----
security login totp delete -vserver <svm_name> -username <account_username>
----

. Create a new TOTP secret key:
+
[source,cli]
----
security login totp create -vserver <svm_name> -username <account_username>
----

. Verify that the TOTP configuration is enabled on your account:
+
[source,cli]
----
security login totp show -vserver <svm_name> -username <account_username>
----

== Reset TOTP if your key is lost

If your TOTP secret key is lost, contact your storage administrator to link:disable-totp-secret-key-task.html[have the key disabled]. After your key is disabled, you can use your first authentication method to log in and configure a new TOTP.

.Before you begin:

The TOTP secret key must be disabled by a storage administrator. 
If you do not have a storage administrator account, contact your storage administrator to have the key disabled.  

.Steps

. After the TOTP secret is disabled by a storage administrator, use your primary authentication method to log in into your local account.

. Create a new TOTP secret key:
+
[source,cli]
----
security login totp create -vserver <svm_name> -username <account_username >
----

. Verify that the TOTP configuration is enabled on your account:
+
[source,cli]
----
security login totp show -vserver <svm_name> -username <account_username>
----


// 2023 May 02, Jira 912